import{test,expect}from'@playwright/test';import path from'node:path';import{parseGcode}from'../../shared/gcode.js';
test('browser brim-ear editor exports points in the native object frame and generates localized adhesion',async({page,request})=>{
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Choose a 3D model').setInputFiles(path.resolve('tests/fixtures/cube.stl'));
 // The ordinary import centers this 20 mm cube on the 250 by 210 mm MK4 bed.
 await page.getByRole('button',{name:'Brim ears',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Brim ears',exact:true});await dialog.getByRole('button',{name:'Add brim ear'}).click();
 const x=Number(await dialog.getByLabel('Ear 1 X',{exact:true}).inputValue()),y=Number(await dialog.getByLabel('Ear 1 Y',{exact:true}).inputValue());
 await dialog.getByRole('button',{name:'Apply brim ears'}).click();
 const submitting=page.waitForResponse(response=>response.url().endsWith('/api/jobs/project')&&response.request().method()==='POST');await page.getByRole('button',{name:'Slice model',exact:true}).click();const response=await submitting;expect(response.status(),await response.text()).toBe(202);const job=await response.json();
 await expect(page.getByText('Ready to print')).toBeVisible({timeout:90000});const code=await(await request.get(`/api/jobs/${job.id}/download`)).text();expect(code).toMatch(/generated by OrcaSlicer/i);const brim=parseGcode(code).segments.filter(segment=>segment.kind==='extrusion'&&/brim/i.test(segment.feature));expect(brim.length).toBeGreaterThan(20);for(const segment of brim){expect(Math.abs(segment.end[0]-x)).toBeLessThan(5.1);expect(Math.abs(segment.end[1]-y)).toBeLessThan(5.1);expect(segment.end[2]).toBeLessThan(.3);}
});
