import {test,expect} from '@playwright/test';
import {Matrix4,Vector3} from 'three';
import {observeGpu,gpuIdle} from '../fixtures/gpu-observation.js';
import {frame,cameraDrag} from '../fixtures/camera-browser.js';
import {nativePreviewRangeState} from '../../shared/native-preview-range.js';
const axes=[0,1,2,4,5,6,8,9,10];
const sameDirection=(a,b)=>axes.forEach(i=>expect(b.matrixWorldInverse[i]).toBeCloseTo(a.matrixWorldInverse[i],10));
function visiblePathsFit(data,state,f){const view=new Matrix4().fromArray(f.matrixWorldInverse),projection=new Matrix4().fromArray(f.projectionMatrix);let x=0,y=0,minZ=1,maxZ=-1;for(const i of state.segmentIds)for(const v of [data.vertices[i],data.vertices[i+1]]){const p=new Vector3(v[0],v[2],-v[1]).applyMatrix4(view).applyMatrix4(projection);x=Math.max(x,Math.abs(p.x));y=Math.max(y,Math.abs(p.y));minZ=Math.min(minZ,p.z);maxZ=Math.max(maxZ,p.z);}expect(state.segmentIds.length).toBeGreaterThan(100);expect(x).toBeLessThan(.92);expect(y).toBeLessThan(.92);expect(minZ).toBeGreaterThan(-1);expect(maxZ).toBeLessThan(1);}

test('actual native Preview Fit preserves viewing axes and contains the selected native path range without reslicing',async({page,request},info)=>{
 expect((await(await request.get('/api/health')).json()).engine.version).toMatch(/^OrcaSlicer-2\.4\.2/);await observeGpu(page);let slices=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/jobs/project'))slices++;});
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles(new URL('../fixtures/native-gui-cube-2.4.2.3mf',import.meta.url).pathname);await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();
 const prepare=page.getByRole('img',{name:'Interactive 3D model view'});await gpuIdle(page,prepare);await page.locator('.scene-views').getByRole('button',{name:'Right',exact:true}).click();await gpuIdle(page,prepare);await cameraDrag(page,prepare,'left');const start=await frame(prepare);await page.locator('.scene-views').getByRole('button',{name:'Fit',exact:true}).click();await gpuIdle(page,prepare);sameDirection(start,await frame(prepare));
 const processing=page.waitForResponse(r=>r.url().endsWith('/native-preview'));await page.getByRole('button',{name:'Slice model',exact:true}).click();await expect(page.getByText('Ready to print')).toBeVisible({timeout:90000});const processed=await processing;expect(processed.status()).toBe(200);const data=await processed.json();expect(data.engine.version).toBe('2.4.2');
 const canvas=page.getByRole('img',{name:'3D G-code toolpaths'});await expect(canvas).toHaveAttribute('data-processor','native');await gpuIdle(page,canvas);await cameraDrag(page,canvas,'left');await cameraDrag(page,canvas,'middle');const before=await frame(canvas),range=await canvas.getAttribute('data-native-range');await page.getByRole('button',{name:'Fit toolpaths',exact:true}).click();await gpuIdle(page,canvas);sameDirection(before,await frame(canvas));visiblePathsFit(data,nativePreviewRangeState(data),await frame(canvas));await expect(canvas).toHaveAttribute('data-native-range',range);
 const first=20,last=40;await page.getByLabel('First preview layer').fill(String(first));await page.getByLabel('Last preview layer').fill(String(last));await gpuIdle(page,canvas);await page.getByRole('button',{name:'Fit toolpaths',exact:true}).click();await gpuIdle(page,canvas);sameDirection(before,await frame(canvas));visiblePathsFit(data,nativePreviewRangeState(data,{firstLayer:first,lastLayer:last}),await frame(canvas));expect(slices).toBe(1);await page.screenshot({path:info.outputPath('native-fit-preserved-view.png')});
});
