import { test, expect } from "@playwright/test";
import { readFile, writeFile } from "node:fs/promises";
const cube = new URL("../fixtures/cube.stl", import.meta.url).pathname;

test("custom printer, selected material, layer height and rotated STL reach installed OrcaSlicer", async ({
  page,
  request,
}, testInfo) => {
  const health = await (await request.get("/api/health")).json();
  expect(health.engine.version).toMatch(/^OrcaSlicer-2\.4\.2\b/);
  expect(health.slicer).not.toMatch(/fake|fixture/);
  await page.goto("/");
  await expect(page.getByLabel("Layer height", { exact: true })).toBeEnabled();
  await page
    .getByRole("button", { name: "＋ Add printer", exact: true })
    .click();
  const dialog = page.getByRole("dialog", { name: "Add printer" }),
    name = `Core workflow printer ${Date.now()}`;
  await dialog.getByLabel("Create a custom printer").check();
  await dialog.getByLabel("Printer name", { exact: true }).fill(name);
  await dialog
    .getByRole("button", { name: "Create printer", exact: true })
    .click();
  await expect(dialog).not.toBeVisible();
  await expect(
    page.getByLabel("Printer", { exact: true }).locator("option:checked"),
  ).toHaveText(name);
  const options = await page
    .getByLabel("Filament", { exact: true })
    .locator("option")
    .evaluateAll((items) =>
      items.map((o) => ({ id: o.value, name: o.textContent })),
    );
  const material =
    options.find((item) => /Generic PETG/i.test(item.name)) ||
    options.find((item) => /PETG/i.test(item.name)) ||
    options.at(-1);
  await page.getByLabel("Filament", { exact: true }).selectOption(material.id);
  await expect(page.getByLabel("Layer height", { exact: true })).toBeEnabled();
  await page.getByLabel("Layer height", { exact: true }).fill("0.24");
  await page.getByLabel("Choose a 3D model").setInputFiles(cube);
  await expect(page.locator(".scene-object-row")).toHaveCount(1);
  await page.getByRole("button", { name: "Rotate", exact: true }).click();
  await page
    .getByRole("button", { name: "Rotate X to 90°", exact: true })
    .click();
  await page
    .getByRole("button", { name: "Rotate Z to 270°", exact: true })
    .click();
  await page.screenshot({
    path: testInfo.outputPath("core-native-prepare.png"),
  });
  const saved = page.waitForEvent("download");
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  const project = JSON.parse(
    await readFile(await (await saved).path(), "utf8"),
  );
  expect(project.objects[0].rotation).toEqual([90, 0, 270]);
  expect(Number(project.overrides.layer_height)).toBe(0.24);
  expect(project.ids.filamentId).toBe(material.id);
  const response = page.waitForResponse(
    (r) =>
      /\/api\/jobs(?:\/project)?$/.test(r.url()) &&
      r.request().method() === "POST",
  );
  await page.getByRole("button", { name: "Slice model", exact: true }).click();
  const posted = await response;
  expect(posted.status()).toBe(202);
  const job = await posted.json();
  await expect(page.getByText("✓ Ready to print", { exact: true })).toBeVisible(
    { timeout: 90000 },
  );
  const gcode = await (
    await request.get(`/api/jobs/${job.id}/download`)
  ).text();
  expect(gcode).toMatch(/generated by OrcaSlicer/);
  expect(gcode).toMatch(/^G1 .*E[0-9]/m);
  expect(gcode).toMatch(/^; layer_height = 0\.24$/m);
  expect(gcode.includes(name)).toBe(true);
  expect(gcode.includes(material.name)).toBe(true);
  await writeFile(testInfo.outputPath("core-workflow.gcode"), gcode);
});
