import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';
async function chooseH2D(page,request){const listing=await(await request.get('/api/presets')).json(),printer=listing.printers.find(item=>item.name==='Bambu Lab H2D 0.4 nozzle');expect(printer).toBeTruthy();await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Printer',{exact:true}).selectOption(printer.id);await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();return printer;}
async function speed(page){await page.getByLabel('Search profile settings',{exact:true}).fill('filament_max_volumetric_speed');return page.getByLabel('Max volumetric speed (filament_max_volumetric_speed) 1',{exact:true});}
async function exportedPreset(page){const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export saved preset',exact:true}).click();return JSON.parse(await readFile(await(await pending).path(),'utf8'));}
async function savePreset(page,{asNew=false}={}){
 const method=asNew?'POST':'PUT',pending=page.waitForResponse(response=>{const pathname=new URL(response.url()).pathname;return response.request().method()===method&&(asNew?pathname==='/api/presets/custom':/^\/api\/presets\/custom\/[^/]+$/.test(pathname));},{timeout:60000});
 await page.getByRole('button',{name:asNew?'Save as new preset':'Save changes',exact:true}).click();const response=await pending;expect(response.status(),await response.text()).toBe(asNew?201:200);const saved=await response.json();expect(saved.nativeInheritanceMode).toBe(true);return saved;
}
test('real native filament editor switches explicit variants and saves/exports inactive values unchanged',async({page,request},info)=>{
 await chooseH2D(page,request);await page.getByRole('button',{name:'Edit filament preset',exact:true}).click();await expect(page.getByLabel('Edit nozzle 1 volume variant')).toHaveValue('Standard');const input=await speed(page);await expect(input).toHaveValue('25');const row=page.locator('[data-profile-setting="filament_max_volumetric_speed"]');await expect(row.getByRole('button',{name:'Add entry',exact:true})).toHaveCount(0);await expect(row).toContainText('Material 1 → Nozzle 1 · Standard');
 await page.getByLabel('Edit nozzle 1 volume variant').selectOption('High Flow');await expect(input).toHaveValue('40');await input.fill('43');await expect(page.getByLabel('Edit nozzle 1 volume variant')).toBeDisabled();const name=`Browser variant ${Date.now()}`;await page.getByLabel('Preset name').fill(name);await savePreset(page,{asNew:true});await expect(page.getByRole('dialog',{name:'Filament preset editor'})).not.toBeVisible();await expect(page.getByLabel('Filament',{exact:true})).toContainText(name);
 await page.getByRole('button',{name:'Edit filament preset',exact:true}).click();await expect(await speed(page)).toHaveValue('25');let saved=await exportedPreset(page);expect(saved.filament_max_volumetric_speed).toEqual(['25','43']);await page.getByLabel('Edit nozzle 1 volume variant').selectOption('High Flow');await expect(await speed(page)).toHaveValue('43');await page.screenshot({path:info.outputPath('native-custom-high-flow.png')});
 await page.getByRole('button',{name:'Reset Max volumetric speed (filament_max_volumetric_speed) to source',exact:true}).click();await expect(input).toHaveValue('40');await savePreset(page);await expect(page.getByRole('dialog',{name:'Filament preset editor'})).not.toBeVisible();await page.getByRole('button',{name:'Edit filament preset',exact:true}).click();saved=await exportedPreset(page);expect(saved.inherits).toBeTruthy();expect(saved.filament_max_volumetric_speed).toBeUndefined();await expect(await speed(page)).toHaveValue('25');await page.getByLabel('Edit nozzle 1 volume variant').selectOption('High Flow');await expect(await speed(page)).toHaveValue('40');
});
test('real native machine editor labels motion modes and preserves all four stored nozzle variants',async({page,request},info)=>{
 await chooseH2D(page,request);await page.getByRole('button',{name:'Edit printer preset',exact:true}).click();await expect(page.getByLabel('Edit nozzle 2 volume variant')).toBeEnabled();await page.getByLabel('Edit nozzle 2 volume variant').selectOption('High Flow');await page.getByLabel('Search profile settings',{exact:true}).fill('machine_max_speed_x');const row=page.locator('[data-profile-setting="machine_max_speed_x"]');await expect(row).toContainText('Nozzle 2 · High Flow · Normal');await expect(row).toContainText('Nozzle 2 · High Flow · Silent');await expect(row.getByRole('spinbutton')).toHaveCount(4);await row.getByRole('spinbutton').nth(2).fill('450');await row.getByRole('spinbutton').nth(3).fill('350');await page.getByLabel('Preset name').fill(`Browser machine ${Date.now()}`);await savePreset(page,{asNew:true});await expect(page.getByRole('dialog',{name:'Printer preset editor'})).not.toBeVisible();await page.getByRole('button',{name:'Edit printer preset',exact:true}).click();const saved=await exportedPreset(page);expect(saved.machine_max_speed_x).toEqual(['1000','1000','1000','1000','1000','1000','450','350']);await page.getByLabel('Edit nozzle 2 volume variant').selectOption('High Flow');await page.getByLabel('Search profile settings',{exact:true}).fill('machine_max_speed_x');await expect(row.getByRole('spinbutton').nth(2)).toHaveValue('450');await expect(row.getByRole('status')).toHaveCount(0);await expect(page.getByRole('dialog',{name:'Printer preset editor'}).getByRole('status').filter({hasText:'resolves some slicing motion limits differently'})).toContainText('resolves some slicing motion limits differently');await page.screenshot({path:info.outputPath('native-machine-mode-preservation.png')});
});
import{emptyProject,serializeProject}from'../../shared/project.js';
test('editing the second material slot uses its own physical nozzle and preserves the first slot variant',async({page,request},info)=>{
 const printer=await chooseH2D(page,request),choices=await(await request.get(`/api/presets?printerId=${printer.id}`)).json(),ids=choices.defaults,name=`Second slot material ${Date.now()}`;
 const created=await request.post('/api/presets/custom',{data:{type:'filament',name,baseId:ids.filamentId,compatiblePrinterIds:[ids.printerId],selection:ids,nativeEditor:true,projectSettings:{nozzle_volume_type:['Standard','High Flow'],filament_map:['1']},settings:{filament_max_volumetric_speed:['27']}}});expect(created.status(),await created.text()).toBe(201);const saved=await created.json();
 const project={...emptyProject(),name:'Separate material edit contexts',useEmbeddedSettings:false,nativeSettings:{nozzle_volume_type:['High Flow','Standard'],filament_map:['2','1']},ids:{...ids,filamentId:saved.id},filamentIds:[saved.id,saved.id],projectOverrides:{nozzle_volume_type:['Standard','High Flow'],filament_map:['1','2'],filament_map_mode:'Manual'}};
 await page.getByLabel('Open Orca Web project').setInputFiles({name:'material-contexts.orca-web.json',mimeType:'application/json',buffer:Buffer.from(serializeProject(project))});await expect(page.getByRole('button',{name:'Edit filament slot 2 preset',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Edit filament slot 2 preset',exact:true}).click();const input=await speed(page);await expect(input).toHaveValue('40');await expect(page.locator('[data-profile-setting="filament_max_volumetric_speed"]')).toContainText('Material 2 → Nozzle 2 · High Flow');await input.fill('44');await savePreset(page);await expect(page.getByRole('dialog',{name:'Filament preset editor'})).not.toBeVisible();
 await page.getByRole('button',{name:'Edit filament preset',exact:true}).click();await expect(await speed(page)).toHaveValue('27');const exported=await exportedPreset(page);expect(exported.filament_max_volumetric_speed).toEqual(['27','44']);await page.screenshot({path:info.outputPath('second-slot-variant-preservation.png')});
});
