import {test,expect} from '@playwright/test';
import {observeFrameClears,exerciseCappedCamera,cappedIdle,frameClears} from '../fixtures/fps-observation.js';
import {preferences} from '../fixtures/camera-browser.js';
test('installed-native Preview obeys the graphics frame cap without changing native paths or submitting a new slice',async({page,request},info)=>{
 expect((await(await request.get('/api/health')).json()).engine.version).toMatch(/^OrcaSlicer-2\.4\.2/);await observeFrameClears(page);let slices=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/jobs/project'))slices++;});
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await preferences(page,async dialog=>{await dialog.getByLabel('FPS cap',{exact:true}).fill('4');await dialog.getByLabel('FPS cap',{exact:true}).press('Enter');await dialog.getByRole('button',{name:'Increase FPS cap'}).click();await expect(dialog.getByLabel('FPS cap',{exact:true})).toHaveValue('5');await dialog.getByLabel('Show FPS overlay').check();});
 await page.getByLabel('Open Orca Web project').setInputFiles(new URL('../fixtures/native-gui-cube-2.4.2.3mf',import.meta.url).pathname);await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Slice model',exact:true}).click();await expect(page.getByText('Ready to print')).toBeVisible({timeout:90000});const canvas=page.getByRole('img',{name:'3D G-code toolpaths'});await expect(canvas).toHaveAttribute('data-processor','native');await cappedIdle(page,canvas,5);
 const range=await canvas.getAttribute('data-native-range'),volumes=await canvas.getAttribute('data-visible-volumes');expect(Number(volumes)).toBeGreaterThan(100);const times=await exerciseCappedCamera(page,canvas,5,{steps:85});await cappedIdle(page,canvas,5);await expect(page.getByLabel('Viewport FPS',{exact:true})).toBeVisible();await expect(canvas).toHaveAttribute('data-native-range',range);await expect(canvas).toHaveAttribute('data-visible-volumes',volumes);expect(slices).toBe(1);await info.attach('native-capped-frame-clears',{body:JSON.stringify(times),contentType:'application/json'});await page.screenshot({path:info.outputPath('native-preview-fps.png')});
 await preferences(page,async dialog=>{await dialog.getByLabel('FPS cap',{exact:true}).fill('0');await dialog.getByLabel('FPS cap',{exact:true}).press('Enter');await dialog.getByLabel('Show FPS overlay').uncheck();});await expect(page.getByLabel('Viewport FPS',{exact:true})).toBeHidden();const before=(await frameClears(canvas)).length;await page.getByLabel('Last preview layer').fill('30');await expect.poll(async()=>(await frameClears(canvas)).length).toBeGreaterThan(before);expect(slices).toBe(1);
});
