import {routeNativeReadyJobHotend} from '../fixtures/native-preview-job-hotend.js';
import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{createHash}from'node:crypto';import path from'node:path';import{createNativeGcodeWorker}from'../../server/native-gcode-worker.js';import{nativeScalarModes,nativeScalarRangeKey,nativeVertexAttributes}from'../../shared/native-preview-adapter.js';import{nativePreviewRangeState,nativeDefaultOptions}from'../../shared/native-preview-range.js';
async function nativeData(){const text=await readFile(path.resolve('tests/fixtures/native-gui-shrink98-2.4.2.gcode'),'utf8'),worker=createNativeGcodeWorker({binary:process.env.ORCA_GCODE_WORKER_BIN||path.resolve(process.env.ORCA_NATIVE_CACHE_DIR||'.native-cache','gcode-build','orca-gcode-worker'),resourcesDir:process.env.ORCA_RESOURCES_DIR||'/Applications/OrcaSlicer.app/Contents/Resources'});try{return{text,data:{...await worker.process(Buffer.from(text)),sourceSha256:createHash('sha256').update(text).digest('hex'),sourceBytes:Buffer.byteLength(text)}};}finally{await worker.shutdown();}}
async function openPreview(page,text,data){const errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await routeNativeReadyJobHotend(page,'native-scalars-proof');await page.route('**/api/jobs',route=>route.request().method()==='POST'?route.fulfill({status:202,json:{id:'native-scalars-proof',filename:'GUI cube.gcode',status:'ready'}}):route.continue());await page.route('**/api/jobs/native-scalars-proof/download',route=>route.fulfill({contentType:'text/plain',body:text}));await page.route('**/api/jobs/native-preview/capabilities',route=>route.fulfill({json:{available:true,engine:data.engine}}));await page.route('**/api/jobs/native-scalars-proof/native-preview',route=>route.fulfill({json:data}));await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Choose a 3D model').setInputFiles(path.resolve('tests/fixtures/cube.stl'));await page.getByRole('button',{name:'Slice model',exact:true}).click();const canvas=page.getByRole('img',{name:'3D G-code toolpaths'});await expect(canvas).toHaveAttribute('data-processor','native');return{canvas,errors};}
test('real native scalar modes update all four visibility ranges and retain raw native command values',async({page})=>{
 const{text,data}=await nativeData();expect(data.scalarRangesVersion).toBe(1);const{canvas,errors}=await openPreview(page,text,data),select=page.getByLabel('Toolpath color mode');
 // Restrict rendering while checking whole-file native ranges; range collection must not change with the visible layer.
 await page.getByLabel('First preview layer').fill('49');await page.getByLabel('Last preview layer').fill('49');
 for(const travels of[false,true])for(const wipes of[false,true]){await page.getByLabel('Show Travel markers or paths').setChecked(travels);await page.getByLabel('Show Wipe markers or paths').setChecked(wipes);for(const[mode,definition]of Object.entries(nativeScalarModes)){await select.selectOption(mode);await expect(canvas).toHaveAttribute('data-color-mode',mode);const expected=data.scalarRanges[nativeScalarRangeKey({travels,wipes})][mode];await expect.poll(async()=>{const range=JSON.parse(await canvas.getAttribute('data-scalar-range'));return{min:range.min,max:range.max,count:range.count,values:range.values,palette:range.palette};}).toEqual(expected);await expect(page.getByRole('list',{name:'Native scalar color legend'}).locator('li')).toHaveCount(expected.values.length);await expect(page.getByTestId('scalar-availability')).toContainText(definition.label.toLowerCase());await expect(canvas).toHaveAttribute('data-visible-fallback-lines','0');}}
 await page.getByLabel('First preview layer').fill('49');await page.getByLabel('Last preview layer').fill('49');const options={...nativeDefaultOptions,travels:true,wipes:true},state=nativePreviewRangeState(data,{firstLayer:49,lastLayer:49,options}),tickIndex=state.ticks.findIndex(tick=>data.vertices[tick.vertexIndex][11]===8);expect(tickIndex).toBeGreaterThanOrEqual(0);await page.getByLabel('Visible native commands').fill(String(tickIndex));const tick=state.ticks[tickIndex],attributes=nativeVertexAttributes(data,tick.vertexIndex);
 for(const mode of Object.keys(nativeScalarModes)){await select.selectOption(mode);await expect(canvas).toHaveAttribute('data-current-native-vertex',String(tick.vertexIndex));await expect(canvas).toHaveAttribute('data-current-source-line',String(tick.line));await expect(canvas).toHaveAttribute('data-current-scalar-value',String(attributes[mode]));}
 await page.getByLabel('Visible native commands').fill(String(state.ticks.length-1));await select.selectOption('actualSpeed');await page.getByRole('button',{name:'Fit toolpaths'}).click();await page.screenshot({path:test.info().outputPath('native-actual-speed.png')});expect(errors).toEqual([]);
});
test('older helper output keeps supported native modes and disables unavailable scalar modes',async({page})=>{
 const{text,data}=await nativeData();delete data.scalarRanges;delete data.scalarRangesVersion;const{canvas,errors}=await openPreview(page,text,data),select=page.getByLabel('Toolpath color mode');for(const key of Object.keys(nativeScalarModes))await expect(select.locator(`option[value="${key}"]`)).toHaveAttribute('disabled','');await select.selectOption('width');await expect(canvas).toHaveAttribute('data-color-mode','width');await expect(page.getByRole('list',{name:'Native scalar color legend'}).locator('li')).not.toHaveCount(0);expect(errors).toEqual([]);
});
