import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {importNative3MF} from '../../shared/native-project.js';
import {serializeProject} from '../../shared/project.js';
async function save(page){await page.getByRole('button',{name:'Project',exact:true}).click();const waiting=page.waitForEvent('download');await page.locator('.project-actions').getByRole('button',{name:'Save project',exact:true}).click();const p=JSON.parse(await readFile(await(await waiting).path(),'utf8'));await page.getByRole('button',{name:'Prepare',exact:true}).click();return p;}
for(const kind of ['text','SVG'])test(`actual native ${kind} attachment on imported native cube retains object identity and slices`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const project=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));project.useEmbeddedSettings=true;project.nativeWorkflow=true;const family=project.objects[0].native.instanceFamily;expect(family).toBeTruthy();
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles({name:'native-source.orca-web.json',mimeType:'application/json',buffer:Buffer.from(serializeProject(project))});await expect(page.locator('.scene-object-row')).toHaveCount(1);
 const original=await save(page);
 if(kind==='text'){
  await page.locator('.toolbar').getByRole('button',{name:'Text',exact:true}).click();const d=page.getByRole('dialog',{name:'Add native text'});await d.getByLabel('Native text content').fill('O');await d.getByLabel('Native line height (mm)').fill('5');await d.getByLabel('Native text operation').selectOption('emboss');await expect(d.getByRole('button',{name:'Add native text',exact:true})).toBeEnabled();await d.getByRole('button',{name:'Add native text',exact:true}).click();
 }else{
  await page.locator('.toolbar').getByRole('button',{name:'Native SVG',exact:true}).click();const d=page.getByRole('dialog',{name:'Add native SVG'});await d.getByLabel('Native SVG file').setInputFiles({name:'small.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><path d="M0 0H5V5H0Z"/></svg>')});await d.getByLabel('Native SVG operation').selectOption('emboss');await d.getByLabel('Native SVG depth (mm)').fill('1');await expect(d.getByRole('button',{name:'Add native SVG',exact:true})).toBeEnabled();await d.getByRole('button',{name:'Add native SVG',exact:true}).click();
 }
 const next=await save(page);expect(next.objects).toHaveLength(2);expect(next.objects.every(o=>o.native.instanceFamily===family)).toBe(true);expect(new Set(next.objects.map(o=>o.native.groupId)).size).toBe(1);
 await page.getByRole('button',{name:'Undo',exact:true}).click();expect((await save(page)).objects).toEqual(original.objects);await page.getByRole('button',{name:'Redo',exact:true}).click();expect((await save(page)).objects).toEqual(next.objects);
 await page.getByRole('button',{name:'Project',exact:true}).click();const waiting=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const restored=importNative3MF(await readFile(await(await waiting).path()));expect(restored.objects).toHaveLength(2);expect(new Set(restored.objects.map(o=>o.native.instanceFamily)).size).toBe(1);await page.getByRole('button',{name:'Prepare',exact:true}).click();await page.getByRole('button',{name:'Slice model',exact:true}).click();await expect(page.getByRole('link',{name:/Download G-code/})).toBeEnabled({timeout:90000});const download=page.waitForEvent('download');await page.getByRole('link',{name:/Download G-code/}).click();const code=await readFile(await(await download).path(),'utf8');expect(code).toContain('OrcaSlicer 2.4.2');expect(code.match(/^G[0123] /gm).length).toBeGreaterThan(500);expect(errors).toEqual([]);
});
