import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{createHash}from'node:crypto';import path from'node:path';import{createNativeGcodeWorker}from'../../server/native-gcode-worker.js';import{createPresetCatalog}from'../../server/presets.js';import{createNativeHotendService}from'../../server/hotend-assets.js';
test('actual native vendor mesh and provenance change with the immutable ready job, including older default and missing assets',async({page})=>{
 const profiles=path.join(process.env.ORCA_RESOURCES_DIR||'/Applications/OrcaSlicer.app/Contents/Resources','profiles'),catalog=await createPresetCatalog({profilesDir:profiles}),preset=catalog.list().printers.find(item=>item.vendor==='Vzbot'&&item.name.includes('330')&&item.name.includes('0.4')),jobs=new Map(),service=createNativeHotendService({catalog,jobStore:{get:id=>jobs.get(id)},nativeVendorDir:null});expect(preset).toBeTruthy();jobs.set('vendor',{status:'ready',nativeHotend:service.snapshot({printerId:preset.id,printer:catalog.getPreset(preset.id,'machine')})});jobs.set('old',{status:'ready'});const vendor=await service.resolve('vendor'),old=await service.resolve('old');expect(vendor.meta.resource).toBe('Vzbot/Goliath.stl');expect(old.meta.legacy).toBe(true);
 const text=await readFile(path.resolve('tests/fixtures/native-gui-shrink98-2.4.2.gcode'),'utf8'),worker=createNativeGcodeWorker({binary:process.env.ORCA_GCODE_WORKER_BIN||path.resolve(process.env.ORCA_NATIVE_CACHE_DIR||'.native-cache','gcode-build','orca-gcode-worker'),resourcesDir:process.env.ORCA_RESOURCES_DIR||'/Applications/OrcaSlicer.app/Contents/Resources'});let data;try{data={...await worker.process(Buffer.from(text)),sourceSha256:createHash('sha256').update(text).digest('hex'),sourceBytes:Buffer.byteLength(text)};}finally{await worker.shutdown();}
 const errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'&&!message.text().includes('Failed to load resource'))errors.push(message.text());});let job='vendor';await page.route('**/api/jobs',route=>route.request().method()==='POST'?route.fulfill({status:202,json:{id:job,filename:'GUI cube.gcode',status:'ready'}}):route.continue());await page.route('**/api/jobs/*/download',route=>route.fulfill({contentType:'text/plain',body:text}));await page.route('**/api/jobs/native-preview/capabilities',route=>route.fulfill({json:{available:true,engine:data.engine}}));await page.route('**/api/jobs/*/native-preview',route=>route.fulfill({json:data}));await page.route('**/api/jobs/*/hotend',route=>route.fulfill({json:job==='missing'?{version:1,available:false,error:'Native hotend resource unavailable for test'}:(job==='vendor'?vendor:old).meta}));await page.route('**/api/jobs/*/hotend/model?*',route=>route.fulfill({contentType:'model/stl',body:(job==='vendor'?vendor:old).bytes}));
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Choose a 3D model').setInputFiles(path.resolve('tests/fixtures/cube.stl'));
 const slice=async()=>{await page.getByRole('button',{name:'Slice model',exact:true}).click();const canvas=page.getByRole('img',{name:'3D G-code toolpaths'});await expect(canvas).toHaveAttribute('data-processor','native');await page.getByLabel('First preview layer').fill('49');await page.getByLabel('Last preview layer').fill('49');await page.getByLabel('Visible native commands').fill('1');await page.getByRole('button',{name:'Show tool properties',exact:true}).click();return canvas;};
 let canvas=await slice();await expect(canvas).toHaveAttribute('data-tool-marker-visible','true');await expect(canvas).toHaveAttribute('data-tool-marker-triangles','3208');await expect(canvas).toHaveAttribute('data-tool-marker-resource','Vzbot/Goliath.stl');await expect(page.getByRole('region',{name:'Native tool position'})).toContainText('Bundled printer hotend');await expect(page.getByRole('region',{name:'Native tool position'})).toContainText('Vzbot/Goliath.stl');await page.screenshot({path:test.info().outputPath('native-vzbot-hotend.png')});
 await page.getByRole('button',{name:'Prepare',exact:true}).click();job='old';canvas=await slice();await expect(canvas).toHaveAttribute('data-tool-marker-visible','true');await expect(canvas).toHaveAttribute('data-tool-marker-triangles','560');await expect(canvas).toHaveAttribute('data-tool-marker-resource','hotend.stl');await expect(page.getByRole('region',{name:'Native tool position'})).toContainText('This older job has no printer-model snapshot');
 await page.getByRole('button',{name:'Prepare',exact:true}).click();job='missing';canvas=await slice();await expect(canvas).toHaveAttribute('data-tool-marker-visible','false');await expect(canvas).toHaveAttribute('data-tool-marker-triangles','0');await expect(page.getByRole('status').filter({hasText:'Native hotend resource unavailable for test'})).toBeVisible();await expect(page.getByRole('region',{name:'Native tool position'}).locator('dl dd').first()).not.toBeEmpty();expect(errors).toEqual([]);
});
