import { test, expect } from '@playwright/test';
import path from 'node:path';

test('browser workflow uses installed OrcaSlicer 2.4.2 and native presets to generate real toolpaths', async ({ page, request }, testInfo) => {
  const healthResponse = await request.get('/api/health');
  const health = await healthResponse.json();
  expect(healthResponse.status(), JSON.stringify(health)).toBe(200);
  expect(health.engine.available).toBe(true);
  expect(health.engine.version).toMatch(/\bOrcaSlicer-2\.4\.2\b/);
  expect(health.engine.version).not.toMatch(/fake|fixture|test adapter/i);
  expect(health.slicer).not.toMatch(/fake-slicer|tests[/\\]fixtures/i);

  const catalogResponse = await request.get('/api/presets');
  expect(catalogResponse.ok()).toBeTruthy();
  const catalog = await catalogResponse.json();
  const { defaults } = catalog;
  const names = {
    printer: catalog.printers.find(item => item.id === defaults.printerId)?.name,
    process: catalog.processes.find(item => item.id === defaults.processId)?.name,
    filament: catalog.filaments.find(item => item.id === defaults.filamentId)?.name
  };
  for (const name of Object.values(names)) {
    expect(name).toBeTruthy();
    expect(name).not.toMatch(/^Test /);
  }

  await page.goto('/');
  await expect(page.getByRole('status')).toHaveText(health.engine.version);
  await expect(page.getByLabel('Printer', { exact: true })).toHaveValue(defaults.printerId);
  await expect(page.getByLabel('Printer', { exact: true }).locator('option:checked')).toHaveText(names.printer);
  await expect(page.getByLabel('Filament', { exact: true }).locator('option:checked')).toHaveText(names.filament);
  await expect(page.getByLabel('Process preset', { exact: true }).locator('option:checked')).toHaveText(names.process);
  await expect(page.getByLabel('Print profile')).toHaveValue(defaults.processId);
  await expect(page.getByLabel('Layer height', { exact: true })).toBeEnabled();
  await page.getByLabel('Choose a 3D model').setInputFiles(path.resolve('tests/fixtures/cube.stl'));
  await page.getByLabel('Layer height', { exact: true }).fill('0.12');
  await expect(page.locator('.estimate')).toContainText('0.12 mm layer');
  await expect(page.getByRole('button', { name: 'Slice model' })).toBeEnabled();
  await page.screenshot({ path: testInfo.outputPath('native-prepare.png'), fullPage: true });

  const submission = page.waitForResponse(response => response.request().method() === 'POST' && response.url().endsWith('/api/jobs'));
  await page.getByRole('button', { name: 'Slice model' }).click();
  const createdResponse = await submission;
  expect(createdResponse.status()).toBe(202);
  const created = await createdResponse.json();
  expect(created.overrides).toEqual({ layer_height: '0.12' });
  expect(created.settings.layer_height).toBe('0.12');
  expect(created.printer).toBe(names.printer);
  expect(created.profile).toBe(names.process);
  expect(created.filament).toBe(names.filament);
  expect(created.engineVersion).toBe(health.engine.version);

  await expect(page.getByText('Ready to print')).toBeVisible({ timeout: 90_000 });
  await expect(page.getByRole('heading', { name: 'G-code toolpath preview' })).toBeVisible();
  await expect(page.getByText('Job status: ready')).toBeVisible();
  await expect(page.getByLabel('Print profile').locator('option:checked')).toHaveText(names.process);
  const download = page.getByRole('link', { name: 'Download G-code' });
  await expect(download).toHaveAttribute('href', `/api/jobs/${created.id}/download`);
  await page.screenshot({ path: testInfo.outputPath('native-preview-ready.png'), fullPage: true });

  const output = await request.get(await download.getAttribute('href'));
  expect(output.status()).toBe(200);
  expect(output.headers()['content-disposition']).toContain('cube.gcode');
  const gcode = await output.text();
  expect(gcode).toMatch(/generated by OrcaSlicer/i);
  expect(gcode).not.toMatch(/test adapter|test fixture/i);
  expect(gcode).toMatch(/^; layer_height = 0\.12\s*$/m);
  expect(gcode).toMatch(/^G1 .*E[0-9]/m);
  expect(gcode.length).toBeGreaterThan(10_000);
  expect(gcode).toContain(names.printer);
  expect(gcode).toContain(names.filament);
  await testInfo.attach('native-gcode', { body: Buffer.from(gcode), contentType: 'text/plain' });
});
