import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';
import{importNative3MF}from'../../shared/native-project.js';import{serializeProject}from'../../shared/project.js';import{dropToBed,meshBounds}from'../../shared/geometry.js';
async function configuration(request){const listing=await(await request.get('/api/presets')).json(),printerId=listing.printers.find(item=>item.name==='Bambu Lab H2D 0.4 nozzle').id,choices=await(await request.get(`/api/presets?printerId=${printerId}`)).json(),selection={...choices.defaults,filamentIds:[choices.defaults.filamentId,choices.defaults.filamentId]},overrides={project:{nozzle_volume_type:['Standard','High Flow'],filament_map:['1','2']}};const response=await request.post('/api/presets/configuration',{data:{selection,overrides}});expect(response.status(),await response.text()).toBe(200);return{...await response.json(),selection,overrides};}
async function sourceProject(context){const project=importNative3MF(await readFile('tests/fixtures/native-gui-cube-2.4.2.3mf')),original=project.objects[0],bounds=meshBounds({...original,position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]});original.positions=original.positions.map((value,index)=>value-bounds.min[index%3]);project.objects=[dropToBed({...original,scale:[.5,.5,.03],position:[60,70,0],filamentSlot:1,native:{groupId:'body',objectName:'Native variant body',partType:'normal_part',objectSettings:{extruder:'1'},partSettings:{}}})];project.nativeSettings={...context.archiveSettings,layer_height:'.2',initial_layer_print_height:'.2',enable_prime_tower:'0',skirt_loops:'0',brim_type:'no_brim'};project.useEmbeddedSettings=true;project.nativeWorkflow=true;project.ids={...context.selection};return project;}
async function exported(page){await page.getByRole('button',{name:'Project',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();return importNative3MF(await readFile(await(await pending).path()));}
test('browser uses native active configuration while embedded exports and slot edits retain inactive H2D alternatives',async({page,request},testInfo)=>{
 const context=await configuration(request);expect(context.effectiveSettings.filament_max_volumetric_speed).toEqual(['25','40']);expect(context.archiveSettings.filament_max_volumetric_speed).toEqual(['25','40','25','40']);
 const project=await sourceProject(context);await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();
 const resolved=page.waitForResponse(response=>response.url().endsWith('/api/presets/configuration')&&Boolean(response.request().postDataJSON()?.nativeSettings));
 await page.getByLabel('Open Orca Web project').setInputFiles({name:'h2d-variants.orca-web.json',mimeType:'application/json',buffer:Buffer.from(serializeProject(project))});const response=await resolved;expect(response.status(),await response.text()).toBe(200);expect((await response.json()).effectiveSettings.filament_max_volumetric_speed).toEqual(['25','40']);await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Add filament slot',exact:true}).click();await expect(page.getByLabel('Filament 3 color')).toBeVisible();await page.getByRole('button',{name:'Remove filament slot 3',exact:true}).click();await expect(page.getByLabel('Filament 3 color')).toHaveCount(0);
 const saved=await exported(page);expect(saved.nativeSettings.filament_max_volumetric_speed).toEqual(['25','40','25','40']);expect(saved.nativeSettings.filament_self_index).toEqual(['1','1','2','2']);expect(saved.nativeSettings.nozzle_volume_type).toEqual(['Standard','High Flow']);await page.getByRole('button',{name:'Prepare',exact:true}).click();await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();await page.screenshot({path:testInfo.outputPath('h2d-native-variant-preservation.png')});
});
test('catalog H2D selection resolves source scalar shapes and slices through the ordinary upload endpoint',async({page,request})=>{
 const listing=await(await request.get('/api/presets')).json(),printer=listing.printers.find(item=>item.name==='Bambu Lab H2D 0.4 nozzle');await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Printer',{exact:true}).selectOption(printer.id);await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();
 await page.getByLabel('Choose a 3D model').setInputFiles('tests/fixtures/cube.stl');const submitting=page.waitForResponse(response=>response.url().endsWith('/api/jobs')&&response.request().method()==='POST');await page.getByRole('button',{name:'Slice model',exact:true}).click();const response=await submitting;expect(response.status(),await response.text()).toBe(202);const job=await response.json();let completed;await expect.poll(async()=>{completed=await(await request.get(`/api/jobs/${job.id}`)).json();return ['ready','failed'].includes(completed.status);},{timeout:90000}).toBe(true);expect(completed.status,completed.error).toBe('ready');const gcode=await(await request.get(`/api/jobs/${job.id}/download`)).text();expect(gcode).toMatch(/^; printer_settings_id = Bambu Lab H2D 0\.4 nozzle$/m);expect(gcode.split('\n').filter(line=>/^G[0123]\s/.test(line)).length).toBeGreaterThan(1000);
});
