import {routeNativeReadyJobHotend} from '../fixtures/native-preview-job-hotend.js';
import {test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import path from'node:path';import{createHash}from'node:crypto';import{createNativeGcodeWorker}from'../../server/native-gcode-worker.js';import{parseGcode}from'../../shared/gcode.js';import{adaptNativePreview,nativePreviewRange}from'../../shared/native-preview-adapter.js';import{nativePreviewRangeState,nativePreviewSelection,nativePreviewVisibilityTransition}from'../../shared/native-preview-range.js';
const binary=process.env.ORCA_GCODE_WORKER_BIN||path.resolve(process.env.ORCA_NATIVE_CACHE_DIR||'.native-cache','gcode-build',process.platform==='win32'?'orca-gcode-worker.exe':'orca-gcode-worker');let text,data,parsed;
test.beforeAll(async()=>{text=await readFile(path.resolve('tests/fixtures/native-gui-shrink98-2.4.2.gcode'),'utf8');const worker=createNativeGcodeWorker({binary,resourcesDir:process.env.ORCA_RESOURCES_DIR||'/Applications/OrcaSlicer.app/Contents/Resources'});try{const native=await worker.process(Buffer.from(text));data={...native,sourceSha256:createHash('sha256').update(text).digest('hex'),sourceBytes:Buffer.byteLength(text)};parsed=adaptNativePreview(parseGcode(text,{includeSource:true}),data);}finally{await worker.shutdown();}});
async function preview(page,{mismatch=false,unavailable=false}={}){
 await routeNativeReadyJobHotend(page,'native-preview-fixture');await page.route('**/api/jobs',route=>route.request().method()==='POST'?route.fulfill({status:202,json:{id:'native-preview-fixture',filename:'native-gui-cube.gcode',status:'ready'}}):route.continue());
 await page.route('**/api/jobs/native-preview-fixture/download',route=>route.fulfill({status:200,contentType:'text/plain',body:text}));
 await page.route('**/api/jobs/native-preview/capabilities',route=>route.fulfill({status:200,json:unavailable?{available:false,error:'Native helper unavailable in this fixture'}:{available:true,engine:data.engine}}));
 await page.route('**/api/jobs/native-preview-fixture/native-preview',route=>route.fulfill({status:200,json:mismatch?{...data,sourceSha256:'0'.repeat(64)}:data}));
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Choose a 3D model').setInputFiles(path.resolve('tests/fixtures/cube.stl'));await page.getByRole('button',{name:'Slice model',exact:true}).click();await expect(page.getByRole('heading',{name:'G-code toolpath preview'})).toBeVisible();
}
test('real native GUI G-code drives actual-flow geometry, role time/material, layer timing and raw cursor from native vertex IDs',async({page})=>{
 const errors=[];page.on('pageerror',problem=>errors.push(problem.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});await preview(page);const canvas=page.getByRole('img',{name:'3D G-code toolpaths'}),mode=page.getByLabel('Toolpath color mode');await expect(canvas).toHaveAttribute('data-processor','native');await expect(page.getByTestId('native-preview-origin')).toContainText('29,021 render vertices');await expect(page.getByTestId('toolpath-summary')).toContainText('102 printed layers');await expect(page.locator('[data-native-timing="Processor total"]')).toHaveText('2,538.21 s');await expect(page.locator('[data-native-role="Outer wall"]')).toContainText(' g');
 await page.getByLabel('First preview layer').fill('49');await page.getByLabel('Last preview layer').fill('49');await page.getByLabel('Show G-code',{exact:true}).check();const full=nativePreviewRangeState(data,{firstLayer:49,lastLayer:49}),selection=nativePreviewSelection(parsed,full),last=selection.indices.at(-1),a=parsed.native.attributes[last];await mode.selectOption('actualFlow');await expect(canvas).toHaveAttribute('data-current-native-vertex',String(parsed.segments[last].nativeEndVertex));await expect(canvas).toHaveAttribute('data-current-source-line',String(parsed.segments[last].line));await expect(page.getByLabel('G-code source lines').locator('[aria-current=true]')).toHaveAttribute('data-line',String(parsed.segments[last].line));await expect(canvas).toHaveAttribute('data-current-scalar-value',String(a.actualFlow));await expect(canvas).toHaveAttribute('data-visible-volumes',String(selection.indices.filter(index=>parsed.native.volumeData.segments[index]).length));await expect(page.locator('[data-attribute=actualSpeed]')).toContainText('mm/s');await page.getByRole('button',{name:'Fit toolpaths'}).click();await page.screenshot({path:test.info().outputPath('native-processed-preview.png')});
 await mode.selectOption('layerTimeLog');await expect(canvas).toHaveAttribute('data-scalar-range',JSON.stringify(nativePreviewRange(parsed,'layerTimeLog')));await expect(page.locator('[data-native-timing="Layer 50"]')).toHaveText('8.77 s');await expect(page.locator('[data-attribute=layerTime]')).toHaveText('8.769729 s');await page.getByLabel('Visible native commands').fill('1');const tick=full.ticks[1],first=parsed.segments.findIndex(segment=>segment.nativeEndVertex===tick.vertexIndex);await expect(canvas).toHaveAttribute('data-current-native-vertex',String(tick.vertexIndex));await expect(canvas).toHaveAttribute('data-current-source-line',String(tick.line));
 await mode.selectOption('feature');const feature=parsed.segments[first].feature;await page.getByLabel(`Show ${feature} toolpaths`,{exact:true}).uncheck();const before=nativePreviewRangeState(data,{firstLayer:49,lastLayer:49,visibleRange:[0,tick.vertexIndex]}),after=nativePreviewVisibilityTransition(data,before,{firstLayer:49,lastLayer:49,hiddenFeatures:[feature]});await expect(canvas).toHaveAttribute('data-visible-segments',String(after.segmentIds.length));expect(errors).toEqual([]);
});
test('mismatched native source is rejected and unavailable native data never enables timing modes',async({page})=>{await preview(page,{mismatch:true});await expect(page.getByTestId('native-preview-origin')).toContainText('do not match');await expect(page.getByRole('img',{name:'3D G-code toolpaths'})).toHaveAttribute('data-processor','source');for(const name of ['actualFlow','layerTime','layerTimeLog'])await expect(page.getByLabel('Toolpath color mode').locator(`option[value="${name}"]`)).toHaveJSProperty('disabled',true);});
test('missing native helper leaves a usable explicit source-only preview',async({page})=>{await preview(page,{unavailable:true});await expect(page.getByTestId('native-preview-origin')).toContainText('Source-only preview: Native helper unavailable');await page.getByLabel('Toolpath color mode').selectOption('flow');await expect(page.getByTestId('scalar-availability')).toContainText('6,900 /');});
