import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const fixture=JSON.parse(readFileSync(new URL('../fixtures/pa-line/source-three-labelled.json',import.meta.url)));
const rounded=(value,digits=5)=>Number(value.toFixed(digits));
const expected=fixture.map(event=>event[0]==='pa'?['pa',Number(event[1].toPrecision(4))]:event[0]==='speed'?['move',{F:rounded(event[1],3)}]:event[0]==='xy'?['move',{X:rounded(event[1],3),Y:rounded(event[2],3),F:rounded(event[3],3)}]:event[0]==='z'?['move',{Z:rounded(event[1],3),F:rounded(event[2],3)}]:event[0]==='extrude'?['move',{X:rounded(event[1],3),Y:rounded(event[2],3),E:rounded(event[4])}]:['move',{E:rounded(event[1]),F:rounded(event[3],3)}]);

test('browser PA lines reach the real engine and match every independently compiled native-source command',async({page,request})=>{
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Calibration',exact:true}).click();await page.getByRole('menuitem',{name:'Generate calibration…',exact:true}).click();
 await page.getByLabel('Calibration test',{exact:true}).selectOption('pressure-advance-line');await page.getByLabel('Calibration end',{exact:true}).fill('0.004');
 const preparing=page.waitForResponse(response=>response.url().endsWith('/api/calibrations/prepare'));
 await page.getByRole('button',{name:'Generate calibration',exact:true}).click();const prepared=await preparing;expect(prepared.status(),await prepared.text()).toBe(200);
 const submitting=page.waitForResponse(response=>response.url().endsWith('/api/jobs')&&response.request().method()==='POST');await page.getByRole('button',{name:'Slice model',exact:true}).click();
 const submitted=await submitting;expect(submitted.status(),await submitted.text()).toBe(202);const job=await submitted.json();
 await expect(page.getByText('Ready to print')).toBeVisible({timeout:90000});const ready=await(await request.get(`/api/jobs/${job.id}`)).json();expect(ready.calibrationSummary.lineCount).toBe(3);expect(ready.calibrationSummary.layers).toBe(2);
 const gcode=await(await request.get(`/api/jobs/${job.id}/download`)).text();expect(gcode).toMatch(/generated by OrcaSlicer 2\.4\.2/);expect(gcode).not.toMatch(/^M73\b|^; estimated printing time/m);
 const body=gcode.split('; source generator extrusion origin\n')[1].split(/G1 E[^\n]+ ; final calibration retract/)[0];
 const commands=body.split('\n').flatMap(line=>{const code=line.split(';')[0].trim();if(/^G1\b/.test(code))return[['move',Object.fromEntries([...code.matchAll(/\b([XYZEF])([-+\d.]+)/g)].map(match=>[match[1],Number(match[2])]))]];if(/^M900 K/.test(code))return[['pa',Number(code.slice(6))]];return[];});
 expect(commands).toEqual(expected);
});
