import {meshBounds} from '../../shared/geometry.js';
import {test,expect} from '@playwright/test';import {readFile} from 'node:fs/promises';
import {importNative3MF,exportNative3MF} from '../../shared/native-project.js';import {addFilamentSlot} from '../../shared/filament-slots.js';
test('installed-native project resolves a two-material tower, updates native placement and removes its bands when disabled',async({page,request},info)=>{
 expect((await(await request.get('/api/health')).json()).engine.version).toMatch(/^OrcaSlicer-2\.4\.2/);
 let p=importNative3MF(await readFile(new URL('../fixtures/native-gui-cube-2.4.2.3mf',import.meta.url)));p.useEmbeddedSettings=true;p=addFilamentSlot(p);p.nativeSettings={...p.nativeSettings,enable_prime_tower:'1',wipe_tower_wall_type:'rectangle',prime_tower_width:'45',prime_tower_infill_gap:'150',prime_volume:'45',wipe_tower_x:['75'],wipe_tower_y:['160'],wipe_tower_rotation_angle:'0',timelapse_type:'0',enable_wrapping_detection:'0'};const peer=structuredClone(p.objects[0]);peer.id='second';peer.name='Second cube';peer.position[0]+=35;peer.filamentSlot=2;peer.native.groupId='second';delete peer.native.instanceFamily;delete p.objects[0].native.instanceFamily;p.objects.push(peer);
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();const pending=page.waitForResponse(r=>r.url().endsWith('/api/geometry/prime-tower')&&r.request().method()==='POST');await page.getByLabel('Open Orca Web project').setInputFiles({name:'Native tower.3mf',mimeType:'application/octet-stream',buffer:Buffer.from(exportNative3MF(p))});
 const response=await pending;expect(response.status(),await response.text()).toBe(200);const result=(await response.json()).result;expect(result.visible).toBe(true);expect(result.extruders).toEqual([1,2]);expect(result.containedFirstInstances).toEqual([true,true]);expect(result.size[0]).toBe(45);expect(result.size[2]).toBe(meshBounds(p.objects[0]).size[2]);expect(result.position).toEqual([75,160]);
 const canvas=page.getByRole('img',{name:'Interactive 3D model view',exact:true}),rendered=()=>canvas.evaluate(el=>JSON.parse(el.dataset.primeTower));await expect.poll(rendered).toMatchObject({status:'ready',bands:2,triangles:24,size:result.size,position:result.position});
 await page.getByRole('button',{name:'Prime tower',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Prime tower placement'});await dialog.getByLabel('Prime tower X',{exact:true}).fill('65.125');await dialog.getByLabel('Prime tower rotation',{exact:true}).fill('45');const moved=page.waitForResponse(r=>r.url().endsWith('/api/geometry/prime-tower')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Apply prime tower'}).click();expect((await moved).status()).toBe(200);await expect.poll(rendered).toMatchObject({position:[65.125,160],rotation:Math.PI/4});await page.locator('.scene-views').getByRole('button',{name:'Fit',exact:true}).click();await page.screenshot({path:info.outputPath('native-prime-tower.png')});
 await page.getByRole('button',{name:'Prime tower',exact:true}).click();await dialog.getByLabel('Enable prime tower',{exact:true}).uncheck();await dialog.getByRole('button',{name:'Apply prime tower'}).click();await expect.poll(rendered).toMatchObject({status:'idle',visible:false,bands:0});await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(rendered,{timeout:30000}).toMatchObject({status:'ready',visible:true,bands:2});
});
