import {test,expect} from '@playwright/test';import {readFile} from 'node:fs/promises';import {dragTower,dragWorldPoint} from '../fixtures/tower-browser-drag.js';
import {importNative3MF,exportNative3MF} from '../../shared/native-project.js';import {addFilamentSlot} from '../../shared/filament-slots.js';import {parseGcode} from '../../shared/gcode.js';

for(const tool of ['body','X','Y'])test(`native tower ${tool} movement survives Undo, native project export and real slicing`,async({page,request},info)=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));expect((await(await request.get('/api/health')).json()).engine.version).toMatch(/^OrcaSlicer-2\.4\.2/);
 let p=importNative3MF(await readFile(new URL('../fixtures/native-gui-cube-2.4.2.3mf',import.meta.url)));p.useEmbeddedSettings=true;p=addFilamentSlot(p);p.nativeSettings={...p.nativeSettings,enable_prime_tower:'1',wipe_tower_wall_type:'rectangle',prime_tower_width:'60',prime_tower_brim_width:'3',prime_tower_infill_gap:'150',prime_volume:'45',wipe_tower_x:['75'],wipe_tower_y:['160'],wipe_tower_rotation_angle:'0',timelapse_type:'0',enable_wrapping_detection:'0'};
 const peer=structuredClone(p.objects[0]);peer.id='second';peer.name='Second cube';peer.position[0]+=35;peer.filamentSlot=2;peer.native.groupId='second';delete peer.native.instanceFamily;delete p.objects[0].native.instanceFamily;p.objects.push(peer);
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();const pending=page.waitForResponse(r=>r.url().endsWith('/api/geometry/prime-tower')&&r.request().method()==='POST');await page.getByLabel('Open Orca Web project').setInputFiles({name:'Native tower.3mf',mimeType:'application/octet-stream',buffer:Buffer.from(exportNative3MF(p))});
 const response=await pending;expect(response.status(),await response.text()).toBe(200);const result=(await response.json()).result;expect(result.dragContext).toMatchObject({version:1,margin:3.5,space:'native-world'});expect(result.extruders).toEqual([1,2]);
 const canvas=page.getByRole('img',{name:'Interactive 3D model view',exact:true}),rendered=()=>canvas.evaluate(el=>JSON.parse(el.dataset.primeTower));await expect.poll(rendered).toMatchObject({status:'ready',position:[75,160]});await page.locator('.scene-views').getByRole('button',{name:'Top',exact:true}).click();
 let expected;if(tool==='body')expected=await dragTower(page,canvas,result,[10,-20]);else{await dragTower(page,canvas,result,[0,0]);await page.mouse.up();await page.getByRole('button',{name:'Move',exact:true}).click();await page.locator('.scene-views').getByRole('button',{name:'Perspective',exact:true}).click();await page.locator('.scene-views').getByRole('button',{name:'Top',exact:true}).click();const box=await canvas.boundingBox(),before=await canvas.getAttribute('data-camera-frame');await page.mouse.move(box.x+40,box.y+box.height*.6);await page.mouse.wheel(0,600);await expect(canvas).not.toHaveAttribute('data-camera-frame',before);const axis=tool==='X'?0:1,handles=await canvas.evaluate(el=>JSON.parse(el.dataset.primeTowerGizmo));expect(handles.axes.map(h=>h.axis)).toEqual([0,1]);const movement=await dragWorldPoint(page,canvas,handles.axes[axis].handle,[10,-20]);expected=result.position.map((v,i)=>v+(i===axis?movement[i]:0));}await expect.poll(()=>canvas.evaluate(el=>JSON.parse(el.dataset.primeTowerInteraction).dragging)).toBe(true);await page.mouse.up();await expect.poll(async()=>((await rendered()).position?.[0]??NaN)).toBeCloseTo(expected[0],4);await expect.poll(async()=>((await rendered()).position?.[1]??NaN)).toBeCloseTo(expected[1],4);
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(rendered).toMatchObject({position:[75,160]});await page.getByRole('button',{name:'Redo',exact:true}).click();await expect.poll(async()=>((await rendered()).position?.[0]??NaN)).toBeCloseTo(expected[0],4);await page.screenshot({path:info.outputPath(`native-tower-${tool}-drag.png`)});
 await page.getByRole('button',{name:'Project',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const exported=importNative3MF(await readFile(await(await download).path()));expect(Number(exported.nativeSettings.wipe_tower_x[0])).toBeCloseTo(expected[0],4);expect(Number(exported.nativeSettings.wipe_tower_y[0])).toBeCloseTo(expected[1],4);
 await page.getByRole('button',{name:'Prepare',exact:true}).click();const submission=page.waitForResponse(r=>r.url().endsWith('/api/jobs/project')&&r.request().method()==='POST');await page.getByRole('button',{name:'Slice model',exact:true}).click();const submitted=await submission;expect(submitted.status(),await submitted.text()).toBe(202);const job=await submitted.json();await expect(page.getByText('Ready to print')).toBeVisible({timeout:90000});const completed=page.waitForEvent('download');const downloadLink=page.getByRole('link',{name:/Download G-code/});await expect(downloadLink).toHaveAttribute('href',`/api/jobs/${job.id}/download`);await downloadLink.click();const artifact=await completed;expect(await artifact.failure()).toBeNull();const code=await readFile(await artifact.path(),'utf8'),parsed=parseGcode(code),tower=parsed.segments.filter(s=>s.kind==='extrusion'&&/prime|wipe.*tower/i.test(s.feature));expect(tower.length).toBeGreaterThan(20);expect(code).not.toMatch(/test adapter|test fixture/i);expect(errors).toEqual([]);
});
