import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{importNative3MF}from'../../shared/native-project.js';import{addFilamentSlot}from'../../shared/filament-slots.js';import{serializeProject}from'../../shared/project.js';import{parseGcode}from'../../shared/gcode.js';
test('the object filament selector updates a single imported native volume in exported and sliced output',async({page,request},info)=>{
 const p=addFilamentSlot({...importNative3MF(await readFile(new URL('../fixtures/native-gui-shrink98-2.4.2.3mf',import.meta.url))),useEmbeddedSettings:true});Object.assign(p.nativeSettings,{filament_shrink:['100','100'],filament_shrinkage_compensation_z:['100','98'],single_extruder_multi_material:'1'});expect(p.objects[0].native.objectSettings.extruder).toBe('1');
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles({name:'Material choice.orca-web.json',mimeType:'application/json',buffer:Buffer.from(serializeProject(p))});await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();
 await page.getByLabel('Object filament slot').selectOption('2');await expect(page.getByLabel('Object filament slot')).toHaveValue('2');await page.getByRole('button',{name:'Variable layers',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Variable layer heights'});await expect(dialog.getByLabel('Layer material compensation')).toContainText('Used filament slots: 2 · Z compensation: 1.020408×');await expect(dialog.getByRole('img',{name:'Layer height brush bar'})).toHaveAttribute('data-layer-count','102');await dialog.screenshot({path:info.outputPath('single-volume-material-context.png')});await dialog.getByRole('button',{name:'Cancel changes'}).click();
 await page.getByRole('button',{name:'Project',exact:true}).click();const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const exported=importNative3MF(await readFile(await(await downloading).path()));expect(exported.objects[0].filamentSlot).toBe(2);expect(exported.objects[0].native.objectSettings.extruder).toBe('2');
 await page.getByRole('button',{name:'Prepare',exact:true}).click();const submission=page.waitForResponse(response=>response.request().method()==='POST'&&response.url().endsWith('/api/jobs/project'));await page.getByRole('button',{name:'Slice model',exact:true}).click();const response=await submission;expect(response.status(),await response.text()).toBe(202);const job=await response.json();await expect(page.getByText('Ready to print')).toBeVisible({timeout:90000});
 const ready=await(await request.get(`/api/jobs/${job.id}`)).json();expect(ready.shrinkageInitialization.usedFilamentSlots).toEqual([2]);const code=await(await request.get(`/api/jobs/${job.id}/download`)).text(),zs=[...code.matchAll(/^;Z:([\d.]+)/gm)].map(m=>Number(m[1])),walls=parseGcode(code).segments.filter(s=>s.kind==='extrusion'&&/wall/i.test(s.feature));expect(walls.length).toBeGreaterThan(100);expect([...new Set(walls.map(s=>s.tool))]).toEqual([1]);expect(zs).toHaveLength(102);expect(zs.at(-1)).toBe(20.4);await page.screenshot({path:info.outputPath('single-volume-material-native-preview.png'),fullPage:true});
});
