import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {emptyVolumeFixture} from '../fixtures/import-inspection-project.js';
import {exportNative3MF,importNative3MF} from '../../shared/native-project.js';
import {parseProject} from '../../shared/project.js';
const original=new URL('../fixtures/native-gui-cube-2.4.2.3mf',import.meta.url).pathname;
const file=allEmpty=>({name:'Native empty volumes.3mf',mimeType:'model/3mf',buffer:Buffer.from(exportNative3MF(emptyVolumeFixture({allEmpty})))});
async function start(page){await page.goto('/');await page.getByLabel('Open Orca Web project').setInputFiles(original);await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Preferences',exact:true}).click();const d=page.getByRole('dialog',{name:'Preferences'});await d.getByLabel('Load behaviour').selectOption('load_geometry_only');await d.getByRole('button',{name:'Close',exact:true}).click();}
test('actual native inspection removes a planar model before export and installed slicing of the surviving cube',async({page,request},info)=>{expect((await(await request.get('/api/health')).json()).engine.version).toBe('OrcaSlicer-2.4.2');await start(page);const inspection=page.waitForResponse('**/api/geometry/inspect-import');await page.getByLabel('Open Orca Web project').setInputFiles(file(false));const response=await inspection;expect(response.status()).toBe(200);const value=await response.json();expect(value.removedCount).toBe(1);expect(value.objects[1].volume).toBe(0);expect(value.objects[0].volume).toBeGreaterThan(7999);const d=page.getByRole('dialog',{name:'The volume of the object is zero'});await expect(d).toBeVisible();await page.screenshot({path:info.outputPath('native-zero-volume-notice.png')});await d.getByRole('button',{name:'OK',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(1);await page.getByRole('button',{name:'Project',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const p=importNative3MF(await readFile(await(await download).path()));expect(p.objects).toHaveLength(1);expect(p.objects[0].name).not.toBe('Flat sheet');await page.getByRole('button',{name:'Prepare',exact:true}).click();await page.getByRole('button',{name:'Slice model',exact:true}).click();await expect(page.getByText('Ready to print')).toBeVisible({timeout:90000});const codeDownload=page.waitForEvent('download');await page.getByRole('link',{name:/Download G-code/}).click();expect(await readFile(await(await codeDownload).path(),'utf8')).toMatch(/^; total layer number: 125$/m);});
test('actual native all-empty removal keeps the loaded scene and offers explicit no-survivor feedback',async({page})=>{await start(page);await page.getByLabel('position X',{exact:true}).fill('7');const beforeDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Save project',exact:true}).click();const before=parseProject(await readFile(await(await beforeDownload).path(),'utf8'));const inspection=page.waitForResponse('**/api/geometry/inspect-import');await page.getByLabel('Open Orca Web project').setInputFiles(file(true));const value=await(await inspection).json();expect(value.removedCount).toBe(1);expect(value.retainedIds).toEqual([]);await page.getByRole('dialog',{name:'The volume of the object is zero'}).getByRole('button',{name:'OK',exact:true}).click();await expect(page.getByRole('alert')).toContainText('no nonzero-volume objects');await expect(page.getByLabel('position X',{exact:true})).toHaveValue('7');const afterDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Save project',exact:true}).click();const after=parseProject(await readFile(await(await afterDownload).path(),'utf8'));expect(after.objects).toEqual(before.objects);});
