import {test,expect} from '@playwright/test';import {readFile}from'node:fs/promises';
import {importNative3MF,exportNative3MF}from'../../shared/native-project.js';import{paintedFacetGeometry,encodeFacet,decodeFacet}from'../../shared/facet-painting.js';import{transformPositions}from'../../shared/geometry.js';
async function saved(page){await page.getByRole('button',{name:'Project',exact:true}).click();const pending=page.waitForEvent('download');await page.locator('.project-actions').getByRole('button',{name:'Save project',exact:true}).click();const project=JSON.parse(await readFile(await(await pending).path(),'utf8'));await page.getByRole('button',{name:'Prepare',exact:true}).click();return project;}
async function open(page,project){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();if(project){await page.getByLabel('Open Orca Web project').setInputFiles({name:'Advanced paint.3mf',mimeType:'model/3mf',buffer:Buffer.from(exportNative3MF(project))});await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();}else{await page.getByLabel('Choose a 3D model').setInputFiles(new URL('../fixtures/cube.stl',import.meta.url).pathname);await expect(page.getByText('Triangles: 12',{exact:true})).toBeVisible();}await page.getByRole('button',{name:'Paint supports',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Paint facets'});await dialog.getByRole('button',{name:'Top',exact:true}).click();return dialog;}
async function click(dialog,x=15,y=12){const canvas=dialog.getByRole('img',{name:'Interactive 3D model view'}),bounds=await canvas.boundingBox();await canvas.click({position:{x:bounds.width/2+x,y:bounds.height/2+y}});return canvas;}
const values=tree=>Object.hasOwn(tree,'state')?[tree.state]:tree.children.flatMap(values);
test('clipped view filters ray hits and overhang-only constraints block top painting',async({page},info)=>{
 const dialog=await open(page),canvas=dialog.getByRole('img',{name:'Interactive 3D model view'});await expect(dialog.getByLabel('Painting tool',{exact:true})).toHaveValue('circle');await dialog.getByLabel('Clipping axis').selectOption('X');const offset=Number(await dialog.getByLabel('Clipping offset (mm)').inputValue());await expect(canvas).toHaveAttribute('data-clipping-plane',JSON.stringify({normal:[1,0,0],offset}));
 await click(dialog,40);await expect(canvas).toHaveAttribute('data-painted-facets','{}');await dialog.getByLabel('Paint only overhangs').check();await click(dialog,-40);await expect(canvas).toHaveAttribute('data-painted-facets','{}');await dialog.getByLabel('Paint only overhangs').uncheck();await click(dialog,-40);await expect.poll(async()=>Number(await canvas.getAttribute('data-paint-triangle-count'))).toBeGreaterThan(3);
 await dialog.getByLabel('Highlight overhangs').check();await expect(canvas).toHaveAttribute('data-overhang-triangle-count','2');await page.screenshot({path:info.outputPath('clipped-circle-paint.png')});await dialog.getByRole('button',{name:'Apply painting'}).click();const project=await saved(page);expect(paintedFacetGeometry(project.objects[0],'supports').every(f=>f.vertices.every(point=>point[0]<=offset+.06))).toBe(true);
});
test('native gap-fill preview uses connected states and Undo restores exact imported subdivisions',async({page})=>{
 const project=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url))),leaf=state=>({state}),split=child=>({split:3,side:0,children:[leaf(1),leaf(1),leaf(1),child]}),code=encodeFacet(split(split(split(leaf(2)))));project.objects[0].position=[50,50,0];project.objects[0].painting={version:1,supports:Object.fromEntries(Array.from({length:12},(_,index)=>[index,index===6?code:'4']))};
 const dialog=await open(page,project),canvas=dialog.getByRole('img',{name:'Interactive 3D model view'});await dialog.getByLabel('Painting tool',{exact:true}).selectOption('gap');await dialog.getByLabel('Gap area').fill('3.2');await dialog.getByRole('button',{name:'Perform gap fill'}).click();await expect(dialog.getByRole('status')).toContainText('1 native patches');await expect(canvas).toHaveAttribute('data-painted-facets','{"1":12}');await dialog.getByRole('button',{name:'Undo paint'}).click();await expect.poll(async()=>JSON.parse(await canvas.getAttribute('data-painted-facets'))['2']).toBe(1);await dialog.getByRole('button',{name:'Apply painting'}).click();const result=await saved(page);expect(result.objects[0].painting.supports[6]).toBe(code);
});
test('current-subfacet and bucket controls preserve boundaries while invalid native brush radius leaves data unchanged',async({page})=>{
 const project=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));project.objects[0].position=[50,50,0];project.objects[0].painting={version:1,supports:{2:'00043',3:'8'}};
 const dialog=await open(page,project),canvas=dialog.getByRole('img',{name:'Interactive 3D model view'});const before=await canvas.getAttribute('data-painted-facets');await dialog.getByLabel('Brush radius').fill('.1');await click(dialog);await expect(dialog.getByRole('alert')).toContainText('Native brush radius must be between 0.4 and 8');await expect(canvas).toHaveAttribute('data-painted-facets',before);
 await dialog.getByLabel('Painting tool',{exact:true}).selectOption('facet');await dialog.getByLabel('Paint action').selectOption('2');await click(dialog,15,12);await expect(dialog.getByRole('alert')).toHaveCount(0);await expect(canvas).toHaveAttribute('data-painted-facets','{"2":2}');await dialog.getByLabel('Painting tool',{exact:true}).selectOption('bucket');await dialog.getByLabel('Paint action').selectOption('1');await click(dialog,15,12);await expect(canvas).toHaveAttribute('data-painted-facets',before);await dialog.getByRole('button',{name:'Apply painting'}).click();const result=await saved(page);expect(result.objects[0].painting.supports[3]).toBe('8');expect(Array.from(transformPositions(result.objects[0]))).toEqual(Array.from(transformPositions(project.objects[0])));
});
