import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import path from'node:path';import{importNative3MF}from'../../shared/native-project.js';import{worldBrimEars}from'../../shared/brim-ears.js';
test('brim ears render at edited coordinates, export native metadata, cancel and undo atomically',async({page})=>{
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles(path.resolve('tests/fixtures/orca-2.4.2-cube.3mf'));await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Brim ears',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Brim ears',exact:true});await dialog.getByRole('button',{name:'Add brim ear'}).click();
 await dialog.getByLabel('Ear 1 X',{exact:true}).fill('60');await dialog.getByLabel('Ear 1 Y',{exact:true}).fill('70');await dialog.getByLabel('Ear 1 diameter',{exact:true}).fill('12');await dialog.getByRole('button',{name:'Apply brim ears'}).click();
 const canvas=page.locator('canvas[aria-label="Interactive 3D model view"]');await expect.poll(async()=>JSON.parse(await canvas.getAttribute('data-brim-ears'))).toEqual([{position:[60,70,0],radius:6}]);
 await page.getByRole('button',{name:'Brim ears',exact:true}).click();await dialog.getByLabel('Ear 1 diameter',{exact:true}).fill('-2');await dialog.getByRole('button',{name:'Apply brim ears'}).click();await expect(dialog.getByRole('alert')).toContainText('radius');await dialog.getByRole('button',{name:'Cancel changes'}).click();
 await page.getByRole('button',{name:'Project',exact:true}).click();const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const downloaded=await downloading,project=importNative3MF(await readFile(await downloaded.path()));expect(project.objects.flatMap(worldBrimEars)).toEqual([{position:[60,70,0],radius:6}]);expect(project.objects[0].native.objectSettings.brim_type).toBe('painted');
 await page.getByRole('button',{name:'Prepare',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(canvas).toHaveAttribute('data-brim-ears','[]');await page.getByRole('button',{name:'Redo',exact:true}).click();await expect.poll(async()=>JSON.parse(await canvas.getAttribute('data-brim-ears')).length).toBe(1);
 await page.getByRole('button',{name:'Brim ears',exact:true}).click();await dialog.getByRole('button',{name:'Remove all ears'}).click();await dialog.getByRole('button',{name:'Apply brim ears'}).click();await expect(canvas).toHaveAttribute('data-brim-ears','[]');
});
