import {observeGpu,gpuIdle,gpuRedraw} from '../fixtures/gpu-observation.js';
import{test,expect}from'@playwright/test';import path from'node:path';
async function open(page){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles(path.resolve('tests/fixtures/orca-2.4.2-cube.3mf'));await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Brim ears',exact:true}).click();return page.getByRole('dialog',{name:'Brim ears',exact:true});}
const state=canvas=>canvas.getAttribute('data-brim-editing').then(JSON.parse);
test('automatic ears use native angle defaults, append without duplicates, resize selection, and undo/cancel atomically',async({page})=>{const dialog=await open(page),canvas=dialog.locator('canvas');await expect(dialog.getByLabel('Max angle',{exact:true})).toHaveValue('125');await expect(dialog.getByLabel('Detection radius',{exact:true})).toHaveValue('1');await dialog.getByRole('button',{name:'Auto-generate brim ears'}).click();await expect.poll(async()=>(await state(canvas)).ears.length).toBe(4);const original=(await state(canvas)).ears;expect(original.map(e=>e.position.slice(0,2)).flat().some(v=>v<0)).toBe(true);await dialog.getByRole('button',{name:'Auto-generate brim ears'}).click();await expect.poll(async()=>(await state(canvas)).ears.length).toBe(4);await dialog.getByRole('button',{name:'Select all ears',exact:true}).click();await dialog.getByLabel('Head diameter',{exact:true}).fill('12');await expect.poll(async()=>(await state(canvas)).ears.map(e=>e.radius)).toEqual([6,6,6,6]);await dialog.getByRole('button',{name:'Undo ear edit'}).click();await expect.poll(async()=>(await state(canvas)).ears).toEqual(original);await dialog.getByRole('button',{name:'Redo ear edit'}).click();await dialog.getByRole('button',{name:'Remove all ears'}).click();await dialog.getByLabel('Max angle',{exact:true}).fill('90');await dialog.getByRole('button',{name:'Auto-generate brim ears'}).click();await expect.poll(async()=>(await state(canvas)).ears.length).toBe(0);await dialog.getByRole('button',{name:'Undo ear edit'}).click();await expect.poll(async()=>(await state(canvas)).ears.length).toBe(4);await dialog.getByRole('button',{name:'Cancel changes'}).click();await expect(page.locator('canvas[aria-label="Interactive 3D model view"]')).toHaveAttribute('data-brim-ears','[]');});
test('canvas adds on model only, native diameter wheel/keyboard deletion work and section view clips the preview',async({page})=>{const dialog=await open(page),canvas=dialog.locator('canvas');await dialog.getByRole('button',{name:'Perspective',exact:true}).click();await dialog.getByRole('button',{name:'Top',exact:true}).click();const box=await canvas.boundingBox();await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await expect.poll(async()=>(await state(canvas)).ears.length).toBe(1);let ears=(await state(canvas)).ears;expect(ears[0].position[2]).toBe(Math.fround(-.0001));expect(ears[0].position[0]).toBeCloseTo(10,1);expect(ears[0].position[1]).toBeCloseTo(10,1);await page.mouse.click(box.x+10,box.y+50);await expect.poll(async()=>(await state(canvas)).ears.length).toBe(1);await dialog.getByRole('button',{name:'Select all ears',exact:true}).click();const before=Number(await dialog.getByLabel('Head diameter',{exact:true}).inputValue());await canvas.hover();await page.keyboard.down('Control');await page.mouse.wheel(0,-100);await page.keyboard.up('Control');await expect.poll(async()=>Number(await dialog.getByLabel('Head diameter',{exact:true}).inputValue())).toBeCloseTo(Math.min(20,before+.1),5);await canvas.focus();await page.keyboard.press('Delete');await expect.poll(async()=>(await state(canvas)).ears.length).toBe(0);await dialog.getByRole('button',{name:'Undo ear edit'}).click();await expect.poll(async()=>(await state(canvas)).ears.length).toBe(1);await dialog.getByLabel('Brim section view').fill('0.5');await expect(canvas).not.toHaveAttribute('data-clipping-plane','null');await expect.poll(async()=>Number(await canvas.getAttribute('data-clipping-cap-triangles'))).toBeGreaterThan(0);await dialog.getByRole('button',{name:'Reset section view'}).click();await expect(canvas).toHaveAttribute('data-clipping-plane','null');await dialog.getByRole('button',{name:'Apply brim ears'}).click();const mainCanvas=page.locator('canvas[aria-label="Interactive 3D model view"]');await expect.poll(async()=>JSON.parse(await mainCanvas.getAttribute('data-brim-ears')).length).toBe(1);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(mainCanvas).toHaveAttribute('data-brim-ears','[]');});
test('visible ear rectangles select and deselect; dragging and right-click removal have independent local undo',async({page})=>{const dialog=await open(page),canvas=dialog.locator('canvas');await dialog.getByRole('button',{name:'Perspective',exact:true}).click();await dialog.getByRole('button',{name:'Top',exact:true}).click();await dialog.getByRole('button',{name:'Auto-generate brim ears'}).click();const box=await canvas.boundingBox();await page.keyboard.down('Shift');await page.mouse.move(box.x+20,box.y+50);await page.mouse.down();await page.mouse.move(box.x+box.width-20,box.y+box.height-55,{steps:10});await page.mouse.up();await page.keyboard.up('Shift');await expect.poll(async()=>(await state(canvas)).selected.length).toBe(4);await page.keyboard.down('Alt');await page.mouse.move(box.x+20,box.y+50);await page.mouse.down();await page.mouse.move(box.x+box.width-20,box.y+box.height-55,{steps:10});await page.mouse.up();await page.keyboard.up('Alt');await expect.poll(async()=>(await state(canvas)).selected.length).toBe(0);
 // Independent camera projection gives the visible lower-left ear's screen point.
 const {fitSceneCamera}=await import('../../shared/camera-fit.js'),{OrthographicCamera,Vector3}=await import('three');const fit=fitSceneCamera({bounds:{min:[0,0,0],max:[20,20,20]},aspect:box.width/box.height,view:'Top',minExtent:30}),camera=new OrthographicCamera(-fit.orthoSpan*box.width/box.height/2,fit.orthoSpan*box.width/box.height/2,fit.orthoSpan/2,-fit.orthoSpan/2,.1,20000);camera.up.set(0,0,1);camera.position.set(...fit.position);camera.lookAt(...fit.target);camera.updateMatrixWorld();const screen=point=>{const p=new Vector3(...point).project(camera);return[box.x+(p.x+1)*box.width/2,box.y+(1-p.y)*box.height/2];};let prior=await state(canvas),index=prior.ears.findIndex(e=>e.position[0]<0&&e.position[1]<0);const start=screen([-1,-1,.1]),end=screen([3,2,20]);await page.mouse.move(...start);await page.mouse.down();await page.mouse.move(...end,{steps:10});await page.mouse.up();await expect.poll(async()=>(await state(canvas)).ears[index].position[0]).toBeCloseTo(3,1);await expect.poll(async()=>(await state(canvas)).ears[index].position[1]).toBeCloseTo(2,1);await dialog.getByRole('button',{name:'Undo ear edit'}).click();await expect.poll(async()=>(await state(canvas)).ears).toEqual(prior.ears);await page.mouse.click(...start,{button:'right'});await expect.poll(async()=>(await state(canvas)).ears.length).toBe(3);await dialog.getByRole('button',{name:'Undo ear edit'}).click();await expect.poll(async()=>(await state(canvas)).ears).toEqual(prior.ears);});

test('brim ghost hover, placement and selection redraw actual GPU output then remain idle',async({page})=>{
 await observeGpu(page);const dialog=await open(page),canvas=dialog.locator('canvas');await dialog.getByRole('button',{name:'Perspective',exact:true}).click();await dialog.getByRole('button',{name:'Top',exact:true}).click();await gpuIdle(page,canvas);const b=await canvas.boundingBox();
 await gpuRedraw(page,canvas,()=>page.mouse.move(b.x+b.width*.5,b.y+b.height*.5));
 await gpuRedraw(page,canvas,()=>page.mouse.move(b.x+3,b.y+b.height*.6));
 await gpuRedraw(page,canvas,()=>page.mouse.click(b.x+b.width*.5,b.y+b.height*.5));await expect.poll(async()=>(await state(canvas)).ears.length).toBe(1);
 await gpuRedraw(page,canvas,()=>dialog.getByRole('button',{name:'Select all ears',exact:true}).click());
 await gpuRedraw(page,canvas,()=>dialog.getByLabel('Head diameter',{exact:true}).fill('12'));
 await gpuRedraw(page,canvas,()=>dialog.getByRole('button',{name:'Remove all ears',exact:true}).click());await expect.poll(async()=>(await state(canvas)).ears.length).toBe(0);
});
