import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {Triangle,Vector3} from 'three';
import {paintedFacetGeometry} from '../../shared/facet-painting.js';
async function save(page){await page.getByRole('button',{name:'Project',exact:true}).click();const pending=page.waitForEvent('download');await page.locator('.project-actions').getByRole('button',{name:'Save project',exact:true}).click();return JSON.parse(await readFile(await(await pending).path(),'utf8'));}
test('a sparse pointer drag paints one continuous native capsule strip and keeps the support legend legible',async({page},info)=>{
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Choose a 3D model').setInputFiles(new URL('../fixtures/cube.stl',import.meta.url).pathname);await expect(page.getByText('Triangles: 12',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Paint supports',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Paint facets'});await dialog.getByRole('button',{name:'Top',exact:true}).click();await dialog.getByLabel('Brush radius').fill('.4');
 const canvas=dialog.getByRole('img',{name:'Interactive 3D model view'}),box=await canvas.boundingBox();await page.mouse.move(box.x+box.width/2-60,box.y+box.height/2+20);await page.mouse.down();await page.mouse.move(box.x+box.width/2+60,box.y+box.height/2+20,{steps:1});await page.mouse.up();await expect(dialog.getByRole('alert')).toHaveCount(0);await expect.poll(async()=>Number(await canvas.getAttribute('data-paint-triangle-count'))).toBeGreaterThan(100);
 const colors=await dialog.locator('.paint-legend').evaluate(element=>({text:getComputedStyle(element).color,background:getComputedStyle(element.closest('.paint-dialog')).backgroundColor}));const luminance=value=>value.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((sum,v,index)=>sum+v*[.2126,.7152,.0722][index],0);expect((Math.max(luminance(colors.text),luminance(colors.background))+.05)/(Math.min(luminance(colors.text),luminance(colors.background))+.05)).toBeGreaterThan(4.5);
 await page.screenshot({path:info.outputPath('continuous-support-stroke.png')});await dialog.getByRole('button',{name:'Apply painting'}).click();const project=await save(page),facets=paintedFacetGeometry(project.objects[0],'supports'),vertices=facets.flatMap(f=>f.vertices),min=axis=>Math.min(...vertices.map(p=>p[axis])),max=axis=>Math.max(...vertices.map(p=>p[axis])),y=(min(1)+max(1))/2,z=max(2);expect(max(0)-min(0)).toBeGreaterThan(5);
 for(let x=min(0)+.5;x<max(0)-.5;x+=.25)expect(facets.some(f=>new Triangle(...f.vertices.map(p=>new Vector3(...p))).containsPoint(new Vector3(x,y,z))),`gap at X${x}`).toBe(true);
});
