import{test,expect}from'@playwright/test';import{build}from'esbuild';import{readFile}from'node:fs/promises';import path from'node:path';import{importNative3MF}from'../../shared/native-project.js';
let script,css,bytes,project;
test.beforeAll(async()=>{const output=await build({entryPoints:[path.resolve('src/main.jsx')],bundle:true,write:false,outdir:'unused-export-harness',format:'esm',define:{'process.env.NODE_ENV':'"production"'}});script=output.outputFiles.find(file=>file.path.endsWith('.js')).text;css=output.outputFiles.find(file=>file.path.endsWith('.css')).text;bytes=await readFile(path.resolve('tests/fixtures/pa-pattern/calibration-project.3mf'));project=importNative3MF(bytes);});
async function open(page,{expired=false}={}){
 await page.route('**/calibration-export-harness',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><link rel="stylesheet" href="/export-harness.css"></head><body><div id="root"></div><script type="module" src="/export-harness.js"></script></body></html>'}));await page.route('**/export-harness.js',route=>route.fulfill({contentType:'text/javascript',body:script}));await page.route('**/export-harness.css',route=>route.fulfill({contentType:'text/css',body:css}));
 await page.route('**/api/calibrations/prepare',route=>route.fulfill({json:{calibration:{mode:'pressure-advance-pattern',start:0,end:.01,step:.005,speeds:[120],accelerations:[4000],token:'a'.repeat(64)},plan:{label:'Pressure advance pattern',inputFormat:'3mf',request:{mode:'pressure-advance-pattern'},overrides:{process:{}}},objects:project.objects}}));
 let posted,ordinaryExports=0;await page.route('**/api/calibrations/project',route=>{posted=route.request().postDataJSON();return expired?route.fulfill({status:409,json:{error:'Calibration session expired or the server restarted. Regenerate the calibration model.'}}):route.fulfill({contentType:'model/3mf',body:bytes});});await page.route('**/api/projects/export',route=>{ordinaryExports++;return route.fulfill({status:500,json:{error:'Must not export handles without generated commands'}})});
 await page.goto('/calibration-export-harness');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByRole('button',{name:'Calibration',exact:true}).click();await page.getByRole('menuitem',{name:'Generate calibration…'}).click();await page.getByLabel('Calibration test',{exact:true}).selectOption('pressure-advance-pattern');await page.getByRole('button',{name:'Generate calibration',exact:true}).click();await expect(page.getByRole('dialog',{name:'Calibration',exact:true})).not.toBeVisible();await page.getByRole('button',{name:'Project',exact:true}).click();return{posted:()=>posted,ordinary:()=>ordinaryExports};
}
test('native calibration export sends exact token/IDs/objects and downloads all four generated command layers',async({page})=>{const state=await open(page);const waiting=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const download=await waiting,exported=importNative3MF(await readFile(await download.path()));expect(exported.plates[0].layerEvents.items).toHaveLength(4);expect(exported.plates[0].layerEvents.items.every(e=>e.extra.includes('ORCA_WEB_PA_PATTERN_START'))).toBe(true);expect(state.posted().calibration.token).toBe('a'.repeat(64));expect(state.posted().objects).toHaveLength(1);expect(state.ordinary()).toBe(0);});
test('expired native calibration export fails visibly without falling back to handle-only geometry',async({page})=>{const state=await open(page,{expired:true});let downloads=0;page.on('download',()=>downloads++);await page.getByRole('button',{name:'Export native project',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'Regenerate the calibration model'})).toBeVisible();expect(state.ordinary()).toBe(0);expect(downloads).toBe(0);});
test('ordinary JSON save remains a scene file and explains calibration token persistence limits',async({page})=>{const state=await open(page);const waiting=page.waitForEvent('download');await page.getByRole('contentinfo').getByRole('button',{name:'Save project',exact:true}).click();const downloaded=JSON.parse(await readFile(await(await waiting).path(),'utf8'));expect(downloaded.calibration.token).toBe('a'.repeat(64));await expect(page.getByText('Export native 3MF now to preserve calibration layer commands',{exact:false})).toBeVisible();expect(state.ordinary()).toBe(0);});
