import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{importNative3MF}from'../../shared/native-project.js';import{serializeProject}from'../../shared/project.js';import{analyzeMesh,meshBounds}from'../../shared/geometry.js';
async function saved(page){await page.getByRole('button',{name:'Project',exact:true}).click();const pending=page.waitForEvent('download');await page.locator('.project-actions').getByRole('button',{name:'Save project',exact:true}).click();const result=JSON.parse(await readFile(await(await pending).path(),'utf8'));await page.getByRole('button',{name:'Prepare',exact:true}).click();return result;}
async function start(page){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Choose a 3D model').setInputFiles(new URL('../fixtures/cube.stl',import.meta.url).pathname);await expect(page.getByText('Triangles: 12',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Cut',exact:true}).click();return page.getByRole('dialog',{name:'Cut object'});}
test('connector editor creates native plug and hole parts, preserves save/load and undo',async({page})=>{
 const dialog=await start(page);await dialog.getByRole('button',{name:'Add connector'}).click();await dialog.getByLabel('Connector 1 Diameter (mm)',{exact:true}).fill('3');await dialog.getByLabel('Connector 1 Radial clearance (mm)',{exact:true}).fill('.15');await dialog.getByLabel('Connector 1 Shape',{exact:true}).selectOption('square');await expect(dialog.getByLabel('Cut retained sides')).toBeDisabled();await expect(dialog.getByRole('status')).toContainText('4 retained parts');await expect(dialog.getByRole('button',{name:'Apply cut'})).toBeEnabled();await dialog.getByRole('button',{name:'Apply cut'}).click();let project=await saved(page);expect(project.objects).toHaveLength(4);expect(project.objects.every(o=>analyzeMesh(o).manifold)).toBe(true);const connectors=project.objects.filter(o=>o.native.cutConnector);expect(connectors).toHaveLength(2);expect(connectors.map(o=>o.native.partType).sort()).toEqual(['negative_part','normal_part']);expect(connectors.every(o=>Math.abs(o.native.cutConnector.radiusTolerance-.15)<1e-6)).toBe(true);expect(project.objects.every(o=>o.native.cutId.checkSum==='2')).toBe(true);expect(connectors[0].cutConnectorPlan.shape).toBe('square');
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.scene-object-row')).toHaveCount(1);await page.getByLabel('Open Orca Web project').setInputFiles({name:'Saved connector.json',mimeType:'application/json',buffer:Buffer.from(serializeProject(project))});await page.getByRole('dialog',{name:'Unsaved project changes'}).getByRole('button',{name:'Discard changes',exact:true}).click();const restored=await saved(page);expect(restored.objects.map(o=>o.native)).toEqual(project.objects.map(o=>o.native));
});
test('dowels become separate bed-contact groups; invalid connector edits block application',async({page})=>{
 const dialog=await start(page);await dialog.getByRole('button',{name:'Add connector'}).click();await dialog.getByLabel('Connector 1 Type',{exact:true}).selectOption('dowel');await expect(dialog.getByRole('status')).toContainText('5 retained parts');await dialog.getByLabel('Connector 1 U (mm)',{exact:true}).fill('10000');await expect(dialog.getByRole('alert')).toContainText('outside the cut contour');await expect(dialog.getByRole('button',{name:'Apply cut'})).toBeDisabled();await dialog.getByRole('button',{name:'Remove connector 1'}).click();await expect(dialog.getByRole('status')).toContainText('2 retained parts');await dialog.getByRole('button',{name:'Add connector'}).click();await dialog.getByLabel('Connector 1 Type',{exact:true}).selectOption('dowel');await expect(dialog.getByRole('button',{name:'Apply cut'})).toBeEnabled();await dialog.getByRole('button',{name:'Apply cut'}).click();const project=await saved(page);expect(project.objects).toHaveLength(5);expect(new Set(project.objects.map(o=>o.native.groupId)).size).toBe(3);const dowel=project.objects.find(o=>o.native.cutConnector&&o.native.partType==='normal_part');expect(meshBounds(dowel).min[2]).toBeCloseTo(0,5);expect(meshBounds(dowel).size[2]).toBeCloseTo(6,5);expect(dowel.native.cutId.checkSum).toBe('3');
});
test('repeated cut synchronizes existing family peers atomically and preserves painting consent',async({page})=>{
 const project=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));project.objects[0].position=[40,40,0];delete project.objects[0].native.instanceFamily;project.objects[0].native.cutId={id:'9007199254740997',checkSum:'2',connectorsCount:'4'};project.objects[0].painting={version:1,supports:{0:'4'}};const peer=structuredClone(project.objects[0]);peer.id='peer';peer.position=[90,40,0];peer.native.groupId='peer';delete peer.painting;project.objects.push(peer);
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles({name:'Cut family.json',mimeType:'application/json',buffer:Buffer.from(serializeProject(project))});await page.getByRole('button',{name:'Cut',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Cut object'});await dialog.getByRole('button',{name:'Add connector'}).click();await expect(dialog.getByRole('status')).toContainText('4 retained parts');await expect(dialog.getByRole('button',{name:'Apply cut'})).toBeDisabled();await dialog.getByLabel('Clear painting from cut parts').check();await dialog.getByRole('button',{name:'Apply cut'}).click();const result=await saved(page);expect(result.objects).toHaveLength(5);expect(result.objects.every(o=>o.native.cutId.checkSum==='3'&&o.native.cutId.connectorsCount==='5')).toBe(true);expect(result.objects.filter(o=>o.native.cutConnector).every(o=>o.name==='Connector-5')).toBe(true);await page.getByRole('button',{name:'Undo',exact:true}).click();const original=await saved(page);expect(original.objects).toHaveLength(2);expect(original.objects[0].painting.supports[0]).toBe('4');expect(original.objects.every(o=>o.native.cutId.checkSum==='2')).toBe(true);
});
