import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {importNative3MF} from '../../shared/native-project.js';
const fixture=new URL('../fixtures/native-gui-cube-2.4.2.3mf',import.meta.url);
const selected=(page,label)=>page.getByLabel(label,{exact:true}).locator('option:checked');
for(const matched of [false,true])test(`embedded preset labels show the active native profiles with ${matched?'retained catalog IDs':'no catalog IDs'} and survive Undo/export`,async({page,request})=>{
 const catalog=await(await request.get('/api/presets')).json(),project=importNative3MF(await readFile(fixture));project.useEmbeddedSettings=true;project.ids=matched?catalog.defaults:{printerId:'',processId:'',filamentId:''};
 const printer=project.nativeSettings.printer_settings_id,process=project.nativeSettings.print_settings_id;
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles({name:'embedded-labels.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();
 for(const [label,name]of[['Printer',printer],['Process preset',process],['Print profile',process]]){await expect(selected(page,label)).toHaveText(name);await expect(page.getByLabel(label,{exact:true})).toBeDisabled();await expect(page.getByLabel(label,{exact:true})).toHaveAttribute('title','Using the project’s embedded preset');}
 await page.getByLabel('Layer height',{exact:true}).fill('0.12');await page.getByRole('button',{name:'Project',exact:true}).click();const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const exported=importNative3MF(await readFile(await(await downloading).path()));expect(exported.nativeSettings.printer_settings_id).toBe(printer);expect(exported.nativeSettings.print_settings_id).toBe(process);expect(exported.nativeSettings.layer_height).toBe('0.12');
 await page.getByRole('button',{name:'Prepare',exact:true}).click();await page.getByRole('button',{name:'Use installed presets',exact:true}).click();await expect(page.getByLabel('Printer',{exact:true})).toBeEnabled();await expect(selected(page,'Printer')).toHaveText(catalog.printers.find(p=>p.id===catalog.defaults.printerId).name);await expect(selected(page,'Process preset')).toHaveText(catalog.processes.find(p=>p.id===catalog.defaults.processId).name);
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();await expect(selected(page,'Printer')).toHaveText(printer);await expect(selected(page,'Process preset')).toHaveText(process);await expect(selected(page,'Print profile')).toHaveText(process);
});
test('empty preset selectors distinguish loading from a completed catalog failure and recover on reload',async({page})=>{
 let release,first=true;await page.route(/\/api\/presets(?:\?.*)?$/,async route=>{if(!first)return route.continue();first=false;await new Promise(resolve=>release=resolve);await route.fulfill({status:503,json:{error:'Native presets unavailable for this test.'}});});
 await page.goto('/');for(const label of ['Printer','Process preset','Print profile'])await expect(selected(page,label)).toHaveText('Loading presets…');release();await expect(page.getByRole('alert')).toContainText('Native presets unavailable for this test.');for(const label of ['Printer','Process preset','Print profile']){await expect(selected(page,label)).toHaveText('No compatible presets');await expect(page.getByLabel(label,{exact:true})).toBeDisabled();}
 await page.reload();await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();for(const label of ['Printer','Process preset','Print profile']){await expect(page.getByLabel(label,{exact:true})).toBeEnabled();await expect(selected(page,label)).not.toHaveText(/Loading|No compatible/);}
});
