import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{importNative3MF,exportNative3MF,nativeSettingsFromSelection}from'../../shared/native-project.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';import{makeNativeAcceptanceProject}from'../fixtures/native-project.js';
async function load(page){const base=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url))),project=makeNativeAcceptanceProject(base),catalog=fixtureCatalog(base),selected=catalog.resolveSelection({printerId:'printer',processId:'process',filamentId:'red'}),blue=catalog.resolveSelection({printerId:'printer',processId:'process',filamentId:'blue'}).filament;project.nativeSettings={...base.nativeSettings,...nativeSettingsFromSelection({...selected,filaments:[selected.filament,blue]}),single_extruder_multi_material:'1'};await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles({name:'Ordering.3mf',mimeType:'model/3mf',buffer:Buffer.from(exportNative3MF(project))});await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Filament order',exact:true}).click();return page.getByRole('dialog',{name:'Filament printing order'});}
async function saved(page){await page.getByRole('button',{name:'Project',exact:true}).click();const promise=page.waitForEvent('download');await page.locator('.project-actions').getByRole('button',{name:'Save project',exact:true}).click();return JSON.parse(await readFile(await(await promise).path(),'utf8'));}
test('filament order editor exports first-layer and overlapping interval settings on the selected plate',async({page})=>{
 const dialog=await load(page);await dialog.getByLabel('First layer ordering').selectOption('custom');await dialog.getByLabel('First layer filament order').fill('2 1');await dialog.getByRole('button',{name:'Add order range',exact:true}).click();await dialog.getByLabel('Order range start').fill('4');await dialog.getByLabel('Order range end').fill('7');await dialog.getByLabel('Range filament order').fill('2 1');await dialog.getByRole('button',{name:'Add order range',exact:true}).click();await dialog.getByRole('button',{name:'Apply filament order',exact:true}).click();
 const project=await saved(page);expect(project.plates[0].native.metadata.first_layer_print_sequence).toBe('2 1');expect(project.plates[0].native.metadata.other_layers_print_sequence).toBe('2 100 1 2 4 7 2 1');expect(project.plates[1].native.metadata.other_layers_print_sequence).toBeUndefined();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const native=importNative3MF(await readFile(await(await pending).path()));expect(native.plates[0].native.metadata.other_layers_print_sequence).toBe('2 100 1 2 4 7 2 1');
});
test('filament order rejects duplicate or omitted slots and cancel leaves metadata unchanged',async({page})=>{
 const dialog=await load(page);await dialog.getByLabel('First layer ordering').selectOption('custom');await dialog.getByLabel('First layer filament order').fill('1 1');await dialog.getByRole('button',{name:'Apply filament order'}).click();await expect(dialog.getByRole('alert')).toContainText('distinct');await dialog.getByLabel('First layer filament order').fill('1');await dialog.getByRole('button',{name:'Apply filament order'}).click();await expect(dialog.getByRole('alert')).toContainText('every filament');await dialog.getByRole('button',{name:'Cancel changes'}).click();const project=await saved(page);expect(project.plates[0].native.metadata.first_layer_print_sequence).toBeUndefined();
});
test('resetting filament order and undo restore native first-layer settings',async({page})=>{
 const dialog=await load(page);await dialog.getByLabel('First layer ordering').selectOption('custom');await dialog.getByLabel('First layer filament order').fill('2 1');await dialog.getByRole('button',{name:'Apply filament order'}).click();await page.getByRole('button',{name:'Filament order',exact:true}).click();await dialog.getByRole('button',{name:'Reset to automatic'}).click();await dialog.getByRole('button',{name:'Apply filament order'}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Filament order',exact:true}).click();await expect(dialog.getByLabel('First layer filament order')).toHaveValue('2 1');await dialog.getByRole('button',{name:'Cancel changes'}).click();await page.getByRole('button',{name:'Redo',exact:true}).click();const project=await saved(page);expect(project.plates[0].native.metadata.first_layer_print_sequence).toBe('0');expect(project.plates[0].native.metadata.other_layers_print_sequence_nums).toBe('0');
});
