import {test,expect} from '@playwright/test';import {readFile}from'node:fs/promises';import{importNative3MF,exportNative3MF,nativeSettingsFromSelection}from'../../shared/native-project.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';
async function saved(page){await page.getByRole('button',{name:'Project',exact:true}).click();const pending=page.waitForEvent('download');await page.locator('.project-actions').getByRole('button',{name:'Save project',exact:true}).click();const project=JSON.parse(await readFile(await(await pending).path(),'utf8'));await page.getByRole('button',{name:'Prepare',exact:true}).click();return project;}
async function setup(page){const project=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url))),catalog=fixtureCatalog(project),selection=catalog.resolveSelection(catalog.list().defaults);project.nativeSettings={...nativeSettingsFromSelection({...selection,filaments:[selection.filament,selection.filament]}),filament_colour:['#FF0000','#0000FF']};const original=project.objects[0];project.objects=[{...original,name:'Remap A',id:'remap-a',filamentSlot:1,painting:{version:1,color:{2:'8'},supports:{4:'4'}},native:{...original.native,groupId:'remap-group',objectSettings:{extruder:'1'},partSettings:{}}},{...original,name:'Remap B',id:'remap-b',position:original.position.map((v,i)=>v+(i===0?35:0)),filamentSlot:2,native:{...original.native,groupId:'remap-group',objectSettings:{extruder:'1'},partSettings:{extruder:'2'}}}];await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles({name:'Remap.3mf',mimeType:'model/3mf',buffer:Buffer.from(exportNative3MF(project))});await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();await page.locator('.scene-object-list').getByRole('button',{name:'Remap A',exact:true}).click();return saved(page);}
async function open(page){await page.getByRole('button',{name:'Paint colors',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Paint facets'});await dialog.locator('summary').filter({hasText:'Remap filaments'}).click();return dialog;}
async function swaps(dialog){await dialog.getByLabel('Remap filament 1',{exact:true}).selectOption('2');await dialog.getByLabel('Remap filament 2',{exact:true}).selectOption('1');await dialog.getByRole('button',{name:'Remap filaments',exact:true}).click();}
test('native group remap changes real facet and base colors, while pending Reset and Undo restore exact metadata',async({page})=>{
 test.setTimeout(60000); // Several real import/save/export cycles share the full-suite browser/engine load.
 const before=await setup(page),dialog=await open(page),canvas=dialog.getByRole('img',{name:'Interactive 3D model view'});await expect(canvas).toHaveAttribute('data-painted-facets','{"2":1}');await dialog.getByLabel('Remap filament 1',{exact:true}).selectOption('2');await dialog.getByRole('button',{name:'Reset mapping'}).click();await expect(dialog.getByLabel('Remap filament 1',{exact:true})).toHaveValue('1');await expect(dialog.getByRole('button',{name:'Remap filaments',exact:true})).toBeDisabled();await expect(canvas).toHaveAttribute('data-painted-facets','{"2":1}');
 await swaps(dialog);await expect(canvas).toHaveAttribute('data-painted-facets','{"1":1}');const materials=JSON.parse(await canvas.getAttribute('data-part-materials'));expect(materials.find(m=>m.id===before.objects[0].id).color.toLowerCase()).toBe('#0000ff');expect(materials.find(m=>m.id===before.objects[1].id).color.toLowerCase()).toBe('#ff0000');await dialog.getByRole('button',{name:'Undo paint'}).click();await expect(canvas).toHaveAttribute('data-painted-facets','{"2":1}');await dialog.getByRole('button',{name:'Apply painting'}).click();const restored=await saved(page);expect(restored.objects.map(o=>({positions:o.positions,painting:o.painting,native:o.native,filamentSlot:o.filamentSlot}))).toEqual(before.objects.map(o=>({positions:o.positions,painting:o.painting,native:o.native,filamentSlot:o.filamentSlot})));
 const again=await open(page);await swaps(again);await again.getByRole('button',{name:'Apply painting'}).click();const after=await saved(page);expect(after.objects.map(o=>o.filamentSlot)).toEqual([2,1]);expect(after.objects[0].painting.color).toEqual({2:'4'});expect(after.objects[0].painting.supports).toEqual(before.objects[0].painting.supports);expect(after.objects.map(o=>o.positions)).toEqual(before.objects.map(o=>o.positions));const response=await page.request.post('/api/projects/export',{data:{project:after,useEmbeddedSettings:true}});expect(response.ok()).toBe(true);const native=importNative3MF(await response.body());expect(native.objects.map(o=>o.filamentSlot)).toEqual([2,1]);expect(native.objects[0].painting.color).toEqual({2:'4'});
});
