import {test,expect} from '@playwright/test';
import {observeFrameClears,exerciseCappedCamera,cappedIdle,frameClears} from '../fixtures/fps-observation.js';
import {preferences} from '../fixtures/camera-browser.js';
const key='orca-web:native-graphics-preferences-v1';
async function open(page){await observeFrameClears(page);await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Choose a 3D model').setInputFiles(new URL('../fixtures/cube.stl',import.meta.url).pathname);return page.getByRole('img',{name:'Interactive 3D model view'});}
test('native FPS limits, keyboard commits and overlay persist without adding a model Undo step',async({page},info)=>{
 await open(page);await preferences(page,async dialog=>{const fps=dialog.getByLabel('FPS cap',{exact:true});await expect(fps).toHaveValue('0');await expect(dialog.getByLabel('Show FPS overlay')).not.toBeChecked();await fps.press('ArrowUp');await expect(fps).toHaveValue('1');await fps.press('ArrowDown');await expect(fps).toHaveValue('0');await fps.fill('999');await fps.press('Enter');await expect(fps).toHaveValue('240');await fps.fill('');await fps.press('Tab');await expect(dialog.getByRole('alert')).toHaveText('Enter a whole number for FPS cap.');await fps.fill('15');await fps.press('Tab');await dialog.getByLabel('Show FPS overlay').check();await dialog.screenshot({path:info.outputPath('native-fps-preferences.png')});});
 expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key)).toEqual({version:1,opengl_fps_cap:'15',opengl_show_fps_overlay:'true'});await expect(page.getByLabel('Viewport FPS',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.scene-object-row')).toHaveCount(0);await page.reload();await preferences(page,async dialog=>{await expect(dialog.getByLabel('FPS cap',{exact:true})).toHaveValue('15');await expect(dialog.getByLabel('Show FPS overlay')).toBeChecked();});
});
test('Prepare caps actual GPU frame submissions, samples FPS and remains idle; unlimited changes take effect immediately',async({page},info)=>{
 const canvas=await open(page);await preferences(page,async dialog=>{await dialog.getByLabel('FPS cap',{exact:true}).fill('5');await dialog.getByLabel('FPS cap',{exact:true}).press('Enter');await dialog.getByLabel('Show FPS overlay').check();});await cappedIdle(page,canvas,5);const times=await exerciseCappedCamera(page,canvas,5,{steps:85});const fps=Number((await page.getByLabel('Viewport FPS',{exact:true}).innerText()).replace('FPS: ',''));expect(fps).toBeGreaterThan(0);expect(fps).toBeLessThanOrEqual(5);await cappedIdle(page,canvas,5);await info.attach('actual-capped-frame-clears',{body:JSON.stringify(times),contentType:'application/json'});await page.screenshot({path:info.outputPath('prepare-fps-overlay.png')});
 await preferences(page,async dialog=>{await dialog.getByLabel('FPS cap',{exact:true}).fill('0');await dialog.getByLabel('FPS cap',{exact:true}).press('Enter');await dialog.getByLabel('Show FPS overlay').uncheck();});await expect(page.getByLabel('Viewport FPS',{exact:true})).toBeHidden();const count=(await frameClears(canvas)).length;await page.getByRole('button',{name:'Wireframe',exact:true}).click();await expect.poll(async()=>(await frameClears(canvas)).length,{timeout:500}).toBeGreaterThan(count);
});
test('painting canvases inherit the limit and overlay and release their render timers on closing',async({page})=>{
 await open(page);await preferences(page,async dialog=>{await dialog.getByLabel('FPS cap',{exact:true}).fill('5');await dialog.getByLabel('FPS cap',{exact:true}).press('Enter');await dialog.getByLabel('Show FPS overlay').check();});await page.getByRole('button',{name:'Paint supports',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Paint facets'}),canvas=dialog.getByRole('img',{name:'Interactive 3D model view'});await expect(dialog.getByLabel('Viewport FPS',{exact:true})).toBeVisible();await cappedIdle(page,canvas,5);await exerciseCappedCamera(page,canvas,5,{steps:45});await cappedIdle(page,canvas,5);const old=await canvas.elementHandle(),before=(await frameClears(canvas)).length;await dialog.getByRole('button',{name:'Cancel painting',exact:true}).click();await page.waitForTimeout(350);expect(await old.evaluate(c=>(window.__frameClears.get(c)||[]).length)).toBe(before);
});
test('stored native cap normalization and failed storage retain an explicit session-only graphics change',async({page})=>{
 await page.addInitScript(k=>{localStorage.setItem(k,JSON.stringify({version:1,opengl_fps_cap:'999',opengl_show_fps_overlay:'false'}));const original=Storage.prototype.setItem;Storage.prototype.setItem=function(name,value){if(name===k)throw new DOMException('disabled','QuotaExceededError');return original.call(this,name,value);};},key);await open(page);await preferences(page,async dialog=>{await expect(dialog.getByLabel('FPS cap',{exact:true})).toHaveValue('240');await dialog.getByLabel('Show FPS overlay').check();await expect(dialog.getByRole('alert')).toHaveText('Graphics controls changed for this session, but browser storage could not save them.');});await expect(page.getByLabel('Viewport FPS',{exact:true})).toBeVisible();
});
test('native pointer arrows commit immediately in the app and persist without a project Undo entry',async({page})=>{
 await open(page);await preferences(page,async dialog=>{const input=dialog.getByLabel('FPS cap',{exact:true});await input.fill('30');await input.press('Enter');await input.fill('200');await dialog.getByRole('button',{name:'Increase FPS cap'}).click();await expect(input).toHaveValue('31');expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).opengl_fps_cap,key)).toBe('31');await dialog.getByRole('button',{name:'Decrease FPS cap'}).click();await expect(input).toHaveValue('30');});await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.scene-object-row')).toHaveCount(0);await page.reload();await preferences(page,async dialog=>{await expect(dialog.getByLabel('FPS cap',{exact:true})).toHaveValue('30');});
});
