import {test,expect} from '@playwright/test';import {readFile} from 'node:fs/promises';
import {importNative3MF,exportNative3MF} from '../../shared/native-project.js';import {makeNativeAcceptanceProject} from '../fixtures/native-project.js';
async function load(page){const base=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url))),project=makeNativeAcceptanceProject(base);project.objects=project.objects.filter(object=>object.native.groupId==='cutout');project.plates=project.plates.slice(0,1);project.selectedId='base';
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles({name:'Ranges.3mf',mimeType:'model/3mf',buffer:Buffer.from(exportNative3MF(project))});await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Height ranges',exact:true}).click();return page.getByRole('dialog',{name:'Height range settings'});}
async function save(page){await page.getByRole('button',{name:'Project',exact:true}).click();const promise=page.waitForEvent('download');await page.locator('.project-actions').getByRole('button',{name:'Save project',exact:true}).click();return JSON.parse(await readFile(await(await promise).path(),'utf8'));}
test('height editor applies native ranges to every grouped part and retains overrides through native export',async({page})=>{
 const dialog=await load(page);await expect(dialog.getByText('148 native height range controls')).toBeVisible();await dialog.getByRole('button',{name:'Add height range'}).click();await expect(dialog.getByLabel('Height range start')).toHaveValue('0');await expect(dialog.getByLabel('Height range end')).toHaveValue('2');await dialog.getByLabel('Height range end').fill('8');await dialog.getByLabel('Search height range settings').fill('layer_height');await expect(dialog.getByLabel('Override height range layer_height')).toBeDisabled();await dialog.getByLabel('Layer height (layer_height)',{exact:true}).fill('0.12');
 await dialog.getByLabel('Search height range settings').fill('wall_loops');await dialog.getByLabel('Override height range wall_loops').check();await dialog.getByLabel('Wall loops (wall_loops)',{exact:true}).fill('5');await dialog.getByRole('button',{name:'Add height range'}).click();await dialog.getByLabel('Height range start').fill('6');await dialog.getByLabel('Height range end').fill('12');await dialog.getByLabel('Search height range settings').fill('outer_wall_speed');await dialog.getByLabel('Override height range outer_wall_speed').check();await dialog.getByLabel('Outer wall (outer_wall_speed)',{exact:true}).fill('30');await dialog.getByText('Effective ranges and overlap precedence',{exact:true}).click();await expect(dialog.getByText('8–12 mm · layer height 0.16 mm')).toBeVisible();
 await dialog.getByRole('button',{name:'Apply height ranges'}).click();await expect(dialog).toHaveCount(0);const project=await save(page);expect(project.nativeWorkflow).toBe(true);expect(project.objects).toHaveLength(3);for(const object of project.objects){expect(object.native.layerConfigRanges).toHaveLength(2);expect(object.native.layerConfigRanges[0].settings.layer_height).toBe('0.12');expect(object.native.layerConfigRanges[0].settings.wall_loops).toBe('5');expect(object.native.layerConfigRanges[1].settings.outer_wall_speed).toBe('30');}
 const promise=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const imported=importNative3MF(await readFile(await(await promise).path()));for(const object of imported.objects)expect(object.native.layerConfigRanges).toEqual(project.objects[0].native.layerConfigRanges);
});
test('height editor rejects invalid ranges and nozzle bounds, supports inheritance and cancel without changing project',async({page})=>{
 const dialog=await load(page);await dialog.getByRole('button',{name:'Add height range'}).click();await dialog.getByLabel('Height range end').fill('0');await dialog.getByRole('button',{name:'Apply height ranges'}).click();await expect(dialog.getByRole('alert')).toContainText('end above the start');await dialog.getByLabel('Height range end').fill('4');await dialog.getByLabel('Search height range settings').fill('layer_height');await dialog.getByLabel('Layer height (layer_height)',{exact:true}).fill('0.9');await dialog.getByRole('button',{name:'Apply height ranges'}).click();await expect(dialog.getByRole('alert')).toContainText('between');await dialog.getByLabel('Layer height (layer_height)',{exact:true}).fill('0.16');await dialog.getByLabel('Search height range settings').fill('wall_loops');await dialog.getByLabel('Override height range wall_loops').check();await dialog.getByLabel('Wall loops (wall_loops)',{exact:true}).fill('8');await dialog.getByLabel('Override height range wall_loops').uncheck();await expect(dialog.getByLabel('Wall loops (wall_loops)',{exact:true})).toBeDisabled();await dialog.getByLabel('Search height range settings').fill('travel_speed');await expect(dialog.locator('[data-height-setting="travel_speed"]')).toHaveCount(0);await dialog.getByRole('button',{name:'Cancel changes'}).click();const project=await save(page);for(const object of project.objects)expect(object.native.layerConfigRanges).toBeUndefined();
});
test('removing the last saved range restores ordinary object settings through undo and redo',async({page})=>{
 const dialog=await load(page);await dialog.getByRole('button',{name:'Add height range'}).click();await dialog.getByRole('button',{name:'Apply height ranges'}).click();await page.getByRole('button',{name:'Height ranges',exact:true}).click();await dialog.getByRole('button',{name:'Remove height range'}).click();await dialog.getByRole('button',{name:'Apply height ranges'}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Height ranges',exact:true}).click();await expect(dialog.getByLabel('Selected height range').locator('option')).toHaveCount(1);await expect(dialog.getByLabel('Height range start')).toHaveValue('0');await dialog.getByRole('button',{name:'Cancel changes'}).click();await page.getByRole('button',{name:'Redo',exact:true}).click();const project=await save(page);for(const object of project.objects)expect(object.native.layerConfigRanges).toEqual([]);
});
