import {test,expect} from '@playwright/test';
const key='orca-web:native-startup-preferences-v1';
// These acceptance tests deliberately remove the Prepare preference used by
// the older editor suites and exercise the real native startup default.
test.use({storageState:{cookies:[],origins:[]}});
const home=page=>page.getByRole('main',{name:'Home',exact:true});
async function open(page){await page.goto('/');await expect(home(page)).toBeVisible({timeout:1500});}
async function preferences(page,change){await page.getByRole('button',{name:'Preferences',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Preferences'});await change(dialog);await dialog.getByRole('button',{name:'Close',exact:true}).click();}
async function model(page){await open(page);await home(page).getByRole('button',{name:'New project',exact:true}).click();await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Choose a 3D model').setInputFiles(new URL('../fixtures/cube.stl',import.meta.url).pathname);await expect(page.locator('.scene-object-row')).toHaveCount(1);}
test('native Home is the startup default; saved page choices apply only at the next startup',async({page})=>{await open(page);await expect(page.getByRole('button',{name:'Home',exact:true})).toHaveAttribute('aria-pressed','true');await preferences(page,async d=>{const select=d.getByLabel('Default page');await expect(select.locator('option')).toHaveText(['Home','Prepare']);await expect(select).toHaveValue('0');await select.selectOption('1');});await expect(home(page)).toBeVisible();await page.reload();await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await expect(home(page)).toHaveCount(0);await preferences(page,d=>d.getByLabel('Default page').selectOption('0'));await expect(page.getByLabel('Layer height',{exact:true})).toBeVisible();await page.reload();await expect(home(page)).toBeVisible();});
test('Home navigation preserves edited geometry and Undo without reloading the page',async({page})=>{await model(page);await page.evaluate(()=>{window.__homeNavigationToken='same document';});const input=page.getByLabel('position X',{exact:true}),before=await input.inputValue();await input.fill('37');await page.getByRole('button',{name:'Home',exact:true}).click();await expect(home(page)).toBeVisible();expect(await page.evaluate(()=>window.__homeNavigationToken)).toBe('same document');await page.getByRole('button',{name:'Prepare',exact:true}).click();await expect(input).toHaveValue('37');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(input).toHaveValue(before);await expect(page.locator('.scene-object-row')).toHaveCount(1);});
test('Home New project retains the existing discard decision and cancel leaves the old project intact',async({page})=>{await model(page);await page.getByRole('button',{name:'Home',exact:true}).click();await home(page).getByRole('button',{name:'New project',exact:true}).click();const d=page.getByRole('dialog',{name:'Unsaved project changes'});await d.getByRole('button',{name:'Keep editing'}).click();await expect(home(page)).toBeVisible();await home(page).getByRole('button',{name:'New project',exact:true}).click();await d.getByRole('button',{name:'Discard changes'}).click();await expect(page.getByLabel('Layer height',{exact:true})).toBeVisible();await expect(page.locator('.scene-object-row')).toHaveCount(0);});
test('Home Open project invokes the real file chooser and an invalid file preserves existing geometry',async({page})=>{await model(page);await page.getByRole('button',{name:'Home',exact:true}).click();const ready=page.waitForEvent('filechooser');await home(page).getByRole('button',{name:'Open project',exact:true}).click();await(await ready).setFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('not a project')});await expect(page.getByRole('alert')).toBeVisible();await expect(home(page)).toBeVisible();await page.getByRole('button',{name:'Prepare',exact:true}).click();await expect(page.locator('.scene-object-row')).toHaveCount(1);});
test('invalid startup storage falls back to Home and failed writes explain the next launch behavior',async({page})=>{await page.addInitScript(k=>{localStorage.setItem(k,'{"version":99,"default_page":"1"}');const original=Storage.prototype.setItem;Storage.prototype.setItem=function(name,value){if(name===k)throw Error('denied');return original.call(this,name,value);};},key);await open(page);await preferences(page,async d=>{await expect(d.getByLabel('Default page')).toHaveValue('0');await d.getByLabel('Default page').selectOption('1');await expect(d.getByRole('alert')).toHaveText('Startup page could not be saved. Reopening the app will use the previous startup setting.');});await page.reload();await expect(home(page)).toBeVisible();});
for(const theme of ['light','dark'])test(`native Home action assets and compact ${theme} layout are readable and keyboard operable`,async({page},info)=>{await page.setViewportSize({width:600,height:700});await page.addInitScript(value=>localStorage.setItem('orca-web-theme',value),theme);await open(page);const actions=home(page).getByRole('button');await expect(actions).toHaveCount(2);for(const button of await actions.all()){await expect(button).toBeInViewport();await expect(button).toHaveCSS('border-radius','12px');await expect(button.locator('img')).toHaveCSS('width','56px');expect(await button.locator('img').evaluate(e=>e.complete&&e.naturalWidth>0)).toBe(true);}expect(await home(page).evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);await page.screenshot({path:info.outputPath(`native-home-${theme}.png`)});await home(page).getByRole('button',{name:'New project',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();});
