import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{importNative3MF}from'../../shared/native-project.js';import{serializeProject}from'../../shared/project.js';import{transformPositions,meshBounds}from'../../shared/geometry.js';
async function fixture({occluded=false,modifier=false}={}){const p=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url))),original=p.objects[0];p.useEmbeddedSettings=true;p.name='Selection';p.objects=['Alpha','Beta','Gamma'].map((name,i)=>({...structuredClone(original),id:name,name,position:occluded?[60,60,i===1?30:0]:[40+i*40,60,0],native:{...original.native,instanceFamily:undefined,groupId:modifier?'same':name,objectName:name,partType:modifier&&i===1?'negative_part':'normal_part'}}));if(occluded)p.objects=p.objects.slice(0,2);p.selectedId='Alpha';p.selectedIds=['Alpha'];p.selectionScope='object';p.selectionFrame=null;return p;}
async function load(page,p){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles({name:'Selection.json',mimeType:'application/json',buffer:Buffer.from(serializeProject(p))});await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();}
const row=(page,name)=>page.locator('.scene-object-list').getByRole('button',{name,exact:true}).last();
async function save(page){const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Save project',exact:true}).click();return JSON.parse(await readFile(await(await pending).path(),'utf8'));}
async function top(page){await page.locator('.scene-views').getByRole('button',{name:'Top',exact:true}).click();const perspective=page.locator('.scene-views').getByRole('button',{name:'Perspective',exact:true});if(await perspective.count())await perspective.click();await page.locator('.scene-views').getByRole('button',{name:'Top',exact:true}).click();return page.getByRole('img',{name:'Interactive 3D model view'});}
async function rectangle(page,canvas,{command=false}={}){const b=await canvas.boundingBox();await page.keyboard.down('Shift');if(command)await page.keyboard.down('Control');await page.mouse.move(b.x+8,b.y+60);await page.mouse.down();await page.mouse.move(b.x+b.width-8,b.y+b.height-50,{steps:3});await expect(page.getByLabel('Selection rectangle',{exact:true})).toBeVisible();await page.mouse.up();await page.keyboard.up('Shift');if(command)await page.keyboard.up('Control');await expect(page.getByLabel('Selection rectangle',{exact:true})).toHaveCount(0);}
test('tree toggles and ranges select complete targets, shortcuts respect text inputs, and single-object tools cannot mutate the primary',async({page})=>{
 const p=await fixture();await load(page,p);await row(page,'Beta').click({modifiers:['Control']});await expect(page.getByLabel('Selection count')).toContainText('2 objects');await expect(row(page,'Alpha')).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('button',{name:'Cut',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Paint supports',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Split shells',exact:true})).toBeDisabled();await expect(page.getByLabel('Object name',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Place on face',exact:true})).toBeDisabled();
 await row(page,'Alpha').click({modifiers:['Meta']});await expect(row(page,'Alpha')).toHaveAttribute('aria-pressed','false');await expect(page.getByLabel('Selection count')).toContainText('1 objects');await row(page,'Alpha').click();await row(page,'Gamma').click({modifiers:['Shift']});await expect(page.getByLabel('Selection count')).toContainText('3 objects');
 await page.keyboard.press('Control+Shift+A');await expect(page.getByLabel('Selection count')).toContainText('3 objects');await page.getByRole('button',{name:'Deselect all',exact:true}).click();await expect(page.getByLabel('Selection count')).toContainText('0 objects');await page.keyboard.press('Control+A');await expect(page.getByLabel('Selection count')).toContainText('3 objects');await page.getByLabel('position X',{exact:true}).focus();await page.keyboard.press('Control+A');await expect(page.getByLabel('Selection count')).toContainText('3 objects');await page.getByRole('button',{name:'Deselect all',exact:true}).click();await expect(page.getByLabel('Selection count')).toContainText('0 objects');
});
test('joint numeric transforms survive project save/reload and undo; center/drop and batch duplicate/delete preserve relative geometry',async({page})=>{
 const p=await fixture();await load(page,p);await row(page,'Beta').click({modifiers:['Control']});await page.getByLabel('rotation Z',{exact:true}).fill('90');await page.getByLabel('Uniform scaling').uncheck();await page.getByLabel('scale X',{exact:true}).fill('1.5');await page.getByLabel('position X',{exact:true}).fill('5');const edited=await save(page);expect(edited.selectionFrame.rotation).toEqual([0,0,90]);expect(edited.selectionFrame.scale).toEqual([1.5,1,1]);expect(edited.selectedIds).toEqual(['Alpha','Beta']);expect(edited.objects[2]).toEqual(p.objects[2]);
 await page.getByLabel('Open Orca Web project').setInputFiles({name:'Saved.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(edited))});await expect(page.getByLabel('position X',{exact:true})).toHaveValue('5');await expect(page.getByLabel('rotation Z',{exact:true})).toHaveValue('90');await page.getByLabel('position Z',{exact:true}).fill('7');await page.getByRole('button',{name:'Drop to bed',exact:true}).click();await expect(page.getByLabel('position Z',{exact:true})).toHaveValue('0');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('position Z',{exact:true})).toHaveValue('7');await page.getByRole('button',{name:'Redo',exact:true}).click();
 await page.getByRole('button',{name:'Center',exact:true}).click();const centered=await save(page),a=meshBounds(centered.objects[0]),b=meshBounds(centered.objects[1]);expect(b.center[1]-a.center[1]).toBeCloseTo(60,5);expect(a.min[2]).toBe(0);await page.getByRole('button',{name:'Duplicate',exact:true}).click();await expect(page.locator('.scene-object-row')).toHaveCount(5);const duplicated=await save(page);expect(duplicated.selectedIds).toHaveLength(2);expect(new Set(duplicated.objects.map(o=>o.native.groupId)).size).toBe(5);await page.getByRole('button',{name:'Delete object',exact:true}).click();await expect(page.locator('.scene-object-row')).toHaveCount(3);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.scene-object-row')).toHaveCount(5);await expect(page.getByLabel('Selection count')).toContainText('2 objects');
});
test('canvas Cmd/Ctrl click toggles hit objects and Shift rectangle picks visible depth IDs instead of occluded bounds',async({page})=>{
 await load(page,await fixture({occluded:true}));const canvas=await top(page),box=await canvas.boundingBox();await page.mouse.click(box.x+box.width/2,box.y+box.height/2);
 await expect(row(page,'Beta')).toHaveAttribute('aria-pressed','true');await row(page,'Alpha').click();await page.keyboard.down('Control');await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await page.keyboard.up('Control');await expect(page.getByLabel('Selection count')).toContainText('2 objects');await page.keyboard.down('Meta');await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await page.keyboard.up('Meta');await expect(page.getByLabel('Selection count')).toContainText('1 objects');
 await rectangle(page,canvas);await expect(canvas).toHaveAttribute('data-rectangle-hits','["Beta"]');await expect(row(page,'Alpha')).toHaveAttribute('aria-pressed','false');await expect(row(page,'Beta')).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Select all',exact:true}).click();await rectangle(page,canvas);await expect(page.getByLabel('Selection count')).toContainText('2 objects');
});
test('rectangle adds with control, modifier-only hits stay in part scope, and the saved scope survives reload',async({page})=>{
 const p=await fixture({occluded:true,modifier:true});await load(page,p);await page.getByRole('button',{name:'Deselect all',exact:true}).click();const canvas=await top(page);await rectangle(page,canvas);await expect(canvas).toHaveAttribute('data-rectangle-hits','["Beta"]');await expect(page.getByLabel('Transform scope')).toHaveValue('part');await expect(row(page,'Alpha')).toHaveAttribute('aria-pressed','false');await expect(row(page,'Beta')).toHaveAttribute('aria-pressed','true');const saved=await save(page);expect(saved.selectedIds).toEqual(['Beta']);expect(saved.selectionScope).toBe('part');await page.getByLabel('Open Orca Web project').setInputFiles({name:'Part.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(saved))});await expect(page.getByLabel('Transform scope')).toHaveValue('part');await row(page,'Alpha').click();await rectangle(page,canvas,{command:true});await expect(page.getByLabel('Selection count')).toContainText('2 parts');
});
test('joint gizmo translation updates both meshes in a single history step',async({page})=>{
 const p=await fixture();p.objects=p.objects.slice(0,2);await load(page,p);await page.getByRole('button',{name:'Select all',exact:true}).click();const canvas=await top(page);await page.getByRole('button',{name:'Move',exact:true}).click();const box=await canvas.boundingBox(),x=box.x+box.width/2,y=box.y+box.height/2;await page.mouse.move(x+box.height*0.12,y);await page.mouse.down();await page.mouse.move(x+box.height*0.23,y,{steps:5});await page.mouse.up();await expect.poll(async()=>Number(await page.getByLabel('position X',{exact:true}).inputValue())).toBeGreaterThan(1);const saved=await save(page),delta=meshBounds(saved.objects[0]).center[0]-meshBounds(p.objects[0]).center[0];expect(meshBounds(saved.objects[1]).center[0]-meshBounds(p.objects[1]).center[0]).toBeCloseTo(delta,5);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('position X',{exact:true})).toHaveValue('0');
});

test.describe('retina selection',()=>{test.use({deviceScaleFactor:2});test('rectangle ID picking uses backing pixels and keeps hidden and occluded objects out',async({page})=>{
 const p=await fixture({occluded:true});p.objects.push({...structuredClone(p.objects[0]),id:'Hidden',name:'Hidden',visible:false,position:[90,60,40],native:{...p.objects[0].native,groupId:'Hidden',objectName:'Hidden'}});await load(page,p);const canvas=await top(page);await rectangle(page,canvas);await expect(canvas).toHaveAttribute('data-rectangle-hits','["Beta"]');await expect(row(page,'Hidden')).toHaveAttribute('aria-pressed','false');await expect(row(page,'Alpha')).toHaveAttribute('aria-pressed','false');
});});
