import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {multipartFixture} from '../fixtures/multipart-project.js';
import {fixture} from '../fixtures/native-instance-project.js';
import {exportNative3MF,importNative3MF} from '../../shared/native-project.js';
import {parseProject} from '../../shared/project.js';
import {sceneBounds,meshBounds} from '../../shared/geometry.js';
const cube=new URL('../fixtures/cube.stl',import.meta.url).pathname;
const file=(p=multipartFixture())=>({name:'Stack.3mf',mimeType:'model/3mf',buffer:Buffer.from(exportNative3MF(p))});
const dialog=p=>p.getByRole('dialog',{name:'Multi-part object detected'});
async function start(page){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByRole('button',{name:'Preferences',exact:true}).click();const d=page.getByRole('dialog',{name:'Preferences'});await d.getByLabel('Load behaviour').selectOption('load_geometry_only');await d.getByRole('button',{name:'Close',exact:true}).click();}
async function save(page){const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Save project',exact:true}).click();return parseProject(await readFile(await(await pending).path(),'utf8'));}
test('native multipart Yes retains relative heights as one model, preserves current presets and participates in one Undo',async({page},info)=>{await start(page);await page.getByLabel('Layer height',{exact:true}).fill('0.25');await page.getByLabel('Choose a 3D model').setInputFiles(cube);await page.getByLabel('Choose a 3D model').setInputFiles(file());await expect(dialog(page)).toContainText('several objects positioned at multiple heights');await expect(page.getByRole('dialog')).toHaveCount(1);await expect(page.getByLabel('position X',{exact:true})).toBeDisabled();await page.keyboard.press('Control+z');await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(1);await page.screenshot({path:info.outputPath('native-multipart-choice.png')});await dialog(page).getByRole('button',{name:'Yes',exact:true}).click();await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(2);const p=await save(page),added=p.objects.slice(1);expect(added).toHaveLength(2);expect(new Set(added.map(o=>o.native.groupId)).size).toBe(1);expect(sceneBounds(added).size[2]).toBe(40);expect(added.map(o=>o.name)).toEqual(['Bottom','Top']);expect(p.overrides.layer_height).toBe('0.25');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(1);await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(2);});
for(const action of ['No','Escape'])test(`multipart ${action} keeps separate objects and grounds each independently`,async({page})=>{await start(page);await page.getByLabel('Choose a 3D model').setInputFiles(file());await expect(dialog(page)).toBeVisible();if(action==='Escape')await page.keyboard.press('Escape');else await dialog(page).getByRole('button',{name:'No',exact:true}).click();await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(2);const p=await save(page);expect(p.objects).toHaveLength(2);expect(new Set(p.objects.map(o=>o.native.groupId)).size).toBe(2);expect(p.objects.map(o=>meshBounds(o).min[2])).toEqual([0,0]);});
test('explicit geometry Open asks discard before multipart, then exports one two-volume object at full height',async({page})=>{await start(page);await page.getByLabel('Choose a 3D model').setInputFiles(cube);await page.getByLabel('Open Orca Web project').setInputFiles(file());await expect(dialog(page)).toHaveCount(0);await page.getByRole('button',{name:'Discard changes',exact:true}).click();await dialog(page).getByRole('button',{name:'Yes',exact:true}).click();await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(1);await page.getByRole('button',{name:'Project',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const p=importNative3MF(await readFile(await(await pending).path()));expect(p.objects).toHaveLength(2);expect(new Set(p.objects.map(o=>o.native.groupId)).size).toBe(1);expect(sceneBounds(p.objects).size[2]).toBe(40);});
test('linked instances and an existing multi-volume model do not trigger the multipart object question',async({page})=>{await start(page);for(const parts of [1,2]){const loaded=page.waitForResponse(r=>r.url().endsWith('/api/projects/import')&&r.request().method()==='POST');await page.getByLabel('Choose a 3D model').setInputFiles(file(fixture({parts})));expect((await loaded).status()).toBe(200);await expect(page.getByRole('dialog')).toHaveCount(0);}const p=await save(page);expect(p.objects).toHaveLength(6);expect(new Set(p.objects.map(o=>o.native.instanceFamily)).size).toBe(2);});
for(const theme of ['light','dark'])test(`multipart ${theme} dialog uses native warning dimensions, choice buttons and fits compact windows`,async({page},info)=>{await page.addInitScript(value=>localStorage.setItem('orca-web-theme',value),theme);await start(page);await page.setViewportSize({width:520,height:720});await page.getByLabel('Choose a 3D model').setInputFiles(file());await expect(dialog(page)).toBeVisible();await expect(dialog(page).locator('p')).toContainText('heights. Instead');await expect(dialog(page).locator('p')).toContainText('should the file');await expect(dialog(page).getByRole('img',{name:'Warning'})).toHaveAttribute('src','/native-dialogs/exclamation.svg');const image=await dialog(page).getByRole('img',{name:'Warning'}).boundingBox();expect(image.width).toBe(64);expect(image.height).toBe(64);const yes=dialog(page).getByRole('button',{name:'Yes',exact:true});await expect(yes).toBeFocused();await expect(yes).toHaveCSS('background-color','rgb(0, 150, 136)');await expect(yes).toHaveCSS('border-radius','4px');expect((await yes.boundingBox()).width).toBeGreaterThanOrEqual(100);const box=await dialog(page).boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(520);await page.screenshot({path:info.outputPath(`native-multipart-${theme}-compact.png`)});await dialog(page).getByRole('button',{name:'No',exact:true}).click();await expect(dialog(page)).toHaveCount(0);});
