import{test,expect}from'@playwright/test';import path from'node:path';
const cube=path.resolve('tests/fixtures/cube.stl');
async function load(page){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Choose a 3D model').setInputFiles(cube);await expect(page.getByText('Triangles: 12',{exact:true})).toBeVisible();}
async function chooser(page,key,accept){const pending=page.waitForEvent('filechooser');await page.keyboard.press(key);const choice=await pending;expect(await choice.element().getAttribute('accept')).toBe(accept);}
test('native Open/Import shortcuts choose distinct file inputs and saving stays functional',async({page})=>{await load(page);await chooser(page,'ControlOrMeta+o','.json,.3mf');await chooser(page,'ControlOrMeta+i','.stl,.obj,.3mf,.amf,.svg,.step,.stp');const download=page.waitForEvent('download');await page.keyboard.press('ControlOrMeta+Shift+s');expect((await download).suggestedFilename()).toMatch(/\.orca-web\.json$/);});
test('native Delete All spans all plates and undo restores geometry and plate membership',async({page})=>{await load(page);await page.getByRole('button',{name:'＋ Add plate',exact:true}).click();await page.getByLabel('Choose a 3D model').setInputFiles(cube);await expect(page.getByText('2 objects · 2 plates',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Select',exact:true}).click();await page.keyboard.press('ControlOrMeta+d');await expect(page.getByText('0 objects · 2 plates',{exact:true})).toBeVisible();await page.keyboard.press('ControlOrMeta+z');await expect(page.getByText('2 objects · 2 plates',{exact:true})).toBeVisible();await expect(page.getByText('Triangles: 12',{exact:true})).toBeVisible();});
test('modal editors and focused fields block scene shortcuts while native nudge and camera commands act on Prepare',async({page})=>{await load(page);const x=Number(await page.getByLabel('position X',{exact:true}).inputValue()),y=Number(await page.getByLabel('position Y',{exact:true}).inputValue());await page.getByRole('button',{name:'Select',exact:true}).click();await page.keyboard.press('ArrowUp');await expect(page.getByLabel('position Y',{exact:true})).toHaveValue(String(y+10));await page.keyboard.press('Shift+ArrowLeft');await expect(page.getByLabel('position X',{exact:true})).toHaveValue(String(x-1));await page.keyboard.press('ControlOrMeta+1');await expect(page.locator('.scene-renderer canvas').first()).toHaveAttribute('data-camera-view','Top');await page.getByLabel('position X',{exact:true}).focus();await page.keyboard.press('ControlOrMeta+d');await expect(page.getByText('Triangles: 12',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Select',exact:true}).click();await page.keyboard.press('ControlOrMeta+n');const modal=page.getByRole('dialog',{name:'Unsaved project changes'});await expect(modal).toBeVisible();await page.keyboard.press('ControlOrMeta+d');await page.keyboard.press('Delete');await expect(page.getByText('Triangles: 12',{exact:true})).toBeVisible();await modal.getByRole('button',{name:'Keep editing'}).click();await page.keyboard.press('?');await expect(page.getByRole('dialog',{name:'Keyboard shortcuts'})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByLabel('Selection count')).toContainText('1 object');});
test('native tool keys open the correct editor and avoid changing tool state beneath open dialogs',async({page})=>{await load(page);await page.getByRole('button',{name:'Select',exact:true}).click();await page.keyboard.press('c');await expect(page.getByRole('dialog',{name:'Cut object'})).toBeVisible();await page.keyboard.press('r');await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Select',exact:true})).toHaveClass(/active/);await page.keyboard.press('f');await expect(page.getByText('Click a model face to place it on the bed.')).toBeVisible();await page.keyboard.press('r');await expect(page.getByRole('button',{name:'Rotate',exact:true})).toHaveClass(/active/);});
test('native slice and G-code export shortcuts follow actual job readiness',async({page})=>{await load(page);await page.getByRole('button',{name:'Select',exact:true}).click();await page.keyboard.press('ControlOrMeta+r');await expect(page.getByText('✓ Ready to print',{exact:true})).toBeVisible({timeout:15000});const pending=page.waitForEvent('download');await page.keyboard.press('ControlOrMeta+g');expect((await pending).suggestedFilename()).toMatch(/\.gcode$/);});
