import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{nativePreviewVolumeVertexShader}from'../../src/preview-volume-shader.js';
test('travel/wipe/extrusion tubes match original native GLSL eye positions and lighting through corner, vertical, cusp and bias branches',async({page})=>{
 const fixture=JSON.parse(await readFile(new URL('../fixtures/native-motion-geometry-reference.json',import.meta.url))),cases=[];for(const sample of fixture.cases)for(let i=0;i<sample.vertices.length-1;i++)if(sample.expected.valid[i]&&[8,9,10].includes(sample.vertices[i][5]))cases.push({name:sample.name,start:sample.expected.positions[i].slice(0,3),end:sample.expected.positions[i+1].slice(0,3),hwaStart:sample.expected.hwa[i],hwaEnd:sample.expected.hwa[i+1]});
 await page.goto('/');const results=await page.evaluate(({production,reference,cases})=>{
  const gl=document.createElement('canvas').getContext('webgl2');if(!gl)throw Error('WebGL2 required');const compile=(type,text)=>{const s=gl.createShader(type);gl.shaderSource(s,text);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
  // Reference retains native frame/math; only its buffer I/O is represented by
  // constant attributes, as WebGL does not expose native samplerBuffer.
  reference=reference.replace('#version 150\n','precision highp float;\nprecision highp int;\n').replace('height_width_angle.z == 0','height_width_angle.z == 0.0').replace(/uniform (?:u?samplerBuffer) \w+;\n/g,'').replace('in int vertex_id;','in float native_vertex_id;\nin vec3 native_start;\nin vec3 native_end;\nin vec4 native_hwa_start;\nin vec4 native_hwa_end;\nin vec3 native_color_start;\nin vec3 native_color_end;').replace('  int id_a = int(texelFetch(segment_index_tex, gl_InstanceID).r);','  int vertex_id=int(native_vertex_id);\n  int id_a=0;').replace('texelFetch(position_tex, id_a).xyz','native_start').replace('texelFetch(position_tex, id_b).xyz','native_end').replace('texelFetch(height_width_angle_tex, id)','(id==id_a?native_hwa_start:native_hwa_end)').replace('texelFetch(height_width_angle_tex, closer_id).xyz','(closer_id==id_a?native_hwa_start.xyz:native_hwa_end.xyz)').replace('decode_color(texelFetch(color_tex, id).r)','(id==id_a?native_color_start:native_color_end)');
  const identity=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],webView=[1,0,0,0,0,1,0,0,0,0,1,0,-20,-30,-40,1],nativeView=[1,0,0,0,0,0,-1,0,0,1,0,0,-20,-30,-40,1],result=[];
  for(const[shader,native]of[[production,false],[reference,true]]){const source='#version 300 es\n'+shader.replace('out vec3 color;','out vec3 color;\nout vec3 probe_position;').replace('  gl_Position =','  probe_position=eye_position;\n  gl_Position ='),program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,source));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,'#version 300 es\nprecision highp float;in vec3 color;out vec4 c;void main(){c=vec4(color,1);}'));gl.transformFeedbackVaryings(program,['probe_position','color'],gl.INTERLEAVED_ATTRIBS);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);gl.bindVertexArray(gl.createVertexArray());gl.bindBuffer(gl.ARRAY_BUFFER,gl.createBuffer());gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([0,1,2,3,4,5,6,7]),gl.STATIC_DRAW);const id=gl.getAttribLocation(program,'native_vertex_id');gl.enableVertexAttribArray(id);gl.vertexAttribPointer(id,1,gl.FLOAT,false,0,0);gl.uniformMatrix4fv(gl.getUniformLocation(program,native?'view_matrix':'viewMatrix'),false,new Float32Array(native?nativeView:webView));gl.uniformMatrix4fv(gl.getUniformLocation(program,native?'projection_matrix':'projectionMatrix'),false,new Float32Array(identity));gl.uniform3fv(gl.getUniformLocation(program,'camera_position'),[20,-40,30]);const output=gl.createBuffer();gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,output);gl.bufferData(gl.TRANSFORM_FEEDBACK_BUFFER,8*6*4,gl.STREAM_READ);gl.enable(gl.RASTERIZER_DISCARD);const samples=[];
   for(const c of cases){for(const[name,value]of[['native_start',c.start],['native_end',c.end],['native_hwa_start',c.hwaStart],['native_hwa_end',c.hwaEnd],['native_color_start',[.2,.4,.8]],['native_color_end',[.8,.4,.2]]]){const at=gl.getAttribLocation(program,name);if(name.startsWith('native_hwa'))gl.vertexAttrib4fv(at,value);else gl.vertexAttrib3fv(at,value);}gl.beginTransformFeedback(gl.POINTS);gl.drawArrays(gl.POINTS,0,8);gl.endTransformFeedback();const value=new Float32Array(48);gl.getBufferSubData(gl.TRANSFORM_FEEDBACK_BUFFER,0,value);samples.push([...value]);}result.push(samples);gl.disable(gl.RASTERIZER_DISCARD);gl.deleteProgram(program);
  }const error=gl.getError();gl.getExtension('WEBGL_lose_context')?.loseContext();if(error!==gl.NO_ERROR)throw Error('WebGL error '+error);return result;
 },{production:nativePreviewVolumeVertexShader,reference:fixture.originalVertexShader,cases});
 expect(cases.length).toBe(37);for(let c=0;c<cases.length;c++)for(let i=0;i<48;i++)expect(Math.abs(results[0][c][i]-results[1][c][i]),`${cases[c].name} coordinate/color ${i}`).toBeLessThan(1e-6);
});
