import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{fixture}from'../fixtures/native-instance-project.js';import{importNative3MF}from'../../shared/native-project.js';
const reference=JSON.parse(await readFile(new URL('../fixtures/native-instance-cut-reference.json',import.meta.url)));
async function start(page){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();const project=fixture();project.ids=(await(await page.request.get('/api/presets')).json()).defaults;project.filamentIds=[project.ids.filamentId];await page.getByLabel('Open Orca Web project').setInputFiles({name:'Linked cut.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await expect(page.locator('[data-tree-kind=object]')).toHaveCount(1);await expect(page.locator('[data-tree-kind=volume]')).toHaveCount(2);await expect(page.locator('[data-tree-kind=instance]')).toHaveCount(2);return project;}
async function save(page){await page.getByRole('button',{name:'Project',exact:true}).click();const pending=page.waitForEvent('download');await page.locator('.project-actions').getByRole('button',{name:'Save project',exact:true}).click();const project=JSON.parse(await readFile(await(await pending).path(),'utf8'));await page.getByRole('button',{name:'Prepare',exact:true}).click();return project;}
function response(request){const expected=reference.cases[request.results.some(r=>r.flip)?4:0].expected;return{format:'orca-native-instance-cut',version:1,sourceRevision:reference.sourceCommit,selectedInstanceId:request.selectedInstanceId,results:request.results.map((result,i)=>({id:result.id,side:result.side,minimumZBeforeGrounding:expected[i].minimumZBeforeGrounding,minimumZAfterGrounding:expected[i].minimumZAfterGrounding,instances:request.instances.map((instance,k)=>({...instance,matrix:expected[i].instances[k]}))}))};}
test('linked Cut previews both peer families, requires painting consent and commits one native identity/selection/Undo transaction',async({page},info)=>{let posted;await page.route('**/api/geometry/instance-cut',route=>{posted=route.request().postDataJSON();return route.fulfill({json:response(posted)});});await start(page);const before=await save(page);await page.getByRole('button',{name:'Cut',exact:true}).click();const d=page.getByRole('dialog',{name:'Cut object'});await expect(d.getByLabel('Cut result placement')).toHaveValue('original');await expect(d.getByRole('status')).toContainText('8 retained parts');expect(posted.operation).toBe('instance-cut-frames');expect(posted.instances).toHaveLength(2);await expect(d.getByRole('button',{name:'Apply cut',exact:true})).toBeDisabled();await d.getByLabel('Clear painting from cut parts').check();await d.getByRole('button',{name:'Apply cut',exact:true}).click();await expect(page.locator('[data-tree-kind=object]')).toHaveCount(2);await expect(page.locator('[data-tree-kind=volume]')).toHaveCount(4);await expect(page.locator('[data-tree-kind=instance]')).toHaveCount(4);await expect(page.getByLabel('Selection count')).toContainText('4 objects');const after=await save(page);expect(after.objects.every(o=>!o.painting)).toBe(true);expect(new Set(after.objects.map(o=>o.native.instanceFamily)).size).toBe(2);expect(after.selectedIds).toHaveLength(8);await page.getByRole('button',{name:'Undo',exact:true}).click();expect((await save(page)).objects).toEqual(before.objects);await page.getByRole('button',{name:'Redo',exact:true}).click();expect((await save(page)).objects).toEqual(after.objects);await page.getByRole('button',{name:'Project',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const restored=importNative3MF(await readFile(await(await pending).path()));expect(restored.objects).toHaveLength(8);expect(new Set(restored.objects.map(o=>o.native.instanceFamily)).size).toBe(2);await page.getByRole('button',{name:'Prepare',exact:true}).click();await page.screenshot({path:info.outputPath('linked-cut.png')});});
test('native Cut flags submit current choices, while cancellation discards a late preview and keeps history unchanged',async({page})=>{let requests=[],release;await page.route('**/api/geometry/instance-cut',async route=>{const data=route.request().postDataJSON();requests.push(data);if(requests.length>1)await new Promise(r=>release=r);await route.fulfill({json:response(data)}).catch(()=>{});});await start(page);const before=await save(page);await page.getByRole('button',{name:'Cut',exact:true}).click();const d=page.getByRole('dialog',{name:'Cut object'});await expect(d.getByRole('status')).toContainText('8 retained parts');await d.getByLabel('upper flip',{exact:true}).check();await expect.poll(()=>requests.length).toBe(2);expect(requests[1].results[0].flip).toBe(true);await d.getByRole('button',{name:'Cancel cut',exact:true}).click();release();expect((await save(page)).objects).toEqual(before.objects);});
test('unavailable native linked Cut refuses mutation and gives the native error without cutting one peer',async({page})=>{await page.route('**/api/geometry/instance-cut',route=>route.fulfill({status:503,json:{error:'Native arrangement helper is not installed. Build it with npm run build:native:arrange.'}}));await start(page);const before=await save(page);await page.getByRole('button',{name:'Cut',exact:true}).click();const d=page.getByRole('dialog',{name:'Cut object'});await expect(d.getByRole('alert')).toContainText('build:native:arrange');await expect(d.getByRole('button',{name:'Apply cut',exact:true})).toBeDisabled();await d.getByRole('button',{name:'Cancel cut',exact:true}).click();expect((await save(page)).objects).toEqual(before.objects);});

test('browser bed contract cuts linked instances across two plates without changing their plate-local placement',async({page})=>{
 let posted;await page.route('**/api/geometry/instance-cut',route=>{posted=route.request().postDataJSON();const expected=reference.cases[7].expected;return route.fulfill({json:{format:'orca-native-instance-cut',version:1,sourceRevision:reference.sourceCommit,selectedInstanceId:posted.selectedInstanceId,results:posted.results.map((result,index)=>({id:result.id,side:result.side,minimumZBeforeGrounding:expected[index].minimumZBeforeGrounding,minimumZAfterGrounding:expected[index].minimumZAfterGrounding,instances:posted.instances.map((instance,k)=>({...instance,matrix:expected[index].instances[k]}))}))}});});
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();const project=fixture();project.ids=(await(await page.request.get('/api/presets')).json()).defaults;project.filamentIds=[project.ids.filamentId];project.plates.push({id:'plate-2',name:'Plate 2'});for(const o of project.objects){delete o.painting;if(o.id.startsWith('i1'))o.plateId='plate-2';}project.activePlateId='plate-2';project.selectedId='i1p0';project.selectedIds=['i1p0'];
 await page.getByLabel('Open Orca Web project').setInputFiles({name:'Linked two plates.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await expect(page.locator('[data-tree-kind=object]')).toHaveCount(1);await expect(page.locator('[data-tree-kind=instance]')).toHaveCount(2);const before=await save(page);
 await page.getByRole('button',{name:'Cut',exact:true}).click();const d=page.getByRole('dialog',{name:'Cut object'});await expect(d.getByRole('status')).toContainText('8 retained parts');expect(posted.instances.map(i=>i.matrix[12])).toEqual([40,400]);await d.getByRole('button',{name:'Apply cut',exact:true}).click();
 const result=await save(page);expect(result.objects.filter(o=>o.plateId==='plate-1')).toHaveLength(4);expect(result.objects.filter(o=>o.plateId==='plate-2')).toHaveLength(4);expect(result.selectedIds).toHaveLength(4);expect(result.selectedIds.every(id=>result.objects.find(o=>o.id===id).plateId==='plate-2')).toBe(true);expect(result.objects.every(o=>Math.max(...o.positions.filter((_,i)=>i%3===0))<150)).toBe(true);
 await page.getByRole('button',{name:'Undo',exact:true}).click();expect((await save(page)).objects).toEqual(before.objects);
});
