import{test,expect}from'@playwright/test';import{build}from'esbuild';import{readFile}from'node:fs/promises';import path from'node:path';
import{prepareMultiPatternFixture}from'../fixtures/pa-pattern-multiplate.js';import{importNative3MF}from'../../shared/native-project.js';
let script,css,fixture;
test.beforeAll(async()=>{const output=await build({entryPoints:[path.resolve('src/main.jsx')],bundle:true,write:false,outdir:'unused-multi-pattern-harness',format:'esm',define:{'process.env.NODE_ENV':'"production"'}});script=output.outputFiles.find(file=>file.path.endsWith('.js')).text;css=output.outputFiles.find(file=>file.path.endsWith('.css')).text;fixture=await prepareMultiPatternFixture();});
async function open(page,{generate=true}={}){
 await page.route('**/multi-pattern-harness',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><link rel="stylesheet" href="/multi-pattern.css"></head><body><div id="root"></div><script type="module" src="/multi-pattern.js"></script></body></html>'}));await page.route('**/multi-pattern.js',route=>route.fulfill({contentType:'text/javascript',body:script}));await page.route('**/multi-pattern.css',route=>route.fulfill({contentType:'text/css',body:css}));
 const {nativeProject,...prepared}=fixture.prepared;await page.route('**/api/calibrations/prepare',route=>route.fulfill({json:{...prepared,calibration:{...prepared.calibration,token:'a'.repeat(64)}}}));let submitted;await page.route('**/api/jobs/calibration',route=>{submitted=route.request().postDataJSON();return route.fulfill({status:202,json:{id:'transport-only',status:'failed',error:'Transport fixture only; native slicing is tested separately.'}})});
 const exported=[];let ordinary=0;await page.route('**/api/calibrations/project',route=>{const body=route.request().postDataJSON();exported.push(body);const project=body.allPlates?nativeProject:nativeProject.plateProjects[body.plateId];return route.fulfill({contentType:'model/3mf',body:Buffer.from(project.bytes)})});if(generate)await page.route('**/api/projects/export',route=>{ordinary++;return route.fulfill({status:500,json:{error:'No handle-only export'}})});
 await page.goto('/multi-pattern-harness');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();
 if(generate){await page.getByRole('button',{name:'Calibration',exact:true}).click();await page.getByRole('menuitem',{name:'Generate calibration…'}).click();await page.getByLabel('Calibration test',{exact:true}).selectOption('pressure-advance-pattern');await expect(page.getByText('Complete patterns are placed on additional rectangular plates',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Generate calibration',exact:true}).click();await expect(page.getByRole('dialog',{name:'Calibration',exact:true})).not.toBeVisible();}
 return{exported,submitted:()=>submitted,ordinary:()=>ordinary};
}
test('generated batch keeps plate assignments and submits the full bound scene with the selected plate',async({page})=>{const state=await open(page);await expect(page.getByText('Objects: 6',{exact:true})).toBeVisible();await page.locator('.plate-tabs').getByRole('button',{name:'Plate 2',exact:true}).click();await expect(page.getByText('Objects: 2',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Slice model',exact:true}).click();await expect.poll(()=>state.submitted()?.plateId).toBe('plate-2');expect(state.submitted().objects).toHaveLength(8);expect(state.submitted().objects.filter(object=>object.plateId==='plate-2')).toHaveLength(2);expect(state.submitted().calibration.token).toBe('a'.repeat(64));});
test('selected calibration 3MF export has four complete layers and native project export keeps both plates',async({page})=>{const state=await open(page);await page.locator('.plate-tabs').getByRole('button',{name:'Plate 2',exact:true}).click();await page.getByRole('button',{name:'Project',exact:true}).click();for(const [button,allPlates,count,objects]of[['Export plate as 3MF',false,1,2],['Export native project',true,2,8]]){const waiting=page.waitForEvent('download');await page.getByRole('button',{name:button,exact:true}).click();const project=importNative3MF(await readFile(await(await waiting).path()));expect(project.plates).toHaveLength(count);expect(project.objects).toHaveLength(objects);expect(project.plates.every(plate=>plate.layerEvents.items.length===4)).toBe(true);expect(state.exported.at(-1).allPlates).toBe(allPlates);expect(state.exported.at(-1).plateId).toBe('plate-2');expect(state.exported.at(-1).objects).toHaveLength(8);}expect(state.ordinary()).toBe(0);});
test('imported complete generated batch permits plate switching and selected export while blocking geometry edits',async({page})=>{await open(page,{generate:false});await page.getByLabel('Open Orca Web project').setInputFiles({name:'Complete PA batch.3mf',mimeType:'model/3mf',buffer:Buffer.from(fixture.prepared.nativeProject.bytes)});await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();await page.locator('.plate-tabs').getByRole('button',{name:'Plate 2',exact:true}).click();await expect(page.getByText('Objects: 2',{exact:true})).toBeVisible();await page.locator('[data-tree-kind=object][data-plate-id=plate-2] .tree-label').first().click();await page.getByLabel('position X',{exact:true}).fill('10');await expect(page.getByRole('alert').filter({hasText:'fixed absolute layer commands'})).toBeVisible();await page.getByRole('button',{name:'Project',exact:true}).click();const waiting=page.waitForEvent('download');await page.getByRole('button',{name:'Export plate as 3MF',exact:true}).click();const project=importNative3MF(await readFile(await(await waiting).path()));expect(project.plates).toHaveLength(1);expect(project.objects).toHaveLength(2);expect(project.plates[0].layerEvents.items).toHaveLength(4);});
