import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {importNative3MF,exportNative3MF} from '../../shared/native-project.js';
import {emptyProject,serializeProject} from '../../shared/project.js';
import {createTextMesh} from '../../shared/text-geometry.js';
import {paintedFacetGeometry} from '../../shared/facet-painting.js';
import {testFont} from '../fixtures/text-font.js';
async function saved(page){await page.getByRole('button',{name:'Project',exact:true}).click();const pending=page.waitForEvent('download');await page.locator('.project-actions').getByRole('button',{name:'Save project',exact:true}).click();const project=JSON.parse(await readFile(await(await pending).path(),'utf8'));await page.getByRole('button',{name:'Prepare',exact:true}).click();return project;}
async function source(){const project=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));project.objects[0].position=[50,50,0];project.objects[0].painting={version:1,supports:{6:'0482'}};return project;}
async function open(page,project){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles({name:'Painted native.3mf',mimeType:'model/3mf',buffer:Buffer.from(exportNative3MF(project))});await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();}
test('split and safe repair preserve painted regions, while cut requires explicit clearing consent',async({page})=>{
 const project=await source();await open(page,project);await page.getByRole('button',{name:'Repair mesh',exact:true}).click();let result=await saved(page);expect(paintedFacetGeometry(result.objects[0],'supports')).toEqual(paintedFacetGeometry(project.objects[0],'supports'));
 await page.getByRole('button',{name:'Split shells',exact:true}).click();result=await saved(page);expect(paintedFacetGeometry(result.objects[0],'supports')).toEqual(paintedFacetGeometry(project.objects[0],'supports'));
 await page.getByRole('button',{name:'Cut',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Cut object'});await expect(dialog.getByLabel('Clear painting from cut parts')).toBeVisible();await expect(dialog.getByRole('status')).toContainText('retained');await expect(dialog.getByRole('button',{name:'Apply cut'})).toBeDisabled();await dialog.getByLabel('Clear painting from cut parts').check();await expect(dialog.getByRole('button',{name:'Apply cut'})).toBeEnabled();await dialog.getByRole('button',{name:'Apply cut'}).click();result=await saved(page);expect(result.objects).toHaveLength(2);expect(result.objects.every(object=>object.painting===undefined)).toBe(true);
 await page.getByRole('button',{name:'Undo',exact:true}).click();result=await saved(page);expect(result.objects).toHaveLength(1);expect(result.objects[0].painting.supports[6]).toBe('0482');
});
test('repair refuses ambiguous painted duplicate deletion and leaves the project unchanged',async({page})=>{
 const project=await source(),mesh=project.objects[0];mesh.positions.push(...mesh.positions.slice(0,9));delete mesh.native.meshSource;mesh.painting.supports[12]='8';await open(page,project);const before=await saved(page);await page.getByRole('button',{name:'Repair mesh',exact:true}).click();await expect(page.getByRole('alert')).toContainText('painted degenerate or duplicate');const after=await saved(page);expect(after.objects[0].positions).toEqual(before.objects[0].positions);expect(after.objects[0].painting).toEqual(before.objects[0].painting);
});
test('regenerating painted editable text needs explicit clearing consent',async({page})=>{
 const font=testFont(),bytes=Buffer.from(font.toArrayBuffer());await page.route('**/api/fonts',route=>route.fulfill({json:{fonts:[{id:'test-ring',name:'Test Ring',bytes:bytes.length}],defaultId:'test-ring'}}));await page.route('**/api/fonts/test-ring',route=>route.fulfill({body:bytes,contentType:'font/otf'}));
 const mesh=createTextMesh(font,{text:'O',fontId:'test-ring',anchor:[50,50,0],mode:'standalone'},{plateId:'plate-1'});mesh.painting={version:1,supports:{0:'4'}};const project={...emptyProject(),objects:[mesh],selectedId:mesh.id};
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles({name:'Painted text.json',mimeType:'application/json',buffer:Buffer.from(serializeProject(project))});await page.getByRole('button',{name:'Edit text',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Edit text',exact:true});await expect(dialog.getByRole('status')).toContainText('closed text surfaces');await expect(dialog.getByRole('button',{name:'Update text'})).toBeDisabled();await dialog.getByLabel('Clear painting from regenerated text').check();await expect(dialog.getByRole('button',{name:'Update text'})).toBeEnabled();await dialog.getByRole('button',{name:'Update text'}).click();const result=await saved(page);expect(result.objects[0].painting).toBeUndefined();expect(result.objects[0].text.text).toBe('O');
});
