import{test as base,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{importNative3MF}from'../../shared/native-project.js';import{serializeProject}from'../../shared/project.js';
const test=base.extend({secondFilament:async({request},use)=>{const {defaults}=await(await request.get('/api/presets')).json();const response=await request.post('/api/presets/custom',{data:{type:'filament',name:`Shrinkage preview ${Date.now()}-${Math.random().toString(36).slice(2)}`,baseId:defaults.filamentId,compatiblePrinterIds:[defaults.printerId],settings:{filament_shrink:[97],filament_shrinkage_compensation_z:[98]}}});expect(response.status(),await response.text()).toBe(201);const record=await response.json();try{await use(record.id);}finally{await request.delete(`/api/presets/custom/${record.id}`);}}});
async function baseProject(){const project=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));project.useEmbeddedSettings=true;project.objects[0].position=[60,70,0];project.nativeSettings={...project.nativeSettings,layer_height:'.2',initial_layer_print_height:'.2',filament_settings_id:['One','Two','Three'],filament_diameter:['1.75','1.75','1.75'],filament_shrink:['98','97','96'],filament_shrinkage_compensation_z:['98','98','98'],enable_support:'0',enable_prime_tower:'0'};return project;}
async function openProject(page,project){await page.getByLabel('Open Orca Web project').setInputFiles({name:'Shrinkage.orca.json',mimeType:'application/json',buffer:Buffer.from(serializeProject(project))});await expect(page.getByRole('button',{name:'Variable layers',exact:true})).toBeEnabled();}
async function editor(page){await page.getByRole('button',{name:'Variable layers',exact:true}).click();return page.getByRole('dialog',{name:'Variable layer heights'});}
test('embedded full material vectors change actual layer texture while unused mismatches retain source compensation warning',async({page},info)=>{
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();const project=await baseProject();await openProject(page,project);let dialog=await editor(page);await expect(dialog.getByLabel('Layer material compensation')).toContainText('Used filament slots: 1 · Z compensation: 1.020408×');await expect(dialog.getByRole('img',{name:'Layer height brush bar'})).toHaveAttribute('data-layer-count','102');await expect(dialog.getByText(/known shrinkage discrepancy/)).toBeVisible();await dialog.screenshot({path:info.outputPath('source-shrinkage-discrepancy.png')});await dialog.getByRole('button',{name:'Cancel changes'}).click();
 project.objects[0].painting={version:1,color:{4:'8'}};await openProject(page,project);dialog=await editor(page);await expect(dialog.getByLabel('Layer material compensation')).toContainText('Used filament slots: 1, 2 · Z compensation: 1×');await expect(dialog.getByLabel('Layer material compensation')).toContainText('different XY or Z');await expect(dialog.getByRole('img',{name:'Layer height brush bar'})).toHaveAttribute('data-layer-count','100');await expect(dialog.getByText(/known shrinkage discrepancy/)).toHaveCount(0);
});
async function catalogProject(page,second){const catalog=await(await page.request.get('/api/presets')).json(),project=await baseProject(),first=catalog.defaults.filamentId;expect(second).toBeTruthy();project.useEmbeddedSettings=false;project.ids=catalog.defaults;project.filamentIds=[first,second,first];project.overrides={layer_height:.2,initial_layer_print_height:.2};project.objects[0].painting={version:1,color:{4:'8'}};await openProject(page,project);await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();return{project,first,second};}
test('catalog preview waits for every deduplicated material request and uses the second slot instead of first-slot presentation',async({page,secondFilament})=>{
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();const{first,second}=await catalogProject(page,secondFilament),seen=[];let release;const gate=new Promise(resolve=>release=resolve);
 await page.route('**/api/presets/selection?*',async route=>{const id=new URL(route.request().url()).searchParams.get('filamentId');seen.push(id);if(id===second)await gate;const response=await route.fetch(),body=await response.json();body.filamentSettings={...body.filamentSettings,filament_diameter:['1.75'],filament_shrink:[id===second?97:98],filament_shrinkage_compensation_z:[98]};await route.fulfill({response,json:body});});
 const dialog=await editor(page);await expect(dialog.getByText('Resolving filament shrinkage settings…')).toBeVisible();await expect(dialog.getByRole('button',{name:'Apply variable layers'})).toBeDisabled();await expect(dialog.getByRole('img',{name:'Layer height brush bar'})).toHaveCount(0);await expect.poll(()=>seen.includes(second)).toBe(true);release();await expect(dialog.getByLabel('Layer material compensation')).toContainText('Used filament slots: 1, 2 · Z compensation: 1×');await expect(dialog.getByRole('img',{name:'Layer height brush bar'})).toHaveAttribute('data-layer-count','100');expect(seen.filter(id=>id===first)).toHaveLength(1);expect(seen.filter(id=>id===second)).toHaveLength(1);
});
test('a missing material prevents an inaccurate preview and close cancels pending reads without changing the project',async({page,secondFilament})=>{
 await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();const{second}=await catalogProject(page,secondFilament);await page.route('**/api/presets/selection?*',async route=>{if(new URL(route.request().url()).searchParams.get('filamentId')===second)await route.fulfill({status:404,json:{error:'Second filament is unavailable'}});else await route.continue();});let dialog=await editor(page);await expect(dialog.getByRole('alert')).toContainText('Second filament is unavailable');await expect(dialog.getByRole('button',{name:'Apply variable layers'})).toBeDisabled();await expect(dialog.getByRole('img',{name:'Layer height brush bar'})).toHaveCount(0);await dialog.getByRole('button',{name:'Cancel changes'}).click();await page.unroute('**/api/presets/selection?*');
 let release;const gate=new Promise(resolve=>release=resolve);const failed=[];page.on('requestfailed',request=>{if(request.url().includes('/api/presets/selection?'))failed.push(request.failure()?.errorText);});await page.route('**/api/presets/selection?*',async route=>{await gate;await route.abort();});dialog=await editor(page);await expect(dialog.getByText('Resolving filament shrinkage settings…')).toBeVisible();await dialog.getByRole('button',{name:'Cancel changes'}).click();release();await expect.poll(()=>failed.length).toBeGreaterThan(0);await expect(page.getByRole('dialog',{name:'Variable layer heights'})).toHaveCount(0);
});
