import{test,expect}from'@playwright/test';import{build}from'esbuild';import path from'node:path';import{readFile}from'node:fs/promises';
let script,css;
test.beforeAll(async()=>{const result=await build({stdin:{contents:`import React from'react';import{createRoot}from'react-dom/client';import ProfileEditor from ${JSON.stringify(path.resolve('src/ProfileEditor.jsx'))};const p=new URLSearchParams(location.search),selection=JSON.parse(p.get('selection'));function Harness(){const[open,setOpen]=React.useState(true);return <ProfileEditor open={open} scope="process" selectedId={p.get('id')} printerId={selection.printerId} selection={selection} onClose={()=>setOpen(false)} onSaved={value=>{window.saved=value;setOpen(false)}}/>}createRoot(document.getElementById('root')).render(<Harness/>);`,loader:'jsx',resolveDir:process.cwd()},bundle:true,write:false,outdir:'unused-inheritance-browser',format:'iife',define:{'process.env.NODE_ENV':'"production"'}});script=result.outputFiles.find(file=>file.path.endsWith('.js')).text;css=result.outputFiles.find(file=>file.path.endsWith('.css')).text;});
async function importPreset(request,preset){const result=await request.post('/api/presets/custom/import',{data:{preset}});expect(result.status(),await result.text()).toBe(201);return result.json();}
async function show(page,record,selection){
 await page.route('**/inheritance-harness?*',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><link rel="stylesheet" href="/inheritance-harness.css"><div id="root"></div><script src="/inheritance-harness.js"></script>'}));await page.route('**/inheritance-harness.js',route=>route.fulfill({contentType:'text/javascript',body:script}));await page.route('**/inheritance-harness.css',route=>route.fulfill({contentType:'text/css',body:css}));await page.goto(`/inheritance-harness?id=${record.id}&selection=${encodeURIComponent(JSON.stringify(selection))}`);await expect(page.getByLabel('Preset name',{exact:true})).toBeEnabled();
}
test('parent-relative reset saves native differences and exported JSON retains its parent',async({page,request},info)=>{
 const selection=(await(await request.get('/api/presets')).json()).defaults,parent=await(await request.get(`/api/presets/custom/source/process/${selection.processId}`)).json(),child=await importPreset(request,{type:'process',name:`Fine inherited browser ${Date.now()}`,inherits:parent.name,layer_height:'0.12'});
 await show(page,child,selection);await expect(page.getByRole('status').filter({hasText:`Native parent: ${parent.name}`})).toBeVisible();await page.getByLabel('Search profile settings',{exact:true}).fill('layer_height');const input=page.getByLabel('Layer height (layer_height)',{exact:true});await expect(input).toHaveValue('0.12');await page.screenshot({path:info.outputPath('native-parent-reset.png'),fullPage:true});
 await page.getByRole('button',{name:'Reset Layer height (layer_height) to source',exact:true}).click();await expect(input).toHaveValue('0.2');await page.getByRole('button',{name:'Save changes',exact:true}).click();const review=page.getByRole('alertdialog',{name:'Review native setting corrections'});await expect(review).toBeVisible();await expect(review).toContainText('Layer height exceeds the printer limits');await review.getByRole('radio',{name:'Ignore printer limits',exact:true}).check();await review.getByRole('button',{name:'Apply choices and save',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();
 await show(page,child,selection);await expect(input).toHaveValue('0.2');const promise=page.waitForEvent('download');await page.getByRole('button',{name:'Export saved preset',exact:true}).click();const download=await promise,document=JSON.parse(await readFile(await download.path(),'utf8'));expect(document.inherits).toBe(parent.name);expect(document.layer_height).toBeUndefined();expect(document.name).toBe(child.name);expect(document.type).toBe('process');
});
test('a native root with children reports rename and delete conflicts without losing its saved document',async({page,request})=>{
 const selection=(await(await request.get('/api/presets')).json()).defaults,root=await importPreset(request,{type:'process',name:`Browser parent ${Date.now()}`,layer_height:'0.2'});await importPreset(request,{type:'process',name:`Browser child ${Date.now()}`,inherits:root.name,layer_height:'0.12'});
 await show(page,root,selection);await expect(page.getByRole('status').filter({hasText:'Native root preset.'})).toBeVisible();await page.getByLabel('Preset name',{exact:true}).fill(`${root.name} renamed`);await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'has children'})).toBeVisible();await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByRole('button',{name:'Delete preset',exact:true}).click();await page.getByRole('button',{name:'Confirm delete',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'inherited by another preset'})).toBeVisible();expect((await(await request.get(`/api/presets/custom/${root.id}/export`)).json()).name).toBe(root.name);
});
