import{test,expect}from'@playwright/test';import{build}from'esbuild';import path from'node:path';
let script,css;
test.beforeAll(async()=>{const result=await build({stdin:{contents:`import React from'react';import{createRoot}from'react-dom/client';import ProfileEditor from ${JSON.stringify(path.resolve('src/ProfileEditor.jsx'))};const params=new URLSearchParams(location.search);const selection=JSON.parse(params.get('selection'));function Harness(){const[open,setOpen]=React.useState(true);return <ProfileEditor open={open} scope="filament" selectedId={params.get('id')} printerId={selection.printerId} selection={selection} onClose={()=>setOpen(false)} onSaved={value=>{window.saved=value}}/>}createRoot(document.getElementById('root')).render(<Harness/>);`,loader:'jsx',resolveDir:process.cwd()},bundle:true,write:false,outdir:'unused-dependency-browser',format:'iife',define:{'process.env.NODE_ENV':'"production"'}});script=result.outputFiles.find(file=>file.path.endsWith('.js')).text;css=result.outputFiles.find(file=>file.path.endsWith('.css')).text;});
async function fixture(page,request,dependencies){const listing=await(await request.get('/api/presets')).json(),selection=listing.defaults;const source=await(await request.get(`/api/presets/custom/source/filament/${selection.filamentId}`)).json();const imported=await request.post('/api/presets/custom/import',{data:{preset:{type:'filament',name:`Dependency browser ${Date.now()}`,inherits:source.name,...dependencies}}});expect(imported.status(),await imported.text()).toBe(201);const record=await imported.json();selection.filamentId=record.id;
 await page.route('**/dependency-harness?*',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><link rel="stylesheet" href="/dependency-harness.css"><div id="root"></div><script src="/dependency-harness.js"></script>'}));await page.route('**/dependency-harness.js',route=>route.fulfill({contentType:'text/javascript',body:script}));await page.route('**/dependency-harness.css',route=>route.fulfill({contentType:'text/css',body:css}));await page.goto(`/dependency-harness?id=${record.id}&selection=${encodeURIComponent(JSON.stringify(selection))}`);await expect(page.getByLabel('Preset name',{exact:true})).toBeEnabled();return{record,selection};}
test('native dependency editor retains unavailable names on Cancel, All retains dormant condition, and saved JSON preserves both',async({page,request},info)=>{
 const {record}=await fixture(page,request,{compatible_printers:['Other computer printer'],compatible_printers_condition:'false',compatible_prints:['Other computer process'],compatible_prints_condition:'layer_height < 0.2'});
 await expect(page.getByText('This preset is incompatible',{exact:false})).toBeVisible();await expect(page.getByLabel('Compatible printers condition',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'Set compatible printers',exact:true}).click();await expect(page.getByText('Unavailable stored names',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Cancel dependency choices',exact:true}).click();await expect(page.getByText('Other computer printer',{exact:true})).toBeVisible();
 await page.getByLabel('All compatible printers',{exact:true}).check();await expect(page.getByLabel('Compatible printers condition',{exact:true})).toBeEnabled();await expect(page.getByLabel('Compatible printers condition',{exact:true})).toHaveValue('false');
 await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();const exported=await(await request.get(`/api/presets/custom/${record.id}/export`)).json();expect(exported.compatible_printers).toEqual([]);expect(exported.compatible_printers_condition).toBe('false');expect(exported.compatible_prints).toEqual(['Other computer process']);expect(exported.compatible_prints_condition).toBe('layer_height < 0.2');
});
test('false imported dependency can be repaired in the editor and native configuration rejects it until saved',async({page,request},info)=>{
 const {record,selection}=await fixture(page,request,{compatible_printers:[],compatible_printers_condition:'false',compatible_prints:[],compatible_prints_condition:''});let response=await request.post('/api/presets/configuration',{data:{selection}});expect(response.status()).toBe(400);expect((await response.json()).error).toContain('incompatible');
 await page.getByLabel('Compatible printers condition',{exact:true}).fill('nozzle_diameter[0] == 0.4');await page.getByRole('button',{name:'Set compatible process profiles',exact:true}).click();const group=page.getByRole('group',{name:'Choose compatible process profiles',exact:true});const options=group.getByRole('checkbox');for(const item of await options.all())await item.check();await page.getByRole('button',{name:'Apply dependency choices',exact:true}).click();await expect(page.getByLabel('All compatible process profiles',{exact:true})).toBeChecked();await page.screenshot({path:info.outputPath('native-dependencies.png'),fullPage:true});
 await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();response=await request.post('/api/presets/configuration',{data:{selection}});expect(response.status(),await response.text()).toBe(200);expect((await(await request.get(`/api/presets/custom/${record.id}/export`)).json()).compatible_printers_condition).toBe('nozzle_diameter[0] == 0.4');
});
