import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{nativeOptionsVertexShader,nativeOptionPositions,nativeOptionNormals}from'../../src/preview-options-data.js';
test('production marker shader matches original native GLSL positions and lighting on both platform scales',async({page})=>{
 const fixture=JSON.parse(await readFile(new URL('../fixtures/native-preview-options-reference.json',import.meta.url)));await page.goto('/');const result=await page.evaluate(({production,reference,positions,normals})=>{
  const gl=document.createElement('canvas').getContext('webgl2');if(!gl)throw Error('WebGL2 required');
  const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
  reference=reference.replace('#version 150\n','precision highp float;\nprecision highp int;\n').replace(/uniform (?:u?samplerBuffer) \w+;\n/g,'').replace('in vec3 in_normal;','in vec3 in_normal;\nin vec3 native_position;\nin vec4 native_hwa;\nin vec3 native_color;').replace('  int id = int(texelFetch(segment_index_tex, gl_InstanceID).r);\n','').replace('texelFetch(height_width_angle_tex, id)','native_hwa').replace('texelFetch(position_tex, id).xyz','native_position').replace('decode_color(texelFetch(color_tex, id).r)','native_color');
  const view=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],nativeView=[1,0,0,0,0,0,-1,0,0,1,0,0,0,0,0,1];
  const cases=[{position:[100,200,.2],hwa:[.2,.45,0,.1]},{position:[-30,12,20],hwa:[.6,1.2,0,.1]},{position:[0,0,0],hwa:[0,0,0,0]}],results=[];
  for(const[shader,isNative]of[[production,false],[reference,true]]){
   const src='#version 300 es\n'+shader.replace('out vec3 color;','out vec3 color;\nout vec3 probe_position;').replace('  gl_Position =','  probe_position = eye_position;\n  gl_Position ='),program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,src));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,'#version 300 es\nprecision highp float;in vec3 color;out vec4 c;void main(){c=vec4(color,1);}'));gl.transformFeedbackVaryings(program,['probe_position','color'],gl.INTERLEAVED_ATTRIBS);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);gl.bindVertexArray(gl.createVertexArray());
   for(const[name,values]of[['in_position',positions],['in_normal',normals]]){gl.bindBuffer(gl.ARRAY_BUFFER,gl.createBuffer());gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(values),gl.STATIC_DRAW);const id=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(id);gl.vertexAttribPointer(id,3,gl.FLOAT,false,0,0);}
   gl.uniformMatrix4fv(gl.getUniformLocation(program,isNative?'view_matrix':'viewMatrix'),false,new Float32Array(isNative?nativeView:view));gl.uniformMatrix4fv(gl.getUniformLocation(program,isNative?'projection_matrix':'projectionMatrix'),false,new Float32Array(view));const output=gl.createBuffer();gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,output);gl.bufferData(gl.TRANSFORM_FEEDBACK_BUFFER,96*6*4,gl.STREAM_READ);gl.enable(gl.RASTERIZER_DISCARD);const probes=[];
   for(const scale of[.75,1.5])for(const row of cases){gl.vertexAttrib3fv(gl.getAttribLocation(program,'native_position'),row.position);gl.vertexAttrib4fv(gl.getAttribLocation(program,'native_hwa'),row.hwa);gl.vertexAttrib3fv(gl.getAttribLocation(program,'native_color'),[.9019608,.9019608,.9019608]);gl.uniform1f(gl.getUniformLocation(program,'scaling_factor'),scale);gl.beginTransformFeedback(gl.POINTS);gl.drawArrays(gl.POINTS,0,96);gl.endTransformFeedback();const value=new Float32Array(96*6);gl.getBufferSubData(gl.TRANSFORM_FEEDBACK_BUFFER,0,value);probes.push([...value]);}results.push(probes);gl.disable(gl.RASTERIZER_DISCARD);gl.deleteProgram(program);
  }
  const error=gl.getError();gl.getExtension('WEBGL_lose_context')?.loseContext();if(error!==gl.NO_ERROR)throw Error('WebGL error '+error);return results;
 },{production:nativeOptionsVertexShader,reference:fixture.originalVertexShader,positions:nativeOptionPositions,normals:nativeOptionNormals});
 expect(result[0]).toHaveLength(6);for(let c=0;c<6;c++)for(let i=0;i<96*6;i++)expect(Math.abs(result[0][c][i]-result[1][c][i]),`case${c} coordinate/color${i}`).toBeLessThan(1e-6);
});
