import {test,expect} from '@playwright/test';import {readFile} from 'node:fs/promises';
import {towerProject,towerSettings} from '../fixtures/native-prime-tower-input.js';
const ref=JSON.parse(await readFile(new URL('../fixtures/native-prime-tower-reference.json',import.meta.url)));
const canvas=page=>page.getByRole('img',{name:'Interactive 3D model view',exact:true});
const rendered=page=>canvas(page).evaluate(el=>JSON.parse(el.dataset.primeTower));
async function start(page){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();const p={...towerProject(),useEmbeddedSettings:true,nativeWorkflow:true,nativeSettings:{...towerSettings,printer_settings_id:'Tower fixture',print_settings_id:'Tower process',filament_settings_id:['PLA','PLA','PLA']}};await page.getByLabel('Open Orca Web project').setInputFiles({name:'Tower.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();return p;}
function response(body){const p=body.projectRequest.project,s=p.nativeSettings,c=ref.cases[0],index=p.plates.findIndex(x=>x.id===p.activePlateId);const visible=p.objects.some(o=>o.plateId===p.activePlateId);return{result:{format:'orca-native-prime-tower',version:1,sourceRevision:ref.sourceCommit,plateId:p.activePlateId,...structuredClone(c.expected),visible,size:visible?[Number(s.prime_tower_width),c.expected.size[1],20]:null,position:[Number(s.wipe_tower_x[index]??s.wipe_tower_x[0]),Number(s.wipe_tower_y[index]??s.wipe_tower_y[0])],rotation:Number(s.wipe_tower_rotation_angle)*Math.PI/180},warnings:[]};}
test('pre-slice tower renders native color bands, updates placement, supports Undo, and disappears on an empty plate',async({page},info)=>{
 let calls=0;await page.route('**/api/geometry/prime-tower',route=>{calls++;return route.fulfill({json:response(route.request().postDataJSON())});});await start(page);await expect.poll(()=>rendered(page)).toMatchObject({status:'ready',visible:true,bands:2,triangles:24,position:[100,140],size:ref.cases[0].expected.size});
 const initialCalls=calls;await page.getByRole('button',{name:'Prime tower',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Prime tower placement'});await dialog.getByLabel('Prime tower X',{exact:true}).fill('80');await dialog.getByLabel('Prime tower rotation',{exact:true}).fill('30');await dialog.getByRole('button',{name:'Apply prime tower'}).click();await expect.poll(()=>rendered(page)).toMatchObject({position:[80,140],rotation:Math.PI/6});expect(calls).toBeGreaterThan(initialCalls);await page.locator('.scene-views').getByRole('button',{name:'Fit',exact:true}).click();const target=JSON.parse(await canvas(page).getAttribute('data-camera-target'));expect(target[1]).toBeGreaterThan(80);await page.screenshot({path:info.outputPath('prime-tower-bands.png')});
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(()=>rendered(page)).toMatchObject({position:[100,140],rotation:0});await page.getByRole('button',{name:'＋ Add plate',exact:true}).click();await expect.poll(()=>rendered(page)).toMatchObject({status:'ready',visible:false,bands:0,triangles:0});await page.locator('.plate-tabs').getByRole('button',{name:'Plate 1',exact:true}).click();await expect.poll(()=>rendered(page)).toMatchObject({status:'ready',visible:true,bands:2});
});
test('disabled tower discards delayed geometry and error responses remove stale bands',async({page})=>{
 let release,requests=0,fail=false;await page.route('**/api/geometry/prime-tower',async route=>{requests++;if(requests===1)await new Promise(r=>release=r);await route.fulfill(fail?{status:503,json:{error:'Native tower helper unavailable'}}:{json:response(route.request().postDataJSON())}).catch(()=>{});});await start(page);await expect.poll(()=>requests).toBe(1);
 await page.getByRole('button',{name:'Prime tower',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Prime tower placement'});await dialog.getByLabel('Enable prime tower',{exact:true}).uncheck();await dialog.getByRole('button',{name:'Apply prime tower'}).click();release();await expect.poll(()=>rendered(page)).toMatchObject({status:'idle',visible:false,bands:0});
 fail=true;await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByText('Prime tower preview unavailable: Native tower helper unavailable',{exact:true})).toBeVisible();await expect.poll(()=>rendered(page)).toMatchObject({status:'error',visible:false,bands:0});
});
