import {test,expect} from '@playwright/test';import {readFile} from 'node:fs/promises';import path from 'node:path';import {png} from '../image-fixture.js';import {IMAGE_WORKER_ID,NATIVE_COVER_SIZES} from '../../shared/native-cover.js';import {extractBoundedZip} from '../../shared/import-limits.js';
const source=png(3,1),result={provenance:IMAGE_WORKER_ID,sourceWidth:3,sourceHeight:1,images:Object.fromEntries(Object.entries(NATIVE_COVER_SIZES).map(([kind,[name,width,height]])=>[kind,{name,width,height,data:png(width,height).toString('base64')}]))};
async function start(page,capability={available:true,...IMAGE_WORKER_ID}){await page.route('**/api/project-images/capabilities',route=>route.fulfill({json:capability}));await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles(path.resolve('tests/fixtures/native-gui-cube-2.4.2.3mf'));await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Project',exact:true}).click();await page.getByLabel('Add Model Pictures files',{exact:true}).setInputFiles({name:'photo.png',mimeType:'image/png',buffer:source});await expect(page.getByRole('button',{name:'Download photo.png'})).toBeVisible();}
async function save(page){const pending=page.waitForEvent('download');await page.getByRole('contentinfo').getByRole('button',{name:'Save project',exact:true}).click();return JSON.parse((await readFile(await(await pending).path())).toString());}
test('setting a project cover publishes the complete native set, exports exact images and supports undo',async({page})=>{await page.route('**/api/project-images/cover',route=>route.fulfill({json:result}));await start(page);const before=await save(page);await page.getByRole('button',{name:'Set photo.png as cover'}).click();await expect(page.getByText(/bytes · Project cover/)).toBeVisible();const project=await save(page);expect(project.nativeModelMetadata.DesignerCover).toBe('photo.png');expect(Object.keys(project.nativeAuxiliary.covers)).toHaveLength(3);for(const value of Object.values(result.images))expect(project.nativeAuxiliary.files.find(file=>file.path===`Auxiliaries/.thumbnails/${value.name}`).data).toBe(value.data);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const files=extractBoundedZip(await readFile(await(await pending).path()));for(const value of Object.values(result.images))expect(Buffer.from(files[`Auxiliaries/.thumbnails/${value.name}`])).toEqual(Buffer.from(value.data,'base64'));await page.getByRole('button',{name:'Undo',exact:true}).click();const undone=await save(page);expect(undone.nativeModelMetadata).toEqual(before.nativeModelMetadata);expect(undone.nativeAuxiliary).toEqual(before.nativeAuxiliary);
});
test('cover generation reports missing native capability and rejects incomplete results without editing attachments',async({page})=>{await start(page,{available:false,reason:'Build the native image worker to generate project covers.'});await expect(page.getByRole('button',{name:'Set photo.png as cover'})).toBeDisabled();await expect(page.getByText('Build the native image worker to generate project covers.')).toBeVisible();await page.unroute('**/api/project-images/capabilities');await page.route('**/api/project-images/capabilities',route=>route.fulfill({json:{available:true,...IMAGE_WORKER_ID}}));await page.getByRole('button',{name:'Prepare',exact:true}).click();await page.getByRole('button',{name:'Project',exact:true}).click();await page.route('**/api/project-images/cover',route=>route.fulfill({json:{...result,images:{cover:result.images.cover}}}));await page.getByRole('button',{name:'Set photo.png as cover'}).click();await expect(page.getByRole('alert')).toContainText('Incomplete');expect((await save(page)).nativeAuxiliary.files).toHaveLength(1);});
test('pending covers cannot overwrite project edits and can be cancelled',async({page})=>{let release;await page.route('**/api/project-images/cover',route=>{release=()=>route.fulfill({json:result}).catch(()=>{});});await start(page);await page.getByRole('button',{name:'Set photo.png as cover'}).click();await expect(page.getByRole('button',{name:'Cancel cover generation'})).toBeVisible();await expect.poll(()=>Boolean(release)).toBe(true);await page.getByLabel('Project name',{exact:true}).fill('Edited while rendering');await release();await expect(page.getByRole('alert')).toContainText('project changed');expect((await save(page)).nativeAuxiliary.files).toHaveLength(1);release=null;await page.getByRole('button',{name:'Set photo.png as cover'}).click();await expect.poll(()=>Boolean(release)).toBe(true);await page.getByRole('button',{name:'Cancel cover generation'}).click();await release();await expect(page.getByRole('button',{name:'Set photo.png as cover'})).toBeEnabled();expect((await save(page)).nativeAuxiliary.files).toHaveLength(1);});
