import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {fixture} from '../fixtures/native-instance-project.js';
import {importNative3MF,exportNative3MF} from '../../shared/native-project.js';
import {serializeProject,parseProject,emptyProject} from '../../shared/project.js';
import {assertInstanceFamilies} from '../../shared/native-instances.js';
const cube=new URL('../fixtures/cube.stl',import.meta.url).pathname;
async function start(page){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByRole('button',{name:'Preferences',exact:true}).click();const d=page.getByRole('dialog',{name:'Preferences'});await d.getByLabel('Load behaviour').selectOption('load_geometry_only');await d.getByRole('button',{name:'Close',exact:true}).click();}
function source(){const p=fixture({mirror:true});for(const o of p.objects){o.native.objectSettings={extruder:'1',wall_loops:'9'};o.native.partSettings={extruder:'1',sparse_infill_density:'70%'};o.native.layerConfigRanges=[{minZ:1,maxZ:3,settings:{layer_height:'0.12'}}];o.native.layerHeightProfile=[0,.2,1,.2,10,.2];}return p;}
const file=()=>({name:'Linked painted assembly.3mf',mimeType:'model/3mf',buffer:Buffer.from(exportNative3MF(source()))});
async function save(page){const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Save project',exact:true}).click();return parseProject(await readFile(await(await pending).path(),'utf8'));}
async function loadJson(page,p){await page.getByLabel('Open Orca Web project').setInputFiles({name:'Current.orca-web.json',mimeType:'application/json',buffer:Buffer.from(serializeProject(p))});}
test('geometry Add retains linked parts, painting and layer profiles and strips imported overrides in the saved project',async({page},info)=>{await start(page);await page.getByLabel('Layer height',{exact:true}).fill('0.25');await page.getByLabel('Choose a 3D model').setInputFiles(cube);await page.getByLabel('Choose a 3D model').setInputFiles(file());await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(2);const p=await save(page),parts=p.objects.slice(1);expect(parts).toHaveLength(4);expect(new Set(parts.map(o=>o.native.groupId)).size).toBe(2);expect(new Set(parts.map(o=>o.native.instanceFamily)).size).toBe(1);assertInstanceFamilies(parts);for(const o of parts){expect(o.painting.color).toEqual({0:'4'});expect(o.native.objectSettings).toEqual({extruder:'1'});expect(o.native.partSettings).toEqual({extruder:'1'});expect(o.native.layerHeightProfile).toEqual([0,.2,1,.2,10,.2]);expect(o.native.layerConfigRanges[0].settings.layer_height).toBe('0.12');}expect(p.overrides.layer_height).toBe('0.25');await page.screenshot({path:info.outputPath('native-geometry-parts.png')});await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(1);await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(2);});
test('geometry-only Open retains current material colors and purge settings while replacing objects',async({page})=>{await start(page);await page.getByLabel('Choose a 3D model').setInputFiles(cube);const p=await save(page);p.projectOverrides={filament_colour:['#123456'],flush_volumes_matrix:['0'],flush_volumes_vector:['141','142']};p.overrides={layer_height:'0.25'};await loadJson(page,p);await expect(page.getByLabel('Layer height',{exact:true})).toHaveValue('0.25');await expect(page.getByRole('dialog',{name:'Importing project'})).toHaveCount(0);expect((await save(page)).projectOverrides).toEqual(p.projectOverrides);await page.getByLabel('Open Orca Web project').setInputFiles(file());await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(1);const out=await save(page);expect(out.objects).toHaveLength(4);expect(out.projectOverrides).toEqual(p.projectOverrides);expect(out.overrides.layer_height).toBe('0.25');expect(out.ids).toEqual(p.ids);expect(out.nativeSettings).toBeUndefined();});
test('repeated geometry Add keeps separate model families and preserves exported paint',async({page})=>{await start(page);await page.getByLabel('Choose a 3D model').setInputFiles(file());await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(1);await page.getByLabel('Choose a 3D model').setInputFiles(file());await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(2);const out=await save(page);expect(out.objects).toHaveLength(8);expect(new Set(out.objects.map(o=>o.native.instanceFamily)).size).toBe(2);assertInstanceFamilies(out.objects);await page.getByRole('button',{name:'Project',exact:true}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const round=importNative3MF(await readFile(await(await pending).path()));expect(round.objects).toHaveLength(8);expect(new Set(round.objects.map(o=>o.native.instanceFamily)).size).toBe(2);for(const o of round.objects)expect(o.painting.color).toEqual({0:'4'});});
test('failed geometry import and cancelled delayed API response retain the project and Undo history',async({page})=>{await start(page);await page.getByLabel('Choose a 3D model').setInputFiles(cube);await page.getByLabel('position X',{exact:true}).fill('41');const before=await save(page);let release,arrived;const begun=new Promise(r=>arrived=r);await page.route('**/api/projects/import',async route=>{arrived();await new Promise(r=>release=r);await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({project:source()})}).catch(()=>{});});await page.getByLabel('Choose a 3D model').setInputFiles(file());await begun;await page.getByRole('dialog',{name:'Importing project'}).getByRole('button',{name:'Cancel import'}).click();release();await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(1);expect((await save(page)).objects).toEqual(before.objects);await page.unroute('**/api/projects/import');await page.route('**/api/projects/import',route=>route.fulfill({status:422,contentType:'application/json',body:JSON.stringify({error:'Reference geometry could not be parsed'})}));await page.getByLabel('Choose a 3D model').setInputFiles(file());await expect(page.getByRole('alert')).toContainText('Reference geometry could not be parsed');expect((await save(page)).objects).toEqual(before.objects);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('position X',{exact:true})).not.toHaveValue('41');});
