import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';
const code='G90\nM83\nG1 X0 Y0 Z.2\n;LAYER_CHANGE\n;TYPE:Outer wall\nG1 X10 E1\n;TYPE:Support\nG1 Y10 E2\n;TYPE:Support interface\nG1 X12 E.5\n';
async function editor(page){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Choose a 3D model').setInputFiles(new URL('../fixtures/cube.stl',import.meta.url).pathname);await expect(page.getByText('Triangles: 12',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Paint supports',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Paint facets'});await dialog.getByRole('button',{name:'Top',exact:true}).click();await dialog.getByLabel('Painting tool',{exact:true}).selectOption('triangle');const canvas=dialog.getByRole('img',{name:'Interactive 3D model view'}),box=await canvas.boundingBox();await canvas.click({position:{x:box.width/2+10,y:box.height/2+10}});await expect(canvas).toHaveAttribute('data-painted-facets','{"1":1}');return dialog;}
async function saved(page){await page.getByRole('button',{name:'Project',exact:true}).click();const pending=page.waitForEvent('download');await page.locator('.project-actions').getByRole('button',{name:'Save project',exact:true}).click();return JSON.parse(await readFile(await(await pending).path(),'utf8'));}
test('sliced support preview renders only returned support paths and retains the paint draft',async({page})=>{
 let submitted;await page.route('**/api/jobs/project',async route=>{submitted=route.request().postDataJSON();await route.fulfill({json:{id:'preview-owned',status:'queued'}});});await page.route('**/api/jobs/preview-owned',route=>route.fulfill({json:{id:'preview-owned',status:'ready'}}));await page.route('**/api/jobs/preview-owned/download',route=>route.fulfill({body:code,contentType:'text/plain'}));const dialog=await editor(page);await dialog.getByRole('button',{name:'Sliced support preview',exact:true}).click();const preview=dialog.getByRole('region',{name:'Sliced support preview'});await expect(preview.getByText('2 support deposition segments',{exact:false})).toBeVisible();await expect(preview.getByRole('img',{name:'Interactive 3D model view'})).toHaveAttribute('data-support-segments','2');expect(submitted.project.objects[0].painting.supports).toBeTruthy();expect(submitted.overrides?.enable_support).not.toBe(true);await preview.getByRole('button',{name:'Back to painting'}).click();await expect(dialog.getByRole('img',{name:'Interactive 3D model view'})).toHaveAttribute('data-painted-facets','{"1":1}');await dialog.getByRole('button',{name:'Apply painting'}).click();expect((await saved(page)).objects[0].painting.supports).toBeTruthy();
});
test('closing while creation is pending cancels only the returned preview job and validation failure keeps painting editable',async({page})=>{
 let finish,cancelled=[];await page.route('**/api/jobs/project',route=>new Promise(resolve=>{finish=async()=>{await route.fulfill({json:{id:'pending-owned',status:'queued'}});resolve();};}));await page.route('**/api/jobs/*/cancel',async route=>{cancelled.push(route.request().url().split('/').at(-2));await route.fulfill({json:{id:'pending-owned',status:'cancelled'}});});const dialog=await editor(page);await dialog.getByRole('button',{name:'Sliced support preview',exact:true}).click();await expect.poll(()=>Boolean(finish)).toBe(true);await dialog.getByRole('button',{name:'Back to painting'}).click();await finish();await expect.poll(()=>cancelled).toEqual(['pending-owned']);await page.unroute('**/api/jobs/project');await page.route('**/api/jobs/project',route=>route.fulfill({status:400,json:{error:'Native preview validation fixture failed'}}));await dialog.getByRole('button',{name:'Sliced support preview',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Native preview validation fixture failed');await dialog.getByRole('button',{name:'Back to painting'}).click();await expect(dialog.getByRole('img',{name:'Interactive 3D model view'})).toHaveAttribute('data-painted-facets','{"1":1}');
});
