import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{importNative3MF,exportNative3MF}from'../../shared/native-project.js';import{layerProfileContext}from'../../shared/variable-layers.js';import{adjustLayerHeightProfile}from'../../shared/variable-layer-brush.js';import{layerHeightProfileFromRanges}from'../../shared/layer-height-profile.js';
async function saved(page){await page.getByRole('button',{name:'Project',exact:true}).click();const pending=page.waitForEvent('download');await page.locator('.project-actions').getByRole('button',{name:'Save project',exact:true}).click();const result=JSON.parse(await readFile(await(await pending).path(),'utf8'));await page.getByRole('button',{name:'Prepare',exact:true}).click();return result;}
async function source(){const p=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));p.objects[0].position=[50,50,0];p.nativeSettings.layer_height='.2';p.nativeSettings.initial_layer_print_height='.2';return p;}
async function open(page,project){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles({name:'Layers.3mf',mimeType:'model/3mf',buffer:Buffer.from(exportNative3MF(project))});await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Variable layers',exact:true}).click();return page.getByRole('dialog',{name:'Variable layer heights'});}
async function clickBar(page,dialog,{z=10,height=20,button='left',shift=false}={}){const bar=dialog.getByRole('img',{name:'Layer height brush bar'}),box=await bar.boundingBox(),x=box.x+box.width*.6,y=box.y+box.height*(1-z/height)-1;if(shift)await page.keyboard.down('Shift');await page.mouse.click(x,y,{button});if(shift)await page.keyboard.up('Shift');return(height*(box.y+box.height-y-1)/box.height);}
const closeProfile=(a,b)=>{expect(a.length).toBe(b.length);a.forEach((value,index)=>expect(value).toBeCloseTo(b[index],7));};
test('3D native texture responds to a held brush stroke, local undo restores the profile, and cancel preserves project data',async({page})=>{
 const p=await source(),errors=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});const dialog=await open(page,p);await dialog.getByRole('button',{name:'Create uniform profile'}).click();const model=dialog.getByRole('img',{name:'Interactive 3D model view'});await expect(model).toHaveAttribute('data-layer-shader-objects','1');await expect(model).toHaveAttribute('data-layer-count','100');const bar=dialog.getByRole('img',{name:'Layer height brush bar'}),box=await bar.boundingBox();await page.mouse.move(box.x+35,box.y+box.height/2);await page.mouse.down();await expect(dialog.getByLabel('Variable layer control point')).toHaveAttribute('max',/^[1-9]\d+$/);await page.waitForTimeout(220);await page.mouse.up();await expect(dialog.getByRole('button',{name:'Undo layer brush stroke'})).toBeEnabled();await expect(model).toHaveAttribute('data-layer-cursor-z',/.+/);await dialog.getByRole('button',{name:'Undo layer brush stroke'}).click();await expect(dialog.getByLabel('Variable layer control point')).toHaveAttribute('max','4');await dialog.getByRole('button',{name:'Cancel changes'}).click();expect((await saved(page)).objects[0].native.layerHeightProfile||[]).toEqual([]);expect(errors).toEqual([]);
});
for(const action of ['increase','decrease','reduce','smooth'])test(`native bar ${action} gesture applies the source brush and survives export`,async({page},testInfo)=>{
 const p=await source();p.objects[0].native.layerHeightProfile=[0,.2,.2,.2,.2,.2,8,.14,10,.13,12,.23,20,.2];const context=layerProfileContext(p.objects,p.objects[0].id,p.nativeSettings,{filamentCount:1}),dialog=await open(page,p),z=await clickBar(page,dialog,{button:['increase','smooth'].includes(action)?'right':'left',shift:['reduce','smooth'].includes(action)}),expected=adjustLayerHeightProfile(p.objects[0].native.layerHeightProfile,context,{z,action});await expect(dialog.getByRole('button',{name:'Undo layer brush stroke'})).toBeEnabled();if(action==='decrease')await dialog.screenshot({path:testInfo.outputPath('variable-layer-3d-brush.png')});await dialog.getByRole('button',{name:'Apply variable layers'}).click();const result=await saved(page);closeProfile(result.objects[0].native.layerHeightProfile,expected);await page.getByRole('button',{name:'Undo',exact:true}).click();closeProfile((await saved(page)).objects[0].native.layerHeightProfile,p.objects[0].native.layerHeightProfile);
});
test('wheel adjusts native brush bounds without zooming and default initialization preserves locked height ranges',async({page})=>{
 const p=await source();p.objects[0].native.layerConfigRanges=[{minZ:4,maxZ:8,settings:{layer_height:'.1',extruder:'0'}}];const context=layerProfileContext(p.objects,p.objects[0].id,p.nativeSettings,{filamentCount:1}),dialog=await open(page,p),bar=dialog.getByRole('img',{name:'Layer height brush bar'}),box=await bar.boundingBox();await page.mouse.move(box.x+35,box.y+box.height/2);await page.mouse.wheel(0,-10000);await expect(dialog.getByLabel('Layer brush width')).toHaveValue('10');await page.mouse.wheel(0,10000);await expect(dialog.getByLabel('Layer brush width')).toHaveValue('1.5');await dialog.getByLabel('Layer brush width').fill('2');await clickBar(page,dialog,{z:6});await dialog.getByRole('button',{name:'Apply variable layers'}).click();const result=await saved(page);closeProfile(result.objects[0].native.layerHeightProfile,layerHeightProfileFromRanges(context));expect(result.objects[0].native.layerConfigRanges[0].settings.layer_height).toBe('0.1');
});
