import{test,expect}from'@playwright/test';import{readFile}from'node:fs/promises';import{importNative3MF,exportNative3MF}from'../../shared/native-project.js';
async function load(page){const project=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));project.nativeSettings.layer_height='.2';await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByLabel('Open Orca Web project').setInputFiles({name:'Variable.3mf',mimeType:'model/3mf',buffer:Buffer.from(exportNative3MF(project))});await expect(page.getByText('Embedded native presets',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Variable layers',exact:true}).click();return page.getByRole('dialog',{name:'Variable layer heights'});}
async function save(page){await page.getByRole('button',{name:'Project',exact:true}).click();const promise=page.waitForEvent('download');await page.locator('.project-actions').getByRole('button',{name:'Save project',exact:true}).click();return JSON.parse(await readFile(await(await promise).path(),'utf8'));}
test('adaptive profile generation, smoothing and native export preserve a real variable curve',async({page})=>{
 const dialog=await load(page);await dialog.getByRole('button',{name:'Generate adaptive layers'}).click();await expect(dialog.getByText(/70 control points/)).toBeVisible();await expect(dialog.getByLabel('Variable layer point Z')).toBeDisabled();await dialog.getByLabel('Variable layer control point').fill('10');await dialog.getByLabel('Variable layer point height').fill('0.12');await dialog.getByLabel('Variable layer smoothing radius').fill('3');await dialog.getByLabel('Keep minimum heights').check();await dialog.getByRole('button',{name:'Smooth layer heights'}).click();await dialog.getByRole('button',{name:'Apply variable layers'}).click();const project=await save(page),profile=project.objects[0].native.layerHeightProfile;expect(profile.length).toBe(140);expect(profile[0]).toBe(0);expect(profile[1]).toBe(.2);expect(profile.at(-2)).toBe(20);expect(profile[19]).toBeLessThanOrEqual(.12);expect(project.nativeWorkflow).toBe(true);
 const promise=page.waitForEvent('download');await page.getByRole('button',{name:'Export native project',exact:true}).click();const actual=importNative3MF(await readFile(await(await promise).path())).objects[0].native.layerHeightProfile;expect(actual).toEqual(profile.map(value=>Number(value.toFixed(6))));
});
test('point editing enforces native bounds and ordering; cancel leaves no draft metadata',async({page})=>{
 const dialog=await load(page);await dialog.getByRole('button',{name:'Create uniform profile'}).click();await dialog.getByLabel('Variable layer control point').fill('3');await dialog.getByLabel('Variable layer point height').fill('0.6');await dialog.getByRole('button',{name:'Apply variable layers'}).click();await expect(dialog.getByRole('alert')).toContainText('between');await dialog.getByLabel('Variable layer point height').fill('0.16');await dialog.getByRole('button',{name:'Add point after selection'}).click();await dialog.getByLabel('Variable layer point Z').fill('25');await dialog.getByRole('button',{name:'Apply variable layers'}).click();await expect(dialog.getByRole('alert')).toContainText('ascending');await dialog.getByRole('button',{name:'Cancel changes'}).click();const project=await save(page);expect(project.objects[0].native.layerHeightProfile).toBeUndefined();
});
test('removing a variable profile participates in ordinary undo and redo',async({page})=>{
 const dialog=await load(page);await dialog.getByRole('button',{name:'Generate adaptive layers'}).click();await dialog.getByRole('button',{name:'Apply variable layers'}).click();await page.getByRole('button',{name:'Variable layers',exact:true}).click();await dialog.getByRole('button',{name:'Remove variable profile'}).click();await dialog.getByRole('button',{name:'Apply variable layers'}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Variable layers',exact:true}).click();await expect(dialog.getByText(/70 control points/)).toBeVisible();await dialog.getByRole('button',{name:'Cancel changes'}).click();await page.getByRole('button',{name:'Redo',exact:true}).click();const project=await save(page);expect(project.objects[0].native.layerHeightProfile).toEqual([]);
});
