import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {emptyVolumeFixture} from '../fixtures/import-inspection-project.js';
import {exportNative3MF} from '../../shared/native-project.js';
import {parseProject} from '../../shared/project.js';
import {IMPORT_INSPECTION_REVISION,prepareNativeImportInspection} from '../../shared/native-import-inspection.js';
const cube=new URL('../fixtures/cube.stl',import.meta.url).pathname;
const file=allEmpty=>({name:'Empty volumes.3mf',mimeType:'model/3mf',buffer:Buffer.from(exportNative3MF(emptyVolumeFixture({allEmpty})))});
const dialog=p=>p.getByRole('dialog',{name:'The volume of the object is zero'});
async function start(page){await page.goto('/');await expect(page.getByLabel('Layer height',{exact:true})).toBeEnabled();await page.getByRole('button',{name:'Preferences',exact:true}).click();const d=page.getByRole('dialog',{name:'Preferences'});await d.getByLabel('Load behaviour').selectOption('load_geometry_only');await d.getByRole('button',{name:'Close',exact:true}).click();}
async function save(page){const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Save project',exact:true}).click();return parseProject(await readFile(await(await pending).path(),'utf8'));}
// Explicit transport replay; the native suite checks actual original Model code.
async function replay(page,{allEmpty=false,fail=false,hold}={}){await page.route('**/api/geometry/inspect-import',async route=>{const prepared=prepareNativeImportInspection(route.request().postDataJSON().project);if(hold)await hold;const volumes=prepared.request.objects.map((o,i)=>allEmpty||i?0:8000);const json={format:'orca-native-import-inspection',version:1,sourceRevision:IMPORT_INSPECTION_REVISION,objects:prepared.request.objects.map((o,i)=>({id:o.id,volume:volumes[i]})),retainedIds:prepared.request.objects.filter((o,i)=>volumes[i]>0).map(o=>o.id),removedCount:volumes.filter(v=>v===0).length,unitSuggestion:'none'};await route.fulfill({status:fail?503:200,json:fail?{error:'Native inspection unavailable'}:json});});}
test('zero-volume notice precedes insertion, uses native information icon, and surviving geometry is one Undo action',async({page},info)=>{await start(page);await page.getByLabel('Choose a 3D model').setInputFiles(cube);await replay(page);await page.getByLabel('Choose a 3D model').setInputFiles(file());await expect(dialog(page)).toContainText('Objects with zero volume removed');await expect(page.getByRole('dialog')).toHaveCount(1);await expect(dialog(page).getByRole('img',{name:'Information'})).toHaveAttribute('src','/native-dialogs/info.svg');await expect(dialog(page).getByRole('button',{name:'OK',exact:true})).toBeFocused();await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(1);await page.screenshot({path:info.outputPath('zero-volume-notice.png')});await dialog(page).getByRole('button',{name:'OK',exact:true}).click();await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(2);const p=await save(page);expect(p.objects).toHaveLength(2);expect(p.objects.some(o=>o.name==='Flat sheet')).toBe(false);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(1);await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(2);});
test('all-empty geometry Open reports the removal and retains the previous document and edit history',async({page})=>{await start(page);await page.getByLabel('Choose a 3D model').setInputFiles(cube);const originalX=await page.getByLabel('position X',{exact:true}).inputValue();await page.getByLabel('position X',{exact:true}).fill('5');const before=await save(page);await replay(page,{allEmpty:true});await page.getByLabel('Open Orca Web project').setInputFiles(file(true));await dialog(page).getByRole('button',{name:'OK',exact:true}).click();await expect(page.getByRole('alert')).toContainText('no nonzero-volume objects');const after=await save(page);expect(after.objects).toEqual(before.objects);await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('position X',{exact:true})).toHaveValue(originalX);});
test('dismissal acknowledges the information and imports only surviving models',async({page})=>{await start(page);await replay(page);await page.getByLabel('Choose a 3D model').setInputFiles(file());await expect(dialog(page)).toBeVisible();await page.keyboard.press('Escape');await expect(dialog(page)).toHaveCount(0);await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(1);expect((await save(page)).objects).toHaveLength(1);});
test('failed or cancelled inspection leaves existing geometry and Undo intact, including a late response',async({page})=>{await start(page);await page.getByLabel('Choose a 3D model').setInputFiles(cube);const originalX=await page.getByLabel('position X',{exact:true}).inputValue();await page.getByLabel('position X',{exact:true}).fill('7');await replay(page,{fail:true});await page.getByLabel('Choose a 3D model').setInputFiles(file());await expect(page.getByRole('alert')).toContainText('Native inspection unavailable');await expect(page.locator('[data-tree-kind="object"]')).toHaveCount(1);await page.unrouteAll({behavior:'wait'});let release;const hold=new Promise(r=>release=r);await replay(page,{hold});const arrived=page.waitForRequest('**/api/geometry/inspect-import');await page.getByLabel('Choose a 3D model').setInputFiles(file());await arrived;await page.getByRole('button',{name:'Cancel import',exact:true}).click();release();await page.unrouteAll({behavior:'wait'});await expect(dialog(page)).toHaveCount(0);await expect(page.getByLabel('position X',{exact:true})).toHaveValue('7');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('position X',{exact:true})).toHaveValue(originalX);});
