import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createPresetCatalog } from '../../server/presets.js';
import { createCustomPresetCatalog } from '../../server/custom-presets.js';
import { inspectSlicer, sliceModel } from '../../server/slicer.js';

// Requires the actual installed native engine; never substitutes fixtures or skips.
test('real OrcaSlicer honors saved custom machine, process, and filament presets', {timeout:120000},async t=>{
  const binary=process.env.ORCA_SLICER_BIN||(process.platform==='darwin'?'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer':'orca-slicer');
  const health=await inspectSlicer(binary);assert.equal(health.available,true,health.error);assert.match(health.version,/^OrcaSlicer-2\.4\.2(?:\b|$)/);
  const dataDir=await mkdtemp(path.join(tmpdir(),'orca-custom-native-'));t.after(()=>rm(dataDir,{recursive:true,force:true}));
  const baseCatalog=await createPresetCatalog({binary});
  const catalog=await createCustomPresetCatalog({baseCatalog,dataDir});
  const defaults=baseCatalog.list().defaults,basePrinter=baseCatalog.getPreset(defaults.printerId,'machine');
  const printer=await catalog.saveCustom({type:'machine',name:'Native test custom printer',baseId:defaults.printerId,settings:{machine_start_gcode:`${basePrinter.machine_start_gcode||''}\n; NATIVE_CUSTOM_MACHINE_TEST`}});
  const processPreset=await catalog.saveCustom({type:'process',name:'Native test custom process',baseId:defaults.processId,settings:{layer_height:.12},compatiblePrinterIds:[printer.id]});
  const filament=await catalog.saveCustom({type:'filament',name:'Native test custom filament',baseId:defaults.filamentId,settings:{nozzle_temperature:[218],nozzle_temperature_initial_layer:[218]},compatiblePrinterIds:[printer.id]});
  const selected=catalog.resolveSelection({printerId:printer.id,processId:processPreset.id,filamentId:filament.id});
  const files={printerPath:path.join(dataDir,'machine.json'),profilePath:path.join(dataDir,'process.json'),filamentPath:path.join(dataDir,'filament.json')};
  await Promise.all([writeFile(files.printerPath,JSON.stringify(selected.printer)),writeFile(files.profilePath,JSON.stringify(selected.process)),writeFile(files.filamentPath,JSON.stringify(selected.filament))]);
  const output=path.join(dataDir,'result.gcode');
  await sliceModel({binary,input:path.resolve('tests/fixtures/cube.stl'),output,...files,timeoutMs:90000});
  const gcode=await readFile(output,'utf8');
  assert.match(gcode,/generated by OrcaSlicer/i);assert.match(gcode,/^G1 .*E[0-9]/m);
  assert.match(gcode,/NATIVE_CUSTOM_MACHINE_TEST/);assert.match(gcode,/layer_height = 0\.12/);
  assert.match(gcode,/nozzle_temperature = 218/);assert.match(gcode,/nozzle_temperature_initial_layer = 218/);
  for(const name of [printer.name,processPreset.name,filament.name])assert.ok(gcode.includes(name),name);
});
