import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,readFile,readdir,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{inspectSlicer,runSlicer}from'../../server/slicer.js';import{importNative3MF,exportNative3MF}from'../../shared/native-project.js';import{createNativeProjectService}from'../../server/native-projects.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';import{meshBounds}from'../../shared/geometry.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer';
const motions=code=>code.split(/\r?\n/).map(line=>line.split(';',1)[0].trim().replace(/\s+/g,' ')).filter(line=>/^G(?:0?[0123])(?:\s|$)/.test(line));
test('installed native slicer preserves cut families and every connector type without changing geometry toolpaths',{timeout:120000},async t=>{
 const engine=await inspectSlicer(binary);assert.equal(engine.available,true,engine.error);assert.match(engine.version,/^OrcaSlicer-2\.4\.2\b/);
 const directory=await mkdtemp(path.join(tmpdir(),'orca-cut-metadata-'));t.after(()=>process.env.ORCA_CUT_DEBUG?t.diagnostic(directory):rm(directory,{recursive:true,force:true}));const project=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url))),template=project.objects[0];
 project.nativeSettings={...project.nativeSettings,brim_type:'no_brim',skirt_loops:'0'};project.objects=[];
 for(const[type,index]of ['plug','dowel','snap'].map((type,index)=>[type,index])){
  const body=structuredClone(template);delete body.native.instanceFamily;body.id=`body-${index}`;body.name=`Cut body ${type}`;body.position=[45+index*35,70,0];body.native.groupId=body.id;body.native.objectName=body.name;body.native.cutId={id:'9007199254740997',checkSum:'3',connectorsCount:'3'};
  const connector=structuredClone(body);connector.id=`connector-${index}`;connector.name=`Connector-${index+1}`;connector.scale=[.2,.2,1.1];connector.position[2]=0;connector.native.partType='negative_part';connector.native.cutConnector={type,radiusTolerance:.125,heightTolerance:.25};project.objects.push(body,connector);
 }
 const service=createNativeProjectService({catalog:fixtureCatalog(project)}),prepared=await service.prepare({project,useEmbeddedSettings:true});
 async function slice(label,bytes){const dir=path.join(directory,label);await mkdir(dir);await mkdir(path.join(dir,'config'));await mkdir(path.join(dir,'output'));await writeFile(path.join(dir,'model.3mf'),bytes);await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--datadir',path.join(dir,'config'),'--outputdir',path.join(dir,'output'),'--export-3mf','reexport.3mf',path.join(dir,'model.3mf')],{cwd:dir,timeoutMs:60000,signal:t.signal});const gcodes=(await readdir(path.join(dir,'output'))).filter(name=>name.endsWith('.gcode'));assert.equal(gcodes.length,1);return{project:importNative3MF(await readFile(path.join(dir,'output','reexport.3mf'))),code:await readFile(path.join(dir,'output',gcodes[0]),'utf8')};}
 const actual=await slice('metadata',prepared.bytes);for(const expected of prepared.project.objects){const observed=actual.project.objects.find(object=>object.name===expected.name);assert.ok(observed,expected.name);assert.deepEqual(observed.native.cutId,expected.native.cutId);assert.deepEqual(observed.native.cutConnector,expected.native.cutConnector);assert.equal(observed.native.partType,expected.native.partType);assert.deepEqual(meshBounds(observed),meshBounds(expected));}
 const reference=structuredClone(project);for(const object of reference.objects){delete object.native.cutId;delete object.native.cutConnector;}const plain=await slice('geometry-reference',exportNative3MF(reference));assert.deepEqual(motions(actual.code),motions(plain.code));assert.ok(motions(actual.code).length>5000);t.diagnostic(`Native re-export preserves a >2^53 cut identity and plug/dowel/snap flags on all six volumes; ${motions(actual.code).length} motion commands exactly match the same geometry without cut metadata.`);
});
