import test from'node:test';import assert from'node:assert/strict';import{readFile,mkdir,mkdtemp,writeFile,readdir,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';import{Matrix4,Vector3}from'three';import{createNativeArrangeWorker}from'../../server/native-arrange-worker.js';import{validateNativeCutToPartsResult,applyNativeCutToParts}from'../../shared/native-cut-to-parts.js';import{cutPartsCases,cutPartsFixture}from'../fixtures/cut-to-parts-project.js';import{createMesh,meshBounds}from'../../shared/geometry.js';import{createPresetCatalog}from'../../server/presets.js';import{createNativeProjectService}from'../../server/native-projects.js';import{inspectSlicer,runSlicer}from'../../server/slicer.js';import{importNative3MF}from'../../shared/native-project.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer',reference=JSON.parse(await readFile(new URL('../fixtures/cut-to-parts-reference.json',import.meta.url)));
const nativeWorker=t=>{const w=createNativeArrangeWorker({binary:process.env.ORCA_ARRANGE_WORKER_BIN||path.resolve('native/build/arrange/orca-arrange-worker')});t.after(()=>w.shutdown());return w;};
const executeCut=(w,request)=>w.process(Buffer.from(JSON.stringify(request)));
const canonicalFaces=(vertices,triangles)=>triangles.map(face=>{const points=face.map(i=>JSON.stringify(vertices[i]));return[points,points.slice(1).concat(points[0]),points.slice(2).concat(points.slice(0,2))].map(p=>p.join('|')).sort()[0];}).sort();
test('original native cut_mesh and instance reset match exactly across seven ordinary, linked, mirrored and modifier cases',async t=>{const w=nativeWorker(t);assert.equal((await w.identity()).metadata.version,'2.4.2');for(let i=0;i<reference.cases.length;i++){
 const{prepared}=cutPartsFixture(cutPartsCases[i]),value=validateNativeCutToPartsResult(await executeCut(w,prepared.request),prepared.request),expected=reference.cases[i].expected;
 assert.deepEqual(value.instances.map(x=>x.matrix),expected.instances,reference.cases[i].name);assert.equal(value.minimumZBeforeGrounding,expected.minimumZBeforeGrounding);assert.equal(value.minimumZAfterGrounding,expected.minimumZAfterGrounding);
 assert.equal(value.parts.length,expected.parts.length);for(let n=0;n<value.parts.length;n++){const actual=value.parts[n],part=expected.parts[n];assert.deepEqual(actual.matrix,part.matrix);assert.equal(actual.name,part.name);assert.equal(actual.type,part.type);assert.equal(actual.fromUpper,part.fromUpper);assert.deepEqual(canonicalFaces(actual.vertices,actual.triangles),canonicalFaces(part.rawVertices,part.triangles),`${i}/${n}: exact oriented triangles`);if(i!==0){assert.deepEqual(actual.vertices,part.rawVertices);assert.deepEqual(actual.triangles,part.triangles);}}
 const out=applyNativeCutToParts(prepared,value);assert.equal(out.created.length,expected.parts.length*expected.instances.length);assert.equal(new Set(out.created.map(o=>o.native.instanceFamily)).size,1);
 }t.diagnostic('Original cap triangulation and Float32 vertices agree exactly; the previous mirrored Z discrepancy is removed without tolerance changes.');});
test('native kernel rejects malformed frames, identity, role and triangle requests',async t=>{const w=nativeWorker(t),{prepared}=cutPartsFixture(cutPartsCases[1]);for(const change of[r=>r.sourceRevision='wrong',r=>r.cutMatrix[0]=2,r=>r.instances[0].matrix[15]=0,r=>r.selectedInstanceId='missing',r=>r.sourceParts[0].triangles[0][0]=-1,r=>r.sourceParts[0].type='invented',r=>r.instances[0].autoDrop='yes']){const r=structuredClone(prepared.request);change(r);await assert.rejects(executeCut(w,r));}});
function referenceProject(project,expected){return{...project,objects:expected.instances.flatMap((matrix,i)=>expected.parts.map((part,index)=>{const frame=new Matrix4().fromArray(matrix).multiply(new Matrix4().fromArray(part.matrix)),positions=part.triangles.flatMap(face=>face.flatMap(v=>new Vector3(...part.rawVertices[v]).applyMatrix4(frame).toArray()));return createMesh({id:`reference-${i}-${index}`,name:part.name,plateId:'plate-1',filamentSlot:1,positions,native:{groupId:`reference-${i}`,instanceFamily:'reference-family',objectName:expected.name,partType:part.type,objectSettings:{wall_loops:'3'},partSettings:{},meshSource:{version:1,vertices:part.rawVertices.flat(),triangles:part.triangles.flat(),component:part.matrix,build:matrix}}});}))};}
const motion=code=>code.split(/\r?\n/).map(l=>l.split(';',1)[0].trim().replace(/\s+/g,' ')).filter(l=>/^G(?:0?[0123])(?:\s|$)/.test(l));
test('Cut to parts native slicing matches original cut_mesh output in four fixed translation-only runs',{timeout:180000},async t=>{assert.equal((await inspectSlicer(binary)).version,'OrcaSlicer-2.4.2');const w=nativeWorker(t),{project,prepared}=cutPartsFixture(cutPartsCases[1]),value=await executeCut(w,prepared.request),out=applyNativeCutToParts(prepared,value),expected=referenceProject(project,reference.cases[1].expected),catalog=await createPresetCatalog({binary}),service=createNativeProjectService({catalog}),ids=catalog.list().defaults,selection={printerId:ids.printerId,processId:ids.processId,filamentIds:[ids.filamentId]},overrides={process:{layer_height:.2,brim_type:'no_brim',enable_prime_tower:false,wall_generator:'classic',sparse_infill_pattern:'rectilinear'},filaments:[{slow_down_for_layer_cooling:[false]}]},inputs={reference:(await service.prepare({project:expected,selection,overrides})).bytes,web:(await service.prepare({project:{...project,objects:out.objects},selection,overrides})).bytes};
 const restored=importNative3MF(inputs.web);assert.equal(restored.objects.length,4);assert.equal(new Set(restored.objects.map(o=>o.native.instanceFamily)).size,1);assert.deepEqual(restored.objects.map(o=>[meshBounds(o).min[2],meshBounds(o).max[2]]),[[5,10],[0,5],[5,10],[0,5]]);
 const dir=await mkdtemp(path.join(tmpdir(),'orca-cut-parts-')),artifacts='test-results/cut-to-parts-native';t.after(()=>rm(dir,{recursive:true,force:true}));await mkdir(artifacts,{recursive:true});const rows=[];
 for(const[index,name]of['reference','reference','web','web'].entries()){const cwd=path.join(dir,`${index}-${name}`);await mkdir(path.join(cwd,'out'),{recursive:true});await mkdir(path.join(cwd,'config'));await writeFile(path.join(cwd,'model.3mf'),inputs[name]);await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--datadir',path.join(cwd,'config'),'--outputdir',path.join(cwd,'out'),path.join(cwd,'model.3mf')],{cwd,timeoutMs:60000,signal:t.signal});const file=(await readdir(path.join(cwd,'out'))).find(n=>n.endsWith('.gcode')),code=await readFile(path.join(cwd,'out',file),'utf8');await writeFile(path.join(artifacts,`${index}-${name}.3mf`),inputs[name]);await writeFile(path.join(artifacts,`${index}-${name}.gcode`),code);rows.push(motion(code));assert.match(code,/; total layer number: 50\n/);}
 assert.ok(rows[0].length>1000);for(let i=1;i<rows.length;i++){const differences=[];for(let n=0;n<Math.max(rows[0].length,rows[i].length);n++)if(rows[0][n]!==rows[i][n])differences.push({index:n,expected:rows[0][n],actual:rows[i][n]});assert.equal(differences.length,0,`Fixed run ${i}: ${JSON.stringify(differences.slice(0,4))}`);}t.diagnostic(`All four original/web fixed Cut to parts runs match ${rows[0].length} motion commands across two linked footprints; native cap triangulation and slicing are exact for this fixture.`);
});
