import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,readFile,readdir,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{inspectSlicer,runSlicer}from'../../server/slicer.js';import{importNative3MF}from'../../shared/native-project.js';import{createNativeProjectService}from'../../server/native-projects.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';import{cutNativeGroupWithConnectors}from'../../shared/cut-connectors.js';import{arrangeCutResult,cutMesh}from'../../shared/geometry-cut.js';import{createMesh,meshBounds,transformPositions}from'../../shared/geometry.js';import{parseGcode}from'../../shared/gcode.js';import oracle from'../fixtures/cut-connectors-native-reference.json'with{type:'json'};
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer',sectors={triangle:3,square:4,hexagon:6,circle:360};
const motions=code=>code.split(/\r?\n/).map(line=>line.split(';',1)[0].trim().replace(/\s+/g,' ')).filter(line=>/^G(?:0?[0123])(?:\s|$)/.test(line));
// Independent reference uses exact native C++ primitive fixture, then applies
// CutUtils.cpp's native processed transforms. It does not call web primitive or
// connector-generation helpers; planar clipping was verified independently.
function expectedPositions(plan,{hole=false,dowel=false}={}){
 const shape=hole&&plan.type==='snap'?'circle':plan.shape,index=hole&&plan.type==='snap'?0:plan.type==='snap'?'snap':plan.style==='prism'?0:plan.type==='plug'?1:2,mesh=oracle[index==='snap'?'snap':`${sectors[shape]}-${index}`],center=[0,1,2].map(axis=>(Math.min(...mesh.vertices.map(v=>v[axis]))+Math.max(...mesh.vertices.map(v=>v[axis])))/2),radius=Math.fround(plan.diameter/2),depth=Math.fround(plan.depth),height=plan.type==='dowel'&&plan.style==='prism'?depth*2:depth,radial=hole?Math.fround(plan.radiusTolerance):0,ht=hole?Math.fround(plan.heightTolerance):0,shift=(plan.type==='dowel'?0:depth/2)+ht/2-(hole&&plan.type!=='dowel'?.05:0),angle=-plan.rotation*Math.PI/180,c=Math.cos(angle),s=Math.sin(angle);
 return mesh.faces.flatMap(face=>face.flatMap(index=>{const raw=mesh.vertices[index].map((value,axis)=>Math.fround(Math.fround(value)-Math.fround(center[axis]))),x=raw[0]*(radius+radial),y=raw[1]*(radius+radial),z=raw[2]*(height+ht)+shift;return dowel?[x+plan.u,y+plan.v,z]:[plan.u+c*x-s*y,plan.v+s*x+c*y,10+z];}));
}
async function context(t){const engine=await inspectSlicer(binary);assert.equal(engine.available,true,engine.error);assert.match(engine.version,/^OrcaSlicer-2\.4\.2\b/);const root=await mkdtemp(path.join(tmpdir(),'orca-cut-connectors-'));t.after(()=>process.env.ORCA_CUT_DEBUG?t.diagnostic(root):rm(root,{recursive:true,force:true}));const p=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));p.objects[0].position=[60,70,0];p.nativeSettings={...p.nativeSettings,brim_type:'no_brim',skirt_loops:'0',layer_height:'.2',initial_layer_print_height:'.2',slow_down_layers:'0',slow_down_for_layer_cooling:['0'],detect_overhang_wall:'0'};const service=createNativeProjectService({catalog:fixtureCatalog(p)});
 return{p,async slice(name,project){const prepared=await service.prepare({project,useEmbeddedSettings:true}),dir=path.join(root,name);await mkdir(dir);await mkdir(path.join(dir,'config'));await mkdir(path.join(dir,'output'));await writeFile(path.join(dir,'model.3mf'),prepared.bytes);await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--datadir',path.join(dir,'config'),'--outputdir',path.join(dir,'output'),'--export-3mf','reexport.3mf',path.join(dir,'model.3mf')],{cwd:dir,timeoutMs:60000,signal:t.signal});const files=(await readdir(path.join(dir,'output'))).filter(name=>name.endsWith('.gcode'));assert.equal(files.length,1);return{code:await readFile(path.join(dir,'output',files[0]),'utf8'),native:importNative3MF(await readFile(path.join(dir,'output','reexport.3mf')))};}};
}
for(const {type,style,shape,depth}of [{type:'plug',style:'prism',shape:'circle',depth:3},{type:'plug',style:'frustum',shape:'triangle',depth:3},{type:'dowel',style:'prism',shape:'square',depth:3},{type:'dowel',style:'frustum',shape:'hexagon',depth:3},{type:'snap',style:'prism',shape:'circle',depth:4}])test(`native ${type} ${style} ${shape} cut matches independent source geometry and preserves editable connectors`,{timeout:120000},async t=>{
 const ctx=await context(t);if(type==='dowel'&&style==='frustum'){ctx.p.nativeSettings.enable_support='1';ctx.p.nativeSettings.support_type='normal(auto)';}const plan={type,style,shape,depth,u:70,v:80,diameter:3,radiusTolerance:.15,heightTolerance:.2,rotation:type==='snap'?0:23,snapSpace:.3,snapBulge:.15},raw=cutNativeGroupWithConnectors(ctx.p.objects,ctx.p.objects[0].id,{offset:10,connectors:[plan]}),cut=arrangeCutResult(raw,{width:250,depth:210,height:250}),p={...ctx.p,objects:cut.created},reference=structuredClone(p),ids={upper:new Set(cut.upper.map(o=>o.id)),lower:new Set(cut.lower.map(o=>o.id)),dowels:new Set(cut.dowels.map(o=>o.id))};
 for(const object of reference.objects)if(object.native.cutConnector){const hole=object.native.partType==='negative_part',dowel=ids.dowels.has(object.id);let positions=expectedPositions(plan,{hole,dowel});if(type==='dowel'&&hole){const clipped=cutMesh(createMesh({positions}),{offset:10});positions=ids.upper.has(object.id)?clipped.upper.positions:clipped.lower.positions;}assert.equal(positions.length,object.positions.length);object.positions=positions;}
 const actual=await ctx.slice('actual',p),expected=await ctx.slice('reference',reference);assert.deepEqual(motions(actual.code),motions(expected.code));assert.ok(motions(actual.code).length>1000);assert.equal(actual.native.objects.filter(o=>o.native.cutConnector).length,type==='dowel'?3:2);for(const object of actual.native.objects){assert.equal(object.native.cutId.id,cut.created[0].native.cutId.id);if(object.native.cutConnector)assert.equal(object.native.cutConnector.type,type);}
 const extrusions=parseGcode(actual.code).segments.filter(s=>s.kind==='extrusion'),lower=cut.lower.find(o=>o.native.partType==='normal_part'&&!o.native.cutConnector),upper=cut.upper.find(o=>o.native.partType==='normal_part'&&!o.native.cutConnector),lb=meshBounds(lower),ub=meshBounds(upper),inside=(s,b)=>s.end[0]>=b.min[0]&&s.end[0]<=b.max[0]&&s.end[1]>=b.min[1]&&s.end[1]<=b.max[1];assert.ok(extrusions.some(s=>inside(s,lb)&&s.end[2]>.8&&s.end[2]<2),'lower body prints');assert.ok(extrusions.some(s=>inside(s,ub)&&s.end[2]>.8&&s.end[2]<2),'upper body prints');
 if(type!=='dowel'){assert.ok(extrusions.some(s=>inside(s,lb)&&s.end[2]>10.4&&s.end[2]<10+depth),'plug/snap continues above its connected lower body');}
 const hole=cut.upper.find(o=>o.native.cutConnector),holeBounds=meshBounds(hole),center=holeBounds.center,innerRadius=type==='plug'&&shape==='triangle'?.15:.35;let checked=0;
 for(const s of extrusions)if(inside(s,ub)&&s.end[2]>.25&&s.end[2]<Math.min(depth-.5,2.5)){for(const fraction of [.25,.5,.75]){const point=[0,1].map(axis=>s.start[axis]+fraction*(s.end[axis]-s.start[axis]));assert.ok(Math.hypot(point[0]-center[0],point[1]-center[1])>innerRadius,'native negative connector must not deposit material in its central clearance');}checked++;}assert.ok(checked>100);
 t.diagnostic(`${motions(actual.code).length} exact native motion commands against C++-mesh reference; ${checked} upper-body extrusion moves avoid the connector void; ${actual.native.objects.filter(o=>o.native.cutConnector).length} connector volumes survive native re-export.`);
});
