import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createApp, defaultBinary } from '../../server/app.js';
import { createPresetCatalog } from '../../server/presets.js';
import { runSlicer } from '../../server/slicer.js';

function motionLines(gcode) {
  return gcode.split(/\r?\n/)
    .map(line => line.split(';', 1)[0].trim().replace(/\s+/g, ' '))
    .filter(line => /^G(?:0?[0123])(?:\s|$)/.test(line));
}

// One fixture and one explicit engine version. This does not claim engine-wide,
// project, visual, or printer-device parity.
async function checkNativeEquivalence(t, overrides, expectedConfig) {
  const directory = await mkdtemp(path.join(tmpdir(), 'orca-native-equivalence-'));
  let app, server;
  t.after(async () => {
    try {
      if (app) await app.locals.shutdown();
      if (server) await new Promise(resolve => server.close(resolve));
    } finally { await rm(directory, { recursive: true, force: true }); }
  });
  const binary = process.env.ORCA_SLICER_BIN || defaultBinary;
  const catalog = await createPresetCatalog({ binary });
  const defaults = catalog.list().defaults;
  assert.ok(defaults.printerId && defaults.processId && defaults.filamentId);
  const geometry = await readFile(new URL('../fixtures/cube.stl', import.meta.url));
  assert.equal((geometry.toString().match(/facet normal/g) || []).length, 12, 'The reference fixture must be a watertight twelve-triangle cube');

  app = await createApp({ dataDir: path.join(directory, 'api-data'), binary, catalog, sliceTimeoutMs: 60000 });
  server = app.listen(0, '127.0.0.1');
  await new Promise((resolve, reject) => { server.once('listening', resolve); server.once('error', reject); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const healthResponse = await fetch(`${base}/api/health`);
  const health = await healthResponse.json();
  assert.equal(healthResponse.status, 200, JSON.stringify(health));
  assert.match(health.engine.version, /^OrcaSlicer-2\.4\.2(?:\b|$)/, 'This differential baseline requires the real OrcaSlicer 2.4.2 engine');

  const form = new FormData();
  for (const [key, value] of Object.entries(defaults)) form.set(key, value);
  form.set('settings', JSON.stringify(overrides));
  form.set('model', new Blob([geometry]), 'model.stl');
  const upload = await fetch(`${base}/api/jobs`, { method: 'POST', body: form });
  const created = await upload.json();
  assert.equal(upload.status, 202, created.error);
  const deadline = Date.now() + 65000;
  let job;
  do {
    job = await (await fetch(`${base}/api/jobs/${created.id}`)).json();
    if (['ready', 'failed'].includes(job.status)) break;
    await new Promise(resolve => setTimeout(resolve, 100));
  } while (Date.now() < deadline);
  assert.equal(job.status, 'ready', job.error || JSON.stringify(job));
  const download = await fetch(`${base}/api/jobs/${job.id}/download`);
  assert.equal(download.status, 200);
  const apiGcode = await download.text();

  // Independent reference: explicitly construct native CLI arguments, bypassing
  // the API's preparation and sliceModel/buildSlicerArgs adapter.
  const reference = path.join(directory, 'reference');
  const output = path.join(reference, 'output');
  const dataDirectory = path.join(reference, 'config');
  await mkdir(output, { recursive: true });
  await mkdir(dataDirectory);
  const selected = catalog.resolveSelection({ ...defaults, overrides });
  for (const [type, config] of Object.entries(selected)) await writeFile(path.join(reference, `${type}.json`), JSON.stringify(config));
  const model = path.join(reference, 'model.stl');
  await writeFile(model, geometry);
  await runSlicer(binary, [
    '--slice', '0', '--outputdir', output,
    '--load-settings', `${path.join(reference, 'printer.json')};${path.join(reference, 'process.json')}`,
    '--load-filaments', path.join(reference, 'filament.json'),
    '--datadir', dataDirectory, model
  ], { cwd: reference, timeoutMs: 60000, signal: t.signal });
  const outputs = (await readdir(output)).filter(name => name.endsWith('.gcode'));
  assert.deepEqual(outputs, ['plate_1.gcode']);
  const referenceGcode = await readFile(path.join(output, 'plate_1.gcode'), 'utf8');
  for (const gcode of [apiGcode, referenceGcode]) {
    assert.match(gcode, /generated by OrcaSlicer/i);
    for (const expected of expectedConfig) assert.ok(gcode.includes(expected), `Native output must retain ${expected}`);
  }
  const actual = motionLines(apiGcode);
  const expected = motionLines(referenceGcode);
  assert.ok(expected.length >= 2000, `Expected thousands of native movement commands, got ${expected.length}`);
  const extrusionCount = expected.filter(line => /\bE[-+]?(?:\d|\.\d)/.test(line)).length;
  assert.ok(extrusionCount >= 1000, `Reference must include substantial extrusion moves, got ${extrusionCount}`);
  assert.equal(actual.length, expected.length, 'The API and reference must contain the same number of movement commands');
  const mismatch = expected.findIndex((line, index) => line !== actual[index]);
  assert.equal(mismatch, -1, `Motion command ${mismatch}: API=${actual[mismatch]} reference=${expected[mismatch]}`);
  t.diagnostic(`Matched all ${expected.length} motion/extrusion commands with ${health.engine.version}; ${JSON.stringify(overrides)}.`);
 }

test('OrcaSlicer 2.4.2 API and direct CLI produce identical cube motion/extrusion with the same native settings', { timeout: 120000 }, async t => {
  await checkNativeEquivalence(t, { layer_height: 0.16, outer_wall_speed: 70 }, ['layer_height = 0.16', 'outer_wall_speed = 70']);
});

test('expanded native process enums, percentages, accelerations and vectors survive real API/CLI slicing', { timeout: 120000 }, async t => {
  await checkNativeEquivalence(t, {
    layer_height: 0.2, outer_wall_line_width: '125%', ironing_type: 'topmost',
    bottom_surface_pattern: 'concentric', initial_layer_acceleration: 500,
    small_area_infill_flow_compensation_model: ['0,0\n0.2,0.4444']
  }, ['outer_wall_line_width = 125%', 'ironing_type = topmost', 'bottom_surface_pattern = concentric', 'initial_layer_acceleration = 500', '0.2,0.4444']);
});
