import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,readFile,readdir,rm,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{inspectSlicer,runSlicer}from'../../server/slicer.js';import{createPresetCatalog}from'../../server/presets.js';import{createNativeProjectService}from'../../server/native-projects.js';import{importNative3MF,nativeSettingsFromSelection}from'../../shared/native-project.js';import{updatePlatePrintSequence}from'../../shared/filament-sequence.js';import{parseGcode}from'../../shared/gcode.js';import{dropToBed}from'../../shared/geometry.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer';
async function context(t){const engine=await inspectSlicer(binary);assert.equal(engine.available,true,engine.error);assert.match(engine.version,/^OrcaSlicer-2\.4\.2\b/);const root=await mkdtemp(path.join(tmpdir(),'orca-order-'));t.after(()=>process.env.ORCA_ORDER_DEBUG?t.diagnostic(root):rm(root,{recursive:true,force:true}));const base=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));base.objects[0].position=[60,70,0];return{root,base,async slice(name,prepared){const dir=path.join(root,name);await mkdir(dir);await mkdir(path.join(dir,'config'));await mkdir(path.join(dir,'output'));await writeFile(path.join(dir,'model.3mf'),prepared.bytes);await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--datadir',path.join(dir,'config'),'--outputdir',path.join(dir,'output'),path.join(dir,'model.3mf')],{cwd:dir,timeoutMs:60000,signal:t.signal});const files=(await readdir(path.join(dir,'output'))).filter(f=>f.endsWith('.gcode'));assert.equal(files.length,1);return readFile(path.join(dir,'output',files[0]),'utf8');}};}
test('native per-plate custom filament order controls first layer, interval order and later overlap priority',{timeout:120000},async t=>{
 const c=await context(t),project=c.base,catalog=fixtureCatalog(project),selected=catalog.resolveSelection({printerId:'printer',processId:'process',filamentId:'red'}),blue=catalog.resolveSelection({printerId:'printer',processId:'process',filamentId:'blue'}).filament;
 project.nativeSettings={...project.nativeSettings,...nativeSettingsFromSelection({...selected,filaments:[selected.filament,blue]}),single_extruder_multi_material:'1',enable_prime_tower:'0',brim_type:'no_brim',skirt_loops:'0',layer_height:'.2',initial_layer_print_height:'.2'};
 project.objects[0].scale=[.5,.5,.1];project.objects[0]=dropToBed(project.objects[0]);const second=structuredClone(project.objects[0]);delete second.native.instanceFamily;second.id='second';second.name='Second filament';second.position[0]+=40;second.filamentSlot=2;second.native.groupId='second';second.native.objectSettings={extruder:'2'};second.native.partSettings={extruder:'2'};project.objects.push(second);
 const service=createNativeProjectService({catalog});const orders={firstLayer:[2,1],ranges:[{start:2,end:100,order:[1,2]},{start:4,end:7,order:[2,1]}]};project.plates[0]=updatePlatePrintSequence(project.plates[0],orders,2);
 const prepared=await service.prepare({project,useEmbeddedSettings:true}),code=await c.slice('ranged',prepared),layers=new Map();
 for(const segment of parseGcode(code).segments.filter(s=>s.kind==='extrusion'&&s.feature==='Outer wall')){const z=segment.end[2];if(!layers.has(z))layers.set(z,[]);const tools=layers.get(z);if(tools.at(-1)!==segment.tool)tools.push(segment.tool);}
 assert.equal(layers.size,10);for(const[z,tools]of layers){const layer=Math.round(z/.2),expected=layer===1||(layer>=4&&layer<=7)?[1,0]:[0,1];assert.deepEqual(tools,expected,`layer ${layer}`);}
 const reversed=structuredClone(project);reversed.plates[0]=updatePlatePrintSequence(reversed.plates[0],{firstLayer:[1,2],ranges:[]},2);const reversedCode=await c.slice('first-reversed',await service.prepare({project:reversed,useEmbeddedSettings:true}));const first=parseGcode(reversedCode).segments.find(s=>s.kind==='extrusion'&&s.feature==='Outer wall');assert.equal(first.tool,0);t.diagnostic('All 10 native layers use requested first/interval ordering, later overlapping ranges win; reversing first-layer order changes the first deposited tool.');
});
test('installed bundled legacy vector settings flatten into a valid native project and slice through embedded mode',{timeout:120000},async t=>{
 const c=await context(t),catalog=await createPresetCatalog({binary}),selected=catalog.resolveSelection(catalog.list().defaults);assert.equal(selected.printer.name,'Prusa MK4 0.4 nozzle');assert.equal(selected.printer.nozzle_type,'hardened_steel');
 const settings=nativeSettingsFromSelection(selected);assert.deepEqual(settings.nozzle_type,['hardened_steel']);c.base.nativeSettings=settings;const service=createNativeProjectService({catalog}),prepared=await service.prepare({project:c.base,useEmbeddedSettings:true});const code=await c.slice('canonical-bundled',prepared);assert.match(code,/generated by OrcaSlicer/);assert.match(code,/^; nozzle_type = hardened_steel$/m);assert.ok(parseGcode(code).segments.some(s=>s.kind==='extrusion'));t.diagnostic('Installed Prusa MK4/Standard/Generic PLA bundled defaults normalize then prepare and slice through the strict embedded project path.');
});
