import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createApp, defaultBinary } from '../../server/app.js';
import { createPresetCatalog } from '../../server/presets.js';
import { runSlicer } from '../../server/slicer.js';

// These acceptance tests require a real engine and installed system presets.
// They test native file loading/slicing, not web project editing or viewport parity.
async function setup(t) {
  const directory = await mkdtemp(path.join(tmpdir(), 'orca-native-formats-'));
  let app, server;
  t.after(async () => {
    try {
      if (app) await app.locals.shutdown();
      if (server) await new Promise(resolve => server.close(resolve));
    } finally { await rm(directory, { recursive: true, force: true }); }
  });
  const binary = process.env.ORCA_SLICER_BIN || defaultBinary;
  const catalog = await createPresetCatalog({ binary });
  const defaults = catalog.list().defaults;
  assert.ok(defaults.printerId && defaults.processId && defaults.filamentId);
  const dataDir = path.join(directory, 'data');
  app = await createApp({ dataDir, binary, catalog, sliceTimeoutMs: 60000 });
  server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const healthResponse = await fetch(`${base}/api/health`);
  const health = await healthResponse.json();
  assert.equal(healthResponse.status, 200, JSON.stringify(health));
  assert.match(health.engine.version, /OrcaSlicer-\d+\.\d+/);
  return { app, base, binary, catalog, defaults, directory, dataDir };
}

async function uploadAndWait(context, filename, geometry) {
  const form = new FormData();
  for (const [key, value] of Object.entries(context.defaults)) form.set(key, value);
  form.set('settings', '{}');
  form.set('model', new Blob([geometry]), filename);
  const response = await fetch(`${context.base}/api/jobs`, { method: 'POST', body: form });
  const created = await response.json();
  assert.equal(response.status, 202, created.error);
  const deadline = Date.now() + 65000;
  let job;
  do {
    job = await (await fetch(`${context.base}/api/jobs/${created.id}`)).json();
    if (['ready', 'failed'].includes(job.status)) break;
    await new Promise(resolve => setTimeout(resolve, 100));
  } while (Date.now() < deadline);
  assert.ok(['ready', 'failed'].includes(job.status), `Job did not finish: ${JSON.stringify(job)}`);
  await context.app.locals.waitForIdle();
  assert.deepEqual(await readdir(path.join(context.dataDir, 'uploads')), []);
  assert.deepEqual(await readdir(path.join(context.dataDir, 'work')), []);
  assert.equal((await readdir(path.join(context.dataDir, 'jobs'))).some(name => name.startsWith('.slice-')), false);
  return job;
}

async function assertNativeToolpaths(context, job) {
  assert.equal(job.status, 'ready', job.error);
  const response = await fetch(`${context.base}/api/jobs/${job.id}/download`);
  assert.equal(response.status, 200);
  const gcode = await response.text();
  assert.match(gcode, /generated by OrcaSlicer/i);
  assert.match(gcode, /^G1 .*E[0-9]/m);
  assert.ok(gcode.length > 10000, 'Expected genuine toolpaths, not a fixture stub');
  assert.ok(gcode.includes(job.printer));
  assert.ok(gcode.includes(job.filament));
  assert.ok(gcode.includes(`layer_height = ${job.settings.layer_height}`));
}

test('real OrcaSlicer loads and slices a watertight API-uploaded OBJ', { timeout: 120000 }, async t => {
  const context = await setup(t);
  const vertices = [[0,0,0], [20,0,0], [20,20,0], [0,20,0], [0,0,20], [20,0,20], [20,20,20], [0,20,20]];
  const faces = [[0,2,1], [0,3,2], [4,5,6], [4,6,7], [0,1,5], [0,5,4], [1,2,6], [1,6,5], [2,3,7], [2,7,6], [3,0,4], [3,4,7]];
  const obj = ['o cube', ...vertices.map(vertex => `v ${vertex.join(' ')}`), ...faces.map(face => `f ${face.map(index => index + 1).join(' ')}`)].join('\n') + '\n';
  const job = await uploadAndWait(context, 'watertight-cube.obj', obj);
  await assertNativeToolpaths(context, job);
});

test('real OrcaSlicer rejects malformed STL and the API offers no download', { timeout: 120000 }, async t => {
  const context = await setup(t);
  const job = await uploadAndWait(context, 'malformed.stl', 'solid malformed\nfacet normal 0 0 1\nthis is not STL geometry\nendsolid malformed\n');
  assert.equal(job.status, 'failed');
  assert.match(job.error, /OrcaSlicer exited/);
  assert.match(job.error, /load|model|file|format|facet|mesh|stl|empty/i);
  const download = await fetch(`${context.base}/api/jobs/${job.id}/download`);
  assert.equal(download.status, 404);
  assert.deepEqual((await readdir(path.join(context.dataDir, 'jobs'))).filter(name => name.endsWith('.gcode')), []);
});
