import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createMesh, meshBounds, sceneBounds, dropToBed, arrangeObjects, exportSTL, fitsOnBed } from '../../shared/geometry.js';
import { emptyProject, export3MF } from '../../shared/project.js';
import { createPresetCatalog } from '../../server/presets.js';
import { inspectSlicer, runSlicer } from '../../server/slicer.js';

const binary = process.env.ORCA_SLICER_BIN || (process.platform === 'darwin' ? '/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer' : 'orca-slicer');

async function setup(t) {
  const directory = await mkdtemp(path.join(tmpdir(), 'orca-native-geometry-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const engine = await inspectSlicer(binary);
  assert.equal(engine.available, true, engine.error);
  assert.match(engine.version, /^OrcaSlicer-2\.4\.2(?:\b|$)/);
  const catalog = await createPresetCatalog({ binary });
  const selected = catalog.resolveSelection({ ...catalog.list().defaults, overrides: { layer_height: 0.2, brim_type: 'no_brim' } });
  for (const [type, config] of Object.entries(selected)) await writeFile(path.join(directory, `${type}.json`), JSON.stringify(config));
  const stl = await readFile(new URL('../fixtures/cube.stl', import.meta.url), 'utf8');
  const positions = [...stl.matchAll(/vertex\s+([-+.\deE]+)\s+([-+.\deE]+)\s+([-+.\deE]+)/g)].flatMap(match => match.slice(1).map(Number));
  assert.equal(positions.length, 108, 'Geometry acceptance requires the twelve-triangle cube');
  return { directory, positions, signal: t.signal };
}

async function slice(context, label, bytes, extension) {
  const work = path.join(context.directory, label);
  await mkdir(work); await mkdir(path.join(work, 'config')); await mkdir(path.join(work, 'output'));
  const input = path.join(work, `scene.${extension}`);
  await writeFile(input, bytes instanceof ArrayBuffer ? new Uint8Array(bytes) : bytes);
  await runSlicer(binary, [
    '--slice', '0', '--arrange', '0', '--orient', '0', '--outputdir', path.join(work, 'output'),
    '--datadir', path.join(work, 'config'),
    '--load-settings', `${path.join(context.directory, 'printer.json')};${path.join(context.directory, 'process.json')}`,
    '--load-filaments', path.join(context.directory, 'filament.json'), input
  ], { cwd: work, timeoutMs: 60000, signal: context.signal });
  assert.deepEqual((await readdir(path.join(work, 'output'))).filter(name => name.endsWith('.gcode')), ['plate_1.gcode']);
  const gcode = await readFile(path.join(work, 'output', 'plate_1.gcode'), 'utf8');
  assert.match(gcode, /generated by OrcaSlicer/i);
  return gcode;
}

function objectMoves(gcode) {
  let printing = false, current = '', layerZ = 0;
  const objects = new Map(), all = [];
  for (const line of gcode.split(/\r?\n/)) {
    if (line.startsWith('; printing object ')) { printing = true; current = line.slice('; printing object '.length); if (!objects.has(current)) objects.set(current, []); }
    if (line.startsWith('; stop printing object ')) printing = false;
    const z = line.match(/^;(?:Z:|\s*Z_HEIGHT:)\s*([-+.\d]+)/);
    if (z) layerZ = Number(z[1]);
    if (!printing || !/^G[0123]\s/.test(line)) continue;
    const x = line.match(/\bX([-+.\d]+)/), y = line.match(/\bY([-+.\d]+)/), e = line.match(/\bE([-+.\d]+)/);
    // Object labels also bracket travel toward another object. Only deposited
    // extrusion belongs to the object's physical footprint (this preset uses M83).
    if (x && y && e && Number(e[1]) > 0) { const point = [Number(x[1]), Number(y[1]), layerZ]; all.push(point); objects.get(current).push(point); }
  }
  const bounds = points => ({ min: [0,1,2].map(axis => Math.min(...points.map(point => point[axis]))), max: [0,1,2].map(axis => Math.max(...points.map(point => point[axis]))) });
  assert.ok(all.length > 1000, 'Native output must contain substantial object toolpaths');
  return { all: bounds(all), objects: [...objects.values()].filter(points => points.length).map(bounds) };
}

function assertFootprint(actual, expected) {
  for (const axis of [0, 1]) {
    assert.ok(Math.abs(actual.min[axis] - expected.min[axis]) < 0.6, `Minimum ${axis}: ${actual.min[axis]} vs ${expected.min[axis]}`);
    assert.ok(Math.abs(actual.max[axis] - expected.max[axis]) < 0.6, `Maximum ${axis}: ${actual.max[axis]} vs ${expected.max[axis]}`);
  }
}

const motions = gcode => gcode.split(/\r?\n/).map(line => line.split(';', 1)[0].trim().replace(/\s+/g, ' ')).filter(line => /^G(?:0?[0123])(?:\s|$)/.test(line));

test('native transformed STL and exported 3MF preserve asymmetric scale, rotation and placement', { timeout: 120000 }, async t => {
  const context = await setup(t);
  const mesh = dropToBed(createMesh({ id: 'prism', name: 'Prism', positions: context.positions, position: [50,60,0], rotation: [0,0,90], scale: [1.5,0.5,0.75], plateId: 'plate-1' }));
  const expected = meshBounds(mesh);
  assert.deepEqual(expected.size, [10,30,15]);
  assert.deepEqual(expected.min, [55,55,0]);
  const project = { ...emptyProject(), name: 'Transformed native acceptance', objects: [mesh], selectedId: mesh.id };
  const stlGcode = await slice(context, 'stl', exportSTL([mesh]), 'stl');
  const threeMFGcode = await slice(context, '3mf', export3MF(project), '3mf');
  assertFootprint(objectMoves(stlGcode).all, expected);
  assertFootprint(objectMoves(threeMFGcode).all, expected);
  for (const gcode of [stlGcode, threeMFGcode]) assert.ok(/^;Z:15(?:\.0*)?$/m.test(gcode), 'The final printed layer must be at 15 mm');
  const actual = motions(threeMFGcode), reference = motions(stlGcode);
  assert.ok(reference.length >= 2000);
  assert.equal(actual.length, reference.length, 'Equivalent transformed surfaces should have identical motion counts');
  const mismatch = reference.findIndex((line, index) => line !== actual[index]);
  assert.equal(mismatch, -1, `First differing command ${mismatch}: 3MF=${actual[mismatch]}, STL=${reference[mismatch]}`);
  t.diagnostic(`STL and exported 3MF match ${reference.length} native motion commands at X55–65, Y55–85, Z0–15 mm.`);
});

test('native 3MF preserves multiple arranged object footprints without automatic recentering', { timeout: 120000 }, async t => {
  const context = await setup(t);
  const objects = arrangeObjects([
    createMesh({ id: 'first', name: 'First', positions: context.positions, scale: [1.5,0.5,0.5], plateId: 'plate-1' }),
    createMesh({ id: 'second', name: 'Second', positions: context.positions, rotation: [0,0,90], scale: [1,0.5,0.5], plateId: 'plate-1' })
  ], { width: 250, depth: 210, height: 220 }, { gap: 10, margin: 30 });
  assert.ok(objects.every(object => fitsOnBed(object, { width: 250, depth: 210, height: 220 })));
  const project = { ...emptyProject(), objects, selectedId: objects[0].id };
  const gcode = await slice(context, 'arranged-3mf', export3MF(project), '3mf');
  const paths = objectMoves(gcode);
  assert.equal(paths.objects.length, 2, '3MF should remain two native objects');
  assertFootprint(paths.all, sceneBounds(objects));
  const expected = objects.map(meshBounds).sort((a,b) => a.min[0] - b.min[0]);
  const actual = paths.objects.sort((a,b) => a.min[0] - b.min[0]);
  actual.forEach((bounds, index) => assertFootprint(bounds, expected[index]));
  assert.ok(actual[1].min[0] - actual[0].max[0] >= 9.5, 'Arrangement gap must survive native import and slicing');
  t.diagnostic('Both separate native objects retain their arranged positions and 10 mm clearance.');
});
