import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,mkdir,readFile,readdir,rm,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{inspectSlicer,runSlicer}from'../../server/slicer.js';import{createNativeProjectService}from'../../server/native-projects.js';import{importNative3MF,nativeSettingsFromSelection}from'../../shared/native-project.js';import{updateHeightRanges}from'../../shared/height-ranges.js';import{parseGcode}from'../../shared/gcode.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer';
const range=(minZ,maxZ,settings={})=>({minZ,maxZ,settings:{layer_height:'.2',extruder:'0',...settings}});
async function setup(t){
 const engine=await inspectSlicer(binary);assert.equal(engine.available,true,engine.error);assert.match(engine.version,/^OrcaSlicer-2\.4\.2\b/);const root=await mkdtemp(path.join(tmpdir(),'orca-height-ranges-'));t.after(()=>process.env.ORCA_HEIGHT_DEBUG?t.diagnostic(root):rm(root,{recursive:true,force:true}));
 const base=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));base.objects[0].position=[60,70,0];base.nativeSettings={...base.nativeSettings,layer_height:'.2',initial_layer_print_height:'.2',brim_type:'no_brim',skirt_loops:'0',outer_wall_speed:'70',slow_down_layers:'0',small_perimeter_threshold:'0',slow_down_for_layer_cooling:['0']};
 const service=createNativeProjectService({catalog:fixtureCatalog(base)});
 return{base,async slice(name,project){const prepared=await service.prepare({project,useEmbeddedSettings:true}),directory=path.join(root,name);await mkdir(directory);await mkdir(path.join(directory,'config'));await mkdir(path.join(directory,'output'));await writeFile(path.join(directory,'model.3mf'),prepared.bytes);
 await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--datadir',path.join(directory,'config'),'--outputdir',path.join(directory,'output'),path.join(directory,'model.3mf')],{cwd:directory,timeoutMs:60000,signal:t.signal});const files=(await readdir(path.join(directory,'output'))).filter(name=>name.endsWith('.gcode'));assert.equal(files.length,1);const code=await readFile(path.join(directory,'output',files[0]),'utf8');return{code,parsed:parseGcode(code),project:prepared.project};}};
}
const walls=result=>result.parsed.segments.filter(s=>s.kind==='extrusion'&&s.feature==='Outer wall');
test('native overlapping height ranges match independently sliced wall-speed references per layer',{timeout:120000},async t=>{
 const context=await setup(t),project=structuredClone(context.base);project.objects=updateHeightRanges(project.objects,project.objects[0].id,[range(4,8,{outer_wall_speed:30}),range(6,12,{outer_wall_speed:55})]);
 const actual=await context.slice('overlap',project),references=new Map();for(const speed of [30,55,70]){const reference=structuredClone(context.base);reference.nativeSettings.outer_wall_speed=String(speed);references.set(speed,walls(await context.slice(`reference-${speed}`,reference)));}
 const actualWalls=walls(actual);assert.ok(actualWalls.length>100);let measured=0;for(let i=0;i<actualWalls.length;i++){const segment=actualWalls[i],z=segment.end[2]-.1,speed=z>=4&&z<8?30:z>=8&&z<12?55:70,expected=references.get(speed)[i];assert.ok(expected);assert.deepEqual(segment.start,expected.start,`start at ${z}`);assert.deepEqual(segment.end,expected.end,`end at ${z}`);assert.ok(Math.abs(segment.extrusion-expected.extrusion)<1e-8);assert.ok(Math.abs(segment.feedrate-expected.feedrate)<.002,`${z}: ${segment.feedrate} vs ${expected.feedrate}`);measured++;}
 assert.equal(actualWalls.length,references.get(70).length);t.diagnostic(`${measured} native wall moves match three independent fixed-speed slices. 4–8 mm takes 30 mm/s; overlap trims the 55 mm/s range to 8–12 mm; gaps use 70 mm/s.`);
});
test('native ranged layer heights preserve the first layer, change interior increments, and restore default heights in gaps',{timeout:120000},async t=>{
 const context=await setup(t),project=structuredClone(context.base);project.objects=updateHeightRanges(project.objects,project.objects[0].id,[range(0,8,{layer_height:'.1'}),range(12,16,{layer_height:'.25'})]);
 const result=await context.slice('layer-heights',project),zs=[...result.code.matchAll(/^;Z:([\d.]+)/gm)].map(match=>Number(match[1]));assert.equal(zs[0],.2);for(const [lo,hi,height]of [[1,7,.1],[9,11,.2],[13,15,.25],[17,19,.2]]){const indices=zs.map((z,i)=>i).filter(i=>zs[i]>lo&&zs[i]<hi);assert.ok(indices.length>4);for(const i of indices)assert.ok(Math.abs(zs[i]-zs[i-1]-height)<.00001,`${zs[i]} has ${zs[i]-zs[i-1]} vs ${height}`);}
 assert.ok(zs.length>100);assert.ok(zs.at(-1)>=19.9&&zs.at(-1)<=20.3);t.diagnostic(`${zs.length} native layers; fixed 0.2 mm first layer, 0.1/0.25 mm interior ranges, and 0.2 mm gaps.`);
});
test('native height ranges override ordinary part settings while modifiers retain final priority',{timeout:120000},async t=>{
 const context=await setup(t),project=structuredClone(context.base),object=project.objects[0];object.native.partSettings.outer_wall_speed='90';object.native.groupId='cube';
 const modifier=structuredClone(object);modifier.id='modifier';modifier.name='Half cube modifier';modifier.scale=[.5,1,1];modifier.position[0]-=5;modifier.native.partType='modifier_part';modifier.native.partSettings={outer_wall_speed:'45'};project.objects.push(modifier);project.objects=updateHeightRanges(project.objects,object.id,[range(4,8,{outer_wall_speed:30})]);
 const result=await context.slice('modifier-precedence',project),inside=walls(result).filter(segment=>segment.end[2]>4.1&&segment.end[2]<7.9);assert.ok(inside.length>50);const speeds=new Set(inside.map(segment=>Math.round(segment.feedrate)));assert.ok(speeds.has(1800),JSON.stringify([...speeds]));assert.ok(speeds.has(2700),JSON.stringify([...speeds]));assert.ok(!speeds.has(5400),'Ordinary part speed must not override the range');t.diagnostic(`${inside.length} native ranged outer-wall segments include 30 mm/s range and 45 mm/s modifier speeds; ordinary 90 mm/s part speed is overridden.`);
});

test('native range filament assignment changes material only inside its Z interval',{timeout:120000},async t=>{
 const context=await setup(t),project=structuredClone(context.base),catalog=fixtureCatalog(project),selected=catalog.resolveSelection({printerId:'printer',processId:'process',filamentId:'red'}),blue=catalog.resolveSelection({printerId:'printer',processId:'process',filamentId:'blue'}).filament;
 project.nativeSettings={...project.nativeSettings,...nativeSettingsFromSelection({...selected,filaments:[selected.filament,blue]}),single_extruder_multi_material:'1',enable_prime_tower:'0'};project.objects=updateHeightRanges(project.objects,project.objects[0].id,[range(4,8,{extruder:'2'})],2);
 const result=await context.slice('filament-range',project),segments=walls(result);const inside=segments.filter(segment=>segment.end[2]-.1>=4&&segment.end[2]-.1<8),outside=segments.filter(segment=>segment.end[2]-.1<4||segment.end[2]-.1>=8);assert.ok(inside.length>40);assert.ok(outside.length>100);assert.ok(inside.every(segment=>segment.tool===1),JSON.stringify([...new Set(inside.map(s=>s.tool))]));assert.ok(outside.every(segment=>segment.tool===0),JSON.stringify([...new Set(outside.map(s=>s.tool))]));const used=result.code.match(/^; filament used \[mm\] = (.+)$/m)[1].split(',').map(Number);assert.ok(used[0]>0&&used[1]>0);t.diagnostic(`${inside.length} ranged wall segments use second filament; ${outside.length} outside segments retain first filament. Native material usage [${used}] mm.`);
});
