import test from'node:test';import assert from'node:assert/strict';import{readFile,writeFile,mkdir,mkdtemp,readdir,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{inspectSlicer,sliceModel}from'../../server/slicer.js';import{shrinkageCase}from'../fixtures/shrinkage-cases.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';import{exportSTL}from'../../shared/geometry.js';import{parseGcode}from'../../shared/gcode.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer';const zs=code=>[...code.matchAll(/^;Z:([\d.]+)/gm)].map(m=>Number(m[1]));
for(const extension of ['stl','obj'])for(const preservePosition of [true,false])test(`legacy ${extension.toUpperCase()} ${preservePosition?'preserved':'native automatic'} placement receives native second-apply shrinkage`,{timeout:120000},async t=>{
 const engine=await inspectSlicer(binary);assert.equal(engine.version,'OrcaSlicer-2.4.2');const root=await mkdtemp(path.join(tmpdir(),'orca-legacy-shrink-'));t.after(()=>process.env.ORCA_SHRINK_DEBUG?t.diagnostic(root):rm(root,{recursive:true,force:true}));const prepared=await shrinkageCase('z-only'),object=prepared.project.objects[0],selection=fixtureCatalog(prepared.project).resolveSelection({printerId:'printer',processId:'process',filamentId:'red'});for(const [name,type]of [['printer','machine'],['process','process'],['filament','filament']])Object.assign(selection[name],{from:'system',type,instantiation:'true'});selection.process.compatible_printers=[selection.printer.name];selection.filament.compatible_printers=[selection.printer.name];
 const input=path.join(root,`model.${extension}`),output=path.join(root,'result.gcode');if(extension==='stl')await writeFile(input,Buffer.from(exportSTL([object])));else{let text='o native_model\n';for(let i=0;i<object.positions.length;i+=3)text+=`v ${object.positions.slice(i,i+3).join(' ')}\n`;for(let i=0;i<object.positions.length/3;i+=3)text+=`f ${i+1} ${i+2} ${i+3}\n`;await writeFile(input,text);}
 const printerPath=path.join(root,'printer.json'),profilePath=path.join(root,'process.json'),filamentPath=path.join(root,'filament.json');await writeFile(printerPath,JSON.stringify(selection.printer));await writeFile(profilePath,JSON.stringify(selection.process));await writeFile(filamentPath,JSON.stringify(selection.filament));const result=await sliceModel({binary,input,output,printerPath,profilePath,filamentPath,preservePosition,legacySelection:selection,engineVersion:engine.version,signal:t.signal,timeoutMs:60000});const code=await readFile(output,'utf8');assert.equal(zs(code).length,102);assert.equal(zs(code).at(-1),20.4);assert.equal(result.shrinkageInitialization.method,'native-two-apply');assert.equal((await readdir(root)).some(file=>file.startsWith('.slice-')),false);
 const walls=parseGcode(code).segments.filter(s=>s.kind==='extrusion'&&/outer wall/i.test(s.feature)),xs=walls.flatMap(s=>[s.start[0],s.end[0]]),ys=walls.flatMap(s=>[s.start[1],s.end[1]]);assert.ok(walls.length>100);if(preservePosition){assert.ok(Math.abs(Math.min(...xs)-60.2)<.01);assert.ok(Math.abs(Math.min(...ys)-70.2)<.01);}t.diagnostic(`${extension} ${preservePosition?'preserved XY':'native automatic placement'}:102layers Z20.4; bounds ${Math.min(...xs)},${Math.min(...ys)} to ${Math.max(...xs)},${Math.max(...ys)}.`);
});
test('native placement STL export retains unscaled20mm vertices at100% and98% before initialization',{timeout:120000},async t=>{
 const{runSlicer}=await import('../../server/slicer.js'),{parseModel}=await import('../../src/model-loader.js'),{meshBounds}=await import('../../shared/geometry.js');const engine=await inspectSlicer(binary);assert.equal(engine.version,'OrcaSlicer-2.4.2');const root=await mkdtemp(path.join(tmpdir(),'orca-export-shrink-'));t.after(()=>rm(root,{recursive:true,force:true}));const prepared=await shrinkageCase('z-only'),source=prepared.project.objects[0],selection=fixtureCatalog(prepared.project).resolveSelection({printerId:'printer',processId:'process',filamentId:'red'});
 for(const[name,type]of[['printer','machine'],['process','process'],['filament','filament']])Object.assign(selection[name],{from:'system',type,instantiation:'true'});selection.process.compatible_printers=[selection.printer.name];selection.filament.compatible_printers=[selection.printer.name];const input=path.join(root,'model.stl');await writeFile(input,Buffer.from(exportSTL([source])));const bounds=[];
 for(const value of ['100%','98%']){const dir=path.join(root,value);await mkdir(dir);await mkdir(path.join(dir,'config'));const printer=path.join(dir,'printer.json'),process=path.join(dir,'process.json'),filament=path.join(dir,'filament.json');await writeFile(printer,JSON.stringify(selection.printer));await writeFile(process,JSON.stringify(selection.process));await writeFile(filament,JSON.stringify({...selection.filament,filament_shrink:[value],filament_shrinkage_compensation_z:[value]}));await runSlicer(binary,['--export-stl','--arrange','1','--orient','0','--load-settings',`${printer};${process}`,'--load-filaments',filament,'--outputdir',dir,'--datadir',path.join(dir,'config'),input],{cwd:dir,signal:t.signal,timeoutMs:60000});const filename=(await readdir(path.join(dir,'stl'))).find(f=>f.endsWith('.stl')),models=await parseModel(await readFile(path.join(dir,'stl',filename)),filename,{place:false});assert.equal(models.length,1);bounds.push(meshBounds(models[0]));}
 assert.deepEqual(bounds[0].size,[20,20,20]);assert.deepEqual(bounds[1],bounds[0]);t.diagnostic(`Both100% and98% native placement exports have identical raw mesh bounds ${JSON.stringify(bounds[0])}. Wall-centerline19.6mm is nozzle offset, not mesh scaling.`);
});

test('legacy preserved STL initialization matches all GUI reference motions for both98% axes',{timeout:120000},async t=>{
 const engine=await inspectSlicer(binary);assert.equal(engine.version,'OrcaSlicer-2.4.2');const root=await mkdtemp(path.join(tmpdir(),'orca-legacy-gui-'));t.after(()=>rm(root,{recursive:true,force:true}));const prepared=await shrinkageCase('both'),selection=fixtureCatalog(prepared.project).resolveSelection({printerId:'printer',processId:'process',filamentId:'red'}),input=path.join(root,'model.stl'),output=path.join(root,'result.gcode');await writeFile(input,Buffer.from(exportSTL(prepared.project.objects)));await sliceModel({binary,input,output,preservePosition:true,legacySelection:selection,engineVersion:engine.version,signal:t.signal,timeoutMs:60000});const actual=await readFile(output,'utf8'),reference=await readFile(new URL('../fixtures/native-gui-shrink98-2.4.2.gcode',import.meta.url),'utf8'),moves=code=>code.split(/\r?\n/).map(line=>line.split(';',1)[0].trim()).filter(line=>/^G[0123]\b/.test(line));assert.equal(moves(actual).length,9217);assert.deepEqual(moves(actual),moves(reference));
});
