import test from 'node:test';import assert from 'node:assert/strict';
import {createNativeImageWorker,IMAGE_WORKER_ID} from '../../server/native-images.js';
import {png,bmp,decodePng} from '../image-fixture.js';
async function worker(t){const value=createNativeImageWorker();t.after(()=>value.close());assert.deepEqual(await value.capabilities(),{available:true,...IMAGE_WORKER_ID});return value;}
test('pinned native wx cover generator center-crops a wide RGB image to the three native project sizes',async t=>{const value=await worker(t),colors=[[255,0,0,255],[0,255,0,255],[0,0,255,255]],result=await value.generate({name:'wide.png',data:png(3,1,x=>colors[x]).toString('base64')});for(const kind of ['cover','small','middle']){const output=result.images[kind],image=decodePng(Buffer.from(output.data,'base64'));assert.equal(image.width,output.width);assert.equal(image.height,output.height);assert.deepEqual(image.pixel(Math.floor(image.width/2),Math.floor(image.height/2)),colors[1]);if(kind==='small'){assert.deepEqual(image.pixel(0,0),colors[0]);assert.deepEqual(image.pixel(image.width-1,0),colors[2]);}else{// Native Float32 scaling produces 719×239 for the 240×240 cover: the first crop column averages red+green and the unfilled last row remains opaque black.
assert.deepEqual(image.pixel(0,0),kind==='cover'?[127,127,0,255]:colors[1]);assert.deepEqual(image.pixel(image.width-1,image.height-1),kind==='cover'?[0,0,0,255]:colors[1]);}}});
test('native cover decoding supports BMP and preserves uniform partial alpha while downscaling PNG',async t=>{const value=await worker(t);for(const[name,bytes,color]of [['image.bmp',bmp(),[30,60,90,255]],['alpha.png',png(1000,800,()=>[20,90,150,128]),[20,90,150,128]]]){const result=await value.generate({name,data:bytes.toString('base64')});for(const output of Object.values(result.images)){const image=decodePng(Buffer.from(output.data,'base64'));assert.deepEqual(image.pixel(Math.floor(image.width/2),Math.floor(image.height/2)),color);}}});

test('generated native covers survive web/native export relationships and installed Orca re-export',{timeout:90000},async t=>{
 const {mkdtemp,mkdir,readFile,writeFile,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),path=await import('node:path'),{createNativeProjectService}=await import('../../server/native-projects.js'),{createPresetCatalog}=await import('../../server/presets.js'),{runSlicer}=await import('../../server/slicer.js'),{exportNative3MF,importNative3MF}=await import('../../shared/native-project.js'),{addAttachments}=await import('../../shared/native-auxiliary.js'),{applyNativeCover}=await import('../../shared/native-cover.js'),{extractBoundedZip}=await import('../../shared/import-limits.js');
 const value=await worker(t),binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer',root=await mkdtemp(path.join(tmpdir(),'orca-cover-native-'));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(path.join(root,'config'));await mkdir(path.join(root,'output'));
 const service=createNativeProjectService({catalog:await createPresetCatalog({binary})}),original=(await service.importArchive(await readFile(new URL('../fixtures/native-gui-cube-2.4.2.3mf',import.meta.url)))).project,project=(await service.prepare({project:original,useEmbeddedSettings:true})).project,bytes=png(3,1);
 project.nativeAuxiliary=addAttachments(project.nativeAuxiliary,'Model Pictures',[{name:'cover.png',bytes}]);const generated=await value.generate({name:'cover.png',data:bytes.toString('base64')}),covered=applyNativeCover(project,'Auxiliaries/Model Pictures/cover.png',generated),archive=exportNative3MF(covered,{includeWebProject:false});await writeFile(path.join(root,'input.3mf'),archive);
 await runSlicer(binary,['--datadir',path.join(root,'config'),'--outputdir',path.join(root,'output'),'--export-3mf','covered.3mf',path.join(root,'input.3mf')],{cwd:root,timeoutMs:60000,signal:t.signal});
 const saved=await readFile(path.join(root,'output','covered.3mf')),output=extractBoundedZip(saved),restored=importNative3MF(saved);assert.equal(restored.nativeModelMetadata.DesignerCover,'cover.png');assert.deepEqual(restored.nativeAuxiliary.covers,covered.nativeAuxiliary.covers);for(const file of covered.nativeAuxiliary.files)assert.deepEqual(Buffer.from(output[file.path]),Buffer.from(file.data,'base64'),file.path);
 t.diagnostic('All three generated PNGs, original picture, DesignerCover and root package relationships survive installed Orca 2.4.2 re-export; GUI visual acceptance remains pending.');
});
test('native JPEG decoder processes the installed Orca homepage raster through the cover API',async t=>{const {readFile}=await import('node:fs/promises'),{attachmentImageSource}=await import('../../shared/native-auxiliary.js'),value=await worker(t),bytes=await readFile('/Applications/OrcaSlicer.app/Contents/Resources/web/homepage/img/a.jpg'),data=bytes.toString('base64'),source=attachmentImageSource({path:'Auxiliaries/Model Pictures/native.jpg',data}),result=await value.generate({name:'native.jpg',data});assert.equal(result.sourceWidth,source.width);assert.equal(result.sourceHeight,source.height);for(const output of Object.values(result.images)){const image=decodePng(Buffer.from(output.data,'base64'));assert.equal(image.width,output.width);assert.equal(image.height,output.height);assert.equal(image.pixel(Math.floor(image.width/2),Math.floor(image.height/2))[3],255);}});
