import test from 'node:test';import assert from 'node:assert/strict';import{readFile,writeFile,mkdtemp,mkdir,readdir,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{createPresetCatalog}from'../../server/presets.js';
import{resolveCatalogNativeSettings,resolveEmbeddedNativeSettings,runNativeConfig,defaultConfigWorker,NATIVE_CONFIG_REVISION}from'../../server/native-config.js';
import{createNativeProjectService,normalizeProjectSettings}from'../../server/native-projects.js';
import{importNative3MF,exportNative3MF}from'../../shared/native-project.js';
import{meshBounds,dropToBed}from'../../shared/geometry.js';
import{runSlicer}from'../../server/slicer.js';
const binary=process.env.ORCA_SLICER_BIN||process.env.ORCA_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer';
const catalogPromise=createPresetCatalog({binary});
async function choice(name){const catalog=await catalogPromise,printerId=catalog.list().printers.find(item=>item.name===name)?.id;assert.ok(printerId,`Installed preset is required: ${name}`);const selection=catalog.list({printerId}).defaults;selection.filamentIds=Array(catalog.getPreset(printerId,'machine').nozzle_diameter.length).fill(selection.filamentId);return{catalog,selection};}
async function model(settings){const project=importNative3MF(await readFile(new URL('../fixtures/native-gui-cube-2.4.2.3mf',import.meta.url))),original=project.objects[0],bounds=meshBounds({...original,position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]});original.positions=original.positions.map((value,index)=>value-bounds.min[index%3]);project.objects=settings.filament_settings_id.map((_,index)=>dropToBed({...structuredClone(original),id:`native-variant-${index}`,name:`Material ${index+1}`,scale:[.5,.5,.03],position:[60+index*25,70,0],filamentSlot:index+1,native:{groupId:`group-${index}`,objectName:`Material ${index+1}`,partType:'normal_part',objectSettings:{extruder:String(index+1)},partSettings:{}}}));project.plates=project.plates.map(plate=>({...plate,native:{metadata:{filament_map_mode:'Manual',filament_map:settings.filament_map.join(' ')}}}));project.nativeSettings={...settings,layer_height:'.2',initial_layer_print_height:'.2',enable_prime_tower:'0',skirt_loops:'0',brim_type:'no_brim'};return project;}
async function slice(project){const directory=await mkdtemp(path.join(tmpdir(),'orca-config-acceptance-'));try{await mkdir(path.join(directory,'config'));await mkdir(path.join(directory,'output'));await writeFile(path.join(directory,'model.3mf'),exportNative3MF(project));await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--datadir',path.join(directory,'config'),'--outputdir',path.join(directory,'output'),'--export-3mf','resaved.3mf',path.join(directory,'model.3mf')],{cwd:directory,timeoutMs:120000});const files=await readdir(path.join(directory,'output')),gcode=await readFile(path.join(directory,'output',files.find(file=>file.endsWith('.gcode'))),'utf8'),motions=gcode.split('\n').filter(line=>/^G[0123](?:\s|$)/.test(line)).map(line=>line.split(';')[0].trim());assert.ok(motions.length>500);return{motions,settings:importNative3MF(await readFile(path.join(directory,'output','resaved.3mf'))).nativeSettings};}catch(error){const logs=(await readdir(directory)).filter(file=>file.endsWith('.log'));error.nativeDiagnostic=(await Promise.all(logs.map(file=>readFile(path.join(directory,file),'utf8')))).join('\n');throw error;}finally{await rm(directory,{recursive:true,force:true});}}
test('exact native preset loader handles scalar numeric tokens, legacy enums, metadata and separate active variants', {timeout:120000}, async()=>{
 const h2d=await choice('Bambu Lab H2D 0.4 nozzle'),selection=h2d.selection;
 const result=await resolveCatalogNativeSettings({...h2d,overrides:{machine:{retraction_length:['.6','.9']},filaments:[{filament_max_volumetric_speed:['27']},{filament_max_volumetric_speed:['43']}],project:{nozzle_volume_type:['Standard','High Flow'],filament_map:['1','2']}}});
 assert.deepEqual(result.archiveSettings.filament_max_volumetric_speed,['27','40','25','43']);assert.deepEqual(result.effectiveSettings.filament_max_volumetric_speed,['27','43']);assert.deepEqual(result.archiveSettings.retraction_length,['0.6','0.8','0.8','0.9']);assert.deepEqual(result.archiveSettings.filament_ids,['GFA00','GFA00']);assert.deepEqual(result.filaments.map(item=>item.filament_max_volumetric_speed),[['27'],['43']]);
 const embedded=await resolveEmbeddedNativeSettings(result.archiveSettings);assert.deepEqual(embedded.filament_max_volumetric_speed,['27','43']);
 const request={printer:h2d.catalog.getPresetSource(selection.printerId,'machine'),process:h2d.catalog.getPresetSource(selection.processId,'process'),filaments:selection.filamentIds.map(id=>h2d.catalog.getPresetSource(id,'filament')),project:{filament_map:['1','2'],nozzle_volume_type:['Standard','High Flow']}};
 request.process.chain.push({bridge_speed:['57','83']});request.process.vendors.push('BBL');const scalar=await runNativeConfig(request);assert.equal(scalar.effectiveSettings.bridge_speed,'57');assert.equal(scalar.sourceRevision,NATIVE_CONFIG_REVISION);
 const j1=await resolveCatalogNativeSettings(await choice('Snapmaker J1 (0.4 nozzle)'));assert.equal(j1.archiveSettings.ensure_vertical_shell_thickness,'ensure_all');assert.deepEqual(j1.archiveSettings.printer_extruder_id,['1','2']);
});
test('native H2D/J1 slices agree between complete archive and selected settings; re-export preserves all inactive variants', {timeout:120000}, async t=>{
 for(const [name,volumes] of [['Bambu Lab H2D 0.4 nozzle',['Standard','Standard']],['Bambu Lab H2D 0.4 nozzle',['Standard','High Flow']],['Snapmaker J1 (0.4 nozzle)',['Standard','Standard']]]){
  const context=await choice(name),resolved=await resolveCatalogNativeSettings({...context,overrides:{project:{nozzle_volume_type:volumes,filament_map:['1','2']}}});
  const project=await model(normalizeProjectSettings(resolved.archiveSettings).settings),service=createNativeProjectService({catalog:context.catalog}),prepared=await service.prepare({project,useEmbeddedSettings:true});
  const actual=await slice(prepared.project),reference=await slice({...prepared.project,nativeSettings:{...normalizeProjectSettings(resolved.effectiveSettings).settings,...Object.fromEntries(['layer_height','initial_layer_print_height','enable_prime_tower','skirt_loops','brim_type'].map(key=>[key,project.nativeSettings[key]]))}});
  assert.deepEqual(actual.motions,reference.motions,`${name}: ${volumes.join('/')}`);t.diagnostic(`${name} ${volumes.join('/')}: ${actual.motions.length} matching motion lines; native re-export retains full variants`);assert.deepEqual(actual.settings.filament_max_volumetric_speed,resolved.archiveSettings.filament_max_volumetric_speed);assert.deepEqual(actual.settings.filament_self_index,resolved.archiveSettings.filament_self_index);assert.deepEqual(actual.settings.printer_extruder_variant,resolved.archiveSettings.printer_extruder_variant);
 }
});
test('native XL manual mapping rejects its unchanged default printable mask on physical nozzle three', {timeout:120000}, async()=>{
 const resolved=await resolveCatalogNativeSettings({...await choice('Prusa XL 5T 0.4 nozzle'),overrides:{project:{filament_map:['1','2','3','4','5']}}});assert.deepEqual(resolved.effectiveSettings.filament_printable,['3','3','3','3','3']);
 const project=await model(normalizeProjectSettings(resolved.archiveSettings).settings);await assert.rejects(()=>slice(project),error=>{assert.match(error.message,/exited 188/);assert.match(error.nativeDiagnostic,/can not be printed on extruder 3/);return true;});
});
import{zipSync,strFromU8,strToU8}from'fflate';import{extractBoundedZip}from'../../shared/import-limits.js';import{prusaFixture}from'../fixtures/prusa-project.js';
test('native Prusa import expands a selected H2D material with all source variants and preserves native part roles', {timeout:120000}, async()=>{
 const context=await choice('Bambu Lab H2D 0.4 nozzle'),entries=extractBoundedZip(prusaFixture());entries['Metadata/Slic3r_PE_model.config']=strToU8(strFromU8(entries['Metadata/Slic3r_PE_model.config']).replace('key="extruder" value="2"','key="extruder" value="3"'));
 const service=createNativeProjectService({catalog:context.catalog}),imported=await service.importArchive(zipSync(entries),{selection:context.selection,overrides:{filaments:[{}, {filament_max_volumetric_speed:['43']}],project:{nozzle_volume_type:['Standard','High Flow'],filament_map:['1','2']}}});
 assert.equal(imported.nativeImport.addedFilamentSlots,1);assert.deepEqual(imported.project.nativeSettings.filament_max_volumetric_speed,['25','40','25','43','25','43']);assert.deepEqual(imported.project.nativeSettings.filament_self_index,['1','1','2','2','3','3']);assert.deepEqual(imported.project.objects.map(object=>object.native.partType),['normal_part','negative_part','normal_part']);assert.deepEqual(imported.project.objects.map(object=>object.filamentSlot),[1,1,3]);const prepared=await service.prepare({project:imported.project,useEmbeddedSettings:true});assert.deepEqual(prepared.effectiveSettings.filament_max_volumetric_speed,['25','43','25']);
});
