import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import path from'node:path';import{createHash}from'node:crypto';import{createNativeGcodeWorker}from'../../server/native-gcode-worker.js';import{parseGcode}from'../../shared/gcode.js';import{derivePreviewAttributes}from'../../shared/gcode-attributes.js';
const binary=process.env.ORCA_GCODE_WORKER_BIN||path.resolve(process.env.ORCA_NATIVE_CACHE_DIR||'.native-cache','gcode-build',process.platform==='win32'?'orca-gcode-worker.exe':'orca-gcode-worker');
async function worker(t){const value=createNativeGcodeWorker({binary,resourcesDir:process.env.ORCA_RESOURCES_DIR||'/Applications/OrcaSlicer.app/Contents/Resources'});await value.identity();t.after(()=>value.shutdown());return value;}
test('full pinned native processor matches native GUI estimates and all 6,896 independent fallback scalar rows',async t=>{
 const native=await worker(t),bytes=await readFile(new URL('../fixtures/native-gui-shrink98-2.4.2.gcode',import.meta.url)),before=createHash('sha256').update(bytes).digest('hex'),result=await native.process(bytes);assert.equal(result.processorMoveCount,21543);assert.equal(result.vertexCount,29021);assert.equal(result.layers.length,102);assert.equal(Math.floor(result.modes[0].processorSeconds),42*60+18);assert.equal(result.layers[49].z,10);assert.ok(Math.abs(result.layers[49].seconds[0]-8.769728660583496)<1e-6);assert.equal(result.roles.length,8);assert.equal(result.roles.reduce((sum,r)=>sum+r.filamentGrams,0).toFixed(2),'4.24');assert.equal(result.roles.reduce((sum,r)=>sum+r.filamentMeters*1000,0).toFixed(2),'1423.12');
 const parsed=parseGcode(bytes.toString(),{includeSource:true}),attributes=derivePreviewAttributes(parsed),byLine=new Map(result.vertices.filter(v=>v[11]===10).map(v=>[v[12],v]));let compared=0;
 for(let i=0;i<parsed.segments.length;i++){const segment=parsed.segments[i],values=attributes.segments[i];if(values.height===null||values.flow===null||segment.kind!=='extrusion')continue;const vertex=byLine.get(segment.line);assert.ok(vertex,`native source line ${segment.line}`);assert.deepEqual([vertex[3],vertex[4],vertex[7]],[values.height,values.width,values.mm3PerMm],`native dimensions/linear flow at line${segment.line}`);assert.equal(Math.fround(vertex[5]*vertex[7]),values.flow);compared++;}assert.equal(compared,6896);
 assert.equal(result.vertices[0][18],null);assert.ok(result.vertices.filter(v=>v[12]<428).every(v=>v[18]===null));assert.equal(result.vertices.find(v=>v[12]>=428)?.[18],Math.fround(.026));assert.ok(result.vertices.some(v=>v[11]===10&&v[6]<v[5]));assert.ok(result.ranges.normal.customVisible.layerTimeLog.layerColors.length===102);assert.equal(createHash('sha256').update(bytes).digest('hex'),before);
});
test('native processing retains actual arc subdivisions, stationary events and source line IDs and is deterministic',async t=>{
 const native=await worker(t),code='G90\nM83\nT0\nG92 X0 Y0 Z0 E0\n; CHANGE_LAYER\nG1 Z0.2 F600\n; FEATURE: Outer wall\n; LAYER_HEIGHT: 0.2\n; LINE_WIDTH: 0.4\nG1 X10 E1 F1200\nG1 Y10 E1\nG2 X0 Y0 I-10 J0 E1\nG1 E-1\nG1 E1\nM900 K0.03\nG1 X5 E0.5\n';const first=await native.process(Buffer.from(code)),second=await native.process(Buffer.from(code));assert.deepEqual(second,first);assert.ok(first.vertices.filter(v=>v[12]===12&&v[11]===10).length>10);assert.ok(first.vertices.some(v=>v[11]===1));assert.ok(first.vertices.some(v=>v[11]===2));assert.ok(first.vertices.filter(v=>v[12]<15).every(v=>v[18]===null));assert.ok(first.vertices.filter(v=>v[12]>=15).every(v=>v[18]===Math.fround(.03)));assert.ok(first.modes[0].processorSeconds>0);
});
test('real processor HTTP endpoint hashes an owned ready file and clears native cache on deletion',async t=>{
 const {default:express}=await import('express'),{mkdtemp,mkdir,writeFile,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{createNativePreviewService}=await import('../../server/native-preview.js');
 const dataDir=await mkdtemp(path.join(tmpdir(),'orca-real-native-preview-'));await mkdir(path.join(dataDir,'jobs'));const bytes=await readFile(new URL('../fixtures/native-gui-shrink98-2.4.2.gcode',import.meta.url));await writeFile(path.join(dataDir,'jobs/owned.gcode'),bytes);const jobs=new Map([['owned',{id:'owned',status:'ready'}]]),service=createNativePreviewService({dataDir,jobStore:{get:id=>jobs.get(id)},binary,resourcesDir:process.env.ORCA_RESOURCES_DIR||'/Applications/OrcaSlicer.app/Contents/Resources'}),app=express();app.use('/api/jobs',service.router);const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(async()=>{await service.shutdown();await new Promise(resolve=>server.close(resolve));await rm(dataDir,{recursive:true,force:true});});const url=`http://127.0.0.1:${server.address().port}/api/jobs`;assert.equal((await(await fetch(url+'/native-preview/capabilities')).json()).available,true);const response=await fetch(url+'/owned/native-preview');assert.equal(response.status,200);const data=await response.json();assert.equal(data.sourceSha256,createHash('sha256').update(bytes).digest('hex'));assert.equal(data.vertexCount,29021);assert.equal(service.cacheInfo.entries,1);jobs.delete('owned');service.invalidate('owned');assert.equal(service.cacheInfo.entries,0);assert.equal((await fetch(url+'/owned/native-preview')).status,404);
});
