import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';import{Matrix4,Vector3}from'three';import{importNative3MF}from'../../shared/native-project.js';import{meshPointMatrix}from'../../shared/brim-ears.js';import{createNativeEmbossWorker}from'../../server/native-emboss-worker.js';
const stage=fileURLToPath(new URL('../../',import.meta.url)),binary=process.env.ORCA_EMBOSS_WORKER_BIN||path.join(stage,'native/build/emboss/orca-emboss-worker'),font=process.env.ORCA_EMBOSS_REFERENCE_FONT||'/System/Library/Fonts/Helvetica.ttc';
const worker=()=>createNativeEmbossWorker({binary,resolveFont:async id=>{assert.equal(id,'helvetica');return{filename:font};}});
const chunks=(a,n)=>Array.from({length:a.length/n},(_,i)=>a.slice(i*n,i*n+n));
export async function reference(mode){const project=importNative3MF(await readFile(new URL(`../fixtures/native-text-${mode}-2.4.2.3mf`,import.meta.url))),part=project.objects.find(o=>o.native.textConfiguration),source=part.native.meshSource,frame=meshPointMatrix(part).multiply(new Matrix4().fromArray(part.native.embossShape.frame)),inverse=frame.clone().invert(),rawToWorld=new Matrix4().fromArray(source.build).multiply(new Matrix4().fromArray(source.component));const vertices=chunks(source.vertices,3).map(v=>new Vector3(...v).applyMatrix4(rawToWorld).applyMatrix4(inverse).toArray());const t=part.native.textConfiguration,s=part.native.embossShape;const request={text:t.text,lineHeight:t.lineHeight,depth:s.depth,horizontal:t.horizontal,vertical:t.vertical,useSurface:s.useSurface};if(s.useSurface){request.transform=frame.toArray();request.sources=project.objects.filter(o=>o!==part).map(o=>{const raw=o.native.meshSource;return{vertices:chunks(raw.vertices,3),triangles:chunks(raw.triangles,3),transform:meshPointMatrix(o).multiply(new Matrix4().fromArray(raw.build)).multiply(new Matrix4().fromArray(raw.component)).toArray()};});}return{project,part,frame,vertices,triangles:chunks(source.triangles,3),request};}
const canonical=t=>[t,t.slice(1).concat(t[0]),[t[2],t[0],t[1]]].map(a=>a.join(',')).sort()[0];
function edges(triangles){const result=new Map();for(const t of triangles)for(let i=0;i<3;i++){const a=t[i],b=t[(i+1)%3],key=a<b?`${a},${b}`:`${b},${a}`;result.set(key,(result.get(key)||0)+(a<b?1:-1));}return [...result].filter(([,count])=>count).sort((a,b)=>a[0].localeCompare(b[0]));}
function area2(vertices,t){const[a,b,c]=t.map(i=>vertices[i]);return(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);}
for(const mode of ['planar','surface'])test(`pinned native worker regenerates captured GUI ${mode} mesh using native font/CGAL geometry`,async t=>{const expected=await reference(mode),service=worker();t.after(()=>service.close());const actual=await service.generate(expected.request,{fontId:'helvetica',signal:t.signal});assert.equal(actual.vertices.length,expected.vertices.length);assert.equal(actual.triangles.length,expected.triangles.length);let maxError=0;const mapping=actual.vertices.map(a=>{let nearest=-1,distance=Infinity;expected.vertices.forEach((b,index)=>{const d=Math.hypot(...a.map((v,i)=>v-b[i]));if(d<distance){nearest=index;distance=d;}});maxError=Math.max(maxError,distance);assert.ok(distance<1e-6,`Native vertex error ${distance} mm`);return nearest;});assert.equal(new Set(mapping).size,mapping.length);
 if(mode==='planar'){assert.deepEqual(actual.triangles,expected.triangles);assert.deepEqual(mapping,mapping.map((_,i)=>i));}
 else{const a=new Map(actual.triangles.map(face=>{const t=face.map(i=>mapping[i]);return[canonical(t),t];})),b=new Map(expected.triangles.map(t=>[canonical(t),t]));const changedA=[...a].filter(([key])=>!b.has(key)).map(([,face])=>face),changedB=[...b].filter(([key])=>!a.has(key)).map(([,face])=>face);assert.equal(changedA.length,changedB.length);for(const faces of [changedA,changedB])for(const face of faces){const z=face.map(i=>expected.vertices[i][2]);assert.ok(Math.max(...z)-Math.min(...z)<1e-7,'Only coplanar cap triangulation may differ');assert.ok(Math.abs(z[0]-1)<1e-6||Math.abs(z[0]+.015)<1e-6);}
 for(const front of [true,false]){const subset=faces=>faces.filter(face=>(expected.vertices[face[0]][2]>.5)===front),ca=subset(changedA),cb=subset(changedB);assert.deepEqual(edges(ca),edges(cb),'Changed cap triangles retain the same oriented boundary');const area=faces=>faces.reduce((sum,face)=>{const value=area2(expected.vertices,face);assert.equal(value>0,front,'Cap orientation is retained');return sum+value;},0);assert.ok(Math.abs(area(ca)-area(cb))<1e-8,'Coplanar coverage area is identical');}t.diagnostic(`${changedA.length} triangles differ only by native CGAL cap triangulation; oriented boundaries and covered area match.`);}
 t.diagnostic(`${actual.vertices.length} corresponding vertices; ${actual.triangles.length} triangles; maximum saved-coordinate error ${maxError} mm.`);
});
test('real native worker applies native typography and extrusion options and rejects unavailable collection or missing per-glyph sources',async t=>{const service=worker();t.after(()=>service.close());const baseline={text:'Ab\nCd',lineHeight:13,depth:1};const normal=await service.generate(baseline,{fontId:'helvetica',signal:t.signal}),altered=await service.generate({...baseline,charGap:120,lineGap:200,boldness:.15,skew:.1,horizontal:'left',vertical:'top',depth:2,outside:false},{fontId:'helvetica',signal:t.signal});assert.notDeepEqual(normal.vertices,altered.vertices);const z=altered.vertices.map(v=>v[2]);assert.ok(Math.abs(Math.min(...z)+1.985)<1e-6);assert.ok(Math.abs(Math.max(...z)-.015)<1e-6);await assert.rejects(service.generate({...baseline,collection:999},{fontId:'helvetica'}),/collection index/);await assert.rejects(service.generate({...baseline,perGlyph:true,transform:new Matrix4().toArray()},{fontId:'helvetica'}),/source meshes/);});

test('real native font parser reports collection metrics for the captured Helvetica file',async t=>{const service=worker();t.after(()=>service.close());const info=await service.fontInfo({fontId:'helvetica',signal:t.signal});assert.equal(info.collections.length,6);assert.equal(info.collections[0].style,'Regular');assert.equal(info.collections[1].style,'Bold');assert.equal(info.collections[0].unitsPerEm,2048);});
