import {createNativeProjectService} from '../../server/native-projects.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';
import test from 'node:test';import assert from 'node:assert/strict';import{readFile,writeFile,mkdir,mkdtemp,readdir,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{runNativeConfig,NATIVE_CONFIG_REVISION}from'../../server/native-config.js';import{pasteNativeProcessSettings}from'../../server/native-settings-clipboard.js';
import{importNative3MF,exportNative3MF}from'../../shared/native-project.js';import{captureLayerClipboard,pasteLayerClipboard}from'../../shared/native-settings-clipboard.js';import{runSlicer}from'../../server/slicer.js';
const references=JSON.parse(await readFile(new URL('../fixtures/native-settings-clipboard-reference.json',import.meta.url),'utf8'));
test('native process settings Paste matches twelve independently compiled original ObjectList cases',{timeout:60000},async t=>{assert.equal(references.provenance.revision,NATIVE_CONFIG_REVISION);for(const {name,expected,...request} of references.cases){const result=await runNativeConfig({operation:'paste-process-settings',...request});assert.deepEqual(result.settings,expected,name);}t.diagnostic('12 exact original ObjectList comparisons, including typed equality, preserved destination extruders, parent compensation and reuse across multiple destinations.');});
test('native settings Paste rejects excessive/unknown inputs and retains method types through validated API service',{timeout:30000},async()=>{
 await assert.rejects(()=>runNativeConfig({operation:'paste-process-settings',clipboard:{wall_loops:'5'},globalSettings:{},targets:Array(257).fill({kind:'object',settings:{}})}),/1–256/);
 const service={run:runNativeConfig};const result=await pasteNativeProcessSettings({clipboard:{version:1,kind:'part',settings:{wall_loops:'5',layer_height:'.16'}},targets:[{kind:'part',settings:{extruder:'2'},parentSettings:{layer_height:'.12',wall_loops:'3'}}],globalSettings:{wall_loops:'2',layer_height:'.2'},filamentCount:2},service);assert.deepEqual(result.settings,[{extruder:'2',layer_height:'0.2',wall_loops:'5'}]);
 await assert.rejects(()=>pasteNativeProcessSettings({clipboard:{version:1,kind:'part',settings:{post_process:['not allowed']}},targets:[{kind:'part',settings:{}}],globalSettings:{}},service),/Unsupported object/);
});
test('native process and height-range clipboard preserve settings through installed slicing and re-export',{timeout:120000},async()=>{
 const p=importNative3MF(await readFile(new URL('../fixtures/native-gui-cube-2.4.2.3mf',import.meta.url))),o=p.objects[0];
 const result=await runNativeConfig({operation:'paste-process-settings',clipboard:{wall_loops:'5',sparse_infill_density:'25%'},globalSettings:{},targets:[{kind:'object',settings:{extruder:'1',wall_loops:'2'}}]});o.native.objectSettings=result.settings[0];
 const ranges=[{minZ:1,maxZ:5,settings:{layer_height:'.1',wall_loops:'6',extruder:'0'}}];p.objects=pasteLayerClipboard(p.objects,o.id,captureLayerClipboard(ranges),1);const dir=await mkdtemp(path.join(tmpdir(),'orca-settings-clipboard-'));
 const service=createNativeProjectService({catalog:fixtureCatalog(p)});
 try{const prepared=await service.prepare({project:p,useEmbeddedSettings:true});await mkdir(path.join(dir,'output'));await mkdir(path.join(dir,'config'));await writeFile(path.join(dir,'model.3mf'),prepared.bytes);await runSlicer(process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer',['--slice','0','--arrange','0','--orient','0','--datadir',path.join(dir,'config'),'--outputdir',path.join(dir,'output'),'--export-3mf','resaved.3mf',path.join(dir,'model.3mf')],{cwd:dir,timeoutMs:90000});const entries=await readdir(path.join(dir,'output')),gcode=await readFile(path.join(dir,'output',entries.find(name=>name.endsWith('.gcode'))),'utf8'),resaved=importNative3MF(await readFile(path.join(dir,'output','resaved.3mf')));assert.equal(resaved.objects[0].native.objectSettings.wall_loops,'5');assert.equal(resaved.objects[0].native.objectSettings.sparse_infill_density,'25%');assert.equal(resaved.objects[0].native.layerConfigRanges[0].settings.wall_loops,'6');const z=[...gcode.matchAll(/^;Z:([\d.]+)/gm)].map(m=>Number(m[1]));assert.ok(z.length>125);assert.ok(z.slice(1).some((value,index)=>value>1&&value<5&&Math.abs(value-z[index]-.1)<1e-6));assert.match(gcode,/^G1 .*E[\d.]/m);
 }catch(error){for(const name of await readdir(dir))if(name.endsWith('.log'))console.error((await readFile(path.join(dir,name),'utf8')).split('\n').slice(-24).join('\n'));throw error;}finally{await service.close();await rm(dir,{recursive:true,force:true});}
});
