import test from'node:test';import assert from'node:assert/strict';import{readFile,mkdtemp,writeFile,rm}from'node:fs/promises';import{execFile}from'node:child_process';import{promisify}from'node:util';import{tmpdir}from'node:os';import path from'node:path';import{validateNativeFillBedResult}from'../../shared/native-fill-bed.js';
const exec=promisify(execFile),binary=process.env.ORCA_ARRANGE_WORKER_BIN||path.resolve('native/build/arrange/orca-arrange-worker'),reference=JSON.parse(await readFile(new URL('../fixtures/native-fill-reference.json',import.meta.url)));async function run(request){const directory=await mkdtemp(path.join(tmpdir(),'native-fill-'));try{await writeFile(path.join(directory,'input.json'),JSON.stringify(request));await exec(binary,[path.join(directory,'input.json'),path.join(directory,'output.json')],{timeout:60000,maxBuffer:65536});return JSON.parse(await readFile(path.join(directory,'output.json')));}finally{await rm(directory,{recursive:true,force:true});}}
test('native Fill matches unchanged original GUI prepare/process/finalize and float-grid reference in 12 cases',async()=>{const version=await exec(binary,['--version']);assert.equal(version.stdout.trim(),`OrcaArrangeWorker-2.4.2 revision${reference.sourceCommit}`);assert.equal(reference.cases.length,12);for(const fixture of reference.cases){const result=validateNativeFillBedResult(await run(fixture.request),fixture.request);assert.equal(result.added,fixture.expected.added,fixture.name);assert.equal(result.requiresArrange,fixture.expected.requiresArrange,fixture.name);assert.equal(result.diagnostics.path,fixture.expected.path,fixture.name);assert.deepEqual(result.instances.map(i=>i.matrix),fixture.expected.instances,fixture.name);assert.deepEqual(result.diagnostics.placements,fixture.expected.placements,fixture.name);}});
test('native Fill rejects candidate/output limits, malformed frames and unimplemented viewport-dependent inputs',async()=>{const source=reference.cases[0].request;const cases=[
 [r=>{for(const p of r.objects[0].parts)for(const v of p.vertices){v[0]/=100;v[1]/=100;}},/4096 candidate/],
 [r=>{for(const p of r.objects[0].parts)for(const v of p.vertices){v[0]/=10;v[1]/=10;}},/256-instance/],
 [r=>{r.objects[0].instances[0].matrix[15]=0;},/affine transform/],
 [r=>{r.isBbl='false';},/vendor context/],
 [r=>{r.objects[0].instances[0].matrix[0]=1e7;},/world coordinates/],
 [r=>{r.settings.enable_prime_tower='1';r.settings.timelapse_type='1';},/viewport tower footprint/],
 [r=>{r.settings.extruder_printable_area=['0x0,100x0,100x100,0x100'];},/per-extruder printable regions/]
 ];for(const[edit,expected]of cases){const request=structuredClone(source);edit(request);await assert.rejects(run(request),expected);}});
