import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {Matrix4} from 'three';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createNativeArrangeWorker} from '../../server/native-arrange-worker.js';
import {prepareNativeImportInspection,applyNativeImportInspection} from '../../shared/native-import-inspection.js';
import {inspectionBox,inspectionProject,emptyVolumeFixture} from '../fixtures/import-inspection-project.js';
import {fixture} from '../fixtures/native-instance-project.js';
async function worker(t){const w=createNativeArrangeWorker({binary:process.env.ORCA_ARRANGE_WORKER_BIN||path.resolve('native/build/arrange/orca-arrange-worker')});t.after(()=>w.shutdown());return w;}
const inspect=async(w,p)=>{const prepared=prepareNativeImportInspection(p);return{prepared,result:await w.process(Buffer.from(JSON.stringify(prepared.request)))};};
test('original native mesh statistics retain float rounding and count solids through the first instance only',async t=>{const w=await worker(t),p=fixture({mirror:true}),{result}=await inspect(w,p);assert.equal(result.objects.length,1);assert.equal(result.objects[0].volume,2000.0001220703125);assert.equal(result.removedCount,0);assert.equal(result.unitSuggestion,'none');p.objects[1].native.partType=p.objects[3].native.partType='negative_part';assert.equal((await inspect(w,p)).result.objects[0].volume,1000.0000610351562);});
test('native filter removes open planar meshes and modifier-only objects while retaining a valid source solid',async t=>{const w=await worker(t),p=emptyVolumeFixture();p.objects.push(inspectionBox(10,{id:'modifier',role:'modifier_part'}));const{prepared,result}=await inspect(w,p);assert.deepEqual(result.objects.slice(1).map(o=>o.volume),[0,0]);assert.equal(result.removedCount,2);const out=applyNativeImportInspection(prepared,result);assert.equal(out.objects.length,1);assert.equal(out.objects[0],p.objects[0]);});
test('native source applies zero, meters and inches thresholds in order to float mesh volumes',async t=>{const w=await worker(t);for(const[size,unit,removed]of [[.0001,'none',1],[.1,'meters',0],[.2,'inches',0],[1,'inches',0],[2,'none',0],[10,'none',0]]){const{result}=await inspect(w,inspectionProject([inspectionBox(size)]));assert.equal(result.unitSuggestion,unit,`size ${size}`);assert.equal(result.removedCount,removed,`size ${size}`);}});
test('cut-family checksum and connector count participate in native imperial detection',async t=>{const w=await worker(t),cutId={id:'42',checkSum:'2',connectorsCount:'0'},p=inspectionProject([inspectionBox(1,{id:'small',cutId}),inspectionBox(10,{id:'large',cutId})]);assert.equal((await inspect(w,p)).result.unitSuggestion,'none');p.objects[1].native.cutId.checkSum='3';assert.equal((await inspect(w,p)).result.unitSuggestion,'inches');p.objects[1].native.cutId.checkSum='2';p.objects[1].native.cutId.connectorsCount='1';assert.equal((await inspect(w,p)).result.unitSuggestion,'inches');});
test('native determinant uses volume and first-instance scaling and ignores later instances for unit inference',async t=>{const w=await worker(t),base=inspectionBox(1,{component:new Matrix4().makeScale(-2,3,4),build:new Matrix4().makeScale(2,2,2)});const out=(await inspect(w,inspectionProject([base]))).result;assert.ok(Math.abs(out.objects[0].volume-192)<.0001);const p=fixture({parts:1});for(const o of p.objects){o.native.meshSource.vertices=o.native.meshSource.vertices.map(v=>v/10);o.positions=o.positions.map((v,i)=>{const origin=o.native.meshSource.build[12+i%3];return origin+(v-origin)/10;});}p.objects[1].scale=[100,100,100];assert.equal((await inspect(w,p)).result.unitSuggestion,'inches');});
test('native admission rejects forged identities, mesh indices, roles, matrices and cut IDs',async t=>{const w=await worker(t),original=prepareNativeImportInspection(inspectionProject([inspectionBox(1)])).request;for(const[change,pattern]of [[r=>r.sourceRevision='other',/identity/],[r=>r.objects.push(r.objects[0]),/Duplicate/],[r=>r.objects[0].parts[0].triangles[0][0]=-1,/index/],[r=>r.objects[0].parts[0].type='bogus',/role/],[r=>r.objects[0].instances[0][15]=0,/affine/],[r=>r.objects[0].cutId={id:'-1',checkSum:'1',connectorsCount:'0'},/cut identity/]]){const request=structuredClone(original);change(request);await assert.rejects(w.process(Buffer.from(JSON.stringify(request))),pattern);}});
test('native inspection adapter has a matching original-source build manifest and binary hash',async()=>{const manifest=JSON.parse(await readFile('native/build/arrange/build-manifest.json','utf8'));assert.equal(manifest.sourceManifest.commit,'8500fcdccaa10b5099ac20d252af3a7c560046f1');for(const name of ['native/arrange-worker/worker/native-import-inspection.cpp','native/arrange-worker/worker/native-import-inspection.hpp'])assert.equal(createHash('sha256').update(await readFile(name)).digest('hex'),manifest.adapterSources[name]);assert.equal(createHash('sha256').update(await readFile('native/build/arrange/orca-arrange-worker')).digest('hex'),manifest.binarySha256);});
