import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,readFile,writeFile,readdir,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{parseGcode}from'../../shared/gcode.js';
import{createPresetCatalog}from'../../server/presets.js';import{createCustomPresetCatalog}from'../../server/custom-presets.js';import{createNativeProjectService}from'../../server/native-projects.js';import{importNative3MF}from'../../shared/native-project.js';import{inspectSlicer,runSlicer}from'../../server/slicer.js';
test('native user diff and parent-relative reset survive restart and control actual installed slicing',{timeout:120000},async t=>{
 const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer';assert.equal((await inspectSlicer(binary)).version,'OrcaSlicer-2.4.2');
 const directory=await mkdtemp(path.join(tmpdir(),'orca-inherited-native-'));t.after(()=>rm(directory,{recursive:true,force:true}));const baseCatalog=await createPresetCatalog({binary}),catalog=await createCustomPresetCatalog({baseCatalog,dataDir:directory});t.after(()=>catalog.close());
 const ids=catalog.list().defaults,parent=catalog.getPreset(ids.processId,'process'),child=await catalog.importPreset({preset:{type:'process',name:'Native inherited fine process',inherits:parent.name,layer_height:'0.12'}});assert.equal(catalog.exportPreset(child.id).inherits,parent.name);
 const project=importNative3MF(await readFile(new URL('../fixtures/native-gui-cube-2.4.2.3mf',import.meta.url))),selection={...ids,processId:child.id,filamentIds:[ids.filamentId]};
 async function slice(current,label){const service=createNativeProjectService({catalog:current});try{const prepared=await service.prepare({project,selection}),work=path.join(directory,label);await mkdir(work);await mkdir(path.join(work,'config'));await mkdir(path.join(work,'out'));await writeFile(path.join(work,'model.3mf'),prepared.bytes);await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--datadir',path.join(work,'config'),'--outputdir',path.join(work,'out'),path.join(work,'model.3mf')],{cwd:work,timeoutMs:60000,signal:t.signal});const file=(await readdir(path.join(work,'out'))).find(name=>name.endsWith('.gcode'));assert.ok(file);return readFile(path.join(work,'out',file),'utf8');}finally{await service.close();}}
 const before=await slice(catalog,'fine');assert.match(before,/^; layer_height = 0\.12$/m);assert.ok(before.includes(child.name));
 const context=await catalog.sourceContext(child.id,'process',{selection});assert.equal(context.baseSettings.layer_height,parent.layer_height);await catalog.saveCustom({nativeEditor:true,selection,settings:{}},child.id);assert.equal(catalog.exportPreset(child.id).layer_height,undefined);assert.equal(catalog.exportPreset(child.id).inherits,parent.name);
 const reopened=await createCustomPresetCatalog({baseCatalog,dataDir:directory});t.after(()=>reopened.close());assert.equal(reopened.getCustom(child.id).preset.layer_height,parent.layer_height);const after=await slice(reopened,'parent-reset');assert.ok(after.includes(`; layer_height = ${parent.layer_height}`));assert.ok(after.includes(child.name));
 const count=value=>Number(value.match(/^; total layer number: (\d+)$/m)?.[1]);assert.ok(count(before)>count(after));for(const [label,code]of [['fine',before],['parent-reset',after]]){const parsed=parseGcode(code),layers=parsed.layers.filter(layer=>!layer.preamble);assert.equal(parsed.truncated,false);assert.equal(layers.length,count(code));assert.ok(layers.every(layer=>layer.extrusionSegments>0),`${label}: every native layer must deposit material`);assert.ok(parsed.metrics.extrusionMm>0);await mkdir('test-results/native-inheritance',{recursive:true});await writeFile(`test-results/native-inheritance/${label}.gcode`,code);}t.diagnostic(`Imported child: ${count(before)} layers; parent reset after restart: ${count(after)} layers. No native GUI export or printer connection.`);
});
