import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{createHash}from'node:crypto';import path from'node:path';
import{createNativeGcodeWorker}from'../../server/native-gcode-worker.js';import{parseGcode}from'../../shared/gcode.js';import{adaptNativePreview,nativePreviewRange,nativeVertexColor,nativeScalarModes,nativeScalarRangeKey}from'../../shared/native-preview-adapter.js';
const binary=process.env.ORCA_GCODE_WORKER_BIN||path.resolve(process.env.ORCA_NATIVE_CACHE_DIR||'.native-cache','gcode-build','orca-gcode-worker'),fixture=JSON.parse(await readFile(new URL('../fixtures/native-scalar-reference.json',import.meta.url)));
async function worker(t){const w=createNativeGcodeWorker({binary,resourcesDir:process.env.ORCA_RESOURCES_DIR||'/Applications/OrcaSlicer.app/Contents/Resources'});await w.identity();t.after(()=>w.shutdown());return w;}
test('real GUI G-code scalar ranges and every vertex color match original C++ for all seven modes and four visibility combinations',async t=>{
 const w=await worker(t),bytes=await readFile(new URL('../fixtures/native-gui-shrink98-2.4.2.gcode',import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),fixture.nativeGui.sourceSha256);const data=await w.process(bytes),parsed=adaptNativePreview(parseGcode(bytes.toString(),{includeSource:true}),data);assert.equal(data.vertexCount,fixture.nativeGui.vertexCount);assert.equal(data.scalarRangesVersion,1);let compared=0;
 for(const travels of[false,true])for(const wipes of[false,true]){const options={travels,wipes},key=nativeScalarRangeKey(options),expected=fixture.nativeGui.expected[key];assert.deepEqual(data.scalarRanges[key],expected.ranges);for(const mode of Object.keys(nativeScalarModes)){const range=nativePreviewRange(parsed,mode,{options}),rgb=Buffer.alloc(data.vertexCount*3);for(let i=0;i<data.vertexCount;i++){const hex=nativeVertexColor(parsed,i,mode,range);rgb.set(hex.slice(1).match(/../g).map(v=>parseInt(v,16)),i*3);}assert.equal(createHash('sha256').update(rgb).digest('hex'),expected.colorSha256[mode],`${key}/${mode} native RGB stream`);compared+=data.vertexCount;}}
 assert.equal(compared,812588);t.diagnostic(`${compared} original native vertex colors across28 mode/visibility streams match byte-for-byte.`);
});
test('native PA ranges remain unavailable without an explicit PA command and begin at the determined value when one appears',async t=>{
 const w=await worker(t),prefix='G90\nM83\nG1 Z0.2 F600\n; FEATURE: Outer wall\n; LAYER_HEIGHT: 0.2\n; LINE_WIDTH: 0.4\nG1 X10 E1 F1200\nG1 Y10 E1\n',unknown=await w.process(Buffer.from(prefix));for(const value of Object.values(unknown.scalarRanges)){assert.deepEqual([value.pressureAdvance.min,value.pressureAdvance.max,value.pressureAdvance.count,value.pressureAdvance.values],[null,null,0,[]]);}assert.ok(unknown.vertices.every(v=>v[18]===null));const known=await w.process(Buffer.from(prefix+'M900 K0.05\nG1 X20 E1\n'));for(const value of Object.values(known.scalarRanges)){assert.equal(value.pressureAdvance.min,Math.fround(.05));assert.equal(value.pressureAdvance.max,Math.fround(.05));}assert.ok(known.vertices.filter(v=>v[12]<9).every(v=>v[18]===null));
});
