import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,writeFile,readFile,rm,readdir,mkdir}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';import express from'express';
import{createPresetCatalog}from'../../server/presets.js';import{createCustomPresetCatalog}from'../../server/custom-presets.js';import{createCalibrationSessions}from'../../server/calibration-sessions.js';import{runSlicer}from'../../server/slicer.js';import{applyCalibrationGcode}from'../../shared/calibration.js';import{normalizePAPatternCommands}from'../../shared/pa-pattern-gcode.js';import{importNative3MF}from'../../shared/native-project.js';import{parseGcode}from'../../shared/gcode.js';import{createNativeProjectService}from'../../server/native-projects.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer',resourcesDir=process.env.ORCA_RESOURCES_DIR||'/Applications/OrcaSlicer.app/Contents/Resources';let base;test.before(async()=>base=await createPresetCatalog({binary}));
const n=(v,p=5)=>Number(v.toFixed(p));
function fixtureMotion(events,p){const dx=p.startX-50,dy=p.startY-50;return events.flatMap(e=>{switch(e[0]){case'speed':return[];case'pa':return[{command:`M900 K${Number(e[1].toPrecision(4))}`}];case'acceleration':return[{command:`M204 P${e[1]}`}];case'resetE':return[{command:'G92 E0'}];case'xy':return[{motion:{X:n(e[1]+dx,3),Y:n(e[2]+dy,3)},feed:n(e[3],3)}];case'z':return[{motion:{Z:n(e[1],3)},feed:n(e[2],3)}];case'extrude':return[{motion:{X:n(e[1]+dx,3),Y:n(e[2]+dy,3),E:n(e[4])},feed:n(e[6],3)}];default:return[{motion:{E:n(e[1])},feed:n(e[3],3)}];}});}
for(const configuration of[{name:'single-relative',relative:true,end:.01,speeds:[120],accelerations:[4000],fixture:'three-relative'},{name:'single-absolute',relative:false,end:.08,speeds:[80],accelerations:[1000],fixture:'full-absolute'},{name:'batch-two-by-two',relative:true,end:.01,speeds:[80,120],accelerations:[1000,2000]}])test(`real native PA pattern 3MF session slices exact four-layer generated commands (${configuration.name})`,{timeout:120000},async t=>{
 const directory=await mkdtemp(path.join(tmpdir(),'orca-pa-pattern-'));t.after(()=>rm(directory,{recursive:true,force:true}));const catalog=await createCustomPresetCatalog({baseCatalog:base,dataDir:directory}),ids={...catalog.list().defaults};
 if(!configuration.relative){const original=catalog.resolveSelection(ids).printer,custom=await catalog.saveCustom({type:'machine',name:'Absolute pattern machine',baseId:ids.printerId,settings:{use_relative_e_distances:false,before_layer_change_gcode:original.before_layer_change_gcode.replace(/^G92 E.*$/gm,'')}});ids.printerId=custom.id;}
 const sessions=createCalibrationSessions({binary,resourcesDir,catalog}),app=express();app.use('/api/calibrations',sessions.router);app.use((error,req,res,next)=>res.status(error.status||500).json({error:error.message}));const server=app.listen(0,'127.0.0.1');await new Promise((resolve,reject)=>{server.once('listening',resolve);server.once('error',reject)});t.after(async()=>{await sessions.shutdown();await new Promise(resolve=>server.close(resolve))});const post=(route,body)=>fetch(`http://127.0.0.1:${server.address().port}/api/calibrations/${route}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
 const params={...ids,mode:'pressure-advance-pattern',start:0,end:configuration.end,step:.005,speeds:configuration.speeds,accelerations:configuration.accelerations},response=await post('prepare',params),prepared=await response.json();assert.equal(response.status,200,JSON.stringify(prepared));assert.equal(prepared.plan.inputFormat,'3mf');assert.equal(prepared.objects.length,configuration.speeds.length*configuration.accelerations.length);const request={calibration:prepared.calibration,ids,objects:prepared.objects},valid=await sessions.validateProject(request);assert.equal(valid.project.plates[0].layerEvents.items.length,4);const imported=importNative3MF(valid.bytes);assert.equal(imported.objects.length,prepared.objects.length);assert.equal(imported.plates[0].layerEvents.items.length,4);
 const exportResponse=await post('project',request);assert.equal(exportResponse.status,200);assert.equal(exportResponse.headers.get('cache-control'),'no-store');const exported=new Uint8Array(await exportResponse.arrayBuffer());assert.deepEqual(exported,valid.bytes);assert.equal(importNative3MF(exported).plates[0].layerEvents.items.length,4);const reimported=await createNativeProjectService({catalog}).importArchive(exported);const reprepared=await createNativeProjectService({catalog}).prepare({project:reimported.project,useEmbeddedSettings:true});assert.equal(importNative3MF(reprepared.bytes).plates[0].layerEvents.items.length,4);assert.equal((await post('project',{...request,extra:'untrusted'})).status,400);assert.equal((await post('project',{...request,calibration:{...prepared.calibration,token:'f'.repeat(64)}})).status,409);assert.equal((await post('project',{...request,calibration:{...prepared.calibration,speeds:[99]}})).status,409);
 await assert.rejects(sessions.validateProject({...request,calibration:{...prepared.calibration,speeds:[90]}}),/parameters changed/);await assert.rejects(sessions.validateProject({...request,ids:{...ids,filamentId:'changed'}}),/preset selection changed/);const changed=structuredClone(prepared.objects);changed[0].positions[0]+=.1;await assert.rejects(sessions.validateProject({...request,objects:changed}),/geometry or object settings/);
 const input=path.join(directory,'patterns.3mf'),outdir=path.join(directory,'output');await writeFile(input,reprepared.bytes);await mkdir(outdir);await mkdir(path.join(directory,'config'));await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--outputdir',outdir,'--datadir',path.join(directory,'config'),input],{cwd:directory,timeoutMs:60000,signal:t.signal});const files=(await readdir(outdir)).filter(f=>f.endsWith('.gcode'));assert.equal(files.length,1);const raw=await readFile(path.join(outdir,files[0]),'utf8');assert.match(raw,/generated by OrcaSlicer 2\.4\.2/);const output=applyCalibrationGcode(raw,valid.plan);assert.equal(output.summary.patternCount,prepared.objects.length);assert.equal(output.summary.layers,4);assert.match(output.gcode,/M555 X25 Y21 W200 H164/);assert.match(output.gcode,/; estimated printing time/);
 const blocks=[...output.gcode.matchAll(/^; ORCA_WEB_PA_PATTERN_START (\d+) Z([\d.]+)\r?\n([\s\S]*?)^; ORCA_WEB_PA_PATTERN_END \1 Z\2\r?$/gm)];assert.equal(blocks.length,prepared.objects.length*4);if(configuration.fixture){const reference=JSON.parse(await readFile(new URL(`../fixtures/pa-pattern/source-${configuration.fixture}.json`,import.meta.url)));assert.deepEqual(blocks.flatMap(b=>normalizePAPatternCommands(b[3])),fixtureMotion(reference,valid.plan.paPatterns[0]));}
 const preview=parseGcode(output.gcode);assert.equal(preview.layers.filter(l=>!l.preamble).length,4);assert.ok(preview.segments.some(s=>s.kind==='extrusion'&&s.feature==='Custom'));assert.ok(preview.segments.some(s=>s.kind==='extrusion'&&s.feature==='Outer wall'));
 const savedResponse=await post('result',{token:prepared.calibration.token,value:.005,name:'Measured pattern PA'}),saved=await savedResponse.json();assert.equal(savedResponse.status,201,JSON.stringify(saved));assert.equal(saved.result.settings.pressure_advance[0],'0.005');assert.deepEqual(saved.preset.compatiblePrinterIds,[ids.printerId]);t.diagnostic(`${prepared.objects.length} source handle cubes; four native layers; ${output.summary.sourceGeneratedMoves} generated moves; fixed PA result saved. Source fixtures are independent C++ geometry evidence, not native GUI export or physical measurements.`);
});
