import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,readFile,readdir,rm,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{inspectSlicer,runSlicer}from'../../server/slicer.js';import{createNativeProjectService}from'../../server/native-projects.js';import{importNative3MF,nativeSettingsFromSelection}from'../../shared/native-project.js';import{layerProfileContext}from'../../shared/variable-layers.js';import{generateObjectLayers}from'../../shared/layer-height-texture.js';import{parseGcode}from'../../shared/gcode.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer';
async function setup(t){const engine=await inspectSlicer(binary);assert.equal(engine.available,true,engine.error);assert.match(engine.version,/^OrcaSlicer-2\.4\.2\b/);const root=await mkdtemp(path.join(tmpdir(),'orca-shrinkage-'));t.after(()=>process.env.ORCA_SHRINK_DEBUG?t.diagnostic(root):rm(root,{recursive:true,force:true}));const base=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));base.objects[0].position=[60,70,0];const catalog=fixtureCatalog(base),selection=catalog.resolveSelection({printerId:'printer',processId:'process',filamentId:'red'}),second=catalog.resolveSelection({printerId:'printer',processId:'process',filamentId:'blue'}).filament;
 base.nativeSettings={...base.nativeSettings,...nativeSettingsFromSelection({...selection,filaments:[selection.filament,second]}),layer_height:'.2',initial_layer_print_height:'.2',brim_type:'no_brim',skirt_loops:'0',single_extruder_multi_material:'1',enable_prime_tower:'0',filament_shrink:['98','97'],filament_shrinkage_compensation_z:['98','98'],precise_z_height:'0'};const service=createNativeProjectService({catalog});
 return{base,async slice(label,project){const prepared=await service.prepare({project,useEmbeddedSettings:true}),dir=path.join(root,label);await mkdir(dir);await mkdir(path.join(dir,'config'));await mkdir(path.join(dir,'output'));await writeFile(path.join(dir,'model.3mf'),prepared.bytes);await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--datadir',path.join(dir,'config'),'--outputdir',path.join(dir,'output'),path.join(dir,'model.3mf')],{cwd:dir,timeoutMs:60000,signal:t.signal});const files=(await readdir(path.join(dir,'output'))).filter(name=>name.endsWith('.gcode'));assert.equal(files.length,1);const code=await readFile(path.join(dir,'output',files[0]),'utf8'),zs=[...code.matchAll(/^;Z:([\d.]+)/gm)].map(match=>Number(match[1]));return{code,zs,settings:prepared.settings,project:prepared.project,parsed:parseGcode(code)};}};
}
const motions=code=>code.split(/\r?\n/).map(line=>line.split(';',1)[0].trim()).filter(line=>/^G[0123]\b/.test(line));
function confirmLayers(result){const context=layerProfileContext(result.project.objects,result.project.objects[0].id,result.settings,{filamentCount:2}),layers=generateObjectLayers([],context).filter((_,index)=>index%2===1);assert.equal(result.zs.length,layers.length);result.zs.forEach((z,index)=>assert.ok(Math.abs(z-layers[index])<.0001,`Z layer ${index}: ${z} vs ${layers[index]}`));return context;}
test('native fresh-load CLI shrinkage discrepancy stays explicit instead of claiming source texture matches output',{timeout:120000},async t=>{
 const{base,slice}=await setup(t),actual=await slice('unused-mismatch',base),same=structuredClone(base);same.nativeSettings.filament_shrink=['98','98'];const reference=await slice('all-same',same);assert.deepEqual(motions(actual.code),motions(reference.code));const context=layerProfileContext(actual.project.objects,actual.project.objects[0].id,actual.settings,{filamentCount:2});assert.deepEqual(context.usedFilamentSlots,[1]);assert.equal(context.shrinkageCompensationZ,100/98);assert.equal(generateObjectLayers([],context).length/2,102);assert.equal(actual.zs.length,100);assert.equal(actual.zs.at(-1),20);assert.match(actual.code,/filament_shrinkage_compensation_z = 98%,98%/);assert.ok(context.warnings.some(warning=>warning.includes('known shrinkage discrepancy')));t.diagnostic(`Observed engine discrepancy: source-derived texture has 102 layers, fresh-load CLI outputs 100 through Z20. ${motions(actual.code).length} native motions are identical when the unused slot is changed from XY97% to XY98%. This is diagnostic evidence, not positive active-shrinkage parity.`);
});
for(const kind of ['part','paint','height-range','support'])test(`native ${kind} mixed-XY/equal-Z case matches neutral output and the source-disabled preview`,{timeout:120000},async t=>{
 const{base,slice}=await setup(t),object=base.objects[0];
 if(kind==='part'){const second=structuredClone(object);delete second.native.instanceFamily;second.id='second';second.name='Second material';second.native.groupId='second';second.filamentSlot=2;second.position[0]+=30;base.objects.push(second);}
 if(kind==='paint')object.painting={version:1,color:{4:'8'}};
 if(kind==='height-range')object.native.layerConfigRanges=[{minZ:4,maxZ:8,settings:{layer_height:'.2',extruder:'2'}}];
 if(kind==='support')Object.assign(base.nativeSettings,{enable_support:'1',support_filament:'2',support_interface_filament:'1',support_type:'normal(auto)'});
 const actual=await slice('mixed',base),neutral=structuredClone(base);neutral.nativeSettings.filament_shrink=['100','100'];neutral.nativeSettings.filament_shrinkage_compensation_z=['100','100'];const reference=await slice('neutral-reference',neutral);assert.deepEqual(motions(actual.code),motions(reference.code));const context=confirmLayers(actual);assert.deepEqual(context.usedFilamentSlots,[1,2]);assert.equal(context.shrinkageCompensationZ,1);assert.equal(actual.zs.length,100);t.diagnostic(`${kind}: 100 native layers and ${motions(actual.code).length} motions equal neutral shrinkage reference; preview reports mixed-material compensation disabled.`);
});
