import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createApp, defaultBinary } from '../../server/app.js';

// This exercises the installed native engine, not a command-line adapter.
test('native preservePosition keeps baked STL XY coordinates and uses native bed placement for Z', { timeout: 120000 }, async t => {
  const dataDir = await mkdtemp(path.join(tmpdir(), 'orca-native-position-'));
  const app = await createApp({ dataDir, binary: process.env.ORCA_SLICER_BIN || defaultBinary });
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(async () => { await app.locals.shutdown(); await new Promise(resolve => server.close(resolve)); await rm(dataDir, { recursive: true, force: true }); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const healthResponse = await fetch(`${base}/api/health`), health = await healthResponse.json();
  assert.equal(healthResponse.status, 200, JSON.stringify(health));
  assert.match(health.engine.version, /OrcaSlicer-\d+\.\d+/);
  assert.doesNotMatch(health.engine.version, /fixture|fake|adapter/i);
  const catalog = await (await fetch(`${base}/api/presets`)).json();
  const cube = (await readFile('tests/fixtures/cube.stl', 'utf8')).replace(/vertex ([^ ]+) ([^ ]+) ([^\n]+)/g,
    (_, x, y, z) => `vertex ${Number(x) + 40} ${Number(y) + 60} ${Number(z) + 5}`);
  const body = new FormData();
  for (const [key, value] of Object.entries(catalog.defaults)) body.set(key, value);
  body.set('settings', JSON.stringify({ brim_type: 'no_brim', enable_support: false }));
  body.set('preservePosition', 'true');
  body.set('model', new Blob([cube]), 'translated.stl');
  const response = await fetch(`${base}/api/jobs`, { method: 'POST', body }), created = await response.json();
  assert.equal(response.status, 202, created.error);
  assert.equal(created.preservePosition, true);
  let job;
  for (let attempt = 0; attempt < 400; attempt++) {
    job = await (await fetch(`${base}/api/jobs/${created.id}`)).json();
    if (['ready', 'failed', 'cancelled'].includes(job.status)) break;
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  assert.equal(job.status, 'ready', job.error);
  const output = await fetch(`${base}/api/jobs/${job.id}/download`);
  assert.equal(output.status, 200);
  const gcode = await output.text();
  assert.match(gcode, /generated by OrcaSlicer/i);
  const points = [];
  let printing = false, x, y;
  for (const line of gcode.split('\n')) {
    if (line.startsWith('; printing object ')) printing = true;
    if (line.startsWith('; stop printing object ')) printing = false;
    if (!/^G[01]\s/.test(line)) continue;
    const nextX = line.match(/\bX([-+\d.]+)/), nextY = line.match(/\bY([-+\d.]+)/);
    if (nextX) x = Number(nextX[1]);
    if (nextY) y = Number(nextY[1]);
    const extrusion = Number(line.match(/\bE([-+\d.]+)/)?.[1] || 0);
    if (printing && extrusion > 0 && (nextX || nextY) && Number.isFinite(x) && Number.isFinite(y)) points.push([x, y]);
  }
  assert.ok(points.length > 100, 'Expected genuine object extrusion moves');
  const minX = Math.min(...points.map(point => point[0])), maxX = Math.max(...points.map(point => point[0]));
  const minY = Math.min(...points.map(point => point[1])), maxY = Math.max(...points.map(point => point[1]));
  assert.ok(minX >= 39.9 && maxX <= 60.1 && maxX - minX > 19, `Unexpected X extent ${minX}..${maxX}`);
  assert.ok(minY >= 59.9 && maxY <= 80.1 && maxY - minY > 19, `Unexpected Y extent ${minY}..${maxY}`);
  // Orca 2.4.2 still places each imported STL on the bed, even with arrange/orient
  // disabled. Clients must snap exported objects to the bed rather than promise
  // preservation of a floating Z coordinate.
  assert.match(gcode, /; max_z_height: 20\.00/);
});
