import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,readFile,writeFile,readdir,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{inspectSlicer,runSlicer}from'../../server/slicer.js';import{createPresetCatalog}from'../../server/presets.js';import{createNativeProjectService}from'../../server/native-projects.js';import{importNative3MF}from'../../shared/native-project.js';import{makeNativeAcceptanceProject}from'../fixtures/native-project.js';import{parseGcode}from'../../shared/gcode.js';import{updatePrimeTower}from'../../shared/prime-tower.js';import{nativeProjectRequest}from'../../shared/native-project-client.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer';
test('prime tower position changes native deposited tower paths by the requested displacement without moving model extrusion',{timeout:120000},async t=>{
 const engine=await inspectSlicer(binary);assert.match(engine.version,/^OrcaSlicer-2\.4\.2\b/);const directory=await mkdtemp(path.join(tmpdir(),'orca-prime-'));t.after(()=>rm(directory,{recursive:true,force:true}));const catalog=await createPresetCatalog({binary}),service=createNativeProjectService({catalog}),ids=catalog.list().defaults;
 let project=makeNativeAcceptanceProject(importNative3MF(await readFile('tests/fixtures/orca-2.4.2-cube.3mf')));project={...project,ids,filamentIds:[ids.filamentId,ids.filamentId],useEmbeddedSettings:false,overrides:{layer_height:'0.2',brim_type:'no_brim'},objects:project.objects.filter(object=>['base','blue'].includes(object.id))};
 const outputs=[];
 for(const[x,index]of [[100,0],[130,1]]){
  const changed=updatePrimeTower(project,{enabled:true,x,y:100,width:25,rotation:0}),request=nativeProjectRequest(changed);request.overrides.machine={single_extruder_multi_material:true};const prepared=await service.prepare(request),root=path.join(directory,String(index));await mkdir(root);await mkdir(path.join(root,'config'));await mkdir(path.join(root,'output'));await writeFile(path.join(root,'model.3mf'),prepared.bytes);
  await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--datadir',path.join(root,'config'),'--outputdir',path.join(root,'output'),path.join(root,'model.3mf')],{cwd:root,timeoutMs:60000,signal:t.signal});const filename=(await readdir(path.join(root,'output'))).find(name=>name.endsWith('.gcode'));assert.ok(filename);const code=await readFile(path.join(root,'output',filename),'utf8'),parsed=parseGcode(code);const tower=parsed.segments.filter(segment=>segment.kind==='extrusion'&&/prime|wipe.*tower/i.test(segment.feature));assert.ok(tower.length>20,JSON.stringify(parsed.features));outputs.push({tower,model:parsed.segments.filter(segment=>segment.kind==='extrusion'&&/outer wall/i.test(segment.feature))});
 }
 assert.equal(outputs[0].tower.length,outputs[1].tower.length);for(let i=0;i<outputs[0].tower.length;i++){for(const endpoint of ['start','end']){assert.ok(Math.abs(outputs[1].tower[i][endpoint][0]-outputs[0].tower[i][endpoint][0]-30)<.002);assert.ok(Math.abs(outputs[1].tower[i][endpoint][1]-outputs[0].tower[i][endpoint][1])<.002);}}
 assert.deepEqual(outputs[0].model.map(segment=>segment.end),outputs[1].model.map(segment=>segment.end));t.diagnostic(`${outputs[0].tower.length} native prime-tower extrusion segments moved exactly 30 mm in X; model walls did not move.`);
});
