import{createHash}from'node:crypto';
import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,writeFile,readFile,mkdir,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{createPresetCatalog}from'../../server/presets.js';import{runSlicer,inspectSlicer}from'../../server/slicer.js';import{importPrusaArchive,defaultPrusaWorker}from'../../server/native-prusa.js';import{importNative3MF,exportNative3MF}from'../../shared/native-project.js';import{serializeProject,parseProject}from'../../shared/project.js';import{prusaFixture,expectedPrusaObjects}from'../fixtures/prusa-project.js';import{capturePrusaSource}from'../../shared/prusa-provenance.js';import{extractBoundedZip}from'../../shared/import-limits.js';import{parseGcode}from'../../shared/gcode.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer',worker=defaultPrusaWorker;
const motions=code=>code.split(/\r?\n/).map(line=>line.split(';',1)[0].trim()).filter(line=>/^G[0123]\b/.test(line));
test('pinned GUI Prusa importer preserves material/negative parts and all painting channels with exact native slice motions',{timeout:120000},async t=>{
 const directory=await mkdtemp(path.join(tmpdir(),'orca-prusa-native-'));if(!process.env.ORCA_KEEP_TEST_OUTPUT)t.after(()=>rm(directory,{recursive:true,force:true}));else t.diagnostic(directory);const manifest=JSON.parse(await readFile(path.join(path.dirname(worker),'build-manifest.json'),'utf8'));assert.equal(manifest.binarySha256,createHash('sha256').update(await readFile(worker)).digest('hex'));assert.equal(manifest.sourceManifest.commit,'8500fcdccaa10b5099ac20d252af3a7c560046f1');assert.equal((await inspectSlicer(binary)).version,'OrcaSlicer-2.4.2');const catalog=await createPresetCatalog({binary}),selection=catalog.resolveSelection({...catalog.list().defaults,overrides:{layer_height:.2,initial_layer_print_height:.2,outer_wall_speed:70,enable_prime_tower:false,sparse_infill_pattern:'rectilinear'}});selection.printer={...selection.printer,single_extruder_multi_material:'1'};
 const result=await importPrusaArchive(prusaFixture(),{selection,workerPath:worker,filename:'Native Prusa source.3mf'});assert.equal(result.project.objects.length,3);assert.deepEqual(result.project.objects.map(o=>o.filamentSlot),[1,1,2]);assert.deepEqual(result.project.objects.map(o=>o.native.partType),['normal_part','negative_part','normal_part']);assert.equal(result.nativeImport.addedFilamentSlots,1);assert.equal(result.project.nativeSettings.filament_colour[1],'#00C1AE');assert.equal(result.project.nativeSettings.layer_height,'0.2');assert.equal(result.project.objects[0].native.objectSettings.outer_wall_speed,undefined);assert.deepEqual(result.project.objects[0].painting,{version:1,winding:1,supports:{4:'4'},seam:{4:'8'},color:{4:'8'},fuzzy:{4:'4'}});
 assert.equal(result.project.nativeLegacySource.report.filteredModelSettings.length,4);assert.equal(result.project.nativeLegacySource.report.ignoredCarriers.length,2);assert.deepEqual(parseProject(serializeProject(result.project)).nativeLegacySource,result.project.nativeLegacySource);assert.deepEqual(capturePrusaSource(extractBoundedZip(result.bytes)),result.project.nativeLegacySource);const roundtrip=importNative3MF(result.bytes);assert.deepEqual(roundtrip.nativeLegacySource,result.project.nativeLegacySource);assert.deepEqual(roundtrip.objects.map(o=>o.native.partType),['normal_part','negative_part','normal_part']);assert.deepEqual(roundtrip.objects[0].painting,result.project.objects[0].painting);
 const expected={...result.project,objects:expectedPrusaObjects(),selectedId:'expected-0',selectedIds:['expected-0']};async function slice(bytes,label){const dir=path.join(directory,label);await mkdir(dir);await mkdir(path.join(dir,'config'));const input=path.join(dir,'model.3mf');await writeFile(input,bytes);await runSlicer(binary,['--slice','0','--orient','0','--outputdir',dir,'--datadir',path.join(dir,'config'),input],{cwd:dir,timeoutMs:60000});return readFile(path.join(dir,'plate_1.gcode'),'utf8');}
 const imported=await slice(result.bytes,'imported'),reference=await slice(exportNative3MF(expected),'reference');assert.ok(motions(imported).length>5000);assert.deepEqual(motions(imported),motions(reference));const parsed=parseGcode(imported),tools=new Set(parsed.segments.filter(s=>s.kind==='extrusion'&&/wall/i.test(s.feature)).map(s=>s.tool));assert.deepEqual([...tools].sort(),[0,1]);assert.equal([...imported.matchAll(/^;Z:/gm)].length,100);t.diagnostic(`${motions(imported).length} identical native motion commands;100layers;tools0,1;3separateparts.`);
});

import {createApp} from '../../server/app.js';
test('raw Prusa API jobs retain both materials and negative geometry at unity and98%, and project import preserves inactive carriers',{timeout:180000},async t=>{
 const dataDir=await mkdtemp(path.join(tmpdir(),'orca-prusa-api-'));
 const app=await createApp({binary,dataDir}),server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{await app.locals.shutdown();await new Promise(r=>server.close(r));await rm(dataDir,{recursive:true,force:true});});
 const base=`http://127.0.0.1:${server.address().port}`,{defaults}=await(await fetch(`${base}/api/presets`)).json();
 for(const shrink of[100,98]){
  const form=new FormData();for(const[key,value]of Object.entries(defaults))form.set(key,value);form.set('model',new Blob([prusaFixture()]),'Prusa assembly.3mf');form.set('settings',JSON.stringify({layer_height:.2,initial_layer_print_height:.2,outer_wall_speed:70,enable_prime_tower:false,sparse_infill_pattern:'rectilinear'}));form.set('printerSettings',JSON.stringify({single_extruder_multi_material:true}));form.set('filamentSettings',JSON.stringify({filament_shrink:[shrink],filament_shrinkage_compensation_z:[shrink]}));
  const response=await fetch(`${base}/api/jobs`,{method:'POST',body:form}),created=await response.json();assert.equal(response.status,202,JSON.stringify(created));await app.locals.waitForIdle();const job=await(await fetch(`${base}/api/jobs/${created.id}`)).json();assert.equal(job.status,'ready',job.error);assert.equal(job.nativeImport.format,'prusa-3mf');assert.equal(job.nativeImport.addedFilamentSlots,1);assert.equal(job.nativeImport.warnings.length,2);
  const code=await(await fetch(`${base}/api/jobs/${created.id}/download`)).text(),zs=[...code.matchAll(/^;Z:([\d.]+)/gm)].map(m=>Number(m[1]));assert.equal(zs.length,shrink===98?102:100);assert.equal(zs.at(-1),shrink===98?20.4:20);assert.equal(Boolean(job.shrinkageInitialization),shrink===98);
  const segments=parseGcode(code).segments.filter(s=>s.kind==='extrusion'&&/wall/i.test(s.feature)&&s.end[2]>.3);assert.deepEqual([...new Set(segments.map(s=>s.tool))].sort(),[0,1]);assert.ok(segments.length>1000);
  for(const segment of segments)for(const ratio of[.25,.5,.75]){const x=segment.start[0]+(segment.end[0]-segment.start[0])*ratio,y=segment.start[1]+(segment.end[1]-segment.start[1])*ratio;assert.ok(!(x>98&&x<102&&y>18&&y<22),'Native negative volume remains empty');}
 }
 const form=new FormData();form.set('model',new Blob([prusaFixture()]),'Prusa project.3mf');form.set('selection',JSON.stringify({printerId:defaults.printerId,processId:defaults.processId,filamentIds:[defaults.filamentId]}));form.set('overrides',JSON.stringify({process:{layer_height:.16},machine:{single_extruder_multi_material:true}}));
 const response=await fetch(`${base}/api/projects/import`,{method:'POST',body:form}),imported=await response.json();assert.equal(response.status,200,JSON.stringify(imported));assert.equal(imported.project.nativeSettings.layer_height,'0.16');assert.equal(imported.project.objects.length,3);assert.equal(imported.selection.filamentIds.length,2);assert.ok(imported.selection.filamentIds.every(Boolean));assert.equal(imported.project.nativeLegacySource.entries.length,3);assert.equal(imported.warnings.length,2);
 const exported=await fetch(`${base}/api/projects/export`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project:imported.project,useEmbeddedSettings:true})});assert.equal(exported.status,200);const roundtrip=importNative3MF(new Uint8Array(await exported.arrayBuffer()));assert.deepEqual(roundtrip.nativeLegacySource,imported.project.nativeLegacySource);assert.deepEqual(roundtrip.objects.map(o=>o.filamentSlot),[1,1,2]);
 const embedded={...imported.project.nativeSettings,layer_height:'0.18',filament_shrink:['99%','98%'],filament_shrinkage_compensation_z:['97%','96%'],flush_volumes_matrix:['0','230','170','0'],flush_volumes_vector:['120','80','90','110']};
 const embeddedForm=new FormData();embeddedForm.set('model',new Blob([prusaFixture()]),'Current embedded context.3mf');embeddedForm.set('nativeSettings',JSON.stringify(embedded));
 const embeddedResponse=await fetch(`${base}/api/projects/import`,{method:'POST',body:embeddedForm}),embeddedProject=await embeddedResponse.json();assert.equal(embeddedResponse.status,200,JSON.stringify(embeddedProject));assert.equal(embeddedProject.project.nativeSettings.layer_height,'0.18');assert.deepEqual(embeddedProject.project.nativeSettings.filament_shrink,['99%','98%']);assert.deepEqual(embeddedProject.project.nativeSettings.filament_shrinkage_compensation_z,['97%','96%']);assert.deepEqual(embeddedProject.project.nativeSettings.flush_volumes_matrix,['0','230','170','0']);
 embeddedForm.set('selection',JSON.stringify(defaults));const mixed=await fetch(`${base}/api/projects/import`,{method:'POST',body:embeddedForm});assert.equal(mixed.status,400);assert.match((await mixed.json()).error,/Choose embedded settings or catalog/);
 t.diagnostic('Raw100%:100layers;raw98%:102layers;both tools and negative volume retained;project source bytes and full embedded vectors roundtrip.');
});
