import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,readFile,writeFile,readdir,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{inspectSlicer,runSlicer}from'../../server/slicer.js';import{createNativeProjectService}from'../../server/native-projects.js';import{importNative3MF}from'../../shared/native-project.js';import{addFilamentSlot}from'../../shared/filament-slots.js';import{normalizePurgeSettings}from'../../shared/purge-volumes.js';import{extendPrusaFilaments}from'../../shared/prusa-context.js';import{dropToBed,meshBounds}from'../../shared/geometry.js';import{updatePlatePrintSequence}from'../../shared/filament-sequence.js';import{parseGcode}from'../../shared/gcode.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer';
async function context(t){assert.match((await inspectSlicer(binary)).version,/^OrcaSlicer-2\.4\.2\b/);const root=await mkdtemp(path.join(tmpdir(),'orca-native-purge-'));t.after(()=>rm(root,{recursive:true,force:true}));let project=importNative3MF(await readFile(new URL('../fixtures/native-gui-cube-2.4.2.3mf',import.meta.url)));project.useEmbeddedSettings=true;while(project.nativeSettings.filament_settings_id.length<4)project=addFilamentSlot(project);
 // Explicit test printer derived from a complete native GUI configuration. It is
 // not presented as a saved J1/XL printer fixture. Physical identities match
 // PrintConfig get_extruder_id and PresetBundle full-config indexing.
 Object.assign(project.nativeSettings,{nozzle_diameter:['.4','.4'],physical_extruder_map:['0','1'],printer_extruder_id:['1','2'],printer_extruder_variant:['Direct Drive Standard','Direct Drive Standard'],print_extruder_id:['1','2'],print_extruder_variant:['Direct Drive Standard','Direct Drive Standard'],nozzle_volume_type:['Standard','Standard'],extruder_offset:['0x0','0x0'],filament_map_mode:'Manual',filament_map:['1','1','2','2'],layer_height:'.2',initial_layer_print_height:'.2',skirt_loops:'0',brim_type:'no_brim',enable_prime_tower:'0',change_filament_gcode:';PURGE from=[previous_extruder] to=[next_extruder] hotend=[next_hotend] length=[flush_length]\nT[next_extruder]'});
 Object.assign(project.nativeSettings,normalizePurgeSettings({...project.nativeSettings,flush_volumes_matrix:Array.from({length:32},(_,i)=>String(Math.floor(i/4)%4===i%4?0:i<16?100:500)),flush_multiplier:['1','1']},4));
 const original=project.objects[0],sourceBounds=meshBounds({...original,position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]});original.positions=original.positions.map((value,index)=>value-sourceBounds.min[index%3]);project.objects=Array.from({length:4},(_,i)=>dropToBed({...structuredClone(original),id:`part-${i}`,name:`Material ${i+1}`,position:[50+i*25,70,0],scale:[.5,.5,.03],filamentSlot:i+1,native:{groupId:`group-${i}`,objectName:`Material ${i+1}`,objectSettings:{extruder:String(i+1)},partSettings:{},partType:'normal_part'}}));
 project.plates=project.plates.map(plate=>updatePlatePrintSequence({...plate,native:{metadata:{filament_map_mode:'Manual',filament_map:'1 1 2 2'}}},{firstLayer:[1,2,3,4],ranges:[{start:2,end:999,order:[1,2,3,4]}]},4));
 const service=createNativeProjectService({catalog:fixtureCatalog(project)});
 return{project,async slice(name,changed){const folder=path.join(root,name);await mkdir(folder);await mkdir(path.join(folder,'config'));await mkdir(path.join(folder,'output'));const prepared=await service.prepare({project:changed,useEmbeddedSettings:true});await writeFile(path.join(folder,'model.3mf'),prepared.bytes);await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--export-3mf','native.3mf','--datadir',path.join(folder,'config'),'--outputdir',path.join(folder,'output'),path.join(folder,'model.3mf')],{cwd:folder,timeoutMs:60000,signal:t.signal});const code=await readFile(path.join(folder,'output',(await readdir(path.join(folder,'output'))).find(name=>name.endsWith('.gcode'))),'utf8');const events=[...code.matchAll(/^;PURGE from=(-?\d+) to=(\d+) hotend=(\d+) length=([\d.e+-]+)$/gm)].map(match=>({from:Number(match[1]),to:Number(match[2]),nozzle:Number(match[3]),length:Number(match[4])}));assert.ok(events.length>=12,'native tool-change macros must execute');return{events,settings:importNative3MF(await readFile(path.join(folder,'output','native.3mf'))).nativeSettings,walls:parseGcode(code).segments.filter(s=>s.kind==='extrusion'&&s.feature==='Outer wall').map(s=>[s.tool,s.start,s.end])};}};
}
test('native 2.4.2 uses each physical nozzle matrix and multiplier independently and retains them in native re-export',{timeout:120000},async t=>{const c=await context(t),baseline=await c.slice('baseline',c.project),second=structuredClone(c.project);second.nativeSettings.flush_multiplier[1]='.5';const halved=await c.slice('second-half',second),first=structuredClone(c.project);first.nativeSettings.flush_volumes_matrix=first.nativeSettings.flush_volumes_matrix.map((value,index)=>String(index<16?Number(value)*2:value));const doubled=await c.slice('first-double',first);
 const area=Math.PI*(1.75/2)**2;assert.equal(baseline.events.length,halved.events.length);assert.equal(baseline.events.length,doubled.events.length);assert.ok(baseline.events.some(event=>event.nozzle===0&&event.length>0));assert.ok(baseline.events.some(event=>event.nozzle===1&&event.length>0));
 for(const[index,event]of baseline.events.entries()){const expected=event.length===0?0:(event.nozzle===0?100:500)/area;assert.ok(Math.abs(event.length-expected)<.001,JSON.stringify(event));for(const result of[halved,doubled])assert.deepEqual({...result.events[index],length:0},{...event,length:0});assert.ok(Math.abs(halved.events[index].length-event.length*(event.nozzle===1?.5:1))<.001);assert.ok(Math.abs(doubled.events[index].length-event.length*(event.nozzle===0?2:1))<.001);}
 assert.deepEqual(baseline.walls,halved.walls);assert.deepEqual(baseline.walls,doubled.walls);assert.ok(baseline.walls.length>=48,`${baseline.walls.length} wall segments`);for(const[result,source]of[[baseline,c.project],[halved,second],[doubled,first]])for(const key of['flush_volumes_matrix','flush_multiplier','filament_map'])assert.deepEqual(result.settings[key].map(Number),source.nativeSettings[key].map(Number));t.diagnostic(`${baseline.events.length} native purge events: 100/500 mm³ tables remain independent; halving nozzle2 multiplier and doubling nozzle1 table change only their intended purge lengths.`);
});
test('native slicing retains both old nozzle tables after imported-material expansion',{timeout:120000},async t=>{const c=await context(t);c.project.nativeSettings=extendPrusaFilaments(c.project.nativeSettings,5);c.project.plates=c.project.plates.map(plate=>updatePlatePrintSequence(plate,{firstLayer:[1,2,3,4,5],ranges:[{start:2,end:999,order:[1,2,3,4,5]}]},5));const result=await c.slice('expanded',c.project);assert.equal(result.settings.flush_volumes_matrix.length,50);assert.deepEqual(result.settings.flush_multiplier,['1','1']);for(let n=0;n<2;n++)for(let from=0;from<4;from++)for(let to=0;to<4;to++)assert.equal(Number(result.settings.flush_volumes_matrix[n*25+from*5+to]),from===to?0:n===0?100:500);assert.equal(result.settings.filament_settings_id.length,5);assert.deepEqual(result.settings.filament_map,['1','1','2','2','1']);});
