import test from 'node:test';import assert from 'node:assert/strict';import{readFile,mkdtemp,rm,readdir}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{createApp,defaultBinary}from'../../server/app.js';import{importNative3MF,exportNative3MF}from'../../shared/native-project.js';import{shrinkageCase}from'../fixtures/shrinkage-cases.js';import{parseGcode}from'../../shared/gcode.js';
import{makeNativeAcceptanceProject}from'../fixtures/native-project.js';
import{export3MF,emptyProject}from'../../shared/project.js';import{createMesh}from'../../shared/geometry.js';
const motions=code=>code.split(/\r?\n/).map(line=>line.split(';',1)[0].trim()).filter(line=>/^G[0123]\b/.test(line));
async function setup(t){const dataDir=await mkdtemp(path.join(tmpdir(),'orca-raw-shrink-api-')),app=await createApp({dataDir,binary:process.env.ORCA_SLICER_BIN||defaultBinary}),server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(async()=>{await app.locals.shutdown();await new Promise(resolve=>server.close(resolve));if(process.env.ORCA_SHRINK_DEBUG)t.diagnostic(dataDir);else await rm(dataDir,{recursive:true,force:true});});const base=`http://127.0.0.1:${server.address().port}`,health=await(await fetch(`${base}/api/health`)).json();assert.equal(health.engine.version,'OrcaSlicer-2.4.2');const{defaults}=await(await fetch(`${base}/api/presets`)).json();return{async slice(bytes,{filamentShrink=98,printerSettings={},settings={}}={}){const form=new FormData();for(const[key,value]of Object.entries(defaults))form.set(key,value);form.set('model',new Blob([bytes]),'raw-project.3mf');form.set('settings',JSON.stringify({layer_height:.2,initial_layer_print_height:.2,outer_wall_speed:70,enable_prime_tower:false,...settings}));form.set('filamentSettings',JSON.stringify({filament_shrink:[filamentShrink],filament_shrinkage_compensation_z:[filamentShrink]}));form.set('printerSettings',JSON.stringify(printerSettings));const response=await fetch(`${base}/api/jobs`,{method:'POST',body:form}),created=await response.json();assert.equal(response.status,202,JSON.stringify(created));await app.locals.waitForIdle();const job=await(await fetch(`${base}/api/jobs/${created.id}`)).json();assert.equal(job.status,'ready',job.error);const code=await(await fetch(`${base}/api/jobs/${created.id}/download`)).text();assert.deepEqual(await readdir(path.join(dataDir,'work')),[]);return{job,code,zs:[...code.matchAll(/^;Z:([\d.]+)/gm)].map(m=>Number(m[1])),parsed:parseGcode(code)};}};}
test('raw native 3MF with selected98% profiles matches the captured GUI motions',{timeout:120000},async t=>{
 const api=await setup(t),bytes=await readFile(new URL('../fixtures/native-gui-shrink98-2.4.2.3mf',import.meta.url)),actual=await api.slice(bytes),reference=await readFile(new URL('../fixtures/native-gui-shrink98-2.4.2.gcode',import.meta.url),'utf8');assert.equal(actual.job.shrinkageInitialization.configuration,'native-profile-merge');assert.equal(actual.zs.length,102);assert.equal(actual.zs.at(-1),20.4);assert.equal(motions(actual.code).length,9217);assert.deepEqual(motions(actual.code),motions(reference));
});
test('raw native merged settings retain an active embedded second material when selected slot1 is100%',{timeout:120000},async t=>{
 const api=await setup(t),p=(await shrinkageCase('range-same')).project;p.objects[0].native.layerConfigRanges=[];p.objects[0].filamentSlot=2;p.objects[0].native.objectSettings.extruder='2';const actual=await api.slice(exportNative3MF(p),{filamentShrink:100,printerSettings:{single_extruder_multi_material:true}});assert.deepEqual(actual.job.shrinkageInitialization.usedFilamentSlots,[2]);assert.equal(actual.zs.length,102);assert.equal(actual.zs.at(-1),20.4);assert.ok(actual.parsed.segments.some(s=>s.kind==='extrusion'&&s.tool===1));
});
test('raw painted mixed material XY mismatch disables all shrinkage after exact native merge',{timeout:120000},async t=>{
 const api=await setup(t),p=(await shrinkageCase('mixed-xy')).project,actual=await api.slice(exportNative3MF(p),{printerSettings:{single_extruder_multi_material:true}});assert.equal(actual.job.shrinkageInitialization,undefined);assert.equal(actual.zs.length,100);assert.equal(actual.zs.at(-1),20);const tools=new Set(actual.parsed.segments.filter(s=>s.kind==='extrusion'&&/wall/i.test(s.feature)).map(s=>s.tool));assert.deepEqual([...tools].sort(),[0,1]);
});
test('raw native negative parts, modifier settings, material slots and custom layer events survive initialization',{timeout:120000},async t=>{
 const api=await setup(t),base=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url))),p=makeNativeAcceptanceProject(base),full=(await shrinkageCase('range-same')).project;
 p.nativeSettings={...full.nativeSettings,single_extruder_multi_material:'1',brim_type:'no_brim'};p.plates=p.plates.slice(0,1);p.objects=p.objects.filter(o=>o.plateId==='plate-1');p.plates[0].layerEvents={mode:'SingleExtruder',items:[{printZ:1,type:'Custom',extruder:1,color:'',extra:'M117 Raw archive event'}]};
 const actual=await api.slice(exportNative3MF(p),{printerSettings:{single_extruder_multi_material:true}});assert.deepEqual(actual.job.shrinkageInitialization.usedFilamentSlots,[1,2]);assert.equal(actual.zs.length,102);assert.match(actual.code,/^M117 Raw archive event$/m);assert.match(actual.code,/outer_wall_speed = 70/);
 const segments=actual.parsed.segments.filter(s=>s.kind==='extrusion'&&s.feature!=='Custom'&&s.end[2]>.3),tools=new Set(segments.map(s=>s.tool));assert.deepEqual([...tools].sort(),[0,1]);
 const cutout=segments.filter(s=>s.start[0]<55&&s.end[0]<55);assert.ok(cutout.length>1000);
 for(const s of cutout)for(const t of [.25,.5,.75]){const x=s.start[0]+(s.end[0]-s.start[0])*t,y=s.start[1]+(s.end[1]-s.start[1])*t;assert.ok(!(x>37&&x<43&&y>47&&y<53),'Native negative part remains a through-hole');}
 const blueWalls=segments.filter(s=>s.tool===1&&s.feature==='Outer wall');assert.ok(blueWalls.length>100);assert.ok(blueWalls.some(s=>Math.abs(s.speed-45)<.01),'Per-part45mm/s wall override survives selected global70mm/s process');
});
test('geometry-only3MF receives native automatic placement and keeps independent native objects',{timeout:120000},async t=>{
 const api=await setup(t),base=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url))),p={...emptyProject(),objects:[createMesh({...base.objects[0],id:'one',name:'First cube',plateId:'plate-1',native:undefined,position:[30,40,0]}),createMesh({...base.objects[0],id:'two',name:'Second cube',plateId:'plate-1',native:undefined,position:[80,40,0]})],selectedId:'one'},actual=await api.slice(export3MF(p));
 assert.equal(actual.zs.length,102);assert.equal(actual.zs.at(-1),20.4);assert.equal(actual.job.shrinkageInitialization.configuration,'native-archive-normalization');const labels=new Set([...actual.code.matchAll(/^; printing object (.+) id:/gm)].map(m=>m[1]));assert.equal(labels.size,2);assert.ok([...labels].some(name=>name.includes('First cube')));assert.ok([...labels].some(name=>name.includes('Second cube')));
});
test('raw native initialization leaves printer bed adaptation authoritative',{timeout:120000},async t=>{
 const api=await setup(t),bytes=await readFile(new URL('../fixtures/native-gui-shrink98-2.4.2.3mf',import.meta.url)),printerSettings={printable_area:['0x0','300x0','300x250','0x250']},warm=await api.slice(bytes,{printerSettings}),cold=await api.slice(bytes,{printerSettings,filamentShrink:100});
 const bounds=parsed=>{const walls=parsed.segments.filter(s=>s.kind==='extrusion'&&s.feature==='Outer wall'),xs=walls.flatMap(s=>[s.start[0],s.end[0]]),ys=walls.flatMap(s=>[s.start[1],s.end[1]]);assert.ok(walls.length>100);return{center:[(Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2],width:Math.max(...xs)-Math.min(...xs)};},w=bounds(warm.parsed),c=bounds(cold.parsed);
 assert.deepEqual(w.center,[95,100]);assert.deepEqual(w.center,c.center);assert.ok(w.width>c.width+.39);assert.equal(warm.zs.length,102);assert.equal(cold.zs.length,100);assert.equal(cold.job.shrinkageInitialization,undefined);
});

// Core material-property resources are interpreted by the native importer.
// The adapter must retain that interpretation rather than baking every object
// into a separate, slot-one STL.
import{XMLParser,XMLBuilder}from'fast-xml-parser';import{strFromU8,strToU8,zipSync}from'fflate';import{extractBoundedZip}from'../../shared/import-limits.js';
const xmlParser=new XMLParser({ignoreAttributes:false,parseTagValue:false,parseAttributeValue:false}),xmlBuilder=new XMLBuilder({ignoreAttributes:false});
test('generic3MF color resources retain native material assignments during normalization',{timeout:120000},async t=>{
 const api=await setup(t),base=(await shrinkageCase('range-same')).project,original=base.objects[0],p={...emptyProject(),objects:[createMesh({...original,id:'red',name:'Red source',plateId:'plate-1',native:undefined,position:[-30,0,0]}),createMesh({...original,id:'blue',name:'Blue source',plateId:'plate-1',native:undefined,position:[30,0,0]})],selectedId:'red'},files=extractBoundedZip(export3MF(p)),model=xmlParser.parse(strFromU8(files['3D/3dmodel.model']));
 model.model['@_xmlns:m']='http://schemas.microsoft.com/3dmanufacturing/material/2015/02';model.model.resources['m:colorgroup']=[{'@_id':'10','m:color':{'@_color':'#FF0000'}},{'@_id':'11','m:color':{'@_color':'#0000FF'}}];for(const[index,object]of model.model.resources.object.entries()){object['@_pid']=String(index+10);object['@_pindex']='0';}
 files['3D/3dmodel.model']=strToU8(xmlBuilder.build(model));files['Metadata/project_settings.config']=strToU8(JSON.stringify({...base.nativeSettings,single_extruder_multi_material:'1'}));delete files['Metadata/orca-web.json'];const actual=await api.slice(zipSync(files),{printerSettings:{single_extruder_multi_material:true}});
 assert.equal(actual.job.shrinkageInitialization.configuration,'native-archive-normalization');assert.deepEqual(actual.job.shrinkageInitialization.usedFilamentSlots,[1,2]);assert.equal(actual.zs.length,102);const walls=actual.parsed.segments.filter(s=>s.kind==='extrusion'&&s.feature==='Outer wall');assert.deepEqual([...new Set(walls.map(s=>s.tool))].sort(),[0,1]);for(const tool of[0,1])assert.ok(walls.filter(s=>s.tool===tool).length>300);
});
test('3MF carrying native object settings without project globals preserves part overrides through normalization',{timeout:120000},async t=>{
 const api=await setup(t),base=importNative3MF(await readFile(new URL('../fixtures/native-gui-shrink98-2.4.2.3mf',import.meta.url))),p={...emptyProject(),objects:[createMesh({...base.objects[0],id:'one',name:'Legacy object settings',plateId:'plate-1',native:undefined})],selectedId:'one'},files=extractBoundedZip(export3MF(p));files['Metadata/model_settings.config']=strToU8('<config><object id="1"><metadata key="name" value="Object with local speed"/><metadata key="outer_wall_speed" value="45"/><part id="1" subtype="normal_part"><metadata key="name" value="Retained part"/></part></object></config>');delete files['Metadata/orca-web.json'];const actual=await api.slice(zipSync(files));
 assert.equal(actual.job.shrinkageInitialization.configuration,'native-archive-normalization');assert.equal(actual.zs.length,102);assert.match(actual.code,/outer_wall_speed = 70/);const walls=actual.parsed.segments.filter(s=>s.kind==='extrusion'&&s.feature==='Outer wall'&&s.end[2]>1);assert.ok(walls.length>300);assert.ok(walls.every(s=>Math.abs(s.speed-45)<.01),'Native object45mm/s setting survives selected global70mm/s');
});
