import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,readFile,readdir,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';import express from'express';
import{createPresetCatalog}from'../../server/presets.js';import{createCalibrationSessions}from'../../server/calibration-sessions.js';import{runSlicer}from'../../server/slicer.js';import{applyCalibrationOverrides,applyCalibrationGcode}from'../../shared/calibration.js';import{retractionLength}from'../../shared/retraction-calibration.js';import{exportSTL,analyzeMesh,meshBounds}from'../../shared/geometry.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer',resourcesDir=process.env.ORCA_RESOURCES_DIR||'/Applications/OrcaSlicer.app/Contents/Resources';let base;test.before(async()=>{base=await createPresetCatalog({binary})});
function inspect(gcode){const layers=[],extrusions=[];let index=-1,phase='before',relative=false,e=0,feed=0,retracted=0,active=false,cycles=0;for(const line of gcode.split('\n')){
 if(line===';LAYER_CHANGE'){index++;layers.push({z:null,before:[],after:[]});phase='before';active=true;}if(line.startsWith(';Z:')&&index>=0)layers[index].z=Number(line.slice(3));if(line===';_SET_FAN_SPEED_CHANGING_LAYER')phase='after';if(line===';TYPE:Custom'&&active)active=false;
 const command=line.split(';')[0].trim();if(/^M83\b/.test(command))relative=true;if(/^M82\b/.test(command))relative=false;const v=Object.fromEntries([...command.matchAll(/\b([XYZEF])([-+]?\d*\.?\d+)/g)].map(m=>[m[1],Number(m[2])]));if(/^G92\b/.test(command)&&v.E!==undefined)e=v.E;
 if(/^G[0123]\b/.test(command)){if(v.F!==undefined)feed=v.F;const delta=v.E===undefined?0:relative?v.E:v.E-e;if(v.E!==undefined)e=relative?e+v.E:v.E;
 if(active&&/;\s*(?:;\s*)?unretract\s*$/.test(line)){assert.ok(Math.abs(delta-retracted)<.00012,`Unretract ${delta} did not balance prior retraction ${retracted}`);retracted=0;cycles++;}else if(active&&(/;\s*(?:retract|wipe and retract)\s*$/.test(line)))retracted-=delta;
 if(active&&v.E!==undefined&&!['X','Y','Z'].some(k=>v[k]!==undefined))extrusions.push({index,phase,delta:Number(delta.toFixed(5)),feed});if(active&&['X','Y','Z'].some(k=>v[k]!==undefined))layers[index][phase].push({move:command.replace(/\s[EF][-+\d.]+/g,''),delta,feed,wipe:/wipe and retract/.test(line)});
 }}return{layers,cycles,extrusions};}
function wipeBlocks(gcode){let relative=false,e=0,feed=0,prior=null,current=null;const blocks=[];for(const line of gcode.split('\n')){const command=line.split(';')[0].trim();if(/^M83\b/.test(command))relative=true;if(/^M82\b/.test(command))relative=false;const v=Object.fromEntries([...command.matchAll(/\b([XYZEF])([-+]?\d*\.?\d+)/g)].map(m=>[m[1],Number(m[2])]));if(/^G92\b/.test(command)&&v.E!==undefined)e=v.E;if(line===';WIPE_START')current={before:prior?.retract?-prior.delta:0,moves:[]};if(/^G[0123]\b/.test(command)){if(v.F!==undefined)feed=v.F;const delta=v.E===undefined?0:relative?v.E:v.E-e;if(v.E!==undefined)e=relative?e+v.E:v.E;if(current&&/wipe and retract/.test(line))current.moves.push({path:command.replace(/\s[EF][-+\d.]+/g,''),delta,feed});prior={retract:/; retract$/.test(line),delta};}if(line===';WIPE_END'){current.total=current.before-current.moves.reduce((sum,m)=>sum+m.delta,0);current.key=JSON.stringify(current.moves.map(m=>[m.path,m.feed]));blocks.push(current);current=null;}}return blocks;}
for(const scenario of ['positive-wipe-hop','zero-wipe-nohop','absolute-no-wipe'])test(`real native retraction ${scenario} changes paired E and matches native wipe/deposition/travel paths`,{timeout:120000},async t=>{
 const directory=await mkdtemp(path.join(tmpdir(),'orca-retraction-native-'));t.diagnostic(directory);t.after(()=>process.env.ORCA_KEEP_NATIVE?undefined:rm(directory,{recursive:true,force:true}));const ids=base.list().defaults;
 const catalog={resolveSelection:async values=>{const s=await base.resolveSelection(values);s.filament.slow_down_layer_time=['0'];s.process.max_volumetric_extrusion_rate_slope='0';s.filament.adaptive_pressure_advance=['0'];if(scenario!=='positive-wipe-hop')s.printer.z_hop=['0'];if(scenario==='absolute-no-wipe'){s.printer.wipe=['0'];s.printer.use_relative_e_distances='0';s.printer.machine_start_gcode='G21\nG90\nM82\nG92 E0';s.printer.before_layer_change_gcode=';BEFORE_LAYER_CHANGE';}return s;}};
 const sessions=createCalibrationSessions({binary,resourcesDir,catalog}),app=express();app.use('/api/calibrations',sessions.router);app.use((error,req,res,next)=>res.status(error.status||500).json({error:error.message}));const server=app.listen(0,'127.0.0.1');await new Promise((resolve,reject)=>{server.once('listening',resolve);server.once('error',reject)});t.after(async()=>{await sessions.shutdown();await new Promise(resolve=>server.close(resolve))});
 const response=await fetch(`http://127.0.0.1:${server.address().port}/api/calibrations/prepare`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...ids,mode:'retraction',start:scenario==='zero-wipe-nohop'?0:.2,end:scenario==='zero-wipe-nohop'?.4:.6,step:.2})}),prepared=await response.json();assert.equal(response.status,200,JSON.stringify(prepared));const analysis=analyzeMesh(prepared.objects[0]);assert.equal(analysis.manifold,true,JSON.stringify(analysis));assert.ok(Math.abs(meshBounds(prepared.objects[0]).size[2]-3.3999)<.0001);
 const inputPath=path.join(directory,'retraction.stl');await writeFile(inputPath,new Uint8Array(exportSTL(prepared.objects)));const verified=await sessions.validateUpload({calibration:prepared.calibration,ids,inputPath,overrides:{}});await assert.rejects(sessions.validateUpload({calibration:{...prepared.calibration,end:prepared.calibration.end+.2},ids,inputPath,overrides:{}}),/parameters changed/);
 const settings=applyCalibrationOverrides(verified.selection,verified.plan);await mkdir(path.join(directory,'config'));await writeFile(path.join(directory,'process.json'),JSON.stringify(settings.process));
 async function slice(length){const out=path.join(directory,`out-${length}`);await mkdir(out);await writeFile(path.join(directory,'printer.json'),JSON.stringify({...settings.printer,retraction_length:[String(length)]}));await writeFile(path.join(directory,'filament.json'),JSON.stringify({...settings.filament,filament_retraction_length:[String(length)]}));await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--outputdir',out,'--datadir',path.join(directory,'config'),'--load-settings',`${path.join(directory,'printer.json')};${path.join(directory,'process.json')}`,'--load-filaments',path.join(directory,'filament.json'),inputPath],{cwd:directory,timeoutMs:60000,signal:t.signal});const files=(await readdir(out)).filter(n=>n.endsWith('.gcode'));assert.equal(files.length,1);return readFile(path.join(out,files[0]),'utf8');}
 const raw=await slice(verified.plan.retraction.baseLength),result=applyCalibrationGcode(raw,verified.plan),actual=inspect(result.gcode),refs=new Map([[verified.plan.retraction.baseLength,inspect(raw)]]);for(const length of new Set([verified.plan.retraction.initialLength,...actual.layers.map(l=>retractionLength(verified.plan,l.z))]))if(!refs.has(length))refs.set(length,inspect(await slice(length)));
 // Repeated identical native slices can reorder tower islands. Prove every
 // transformed XYZ/feed/deposition command stays equal to its actual native
 // baseline, then compare wipe geometry and E distribution to independent
 // native constant-length slices without treating island order as an oracle.
 const baseline=inspect(raw);let checked=0;
 for(let index=0;index<actual.layers.length;index++)for(const phase of ['before','after']){const expected=baseline.layers[index][phase],moves=actual.layers[index][phase];assert.equal(moves.length,expected.length);for(let m=0;m<moves.length;m++){assert.equal(moves[m].move,expected[m].move);assert.equal(moves[m].feed,expected[m].feed);if(!moves[m].wipe)assert.ok(Math.abs(moves[m].delta-expected[m].delta)<.00012);checked++;}}
 let matchedWipes=0;const nativeBlocks=[];for(const length of refs.keys()){const content=await readFile(path.join(directory,`out-${length}`,'plate_1.gcode'),'utf8');nativeBlocks.push(...wipeBlocks(content));}const coveredLengths=new Set();
 for(const block of wipeBlocks(result.gcode)){const reference=nativeBlocks.find(candidate=>candidate.key===block.key&&Math.abs(candidate.total-block.total)<.00012);if(!reference)continue;assert.ok(Math.abs(block.before-reference.before)<.00012);for(let i=0;i<block.moves.length;i++)assert.ok(Math.abs(block.moves[i].delta-reference.moves[i].delta)<.00012);matchedWipes++;coveredLengths.add(Number(block.total.toFixed(5)));}
 if(scenario!=='absolute-no-wipe'){assert.equal(matchedWipes,wipeBlocks(result.gcode).length,'Every generated wipe cycle must match a native constant-length reference');assert.ok(matchedWipes>20);for(const layer of actual.layers)assert.ok(coveredLengths.has(Number(retractionLength(verified.plan,layer.z).toFixed(5))),`No independent native wipe proof for ${layer.z}`);}
 if(scenario==='absolute-no-wipe')for(let index=0;index<actual.layers.length;index++)for(const phase of ['before','after']){const length=phase==='after'?retractionLength(verified.plan,actual.layers[index].z):index?retractionLength(verified.plan,actual.layers[index-1].z):verified.plan.retraction.initialLength;const printed=moves=>moves.filter(m=>m.delta>0).map(m=>({...m,delta:Number(m.delta.toFixed(5))})).sort((a,b)=>a.move.localeCompare(b.move));assert.deepEqual(printed(actual.layers[index][phase]),printed(refs.get(length).layers[index][phase]));const es=rows=>rows.filter(r=>r.index===index&&r.phase===phase).sort((a,b)=>a.delta-b.delta);const expectedE=es(refs.get(length).extrusions);const actualE=es(actual.extrusions);assert.equal(actualE.length,expectedE.length);for(let i=0;i<actualE.length;i++)if(actualE[i].delta<0)assert.equal(actualE[i].delta,expectedE[i].delta);else assert.ok(actualE[i].delta>=0); /* Pair balance is checked above across layer boundaries. */}
 assert.ok(actual.cycles>10);assert.ok(result.summary.changedExtrusionCommands>20);assert.equal(result.summary.timeEstimate,'unavailable-after-retraction-calibration');assert.doesNotMatch(result.gcode,/^M73\b|^; estimated printing time/m);assert.match(result.gcode,/^; filament used \[g\]/m);t.diagnostic(`${scenario}: ${analysis.triangles} closed triangles, ${actual.cycles} balanced retraction cycles, ${checked} preserved native XYZ/E/F movements, ${matchedWipes} matched native wipe cycles across ${refs.size} constant-length slices. No printer contacted.`);
});
