import test from'node:test';import assert from'node:assert/strict';import{readFile,writeFile,mkdir,mkdtemp,readdir,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{inspectSlicer,sliceModel}from'../../server/slicer.js';import{prepareShrinkageWarmup}from'../../server/shrinkage-warmup.js';import{parseGcode}from'../../shared/gcode.js';import{shrinkageCase}from'../fixtures/shrinkage-cases.js';import{createNativeProjectService}from'../../server/native-projects.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';import{importNative3MF}from'../../shared/native-project.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer';
const motions=code=>code.split(/\r?\n/).map(line=>line.split(';',1)[0].trim()).filter(line=>/^G[0123]\b/.test(line));
const zs=code=>[...code.matchAll(/^;Z:([\d.]+)/gm)].map(match=>Number(match[1]));
async function setup(t){const engine=await inspectSlicer(binary);assert.equal(engine.available,true,engine.error);assert.equal(engine.version,'OrcaSlicer-2.4.2');const root=await mkdtemp(path.join(tmpdir(),'orca-warmup-native-'));t.after(()=>process.env.ORCA_SHRINK_DEBUG?t.diagnostic(root):rm(root,{recursive:true,force:true}));return{root,async slice(prepared,label,{initialize=true}={}){const dir=path.join(root,label);await mkdir(dir);const input=path.join(dir,'model.3mf'),output=path.join(dir,'result.gcode');await writeFile(input,prepared.bytes);const warm=initialize?prepareShrinkageWarmup({...prepared,engineVersion:engine.version}):null,result=await sliceModel({binary,input,output,preservePosition:true,timeoutMs:60000,signal:t.signal,shrinkageWarmup:warm});const code=await readFile(output,'utf8');assert.deepEqual((await readdir(dir)).sort(),['model.3mf','result.gcode']);return{code,warm,result,parsed:parseGcode(code)};}};}
const walls=parsed=>{const segments=parsed.segments.filter(segment=>segment.kind==='extrusion'&&/outer wall|external perimeter/i.test(segment.feature));assert.ok(segments.length>100);const min=[Infinity,Infinity],max=[-Infinity,-Infinity];for(const segment of segments)for(const p of[segment.start,segment.end])for(let a=0;a<2;a++){min[a]=Math.min(min[a],p[a]);max[a]=Math.max(max[a],p[a]);}return{min,max,size:max.map((v,a)=>v-min[a])};};
test('second native apply matches all captured positive-shrinkage GUI motions without changing vertices',{timeout:120000},async t=>{
 const{slice}=await setup(t),project=importNative3MF(await readFile(new URL('../fixtures/native-gui-shrink98-2.4.2.3mf',import.meta.url))),prepared=await createNativeProjectService({catalog:fixtureCatalog(project)}).prepare({project,useEmbeddedSettings:true}),actual=await slice(prepared,'warm'),cold=await slice(prepared,'cold',{initialize:false}),reference=await readFile(new URL('../fixtures/native-gui-shrink98-2.4.2.gcode',import.meta.url),'utf8');
 assert.deepEqual(motions(actual.code),motions(reference));assert.equal(motions(actual.code).length,9217);assert.equal(zs(actual.code).length,102);assert.equal(zs(actual.code).at(-1),20.4);assert.equal(zs(cold.code).length,100);assert.equal(zs(cold.code).at(-1),20);assert.equal(actual.result.shrinkageInitialization.method,'native-two-apply');t.diagnostic('9,217 installed-CLI motion commands exactly match the captured native GUI reference; cold CLI retains the independently observed 100-layer discrepancy.');
});
for(const kind of['xy-only','z-only','unused-slot','paint-same','range-same','brim','support-slot','mixed-xy'])test(`native ${kind} initialization preserves source-used materials and expected compensated geometry`,{timeout:120000},async t=>{
 const{slice}=await setup(t),prepared=await shrinkageCase(kind),actual=await slice(prepared,kind),cold=await slice(prepared,`${kind}-cold`,{initialize:false}),layers=zs(actual.code),xy=walls(actual.parsed),plainXY=walls(cold.parsed);
 if(kind==='mixed-xy'){assert.equal(actual.warm,null);assert.deepEqual(motions(actual.code),motions(cold.code));assert.equal(layers.length,100);return;}
 assert.equal(layers.length,kind==='xy-only'?100:102);assert.equal(layers.at(-1),kind==='xy-only'?20:20.4);assert.deepEqual(actual.warm.summary.usedFilamentSlots,['unused-slot','xy-only','z-only','brim'].includes(kind)?[1]:[1,2]);
 if(kind==='z-only'){xy.size.forEach((width,axis)=>assert.ok(Math.abs(width-plainXY.size[axis])<.003));}else xy.size.forEach((width,axis)=>assert.ok(width>plainXY.size[axis]+.39&&width<plainXY.size[axis]+.42,`${kind} axis${axis}: ${width} vs ${plainXY.size[axis]}`));
 if(kind==='brim'){const brim=actual.parsed.segments.filter(s=>s.kind==='extrusion'&&/brim/i.test(s.feature));assert.ok(brim.length>50);assert.ok(brim.every(s=>s.end[2]<.3));}
 if(kind==='paint-same'||kind==='range-same'){const slots=new Set(actual.parsed.segments.filter(s=>s.kind==='extrusion'&&/wall/i.test(s.feature)).map(s=>s.tool));assert.ok(slots.size>1,JSON.stringify([...slots]));}
 t.diagnostic(`${kind}: ${layers.length} layers; bounds ${xy.size.map(v=>v.toFixed(3)).join('×')}mm; source-used slots ${actual.warm.summary.usedFilamentSlots.join(',')}. GUI reference for this variant remains pending.`);
});
