import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createApp, defaultBinary } from '../../server/app.js';

// Deliberately fails when a real engine/resources are unavailable. Never silently skips or substitutes a fake.
test('real OrcaSlicer slices an API-uploaded STL with native presets and honors process overrides', {timeout:120000}, async t=>{
  const dataDir=await mkdtemp(path.join(tmpdir(),'orca-native-test-'));
  const app=await createApp({dataDir,binary:process.env.ORCA_SLICER_BIN||defaultBinary});
  const server=app.listen(0,'127.0.0.1');
  await new Promise(resolve=>server.once('listening',resolve));
  t.after(async()=>{await app.locals.shutdown();await new Promise(resolve=>server.close(resolve));await rm(dataDir,{recursive:true,force:true});});
  const base=`http://127.0.0.1:${server.address().port}`;
  const response=await fetch(`${base}/api/health`),health=await response.json();
  assert.equal(response.status,200,JSON.stringify(health));
  assert.match(health.engine.version,/^OrcaSlicer-2\.4\.2(?:\b|$)/);
  const presets=await(await fetch(`${base}/api/presets`)).json();
  assert.ok(presets.defaults.printerId&&presets.defaults.processId&&presets.defaults.filamentId);
  const geometry=await readFile('tests/fixtures/cube.stl');
  assert.ok((geometry.toString().match(/facet normal/g)||[]).length>=4,'Native test requires nonempty geometry');
  for(const [label,overrides] of [['baseline',{}],['overridden',{layer_height:0.12,outer_wall_speed:80,enable_support:true,ironing_type:'top',sparse_infill_density:20}]]){
    const form=new FormData();for(const [key,value] of Object.entries(presets.defaults))form.set(key,value);
    form.set('model',new Blob([geometry]),`${label}.stl`);form.set('settings',JSON.stringify(overrides));
    const upload=await fetch(`${base}/api/jobs`,{method:'POST',body:form}),created=await upload.json();
    assert.equal(upload.status,202,created.error);
    let job;
    for(let attempt=0;attempt<400;attempt++){
      job=await(await fetch(`${base}/api/jobs/${created.id}`)).json();
      if(['ready','failed'].includes(job.status))break;
      await new Promise(resolve=>setTimeout(resolve,100));
    }
    assert.equal(job.status,'ready',job.error);
    const download=await fetch(`${base}/api/jobs/${created.id}/download`);
    assert.equal(download.status,200);
    const gcode=await download.text();
    assert.match(gcode,/generated by OrcaSlicer/i);
    assert.match(gcode,/^G1 .*E[0-9]/m);
    assert.ok(gcode.length>10000,'Should contain genuine toolpaths, not a stub');
    assert.ok(gcode.includes(job.printer),'Generated config must name the selected printer');
    assert.ok(gcode.includes(job.filament),'Generated config must name the selected filament');
    if(label==='overridden'){
      for(const expected of ['layer_height = 0.12','outer_wall_speed = 80','enable_support = 1','ironing_type = top','sparse_infill_density = 20%'])assert.ok(gcode.includes(expected),expected);
    } else assert.ok(gcode.includes(`layer_height = ${job.settings.layer_height}`));
  }
});
