import test from 'node:test';import assert from 'node:assert/strict';import{readFile,writeFile,mkdir,readdir,mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{inspectSlicer,runSlicer}from'../../server/slicer.js';import{createNativeProjectService}from'../../server/native-projects.js';import{importNative3MF}from'../../shared/native-project.js';import{layerProfileContext,adaptiveLayerHeightProfile,smoothLayerHeightProfile,updateLayerHeightProfile}from'../../shared/variable-layers.js';import{createMesh}from'../../shared/geometry.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer',reference=JSON.parse(await readFile(new URL('../fixtures/variable-layers-native-reference.json',import.meta.url)));
function pyramid(){const a=[-10,-10,0],b=[10,-10,0],c=[10,10,0],d=[-10,10,0],top=[0,0,20];return createMesh({id:'pyramid',name:'Pyramid',positions:[a,c,b,a,d,c,a,b,top,b,c,top,c,d,top,d,a,top].flat(),plateId:'plate-1'});}
const motions=code=>code.split(/\r?\n/).map(line=>line.split(';',1)[0].trim()).filter(line=>/^G[0123]\b/.test(line));
for(const scenario of [{shape:'cube',quality:.5},{shape:'pyramid',quality:0},{shape:'pyramid',quality:.25},{shape:'pyramid',quality:0,smooth:true}])test(`native variable layers ${scenario.shape} quality ${scenario.quality}${scenario.smooth?' smoothed':''} match independent native C++ profile`,{timeout:120000},async t=>{
 const engine=await inspectSlicer(binary);assert.equal(engine.available,true,engine.error);assert.match(engine.version,/^OrcaSlicer-2\.4\.2\b/);const root=await mkdtemp(path.join(tmpdir(),'orca-variable-layers-'));t.after(()=>rm(root,{recursive:true,force:true}));const base=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));base.nativeSettings={...base.nativeSettings,layer_height:'.2',initial_layer_print_height:'.2',brim_type:'no_brim',skirt_loops:'0'};if(scenario.shape==='pyramid'){base.objects=[pyramid()];base.selectedId=base.objects[0].id;}base.objects[0].position=[60,70,0];const context=layerProfileContext(base.objects,base.selectedId,base.nativeSettings),native=reference.cases.find(item=>item.shape===scenario.shape&&item.quality===scenario.quality),service=createNativeProjectService({catalog:fixtureCatalog(base)});let generated=adaptiveLayerHeightProfile(context,scenario.quality);if(scenario.smooth)generated=smoothLayerHeightProfile(generated,context,{radius:3});
 async function slice(label,profile){const project=structuredClone(base);project.objects=updateLayerHeightProfile(project.objects,project.selectedId,profile,project.nativeSettings);const prepared=await service.prepare({project,useEmbeddedSettings:true}),dir=path.join(root,label);await mkdir(dir);await mkdir(path.join(dir,'config'));await mkdir(path.join(dir,'output'));await writeFile(path.join(dir,'model.3mf'),prepared.bytes);await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--datadir',path.join(dir,'config'),'--outputdir',path.join(dir,'output'),path.join(dir,'model.3mf')],{cwd:dir,timeoutMs:60000,signal:t.signal});const files=(await readdir(path.join(dir,'output'))).filter(name=>name.endsWith('.gcode'));assert.equal(files.length,1);return readFile(path.join(dir,'output',files[0]),'utf8');}
 const actual=await slice('browser-profile',generated),expected=await slice('native-reference',scenario.smooth?native.smooth:native.profile);assert.deepEqual(motions(actual),motions(expected));const zs=[...actual.matchAll(/^;Z:([\d.]+)/gm)].map(match=>Number(match[1]));assert.equal(zs[0],.2);assert.ok(zs.length>20);assert.ok(zs.some((z,i)=>i>1&&Math.abs(z-zs[i-1]-.2)>.005),'Native must actually use variable heights, not silently reset to the uniform process');t.diagnostic(`${zs.length} layers and ${motions(actual).length} native motion commands match independent compiled-source profile exactly.`);
});
