import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,readdir,rm,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import express from 'express';
import {createCalibrationSessions} from '../../server/calibration-sessions.js';import {createPresetCatalog} from '../../server/presets.js';import {runSlicer} from '../../server/slicer.js';import {applyCalibrationOverrides,applyCalibrationGcode} from '../../shared/calibration.js';import {vfaRequestedSpeed} from '../../shared/vfa-calibration.js';import {analyzeMesh,meshBounds,exportSTL} from '../../shared/geometry.js';
const binary=process.env.ORCA_SLICER_BIN||'/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer',resourcesDir=process.env.ORCA_RESOURCES_DIR||'/Applications/OrcaSlicer.app/Contents/Resources';let base;
test.before(async()=>{base=await createPresetCatalog({binary})});
function outerMoves(gcode){let layer=-1,feature='',active=false,feed,e=0,relative=false;const layers=[];for(const line of gcode.split('\n')){
 if(line===';LAYER_CHANGE'){layers.push({z:null,moves:[]});layer++;active=false;}if(line.startsWith(';Z:')&&layer>=0)layers[layer].z=Number(line.slice(3));if(line.startsWith('; printing object '))active=true;if(line.startsWith('; stop printing object '))active=false;if(line.startsWith(';TYPE:'))feature=line.slice(6).trim();const command=line.split(';')[0].trim();if(command==='M83')relative=true;if(command==='M82')relative=false;const values=Object.fromEntries([...command.matchAll(/\b([XYZEF])([-+]?\d*\.?\d+(?:e[-+]?\d+)?)/gi)].map(m=>[m[1],Number(m[2])]));if(/^G92\b/.test(command)&&values.E!==undefined)e=values.E;
 if(/^G[0123]\b/.test(command)){if(values.F!==undefined)feed=values.F;const delta=values.E===undefined?0:relative?values.E:values.E-e;if(active&&feature==='Outer wall'&&delta>0&&('X'in values||'Y'in values))layers[layer].moves.push({geometry:command.replace(/\sF[-+\d.]+/g,''),feed});if(values.E!==undefined)e=relative?e+values.E:values.E;}}
 return layers;}
for(const scenario of ['unlimited','flow-capped','slowdown-ramp'])test(`real native VFA ${scenario} matches independently sliced band speeds, geometry and extrusion`,{timeout:120000},async t=>{
 const directory=await mkdtemp(path.join(tmpdir(),'orca-vfa-native-'));t.after(()=>rm(directory,{recursive:true,force:true}));const ids=base.list().defaults;
 const catalog={resolveSelection:async values=>{const selected=await base.resolveSelection(values);selected.process.small_perimeter_threshold='0';selected.process.max_volumetric_extrusion_rate_slope='0';selected.filament.adaptive_pressure_advance=['0'];if(scenario==='flow-capped')selected.filament.filament_max_volumetric_speed=['2'];if(scenario==='slowdown-ramp'){selected.process.initial_layer_speed='20';selected.process.slow_down_layers='5';}return selected;}};
 const sessions=createCalibrationSessions({binary,resourcesDir,catalog}),app=express();app.use('/api/calibrations',sessions.router);app.use((error,req,res,next)=>res.status(error.status||500).json({error:error.message}));const server=app.listen(0,'127.0.0.1');await new Promise((resolve,reject)=>{server.once('listening',resolve);server.once('error',reject)});t.after(async()=>{await sessions.shutdown();await new Promise(resolve=>server.close(resolve))});
 const response=await fetch(`http://127.0.0.1:${server.address().port}/api/calibrations/prepare`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...ids,mode:'vfa',start:40,end:80,step:20})}),prepared=await response.json();assert.equal(response.status,200,JSON.stringify(prepared));const mesh=prepared.objects[0],analysis=analyzeMesh(mesh);assert.equal(analysis.manifold,true,JSON.stringify(analysis));assert.ok(Math.abs(meshBounds(mesh).size[2]-15)<.002);
 const inputPath=path.join(directory,'vfa.stl');await writeFile(inputPath,new Uint8Array(exportSTL(prepared.objects)));const verified=await sessions.validateUpload({calibration:prepared.calibration,ids,inputPath,overrides:{}});
 await assert.rejects(sessions.validateUpload({calibration:{...prepared.calibration,end:100},ids,inputPath,overrides:{}}),/parameters changed/);const tampered=Buffer.from(exportSTL(prepared.objects));tampered[100]^=1;const changedPath=path.join(directory,'changed.stl');await writeFile(changedPath,tampered);await assert.rejects(sessions.validateUpload({calibration:prepared.calibration,ids,inputPath:changedPath,overrides:{}}),/geometry changed/);
 const settings=applyCalibrationOverrides(verified.selection,verified.plan);await mkdir(path.join(directory,'config'));for(const scope of ['printer','filament'])await writeFile(path.join(directory,`${scope}.json`),JSON.stringify(settings[scope]));
 async function slice(speed){const out=path.join(directory,`out-${speed}`);await mkdir(out);await writeFile(path.join(directory,'process.json'),JSON.stringify({...settings.process,outer_wall_speed:String(speed)}));await runSlicer(binary,['--slice','0','--arrange','0','--orient','0','--outputdir',out,'--datadir',path.join(directory,'config'),'--load-settings',`${path.join(directory,'printer.json')};${path.join(directory,'process.json')}`,'--load-filaments',path.join(directory,'filament.json'),inputPath],{cwd:directory,timeoutMs:60000,signal:t.signal});const file=(await readdir(out)).filter(name=>name.endsWith('.gcode'));assert.equal(file.length,1);return readFile(path.join(out,file[0]),'utf8');}
 const raw=await slice(100),result=applyCalibrationGcode(raw,verified.plan),actual=outerMoves(result.gcode),references=new Map([[100,outerMoves(raw)]]);for(const speed of [40,60,80])references.set(speed,outerMoves(await slice(speed)));
 let measured=0;for(let index=0;index<actual.length;index++){const layer=actual[index],speed=vfaRequestedSpeed(verified.plan,layer.z),expected=references.get(speed)[index];assert.ok(layer.moves.length>0);assert.equal(layer.moves.length,expected.moves.length);for(let move=0;move<layer.moves.length;move++){assert.equal(layer.moves[move].geometry,expected.moves[move].geometry,`Layer ${index+1} geometry/extrusion`);assert.ok(Math.abs(layer.moves[move].feed-expected.moves[move].feed)<.002,`Layer ${index+1} move ${move}: ${layer.moves[move].feed} versus independent native ${expected.moves[move].feed}`);measured++;}}
 assert.equal(result.summary.layers,76);assert.equal(result.summary.closingLayer,true);assert.equal(result.summary.timeEstimate,'unavailable-after-speed-calibration');assert.doesNotMatch(result.gcode,/^M73\b|^; estimated printing time/m);assert.match(result.gcode,/^; filament used \[g\]/m);if(scenario==='flow-capped'){assert.ok(result.summary.cappedMoves>0);assert.ok(Math.max(...result.summary.effectiveSpeeds)<40);}else assert.ok(result.summary.changedMoves>0);
 t.diagnostic(`${scenario}: ${analysis.triangles} closed native triangles; ${measured} effective outer-wall moves match four independent constant-speed native slices, including terminal spiral pass. No printer contacted.`);
});
