// SPDX-License-Identifier: AGPL-3.0-only
#pragma once
#include <nlohmann/json.hpp>
#include <Eigen/Geometry>
#include <cmath>
#include <set>
#include <stdexcept>
namespace arrangement_input {
using json=nlohmann::json;
inline void require(bool condition,const char*message){if(!condition)throw std::runtime_error(message);}
inline double number(const json&v,double minimum,double maximum){require(v.is_number(),"Expected a numeric arrangement value");const double n=v.get<double>();require(std::isfinite(n)&&n>=minimum&&n<=maximum,"Arrangement value exceeds numeric bounds");return n;}
inline void matrix(const json&values){if(values.is_null())return;require(values.is_array()&&values.size()==16,"Expected 16 affine matrix elements");Eigen::Matrix4d m;for(size_t i=0;i<16;++i)m.data()[i]=number(values[i],-1e7,1e7);require(m.row(3)==Eigen::RowVector4d(0,0,0,1)&&std::abs(m.determinant())>=1e-12,"Invalid arrangement affine transform");}
inline void config(const json&values){require(values.is_object()&&values.size()<=256,"Invalid arrangement settings");for(const auto&kv:values.items()){require(kv.key().size()<=128,"Setting key exceeds bounds");const auto&v=kv.value();if(v.is_array()){require((!v.empty()||kv.key()=="bed_exclude_area"||kv.key()=="wrapping_exclude_area")&&v.size()<=256,"Arrangement setting vector exceeds bounds");for(const auto&s:v)require(s.is_string()&&s.get_ref<const std::string&>().size()<=4096,"Invalid setting vector entry");}else require(v.is_string()&&v.get_ref<const std::string&>().size()<=4096,"Invalid arrangement setting value");}}
inline void request(const json&request){
 require(request.is_object()&&request.value("format",std::string())=="orca-arrangement-request"&&request.value("version",0)==1&&request.value("sourceRevision",std::string())=="8500fcdccaa10b5099ac20d252af3a7c560046f1","Invalid arrangement request identity");
 config(request.value("settings",json::object()));const auto options=request.value("options",json::object());require(options.is_object(),"Invalid arrangement options");number(options.value("spacing",json(0)),0,100);for(const auto*key:{"rotation","multipleMaterials","alignY","avoidCalibration","sequential"})if(options.contains(key))require(options[key].is_boolean(),"Invalid arrangement option type");
 const auto&objects=request.at("objects");require(objects.is_array()&&!objects.empty()&&objects.size()<=256,"Arrangement requires 1–256 objects");std::set<std::string> ids;size_t triangles=0,vertices=0,parts=0;bool selected=false;
 for(const auto&object:objects){const auto id=object.at("id").get<std::string>();require(!id.empty()&&id.size()<=256&&ids.insert(id).second,"Invalid or duplicate object identity");if(object.contains("selected"))require(object["selected"].is_boolean(),"Invalid selection state");selected|=object.value("selected",true);if(object.contains("printable"))require(object["printable"].is_boolean(),"Invalid printable state");require(object.value("printable",true),"Arrangement of non-printable objects needs the native outside-plate workspace");matrix(object.value("matrix",json()));config(object.value("settings",json::object()));const auto&volumes=object.at("parts");require(volumes.is_array()&&!volumes.empty()&&(parts+=volumes.size())<=4096,"Arrangement part count exceeds bounds");bool normal=false;
  for(const auto&part:volumes){const auto type=part.value("type",std::string("normal_part"));require(type=="normal_part"||type=="negative_part"||type=="modifier_part"||type=="support_enforcer"||type=="support_blocker","Invalid native part type");normal|=type=="normal_part";matrix(part.value("matrix",json()));config(part.value("settings",json::object()));const auto&v=part.at("vertices"),&t=part.at("triangles");require(v.is_array()&&t.is_array()&&!v.empty()&&!t.empty()&&(vertices+=v.size())<=500000&&(triangles+=t.size())<=500000,"Arrangement geometry exceeds 500000 vertices/triangles");for(const auto&p:v){require(p.is_array()&&p.size()==3,"Invalid native vertex");for(const auto&x:p)number(x,-1e6,1e6);}for(const auto&f:t){require(f.is_array()&&f.size()==3,"Invalid native triangle");for(const auto&i:f)require(i.is_number_integer()&&i.get<int64_t>()>=0&&uint64_t(i.get<int64_t>())<v.size(),"Invalid native triangle index");}
   const auto colors=part.value("color",json::object());require(colors.is_object()&&colors.size()<=t.size(),"Invalid facet color map");for(const auto&entry:colors.items()){const auto&key=entry.key();require(!key.empty()&&key.size()<=7&&key.find_first_not_of("0123456789")==std::string::npos&&std::stoul(key)<t.size(),"Invalid facet color index");require(entry.value().is_string(),"Invalid facet color data");const auto&paint=entry.value().get_ref<const std::string&>();require(paint.size()<=65536&&paint.find_first_not_of("0123456789ABCDEFabcdef")==std::string::npos,"Invalid facet color encoding");}
  }require(normal,"Arrangement requires a normal part in each object");
 }require(selected,"Select at least one object to arrange");
}
}
