// SPDX-License-Identifier: AGPL-3.0-only
// Pinned OrcaSlicer 2.4.2 / 8500fcd: GLCanvas3D.cpp get_empty_cells /
// get_nearest_empty_cell; Selection.cpp paste_objects_from_clipboard.
// Preserve the native per-hull append semantics and std::sort tie behavior.
#include "nearest-empty-cell.hpp"
#include <libslic3r/Model.hpp>
#include <libslic3r/BuildVolume.hpp>
#include <algorithm>
#include <cmath>
#include <set>
#include <stdexcept>
using namespace Slic3r;
using json=nlohmann::json;
namespace {
constexpr size_t max_objects=4096,max_vertices=500000,max_triangles=500000,max_cells=2000000,max_visits=50000000;
struct Budget{size_t vertices=0,triangles=0,visits=0;};
double number(const json&j,double low,double high,const char*name){if(!j.is_number())throw std::runtime_error(std::string(name)+" must be numeric");double v=j.get<double>();if(!std::isfinite(v)||v<low||v>high)throw std::runtime_error(std::string(name)+" exceeds bounds");return v;}
Transform3d transform(const json&value){Transform3d t=Transform3d::Identity();if(value.is_null())return t;if(!value.is_array()||value.size()!=16)throw std::runtime_error("Expected 16 affine matrix values");for(size_t i=0;i<16;++i)t.matrix().data()[i]=number(value[i],-1e7,1e7,"Matrix value");if(t.matrix().row(3)!=Eigen::RowVector4d(0,0,0,1)||std::abs(t.linear().determinant())<1e-12)throw std::runtime_error("Invalid clipboard affine transform");return t;}
json matrix(const Transform3d&t){json a=json::array();for(int i=0;i<16;++i)a.push_back(t.matrix().data()[i]);return a;}
Vec2f pair(const json&j,const char*name,double minimum=-1e6){if(!j.is_array()||j.size()!=2)throw std::runtime_error(std::string(name)+" requires two values");return Vec2f(number(j[0],minimum,1e6,name),number(j[1],minimum,1e6,name));}
void load_model(Model&model,const json&objects,Budget&budget,bool require_normal=true){
 if(!objects.is_array()||objects.size()>max_objects)throw std::runtime_error("Clipboard model exceeds 4096 objects");std::set<std::string> ids;
 for(const auto&item:objects){const std::string id=item.at("id").get<std::string>();if(id.empty()||id.size()>256||!ids.insert(id).second)throw std::runtime_error("Invalid or duplicate clipboard object ID");const auto&parts=item.at("parts");if(!parts.is_array()||parts.empty()||parts.size()>1024)throw std::runtime_error("Clipboard object requires 1–1024 parts");auto*object=model.add_object();object->name=id;object->input_file=item.value("inputFile",std::string());if(object->input_file.size()>4096)throw std::runtime_error("Clipboard source identity exceeds bounds");bool normal=false;
  for(const auto&part:parts){indexed_triangle_set geometry;const auto&vertices=part.at("vertices"),&triangles=part.at("triangles");if(!vertices.is_array()||!triangles.is_array()||vertices.empty()||triangles.empty()||(budget.vertices+=vertices.size())>max_vertices||(budget.triangles+=triangles.size())>max_triangles)throw std::runtime_error("Clipboard geometry exceeds 500000 vertices/triangles");for(const auto&p:vertices){if(!p.is_array()||p.size()!=3)throw std::runtime_error("Invalid clipboard vertex");geometry.vertices.emplace_back(number(p[0],-1e6,1e6,"Coordinate"),number(p[1],-1e6,1e6,"Coordinate"),number(p[2],-1e6,1e6,"Coordinate"));}for(const auto&f:triangles){if(!f.is_array()||f.size()!=3)throw std::runtime_error("Invalid clipboard triangle");Vec3i32 face;for(int i=0;i<3;++i){if(!f[i].is_number_integer())throw std::runtime_error("Triangle indices must be integers");face[i]=int(number(f[i],0,geometry.vertices.size()-1,"Triangle index"));}geometry.indices.push_back(face);}
   const std::string type=part.value("type",std::string("normal_part"));if(type!="normal_part"&&type!="negative_part"&&type!="modifier_part"&&type!="support_enforcer"&&type!="support_blocker")throw std::runtime_error("Unsupported clipboard part type");normal|=type=="normal_part";auto*volume=object->add_volume(TriangleMesh(std::move(geometry)));volume->set_type(ModelVolume::type_from_string(type));volume->set_transformation(transform(part.value("matrix",json()))*volume->get_matrix());
  }
  if(require_normal&&!normal)throw std::runtime_error("Clipboard whole object requires a normal part");auto*instance=object->add_instance();instance->set_transformation(Geometry::Transformation(transform(item.value("matrix",json()))));
 }
}
struct Cell{Vec2f point;size_t grid=0,eligible=0,ties=0;bool fallback=false;};
Cell nearest(const Model&model,const BoundingBoxf&bbox,Vec2f start_point,Vec2f step,Budget&budget,double fallback_size){
 std::vector<Vec2f> cells,cells_ret;
 // Keep mixed double/float arithmetic and truncating int conversion from native source.
 const auto ratio_x=(start_point.x()-bbox.min.x())/step.x(),ratio_y=(start_point.y()-bbox.min.y())/step.y();if(std::abs(ratio_x)>2e9||std::abs(ratio_y)>2e9)throw std::runtime_error("Clipboard grid origin exceeds integer bounds");
 auto min_x=start_point.x()-step.x()*int(ratio_x),min_y=start_point.y()-step.y()*int(ratio_y);
 const float largest_x=std::max(std::abs(float(min_x)),std::abs(float(bbox.max.x()))),largest_y=std::max(std::abs(float(min_y)),std::abs(float(bbox.max.y())));
 if(float(largest_x+step.x())==largest_x||float(largest_y+step.y())==largest_y)throw std::runtime_error("Clipboard cell step is below native float resolution");
 for(float x=min_x;x<bbox.max.x()-step.x()/2;x+=step.x())for(float y=min_y;y<bbox.max.y()-step.y()/2;y+=step.y()){if(cells.size()>=max_cells)throw std::runtime_error("Clipboard grid exceeds 2000000 cells");cells.emplace_back(x,y);}
 for(const ModelObject*object:model.objects){const ModelInstance*first=object->instances.front();Polygon hull=object->convex_hull_2d(Geometry::assemble_transform({0.,0.,first->get_offset().z()},first->get_rotation(),first->get_scaling_factor(),first->get_mirror()));if(hull.empty())continue;const double rotation_z0=first->get_rotation().z();for(const auto*instance:object->instances){Geometry::Transformation transformation;const auto&offset=instance->get_offset();transformation.set_offset({scale_(offset.x()),scale_(offset.y()),0.});transformation.set_rotation(Z,instance->get_rotation().z()-rotation_z0);Polygon instance_hull=hull.transform(transformation.get_matrix());for(const auto&cell:cells){if(++budget.visits>max_visits)throw std::runtime_error("Clipboard placement exceeds its 50000000-cell work bound");if(!instance_hull.contains(Point(scale_(cell.x()),scale_(cell.y())))){if(cells_ret.size()>=max_cells)throw std::runtime_error("Clipboard eligible cells exceed 2000000");cells_ret.push_back(cell);}}}}
 Vec2f start=start_point;if(start_point.x()<0&&start_point.y()<0)start=bbox.center().cast<float>();std::sort(cells_ret.begin(),cells_ret.end(),[start](const Vec2f&a,const Vec2f&b){return(a-start).norm()<(b-start).norm();});Cell result;result.grid=cells.size();result.eligible=cells_ret.size();if(cells_ret.empty()){double offset=.05*fallback_size;result.point={float(start_point.x()+offset),float(start_point.y()+offset)};result.fallback=true;}else{result.point=cells_ret.front();const float distance=(result.point-start).norm();result.ties=std::count_if(cells_ret.begin(),cells_ret.end(),[&](const Vec2f&cell){return(cell-start).norm()==distance;});}return result;
}
json cell_json(const Cell&c){return{{"point",{c.point.x(),c.point.y()}},{"gridCells",c.grid},{"eligibleEntries",c.eligible},{"equalDistanceEntries",c.ties},{"fallback",c.fallback}};}
}
json native_nearest_empty_cell(const json&request){
 const auto&bounds=request.at("bedBounds");if(!bounds.is_array()||bounds.size()!=4)throw std::runtime_error("Expected bed minX/minY/maxX/maxY");BoundingBoxf bed(Vec2d(number(bounds[0],-1e6,1e6,"Bed coordinate"),number(bounds[1],-1e6,1e6,"Bed coordinate")),Vec2d(number(bounds[2],-1e6,1e6,"Bed coordinate"),number(bounds[3],-1e6,1e6,"Bed coordinate")));if(bed.size().minCoeff()<=0||bed.size().maxCoeff()>10000)throw std::runtime_error("Invalid clipboard bed dimensions");const BoundingBoxf raw_bed=bed;const double fallback_size=bed.size().maxCoeff();bed.min.array()-=BuildVolume::SceneEpsilon;bed.max.array()+=BuildVolume::SceneEpsilon;Budget budget;Model model;load_model(model,request.at("objects"),budget);json output={{"format","orca-native-clipboard"},{"version",1},{"sourceRevision","8500fcdccaa10b5099ac20d252af3a7c560046f1"}};
 if(request.contains("pasteParts")){
  Model clipboard;load_model(clipboard,request.at("clipboardObjects"),budget,false);if(clipboard.objects.size()!=1)throw std::runtime_error("Part clipboard must contain one object");
  const std::string destination_id=request.at("pasteParts").at("destinationId").get<std::string>();ModelObject*destination=nullptr;for(auto*object:model.objects)if(object->name==destination_id)destination=object;if(!destination)throw std::runtime_error("Select one destination object to paste parts");
  const auto&copies_value=request.value("copies",json(1));if(!copies_value.is_number_integer())throw std::runtime_error("Clone count must be integer");const int copies=int(number(copies_value,1,1000,"Clone count"));
  const auto*source=clipboard.objects.front();if(destination->volumes.size()+source->volumes.size()*size_t(copies)>4096)throw std::runtime_error("Part cloning exceeds 4096 volumes");
  auto*instance=destination->instances.front();const auto source_frame=source->instances.front()->get_transformation().get_matrix_no_offset(),destination_frame=instance->get_transformation().get_matrix_no_offset();const bool same=source->input_file==destination->input_file&&source_frame.isApprox(destination_frame);
  output["parts"]=json::array();output["fromSameObject"]=same;output["destinationId"]=destination_id;
  for(int copy=0;copy<copies;++copy){const auto bounds=destination->instance_bounding_box(size_t(0));BoundingBoxf3 total;ModelVolumePtrs pasted;
   for(auto*volume:source->volumes){auto*next=destination->add_volume(*volume);if(!same)total.merge(next->mesh().bounding_box().transformed(volume->get_matrix()));pasted.push_back(next);}
   if(!same)for(auto*volume:pasted)volume->set_offset((volume->get_offset()-total.center())+destination_frame.inverse()*(Vec3d(bounds.max.x(),bounds.min.y(),bounds.min.z())+.5*total.size()-instance->get_offset()));
   for(size_t i=0;i<pasted.size();++i){
    // Return transforms of supplied raw-mesh coordinates, reversing add_volume centering.
    const auto input_component=transform(request.at("clipboardObjects")[0].at("parts")[i].value("matrix",json()));const auto centered_component=source->volumes[i]->get_matrix();const auto uncenter=input_component.inverse()*centered_component;
    output["parts"].push_back({{"copy",copy},{"sourceIndex",i},{"originalMatrix",matrix(source->instances.front()->get_matrix()*input_component)},{"matrix",matrix(instance->get_matrix()*pasted[i]->get_matrix()*uncenter.inverse())}});
   }
  }return output;
 }
 if(!request.contains("clipboardObjects")){output["nearest"]=cell_json(nearest(model,bed,pair(request.at("startPoint"),"Start point"),pair(request.at("step"),"Cell step",.001),budget,fallback_size));return output;}
 Model clipboard;load_model(clipboard,request.at("clipboardObjects"),budget);if(clipboard.objects.empty())throw std::runtime_error("Clipboard is empty");const auto&copies_value=request.at("copies");if(!copies_value.is_number_integer())throw std::runtime_error("Clone count must be integer");const int copies=int(number(copies_value,1,1000,"Clone count"));if(model.objects.size()+clipboard.objects.size()*size_t(copies)>max_objects)throw std::runtime_error("Cloning exceeds 4096 total objects");
 const double bed_height=number(request.at("bedHeight"),1,10000,"Bed height"),bed_base=number(request.value("bedBaseZ",json(0)), -100000,100000,"Bed base Z");output["clones"]=json::array();Vec2d shift_all=Vec2d::Zero();if(clipboard.objects.size()>1){BoundingBoxf3 all;for(const auto*object:clipboard.objects)all.merge(object->instance_convex_hull_bounding_box(size_t(0)));shift_all=all.size().x()<all.size().y()?Vec2d(all.size().x(),0):Vec2d(0,all.size().y());}
 for(int copy=0;copy<copies;++copy){Cell first_cell;for(size_t i=0;i<clipboard.objects.size();++i){const auto*source=clipboard.objects[i];auto*destination=model.add_object(*source);const auto bbox=source->instance_convex_hull_bounding_box(size_t(0));const bool in_current=bbox.min.x()<=raw_bed.max.x()+BuildVolume::BedEpsilon&&bbox.max.x()>=raw_bed.min.x()-BuildVolume::BedEpsilon&&bbox.min.y()<=raw_bed.max.y()+BuildVolume::BedEpsilon&&bbox.max.y()>=raw_bed.min.y()-BuildVolume::BedEpsilon&&bbox.min.z()<=1000&&bbox.max.z()>=-1e10;const Vec3d center(bed.center().x(),bed.center().y(),bed_base+bed_height/2);const Vec3d start_point=in_current?bbox.center():center,start_offset=in_current?source->instances.front()->get_offset():center;Cell cell;Vec3d displacement;const Vec2f step(bbox.size().x()+1,bbox.size().y()+1);if(step.minCoeff()<=0||!step.allFinite())throw std::runtime_error("Invalid clipboard footprint");if(shift_all.x()!=0||shift_all.y()!=0){if(i==0)first_cell=nearest(model,bed,start_point.head<2>().cast<float>(),step,budget,fallback_size);cell=first_cell;const auto instance_shift=source->instances.front()->get_offset()-clipboard.objects.front()->instances.front()->get_offset();displacement={shift_all.x()+cell.point.x()+instance_shift.x(),shift_all.y()+cell.point.y()+instance_shift.y(),start_offset.z()};}else{cell=nearest(model,bed,start_point.head<2>().cast<float>(),step,budget,fallback_size);const Vec3d point_offset=start_offset-start_point;displacement={cell.point.x()+point_offset.x(),cell.point.y()+point_offset.y(),start_offset.z()};}for(auto*instance:destination->instances){instance->set_offset(displacement);instance->set_assemble_transformation(instance->get_transformation());}const auto initial_paste=destination->instances.front()->get_matrix();if(destination->min_z()>=SINKING_Z_THRESHOLD)destination->ensure_on_bed();output["clones"].push_back({{"initialPasteMatrix",matrix(initial_paste)},{"copy",copy},{"sourceId",source->name},{"originalMatrix",matrix(source->instances.front()->get_matrix())},{"matrix",matrix(destination->instances.front()->get_matrix())},{"nearest",cell_json(cell)}});}}
 output["workVisits"]=budget.visits;return output;
}
