import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createPresetCatalog } from '../../server/presets.js';
import { createCustomPresetCatalog, createCustomPresetRouter } from '../../server/custom-presets.js';

test('HTTP custom preset CRUD/import/export is durable, typed, same-origin, and catalog-compatible',async t=>{
  const dataDir=await mkdtemp(path.join(tmpdir(),'orca-custom-api-'));
  const baseCatalog=await createPresetCatalog({profilesDir:path.resolve('tests/fixtures/presets')});
  const catalog=await createCustomPresetCatalog({baseCatalog,dataDir});
  const app=express();app.use(express.json());app.use('/api/presets/custom',createCustomPresetRouter({catalog}));
  const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
  t.after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await rm(dataDir,{recursive:true,force:true});});
  const base=`http://127.0.0.1:${server.address().port}`;
  const call=async(method,url,body,origin)=>{const response=await fetch(`${base}/api/presets/custom${url}`,{method,headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...(origin?{Origin:origin}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:response.status,body:response.status===204?null:await response.json()};};
  const defaults=catalog.list().defaults;
  const source=await call('GET',`/source/filament/${defaults.filamentId}`);
  assert.equal(source.status,200);assert.equal(source.body.custom,false);assert.deepEqual(source.body.overrides,{});assert.equal(source.body.nativeVersion,'2.4.2');assert.ok(source.body.compatiblePrinterIds.includes(defaults.printerId));
  assert.equal((await call('GET',`/source/filament/${defaults.filamentId}/export`)).body.type,'filament');
  const input={type:'filament',name:'HTTP custom PLA',baseId:defaults.filamentId,settings:{nozzle_temperature:[219]},compatiblePrinterIds:[defaults.printerId]};
  assert.equal((await call('POST','',input,'http://evil.invalid')).status,403);
  assert.equal((await call('POST','',{...input,settings:{nozzle_temperature:219}})).status,400);
  const saved=await call('POST','',input,base);assert.equal(saved.status,201);const id=saved.body.id;
  assert.deepEqual(saved.body.overrides,{nozzle_temperature:['219']});
  assert.equal((await call('GET','?type=filament')).body.length,1);
  assert.equal((await call('PUT',`/${id}`,{name:'HTTP renamed PLA'})).status,200);
  const exported=await call('GET',`/${id}/export`);assert.equal(exported.body.from,'user');assert.equal(exported.body.name,'HTTP renamed PLA');assert.deepEqual(exported.body.nozzle_temperature,['219']);
  const nativeDocument={...exported.body,name:'HTTP imported PLA'};
  const ambiguous=await call('POST','/import',{preset:nativeDocument,compatiblePrinterIds:[defaults.printerId]});assert.equal(ambiguous.status,400);assert.match(ambiguous.body.error,/Native JSON dependencies cannot be combined/);
  assert.equal((await call('GET','?type=filament')).body.length,1,'Rejected mixed dependency sources cannot persist partial data');
  const imported=await call('POST','/import',{preset:nativeDocument});assert.equal(imported.status,201);assert.deepEqual(imported.body.nativeCompatibility.compatible_printers,nativeDocument.compatible_printers);
  const roundtrip=await call('GET',`/${imported.body.id}/export`);assert.deepEqual(roundtrip.body.compatible_printers,nativeDocument.compatible_printers);assert.equal(roundtrip.body.compatible_printers_condition,nativeDocument.compatible_printers_condition);
  const reopened=await createCustomPresetCatalog({baseCatalog,dataDir});assert.equal(reopened.getCustom(imported.body.id).settings.nozzle_temperature[0],'219');
  const selection=reopened.resolveSelection({...defaults,filamentId:imported.body.id});assert.deepEqual(selection.filament.nozzle_temperature,['219']);
  assert.equal((await call('DELETE',`/${id}`)).status,204);assert.equal((await call('GET',`/${id}`)).status,404);
});
