import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {createNativeArrangementService} from '../../server/native-arrangement.js';
import {emptyVolumeFixture} from '../fixtures/import-inspection-project.js';
import {IMPORT_INSPECTION_REVISION} from '../../shared/native-import-inspection.js';
async function setup(t){let received,mode='valid',gate;const worker={identity:async()=>({metadata:{version:'2.4.2'}}),shutdown:async()=>{},process:async(bytes,{signal})=>{received=JSON.parse(bytes);if(mode==='unavailable')throw Object.assign(Error('Native inspection unavailable'),{status:503});if(mode==='wait')await new Promise((resolve,reject)=>{gate=resolve;signal.addEventListener('abort',()=>reject(Object.assign(Error('Inspection cancelled'),{name:'AbortError'})),{once:true});});const result={format:'orca-native-import-inspection',version:1,sourceRevision:IMPORT_INSPECTION_REVISION,objects:received.objects.map((o,i)=>({id:o.id,volume:i?0:8000})),retainedIds:[received.objects[0].id],removedCount:received.objects.length-1,unitSuggestion:'none'};if(mode==='invalid')result.retainedIds=['unknown'];return result;}};const service=createNativeArrangementService({worker}),app=express();app.use('/api/geometry',service.router);const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{await service.close();server.closeAllConnections();await new Promise(r=>server.close(r));});return{url:`http://127.0.0.1:${server.address().port}/api/geometry/inspect-import`,service,received:()=>received,mode:value=>mode=value,gate:()=>gate};}
const post=(url,body,signal)=>fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal});
test('import inspection API validates the project and sends canonical model data to the bounded worker',async t=>{const api=await setup(t),project=emptyVolumeFixture(),r=await post(api.url,{project});assert.equal(r.status,200);const value=await r.json();assert.equal(value.removedCount,1);assert.equal(api.received().operation,'inspect-import');assert.equal(api.received().objects.length,2);assert.equal(api.received().objects[1].parts[0].triangles.length,1);const invalid=await post(api.url,{project:{objects:[]}});assert.equal(invalid.status,400);});
test('unavailable or malformed native inspection is explicit and cannot become a successful filter',async t=>{const api=await setup(t);for(const[mode,status,pattern]of [['unavailable',503,/unavailable/],['invalid',400,/Invalid native/]]){api.mode(mode);const response=await post(api.url,{project:emptyVolumeFixture()});assert.equal(response.status,status);assert.match((await response.json()).error,pattern);}});
test('import inspection cancellation and service shutdown reach the native worker without committing results',async t=>{const api=await setup(t);api.mode('wait');const controller=new AbortController(),pending=post(api.url,{project:emptyVolumeFixture()},controller.signal);while(!api.gate())await new Promise(r=>setTimeout(r,5));controller.abort();await assert.rejects(pending,/abort/i);await api.service.close();assert.equal((await post(api.url,{project:emptyVolumeFixture()})).status,503);});
