import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,mkdir,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';import{createNativePreviewService}from'../../server/native-preview.js';import{nativePreviewFixture,nativeFixtureEngine}from'../fixtures/native-preview-result.js';import{nativeEditorTestContext}from'../fixtures/native-editor-context.js';
async function setup(t,{old=false}={}){const dataDir=await mkdtemp(path.join(tmpdir(),'orca-editor-preview-'));await mkdir(path.join(dataDir,'jobs'));const jobs=new Map([['one',{id:'one',status:'ready',nativePreviewContext:nativeEditorTestContext()}],['two',{id:'two',status:'ready',nativePreviewContext:nativeEditorTestContext()}],['legacy',{id:'legacy',status:'ready'}]]);for(const id of jobs.keys())await writeFile(path.join(dataDir,'jobs',`${id}.gcode`),'G1 X1');const calls=[];let gate;const worker={identity:async()=>({id:'helper',metadata:{...nativeFixtureEngine,...(!old&&{editorContextVersion:1})}}),process:async(bytes,options)=>{calls.push({bytes,options});if(gate)await new Promise(resolve=>{gate.release=resolve;});return nativePreviewFixture();},shutdown:async()=>{}};const service=createNativePreviewService({dataDir,jobStore:{get:id=>jobs.get(id)},worker});t.after(async()=>{await service.shutdown();await rm(dataDir,{recursive:true,force:true});});return{service,jobs,calls,setGate:v=>gate=v};}
test('same G-code with different immutable job palettes gets independent snapshot-bound results',async t=>{const api=await setup(t);api.jobs.get('two').nativePreviewContext.filamentColors[0]='#FFFF00';const one=await api.service.get('one'),two=await api.service.get('two');assert.equal(one.sourceSha256,two.sourceSha256);assert.notEqual(one.editorContextSha256,two.editorContextSha256);assert.equal(api.calls[0].options.context.filamentColors[0],'#C800FF');assert.equal(api.calls[1].options.context.filamentColors[0],'#FFFF00');await api.service.get('one');assert.equal(api.calls.length,2);});
test('changed editor context invalidates cache even if G-code and helper identity stay identical',async t=>{const api=await setup(t),before=await api.service.get('one');api.jobs.get('one').nativePreviewContext.timeCost=99;const after=await api.service.get('one');assert.notEqual(after.editorContextSha256,before.editorContextSha256);assert.equal(api.calls.length,2);assert.equal(api.service.cacheInfo.entries,1);});
test('editor snapshot mutation during native work rejects stale data and never mutates queued input',async t=>{const api=await setup(t),gate={};api.setGate(gate);const pending=api.service.get('one'),rejected=assert.rejects(pending,error=>error.status===409&&/snapshot changed/.test(error.message));while(!gate.release)await new Promise(resolve=>setTimeout(resolve,2));api.jobs.get('one').nativePreviewContext.filamentCosts[0]=999;assert.equal(api.calls[0].options.context.filamentCosts[0],22);gate.release();await rejected;assert.equal(api.service.cacheInfo.entries,0);});
test('old helpers and legacy jobs retain explicit standalone provenance instead of implying editor totals',async t=>{const api=await setup(t,{old:true}),editor=await api.service.get('one'),legacy=await api.service.get('legacy');assert.match(editor.editorContextUnavailable,/cannot apply/);assert.equal(api.calls[0].options.context,undefined);assert.equal(legacy.editorContextUnavailable,undefined);assert.equal(legacy.editorContextSha256,undefined);assert.equal(api.calls[1].options.context,undefined);});
test('invalid stored snapshots are rejected before any native processing',async t=>{const api=await setup(t);api.jobs.get('one').nativePreviewContext.customEvents[0].extruder=22;await assert.rejects(api.service.get('one'),/event metadata/);assert.equal(api.calls.length,0);});

test('unavailable bounded job context reaches the response and participates in cache identity',async t=>{const api=await setup(t);const job=api.jobs.get('legacy');job.nativePreviewContextUnavailable='Native editor Preview snapshot is unavailable: native property exceeds limit';const first=await api.service.get('legacy');assert.equal(first.editorContextUnavailable,job.nativePreviewContextUnavailable);job.nativePreviewContextUnavailable='Native editor Preview snapshot is unavailable: changed reason';const second=await api.service.get('legacy');assert.equal(second.editorContextUnavailable,job.nativePreviewContextUnavailable);assert.equal(api.calls.length,2);assert.equal(api.service.cacheInfo.entries,1);});
