import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';import{createApp}from'../../server/app.js';
async function setup(t){const dataDir=await mkdtemp(path.join(tmpdir(),'orca-process-paste-')),app=await createApp({dataDir,binary:path.resolve('tests/fixtures/fake-slicer.sh'),profilesDir:path.resolve('tests/fixtures/presets')}),server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(async()=>{await app.locals.shutdown();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await rm(dataDir,{recursive:true,force:true});});return{app,get:route=>fetch(`http://127.0.0.1:${server.address().port}${route}`),post:body=>fetch(`http://127.0.0.1:${server.address().port}/api/presets/clipboard`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})};}
const request=()=>({clipboard:{version:1,kind:'part',settings:{wall_loops:'5',extruder:'1',layer_height:'.12'}},globalSettings:{wall_loops:'2',layer_height:'.2'},filamentCount:2,targets:[{kind:'part',settings:{extruder:'2'},parentSettings:{wall_loops:'3',layer_height:'.1'}}]});
test('native process clipboard HTTP route returns typed source settings and preserves destination filament',async t=>{const api=await setup(t),response=await api.post(request());assert.equal(response.status,200,await response.clone().text());const result=await response.json();assert.deepEqual(result.settings,[{extruder:'2',layer_height:'0.2',wall_loops:'5'}]);assert.equal(result.sourceRevision,'8500fcdccaa10b5099ac20d252af3a7c560046f1');});
test('clipboard rejects mismatched scope, global-only settings, unbounded destinations and requests after shutdown',async t=>{const api=await setup(t);for(const change of[r=>r.targets[0].kind='object',r=>r.clipboard.settings.post_process=['bad'],r=>r.targets=Array(257).fill(r.targets[0]),r=>r.path='/tmp/untrusted.json']){const r=request();change(r);const response=await api.post(r);assert.equal(response.status,400,await response.text());}await api.app.locals.shutdown();const response=await api.post(request());assert.equal(response.status,503);assert.match((await response.json()).error,/shutting down/);});

test('process Paste accepts complete resolved catalog settings while keeping compatibility metadata out of native overrides',async t=>{
 const api=await setup(t),catalog=await(await api.get('/api/presets')).json(),selected=await api.get('/api/presets/selection?'+new URLSearchParams(catalog.defaults));assert.equal(selected.status,200,await selected.clone().text());const selection=await selected.json();
 assert.ok(selection.nativeProcessSettings);assert.ok(Object.hasOwn(selection.nativeProcessSettings,'compatible_printers'));
 const r=request();r.globalSettings={...selection.nativeProcessSettings,...selection.settings};const response=await api.post(r);assert.equal(response.status,200,await response.clone().text());const result=await response.json();assert.equal(result.settings[0].extruder,'2');assert.equal(result.settings[0].wall_loops,'5');assert.equal(result.settings[0].layer_height,String(selection.settings.layer_height));
});
