import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{createNativeAllPlatePreview}from'../../server/native-all-plate-preview.js';import{nativeAllPlateStatistics}from'../../shared/native-all-plate-statistics.js';
const sample=JSON.parse(await readFile(new URL('../fixtures/native-all-plate-input.json',import.meta.url)))[0].input.plates;
function setup(){const relation={version:1,source:'native-editor-project',projectHash:'a'.repeat(64),configHash:'b'.repeat(64),plates:[{id:'one',name:'One'},{id:'two',name:'Two'}]},jobs=new Map(sample.map((value,index)=>[`j${index}`,{id:`j${index}`,status:'ready',createdAt:`2026-09-27T01:0${index}:00Z`,engineVersion:'OrcaSlicer-2.4.2',nativePreviewContext:{version:1,index},nativePreviewProject:{...structuredClone(relation),plateId:index?'two':'one',extruders:value.extruders}}])),calls=[];let run=async(id,{signal})=>{if(signal?.aborted)throw Error('cancelled');const index=Number(id.slice(-1));return{...structuredClone(sample[index].data),workerIdentity:'engine',sourceSha256:id,vertices:Array(10).fill([1,2,3])};};const service=createNativeAllPlatePreview({jobStore:{get:id=>structuredClone(jobs.get(id)),list:()=>structuredClone([...jobs.values()])},preview:{get:async(id,options)=>{calls.push(id);return run(id,options);}}});return{service,jobs,calls,changeRun:value=>run=value};}
test('only complete matching owned project slices produce original native all-plate statistics',async()=>{const api=setup(),result=await api.service.get('j0');assert.equal(result.available,true);assert.equal(result.cost,nativeAllPlateStatistics(sample).cost);assert.deepEqual(result.plates.map(plate=>plate.jobId),['j0','j1']);assert.equal(result.vertices,undefined);assert.deepEqual(api.calls,['j0','j1']);});
test('unrelated geometry/config/engine versions, missing and failed plates never produce partial fabricated totals',async()=>{for(const change of[api=>api.jobs.delete('j1'),api=>api.jobs.get('j1').status='failed',api=>api.jobs.get('j1').nativePreviewProject.configHash='c'.repeat(64),api=>api.jobs.get('j1').nativePreviewProject.projectHash='d'.repeat(64),api=>api.jobs.get('j1').engineVersion='different']){const api=setup();change(api);const result=await api.service.get('j0');assert.equal(result.available,false);assert.equal(result.cost,undefined);assert.deepEqual(result.missingPlates,[{id:'two',name:'Two'}]);assert.equal(api.calls.length,0);}});
test('the viewed job anchors its own plate even when newer matching jobs exist',async()=>{const api=setup(),newer={...structuredClone(api.jobs.get('j0')),id:'new0',createdAt:'2026-10-01T00:00:00Z'};api.jobs.set(newer.id,newer);const result=await api.service.get('j0');assert.equal(result.plates[0].jobId,'j0');assert.deepEqual(api.calls,['j0','j1']);});
test('job deletion, changed context, changed extruder metadata and helper replacement reject in-flight aggregation',async()=>{for(const kind of['delete','context','extruders','worker']){const api=setup();api.changeRun(async id=>{const index=Number(id.slice(-1));if(id==='j1'){if(kind==='delete')api.jobs.delete('j0');if(kind==='context')api.jobs.get('j0').nativePreviewContext={changed:true};if(kind==='extruders')api.jobs.get('j0').nativePreviewProject.extruders=[2];}return{...structuredClone(sample[index].data),workerIdentity:kind==='worker'&&id==='j1'?'new':'engine',sourceSha256:id};});await assert.rejects(api.service.get('j0'),error=>[409,503].includes(error.status));}});
test('all-plate work serializes requests, honors cancellation and shutdown',async()=>{const api=setup();let start;const started=new Promise(resolve=>start=resolve);api.changeRun(async(_id,{signal})=>{start();return new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error('cancelled'),{status:499})),{once:true}));});const controller=new AbortController(),request=api.service.get('j0',{signal:controller.signal}),cancelled=assert.rejects(request,/cancelled/);await started;await assert.rejects(api.service.get('j0'),error=>error.status===429);controller.abort();await cancelled;api.service.shutdown();await assert.rejects(api.service.get('j0'),error=>error.status===503);});
test('legacy jobs remain explicitly unavailable and unknown/nonready jobs keep ownership boundaries',async()=>{const api=setup();delete api.jobs.get('j0').nativePreviewProject;assert.match((await api.service.get('j0')).reason,/older job/);await assert.rejects(api.service.get('missing'),error=>error.status===404);api.jobs.get('j1').status='queued';await assert.rejects(api.service.get('j1'),error=>error.status===409);});
test('whole-operation timeout aborts native processing across the complete project request',async()=>{const api=setup();let aborted=false;const store={get:id=>structuredClone(api.jobs.get(id)),list:()=>structuredClone([...api.jobs.values()])},service=createNativeAllPlatePreview({jobStore:store,timeoutMs:15,preview:{get:async(_id,{signal})=>new Promise((resolve,reject)=>{const keepAlive=setTimeout(resolve,1000);signal.addEventListener('abort',()=>{aborted=true;clearTimeout(keepAlive);reject(new Error('cancelled native work'));},{once:true});})}});await assert.rejects(service.get('j0'),error=>error.status===503&&/timed out/.test(error.message));assert.equal(aborted,true);service.shutdown();});
