import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import {once} from 'node:events';
import {createNativeArrangementService} from '../../server/native-arrangement.js';import {towerProject,towerSettings} from '../fixtures/native-prime-tower-input.js';import {readFile} from 'node:fs/promises';
const reference=JSON.parse(await readFile(new URL('../fixtures/native-prime-tower-reference.json',import.meta.url)));
const replay=()=>({format:'orca-native-prime-tower',version:1,sourceRevision:reference.sourceCommit,plateId:'plate-1',...structuredClone(reference.cases[0].expected)});
async function setup(t,{wait=false,invalid=false,fail=false}={}){const seen={};let resolveEntered;seen.entered=new Promise(r=>resolveEntered=r);const service=createNativeArrangementService({projects:{prepareGeometry:async(request,options)=>{seen.project=request;seen.options=options;return{project:towerProject(),settings:{...towerSettings,layer_height:'.4'},effectiveSettings:towerSettings,warnings:[]};}},worker:{identity:async()=>({metadata:{}}),shutdown:async()=>{},process:async(bytes,{signal})=>{seen.native=JSON.parse(bytes);resolveEntered();if(fail)throw Object.assign(new Error('Tower helper unavailable'),{status:503});if(wait)await new Promise((resolve,reject)=>signal.addEventListener('abort',()=>{seen.aborted=true;reject(Object.assign(new Error('Cancelled'),{name:'AbortError'}));},{once:true}));return{...replay(),...(invalid&&{plateId:'wrong'})};}}});const app=express();app.use('/api/geometry',service.router);const server=app.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{await service.close();server.closeAllConnections();await new Promise(r=>server.close(r));});return{service,seen,url:`http://127.0.0.1:${server.address().port}/api/geometry/prime-tower`};}
const post=(url,signal)=>fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectRequest:{project:towerProject(),allPlates:false},objects:[],extruders:[99],contained:true,filamentCount:100}),signal});
test('tower route resolves complete geometry and effective presets, ignoring browser-supplied native counts',async t=>{const api=await setup(t),response=await post(api.url);assert.equal(response.status,200);assert.equal(api.seen.project.allPlates,true);assert.equal(api.seen.options.allowEmptyGeometry,true);assert.equal(api.seen.native.settings.layer_height,'.2'.replace(/^\./,'0.'));assert.equal(api.seen.native.filamentCount,3);assert.equal(api.seen.native.objects.length,2);assert.equal('extruders'in api.seen.native,false);assert.equal((await response.json()).result.visible,true);await api.service.close();assert.equal((await post(api.url)).status,503);});
test('tower route rejects wrong response identity and reports unavailability without fabricated geometry',async t=>{const bad=await setup(t,{invalid:true});assert.equal((await post(bad.url)).status,400);const absent=await setup(t,{fail:true}),r=await post(absent.url);assert.equal(r.status,503);assert.match((await r.json()).error,/unavailable/);});
test('tower disconnect aborts the native request and shutdown aborts remaining work',async t=>{const api=await setup(t,{wait:true}),controller=new AbortController(),pending=post(api.url,controller.signal);await api.seen.entered;controller.abort();await assert.rejects(pending,/abort/i);for(let i=0;i<50&&!api.seen.aborted;i++)await new Promise(r=>setTimeout(r,5));assert.equal(api.seen.aborted,true);const shutdown=await setup(t,{wait:true}),request=post(shutdown.url);await shutdown.seen.entered;await shutdown.service.close();assert.equal((await request).status,499);assert.equal(shutdown.seen.aborted,true);});
