import {createPresetCatalog} from '../../server/presets.js';
import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,writeFile,rm}from'node:fs/promises';import path from'node:path';import{tmpdir}from'node:os';import{createApp}from'../../server/app.js';import{NATIVE_CONFIG_REVISION}from'../../server/native-config.js';
test('contextual preset reads share app shutdown cancellation and preserve the service status',{timeout:15000},async t=>{
 const dataDir=await mkdtemp(path.join(tmpdir(),'orca-editor-lifecycle-')),workerPath=path.join(dataDir,'worker');await writeFile(workerPath,'identity');let entered,aborted=false;const ready=new Promise(resolve=>entered=resolve);
 const runNative=async(_binary,args,{signal})=>{if(args[0]==='--version')return`OrcaConfigWorker-2.4.2 revision${NATIVE_CONFIG_REVISION}`;entered();await new Promise((resolve,reject)=>signal.addEventListener('abort',()=>{aborted=true;reject(signal.reason)},{once:true}));};
 const app=await createApp({dataDir,binary:path.resolve('tests/fixtures/fake-slicer.sh'),profilesDir:path.resolve('tests/fixtures/presets'),nativeConfiguration:{workerPath,runNative}}),server=app.listen(0,'127.0.0.1');await new Promise((resolve,reject)=>{server.once('listening',resolve);server.once('error',reject)});t.after(async()=>{await app.locals.shutdown();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await rm(dataDir,{recursive:true,force:true});});
 const base=`http://127.0.0.1:${server.address().port}`,ids=(await createPresetCatalog({profilesDir:path.resolve('tests/fixtures/presets')})).list().defaults,endpoint=`${base}/api/presets/custom/source/filament/${encodeURIComponent(ids.filamentId)}/context`;
 const pending=fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({selection:ids})});await ready;await app.locals.shutdown();const response=await pending;assert.equal(aborted,true);assert.equal(response.status,503);assert.match((await response.json()).error,/shutting down/);
});
