import test from'node:test';import assert from'node:assert/strict';import express from'express';
import{prepareMultiPatternFixture,multiPatternRequest}from'../fixtures/pa-pattern-multiplate.js';import{createCalibrationSessions}from'../../server/calibration-sessions.js';import{importNative3MF}from'../../shared/native-project.js';
async function setup(t){const fixture=await prepareMultiPatternFixture();let time=100;const sessions=createCalibrationSessions({catalog:fixture.catalog,prepareModel:async()=>fixture.prepared,now:()=>time,ttlMs:100}),app=express();app.use('/api/calibrations',sessions.router);app.use((error,req,res,next)=>res.status(error.status||500).json({error:error.message}));const server=app.listen(0,'127.0.0.1');await new Promise((resolve,reject)=>{server.once('listening',resolve);server.once('error',reject)});t.after(async()=>{await sessions.shutdown();await new Promise(resolve=>server.close(resolve))});const post=(route,body)=>fetch(`http://127.0.0.1:${server.address().port}/api/calibrations/${route}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),response=await post('prepare',{...multiPatternRequest,...fixture.ids}),prepared=await response.json();assert.equal(response.status,200,JSON.stringify(prepared));return{...fixture,prepared,sessions,post,expire:()=>time=201,body:{calibration:prepared.calibration,ids:fixture.ids,objects:prepared.objects}};}
test('multi-plate token validates the whole unchanged scene before selecting each trusted native archive',async t=>{const {prepared,body,sessions}=await setup(t);assert.equal(prepared.plates.length,2);assert.equal(prepared.nativeProject,undefined);await assert.rejects(sessions.validateProject(body),/Select a generated/);for(const [i,plate]of prepared.plates.entries()){const valid=await sessions.validateProject({...body,plateId:plate.id});assert.equal(valid.summary.plateId,plate.id);assert.equal(valid.plan.patternPlateId,plate.id);assert.equal(valid.plan.paPatterns.length,i?2:6);assert.equal(importNative3MF(valid.bytes).plates.length,1);}
 for(const change of[o=>o.at(-1).position[0]++,o=>o.at(-1).plateId='plate-1',o=>o.at(-1).native.objectSettings.outer_wall_speed='99',o=>o.pop()]){const objects=structuredClone(body.objects);change(objects);await assert.rejects(sessions.validateProject({...body,objects,plateId:'plate-1'}),/changed/);}await assert.rejects(sessions.validateProject({...body,plateId:'unknown'}),/plate is missing/);
});
test('full native export retains all generated plates while selected export contains only its complete four layers',async t=>{const {body,post}=await setup(t);for(const [allPlates,count,objects]of[[true,2,8],[false,1,2]]){const response=await post('project',{...body,plateId:'plate-2',allPlates});assert.equal(response.status,200,await response.clone().text());const archive=importNative3MF(new Uint8Array(await response.arrayBuffer()));assert.equal(archive.plates.length,count);assert.equal(archive.objects.length,objects);assert.ok(archive.plates.every(plate=>plate.layerEvents.items.length===4));}assert.equal((await post('project',{...body,allPlates:'true'})).status,400);assert.equal((await post('project',{...body,plateId:'unknown'})).status,409);const legacy=await post('project',body);assert.equal(importNative3MF(new Uint8Array(await legacy.arrayBuffer())).plates.length,2);
});
test('unknown, expired and altered-preset multi-plate requests never yield cached bytes',async t=>{const {body,post,expire}=await setup(t);for(const patch of[{calibration:{...body.calibration,token:'f'.repeat(64)}},{ids:{...body.ids,printerId:'changed'}},{calibration:{...body.calibration,speeds:[80]}}])assert.equal((await post('project',{...body,...patch,plateId:'plate-2',allPlates:false})).status,409);expire();const response=await post('project',{...body,plateId:'plate-2',allPlates:false});assert.equal(response.status,409);assert.match((await response.json()).error,/expired.*Regenerate/);});
