import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,rm,readFile}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';
import{createApp}from'../../server/app.js';import{writeCompatibilityCatalog}from'../fixtures/compatibility-catalog.js';
async function fixture(t){const root=await mkdtemp(path.join(tmpdir(),'orca-compat-api-'));await writeCompatibilityCatalog(path.join(root,'profiles'));const runtime=await createApp({dataDir:path.join(root,'data'),profilesDir:path.join(root,'profiles'),binary:path.resolve('tests/fixtures/fake-slicer.sh')});const server=runtime.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(async()=>{await runtime.locals.shutdown();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await rm(root,{recursive:true,force:true});});const origin=`http://127.0.0.1:${server.address().port}`;return{runtime,origin,get:async url=>{const response=await fetch(origin+url);assert.equal(response.status,200,await response.clone().text());return response.json();}};}
test('HTTP catalog evaluates printer/process expressions, library exclusion and native warnings',{timeout:30000},async t=>{const{get}=await fixture(t),all=await get('/api/presets'),printer=all.printers.find(value=>value.name==='Test Printer A'),a=await get(`/api/presets?printerId=${printer.id}`);assert.ok(a.processes.some(value=>value.name==='Native expression A'));assert.ok(!a.filaments.some(value=>value.name==='Generic PLA'));assert.ok(a.filaments.some(value=>value.name==='Generic PLA @Test A'));assert.ok(a.warnings.some(value=>value.includes('expression error in Native warning material A')));const fine=a.processes.find(value=>value.name==='Test Fine A'),fineChoices=await get(`/api/presets?printerId=${printer.id}&processId=${fine.id}`);assert.ok(fineChoices.filaments.some(value=>value.name==='Fine process material A'));const standard=a.processes.find(value=>value.name==='Test Standard A'),standardChoices=await get(`/api/presets?printerId=${printer.id}&processId=${standard.id}`);assert.ok(!standardChoices.filaments.some(value=>value.name==='Fine process material A'));const b=all.printers.find(value=>value.name==='Test Printer B'),bChoices=await get(`/api/presets?printerId=${b.id}`);assert.ok(!bChoices.processes.some(value=>value.name==='Native expression A'));assert.ok(bChoices.filaments.some(value=>value.name==='Generic PLA'));});
test('HTTP configuration and slicing reject an expression selection after hardware becomes incompatible',{timeout:30000},async t=>{const{get,origin,runtime}=await fixture(t),all=await get('/api/presets'),printer=all.printers.find(value=>value.name==='Test Printer A'),a=await get(`/api/presets?printerId=${printer.id}`),ids={...a.defaults,processId:a.processes.find(value=>value.name==='Native expression A').id};const okay=await get(`/api/presets/selection?${new URLSearchParams(ids)}`);assert.equal(okay.settings.layer_height,'0.18');
 const invalid=await fetch(origin+'/api/presets/configuration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({selection:ids,overrides:{machine:{nozzle_diameter:['0.6']}}})});assert.equal(invalid.status,400);assert.match((await invalid.json()).error,/incompatible/);
 const form=new FormData();form.append('model',new Blob([await readFile('tests/fixtures/cube.stl')]),'model.stl');for(const[key,value]of Object.entries(ids))form.append(key,value);form.append('printerSettings',JSON.stringify({nozzle_diameter:['0.6']}));const response=await fetch(origin+'/api/jobs',{method:'POST',body:form});assert.equal(response.status,400);assert.match((await response.json()).error,/incompatible/);assert.equal((await get('/api/jobs')).length,0);
});
import {createPresetCatalog} from '../../server/presets.js';
import {createCustomPresetCatalog} from '../../server/custom-presets.js';
import {createNativeConfigurationService} from '../../server/native-config.js';
test('trusted catalog overlays use the same overridden compatibility in discovery and native admission',{timeout:30000},async t=>{
 const directory=await mkdtemp(path.join(tmpdir(),'orca-compat-overlay-'));t.after(()=>rm(directory,{recursive:true,force:true}));
 const base=await createPresetCatalog({profilesDir:path.resolve('tests/fixtures/presets')}),ids=base.list().defaults,overlay={...base,getPreset(id,type){const value=base.getPreset(id,type);return id===ids.processId?{...value,compatible_printers:[],compatible_printers_condition:'false'}:value;}},nativeConfig=createNativeConfigurationService(),catalog=await createCustomPresetCatalog({baseCatalog:overlay,dataDir:directory,nativeConfig});t.after(()=>catalog.close());
 const listing=await catalog.listResolved({printerId:ids.printerId});assert.ok(!listing.processes.some(value=>value.id===ids.processId));await assert.rejects(nativeConfig.resolveCatalogNativeSettings({catalog,selection:ids}),/incompatible/);
});
