import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createApp, defaultBinary } from '../../server/app.js';
import { createPresetCatalog } from '../../server/presets.js';
import { runSlicer } from '../../server/slicer.js';

// These acceptance tests require a real engine and installed system presets.
// They test native file loading/slicing, not web project editing or viewport parity.
async function setup(t) {
  const directory = await mkdtemp(path.join(tmpdir(), 'orca-native-formats-'));
  let app, server;
  t.after(async () => {
    try {
      if (app) await app.locals.shutdown();
      if (server) await new Promise(resolve => server.close(resolve));
    } finally { await rm(directory, { recursive: true, force: true }); }
  });
  const binary = process.env.ORCA_SLICER_BIN || defaultBinary;
  const catalog = await createPresetCatalog({ binary });
  const defaults = catalog.list().defaults;
  assert.ok(defaults.printerId && defaults.processId && defaults.filamentId);
  const dataDir = path.join(directory, 'data');
  app = await createApp({ dataDir, binary, catalog, sliceTimeoutMs: 60000 });
  server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const healthResponse = await fetch(`${base}/api/health`);
  const health = await healthResponse.json();
  assert.equal(healthResponse.status, 200, JSON.stringify(health));
  assert.match(health.engine.version, /OrcaSlicer-\d+\.\d+/);
  return { app, base, binary, catalog, defaults, directory, dataDir };
}

async function uploadAndWait(context, filename, geometry) {
  const form = new FormData();
  for (const [key, value] of Object.entries(context.defaults)) form.set(key, value);
  form.set('settings', '{}');
  form.set('model', new Blob([geometry]), filename);
  const response = await fetch(`${context.base}/api/jobs`, { method: 'POST', body: form });
  const created = await response.json();
  assert.equal(response.status, 202, created.error);
  const deadline = Date.now() + 65000;
  let job;
  do {
    job = await (await fetch(`${context.base}/api/jobs/${created.id}`)).json();
    if (['ready', 'failed'].includes(job.status)) break;
    await new Promise(resolve => setTimeout(resolve, 100));
  } while (Date.now() < deadline);
  assert.ok(['ready', 'failed'].includes(job.status), `Job did not finish: ${JSON.stringify(job)}`);
  await context.app.locals.waitForIdle();
  assert.deepEqual(await readdir(path.join(context.dataDir, 'uploads')), []);
  assert.deepEqual(await readdir(path.join(context.dataDir, 'work')), []);
  assert.equal((await readdir(path.join(context.dataDir, 'jobs'))).some(name => name.startsWith('.slice-')), false);
  return job;
}

async function assertNativeToolpaths(context, job) {
  assert.equal(job.status, 'ready', job.error);
  const response = await fetch(`${context.base}/api/jobs/${job.id}/download`);
  assert.equal(response.status, 200);
  const gcode = await response.text();
  assert.match(gcode, /generated by OrcaSlicer/i);
  assert.match(gcode, /^G1 .*E[0-9]/m);
  assert.ok(gcode.length > 10000, 'Expected genuine toolpaths, not a fixture stub');
  assert.ok(gcode.includes(job.printer));
  assert.ok(gcode.includes(job.filament));
  assert.ok(gcode.includes(`layer_height = ${job.settings.layer_height}`));
}

test('real OrcaSlicer exports a 3MF and loads/slices it through the API', { timeout: 120000 }, async t => {
  const context = await setup(t);
  const fixtureDirectory = path.join(context.directory, 'fixture-export');
  const configDirectory = path.join(fixtureDirectory, 'config');
  await mkdir(configDirectory, { recursive: true });
  const configs = context.catalog.resolveSelection(context.defaults);
  for (const [type, config] of Object.entries(configs)) await writeFile(path.join(fixtureDirectory, `${type}.json`), JSON.stringify(config));
  const stl = await readFile(new URL('../fixtures/cube.stl', import.meta.url));
  const input = path.join(fixtureDirectory, 'cube.stl');
  await writeFile(input, stl);
  const project = path.join(fixtureDirectory, 'cube.3mf');
  const args = [
    '--datadir', configDirectory,
    '--load-settings', `${path.join(fixtureDirectory, 'printer.json')};${path.join(fixtureDirectory, 'process.json')}`,
    '--load-filaments', path.join(fixtureDirectory, 'filament.json'),
    '--export-3mf', project, input
  ];
  await runSlicer(context.binary, args, { cwd: fixtureDirectory, timeoutMs: 60000, signal: t.signal });
  const geometry = await readFile(project);
  assert.equal(geometry.subarray(0, 2).toString(), 'PK', 'Native export must be a ZIP-based 3MF');
  assert.ok(geometry.length > 1000, 'Native 3MF must contain geometry and settings');
  const job = await uploadAndWait(context, 'native-cube.3mf', geometry);
  await assertNativeToolpaths(context, job);
});

