import express from 'express';import{execFile}from'node:child_process';import{promisify}from'node:util';import path from 'node:path';import {fileURLToPath}from'node:url';import {access,stat}from'node:fs/promises';import{constants}from'node:fs';import {createNativeEmbossWorker,EMBOSS_WORKER_VERSION,EMBOSS_WORKER_COMMIT,EMBOSS_WORKER_LIMITS}from'./native-emboss-worker.js';import{createNativeFontResolver}from'./native-fonts.js';
const defaultBinary=fileURLToPath(new URL('../native/build/emboss/orca-emboss-worker',import.meta.url));
export function createNativeTextService({fontService,binary=process.env.ORCA_EMBOSS_WORKER_BIN||defaultBinary,systemDirectories,timeoutMs=30000}={}){
 const router=express.Router(),fonts=createNativeFontResolver({fontService,...(systemDirectories&&{systemDirectories})}),worker=createNativeEmbossWorker({binary,resolveFont:id=>fonts.resolve(id),timeoutMs});const metadata=new Map();
 let probe;async function available(){try{await access(binary,constants.X_OK);const info=await stat(binary),key=`${info.size}:${info.mtimeMs}`;if(probe?.key===key)return probe.available;const{stdout}=await promisify(execFile)(binary,['--version'],{timeout:3000,killSignal:'SIGKILL',maxBuffer:4096,windowsHide:true});const valid=stdout.trim()===`OrcaWeb native emboss worker ${EMBOSS_WORKER_VERSION} ${EMBOSS_WORKER_COMMIT}`;let perGlyph=false,svg=false;if(valid){try{const extra=await promisify(execFile)(binary,['--capabilities'],{timeout:3000,killSignal:'SIGKILL',maxBuffer:4096,windowsHide:true}),features=JSON.parse(extra.stdout);perGlyph=features.nativeVersion===EMBOSS_WORKER_VERSION&&features.commit===EMBOSS_WORKER_COMMIT&&features.perGlyph===true;svg=features.nativeVersion===EMBOSS_WORKER_VERSION&&features.commit===EMBOSS_WORKER_COMMIT&&features.svg===true;}catch{}}probe={key,available:valid,perGlyph,svg};return valid;}catch{return false;}}
 const handle=fn=>async(req,res)=>{const controller=new AbortController();res.on('close',()=>{if(!res.writableEnded)controller.abort();});try{await fn(req,res,controller.signal);}catch(error){if(!res.destroyed)res.status(error.name==='AbortError'?499:/deadline|queue is full/.test(error.message)?503:400).json({error:error.message});}};
 router.get('/capabilities',handle(async(req,res)=>{const ready=await available();res.json({available:ready,nativeVersion:EMBOSS_WORKER_VERSION,commit:EMBOSS_WORKER_COMMIT,planar:ready,surface:ready,perGlyph:ready&&probe?.perGlyph===true,svg:ready&&probe?.svg===true,limits:EMBOSS_WORKER_LIMITS,...(!ready&&{error:'Build the native text helper with npm run build:native:emboss, or configure ORCA_EMBOSS_WORKER_BIN.'})});}));
 router.get('/fonts',handle(async(req,res)=>res.json({fonts:await fonts.list()})));
 router.get('/fonts/:id/metadata',handle(async(req,res,signal)=>{const font=await fonts.resolve(req.params.id),key=`${font.id}:${font.bytes}:${font.mtimeMs}`;let info=metadata.get(key);if(!info){info=await worker.fontInfo({fontId:font.id,signal});if(metadata.size>=128)metadata.delete(metadata.keys().next().value);metadata.set(key,info);}res.json({...info,font:{id:font.id,name:font.name,source:font.source,fileName:path.basename(font.filename)}});}));
 router.post('/generate',express.json({limit:'32mb'}),handle(async(req,res,signal)=>{if(!await available())throw new Error('Native text helper is unavailable. Run npm run build:native:emboss or configure ORCA_EMBOSS_WORKER_BIN.');const {fontId,request}=req.body||{};res.json(await worker.generate(request,{fontId,signal}));}));
 router.post('/svg/generate',express.json({limit:'32mb'}),handle(async(req,res,signal)=>{if(!await available()||!probe?.svg)throw new Error('Native SVG helper is unavailable. Rebuild with npm run build:native:emboss.');res.json(await worker.generateSvg(req.body?.request,{signal}));}));
 return{router,worker,fonts,close:()=>worker.close()};
}
