import useProjectEdits from "./useProjectEdits.js";
import useModelTransforms from "./useModelTransforms.js";
import useObjectTreeActions from "./useObjectTreeActions.js";
import useModelClipboard from "./useModelClipboard.js";
import { readJson } from "../lib/http.js";
import useSettingsClipboard from "./useSettingsClipboard.js";
import { processClipboardAvailability } from "../../shared/native-settings-clipboard.js";
import { nativePasteAvailability } from "../../shared/native-clipboard.js";
import useGeometryActions from "./useGeometryActions.js";
import usePresetActions from "./usePresetActions.js";
import useSessionLifecycle from "./useSessionLifecycle.js";
import usePrintSettings from "./usePrintSettings.js";
import useProjectFiles from "./useProjectFiles.js";
import useSlicing from "./useSlicing.js";
import useProjectExport from "./useProjectExport.js";
import { useEffect } from "react";
import usePlateActions from "./usePlateActions.js";
import useKeyboardCommands from "./useKeyboardCommands.js";
import useApplicationMenus from "./useApplicationMenus.js";
export default function useWorkspaceActions({
  status,
  toolState,
  session,
  projectState,
  files,
  selection,
  presets,
  settings,
  appearance,
  emptyCatalog,
  accepted,
  saveBlob,
}) {
  const { dirty, canSlice, pending } = status;
  const {
    setUnsavedAction,
    transformScope,
    selectionAnchor,
    setPrimeTowerSelected,
    setPrimeTowerDragLayout,
    setTreeRangeIndex,
    setHeightRangesOpen,
    setTreeEditorScope,
    setPartsEditorOpen,
    setPaintingChannel,
    setVariableLayersOpen,
    setListClipboard,
    setModelClipboard,
    setCutClipboardDialog,
    cutClipboardDialog,
    modelClipboard,
    setClipboardTask,
    clipboardRequest,
    setClipboardBusy,
    arrangeOptions,
    listClipboard,
    setCutOpen,
    setNativeTextAction,
    nativeTextAction,
    profileEditor,
    setProfileEditor,
    setFilamentError,
    theme,
    settingsCorrections,
    setSettingsCorrections,
    importOptions,
    arranging,
    arrangeController,
    setArranging,
    setArrangeOptions,
    setArrangeOpen,
    setCameraCommand,
    keyboardContext,
    filamentSequence,
    arrowGesture,
    menu,
    setMenu,
    setHelp,
    setCloneOpen,
    setMode,
    primeTowerSelected,
    setTextOpen,
    setBrimOpen,
    cameraFrame,
    setWireframe,
    setTheme,
    setCalibrationOpen,
    setCalibrationResultOpen,
  } = toolState;
  const {
    setJob,
    submitGeneration,
    setError,
    importGeneration,
    setRecovery,
    setNotice,
    catalogRequest,
    selectionRequest,
    catalogPrinter,
    setHealth,
    mounted,
    importRequest,
    job,
    recovery,
    saved,
    setJobs,
    projectInput,
    modelInput,
  } = session;
  const {
    update,
    replace,
    ids,
    project,
    projectRef,
    overrides,
    undo,
    redo,
    canUndo,
    canRedo,
  } = projectState;
  const {
    setImporting,
    setPage,
    recentFiles,
    projectLoadPreferences,
    setProjectLoadDialog,
    setMultipartImport,
    setZeroVolumeImport,
    setSubmitting,
    page,
  } = files;
  const {
    selectionIds,
    multiple,
    activeObjects,
    selected,
    bed,
    visibleObjects,
    transformObject,
  } = selection;
  const {
    resolved,
    setCatalogPending,
    setResolved,
    setCatalog,
    setCatalogRevision,
    catalogPending,
    catalog,
    setSelectionPending,
    catalogRevision,
  } = presets;
  const { displayedSelection, settingsState } = settings;
  const { setPreferencesOpen } = appearance;
  const { requestDiscard, clearResult, edit, createCalibration } =
    useProjectEdits({
      dirty,
      setUnsavedAction,
      setJob,
      submitGeneration,
      update,
      setError,
      importGeneration,
      setImporting,
      replace,
      ids,
      setRecovery,
      setPage,
      setNotice,
    });
  const {
    chooseSelection,
    selectCanvas,
    selectRectangle,
    selectAll,
    deselectAll,
    changeSelected,
    transform,
    mutateSelected,
    deleteSelected,
    centerSelected,
    dropSelected,
    mirrorSelected,
  } = useModelTransforms({
    update,
    transformScope,
    setError,
    selectionIds,
    multiple,
    selectionAnchor,
    activeObjects,
    setPrimeTowerSelected,
    setPrimeTowerDragLayout,
    selected,
    edit,
    project,
    bed,
    setNotice,
  });
  const {
    selectTreeNode,
    selectTreeInstance,
    treeSettings,
    resetTreeSettings,
    treeVisibility,
    treePrintability,
    treePainting,
    treeVariableLayers,
  } = useObjectTreeActions({
    update,
    setError,
    projectRef,
    setTreeRangeIndex,
    setHeightRangesOpen,
    setTreeEditorScope,
    setPartsEditorOpen,
    edit,
    resolved,
    overrides,
    setPaintingChannel,
    setVariableLayersOpen,
  });
  const {
    cutModels,
    resolveCutClipboard,
    copyModels,
    pasteModels,
    duplicateSelected,
    cloneModels,
    fillBed,
  } = useModelClipboard({
    projectRef,
    setListClipboard,
    setModelClipboard,
    bed,
    setCutClipboardDialog,
    edit,
    setNotice,
    setError,
    cutClipboardDialog,
    modelClipboard,
    setClipboardTask,
    clipboardRequest,
    setClipboardBusy,
    readJson,
    arrange: (options) => arrange(options),
    arrangeOptions,
  });
  const { copyProcessSettings, pasteProcessSettings, pasteCopiedLayers } =
    useSettingsClipboard({
      projectRef,
      project,
      setListClipboard,
      setNotice,
      setError,
      clipboardRequest,
      listClipboard,
      resolved,
      overrides,
      setClipboardTask,
      setClipboardBusy,
      readJson,
      edit,
    });
  function pasteClipboardUnavailable() {
    return listClipboard.type === "process"
      ? processClipboardAvailability(project, listClipboard.process)
      : listClipboard.type === "layers"
        ? !selected
          ? "Select an object"
          : null
        : nativePasteAvailability(project, modelClipboard);
  }
  function pasteFromClipboard() {
    if (listClipboard.type === "process") void pasteProcessSettings();
    else if (listClipboard.type === "layers") pasteCopiedLayers();
    else
      pasteModels().catch((cause) => {
        if (cause.name !== "AbortError") setError(cause.message);
      });
  }
  const {
    applyCut,
    replaceGeometry,
    applyTopologyChange,
    confirmNativeTextLoss,
    splitSelected,
    disassembleSelected,
    assemblePlate,
    repairSelected,
  } = useGeometryActions({
    edit,
    setCutOpen,
    setNotice,
    project,
    selected,
    setNativeTextAction,
    projectRef,
    nativeTextAction,
    setError,
    multiple,
    visibleObjects,
  });
  const {
    loadCatalog,
    changePreset,
    useInstalledPresets,
    savedPreset,
    editFilaments,
    changeFilamentSlot,
  } = usePresetActions({
    catalogRequest,
    selectionRequest,
    catalogPrinter,
    setCatalogPending,
    setResolved,
    setError,
    readJson,
    projectRef,
    setCatalog,
    emptyCatalog,
    setCatalogRevision,
    replace,
    setRecovery,
    setNotice,
    update,
    clearResult,
    edit,
    ids,
    profileEditor,
    setProfileEditor,
    project,
    setFilamentError,
  });
  useSessionLifecycle({
    setHealth,
    setRecovery,
    setNotice,
    loadCatalog,
    mounted,
    importGeneration,
    importRequest,
    catalogRequest,
    selectionRequest,
    catalogPending,
    ids,
    catalogPrinter,
    catalog,
    project,
    setSelectionPending,
    setResolved,
    setError,
    catalogRevision,
    job,
    setJob,
    recovery,
    theme,
  });
  const {
    changeProjectSettings,
    changeSetting,
    applySettingsCorrections,
    resetSetting,
    resetSettings,
  } = usePrintSettings({
    edit,
    resolved,
    overrides,
    project,
    setError,
    settingsCorrections,
    displayedSelection,
    settingsState,
    setSettingsCorrections,
  });
  const {
    beginImport,
    cancelImport,
    restoreProject,
    restoreRecoveryProject,
    choose,
    routeProjectFile,
    openProject,
    applyProjectLoad,
    askMultipartImport,
    acknowledgeZeroVolumeImport,
    readStructuredGeometry,
    addProjectGeometry,
    openGeometryProject,
    loadProjectGeometry,
    importProject,
    openRecentFile,
  } = useProjectFiles({
    importRequest,
    importGeneration,
    setImporting,
    setError,
    loadCatalog,
    clearResult,
    saved,
    setPage,
    recovery,
    accepted,
    bed,
    importOptions,
    projectRef,
    edit,
    recentFiles,
    setNotice,
    projectLoadPreferences,
    setProjectLoadDialog,
    requestDiscard,
    setMultipartImport,
    setZeroVolumeImport,
    readJson,
    resolved,
    replace,
    project,
    dirty,
    setUnsavedAction,
  });
  const { previewSupports, submit, refreshJobs, cancelJob, deleteJob } =
    useSlicing({
      projectRef,
      canSlice,
      settingsState,
      project,
      setSettingsCorrections,
      setError,
      setSubmitting,
      submitGeneration,
      ids,
      setJob,
      setPage,
      visibleObjects,
      update,
      setNotice,
      overrides,
      setJobs,
      job,
    });
  const { exportModel, saveProject } = useProjectExport({
    project,
    saveBlob,
    visibleObjects,
    setError,
    recentFiles,
    saved,
    setNotice,
  });
  useEffect(() => {
    if (page === "Project") refreshJobs();
  }, [page]);
  const { newProject, addPlate, arrange, switchPlate, undoEdit, redoEdit } =
    usePlateActions({
      setRecovery,
      cancelImport,
      catalogRequest,
      setCatalogPending,
      ids,
      replace,
      clearResult,
      setError,
      setNotice,
      saved,
      setPage,
      edit,
      arrangeOptions,
      arranging,
      projectRef,
      arrangeController,
      setArranging,
      setArrangeOptions,
      setArrangeOpen,
      setCameraCommand,
      undo,
      redo,
    });
  useKeyboardCommands({
    keyboardContext,
    page,
    pending,
    projectRef,
    edit,
    filamentSequence,
    arrowGesture,
    menu,
    setMenu,
    setPreferencesOpen,
    selected,
    requestDiscard,
    newProject,
    projectInput,
    modelInput,
    saveProject,
    canSlice,
    submit,
    job,
    setHelp,
    cutModels,
    copyModels,
    pasteClipboardUnavailable,
    pasteFromClipboard,
    setCloneOpen,
    canUndo,
    undoEdit,
    canRedo,
    redoEdit,
    selectAll,
    setMode,
    deselectAll,
    project,
    deleteSelected,
    primeTowerSelected,
    multiple,
    setCutOpen,
    setTextOpen,
    setBrimOpen,
    setPaintingChannel,
    transformObject,
    cameraFrame,
    selectionIds,
    changeSelected,
    setCameraCommand,
  });
  const { menus } = useApplicationMenus({
    requestDiscard,
    newProject,
    modelInput,
    projectInput,
    saveProject,
    exportModel,
    undoEdit,
    canUndo,
    redoEdit,
    canRedo,
    cutModels,
    selected,
    pending,
    copyModels,
    pasteFromClipboard,
    pasteClipboardUnavailable,
    copyProcessSettings,
    multiple,
    pasteProcessSettings,
    listClipboard,
    project,
    setCloneOpen,
    duplicateSelected,
    deleteSelected,
    edit,
    setMode,
    selectAll,
    activeObjects,
    deselectAll,
    primeTowerSelected,
    arrange,
    arranging,
    setPage,
    setWireframe,
    setTheme,
    setCalibrationOpen,
    resolved,
    setCalibrationResultOpen,
    setHelp,
  });
  return {
    requestDiscard,
    edit,
    createCalibration,
    selectCanvas,
    selectRectangle,
    selectAll,
    deselectAll,
    changeSelected,
    transform,
    deleteSelected,
    centerSelected,
    dropSelected,
    mirrorSelected,
    selectTreeNode,
    treeSettings,
    resetTreeSettings,
    treeVisibility,
    treePrintability,
    treePainting,
    treeVariableLayers,
    resolveCutClipboard,
    duplicateSelected,
    cloneModels,
    fillBed,
    applyCut,
    confirmNativeTextLoss,
    splitSelected,
    disassembleSelected,
    assemblePlate,
    repairSelected,
    changePreset,
    useInstalledPresets,
    savedPreset,
    editFilaments,
    changeFilamentSlot,
    changeProjectSettings,
    changeSetting,
    applySettingsCorrections,
    resetSetting,
    resetSettings,
    cancelImport,
    restoreRecoveryProject,
    choose,
    openProject,
    applyProjectLoad,
    openRecentFile,
    previewSupports,
    submit,
    refreshJobs,
    cancelJob,
    deleteJob,
    exportModel,
    saveProject,
    newProject,
    addPlate,
    arrange,
    switchPlate,
    undoEdit,
    redoEdit,
    menus,
  };
}
