import {invalidateNativeEmboss} from './native-emboss.js';
import{createDovetailPlan}from'./dovetail-plan.js';
import{cutMesh,nativeCutMembers}from'./geometry-cut.js';
import{analyzeMesh,createMesh,sceneBounds,meshBounds,transformPositions}from'./geometry.js';
import{cutInformationForParts,normalizeCutId}from'./cut-metadata.js';
const dot=(a,b)=>a.reduce((sum,x,i)=>sum+x*b[i],0),sub=(a,b)=>a.map((x,i)=>x-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
function intersects(a,b,positions){const d=sub(b,a);for(let i=0;i<positions.length;i+=9){const x=Array.from(positions.slice(i,i+3)),y=Array.from(positions.slice(i+3,i+6)),z=Array.from(positions.slice(i+6,i+9)),e1=sub(y,x),e2=sub(z,x),p=cross(d,e2),det=dot(e1,p);if(Math.abs(det)<1e-10)continue;const t=sub(a,x),u=dot(t,p)/det;if(u< -1e-8||u>1+1e-8)continue;const q=cross(t,e1),v=dot(d,q)/det,fraction=dot(e2,q)/det;if(v>=-1e-8&&u+v<=1+1e-8&&fraction>=-1e-8&&fraction<=1+1e-8)return true;}return false;}
function identity(){const n=new Uint32Array(2);crypto.getRandomValues(n);return((BigInt(n[0])<<32n)|BigInt(n[1])||1n).toString();}
function cloneBaked(object){const{painting,brimEars,text,assemblyParts,...metadata}=object;if(metadata.native){metadata.native=invalidateNativeEmboss(metadata.native);delete metadata.native.instanceFamily;}return createMesh({...metadata,id:undefined,positions:transformPositions(object),position:[0,0,0],rotation:[0,0,0],scale:[1,1,1],cutFrom:object.id,dovetailSourceId:object.dovetailSourceId||object.id,dovetailSourceName:object.dovetailSourceName||object.name});}
function clip(mesh,plane){const points=transformPositions(mesh);let min=Infinity,max=-Infinity;for(let i=0;i<points.length;i+=3){const distance=dot(Array.from(points.slice(i,i+3)),plane.normal)-plane.offset;min=Math.min(min,distance);max=Math.max(max,distance);}if(plane.keep==='upper'){if(max<=1e-5)return null;if(min>=-1e-5)return mesh;}else{if(min>=-1e-5)return null;if(max<=1e-5)return mesh;}return cutMesh(mesh,plane)[plane.keep];}
export function cutDovetailCells(mesh,plan,{budget={triangles:0}}={}){const cells=[];for(const cell of plan.cells){let fragment=cloneBaked(mesh);for(const plane of cell.planes){budget.triangles+=fragment.positions.length/9;if(budget.triangles>20000000)throw new Error('Dovetail preview work limit exceeded; reduce groove count or source complexity');fragment=clip(fragment,plane);if(!fragment)break;}if(fragment){const report=analyzeMesh(fragment);if(!report.manifold||report.volume<=1e-8)throw new Error('Dovetail produced a collapsed or non-manifold fragment; change the groove or repair the model');cells.push({...cell,mesh:fragment,volume:report.volume});}}return cells;}
/** Native leaves separate closed shells at internal cut interfaces. Keep those
 * fragments as volumes in the same object for native slicing union, preserving
 * processed connector identity instead of inventing an approximate Boolean. */
export function cutNativeGroupWithDovetail(objects,selectedId,options={}){
 if(options.connectors?.length)throw new Error('Dovetail cuts cannot add planar connectors');
 const members=nativeCutMembers(objects,selectedId),solids=members.filter(o=>(o.native?.partType||'normal_part')==='normal_part'),bounds=sceneBounds(solids.map(o=>({...o,visible:true}))),keep=options.keep||'both';if(!bounds||!['both','upper','lower'].includes(keep))throw new Error('Choose printable parts and retained cut sides');
 if(solids.some(o=>Object.keys(o.native?.partSettings||{}).length))throw new Error('Dovetail cutting does not yet support normal-part setting overrides; use object settings first');
 if(new Set(solids.map(o=>o.filamentSlot||1)).size>1)throw new Error('Dovetail cutting currently requires the same filament on all normal parts');
 if(solids.some(o=>!analyzeMesh(o).manifold))throw new Error('Dovetail cutting requires closed manifold source parts');
 if(solids.reduce((n,o)=>n+o.positions.length/9,0)>200000)throw new Error('Dovetail cutting currently supports at most 200,000 source triangles');
 const plan=createDovetailPlan({dovetail:options.dovetail,normal:options.normal||[0,0,1],offset:options.offset,center:bounds.center,radius:Math.hypot(...bounds.size)/2}),halves={upper:[],lower:[]},cells=[],budget={triangles:0};
 if(solids.reduce((sum,o)=>sum+o.positions.length/9,0)*plan.probes.length>8000000)throw new Error('Dovetail contour-check work limit exceeded; reduce groove count or source complexity');
 const solidPositions=solids.map(transformPositions);for(const [a,b]of plan.probes)if(!solidPositions.some(p=>intersects(a,b,p)))throw new Error('Dovetail groove boundary does not intersect the solid model; reduce width, depth, count, gap or angle');
 for(const object of solids)for(const cell of cutDovetailCells(object,plan,{budget})){halves[cell.side].push(cell.mesh);cells.push({...cell,meshId:cell.mesh.id});}
 for(const side of['upper','lower'])if(!halves[side].length)throw new Error('Dovetail must leave a printable body on both cut sides');
 for(let i=0;i<plan.parameters.count;i++)if(!cells.some(cell=>cell.kind==='tongue'&&cell.groove===i)||!cells.some(cell=>cell.side==='lower'&&cell.groove===i))throw new Error(`Dovetail groove ${i+1} does not intersect the model with a usable tongue and socket`);
 const existing=cutInformationForParts(members)?.cutId,cutId=keep==='both'?normalizeCutId({id:existing?.id||identity(),checkSum:(BigInt(existing?.checkSum||'1')+1n).toString(),connectorsCount:existing?.connectorsCount||'0'}):existing,originalName=members[0].native?.objectName||members[0].name,discarded=[];let resetLayerProfiles=0;
 for(const side of['upper','lower']){
  const groupId=halves[side][0].id,solidBounds=sceneBounds(halves[side].map(o=>({...o,visible:true})));
  const connectors=new Set();for(const object of halves[side])if(object.native?.cutConnector){if(connectors.has(object.dovetailSourceId))throw new Error('An existing connector crosses multiple dovetail cuts; change the cut plane or remove that connector first');connectors.add(object.dovetailSourceId);}
  for(const modifier of members.filter(o=>(o.native?.partType||'normal_part')!=='normal_part')){const b=meshBounds(modifier);if([0,1,2].every(a=>b.min[a]<=solidBounds.max[a]&&b.max[a]>=solidBounds.min[a]))halves[side].push(cloneBaked(modifier));else discarded.push(modifier.name);}
  halves[side]=halves[side].map((object,index)=>{const native={...structuredClone(object.native||{}),groupId,objectName:`${originalName} ${side}`,partType:object.native?.partType||'normal_part',objectSettings:structuredClone(members[0].native?.objectSettings||{}),partSettings:structuredClone(object.native?.partSettings||{})};delete native.groupTransform;if(native.layerHeightProfile?.length){native.layerHeightProfile=[];resetLayerProfiles++;}if(cutId)native.cutId={...cutId};return{...object,name:object.native?.cutConnector?object.dovetailSourceName:`${originalName} ${side} ${index+1}`,native,dovetailPlan:plan.parameters};});
 }
 const created=keep==='both'?[...halves.upper,...halves.lower]:halves[keep],replaceIds=members.map(o=>o.id),next=objects.filter(o=>!replaceIds.includes(o.id)).map(o=>cutId&&o.native?.cutId?.id===cutId.id?{...o,native:{...o.native,cutId:{...cutId}}}:o);
 if(created.length>10000||created.reduce((sum,o)=>sum+o.positions.length/9,0)>2000000)throw new Error('Dovetail cut exceeds the project geometry limit');
 return{objects:[...next,...created],created,replaceIds,...halves,report:{normal:plan.frame.normal,offset:options.offset,dovetail:plan.parameters,grooveWidth:plan.grooveWidth,source:plan.source,discarded,resetLayerProfiles,parts:cells.map(({mesh,planes,...cell})=>cell),volumeBefore:solids.reduce((s,o)=>s+analyzeMesh(o).volume,0),volumeAfter:cells.reduce((s,c)=>s+c.volume,0),...(cutId&&{cutFamilyUpdate:{...cutId}})}};
}
