import {inspectThumbnail} from './native-assets.js';
export const RECENT_DEFAULTS=Object.freeze({version:1,max_recent_count:18,recent_models:false});
export const RECENT_FILE_LIMIT=150*1024*1024;
export function recentLimit(text){if(!/^[+-]?\d+$/.test(String(text).trim())||!Number.isSafeInteger(Number(text)))return null;return Math.max(0,Math.min(999,Number(text)));}
export function normalizeRecentPreferences(value){if(value===undefined)return{...RECENT_DEFAULTS};if(!value||value.version!==1||!Number.isInteger(value.max_recent_count)||value.max_recent_count<0||value.max_recent_count>999||typeof value.recent_models!=='boolean')throw Error('Recent-file preferences are damaged.');return{version:1,max_recent_count:value.max_recent_count,recent_models:value.recent_models};}
export function recentEligible(name,kind,preferences){return kind==='project'?/\.(json|3mf)$/i.test(name):kind==='model'&&preferences.recent_models&&/\.(stl|step|stp)$/i.test(name);}
export function recentThumbnail(text){if(!text)return '';if(typeof text!=='string'||text.length>1400000||text.length%4||!/^[A-Za-z0-9+/]*={0,2}$/.test(text))throw Error('Invalid recent-file thumbnail.');const raw=atob(text);if(btoa(raw)!==text)throw Error('Invalid recent-file thumbnail.');inspectThumbnail(Uint8Array.from(raw,c=>c.charCodeAt(0)));return text;}
export function normalizeRecentEntry(value){if(!value||value.version!==1||!/^([a-f0-9]{64})$/.test(value.id)||typeof value.name!=='string'||!value.name||value.name.length>1024||/[\u0000-\u001f]/.test(value.name)||!['project','model'].includes(value.kind)||!Number.isSafeInteger(value.size)||value.size<1||value.size>RECENT_FILE_LIMIT||!Number.isSafeInteger(value.order)||value.order<1||!Number.isFinite(value.lastModified)||value.lastModified<0||value.lastModified>8640000000000000)throw Error('This recent-file entry is damaged.');return{version:1,id:value.id,name:value.name,kind:value.kind,size:value.size,order:value.order,lastModified:value.lastModified,thumbnail:recentThumbnail(value.thumbnail)};}
export function recentRows(values){const rows=[],invalid=[];for(const value of values){try{rows.push(normalizeRecentEntry(value));}catch{invalid.push(value?.id);}}rows.sort((a,b)=>b.order-a.order||a.id.localeCompare(b.id));return{rows,invalid};}
export function recentModifiedTime(value){if(!value)return 'Modification time unavailable';const date=new Date(value),p=n=>String(n).padStart(2,'0');return`${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())} ${p(date.getHours())}:${p(date.getMinutes())}:${p(date.getSeconds())}`;}
