#!/bin/sh
set -eu
outputdir='.'
input=''
while [ "$#" -gt 0 ]; do
  case "$1" in
    --outputdir) outputdir="$2"; shift 2 ;;
    --slice) shift 2 ;;
    --load-settings) shift 2 ;;
    *) input="$1"; shift ;;
  esac
done
printf '; generated by OrcaSlicer test adapter\n; source: %s\nG28\n' "$input" > "$outputdir/result.gcode"
