; Synthetic bounded source commands for real native-processor acceptance; not a slicer/GUI export.
; generated by OrcaSlicer 2.4.2
; filament_diameter: 1.75,2.85
; filament_density: 1.24,0.97
G90
M83
G92 X0 Y0 Z0 E0
;LAYER_CHANGE
; Z_HEIGHT: 0.2
;HEIGHT:0.2
G1 Z0.2 F600
T0
;TYPE:Outer wall
;WIDTH:0.4
G1 X10 E1 F1200
G1 Y10 E2
;TYPE:Support
G1 X0 E3
; WIPE_TOWER_START
;TYPE:Prime tower
G1 Y0 E4
; WIPE_TOWER_END
T1
;COLOR_CHANGE,T1,#123ABC
;TYPE:Outer wall
G1 X10 E1 F1800
; FLUSH_START
G1 E2 F1200
; FLUSH_END
;TYPE:Support
G1 Y10 E2 F1200
; WIPE_TOWER_START
;TYPE:Prime tower
G1 X0 E3
; WIPE_TOWER_END
;LAYER_CHANGE
; Z_HEIGHT: 0.4
;HEIGHT:0.2
G1 Z0.4
;PAUSE_PRINT
M400
;TYPE:Outer wall
G1 Y0 E1 F1200
