import React,{useEffect,useRef,useState}from'react';
import Modal from './Modal.jsx';
import './clone.css';
export default function CloneDialog({onClone,onClose,canAutoArrange=false,onFill}){
 const[count,setCount]=useState('1'),[arrange,setArrange]=useState(()=>{try{return localStorage.getItem('orca-web-clone-auto-arrange')==='true';}catch{return false;}}),[busy,setBusy]=useState(false),[action,setAction]=useState('clone'),[error,setError]=useState(''),[capability,setCapability]=useState(null);const request=useRef(),alive=useRef(true);
 useEffect(()=>{alive.current=true;const controller=new AbortController();fetch('/api/geometry/capabilities',{signal:controller.signal}).then(r=>r.json()).then(value=>{if(alive.current)setCapability(value);}).catch(cause=>{if(cause.name!=='AbortError'&&alive.current)setCapability({available:false,error:cause.message});});return()=>{alive.current=false;controller.abort();request.current?.abort();};},[]);
 function close(){request.current?.abort();onClose();}
 async function submit(event){event.preventDefault();setAction('clone');const copies=Number(count);if(!Number.isInteger(copies)||copies<1||copies>1000){setError('Number of copies must be an integer from 1 to 1000.');return;}setError('');setBusy(true);const controller=new AbortController();request.current=controller;try{await onClone({copies,autoArrange:canAutoArrange&&arrange,signal:controller.signal});if(alive.current&&!controller.signal.aborted)onClose();}catch(cause){if(alive.current&&cause.name!=='AbortError')setError(cause.message);}finally{if(alive.current)setBusy(false);}}
 async function fill(){if(!onFill)return;setAction('fill');setError('');setBusy(true);const controller=new AbortController();request.current=controller;try{await onFill({signal:controller.signal});if(alive.current&&!controller.signal.aborted)onClose();}catch(cause){if(alive.current&&cause.name!=='AbortError')setError(cause.message);}finally{if(alive.current)setBusy(false);}}
 const available=capability?.available===true;
 return <Modal className="clone-dialog" aria-label="Clone" onClose={close}><form onSubmit={submit}><header><h2>Clone</h2><button type="button" onClick={close} aria-label="Close Clone">×</button></header><label><span>Number of copies:</span><input autoFocus aria-label="Number of copies" type="number" min="1" max="1000" step="1" value={count} disabled={busy} onChange={e=>setCount(e.target.value)}/></label><label><span>Auto arrange plate after cloning</span><input aria-label="Auto arrange plate after cloning" type="checkbox" checked={arrange&&canAutoArrange} disabled={busy||!canAutoArrange} onChange={e=>{setArrange(e.target.checked);try{localStorage.setItem('orca-web-clone-auto-arrange',String(e.target.checked));}catch{}}}/></label>{!canAutoArrange&&<p>Auto arrange and Fill require the native arrangement integration.</p>}{capability&&!available&&<p role="alert">{capability.error||'The native placement helper is unavailable. Build it with npm run build:native:arrange.'}</p>}{error&&<p role="alert">{error}</p>}{busy&&<p role="status">{action==='fill'?'Filling the bed with native instances…':'Creating copies with native placement…'}<progress aria-label="Clone progress"/></p>}<footer><button type="button" disabled={busy||!onFill||!available} title={!onFill?'Native Fill integration is not available':undefined} onClick={fill}>Fill</button><button type="submit" disabled={busy||!available}>OK</button><button type="button" onClick={close}>Cancel</button></footer></form></Modal>;
}
