import NativeIcon from './NativeIcon.jsx';
import React from 'react';
import { filamentSlotCount, filamentColors } from '../shared/filament-slots.js';
export default function FilamentSlots({ project, options, pending, add, remove, changePreset, changeColor, error, onPurge, onEdit }) {
  const count = filamentSlotCount(project), colors = filamentColors(project);
  return <section className="filament-slots" aria-label="Project filaments"><div className="side-title"><b className="native-section-title"><NativeIcon name="filament"/>Filament{count>1?` (${count})`:""}</b><button aria-label="Add filament slot" onClick={add} disabled={pending || count>=64}>＋</button><button onClick={onPurge} disabled={pending || count<2}>Flush volumes</button></div>
    {Array.from({length:count},(_,index)=><div className="filament-slot" key={index}><span>{index+1}</span><input type="color" aria-label={`Filament ${index+1} color`} value={colors[index]} disabled={pending} onChange={event=>changeColor(index,event.target.value)}/>{project.useEmbeddedSettings?<select aria-label={index===0?"Filament":`Filament slot ${index+1}`} disabled value="embedded"><option value="embedded">{project.nativeSettings.filament_settings_id[index]}</option></select>:<select aria-label={index===0?"Filament":`Filament slot ${index+1}`} value={project.filamentIds?.[index]||project.ids.filamentId||''} disabled={pending} onChange={event=>changePreset(index,event.target.value)}>{!options.some(option=>option.id===(project.filamentIds?.[index]||project.ids.filamentId))&&<option value={project.filamentIds?.[index]||project.ids.filamentId||''}>Select a compatible filament</option>}{options.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select>}<button aria-label={index===0?"Edit filament preset":`Edit filament slot ${index+1} preset`} disabled={pending||project.useEmbeddedSettings} onClick={()=>onEdit?.(index)}>✎</button><button aria-label={`Remove filament slot ${index+1}`} onClick={()=>remove(index)} disabled={pending||count===1}>−</button></div>)}
    {project.useEmbeddedSettings&&<p>Added slots copy the first embedded filament. Use installed presets to choose other materials.</p>}{error&&<p role="alert">{error}</p>}
  </section>;
}
