import React,{useEffect,useRef}from'react';
export default function GcodeInspector({window:code,attributes}){
 const scroll=useRef(),selected=useRef();
 useEffect(()=>{const node=scroll.current,active=selected.current;if(node&&active)node.scrollTop=Math.max(0,active.offsetTop-node.clientHeight/2+active.offsetHeight/2);},[code.currentLine,code.rows[0]?.line]);
 return<section className="gcode-inspector" aria-label="G-code command inspector"><h3>G-code</h3><p data-testid="gcode-current-command">{code.currentLine?`Line ${code.currentLine}${Number.isInteger(code.nativeVertexIndex)?` · native vertex ${code.nativeVertexIndex}`:''}${code.segmentIndex!==null?` · segment ${code.segmentIndex+1}`:''}${code.event?` · ${code.event}`:''}${code.arc?' · interpolated arc':''}`:'No visible motion selected'}</p>{code.firstLine&&<p>Displayed motion: lines {code.firstLine}–{code.lastLine}</p>}
 {attributes&&<dl className="gcode-motion-attributes" aria-label="Selected motion attributes">{[['height','Layer height','mm'],['width','Line width','mm'],['flow','Flow','mm³/s'],...(Number.isInteger(attributes.nativeVertexIndex)?[['actualFlow','Actual flow','mm³/s'],['actualSpeed','Actual speed','mm/s'],['layerTime','Layer time','s'],['pressureAdvance','Pressure advance',''],['acceleration','Acceleration','mm/s²'],['jerk','Jerk','mm/s']]:[])].map(([key,label,unit])=><React.Fragment key={key}><dt>{label}</dt><dd data-attribute={key}>{Number.isFinite(attributes[key])?`${attributes[key].toLocaleString(undefined,{maximumFractionDigits:6})} ${unit}`:'Unavailable'}</dd></React.Fragment>)}</dl>}
 {code.unavailable?<p>Source text is unavailable for this preview.</p>:<><div ref={scroll} className="gcode-source" role="log" aria-label="G-code source lines" aria-live="off" tabIndex="0">{code.rows.map(row=><div key={row.line} ref={row.selected?selected:null} data-line={row.line} data-selected={row.selected} aria-current={row.selected?'true':undefined} className={`gcode-source-line${row.selected?' selected':''}`}><span className="gcode-line-number">{row.line}</span><code><span className="gcode-command">{row.command}</span><span className="gcode-parameters">{row.parameters}</span><span className="gcode-comment">{row.comment}</span>{row.truncated&&<span className="gcode-truncated"> … [line shortened for display]</span>}</code></div>)}</div>{!code.rows.length&&<p>No source lines were retained.</p>}{!code.sourceComplete&&<p>Source text is limited to the downloaded preview prefix.</p>}{code.rows.some(row=>row.truncated)&&<p>Long lines are limited to 4,096 characters here. Download the complete G-code to inspect the full line.</p>}</>}
 </section>;
}
