import {layerHeightProfileFromRanges} from '../shared/layer-height-profile.js';
import React,{useEffect,useMemo,useRef,useState}from'react';
import SceneViewport from'./SceneViewport.jsx';
import{generateLayerHeightTexture,sampleLayerHeightTexture,layerCursorBlend}from'../shared/layer-height-texture.js';
import{adjustLayerHeightProfile}from'../shared/variable-layer-brush.js';
import{nativeBed}from'../shared/native-project.js';
// Native GLCanvas3D: 70px bar, 100ms held-mouse repeat, Shift actions and
// wheel multiplier 1 + 0.1*rotation/delta clamped to a 1.5–10mm band.
export default function LayerHeightBrushPreview({profile,context,settings,onProfile,onStrokeStart,onStrokeEnd,onError}){
 const canvas=useRef(),latest=useRef(),stroke=useRef(null),timer=useRef(null),[cursorZ,setCursorZ]=useState(null),[bandWidth,setBandWidth]=useState(2),[strokeActive,setStrokeActive]=useState(false);
 const preview=useMemo(()=>{try{return{texture:generateLayerHeightTexture(profile,context)};}catch(cause){return{error:cause.message};}},[profile,context]);
 const bed=useMemo(()=>{const b=nativeBed(settings);return b?{...b,polygon:settings.printable_area.map(point=>point.split('x').map(Number))}:{width:250,depth:210,height:250};},[settings]);
 latest.current={profile,context,onProfile,onStrokeStart,onStrokeEnd,onError,bandWidth};
 function apply(){const current=latest.current,action=stroke.current;if(!action)return;try{const next=adjustLayerHeightProfile(current.profile,current.context,{...action,bandWidth:current.bandWidth});current.onProfile(next);current.profile=next;}catch(cause){stop();current.onError(cause.message);}}
 function stop(){clearInterval(timer.current);timer.current=null;if(stroke.current){stroke.current=null;setStrokeActive(false);latest.current.onStrokeEnd?.();}}
 useEffect(()=>()=>{clearInterval(timer.current);},[]);
 useEffect(()=>{const lose=()=>stop();window.addEventListener('blur',lose);return()=>window.removeEventListener('blur',lose);},[]);
 function position(event,editing=false){const rect=event.currentTarget.getBoundingClientRect();if(!editing&&(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom))return null;const relative=(rect.bottom-event.clientY-1)/(rect.height-(editing?0:1));return relative*context.objectHeight;}
 function mouseAction(event){const right=event.buttons&2||event.button===2;return event.shiftKey?(right?'smooth':'reduce'):(right?'increase':'decrease');}
 function begin(event){if(![0,2].includes(event.button)||preview.error)return;event.preventDefault();event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);onStrokeStart?.();stroke.current={z:position(event,true),action:mouseAction(event)};setCursorZ(position(event));setStrokeActive(true);apply();if(stroke.current)timer.current=setInterval(apply,100);}
 function move(event){setCursorZ(position(event));if(stroke.current&&(event.buttons&3)){stroke.current={z:position(event,true),action:mouseAction(event)};apply();}}
 function finish(event){if(event.currentTarget.hasPointerCapture?.(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);stop();}
 useEffect(()=>{const node=canvas.current;if(!node)return;const wheel=event=>{event.preventDefault();const rotation=-event.deltaY/(event.deltaMode===1?3:event.deltaMode===2?1:100);setBandWidth(value=>Math.max(1.5,Math.min(10,Math.fround(Math.fround(value)*Math.fround(1+Math.fround(.1*Math.fround(rotation)))))));};node.addEventListener('wheel',wheel,{passive:false});return()=>node.removeEventListener('wheel',wheel);},[]);
 useEffect(()=>{
  const node=canvas.current;if(!node||!preview.texture)return;const draw=()=>{const box=node.getBoundingClientRect(),ratio=window.devicePixelRatio||1,width=Math.max(1,Math.round(box.width*ratio)),height=Math.max(1,Math.round(box.height*ratio));node.width=width;node.height=height;const ctx=node.getContext('2d'),image=ctx.createImageData(width,height),data=preview.texture;
   for(let row=0;row<height;row++){const z=context.objectHeight*(1-row/Math.max(1,height-1)),color=sampleLayerHeightTexture(data,z*data.printHeight/context.objectHeight),blend=layerCursorBlend(z,cursorZ,bandWidth);for(let col=0;col<width;col++){const offset=(row*width+col)*4,x=1-2*(width-col)/(Math.max(1,node.parentElement.clientWidth)*ratio),y=1-2*row/height,length=Math.hypot(x,y)||1,intensity=.3+.7624929*.48+.6985074*.18,specular=.075*Math.pow(Math.max((-x*.4574957+y*.4574957)/length,0),20);for(let axis=0;axis<3;axis++)image.data[offset+axis]=255*specular+intensity*((1-blend)*color[axis]+blend*(axis===2?0:255));image.data[offset+3]=255;}}
   ctx.putImageData(image,0,0);const plotProfile=profile.length?profile:layerHeightProfileFromRanges(context,{editable:false});ctx.lineWidth=ratio;ctx.strokeStyle='#000';ctx.beginPath();const baseline=context.layerHeight/(1.12*context.maxLayerHeight)*width;ctx.moveTo(baseline,0);ctx.lineTo(baseline,height);ctx.stroke();if(plotProfile.length){ctx.strokeStyle='#0000ff';ctx.beginPath();for(let i=0;i<plotProfile.length;i+=2){const x=plotProfile[i+1]/(1.12*context.maxLayerHeight)*width,y=height*(1-plotProfile[i]/context.objectHeight);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);}ctx.stroke();}
  };draw();const observer=new ResizeObserver(draw);observer.observe(node);return()=>observer.disconnect();
 },[preview.texture,profile,context,cursorZ,bandWidth]);
 const visualization=useMemo(()=>preview.texture?{texture:preview.texture,context,cursorZ,bandWidth}:undefined,[preview.texture,context,cursorZ,bandWidth]);
 return <section className="layer-brush-section" aria-label="Native layer height brush"><div className="layer-brush-preview"><div className="layer-brush-model"><SceneViewport objects={context.normal} selectedId={null} onSelect={()=>{}} onTransform={()=>{}} onPlaceFace={()=>{}} mode="View" bed={bed} layerHeightVisualization={visualization}/></div><canvas ref={canvas} className="layer-height-bar" role="img" aria-label="Layer height brush bar" tabIndex="0" data-band-width={bandWidth} data-cursor-z={cursorZ??''} data-active={strokeActive} data-layer-count={preview.texture?.layerCount||0} onPointerDown={begin} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish} onLostPointerCapture={stop} onPointerLeave={()=>{if(!stroke.current)setCursorZ(null);}} onContextMenu={event=>event.preventDefault()}/></div>
  <p>Left-drag: decrease · Right-drag: increase · Shift-left: move toward the default · Shift-right: smooth · Scroll over the bar: adjust brush width.</p><div className="variable-layer-controls"><label>Brush width (mm)<input aria-label="Layer brush width" type="number" min="1.5" max="10" step=".1" value={Number(bandWidth.toFixed(3))} onChange={event=>{const value=Number(event.target.value);if(Number.isFinite(value))setBandWidth(Math.max(1.5,Math.min(10,value)));}}/></label><output aria-label="Layer brush cursor">{cursorZ==null?'Hover over the bar':`Z ${cursorZ.toFixed(3)} mm`}</output><span>{preview.texture?.layerCount||0} preview layers</span></div>{preview.error&&<p className="variable-layer-warning" role="status">Layer preview unavailable: {preview.error}</p>}
 </section>;
}
