import React,{useEffect,useMemo,useRef,useState} from 'react';
import Modal from './Modal.jsx';import SceneViewport from './SceneViewport.jsx';
import {bedBounds} from '../shared/geometry.js';import {hasFacetPainting} from '../shared/facet-correspondence.js';
import {nativeTextAnchor,NATIVE_TEXT_FACES} from '../shared/native-text-creation.js';
import {normalizeNativeSvgSource} from '../shared/native-emboss.js';
import {nativeSvgRequest,nativeSvgSettingsUnchanged,prepareNativeSvgCreation,applyNativeSvgCreation,applyNativeSvgResult} from '../shared/native-svg.js';
import './text-dialog.css';import './native-text-dialog.css';
const json=async(url,options)=>{const response=await fetch(url,options),body=await response.json();if(!response.ok)throw new Error(body.error||'Native SVG generation failed');return body;};
export default function NativeSvgDialog({objects=[],selectedId,bed,plateId='plate-1',filamentColors,onApply,onClose}){
 const selected=objects.find(o=>o.id===selectedId),editing=Boolean(selected?.native?.embossShape?.svg&&!selected.native.textConfiguration),original=editing?selected.native.embossShape:null;
 const[svg,setSvg]=useState(original?.svg||null),[depth,setDepth]=useState(original?.depth??10),[surface,setSurface]=useState(original?.useSurface??false),[mode,setMode]=useState(selected?'emboss':'standalone'),[face,setFace]=useState('Top');
 const[placement,setPlacement]=useState(()=>{if(selected){try{return nativeTextAnchor(objects,selectedId);}catch{}}const b=bedBounds(bed);return{anchor:[b.center[0],b.center[1],0],normal:[0,0,1],angle:0};});
 const[capabilities,setCapabilities]=useState(null),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[reading,setReading]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[clearPainting,setClearPainting]=useState(false),[force,setForce]=useState(0);const readSequence=useRef(0);
 useEffect(()=>{const controller=new AbortController();json('/api/native-text/capabilities',{signal:controller.signal}).then(caps=>{setCapabilities(caps);if(!caps.svg)setError('Native SVG helper is unavailable. Rebuild with npm run build:native:emboss.');}).catch(cause=>{if(cause.name!=='AbortError')setError(cause.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>{controller.abort();readSequence.current++;};},[]);
 const signature=JSON.stringify([svg,depth,surface,mode,placement,force]);
 useEffect(()=>{setResult(null);if(editing&&!force&&nativeSvgSettingsUnchanged(selected,{svg,depth,useSurface:surface})){setPending(false);setResult({signature,sourceObjects:objects,value:{objects,selectedId,text:selected,unchanged:true}});return;}if(!svg||!capabilities?.svg)return;const controller=new AbortController();setPending(true);setError('');const timer=setTimeout(async()=>{try{const prepared=editing?nativeSvgRequest(objects,selectedId,{svg,depth,useSurface:surface}):prepareNativeSvgCreation({objects,selectedId,plateId,bed,svg,depth,useSurface:surface,mode,placement});const mesh=await json('/api/native-text/svg/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request:prepared.request}),signal:controller.signal});if(controller.signal.aborted)return;const value=editing?applyNativeSvgResult(objects,selectedId,prepared,mesh,{clearPainting:true}):applyNativeSvgCreation(objects,prepared,mesh);setResult({signature,sourceObjects:objects,value});}catch(cause){if(cause.name!=='AbortError')setError(cause.message);}finally{if(!controller.signal.aborted)setPending(false);}},180);return()=>{clearTimeout(timer);controller.abort();};},[signature,capabilities,objects,selectedId,plateId,bed,editing]);
 const valid=result?.signature===signature&&result.sourceObjects===objects?result.value:null,painted=editing&&hasFacetPainting(selected);
 const preview=useMemo(()=>(valid?.objects||objects).filter(o=>o.plateId===plateId),[valid,objects,plateId]);
 async function readSvg(file){const sequence=++readSequence.current;if(!file)return;setReading(true);setError('');try{if(file.size>2*1024*1024)throw new Error('Native SVG source exceeds 2 MiB');const value=normalizeNativeSvgSource({name:file.name,source:await file.text()});if(sequence===readSequence.current)setSvg(value);}catch(cause){if(sequence===readSequence.current)setError(cause.message);}finally{if(sequence===readSequence.current)setReading(false);}}
 function changeMode(value){setMode(value);if(value==='standalone'){const b=bedBounds(bed);setPlacement({anchor:[b.center[0],b.center[1],0],normal:[0,0,1],angle:0});setSurface(false);}else try{setPlacement(nativeTextAnchor(objects,selectedId,face));}catch(cause){setError(cause.message);}}
 function exportSource(){if(!svg)return;const url=URL.createObjectURL(new Blob([svg.source],{type:'image/svg+xml'})),link=document.createElement('a');link.href=url;link.download=svg.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <Modal className="text-dialog native-text-dialog" aria-label={editing?'Edit native SVG':'Add native SVG'} onClose={onClose}><header><h2>{editing?'Edit native SVG':'Native SVG / emboss'}</h2><button aria-label="Close native SVG tool" onClick={onClose}>×</button></header><div className="text-tool-layout"><div className="text-controls">
 <label>{editing?'Replace embedded SVG':'SVG source file'}<input aria-label="Native SVG file" type="file" accept=".svg,image/svg+xml" onChange={event=>void readSvg(event.target.files?.[0])}/></label>
 {svg?<><p>{svg.name} · {new TextEncoder().encode(svg.source).length} bytes</p><button onClick={exportSource}>Export embedded SVG source</button><details><summary>Embedded source</summary><textarea aria-label="Native SVG source" readOnly rows={6} value={svg.source}/></details></>:<p>Choose a self-contained SVG file. Text and linked images must first be converted to paths.</p>}
 <label>Native SVG depth (mm)<input aria-label="Native SVG depth (mm)" type="number" min=".01" max="10000" step=".1" value={depth} onChange={event=>setDepth(event.target.value===''?'':Number(event.target.value))}/></label>
 {!editing&&<><label>Operation<select aria-label="Native SVG operation" value={mode} onChange={event=>changeMode(event.target.value)}><option value="standalone">Standalone SVG</option><option value="emboss" disabled={!selected}>Emboss · add material</option><option value="engrave" disabled={!selected}>Engrave · remove material</option><option value="modifier" disabled={!selected}>Modifier volume</option></select></label>
 {mode!=='standalone'&&<label>Initial face<select aria-label="Native SVG face" value={face} onChange={event=>{setFace(event.target.value);try{setPlacement(nativeTextAnchor(objects,selectedId,event.target.value));}catch(cause){setError(cause.message);}}}>{Object.keys(NATIVE_TEXT_FACES).map(name=><option key={name}>{name}</option>)}</select></label>}
 <fieldset><legend>Native SVG anchor (mm)</legend>{['X','Y',...(mode==='standalone'?[]:['Z'])].map((axis,index)=><label key={axis}>{axis}<input aria-label={`Native SVG anchor ${axis}`} type="number" step=".1" value={placement.anchor[index]} onChange={event=>setPlacement(old=>({...old,anchor:old.anchor.map((v,i)=>i===index?(event.target.value===''?'':Number(event.target.value)):v)}))}/></label>)}</fieldset>
 <label>Angle (degrees)<input aria-label="Native SVG angle" type="number" min="-180" max="180" value={placement.angle} onChange={event=>setPlacement(old=>({...old,angle:event.target.value===''?'':Number(event.target.value)}))}/></label></>}
 <label className="native-checkbox"><input aria-label="Use native SVG surface" type="checkbox" disabled={!editing&&mode==='standalone'} checked={surface} onChange={event=>setSurface(event.target.checked)}/>Use surface</label>
 <p>{editing?'Original placement and transforms remain applied.':'Choose the initial face and anchor.'} Units, visible fills, strokes, curves and centering use OrcaSlicer 2.4.2’s SVG parser. Colors and gradients describe filled outlines and do not assign filaments.</p>
 </div><div className="text-preview" aria-label="Native SVG geometry preview"><SceneViewport objects={preview} selectedId={valid?.selectedId||selectedId} mode="View" bed={bed} filamentColors={filamentColors} onSelect={()=>{}} onTransform={()=>{}} onPlaceFace={()=>{}}/></div></div>
 {error?<p role="alert">{error}</p>:pending||loading||reading?<p role="status">Generating native SVG geometry…</p>:valid?<p role="status">{valid.unchanged?'No changes · original native SVG geometry retained':`${valid.text.positions.length/9} native triangles · OrcaSlicer 2.4.2 geometry kernel`}</p>:null}
 {valid?.warnings?.map(warning=><p role="note" key={warning}>{warning}</p>)}
 {painted&&!valid?.unchanged&&<label className="paint-loss-consent"><input aria-label="Clear painting from regenerated native SVG" type="checkbox" checked={clearPainting} onChange={event=>setClearPainting(event.target.checked)}/>Regeneration replaces the SVG triangles. Clear support, seam, color and fuzzy painting on this part.</label>}
 <footer>{editing&&<button disabled={!capabilities?.svg||pending||reading} onClick={()=>setForce(value=>value+1)}>Regenerate SVG with current settings</button>}<p>The source remains embedded in the project. SVG path selection and native drag placement are not available here.</p><button onClick={onClose}>Cancel native SVG</button><button disabled={pending||reading||!valid||!valid.unchanged&&(!!error||painted&&!clearPainting)} onClick={()=>{if(!valid.unchanged)onApply(valid);onClose();}}>{editing?'Update native SVG':'Add native SVG'}</button></footer></Modal>;
}
