import {bedBounds} from '../shared/geometry.js';import {defaultNativeText,nativeTextAnchor,NATIVE_TEXT_FACES,prepareNativeTextCreation,applyNativeTextCreation} from '../shared/native-text-creation.js';
import React,{useEffect,useMemo,useState}from'react';import Modal from'./Modal.jsx';import SceneViewport from'./SceneViewport.jsx';import{nativeEmbossRequest,applyNativeEmbossResult,nativeTextSettingsUnchanged}from'../shared/native-emboss-regeneration.js';import{hasFacetPainting}from'../shared/facet-correspondence.js';import'./text-dialog.css';import'./native-text-dialog.css';
const json=async(url,options)=>{const response=await fetch(url,options),body=await response.json();if(!response.ok)throw new Error(body.error||'Native text request failed');return body;};
export default function NativeTextDialog({objects=[],selectedId,bed,plateId='plate-1',filamentColors,onApply,onClose}){
 const selected=objects.find(object=>object.id===selectedId),editing=Boolean(selected?.native?.textConfiguration),original=editing?selected.native.textConfiguration:defaultNativeText();
 const[creationMode,setCreationMode]=useState(selected?'emboss':'standalone'),[face,setFace]=useState('Top'),[placement,setPlacement]=useState(()=>{if(selected){try{return nativeTextAnchor(objects,selectedId);}catch{}}const bounds=bedBounds(bed);return{anchor:[bounds.center[0],bounds.center[1],0],normal:[0,0,1],angle:0};});
 const[config,setConfig]=useState(()=>structuredClone(original)),[depth,setDepth]=useState(editing?selected.native.embossShape.depth:1),[surface,setSurface]=useState(editing?selected.native.embossShape.useSurface:false),[fontId,setFontId]=useState(''),[initialFontId,setInitialFontId]=useState(''),[fonts,setFonts]=useState([]),[fontInfo,setFontInfo]=useState(null),[capabilities,setCapabilities]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[pending,setPending]=useState(false),[result,setResult]=useState(null),[clearPainting,setClearPainting]=useState(false),[forceRegenerate,setForceRegenerate]=useState(false);
 const painted=editing&&hasFacetPainting(selected),set=(key,value)=>setConfig(old=>({...old,[key]:value}));
 useEffect(()=>{const controller=new AbortController();Promise.all([json('/api/native-text/capabilities',{signal:controller.signal}),json('/api/native-text/fonts',{signal:controller.signal})]).then(([caps,data])=>{if(controller.signal.aborted)return;setCapabilities(caps);setFonts(data.fonts);const names=[original.faceName,original.fontDescriptorType==='file_name'?original.fontDescriptor.replace(/\.[^.]+$/,''):null].filter(Boolean).map(name=>name.toLowerCase()),matched=editing?data.fonts.find(font=>names.includes(font.name.toLowerCase())):data.fonts[0];if(matched){setFontId(matched.id);setInitialFontId(matched.id);}if(!caps.available)setError(caps.error);}).catch(cause=>{if(cause.name!=='AbortError')setError(cause.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[]);
 useEffect(()=>{setFontInfo(null);if(!fontId||!capabilities?.available)return;const controller=new AbortController();json(`/api/native-text/fonts/${encodeURIComponent(fontId)}/metadata`,{signal:controller.signal}).then(info=>{if(!controller.signal.aborted)setFontInfo(info);}).catch(cause=>{if(cause.name!=='AbortError')setError(cause.message);});return()=>controller.abort();},[fontId,capabilities]);
 const signature=JSON.stringify([config,depth,surface,fontId,creationMode,placement,forceRegenerate]);
 useEffect(()=>{setResult(null);if(editing&&!forceRegenerate&&nativeTextSettingsUnchanged(selected,{textConfiguration:config,depth,useSurface:surface,fontId,initialFontId})){setPending(false);setError(capabilities?.available===false?capabilities.error||'Native text helper is unavailable':'');setResult({value:{objects,selectedId,text:selected,unchanged:true},signature,sourceObjects:objects});return;}if(!fontInfo||!capabilities?.available)return;const controller=new AbortController();setPending(true);setError('');const timer=setTimeout(async()=>{try{const prepared=editing?nativeEmbossRequest(objects,selectedId,{textConfiguration:config,depth,useSurface:surface}):prepareNativeTextCreation({objects,selectedId,plateId,bed,textConfiguration:config,depth,useSurface:surface,mode:creationMode,placement}),mesh=await json('/api/native-text/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fontId,request:prepared.request}),signal:controller.signal});if(controller.signal.aborted)return;const collection=fontInfo.collections.find(item=>item.index===(config.collection||0));const descriptor={fontName:collection?.family||fontInfo.font.name,fontDescriptor:fontInfo.font.fileName};const generated=editing?applyNativeEmbossResult(objects,selectedId,prepared,mesh,{clearPainting:true,...(fontId!==initialFontId&&descriptor)}):applyNativeTextCreation(objects,prepared,mesh,descriptor);setResult({value:generated,signature,sourceObjects:objects});}catch(cause){if(cause.name!=='AbortError')setError(cause.message);}finally{if(!controller.signal.aborted)setPending(false);}},180);return()=>{clearTimeout(timer);controller.abort();};},[signature,fontInfo,capabilities,objects,selectedId,initialFontId,plateId,bed,editing]);
 const validResult=result?.signature===signature&&result?.sourceObjects===objects?result.value:null;
 const preview=useMemo(()=>(validResult?.objects||objects).filter(object=>object.plateId===plateId),[validResult,objects,plateId]);
 function chooseFont(id){setFontId(id);set('collection',0);setError('');}
 const number=(label,key,step=.1)=><label>{label}<input aria-label={label} type="number" step={step} value={config[key]??0} onChange={event=>set(key,event.target.value===''?'':Number(event.target.value))}/></label>;
 return <Modal className="text-dialog native-text-dialog" aria-label={editing?"Edit native text":"Add native text"} onClose={onClose}><header><h2>{editing?"Edit native text":"Native text / emboss"}</h2><button aria-label="Close native text tool" onClick={onClose}>×</button></header><div className="text-tool-layout"><div className="text-controls">
 <label>Text<textarea aria-label="Native text content" rows={3} maxLength={4096} value={config.text} onChange={event=>set('text',event.target.value)}/></label>
 <label>Installed font<select aria-label="Native text font" value={fontId} onChange={event=>chooseFont(event.target.value)}><option value="">Choose the original font or an explicit substitute</option>{fonts.map(font=><option key={font.id} value={font.id}>{font.name} · {font.source}</option>)}</select></label>
 {editing&&!fontId&&!loading&&<p role="note">The original font “{original.faceName||'unknown'}” was not matched. Choose a font explicitly before regenerating.</p>}
 {fontInfo&&<label>Font collection<select aria-label="Native font collection" value={config.collection||0} onChange={event=>set('collection',Number(event.target.value))}>{fontInfo.collections.map(font=><option key={font.index} value={font.index}>{font.index}: {font.fullName||font.style||font.family||fontInfo.font.name}</option>)}</select></label>}
 <div className="text-number-grid">{number('Native line height (mm)','lineHeight')}<label>Native depth (mm)<input aria-label="Native depth (mm)" type="number" step=".1" value={depth} onChange={event=>setDepth(event.target.value===''?'':Number(event.target.value))}/></label>{number('Character gap (font units)','charGap',1)}{number('Line gap (font units)','lineGap',1)}{number('Native boldness (font units)','boldness',1)}{number('Native skew','skew',.01)}</div>
 <label>Horizontal alignment<select aria-label="Native horizontal alignment" value={config.horizontal} onChange={event=>set('horizontal',event.target.value)}>{['left','center','right'].map(value=><option key={value}>{value}</option>)}</select></label>
 <label>Vertical alignment<select aria-label="Native vertical alignment" value={config.vertical} onChange={event=>set('vertical',event.target.value)}>{['top','middle','bottom'].map(value=><option key={value}>{value}</option>)}</select></label>
 {!editing&&<><label>Operation<select aria-label="Native text operation" value={creationMode} onChange={event=>{const mode=event.target.value;setCreationMode(mode);if(mode==='standalone'){const bounds=bedBounds(bed);setPlacement({anchor:[bounds.center[0],bounds.center[1],0],normal:[0,0,1],angle:0});setSurface(false);set('perGlyph',false);}else try{setPlacement(nativeTextAnchor(objects,selectedId,face));}catch(cause){setError(cause.message);}}}><option value="standalone">Standalone text</option><option value="emboss" disabled={!selected}>Emboss · add material</option><option value="engrave" disabled={!selected}>Engrave · remove material</option><option value="modifier" disabled={!selected}>Modifier volume</option></select></label>
 {creationMode!=='standalone'&&<label>Initial face<select aria-label="Native text face" value={face} onChange={event=>{setFace(event.target.value);try{setPlacement(nativeTextAnchor(objects,selectedId,event.target.value));}catch(cause){setError(cause.message);}}}>{Object.keys(NATIVE_TEXT_FACES).map(name=><option key={name}>{name}</option>)}</select></label>}
 <fieldset><legend>Native text anchor (mm)</legend>{['X','Y',...(creationMode==='standalone'?[]:['Z'])].map((axis,index)=><label key={axis}>{axis}<input aria-label={`Native text anchor ${axis}`} type="number" step=".1" value={placement.anchor[index]} onChange={event=>setPlacement(old=>({...old,anchor:old.anchor.map((v,i)=>i===index?(event.target.value===''?'':Number(event.target.value)):v)}))}/></label>)}</fieldset>
 <label>Angle (degrees)<input aria-label="Native text angle" type="number" min="-180" max="180" value={placement.angle} onChange={event=>setPlacement(old=>({...old,angle:event.target.value===''?'':Number(event.target.value)}))}/></label></>}
 <label className="native-checkbox"><input aria-label="Use native surface" type="checkbox" disabled={!editing&&creationMode==='standalone'} checked={surface} onChange={event=>setSurface(event.target.checked)}/>Use surface</label>
 <label className="native-checkbox"><input aria-label="Native per-glyph layout" type="checkbox" disabled={!capabilities?.perGlyph&&!config.perGlyph||!editing&&creationMode==='standalone'} checked={config.perGlyph} onChange={event=>set('perGlyph',event.target.checked)}/>Per-glyph layout</label>
 <p>{editing?'Native placement and object transforms remain applied.':'Choose an initial face and position; Use surface cuts the actual source geometry.'} {(editing?selected.native.partType:creationMode)===(editing?'negative_part':'engrave')?'Engraving removes material.':''}</p>
 </div><div className="text-preview" aria-label="Native text geometry preview"><SceneViewport objects={preview} selectedId={validResult?.selectedId||selectedId} mode="View" bed={bed} filamentColors={filamentColors} onSelect={()=>{}} onTransform={()=>{}} onPlaceFace={()=>{}}/></div></div>
 {error?<p role="alert">{error}</p>:pending||loading?<p role="status">Generating native text geometry…</p>:validResult?<p role="status">{validResult.unchanged?'No changes · original native geometry retained':`${validResult.text.positions.length/9} native triangles · OrcaSlicer 2.4.2 geometry kernel`}</p>:null}
 {painted&&!validResult?.unchanged&&<label className="paint-loss-consent"><input aria-label="Clear painting from regenerated native text" type="checkbox" checked={clearPainting} onChange={event=>setClearPainting(event.target.checked)}/>Regeneration replaces the text triangles. Clear support, seam, color and fuzzy painting on this part.</label>}
 <footer>{editing&&<button disabled={!fontInfo||!capabilities?.available||pending} onClick={()=>setForceRegenerate(true)}>Regenerate with current settings</button>}<p>Regeneration uses the selected installed font. A surface toolpath may start at a different point after regeneration.</p><button onClick={onClose}>Cancel native text</button><button disabled={pending||!validResult||!validResult.unchanged&&(!!error||painted&&!clearPainting)} onClick={()=>{if(!validResult.unchanged)onApply(validResult);onClose();}}>{editing?'Update native text':'Add native text'}</button></footer></Modal>;
}
