import React,{useEffect,useRef} from 'react';
import {createNativeSpinRepeat} from './native-spin-repeat.js';
/** Native left-hand arrow placement, immediate press and delayed repeat.
 * Text and committed values stay separate so pointer steps use the committed value. */
export default function NativePreferenceSpin({label,value,draft,setDraft,onCommit,min,max,unit}){
 const input=useRef(),latest=useRef(),repeat=useRef(),capture=useRef();latest.current={value,onCommit,min,max};
 function step(direction){const current=latest.current;const next=String(Math.max(current.min,Math.min(current.max,Number(current.value)+direction)));current.value=next;current.onCommit(next);}
 function stop({select=false}={}){repeat.current.stop();const p=capture.current;capture.current=null;if(p&&p.target.hasPointerCapture(p.id))p.target.releasePointerCapture(p.id);if(select)input.current?.select();}
 useEffect(()=>{repeat.current=createNativeSpinRepeat({step});const blur=()=>stop(),visibility=()=>{if(document.hidden)stop();};window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);return()=>{repeat.current.dispose();window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);};},[]);
 function press(event,direction){if(event.button!==0)return;event.preventDefault();input.current.focus();capture.current={target:event.currentTarget,id:event.pointerId};event.currentTarget.setPointerCapture(event.pointerId);repeat.current.start(direction);}
 return <span className="native-preference-spin"><span className="native-preference-arrows">{[[1,'Increase','inc'],[-1,'Decrease','dec']].map(([direction,name,icon])=><button key={icon} type="button" tabIndex={-1} aria-label={`${name} ${label}`} title={`${name} ${label}`} onPointerDown={event=>press(event,direction)} onPointerUp={()=>stop({select:true})} onPointerCancel={()=>stop()} onLostPointerCapture={()=>stop()} onClick={event=>{event.preventDefault();if(event.detail===0){input.current.focus();step(direction);}}}><img src={`/native-icons/spin_${icon}.svg`} alt=""/></button>)}</span><input ref={input} aria-label={label} role="spinbutton" aria-valuemin={min} aria-valuemax={max} aria-valuenow={Number(value)} type="text" inputMode="numeric" value={draft} onChange={event=>setDraft(event.target.value)} onBlur={()=>{stop();onCommit();}} onContextMenu={event=>event.preventDefault()} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();onCommit();}else if(['ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();const n=/^[+-]?\d+$/.test(draft.trim())?Number(draft):Number(value);const next=event.key==='ArrowDown'&&n-1>=min?n-1:event.key==='ArrowUp'&&n+1<=max?n+1:n;if(next!==Number(value))onCommit(String(next));}}}/>{unit&&<span className="native-preference-unit">{unit}</span>}</span>;
}
