import React,{useEffect,useState}from'react';
import Modal from'./Modal.jsx';
import{nativeMaterialLabel}from'../shared/native-filament-preview.js';
import{nativeFixed}from'../shared/native-format.js';
export default function NativeAllPlateStatistics({job,mode='normal',imperial=false,enabled,onOpen}){
 const[open,setOpen]=useState(false);
 if(!(job.nativePreviewProject?.plates.length>1))return null;
 return <><button disabled={!enabled} title={enabled?'Native statistics for every completed plate in this project':'Native editor Preview statistics require the current helper'} onClick={()=>{onOpen?.();setOpen(true);}}>Statistics of all plates</button>{open&&<StatisticsDialog job={job} mode={mode} imperial={imperial} onClose={()=>setOpen(false)}/>}</>;
}
function StatisticsDialog({job,mode,imperial,onClose}){
 const[result,setResult]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();let timer;setResult(null);setError('');setLoading(true);async function load(){try{const response=await fetch(`/api/jobs/${encodeURIComponent(job.id)}/native-preview/all-plates?mode=${encodeURIComponent(mode)}&units=${imperial?'imperial':'metric'}`,{signal:controller.signal}),value=await response.json();if(!response.ok)throw new Error(value.error||'Could not load native all-plate statistics');if(!controller.signal.aborted){setResult(value);setLoading(false);if(!value.available&&value.missingPlates?.length)timer=setTimeout(load,2000);}}catch(cause){if(!controller.signal.aborted){setError(cause.message);setLoading(false);}}}load();return()=>{clearTimeout(timer);controller.abort();};},[job.id,mode,imperial,retry]);
 return <Modal className="native-all-plate-dialog" aria-label="Statistics of all plates" onClose={onClose}><header><h2>Statistics of all plates</h2><button aria-label="Close all-plate statistics" onClick={onClose}>×</button></header>{loading?<p role="status">Processing completed plate results…</p>:error?<><p role="alert">{error}</p><button onClick={()=>setRetry(value=>value+1)}>Retry statistics</button></>:result?.available?<><div className="native-all-plate-table"><table><thead><tr><th>Filament</th>{result.columns.map(column=><th key={column.key}>{column.label}</th>)}{result.showTotals&&<th>Total</th>}</tr></thead><tbody>{result.rows.map(row=><tr key={row.tool} data-filament={row.tool}><th><i style={{backgroundColor:row.color}}/>{row.tool+1}</th>{result.columns.map(column=><td key={column.key} data-material={column.key} data-volume={row.amounts[column.key].volume}>{nativeMaterialLabel(row.amounts[column.key],result.imperial,result.showTotals)}</td>)}{result.showTotals&&<td data-material="total">{nativeMaterialLabel(row.total,result.imperial,true)}</td>}</tr>)}</tbody></table></div><h3>Total estimation</h3><dl><dt>Total time</dt><dd data-native-all-plate-seconds={result.seconds}>{result.timeLabel}</dd><dt>Total cost</dt><dd data-native-all-plate-cost={result.cost}>{nativeFixed(result.cost,2)}</dd></dl><p>{result.plateCount} completed plates · {mode==='stealth'?'Stealth':'Normal'} timing</p><p>Results use this saved project and settings.</p></>:<><p role="status">{result?.reason}</p>{result?.missingPlates?.length>0&&<><p>{result.readyPlates} / {result.totalPlates} plates ready</p><ul>{result.missingPlates.map(plate=><li key={plate.id}>{plate.name}</li>)}</ul></>}</>}<footer><button onClick={onClose}>Close</button></footer></Modal>;
}
