import React,{useState} from 'react';
import {nativePreviewLegendRows} from '../shared/native-preview-adapter.js';
import {nativeHotendDescription} from '../shared/native-hotend-client.js';
import {nativeFixed} from '../shared/native-tool-position.js';
export default function NativeToolPosition({position,profile,range,modelInfo}){
 const[properties,setProperties]=useState(false),[showProfile,setShowProfile]=useState(false),[hover,setHover]=useState(-1);
 if(!position)return null;
 const plotAvailable=Number.isFinite(range?.min)&&Number.isFinite(range?.max);
 const points=profile?.points||[],maxX=points.at(-1)?.position||0,minY=Number.isFinite(range?.min)?range.min:0,maxY=Number.isFinite(range?.max)?range.max:Math.max(1,...points.map(p=>p.speed)),clamp=value=>Math.max(0,Math.min(1,value)),x=value=>10+clamp(value/(maxX||1))*280,y=value=>110-clamp(maxY===minY?0:(value-minY)/(maxY-minY))*95;
 return <section className="native-tool-position" aria-label="Native tool position" data-property-vertex={position.propertyVertexId} data-marker-vertex={position.selectedVertexId} data-source-line={position.sourceLine}>
 <button aria-expanded={properties} onClick={()=>setProperties(!properties)} aria-label={properties?'Hide tool properties':'Show tool properties'}>{properties?'▾':'▸'}</button>
 <div className="native-tool-position-summary"><div>{position.positionText.map((value,i)=><span key={i} className={`native-tool-axis axis-${i}`}>{['X','Y','Z'][i]} <b>{value}</b></span>)}</div><div>Speed: {position.speedText} <span>{position.detail}</span></div></div>
 {properties&&<div className="native-tool-properties"><dl aria-label="Native tool properties">{position.rows.map(([label,value])=><React.Fragment key={label}><dt>{label}</dt><dd>{value}</dd></React.Fragment>)}</dl><p className="native-tool-model-note">{nativeHotendDescription(modelInfo)}</p>{modelInfo?.warnings?.map((warning,i)=><p className="native-tool-model-note" key={i}>{warning}</p>)}<button disabled={!profile} aria-expanded={showProfile} onClick={()=>setShowProfile(!showProfile)}>{showProfile?'Hide actual speed profile':'Show actual speed profile'}</button>{showProfile&&profile&&<div className="native-actual-speed">{plotAvailable?<svg viewBox="0 0 300 130" onMouseLeave={()=>setHover(-1)} onMouseMove={event=>{const box=event.currentTarget.getBoundingClientRect(),px=(event.clientX-box.left)/box.width*300,t=Math.max(0,Math.min(.9999,(px-10)/280));setHover(points.findIndex((point,i)=>i+1<points.length&&point.position/(maxX||1)<t&&t<points[i+1].position/(maxX||1)));}} role="img" aria-label="Native actual speed profile" data-points={JSON.stringify(points)}>{nativePreviewLegendRows(range).map(({value,color},i)=><line key={'level'+i} x1="1" x2="9" y1={y(value)} y2={y(value)} stroke={color} strokeOpacity=".5" strokeWidth="3"/>)}{points.map((point,i)=><line key={'grid'+i} x1={x(point.position)} x2={x(point.position)} y1="15" y2="110" stroke={point.internal?'rgba(0,150,136,.5)':'rgba(128,128,128,.5)'}/>)}{points.slice(1).map((point,i)=><line key={i} x1={x(points[i].position)} y1={y(points[i].speed)} x2={x(point.position)} y2={y(point.speed)} stroke={hover===i?'#009688':'#cccccc'} strokeWidth="2"/>)}<text x="10" y="127">0</text><text x="255" y="127">{maxX.toFixed(1)} mm</text><text x="12" y="10">{maxY.toFixed(1)} mm/s</text></svg>:<p>Native speed plot range is unavailable from this helper. Exact profile samples remain listed.</p>}<table><caption>Actual speed profile · G-code line {profile.sourceLine}</caption><thead><tr><th>Position (mm)</th><th>Speed (mm/s)</th></tr></thead><tbody>{points.map((point,i)=><tr key={i} data-internal={point.internal} data-highlight={hover>=0&&(i===hover||i===hover+1)}><td>{nativeFixed(point.position,3)}</td><td>{nativeFixed(point.speed,1)}</td></tr>)}</tbody></table></div>}</div>}
 </section>;
}
