import {paintButtonState,paintWheelChange} from '../shared/paint-interactions.js';
import {paintObjectMembers,paintObjectBoundsMesh,paintObjectGroup,changeObjectPaint} from '../shared/paint-object-group.js';
import SlicedSupportPreview from './SlicedSupportPreview.jsx';
import {remapPaintFilaments,usedPaintFilaments} from '../shared/filament-remap.js';
import {viewClipPlane} from '../shared/paint-clipping.js';
import React,{useMemo,useRef,useState} from 'react';
import Modal from './Modal.jsx';
import SceneViewport from './SceneViewport.jsx';
import {meshBounds} from '../shared/geometry.js';
import {normalizePainting,PAINT_CHANNELS} from '../shared/facet-painting.js';
import './paint-dialog.css';
const names={supports:'Supports',seam:'Seams',color:'Filament color',fuzzy:'Fuzzy skin'};
export default function PaintDialog({objects,selectedId,bed,filamentColors=[],filamentCount=1,initialChannel='supports',onApply,onClose,onPreviewSupports}){
 const source=objects.find(object=>object.id===selectedId),boundsMesh=useMemo(()=>paintObjectBoundsMesh(objects,selectedId),[objects,selectedId]),bounds=meshBounds(boundsMesh);
 const[draftObjects,setDraftObjects]=useState(()=>objects.map(object=>object.id===selectedId?{...source,painting:normalizePainting(source.painting||{version:1},source.positions.length/9,{filamentCount})}:object)),[channel,setChannel]=useState(initialChannel),[tool,setTool]=useState('circle'),[state,setState]=useState(1),[radius,setRadius]=useState(1),[resolution,setResolution]=useState(.05),[fillAngle,setFillAngle]=useState(30),[edgeDetection,setEdgeDetection]=useState(false),[gapArea,setGapArea]=useState(1),[heightStart,setHeightStart]=useState(bounds.min[2]),[height,setHeight]=useState(.2),[heightAtPointer,setHeightAtPointer]=useState(true);
 const[constraint,setConstraint]=useState('none');
 const cameraForward=useRef([0,0,-1]);const[clipViewDirection,setClipViewDirection]=useState([0,0,-1]),[clipRatio,setClipRatio]=useState(.5),[clipError,setClipError]=useState('');
 const[clipAxis,setClipAxis]=useState('none'),[clipOffset,setClipOffset]=useState(bounds.center[2]),[clipReverse,setClipReverse]=useState(false),[highlight,setHighlight]=useState(false),[overhangAngle,setOverhangAngle]=useState(40),[overhangOnly,setOverhangOnly]=useState(false);
 const[supportPreview,setSupportPreview]=useState(false);const[error,setError]=useState(''),[history,setHistory]=useState([]),[status,setStatus]=useState('Paint directly on the normal parts of the selected object.');
 const draft=draftObjects.find(object=>object.id===selectedId),allCurrent=useRef(draftObjects);allCurrent.current=draftObjects;const current=useRef(draft);current.current=draft;const inStroke=useRef(false),previousHit=useRef(null);
 const paintTargetIds=paintObjectMembers(draftObjects,selectedId).map(object=>object.id);const preview=draftObjects.filter(object=>object.plateId===source.plateId);const[mapping,setMapping]=useState({});const usedSlots=channel==='color'?usedPaintFilaments(draftObjects,selectedId,{filamentCount}):[],hasMapping=Object.entries(mapping).some(([from,to])=>Number(from)!==to);
 const clipPlane=clipAxis==='none'?null:clipAxis==='view'?(clipRatio>0?viewClipPlane(boundsMesh,clipViewDirection,clipRatio):null):{normal:[0,1,2].map(index=>index==='XYZ'.indexOf(clipAxis)?(clipReverse?-1:1):0),offset:Number.isFinite(clipOffset)?clipOffset*(clipReverse?-1:1):bounds.center['XYZ'.indexOf(clipAxis)]*(clipReverse?-1:1)};
 function changeChannel(value){setChannel(value);setState(1);if(tool==='height'&&value!=='color')setTool('circle');setError('');}
 function remember(){const snapshot=allCurrent.current.map(object=>({id:object.id,painting:structuredClone(object.painting),native:structuredClone(object.native),filamentSlot:object.filamentSlot}));setHistory(values=>[...values.slice(-29),snapshot]);}
 function applyObjects(next){allCurrent.current=next;current.current=next.find(object=>object.id===selectedId);setDraftObjects(next);}
 function remap(){try{const result=remapPaintFilaments(allCurrent.current,selectedId,mapping,{filamentCount});remember();applyObjects(result.objects);setMapping({});setError('');setStatus(`${result.report.changedFacets} painted facets and ${result.report.changedParts} normal parts remapped in this native object.`);}catch(error){setError(error.message);}}
 function paint(event){if(event.phase==='break'){previousHit.current=null;return;}if(event.phase==='error'){previousHit.current=null;setError(event.message);return;}if(event.phase==='end'){inStroke.current=false;previousHit.current=null;return;}if(!paintTargetIds.includes(event.id)||tool==='gap')return;try{if(clipAxis!=='none'&&clipAxis!=='view'&&!Number.isFinite(clipOffset))throw new Error('Clipping offset must be finite');if(!inStroke.current){remember();inStroke.current=true;previousHit.current=null;}
  const effectiveState=paintButtonState(channel,{button:event.button??0,shiftKey:event.shiftKey,state});if(effectiveState===null)return;
  const result=paintObjectGroup(allCurrent.current,selectedId,event,{channel,state:effectiveState,tool,radius,resolution,fillAngle:tool==='bucket'&&!edgeDetection?-1:fillAngle,filamentCount,clipPlane,overhangAngle:channel==='supports'&&overhangOnly?overhangAngle:0,heightStart,height,atPointer:heightAtPointer,previousHit:previousHit.current});previousHit.current={id:event.id,point:event.point,triangleIndex:event.triangleIndex};applyObjects(result.objects);setStatus(`${result.report.changedFacets} original facets changed in the last stroke sample.`);setError('');}catch(cause){setError(cause.message);}}

 function wheel(event){try{const changed=paintWheelChange({tool,radius,height,fillAngle,gapArea,clipRatio:clipAxis==='view'?clipRatio:0},event);if(!changed)return false;for(const[key,value]of Object.entries(changed)){if(key==='clipRatio'){if(clipAxis!=='view'){setClipViewDirection([...cameraForward.current]);setClipAxis('view');}setClipRatio(value);}else({radius:setRadius,height:setHeight,fillAngle:setFillAngle,gapArea:setGapArea}[key])(value);}return true;}catch(cause){setError(cause.message);return true;}}
 function undo(){if(!history.length)return;const snapshot=new Map(history.at(-1).map(object=>[object.id,object]));applyObjects(allCurrent.current.map(object=>({...object,...snapshot.get(object.id)})));setHistory(values=>values.slice(0,-1));setMapping({});setError('');}
 function batch(action,options){try{const result=changeObjectPaint(allCurrent.current,selectedId,action,{channel,state,filamentCount,...options});remember();applyObjects(result.objects);setError('');setStatus(action==='gap'?`${result.report.changedPatches} native patches recolored across ${result.report.changedFacets} original facets.`:action==='clear'?'Channel cleared on the selected object.':`${result.report.changedFacets} overhang facets painted.`);}catch(cause){setError(cause.message);}}
 function clear(){batch('clear');}
 function gap(){batch('gap',{areaThreshold:gapArea});}
 function angles(){batch('overhang',{angle:overhangAngle});}

 const actions=channel==='color'?[{state:0,name:'Original filament'},...Array.from({length:Math.min(filamentCount,16)},(_,index)=>({state:index+1,name:`Filament ${index+1}`}))]:channel==='fuzzy'?[{state:1,name:'Paint fuzzy skin'},{state:0,name:'Erase'}]:[{state:1,name:channel==='supports'?'Enforce support':'Prefer seam'},{state:2,name:channel==='supports'?'Block support':'Avoid seam'},{state:0,name:'Erase'}];
 const numeric=(label,value,set,min,max,step=.1)=><label>{label}<input aria-label={label} type="number" min={min} max={max} step={step} value={Number.isFinite(value)?Number(value.toFixed(4)):value} onChange={event=>set(event.target.value===''?'':Number(event.target.value))}/></label>;
 return <Modal className="paint-dialog" aria-label="Paint facets" onClose={onClose}><header><h2>Paint · {source.name}</h2><button aria-label="Close painting tool" onClick={onClose}>×</button></header>
 {!supportPreview&&<><div className="paint-controls"><label>Channel<select aria-label="Painting channel" value={channel} onChange={event=>changeChannel(event.target.value)}>{Object.keys(PAINT_CHANNELS).map(key=><option key={key} value={key}>{names[key]}</option>)}</select></label>
 <label>Tool<select aria-label="Painting tool" value={tool} onChange={event=>setTool(event.target.value)}><option value="circle">Circle brush</option><option value="sphere">Sphere brush</option><option value="facet">Triangle · current subfacet</option><option value="triangle">Original triangle</option><option value="fill">Smart fill · connected angle</option><option value="bucket">Bucket fill · connected state</option>{channel==='color'&&<option value="height">Height range</option>}<option value="gap">Gap fill</option></select></label>
 {tool!=='gap'&&<label>Action<select aria-label="Paint action" value={state} onChange={event=>setState(Number(event.target.value))}>{actions.map(action=><option key={action.state} value={action.state}>{action.name}</option>)}</select></label>}
 {['circle','sphere'].includes(tool)&&<>{numeric('Brush radius',radius,setRadius,.4,8,.2)}{numeric('Brush resolution',resolution,setResolution,.005,10,.005)}</>}
 {(tool==='fill'||tool==='bucket'&&edgeDetection)&&numeric('Fill angle',fillAngle,setFillAngle,0,90,1)}{tool==='bucket'&&<label><input aria-label="Bucket edge detection" type="checkbox" checked={edgeDetection} onChange={event=>setEdgeDetection(event.target.checked)}/>Detect sharp edges</label>}
 {tool==='height'&&<><label><input aria-label="Start height at pointer" type="checkbox" checked={heightAtPointer} onChange={event=>setHeightAtPointer(event.target.checked)}/>Start at pointer</label>{!heightAtPointer&&numeric('Paint range start',heightStart,setHeightStart,-10000,10000)}{numeric('Paint range height',height,setHeight,.1,8,.2)}</>}
 {tool==='gap'&&<>{numeric('Gap area',gapArea,setGapArea,0,5,.2)}<button onClick={gap}>Perform gap fill</button></>}
 {channel==='color'&&['circle','sphere','facet','triangle','height'].includes(tool)&&<label>Stroke direction<select aria-label="Stroke direction" value={constraint} onChange={event=>setConstraint(event.target.value)}><option value="none">Free</option><option value="vertical">Vertical only</option><option value="horizontal">Horizontal only</option></select></label>}
 <button onClick={undo} disabled={!history.length}>Undo paint</button><button onClick={clear}>Clear this channel</button></div>
 <div className="paint-controls paint-constraints"><label>Clip view<select aria-label="Clipping axis" value={clipAxis} onChange={event=>{const axis=event.target.value;setClipAxis(axis);if(axis==='view')setClipViewDirection([...cameraForward.current]);else if(axis!=='none')setClipOffset(bounds.center['XYZ'.indexOf(axis)]);}}><option value="none">Off</option><option value="view">View</option>{['X','Y','Z'].map(axis=><option key={axis}>{axis}</option>)}</select></label>{clipAxis!=='none'&&clipAxis!=='view'&&<>{numeric('Clipping offset (mm)',clipOffset,setClipOffset,-1e7,1e7)}<label><input aria-label="Reverse clipping direction" type="checkbox" checked={clipReverse} onChange={event=>setClipReverse(event.target.checked)}/>Keep positive side</label></>}
 {clipAxis==='view'&&<><label>Clipping position<input aria-label="Clipping position" type="range" min="0" max="1" step=".01" value={clipRatio} onChange={event=>setClipRatio(Number(event.target.value))}/></label>{numeric('Clipping fraction',clipRatio,value=>{if(Number.isFinite(value)&&value>=0&&value<=1)setClipRatio(value);},0,1,.01)}<button onClick={()=>setClipViewDirection([...cameraForward.current])}>Reset clipping direction</button></>}
 {channel==='supports'&&<><label><input aria-label="Highlight overhangs" type="checkbox" checked={highlight} onChange={event=>setHighlight(event.target.checked)}/>Highlight overhangs</label>{numeric('Overhang angle',overhangAngle,setOverhangAngle,0,90,1)}<label><input aria-label="Paint only overhangs" type="checkbox" checked={overhangOnly} onChange={event=>setOverhangOnly(event.target.checked)}/>On highlighted overhangs only</label><button onClick={angles}>Paint overhangs by angle</button><button onClick={()=>setSupportPreview(true)} disabled={!onPreviewSupports}>Sliced support preview</button></>}
 </div>
 {channel==='color'&&<details className="paint-remap"><summary>Remap filaments</summary><p>Remap painted regions and base filaments of all normal parts in this native object. Other paint channels are retained.</p><div className="paint-controls">{usedSlots.map(slot=><label key={slot}>Filament {slot} →<select aria-label={`Remap filament ${slot}`} value={mapping[slot]??slot} onChange={event=>setMapping(value=>({...value,[slot]:Number(event.target.value)}))}>{Array.from({length:Math.min(filamentCount,16)},(_,index)=><option key={index+1} value={index+1}>Filament {index+1}</option>)}</select></label>)}<button disabled={!hasMapping} onClick={remap}>Remap filaments</button><button disabled={!hasMapping} onClick={()=>setMapping({})}>Reset mapping</button></div></details>}
 <p className="paint-legend">{channel==='supports'?'Green: support enforcer · Red: blocker':channel==='seam'?'Yellow: preferred seam · Red: avoided seam':channel==='fuzzy'?'Cyan: painted fuzzy skin':'Colors follow the selected filament slots.'} Erase restores the native default for this channel.</p>
 </>}
 {supportPreview?<SlicedSupportPreview objects={draftObjects} displayObjects={preview} bed={bed} filamentColors={filamentColors} onCreate={onPreviewSupports} onBack={()=>setSupportPreview(false)}/>:<div className="paint-preview"><SceneViewport objects={preview} selectedId={selectedId} bed={bed} mode="Paint" filamentColors={filamentColors} paintChannel={channel} paintTargetId={selectedId} paintTargetIds={paintTargetIds} paintFilamentCount={filamentCount} onPaint={paint} onPaintWheel={wheel} paintCursor={{fillAngle:tool==='bucket'&&!edgeDetection?-1:fillAngle,overhangAngle:channel==='supports'&&overhangOnly?overhangAngle:0,constraint:channel==='color'?constraint:'none',tool,radius,heightStart,height,atPointer:heightAtPointer,channel,state,color:filamentColors[(state||draft.filamentSlot||1)-1]}} clipPlane={clipPlane} onCameraDirection={direction=>{cameraForward.current=direction;}} onClippingError={setClipError} overhangAngle={channel==='supports'&&highlight&&Number.isFinite(overhangAngle)?overhangAngle:0} onSelect={()=>{}} onTransform={()=>{}} onPlaceFace={()=>{}}/></div>}
 {clipError&&<p role="alert">Cross-section unavailable: {clipError}</p>}
 {error?<p role="alert">{error}</p>:<p role="status">{status}</p>}
 <p>{tool==='gap'?'Native gap fill merges same-state patches below the source-mesh area threshold into their lowest adjacent state. It can recolor original/unpainted regions too.':tool==='circle'?'Circle uses the view direction and front-facing connected surfaces.':tool==='sphere'?'Sphere reaches connected surfaces in three dimensions, including back-facing surfaces.':tool==='bucket'?'Bucket fill follows touching subfacets with the same existing state; it preserves boundaries between states.':tool==='facet'?'Triangle changes the current native subfacet under the pointer.':tool==='height'?(heightAtPointer?'Click the model to start the painted Z range at the pointer.':'Click the model to paint the fixed world Z range.'):'The overlay shows the exact native subfacets.'} Clipping hides and excludes the removed side. Gray cross-sections are display-only and cannot be painted. Native brush detail is 0.05 mm; a larger custom detail reduces refinement work.</p>
 {!supportPreview&&<p>Shift-drag erases. Ctrl/⌘ + wheel adjusts the current brush or fill control; Alt + wheel moves the clipping plane. {channel==='color'?'Right-drag pans.':channel==='fuzzy'?'Right-drag erases on the model.':'Right-drag paints blockers or avoided seams on the model.'}</p>}
 <p>Support painting needs support enabled. Fuzzy painting needs Fuzzy Skin set to Painted only or another enabled mode.</p>
 <footer><span>Selected object · other channels retained.</span><button onClick={onClose}>Cancel painting</button><button onClick={()=>{onApply({objects:allCurrent.current,selectedId});onClose();}}>Apply painting</button></footer></Modal>;
}
