import {shrinkagePreviewWarnings} from '../shared/shrinkage-status.js';
import {resolveLayerMaterialSettings} from './layer-material-context.js';
import LayerHeightBrushPreview from './LayerHeightBrushPreview.jsx';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import Modal from './Modal.jsx';
import {layerProfileContext,initialLayerHeightProfile,adaptiveLayerHeightProfile,smoothLayerHeightProfile,updateLayerHeightProfile,normalizeLayerHeightProfile} from '../shared/variable-layers.js';
import './variable-layers.css';
const rounded=n=>Number(Number(n).toFixed(6));
export default function VariableLayersEditor({project,selectedId=project.selectedId,globalSettings={},filamentCount=1,nativeShrinkageInitialization=false,onChange,onClose}){
 const selected=project.objects.find(object=>object.id===selectedId),[profile,setProfile]=useState(()=>[...selected?.native?.layerHeightProfile||[]]),[point,setPoint]=useState(0),[quality,setQuality]=useState(.5),[radius,setRadius]=useState(5),[keepMin,setKeepMin]=useState(false),[error,setError]=useState('');
 const history=useRef([]),strokeBefore=useRef(null),profileNow=useRef(profile),[undoCount,setUndoCount]=useState(0);profileNow.current=profile;
 function clearBrushHistory(){history.current=[];setUndoCount(0);}
 function startStroke(){strokeBefore.current=[...profile];}
 function endStroke(){if(strokeBefore.current&&JSON.stringify(strokeBefore.current)!==JSON.stringify(profileNow.current)){history.current=[...history.current.slice(-99),strokeBefore.current];setUndoCount(history.current.length);}strokeBefore.current=null;}
 function undoStroke(){const previous=history.current.pop();if(previous){setProfile(previous);setUndoCount(history.current.length);setError('');}}
 const [material,setMaterial]=useState(null);
 // The snapshot key prevents a stale response from briefly enabling edits after
 // project/preset changes. Cleanup aborts all reads, including on modal close.
 const materialKey=JSON.stringify([project.ids,project.filamentIds,project.useEmbeddedSettings,project.nativeSettings,project.nativeContext,project.overrides,project.projectOverrides,project.processCorrectionDecisions,globalSettings]);
 useEffect(()=>{const controller=new AbortController();setMaterial(null);resolveLayerMaterialSettings(project,globalSettings,{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setMaterial({key:materialKey,...value});}).catch(cause=>{if(!controller.signal.aborted)setMaterial({key:materialKey,error:cause.message});});return()=>controller.abort();},[materialKey]);
 const ready=material?.key===materialKey?material:null,plate=project.plates.find(item=>item.id===selected?.plateId),effectiveSettings=ready?.settings;
 const computed=useMemo(()=>{if(!ready)return{};if(ready.error)return{error:ready.error};try{return{context:layerProfileContext(project.objects,selectedId,ready.settings,{filamentCount:ready.filamentCount,materialSettingsComplete:true,plate})};}catch(cause){return{error:cause.message};}},[project.objects,selectedId,ready,plate]),context=computed.context;
 if(!selected)return null;
 const count=profile.length/2,index=Math.min(Math.max(0,point),Math.max(0,count-1)),firstProtected=context?.firstLayerFixed?2:1,validContext=context&&Number.isFinite(context.objectHeight),width=760,height=185;
 const x=z=>30+z/context.objectHeight*width,y=h=>20+(context.maxLayerHeight-h)/(context.maxLayerHeight-context.minLayerHeight||1)*height;
 const visiblePoints=validContext?Array.from({length:count},(_,i)=>i).filter(i=>count<=3000||i===count-1||i%Math.ceil(count/3000)===0).map(i=>`${x(profile[i*2])},${y(profile[i*2+1])}`).join(' '):'';
 function run(action){clearBrushHistory();try{setProfile(action());setPoint(0);setError('');}catch(cause){setError(cause.message);}}
 function change(offset,value){clearBrushHistory();setProfile(current=>current.map((v,i)=>i===index*2+offset?value:v));setError('');}
 function add(){clearBrushHistory();const after=Math.min(Math.max(firstProtected-1,index),count-2),z=(profile[after*2]+profile[after*2+2])/2,h=(profile[after*2+1]+profile[after*2+3])/2;setProfile(current=>[...current.slice(0,after*2+2),z,h,...current.slice(after*2+2)]);setPoint(after+1);setError('');}
 function remove(){clearBrushHistory();setProfile(current=>current.filter((_,i)=>Math.floor(i/2)!==index));setPoint(Math.max(0,index-1));setError('');}
 function editGraph(event){if(!count||!context||event.buttons!==1)return;clearBrushHistory();const box=event.currentTarget.getBoundingClientRect(),z=Math.max(0,Math.min(context.objectHeight,((event.clientX-box.left)/box.width*820-30)/width*context.objectHeight)),h=Math.max(context.minLayerHeight,Math.min(context.maxLayerHeight,context.maxLayerHeight-((event.clientY-box.top)/box.height*250-20)/height*(context.maxLayerHeight-context.minLayerHeight)));let nearest=firstProtected;for(let i=firstProtected;i<count;i++)if(Math.abs(profile[i*2]-z)<Math.abs(profile[nearest*2]-z))nearest=i;setPoint(nearest);setProfile(current=>current.map((v,i)=>i===nearest*2+1?rounded(h):v));setError('');}
 function apply(){try{const objects=profile.length?updateLayerHeightProfile(project.objects,selected.id,profile,effectiveSettings,{filamentCount:ready.filamentCount,plate}):updateLayerHeightProfile(project.objects,selected.id,[],effectiveSettings,{filamentCount:ready.filamentCount,plate});onChange(objects);onClose();}catch(cause){setError(cause.message);}}
 let profileError;try{if(context)normalizeLayerHeightProfile(profile,context);}catch(cause){profileError=cause.message;}
 return <Modal className="variable-layers-editor" aria-label="Variable layer heights" onClose={onClose}>
  <header><h2>Variable layer heights · {selected.native?.objectName||selected.name}</h2><button aria-label="Close variable layers" onClick={onClose}>×</button></header>
  <p>Edit an object-wide layer-height curve. Z starts at the object's bottom. Native slicing interpolates between points; the first layer follows its configured height.</p>
  {!ready&&<p role="status">Resolving filament shrinkage settings…</p>}
  {computed.error&&<p role="alert">{computed.error}</p>}
  {context&&<><p aria-label="Layer material compensation">Used filament slots: {context.usedFilamentSlots.join(', ')||'none'} · Z compensation: {rounded(context.shrinkageCompensationZ)}×{context.shrinkageDisabledByMixedMaterials?' · Disabled because used filaments have different XY or Z shrinkage.':''}</p>{shrinkagePreviewWarnings(context,nativeShrinkageInitialization).map(warning=><p key={warning} role="status" className="variable-layer-warning">{warning}</p>)}<div className="variable-layer-controls"><label>Quality / speed<input aria-label="Adaptive quality" type="range" min="0" max="1" step=".05" value={quality} onChange={event=>setQuality(Number(event.target.value))}/><span>{quality} · 0 = finer, 1 = faster</span></label><button onClick={()=>run(()=>adaptiveLayerHeightProfile(context,quality))}>Generate adaptive layers</button><button onClick={()=>run(()=>initialLayerHeightProfile(context))}>Create uniform profile</button><button onClick={()=>{clearBrushHistory();setProfile([]);setPoint(0);setError('');}} disabled={!count}>Remove variable profile</button></div>
  <LayerHeightBrushPreview profile={profile} context={context} settings={effectiveSettings} onProfile={next=>{profileNow.current=next;setProfile(next);setError('');}} onStrokeStart={startStroke} onStrokeEnd={endStroke} onError={setError}/>
  <div className="variable-layer-controls"><button disabled={!undoCount} onClick={undoStroke}>Undo layer brush stroke</button></div>
  <svg className="variable-layer-chart" viewBox="0 0 820 250" role="img" aria-label="Variable layer height curve" onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);editGraph(event);}} onPointerMove={editGraph}>
   <rect x="30" y="20" width="760" height="185" fill="none" stroke="currentColor" opacity=".3"/><text x="30" y="16">{rounded(context.maxLayerHeight)} mm</text><text x="30" y="222">{rounded(context.minLayerHeight)} mm</text><text x="30" y="242">Z 0</text><text x="680" y="242">Z {rounded(context.objectHeight)} mm</text>
   {!!count&&<><polyline points={visiblePoints} fill="none" stroke="var(--accent,#00a884)" strokeWidth="2"/>{Number.isFinite(profile[index*2])&&Number.isFinite(profile[index*2+1])&&<circle cx={x(profile[index*2])} cy={y(profile[index*2+1])} r="5" fill="var(--accent,#00a884)"/>}</>}
  </svg>
  {!count?<p>No variable profile. Slicing uses global and height-range layer heights.</p>:<><p>{count} control points · drag the curve to adjust the nearest editable point. {context.firstLayerFixed?'The first two points preserve the native first layer.':''}</p><div className="variable-layer-controls"><button onClick={()=>setPoint(Math.max(0,index-1))} disabled={!index}>Previous point</button><label>Control point<input aria-label="Variable layer control point" type="number" min="1" max={count} value={index+1} onChange={event=>setPoint(Math.max(0,Math.min(count-1,Number(event.target.value)-1)))}/></label><button onClick={()=>setPoint(Math.min(count-1,index+1))} disabled={index===count-1}>Next point</button><label>Z (mm)<input aria-label="Variable layer point Z" type="number" min="0" max={context.objectHeight} step=".1" disabled={index<firstProtected||index===count-1} value={profile[index*2]===''?'':rounded(profile[index*2])} onChange={event=>change(0,event.target.value===''?'':Number(event.target.value))}/></label><label>Layer height (mm)<input aria-label="Variable layer point height" type="number" min={context.minLayerHeight} max={context.maxLayerHeight} step=".01" disabled={index<firstProtected} value={profile[index*2+1]===''?'':rounded(profile[index*2+1])} onChange={event=>change(1,event.target.value===''?'':Number(event.target.value))}/></label><button onClick={add} disabled={count>=100000}>Add point after selection</button><button onClick={remove} disabled={index<firstProtected||index===count-1||count<=3}>Remove selected point</button></div>
  <div className="variable-layer-controls"><label>Smoothing radius<input aria-label="Variable layer smoothing radius" type="number" min="1" max="100" step="1" value={radius} onChange={event=>setRadius(Number(event.target.value))}/></label><label><input type="checkbox" checked={keepMin} onChange={event=>setKeepMin(event.target.checked)}/> Keep minimum heights</label><button onClick={()=>run(()=>smoothLayerHeightProfile(profile,context,{radius,keepMin}))}>Smooth layer heights</button></div></>}
  {context.ranges.length>0&&<p>Adaptive generation incorporates the object's height ranges. While this variable profile is active, its curve supplies layer heights; range walls, infill, speeds and material settings still apply.</p>}
  {profileError&&<p className="variable-layer-warning">{profileError}</p>}</>}
  {error&&<p role="alert">{error}</p>}<footer><button onClick={onClose}>Cancel changes</button><button onClick={apply} disabled={!context}>Apply variable layers</button></footer>
 </Modal>;
}
