import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';
import{brimFirstLayerFromLoops,brimCornerPoints,brimFirstLayer,autoBrimEars,brimDetectionRadiusMax,defaultBrimDiameter,addBrimEar}from'../../shared/brim-ear-auto.js';
import{importNative3MF}from'../../shared/native-project.js';
const fixture=JSON.parse(await readFile(new URL('../fixtures/brim-ear-reference.json',import.meta.url),'utf8'));
const canonical=paths=>paths.map(p=>{const candidates=p.map((_,i)=>JSON.stringify([...p.slice(i),...p.slice(0,i)]));return candidates.sort()[0];}).sort();
test('native C++ polygon pipeline and source corner predicates: 81 outer/hole/negative/overlap/acute/tiny-edge cases',()=>{for(const [index,f]of fixture.entries()){const actual=brimFirstLayerFromLoops(f.volumes),paths=actual.flatMap(p=>[p.contour,...p.holes]);assert.deepEqual(canonical(paths),canonical(f.paths),`outline ${index}`);const corners=actual.flatMap(p=>[...brimCornerPoints(p.contour,f),...p.holes.flatMap(h=>brimCornerPoints([...h].reverse(),{...f,outer:false}))]);assert.deepEqual(corners.map(JSON.stringify).sort(),f.corners.map(JSON.stringify).sort(),`corners ${index}`);}});
test('default diameter uses native global first-layer width; strict right-angle boundary and duplicates preserve user ears',()=>{assert.equal(defaultBrimDiameter({nozzle_diameter:['.4'],initial_layer_line_width:'150%'}),Math.fround(9.6));assert.equal(defaultBrimDiameter({initial_layer_line_width:'.5'}),8);assert.equal(defaultBrimDiameter({}),null);const p=[[0,0],[2e7,0],[2e7,2e7],[0,2e7]];assert.equal(brimCornerPoints(p,{maxAngle:90}).length,0);assert.equal(brimCornerPoints(p,{maxAngle:91}).length,4);const first=addBrimEar([],[1,2,-.0001],8);assert.equal(addBrimEar(first,[1,2,-.0001],8),first);assert.equal(addBrimEar(first,[1,2,-.0001],10).length,2);assert.throws(()=>addBrimEar(first,[1,2,0],-1),/radius/);});
test('mesh section honors grouped transforms and negatives, ignores modifiers, and rejects damaged topology',async()=>{const project=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url))),base=project.objects[0];base.position=[60,70,0];base.rotation=[0,0,90];base.scale=[-1,1,1];const positive={...base,native:{...base.native,groupId:'g'}};const negative={...structuredClone(positive),id:'negative',position:[60,70,0],scale:[.3,.3,1],native:{...positive.native,partType:'negative_part'}};const modifier={...negative,id:'modifier',position:[100,100,0],native:{...positive.native,partType:'modifier_part'}};const layer=brimFirstLayer([positive,negative,modifier],positive.id);assert.equal(layer.length,1);assert.equal(layer[0].holes.length,1);const generated=autoBrimEars([],layer,{diameter:8});assert.equal(generated.length,4);for(const e of generated){assert.equal(e.radius,4);assert.ok(e.position[0]>59&&e.position[0]<81);assert.ok(e.position[1]>69&&e.position[1]<91);}assert.equal(autoBrimEars(generated,layer,{diameter:8}).length,4);assert.equal(brimDetectionRadiusMax(layer),29);const damaged={...positive,positions:positive.positions.slice(0,-18)};assert.throws(()=>brimFirstLayer([damaged],damaged.id),/open section/);});
test('disconnected ears connect through an ear chain without mutating geometry',async()=>{const{disconnectedBrimEars}=await import('../../shared/brim-ear-auto.js'),layer=brimFirstLayerFromLoops([{loops:[[[0,0],[20e6,0],[20e6,20e6],[0,20e6]]]}]);const ears=[{position:[-12,10,0],radius:3},{position:[-7,10,0],radius:3},{position:[-2,10,0],radius:3},{position:[-20,10,0],radius:3}],before=structuredClone(ears);assert.deepEqual(disconnectedBrimEars(ears,layer),[3]);assert.deepEqual(ears,before);});
