import test from 'node:test';
import assert from 'node:assert/strict';
import { BoxGeometry, ExtrudeGeometry, Path, Shape } from 'three';
import { createCalibrationPlan, applyCalibrationOverrides, applyCalibrationGcode, calibrationLayerCommand, interpolateCalibrationValue } from '../../shared/calibration.js';
import { clipAtZ, prepareCalibrationMesh } from '../../shared/calibration-geometry.js';
import { createMesh, analyzeMesh, meshBounds } from '../../shared/geometry.js';
import { calibrationBed } from '../../server/calibration.js';

const selection = () => ({
  printer: { name:'Test printer', printer_technology:'FFF', gcode_flavor:'marlin2', nozzle_diameter:['0.4'], printable_height:'250', printable_area:['0x0','250x0','250x210','0x210'] },
  process: { name:'Test process', layer_height:'0.2', line_width:'0.45', outer_wall_speed:'120', layer_change_gcode:'; keep native macro', wall_loops:'3' },
  filament: { name:'Test filament', filament_max_volumetric_speed:['12'], nozzle_temperature:['220'] }
});
const temperature = { mode:'temperature', start:230, end:220, step:5 };
const pa = { mode:'pressure-advance', start:0, end:0.01, step:0.002 };

test('temperature plan uses native labelled block coordinates, nozzle scale and native preset scope',()=>{
  const native = selection(); native.printer.nozzle_diameter=['0.6'];
  const plan = createCalibrationPlan(temperature,native);
  assert.deepEqual(plan.model,{resource:'temperature_tower/temperature_tower.drc',minZ:540,maxZ:570,scale:1.4999999999999998});
  assert.ok(Math.abs(plan.height-45)<1e-8);
  const applied=applyCalibrationOverrides(native,plan);
  assert.equal(applied.process.layer_height,'0.3'); assert.deepEqual(applied.filament.nozzle_temperature,['230']);
  assert.equal(applied.process.layer_change_gcode,'; keep native macro'); assert.equal(native.process.wall_loops,'3');
});

test('calibration rejects unsupported modes, arbitrary keys, invalid ranges, oversized towers and multiple extruders',()=>{
  for(const input of [{...temperature,mode:'unknown-mode'},{...temperature,path:'/tmp/model'},{...temperature,start:NaN},{...temperature,end:231},{...temperature,step:10},{...temperature,start:232},{...pa,step:0},{...pa,end:1},{...pa,end:3}]) assert.throws(()=>createCalibrationPlan(input,selection()));
  const multiple=selection();multiple.printer.nozzle_diameter=['0.4','0.4'];assert.throws(()=>createCalibrationPlan(pa,multiple),/one extruder/);
  const small=selection();small.printer.printable_height='10';assert.throws(()=>createCalibrationPlan(temperature,small),/height/);
});

test('PA plan derives bounded wall speed from the native flow area and 1 mm height schedule',()=>{
  const plan=createCalibrationPlan(pa,selection());
  assert.equal(plan.height,6);assert.equal(plan.overrides.process.outer_wall_speed,'120');
  assert.equal(plan.overrides.process.brim_type,'brim_ears');assert.equal(plan.overrides.process.seam_position,'back');
  assert.deepEqual(plan.overrides.filament.adaptive_pressure_advance,['0']);
  const slow=selection();slow.filament.filament_max_volumetric_speed=['5'];
  assert.equal(createCalibrationPlan(pa,slow).overrides.process.outer_wall_speed,'61');
  assert.equal(calibrationLayerCommand(plan,{index:3,count:30,z:1.2}),'M900 K0.002');
});

test('PA commands follow the selected native firmware flavor',()=>{
  const commands={klipper:'SET_PRESSURE_ADVANCE ADVANCE=0.004',reprapfirmware:'M572 D0 S0.004',repetier:'M233 X0.004 Y0.004',marlin:'M900 K0.004',marlin2:'M900 K0.004'};
  for(const [flavor,expected] of Object.entries(commands)) {const native=selection();native.printer.gcode_flavor=flavor;assert.equal(calibrationLayerCommand(createCalibrationPlan(pa,native),{index:4,count:30,z:2.8}),expected);}
  const unsupported=selection();unsupported.printer.gcode_flavor='no-extrusion';assert.throws(()=>createCalibrationPlan(pa,unsupported),/flavor/);
  const precise=createCalibrationPlan({mode:'pressure-advance',start:0,end:0.00000004,step:0.00000002},selection());
  assert.equal(calibrationLayerCommand(precise,{index:4,count:30,z:1.2}),'M900 K2e-8');
  assert.throws(()=>createCalibrationPlan({mode:'pressure-advance',start:1,end:1.00001,step:0.000005},selection()),/precision/);
});

test('temperature interpolation follows the native first-two-layer and final-layer behavior',()=>{
  assert.deepEqual([0,1,2,3,4,5].map(index=>interpolateCalibrationValue(230,220,index,6,5)),[230,230,225,225,220,220]);
  assert.throws(()=>interpolateCalibrationValue(230,220,2,2,5),/index/);
});

const rawGcode = () => '; generated by OrcaSlicer 2.4.2\n; total layer number: 3\n' + [0.2,0.4,0.6].map(z=>`;LAYER_CHANGE\n;Z:${z}\n;HEIGHT:0.2\n;BEFORE_LAYER_CHANGE\nG92 E0\n;AFTER_LAYER_CHANGE\n;_SET_FAN_SPEED_CHANGING_LAYER\nG1 X10 Y10 E1 F1200\n`).join('') + '; total layers count = 3\n';
test('postprocessor inserts actual calibration commands after native layer macros and preserves motion',()=>{
  const plan=createCalibrationPlan(temperature,selection());const raw=rawGcode();const result=applyCalibrationGcode(raw,plan);
  assert.equal(result.summary.layers,3);assert.match(result.gcode,/CHANGING_LAYER\nM104 S230/);assert.match(result.summary.lastCommand,/M104 S220/);
  assert.deepEqual(result.gcode.split('\n').filter(line=>line.startsWith('G')),raw.split('\n').filter(line=>line.startsWith('G')));
  assert.throws(()=>applyCalibrationGcode(result.gcode,plan),/already applied/);
});
test('postprocessor refuses incompatible versions, missing anchors and inconsistent layer metadata',()=>{
  const plan=createCalibrationPlan(pa,selection());
  for(const raw of [rawGcode().replace('2.4.2','2.4.1'),rawGcode().replace('number: 3','number: 4'),rawGcode().replace(';_SET_FAN_SPEED_CHANGING_LAYER','; absent'),rawGcode().replace(';Z:0.4',';Z:0.1')])assert.throws(()=>applyCalibrationGcode(raw,plan));
});

test('clipped geometry is capped with consistent winding and preserves true volume',()=>{
  const geometry=new BoxGeometry(20,10,40).toNonIndexed();geometry.translate(0,0,20);
  let points=clipAtZ(geometry.attributes.position.array,15,false);points=clipAtZ(points,5,true);
  const mesh=createMesh({positions:points});const analysis=analyzeMesh(mesh);
  assert.equal(analysis.manifold,true);assert.equal(analysis.inconsistentWindingEdges,0);assert.ok(Math.abs(analysis.volume-2000)<1e-3);
  assert.deepEqual(meshBounds(mesh).size,[20,10,10]);geometry.dispose();
});

test('clipping retains enclosed holes instead of filling the calibration cut solid',()=>{
  const outline=new Shape();outline.moveTo(-10,-10);outline.lineTo(10,-10);outline.lineTo(10,10);outline.lineTo(-10,10);outline.closePath();
  const hole=new Path();hole.moveTo(-5,-5);hole.lineTo(-5,5);hole.lineTo(5,5);hole.lineTo(5,-5);hole.closePath();outline.holes.push(hole);
  const geometry=new ExtrudeGeometry(outline,{depth:10,bevelEnabled:false});
  const positions=clipAtZ(clipAtZ(geometry.attributes.position.array,6,false),4,true);
  const analysis=analyzeMesh(createMesh({positions}));assert.equal(analysis.manifold,true);assert.ok(Math.abs(analysis.volume-600)<0.001);geometry.dispose();
});

test('calibration placement uses the real bed and rejects unsupported bed shapes',()=>{
  const native=selection(),plan=createCalibrationPlan(pa,native),bed=calibrationBed(native);
  const geometry=new BoxGeometry(70,70,60).toNonIndexed();geometry.translate(0,0,30);
  const mesh=prepareCalibrationMesh(geometry.attributes.position.array,plan,bed);
  assert.deepEqual(meshBounds(mesh).size,[70,70,6]);assert.equal(meshBounds(mesh).min[2],0);
  const irregular=selection();irregular.printer.printable_area=['0x0','250x0','200x210','0x210'];assert.throws(()=>calibrationBed(irregular),/rectangular/);geometry.dispose();
});

const frequency = { mode: 'input-shaping-frequency', testModel: 'fast', shaperType: 'auto', frequencyStartX: 15, frequencyEndX: 110, frequencyStartY: 20, frequencyEndY: 100, damping: 0.15 };
const damping = { mode: 'input-shaping-damping', testModel: 'ringing', shaperType: 'auto', frequencyX: 30, frequencyY: 40, start: 0, end: 0.4 };
test('input shaping generates native models and complete spiral, acceleration and cooling settings',()=>{
  const native=selection(),plan=createCalibrationPlan(frequency,native),applied=applyCalibrationOverrides(native,plan);
  assert.equal(plan.height,60);assert.equal(plan.model.resource,'input_shaping/fast_tower_test.drc');assert.equal(plan.request.shaperType,'ZV');
  assert.equal(applied.process.spiral_mode,'1');assert.equal(applied.process.outer_wall_speed,'200');assert.equal(applied.process.default_acceleration,'20000');
  assert.equal(applied.printer.input_shaping_emit,'0');assert.deepEqual(applied.filament.slow_down_for_layer_cooling,['0']);
  assert.deepEqual(applied.filament.pressure_advance,['0']);assert.deepEqual(applied.printer.machine_max_jerk_x,['10']);
  native.process.layer_height='0.16';native.printer.machine_max_junction_deviation=['0.02'];native.filament.enable_pressure_advance=['1'];native.filament.pressure_advance=['0.04'];
  const damp=applyCalibrationOverrides(native,createCalibrationPlan(damping,native));
  assert.equal(damp.process.layer_height,'0.16');assert.deepEqual(damp.printer.machine_max_junction_deviation,['0.25']);assert.deepEqual(damp.filament.pressure_advance,['0.04']);
});
test('input shaping validates native ranges, firmware-specific types and request fields',()=>{
  for(const invalid of [{...frequency,frequencyStartX:-1},{...frequency,frequencyEndY:501},{...frequency,damping:1},{...frequency,shaperType:'Disable'},{...frequency,step:1},{...frequency,testModel:'../../model'},{...damping,end:1.1},{...damping,start:.4},{...damping,frequencyY:501}]) assert.throws(()=>createCalibrationPlan(invalid,selection()));
  const legacy=selection();legacy.printer.gcode_flavor='marlin';assert.throws(()=>createCalibrationPlan(frequency,legacy),/requires/);
  const reprap=selection();reprap.printer.gcode_flavor='reprapfirmware';const plan=createCalibrationPlan({...frequency,shaperType:'EI2'},reprap);assert.equal(plan.request.frequencyStartY,15);assert.equal(plan.request.frequencyEndY,110);
  assert.throws(()=>createCalibrationPlan({...frequency,shaperType:'2HUMP_EI'},reprap),/shaper type/);
});
test('input shaping follows native frequency first-layer and second-layer firmware sequences',()=>{
  const native=selection();native.printer.gcode_flavor='klipper';const plan=createCalibrationPlan({...frequency,shaperType:'MZV'},native);
  assert.equal(calibrationLayerCommand(plan,{index:0,count:300,z:.2}),'SET_INPUT_SHAPER SHAPER_FREQ_X=15.00\nSET_INPUT_SHAPER SHAPER_FREQ_Y=20.00');
  assert.equal(calibrationLayerCommand(plan,{index:1,count:300,z:.4}),'SET_INPUT_SHAPER SHAPER_TYPE=MZV DAMPING_RATIO_X=0.150 DAMPING_RATIO_Y=0.150\nSET_VELOCITY_LIMIT MINIMUM_CRUISE_RATIO=0');
  assert.equal(calibrationLayerCommand(plan,{index:299,count:300,z:60}),'SET_INPUT_SHAPER SHAPER_FREQ_X=110.00\nSET_INPUT_SHAPER SHAPER_FREQ_Y=100.00');
  const marlin=createCalibrationPlan(frequency,selection());assert.equal(calibrationLayerCommand(marlin,{index:1,count:300,z:.4}),'M593 D0.150');
  native.printer.gcode_flavor='reprapfirmware';const rrf=createCalibrationPlan({...frequency,shaperType:'EI2'},native);assert.equal(calibrationLayerCommand(rrf,{index:1,count:300,z:.4}),'M593 P"EI2" S0.150');assert.equal(calibrationLayerCommand(rrf,{index:299,count:300,z:60}),'M593 F110.00');
});
test('damping preserves native zero no-op, initialization and float32 interpolation instead of fabricating resets',()=>{
  const native=selection();native.printer.gcode_flavor='klipper';const plan=createCalibrationPlan({...damping,shaperType:'ZV'},native);
  assert.equal(calibrationLayerCommand(plan,{index:0,count:300,z:.2}),'');
  assert.equal(calibrationLayerCommand(plan,{index:1,count:300,z:.4}),'SET_VELOCITY_LIMIT MINIMUM_CRUISE_RATIO=0\nSET_INPUT_SHAPER SHAPER_TYPE=ZV SHAPER_FREQ_X=30.00\nSET_INPUT_SHAPER SHAPER_TYPE=ZV SHAPER_FREQ_Y=40.00');
  assert.equal(calibrationLayerCommand(plan,{index:299,count:300,z:60}),'SET_INPUT_SHAPER DAMPING_RATIO_X=0.400 DAMPING_RATIO_Y=0.400');
  assert.equal(calibrationLayerCommand(plan,{index:150,count:300,z:30.2}),'SET_INPUT_SHAPER DAMPING_RATIO_X=0.201 DAMPING_RATIO_Y=0.201');
  const raw=rawGcode(),result=applyCalibrationGcode(raw,plan);assert.deepEqual(result.gcode.split('\n').filter(line=>line.startsWith('G')),raw.split('\n').filter(line=>line.startsWith('G')));
  assert.match(result.gcode,/CHANGING_LAYER\n ; Orca Web calibration input-shaping-damping, layer 1/);
});
test('only a final native spiral closing layer may repeat its preceding Z marker',()=>{
  const plan=createCalibrationPlan(damping,selection()),raw=rawGcode().replace(';Z:0.6',';Z:0.4').replace('layers count = 3','layers count = 2')+'; spiral_mode = 1\n';
  const result=applyCalibrationGcode(raw,plan);assert.equal(result.summary.layers,3);assert.equal(result.summary.scheduleLayers,2);assert.equal(result.summary.closingLayer,true);
  const native=raw.replace('layers count = 2','layers count = 3');assert.throws(()=>applyCalibrationGcode(native,plan),/schedule layer count/);
  const commands=result.gcode.split('\n').filter(line=>line.includes('Orca Web calibration'));assert.equal(commands[1].split(' ;')[0],commands[2].split(' ;')[0]);
  assert.throws(()=>applyCalibrationGcode(raw.replace('; spiral_mode = 1',''),plan),/monotonically/);
  assert.throws(()=>applyCalibrationGcode(raw.replace(';Z:0.4',';Z:0.2'),plan),/monotonically/);
  assert.throws(()=>applyCalibrationGcode(raw,createCalibrationPlan(temperature,selection())),/monotonically/);
});
test('cornering maps positive Marlin junction deviation and other presets to native defaults and units',()=>{
  const native=selection();native.printer.machine_max_junction_deviation=['0.02'];
  const junction=createCalibrationPlan({mode:'cornering',testModel:'fast'},native);
  assert.equal(junction.corneringKind,'junction-deviation');assert.equal(junction.request.end,.25);assert.equal(junction.request.start,0);assert.deepEqual(junction.overrides.printer.machine_max_junction_deviation,['0.25']);
  assert.equal(junction.overrides.process.default_acceleration,'2000');assert.deepEqual(junction.overrides.filament.filament_max_volumetric_speed,['200']);
  const jerk=createCalibrationPlan({mode:'cornering',testModel:'scv'},selection());assert.equal(jerk.corneringKind,'jerk');assert.equal(jerk.request.end,15);assert.equal(jerk.height,100);assert.equal(jerk.model.resource,'cornering/SCV-V2.drc');assert.deepEqual(jerk.overrides.printer.machine_max_jerk_x,['15']);
  for(const bad of [{mode:'cornering',start:-1},{mode:'cornering',end:.4},{mode:'cornering',step:1},{mode:'cornering',testModel:'userfile'}])assert.throws(()=>createCalibrationPlan(bad,native));
});
test('cornering commands match native firmware parameters and zero no-op behavior',()=>{
  for(const [flavor,expected] of Object.entries({marlin:'M205 X15 Y15',marlin2:'M205 X15 Y15',reprapfirmware:'M205 X15 Y15',klipper:'SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=15',repetier:'M207 X15'})){
    const native=selection();native.printer.gcode_flavor=flavor;const plan=createCalibrationPlan({mode:'cornering'},native);assert.equal(calibrationLayerCommand(plan,{index:299,count:300,z:60}),expected);
  }
  const native=selection();native.printer.machine_max_junction_deviation=['0.02'];const plan=createCalibrationPlan({mode:'cornering'},native);
  assert.equal(calibrationLayerCommand(plan,{index:0,count:300,z:.2}),'');assert.equal(calibrationLayerCommand(plan,{index:150,count:300,z:30.2}),'M205 J0.125');assert.equal(calibrationLayerCommand(plan,{index:299,count:300,z:60}),'M205 J0.250');
});
test('cornering rejects overlapping schedule commands and removes stale time/progress while retaining material',()=>{
  const native=selection(),jerk=createCalibrationPlan({mode:'cornering'},native);
  const raw=rawGcode()+'; spiral_mode = 1\n; estimated printing time (normal mode) = 10m\n; estimated first layer printing time (normal mode) = 1m\n; filament used [g] = 2.4\nM73 P30 R7\n';
  const result=applyCalibrationGcode(raw,jerk);assert.doesNotMatch(result.gcode,/^M73\b|^; estimated printing time|^; estimated first layer printing time/m);assert.match(result.gcode,/filament used \[g\] = 2.4/);
  assert.equal(result.summary.timeEstimate,'unavailable-after-cornering-calibration');assert.throws(()=>applyCalibrationGcode(raw.replace('G1 X10','M205 X9 Y9\nG1 X10'),jerk),/competing cornering/);
  native.printer.machine_max_junction_deviation=['0.02'];const jd=createCalibrationPlan({mode:'cornering'},native);
  assert.doesNotThrow(()=>applyCalibrationGcode(raw.replace('G1 X10','M205 X9 Y9\nG1 X10'),jd),'Independent classic jerk does not overwrite Marlin JD');
  assert.throws(()=>applyCalibrationGcode(raw.replace('G1 X10','M205 J0.12\nG1 X10'),jd),/competing cornering/);
});
test('Bambu native layer and Z tags preserve temperature scheduling and original reserved comments',()=>{
 const plan=createCalibrationPlan(temperature,selection()),compatible=rawGcode(),bambu=compatible.replaceAll(';LAYER_CHANGE','; CHANGE_LAYER').replaceAll(';Z:','; Z_HEIGHT: ').replaceAll(';HEIGHT:','; LAYER_HEIGHT: '),expected=applyCalibrationGcode(compatible,plan),actual=applyCalibrationGcode(bambu,plan);
 assert.deepEqual(actual.summary,expected.summary);assert.deepEqual(actual.gcode.split('\n').filter(line=>/^[GM]\d/.test(line)),expected.gcode.split('\n').filter(line=>/^[GM]\d/.test(line)));assert.ok(actual.gcode.includes('; CHANGE_LAYER\n; Z_HEIGHT: 0.2'));assert.ok(!actual.gcode.includes(';LAYER_CHANGE'));
 assert.throws(()=>applyCalibrationGcode(bambu.replace('; Z_HEIGHT: 0.4','; Z_HEIGHT: 0.1'),plan),/monotonically/);
});
