import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{importNative3MF,exportNative3MF}from'../../shared/native-project.js';import{cutNativeGroupWithConnectors,cutPlaneFrame,normalizeConnectorPlans}from'../../shared/cut-connectors.js';import{arrangeCutResult}from'../../shared/geometry-cut.js';import{analyzeMesh,meshBounds,sceneBounds}from'../../shared/geometry.js';import{normalizeNativeParts}from'../../shared/native-object-settings.js';
const plan=(extra={})=>({type:'plug',style:'prism',shape:'circle',u:70,v:80,diameter:3,depth:3,radiusTolerance:.1,heightTolerance:.2,rotation:0,...extra});
async function setup(){const p=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));p.objects[0].position=[60,70,0];return p;}
const approx=(a,b)=>assert.ok(Math.abs(a-b)<2e-5,`${a} ~ ${b}`);
test('plug clearances and cut identity match native processed-volume semantics',async()=>{
 const p=await setup(),before=JSON.stringify(p.objects),result=cutNativeGroupWithConnectors(p.objects,p.objects[0].id,{offset:10,connectors:[plan()]});assert.equal(result.created.length,4);assert.equal(JSON.stringify(p.objects),before);const hole=result.upper.find(o=>o.native.cutConnector),solid=result.lower.find(o=>o.native.cutConnector);assert.equal(hole.native.partType,'negative_part');assert.equal(solid.native.partType,'normal_part');assert.deepEqual(result.created.map(o=>o.native.cutId),Array(4).fill(result.created[0].native.cutId));assert.equal(result.created[0].native.cutId.checkSum,'2');assert.equal(result.created[0].native.cutId.connectorsCount,'1');
 const hb=meshBounds(hole),sb=meshBounds(solid);approx(hb.min[2],9.95);approx(hb.max[2],13.15);approx(hb.size[0],3.2);approx(sb.min[2],10);approx(sb.max[2],13);approx(sb.size[0],3);assert.ok(result.created.every(o=>analyzeMesh(o).manifold));normalizeNativeParts(result.created);const q=importNative3MF(exportNative3MF({...p,objects:result.created}));assert.equal(q.objects.filter(o=>o.native.cutConnector).length,2);
});
test('dowels produce independent upright solids and two tolerance-expanded holes with native preview offsets',async()=>{
 for(const style of ['prism','frustum']){const p=await setup(),result=cutNativeGroupWithConnectors(p.objects,p.objects[0].id,{offset:10,connectors:[plan({type:'dowel',style,shape:'hexagon'})]});assert.equal(result.created.length,5);assert.equal(result.dowels.length,1);assert.equal(new Set(result.created.map(o=>o.native.groupId)).size,3);assert.equal(result.created[0].native.cutId.checkSum,'3');const upper=result.upper.find(o=>o.native.cutConnector),lower=result.lower.find(o=>o.native.cutConnector);approx(meshBounds(upper).min[2],9.95);approx(meshBounds(lower).max[2],10.05);approx(meshBounds(result.dowels[0]).min[2],0);approx(meshBounds(result.dowels[0]).size[2],6);assert.ok(result.created.every(o=>analyzeMesh(o).manifold));const arranged=arrangeCutResult(result,{width:250,depth:210,height:250});assert.equal(arranged.dowels.length,1);for(const groupId of new Set(arranged.created.map(o=>o.native.groupId)))approx(sceneBounds(arranged.created.filter(o=>o.native.groupId===groupId&&o.native.partType==='normal_part')).min[2],0);normalizeNativeParts(arranged.created);}
});
test('snap and asymmetric polygon connectors retain native geometry on oblique planes',async()=>{
 const p=await setup(),normal=[1,0,1],offset=80/Math.sqrt(2),frame=cutPlaneFrame(normal,offset),point=[70,80,10],u=point.reduce((s,v,i)=>s+v*frame.u[i],0),v=point.reduce((s,v,i)=>s+v*frame.v[i],0);
 for(const type of ['plug','dowel','snap']){const result=cutNativeGroupWithConnectors(p.objects,p.objects[0].id,{normal,offset,connectors:[plan({type,u,v,shape:'triangle',style:'frustum',depth:4,rotation:37})]});assert.ok(result.created.every(o=>analyzeMesh(o).manifold));assert.ok(result.created.some(o=>o.native.cutConnector?.type===type));if(type==='snap'){const solid=result.lower.find(o=>o.native.cutConnector);assert.equal(solid.positions.length/9,252);assert.equal(result.upper.find(o=>o.native.cutConnector).positions.length/9,1440);}}
});
test('invalid placement, intersecting negative regions and malformed plans fail without changing the source',async()=>{
 const p=await setup(),source=JSON.stringify(p.objects);const run=connectors=>cutNativeGroupWithConnectors(p.objects,p.objects[0].id,{offset:10,connectors});assert.throws(()=>run([plan({u:50})]),/outside.*contour/);assert.throws(()=>run([plan(),plan({u:71})]),/overlap/);assert.throws(()=>run([plan({depth:20})]),/bounds/);assert.throws(()=>cutNativeGroupWithConnectors(p.objects,p.objects[0].id,{offset:10,keep:'lower',connectors:[plan()]}),/both/);assert.throws(()=>normalizeConnectorPlans([plan({type:'snap',depth:2})]),/snap depth/);assert.throws(()=>normalizeConnectorPlans([plan({diameter:NaN})]),/diameter/);assert.equal(JSON.stringify(p.objects),source);
 const hole=structuredClone(p.objects[0]);hole.id='hole';hole.native.partType='negative_part';hole.scale=[.2,.2,1];p.objects.push(hole);assert.throws(()=>run([plan({diameter:1})]),/negative volume/);
});
test('repeated cuts increment source family counters and synchronize surviving peers without changing unrelated families',async()=>{
 const p=await setup(),body=p.objects[0];body.native.cutId={id:'9007199254740997',checkSum:'2',connectorsCount:'4'};body.native.layerHeightProfile=[0,.2,10,.2,20,.2];const peer=structuredClone(body);peer.id='peer';peer.native.groupId='peer';peer.position[0]=110;const unrelated=structuredClone(peer);unrelated.id='other';unrelated.native.groupId='other';unrelated.native.cutId={id:'8',checkSum:'2',connectorsCount:'1'};p.objects.push(peer,unrelated);
 const result=cutNativeGroupWithConnectors(p.objects,body.id,{offset:10,connectors:[plan()]});assert.equal(result.report.cutFamilyUpdate.id,body.native.cutId.id);assert.equal(result.report.cutFamilyUpdate.checkSum,'3');assert.equal(result.report.cutFamilyUpdate.connectorsCount,'5');assert.equal(result.upper.find(o=>o.native.cutConnector).name,'Connector-5');assert.deepEqual(result.objects.find(o=>o.id==='peer').native.cutId,result.report.cutFamilyUpdate);assert.equal(result.objects.find(o=>o.id==='other'),unrelated);assert.ok(result.created.every(o=>!o.native.layerHeightProfile?.length));assert.ok(result.report.resetLayerProfiles>0);
 const plain=cutNativeGroupWithConnectors(p.objects,body.id,{offset:10});assert.equal(plain.report.cutFamilyUpdate.checkSum,'3');assert.equal(plain.report.cutFamilyUpdate.connectorsCount,'4');
});
