import test from 'node:test';import assert from 'node:assert/strict';import {createMesh} from '../../shared/geometry.js';import {decodeFacet,encodeFacet} from '../../shared/facet-codec.js';import {usedPaintFilaments,remapPaintFilaments} from '../../shared/filament-remap.js';
const mesh=(id,slot,role='normal_part')=>createMesh({id,name:id,plateId:'plate',positions:[0,0,0,10,0,0,0,10,0],filamentSlot:slot,native:{groupId:'group',partType:role,objectSettings:{extruder:'1',wall_loops:'3'},partSettings:slot===2?{extruder:'2'}:{}}});
test('filament remapping swaps native leaves simultaneously and includes base part and object fallback without changing geometry',()=>{
 const code=encodeFacet({split:3,side:0,children:[{state:0},{state:1},{state:2},{state:3}]}),a={...mesh('a',1),painting:{version:1,winding:-1,color:{0:code},supports:{0:'4'},seam:{0:'8'},fuzzy:{0:'4'}}},b=mesh('b',2),modifier=mesh('modifier',1,'modifier_part'),other={...mesh('other',2),native:{...mesh('other',2).native,groupId:'other'}},source=[a,b,modifier,other],snapshot=structuredClone(source);
 assert.deepEqual(usedPaintFilaments(source,'a',{filamentCount:3}),[1,2,3]);const result=remapPaintFilaments(source,'a',{1:2,2:1},{filamentCount:3});assert.equal(result.report.changedParts,2);assert.equal(result.report.changedFacets,1);assert.deepEqual(decodeFacet(result.objects[0].painting.color[0]).tree.children.map(child=>child.state),[0,2,1,3]);assert.equal(result.objects[0].filamentSlot,2);assert.equal(result.objects[1].filamentSlot,1);assert.equal(result.objects[1].native.partSettings.extruder,'1');for(const object of result.objects.slice(0,3))assert.equal(object.native.objectSettings.extruder,'2');assert.equal(result.objects[2].filamentSlot,1);assert.equal(result.objects[3],other);assert.equal(result.objects[0].painting.winding,-1);assert.deepEqual(result.objects[0].painting.supports,a.painting.supports);assert.deepEqual(source,snapshot);assert.equal(result.objects[0].positions,a.positions);
});
test('mapping identity is a no-op and invalid source, target, role and group settings fail before edits',()=>{
 const a=mesh('a',1),b=mesh('b',2);assert.equal(remapPaintFilaments([a],'a',{1:1},{filamentCount:2}).objects[0],a);for(const mapping of [{0:1},{1:0},{17:1},{1:3},{1:'2'},[]])assert.throws(()=>remapPaintFilaments([a],'a',mapping,{filamentCount:2}),/mapping|slots/);assert.throws(()=>remapPaintFilaments([a],'missing',{1:2},{filamentCount:2}),/normal part/);assert.throws(()=>remapPaintFilaments([a,{...b,native:{...b.native,objectSettings:{extruder:'2'}}}],'a',{1:2},{filamentCount:2}),/inconsistent/);
});
