import test from 'node:test';import assert from 'node:assert/strict';import{BoxGeometry}from'three';
import{createCalibrationPlan,applyCalibrationGcode}from'../../shared/calibration.js';
import{FLOW_RATIO_METHODS,flowRatioForModifier,prepareFlowRatioObjects}from'../../shared/flow-ratio-calibration.js';
import{createMesh,meshBounds}from'../../shared/geometry.js';
const selection=()=>({printer:{name:'Printer',gcode_flavor:'marlin2',nozzle_diameter:['0.4'],printable_height:'250',printable_area:['0x0','250x0','250x210','0x210']},process:{name:'Process',initial_layer_print_height:'0.2',top_surface_speed:'100',internal_solid_infill_speed:'150'},filament:{name:'Filament',filament_flow_ratio:['0.98'],filament_max_volumetric_speed:['20']}});
function fixtures(method){return FLOW_RATIO_METHODS[method].modifiers.map((modifier,index)=>{const geometry=new BoxGeometry(20,20,2).toNonIndexed();geometry.translate((index%4)*23,Math.floor(index/4)*23,1);const mesh=createMesh({id:`part-${index}`,name:'flowrate_'+(modifier<0?'m'+Math.abs(modifier):modifier),positions:geometry.attributes.position.array});geometry.dispose();return mesh;});}
test('flow methods use native percent versus additive formulas and source-specific sample lists',()=>{
 const native=selection(),coarse=createCalibrationPlan({mode:'flow-ratio',method:'coarse'},native),yolo=createCalibrationPlan({mode:'flow-ratio',method:'yolo-fine'},native);
 assert.equal(coarse.inputFormat,'3mf');assert.equal(coarse.height,2);assert.equal(coarse.flow.modifiers.length,9);assert.equal(yolo.flow.modifiers.length,16);assert.equal(flowRatioForModifier(coarse,20),1.176);assert.equal(flowRatioForModifier(yolo,.035),1.015);assert.ok(yolo.flow.modifiers.includes(-.04));
 assert.equal(coarse.objectSettings.calib_flowrate_topinfill_special_order,'1');assert.equal(coarse.objectSettings.top_shell_layers,'5');assert.equal(coarse.objectSettings.bottom_shell_layers,'2');assert.equal(coarse.objectSettings.top_surface_pattern,'archimedeanchords');
 assert.equal(coarse.overrides.process.layer_height,'0.2');assert.equal(coarse.overrides.process.initial_layer_print_height,'0.2');
});
test('flow geometry preserves labels and per-object ratios with ten-layer scaling and group centering',()=>{
 const native=selection();native.printer.nozzle_diameter=['0.8'];const plan=createCalibrationPlan({mode:'flow-ratio',method:'fine',pattern:'monotonic'},native);
 assert.equal(plan.height,4);assert.ok(Math.abs(plan.flow.xyScale-4/3)<1e-8);
 const prepared=prepareFlowRatioObjects(fixtures('fine'),plan,{min:[0,0,0],max:[250,210,250]});assert.equal(prepared.objects.length,10);
 for(const object of prepared.objects){assert.ok(Math.abs(meshBounds(object).size[2]-4)<1e-5);assert.equal(object.native.objectSettings.top_surface_pattern,'monotonic');assert.equal(object.native.partType,'normal_part');assert.ok(Number(object.native.objectSettings.print_flow_ratio)>0);assert.equal(meshBounds(object).min[2],0);}
 const zero=prepared.specimens.find(item=>item.modifier===0);assert.equal(zero.flowRatio,.98);assert.equal(prepared.specimens.find(item=>item.modifier===-9).flowRatio,.8918);
});
test('flow plan rejects unknown fields, bad ranges and unsafe substitutions for labelled native specimens',()=>{
 for(const bad of [{mode:'flow-ratio',method:'arbitrary'},{mode:'flow-ratio',pattern:'unknown'},{mode:'flow-ratio',start:1}])assert.throws(()=>createCalibrationPlan(bad,selection()));
 const native=selection();native.filament.filament_flow_ratio=['0'];assert.throws(()=>createCalibrationPlan({mode:'flow-ratio'},native),/flow ratio/);native.filament.filament_flow_ratio=['1.99'];assert.throws(()=>createCalibrationPlan({mode:'flow-ratio'},native),/maximum 2/);
 const plan=createCalibrationPlan({mode:'flow-ratio',method:'coarse'},selection()),objects=fixtures('coarse');objects[0].name='cube';assert.throws(()=>prepareFlowRatioObjects(objects,plan,{min:[0,0,0],max:[250,210,250]}),/label/);assert.throws(()=>prepareFlowRatioObjects(fixtures('coarse'),plan,{min:[0,0,0],max:[30,30,250]}),/fit/);
});
test('flow output validation requires every prepared native specimen and preserves native moves and estimates',()=>{
 let plan=createCalibrationPlan({mode:'flow-ratio',method:'coarse'},selection());const prepared=prepareFlowRatioObjects(fixtures('coarse'),plan,{min:[0,0,0],max:[250,210,250]});plan={...plan,specimens:prepared.specimens};
 const raw='; generated by OrcaSlicer 2.4.2\n; estimated printing time (normal mode) = 20m\n'+plan.specimens.map((item,index)=>`; printing object ${item.name} id:${index} copy 0\n;TYPE:Top surface\nG1 X10 Y10 E1 F1000\n`).join('');
 const output=applyCalibrationGcode(raw,plan);assert.equal(output.summary.specimenCount,9);assert.ok(output.gcode.endsWith(raw));assert.match(output.gcode,/estimated printing time/);assert.throws(()=>applyCalibrationGcode(raw.replace('printing object flowrate_20','printing object changed'),plan),/missing flow specimen/);assert.throws(()=>applyCalibrationGcode(output.gcode,plan),/already applied/);
});
