import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';
import{importNative3MF}from'../../shared/native-project.js';import{bindGeneratedPatternProject,assertGeneratedPatternProjectUnchanged,assertGeneratedPatternEdit,generatedPatternStructure}from'../../shared/generated-pattern-binding.js';import{createNativeProjectService}from'../../server/native-projects.js';
const bytes=await readFile(new URL('../fixtures/pa-pattern/calibration-project.3mf',import.meta.url)),fresh=()=>importNative3MF(bytes),service=createNativeProjectService({catalog:{}});
test('complete generated pattern import captures four-layer geometry/settings/plate binding and survives JSON scene roundtrip',()=>{const project=fresh();assert.equal(generatedPatternStructure(project)[0].layers,4);assert.equal(project.generatedPatternBinding.kind,'pressure-advance-pattern');assert.equal(assertGeneratedPatternProjectUnchanged(JSON.parse(JSON.stringify(project)),{useEmbeddedSettings:true}),true);project.name='Renamed';project.selectedId=null;assert.equal(assertGeneratedPatternProjectUnchanged(project),true);});
test('stale generated patterns reject transform, geometry, native settings, plate and command edits',()=>{for(const mutate of[p=>p.objects[0].position[0]++,p=>p.objects[0].positions[0]++,p=>p.objects[0].native.objectSettings.outer_wall_speed='999',p=>p.nativeSettings.layer_height='.4',p=>p.plates.push({id:'new',name:'New'}),p=>p.plates[0].layerEvents.items[0].extra+='\nG1 X0',p=>delete p.plates[0].layerEvents]){const project=fresh();mutate(project);assert.throws(()=>assertGeneratedPatternProjectUnchanged(project),/fixed absolute.*regenerate/);}const project=fresh();assert.throws(()=>assertGeneratedPatternProjectUnchanged(project,{useEmbeddedSettings:false}),/regenerate/);delete project.generatedPatternBinding;assert.throws(()=>assertGeneratedPatternProjectUnchanged(project),/regenerate/);});
test('incomplete marked projects cannot establish a new binding, ordinary custom commands retain existing semantics',()=>{const project=fresh();project.plates[0].layerEvents.items.pop();assert.throws(()=>bindGeneratedPatternProject(project),/regenerate/);const ordinary={plates:[{id:'one',layerEvents:{items:[{type:'Custom',printZ:.2,extra:'G4 S2'}]}}]};assert.equal(bindGeneratedPatternProject(ordinary),ordinary);assert.equal(assertGeneratedPatternProjectUnchanged(ordinary),false);});
test('native project preparation accepts unchanged embedded import and rejects changed geometry, presets and plates',async()=>{const project=fresh();const prepared=await service.prepare({project,useEmbeddedSettings:true});assert.equal(importNative3MF(prepared.bytes).plates[0].layerEvents.items.length,4);for(const change of[p=>p.objects[0].position[0]++,p=>p.nativeSettings.outer_wall_speed='50',p=>p.plates[0].native.metadata.print_sequence='by object']){const changed=fresh();change(changed);await assert.rejects(service.prepare({project:changed,useEmbeddedSettings:true}),/fixed absolute.*regenerate/);}await assert.rejects(service.prepare({project,useEmbeddedSettings:false,selection:{printerId:'p',processId:'s',filamentIds:['f']}}),/fixed absolute.*regenerate/);});

test('browser edit guard retains fixed paths and checks effective process settings while allowing selection and names',()=>{const current=fresh();current.useEmbeddedSettings=true;const renamed={...current,name:'New project name',selectedId:null,selectedIds:[],objects:current.objects.map(object=>({...object,name:'Renamed handle'}))};assert.equal(assertGeneratedPatternEdit(current,renamed),true);assert.throws(()=>assertGeneratedPatternEdit(current,{...current,generatedPatternBinding:undefined}),/regenerate/);assert.throws(()=>assertGeneratedPatternEdit(current,current,{settings:{...current.nativeSettings,layer_height:'.4'}}),/regenerate/);assert.throws(()=>assertGeneratedPatternEdit(current,{...current,useEmbeddedSettings:false}),/regenerate/);});

test('saved version-one pattern bindings retain their original geometry/settings/active-plate fingerprint',async()=>{const project=fresh();project.objects.forEach((object,index)=>{object.id=`legacy-${index}`;object.native.groupId=`legacy-group-${index}`;delete object.native.meshSource;delete object.native.instanceFamily;delete object.native.instanceAutoDrop; /* The saved v1 fixture predates native source frames and instance identity. */});project.selectedId=project.objects[0].id;project.generatedPatternBinding=JSON.parse(await readFile(new URL('../fixtures/pa-pattern/legacy-binding-v1.json',import.meta.url)));assert.equal(project.generatedPatternBinding.version,1);assert.equal(assertGeneratedPatternProjectUnchanged(project,{useEmbeddedSettings:true}),true);project.objects[0].position[1]++;assert.throws(()=>assertGeneratedPatternProjectUnchanged(project),/regenerate/);});
