import test from 'node:test';import assert from 'node:assert/strict';import {Matrix4}from'three';import{readFile}from'node:fs/promises';import{unzipSync,strFromU8}from'fflate';
import{cutFixture}from'../fixtures/native-instance-cut-project.js';import{fixture}from'../fixtures/native-instance-project.js';import{linkedCutGroups,prepareNativeInstanceCut,applyNativeInstanceCut,validateNativeInstanceCutResult,INSTANCE_CUT_REVISION}from'../../shared/native-instance-cut.js';import{assertInstanceFamilies,instanceGroups}from'../../shared/native-instances.js';import{importNative3MF,exportNative3MF}from'../../shared/native-project.js';import{parseProject,serializeProject}from'../../shared/project.js';import{meshBounds,analyzeMesh}from'../../shared/geometry.js';import{reconcileNativeInstanceEdits}from'../../shared/native-instance-edits.js';
const reference=JSON.parse(await readFile(new URL('../fixtures/native-instance-cut-reference.json',import.meta.url)));
const reply=(prepared,index=0)=>({format:'orca-native-instance-cut',version:1,sourceRevision:INSTANCE_CUT_REVISION,selectedInstanceId:prepared.request.selectedInstanceId,results:prepared.request.results.map((input,i)=>({id:input.id,side:input.side,minimumZBeforeGrounding:reference.cases[index].expected[i].minimumZBeforeGrounding,minimumZAfterGrounding:reference.cases[index].expected[i].minimumZAfterGrounding,instances:prepared.request.instances.map((inst,k)=>({...inst,matrix:[...reference.cases[index].expected[i].instances[k]]}))}))});
test('linked Cut replaces every shared instance with two new ModelObject families, one immutable transaction',()=>{const{project,prepared}=cutFixture(),before=JSON.stringify(project),output=applyNativeInstanceCut(prepared,reply(prepared));assert.equal(JSON.stringify(project),before);assert.deepEqual(output.replaceIds,project.objects.map(o=>o.id));assert.equal(output.created.length,8);assert.equal(new Set(output.created.map(o=>o.native.instanceFamily)).size,2);assert.equal(instanceGroups(output.created).size,4);assert.ok(output.created.every(o=>analyzeMesh(o).manifold));assert.equal(output.report.selectedId,prepared.result.created[0].id);assertInstanceFamilies(output.created);const committed=reconcileNativeInstanceEdits(project,{...project,objects:output.objects});assert.deepEqual(committed.objects,output.objects);assert.equal(parseProject(serializeProject(committed)).objects.length,8);});
test('analytic horizontal frame geometry grounds upper and lower independently and keeps peer XY/Z rotation',()=>{const{prepared}=cutFixture(),out=applyNativeInstanceCut(prepared,reply(prepared));for(const o of out.created){assert.equal(meshBounds(o).min[2],0);assert.equal(meshBounds(o).max[2],5);}const normals=out.upper.map(o=>meshBounds(o).center);assert.deepEqual(normals,[[40,40,2.5],[54,40,2.5],[100,40,2.5],[100,54,2.5]]);const inputs=prepared.request.instances;assert.deepEqual(inputs[0].matrix.slice(12,15),[40,40,10]);assert.deepEqual(inputs[1].matrix.slice(12,15),[100,40,10]);});
test('cut native archive retains shared object identity, source frames, processed connector metadata and independent families',()=>{const{project,prepared}=cutFixture({parts:1,connector:'plug'}),out=applyNativeInstanceCut(prepared,reply(prepared,10)),bytes=exportNative3MF({...project,objects:out.objects}),model=strFromU8(unzipSync(bytes)['3D/3dmodel.model']),restored=importNative3MF(bytes);assert.equal((model.match(/<components>/g)||[]).length,2);assert.equal((model.match(/<item /g)||[]).length,4);assert.equal(restored.objects.length,8);assert.equal(new Set(restored.objects.map(o=>o.native.instanceFamily)).size,2);assert.equal(restored.objects.filter(o=>o.native.cutConnector).length,4);assert.equal(new Set(restored.objects.map(o=>o.native.cutId.id)).size,1);assert.ok(restored.objects.every(o=>o.native.cutId.checkSum==='2'));assertInstanceFamilies(restored.objects);});
test('two-plate Cut sends global native offsets and returns plate-local geometry without moving peers to the selected plate',()=>{const{project,prepared}=cutFixture({multiPlate:true,selected:1}),out=applyNativeInstanceCut(prepared,reply(prepared,7));assert.equal(prepared.request.instances[1].matrix[12],400);assert.equal(out.created.filter(o=>o.plateId==='plate-2').length,4);assert.equal(out.created.filter(o=>o.plateId==='plate-1').length,4);for(const o of out.created)assert.ok(meshBounds(o).max[0]<150);assert.equal(importNative3MF(exportNative3MF({...project,objects:out.objects})).plates.length,2);});
test('no-auto-drop flags preserve original height while native first-instance grounding shifts eligible peers equally',()=>{const frames=[new Matrix4().makeTranslation(40,40,10),new Matrix4().makeRotationZ(Math.PI/2).setPosition(100,40,16)],{prepared}=cutFixture({autoDrops:[false,true],frames}),value=reply(prepared,5),out=applyNativeInstanceCut(prepared,value);assert.equal(value.results[0].instances[0].matrix[14],10);assert.equal(value.results[0].instances[1].matrix[14],6);assert.equal(meshBounds(out.upper[0]).min[2],10);assert.equal(meshBounds(out.upper[2]).min[2],6);});
test('dowels discard the old preview grounding before native per-instance placement, including disabled auto-drop',()=>{const{prepared}=cutFixture({parts:1,connector:'dowel',autoDrops:[false,true]}),dowel=prepared.request.results.find(r=>r.side==='dowel');assert.deepEqual([Math.min(...dowel.parts[0].vertices.map(p=>p[2])),Math.max(...dowel.parts[0].vertices.map(p=>p[2]))],[-2,2]);const out=applyNativeInstanceCut(prepared,reply(prepared,9));assert.equal(out.dowels.length,2);assert.equal(meshBounds(out.dowels[0]).min[2],8);assert.equal(meshBounds(out.dowels[1]).min[2],0);assert.equal(new Set(out.created.map(o=>o.native.instanceFamily)).size,3);});
test('only explicit instance families share a Cut; unrelated cut-family peers are preserved and painting changes require the existing consent flow',()=>{const p=fixture();delete p.objects[2].native.instanceFamily;delete p.objects[3].native.instanceFamily;assert.equal(linkedCutGroups(p.objects,'i0p0').length,1);const{project,prepared}=cutFixture(),unrelated={...structuredClone(project.objects[0]),id:'unrelated',native:{...project.objects[0].native,instanceFamily:undefined,groupId:'other'}};prepared.result.objects.push(unrelated);const out=applyNativeInstanceCut(prepared,reply(prepared));assert.equal(out.objects.find(o=>o.id==='unrelated'),unrelated);assert.ok(out.created.every(o=>!o.painting));});
test('strict response validation rejects altered identity, XY, scale, auto-drop and stale topology before applying',()=>{const{prepared}=cutFixture();for(const edit of [r=>r.sourceRevision='other',r=>r.results.pop(),r=>r.results[0].instances[0].id='other',r=>r.results[0].instances[0].matrix[12]++,r=>r.results[0].instances[0].matrix[0]=2,r=>r.results[0].instances[0].autoDrop=false,r=>r.results[0].instances[1].matrix[14]++,r=>r.results[0].minimumZAfterGrounding=NaN]){let r=reply(prepared);edit(r);assert.throws(()=>validateNativeInstanceCutResult(r,prepared.request));}const{project,cut}=cutFixture();project.objects[0].positions[0]++;assert.throws(()=>prepareNativeInstanceCut({...project,selectedId:'i0p0'},cut),/no longer matches|diverged/);});

test('oversized native load scaling dialog is explicit instead of silently inventing a scaling decision',()=>{const{prepared}=cutFixture();prepared.bed={width:2,depth:2};assert.throws(()=>applyNativeInstanceCut(prepared,reply(prepared)),/oversized-model scaling dialog/);});

test('browser min/max bed contract retains exact two-plate native frames and local results',()=>{
 const {project,cut,prepared}=cutFixture({multiPlate:true,selected:1});
 const bed={polygon:[[0,0],[250,0],[250,210],[0,210]],height:220,min:[0,0,0],max:[250,210,220]};
 const browser=prepareNativeInstanceCut({objects:project.objects,plates:project.plates,selectedId:'i1p0',bed},cut);
 assert.deepEqual(browser.request,prepared.request);assert.deepEqual(browser.bed,{width:250,depth:210,height:220});
 const output=applyNativeInstanceCut(browser,reply(browser,7));assert.equal(output.created.filter(o=>o.plateId==='plate-2').length,4);assert.equal(output.created.filter(o=>o.plateId==='plate-1').length,4);
 for(const object of output.created)assert.ok(meshBounds(object).max[0]<150);
});
test('browser bed dimensions enforce native oversized dialog boundary and reject invalid dimensions',()=>{
 const {project,cut}=cutFixture(),base={objects:project.objects,plates:project.plates,selectedId:'i0p0'};
 const tiny=prepareNativeInstanceCut({...base,bed:{min:[0,0,0],max:[2,2,100],polygon:[[0,0],[2,0],[2,2],[0,2]],height:100}},cut);
 assert.throws(()=>applyNativeInstanceCut(tiny,reply(tiny)),/oversized-model scaling dialog/);
 assert.throws(()=>prepareNativeInstanceCut({...base,bed:{min:[0,0,0],max:[0,2,100]}},cut),/dimensions must be positive/);
});
