import test from 'node:test';import assert from 'node:assert/strict';
import {BoxGeometry} from 'three';
import {emptyProject} from '../../shared/project.js';
import {createMesh} from '../../shared/geometry.js';
import {cutNativeClipboard} from '../../shared/native-cut-clipboard.js';
import {prepareNativePaste,applyNativePaste,CLIPBOARD_REVISION} from '../../shared/native-clipboard.js';
const bed={width:200,depth:200,height:200};
const cutId={id:'123',checkSum:'7',connectorsCount:'2'};
function cube(id,group=id,type='normal_part'){const geometry=new BoxGeometry(10,10,10).toNonIndexed();const mesh=createMesh({id,name:id,plateId:'plate-1',positions:Array.from(geometry.attributes.position.array),position:[30,30,5],native:{groupId:group,partType:type,objectSettings:{wall_loops:'4'}},painting:{version:1,color:{0:'4'}}});geometry.dispose();return mesh;}
function scene(){return{...emptyProject(),objects:[cube('a'),cube('b')],selectedId:'a',selectedIds:['a']};}
test('Cut captures the detached model snapshot and erases only its selected groups without changing source state',()=>{const p=scene(),before=structuredClone(p),cut=cutNativeClipboard(p,bed);assert.deepEqual(p,before);assert.deepEqual(cut.project.objects,[p.objects[1]]);assert.equal(cut.project.selectedId,null);assert.deepEqual(cut.project.selectedIds,[]);assert.equal(cut.clipboard.entries[0].parts[0].name,'a');assert.deepEqual(cut.clipboard.entries[0].parts[0].painting,p.objects[0].painting);p.objects[0].native.objectSettings.wall_loops='7';assert.equal(cut.clipboard.entries[0].parts[0].native.objectSettings.wall_loops,'4');});
test('Cut parts retain the remaining normal volume; removing the last normal part rejects atomically',()=>{const p=scene();p.objects=[cube('body','one'),cube('hole','one','negative_part')];p.selectionScope='part';p.selectedId='hole';p.selectedIds=['hole'];const cut=cutNativeClipboard(p,bed);assert.deepEqual(cut.project.objects.map(o=>o.id),['body']);assert.equal(cut.clipboard.scope,'part');assert.equal(cut.clipboard.entries[0].parts[0].native.partType,'negative_part');p.selectedId='body';p.selectedIds=['body'];const before=structuredClone(p);assert.throws(()=>cutNativeClipboard(p,bed),/without a normal part/);assert.deepEqual(p,before);});
test('Clipboard survives independently restored project history and subsequent paste uses fresh identities',()=>{const p=scene(),{clipboard,project:afterCut}=cutNativeClipboard(p,bed),prepared=prepareNativePaste(afterCut,clipboard,bed),source=prepared.request.clipboardObjects[0],result={format:'orca-native-clipboard',version:1,sourceRevision:CLIPBOARD_REVISION,clones:[{copy:0,sourceId:source.id,originalMatrix:source.matrix,matrix:source.matrix}]};const pasted=applyNativePaste(afterCut,prepared,result).project;assert.deepEqual(pasted.objects.map(o=>o.name),['b','a']);assert.notEqual(pasted.objects[1].id,'a');assert.deepEqual(pasted.objects[1].positions,p.objects[0].positions);assert.equal(prepareNativePaste(p,clipboard,bed).clipboard,clipboard);});
test('Cut rejects locked/generated projects and explicitly invalidates surviving processed cut correspondence',()=>{const p=scene();assert.throws(()=>cutNativeClipboard({...p,calibration:{}},bed),/calibration/);assert.throws(()=>cutNativeClipboard({...p,plates:[{id:'plate-1',locked:true}]},bed),/locked/);for(const object of p.objects)object.native.cutId={id:'123',checkSum:'7',connectorsCount:'1'};const pending=cutNativeClipboard(p,bed);assert.equal(pending.project,p);assert.equal(pending.confirmation.type,'object');const result=cutNativeClipboard(p,bed,{decision:'delete'});assert.equal(result.clipboard.entries[0].parts[0].native.cutId.id,'123');assert.equal(result.project.objects[0].native.cutId,undefined);assert.equal(p.objects[1].native.cutId.id,'123');assert.equal(cutNativeClipboard(p,bed,{decision:'cancel'}).project,p);});
test('native part invalidation is its own geometry-preserving operation and family equality includes checksum/count',()=>{const p=scene();p.objects=[cube('body','g'),cube('part','g'),cube('mate','h'),cube('different','i')];for(const o of p.objects)o.native.cutId={...cutId};p.objects[3].native.cutId.checkSum='8';p.selectionScope='part';p.selectedId='part';p.selectedIds=['part'];const pending=cutNativeClipboard(p,bed);assert.equal(pending.confirmation.type,'part');assert.equal(pending.confirmation.canDeleteConnectors,false);assert.equal(pending.project,p);assert.throws(()=>cutNativeClipboard(p,bed,{decision:'delete-connectors'}),/valid native/);const invalidated=cutNativeClipboard(p,bed,{decision:'invalidate'});assert.equal(invalidated.project.objects.length,4);for(let i=0;i<3;i++){assert.deepEqual(invalidated.project.objects[i].positions,p.objects[i].positions);assert.equal(invalidated.project.objects[i].native.cutId,undefined);}assert.equal(invalidated.project.objects[3],p.objects[3]);assert.match(invalidated.warnings[0],/again/);const removed=cutNativeClipboard(invalidated.project,bed);assert.deepEqual(removed.project.objects.map(o=>o.id),['body','mate','different']);});
test('delete-all-connectors removes matching family connectors and empty connector objects while retaining cut identities',()=>{const p=scene();p.objects=[cube('body','g'),cube('plug','g'),cube('socket','h','negative_part'),cube('mate','h'),cube('dowel','d')];for(const o of p.objects)o.native.cutId={...cutId};for(const o of p.objects.filter(o=>['plug','socket','dowel'].includes(o.id)))o.native.cutConnector={type:'dowel',radiusTolerance:.1,heightTolerance:.2};p.selectionScope='part';p.selectedId='plug';p.selectedIds=['plug'];assert.equal(cutNativeClipboard(p,bed).confirmation.canDeleteConnectors,true);const result=cutNativeClipboard(p,bed,{decision:'delete-connectors'});assert.deepEqual(result.project.objects.map(o=>o.id),['body','mate']);for(const o of result.project.objects)assert.deepEqual(o.native.cutId,cutId);assert.equal(result.project.selectedId,null);assert.equal(result.clipboard.entries[0].parts[0].id,'plug');});
test('removing a helper promotes the final volume overrides into native object settings',()=>{const p=scene();p.objects=[cube('body','g'),cube('hole','g','negative_part')];p.objects[0].native.partSettings={wall_loops:'7',sparse_infill_density:'37%'};p.selectionScope='part';p.selectedId='hole';p.selectedIds=['hole'];const result=cutNativeClipboard(p,bed);assert.deepEqual(result.project.objects[0].native.objectSettings,{wall_loops:'7',sparse_infill_density:'37%'});assert.deepEqual(result.project.objects[0].native.partSettings,{});assert.equal(p.objects[0].native.partSettings.wall_loops,'7');});
