import test from 'node:test';
import assert from 'node:assert/strict';
import {Matrix4} from 'three';
import {prepareNativeImportInspection,validateNativeImportInspection,applyNativeImportInspection,IMPORT_INSPECTION_REVISION} from '../../shared/native-import-inspection.js';
import {fixture} from '../fixtures/native-instance-project.js';
import {inspectionBox,inspectionProject,emptyVolumeFixture} from '../fixtures/import-inspection-project.js';
import {assertInstanceFamilies} from '../../shared/native-instances.js';
const reply=(prepared,volumes)=>({format:'orca-native-import-inspection',version:1,sourceRevision:IMPORT_INSPECTION_REVISION,objects:prepared.request.objects.map((o,i)=>({id:o.id,volume:volumes[i]})),retainedIds:prepared.request.objects.filter((o,i)=>volumes[i]>=1e-10).map(o=>o.id),removedCount:volumes.filter(v=>v<1e-10).length,unitSuggestion:volumes.some(v=>v>=1e-10&&v<.008)?'meters':volumes.some(v=>v>=1e-10&&v<8)?'inches':'none'});
test('inspection preserves canonical volume frames, roles and all linked instances, with source plate origins',()=>{const p=fixture({mirror:true});p.plates[0].native={origin:[250,-210,0]};p.objects[1].native.partType=p.objects[3].native.partType='negative_part';const prepared=prepareNativeImportInspection(p),o=prepared.request.objects[0];assert.equal(prepared.request.objects.length,1);assert.equal(o.instances.length,2);assert.equal(o.parts.length,2);assert.deepEqual(o.parts.map(v=>v.type),['normal_part','negative_part']);assert.deepEqual(o.parts[0].vertices.flat(),p.objects[0].native.meshSource.vertices);assert.equal(o.instances[0][12],290);assert.equal(o.instances[1][12],350);assert.equal(new Matrix4().fromArray(o.instances[1]).determinant(),-1);});
test('independent model IDs remain independent even for equal historical source IDs and processed cuts',()=>{const cutId={id:'18446744073709551615',checkSum:'2',connectorsCount:'0'},p=inspectionProject([inspectionBox(1,{id:'a',cutId}),inspectionBox(10,{id:'b',cutId})]);for(const o of p.objects)o.native.objectId='1';const prepared=prepareNativeImportInspection(p);assert.equal(prepared.request.objects.length,2);assert.deepEqual(prepared.request.objects.map(o=>o.cutId),[cutId,cutId]);});
test('filtering removes a complete model family while retaining original parts, metadata, plate and preset context',()=>{const linked=fixture({mirror:true}),solid=inspectionBox(10),p={...linked,objects:[...linked.objects,solid],projectOverrides:{filament_colour:['#abcdef']}},original=structuredClone(p),prepared=prepareNativeImportInspection(p),out=applyNativeImportInspection(prepared,reply(prepared,[0,1000]));assert.equal(out.objects.length,1);assert.equal(out.objects[0],solid);assert.equal(out.selectedId,solid.id);assert.equal(out.projectOverrides,p.projectOverrides);assert.deepEqual(p,original);assertInstanceFamilies(out.objects);});
test('all-empty results carry no stale selected IDs and leave source/history objects untouched',()=>{const p=emptyVolumeFixture({allEmpty:true}),prepared=prepareNativeImportInspection(p),out=applyNativeImportInspection(prepared,reply(prepared,[0]));assert.deepEqual(out.objects,[]);assert.equal(out.selectedId,null);assert.deepEqual(out.selectedIds,[]);assert.equal(p.objects.length,1);});
test('native results must account for every original identity once, in order, at the original zero threshold',()=>{const prepared=prepareNativeImportInspection(inspectionProject([inspectionBox(1,{id:'a'}),inspectionBox(2,{id:'b'})])),good=reply(prepared,[1e-10,1e-11]);assert.equal(validateNativeImportInspection(good,prepared.request),good);for(const change of [v=>v.version=2,v=>v.sourceRevision='other',v=>v.objects.reverse(),v=>v.objects[0].volume=NaN,v=>v.retainedIds=['model-1'],v=>v.retainedIds=['model-0','model-0'],v=>v.removedCount=0,v=>v.unitSuggestion='feet',v=>v.objects.pop()]){const bad=structuredClone(good);change(bad);assert.throws(()=>validateNativeImportInspection(bad,prepared.request),/Invalid native/);}});
test('non-retained geometry retains original coordinates and a separate native volume transform',()=>{const p=emptyVolumeFixture({allEmpty:true});p.objects[0].position=[2,3,4];p.objects[0].scale=[2,3,4];const prepared=prepareNativeImportInspection(p);assert.deepEqual(prepared.request.objects[0].parts[0].vertices,[[0,0,0],[10,0,0],[0,10,0]]);assert.deepEqual(prepared.request.objects[0].parts[0].matrix.slice(12,15),[-3,-7,4]);assert.deepEqual(p.objects[0].positions,[0,0,0,10,0,0,0,10,0]);});
test('empty, excessive, divergent and stale retained geometry is rejected before native admission',()=>{assert.throws(()=>prepareNativeImportInspection(inspectionProject([])),/1–256/);assert.throws(()=>prepareNativeImportInspection(inspectionProject(Array.from({length:257},(_,i)=>inspectionBox(1,{id:`b${i}`})))),/1–256/);const linked=fixture();linked.objects[2].native.meshSource.vertices[0]++;assert.throws(()=>prepareNativeImportInspection(linked),/retained|Retained|diverged/);});

test('zero-volume notice uses the original installed information icon with AGPL attribution',async()=>{const{readFile}=await import('node:fs/promises'),{createHash}=await import('node:crypto'),manifest=JSON.parse(await readFile(new URL('../../public/native-dialogs/manifest.json',import.meta.url)));const asset=manifest.assets.find(a=>a.file==='info.svg');assert.equal(asset.sha256,'ad5535e1ad682a4ad3381c90ebb06e21ab4e9924762ff9e96fbd6777aea969a0');assert.equal(createHash('sha256').update(await readFile(new URL('../../public/native-dialogs/info.svg',import.meta.url))).digest('hex'),asset.sha256);assert.match(await readFile(new URL('../../public/native-dialogs/NOTICE.md',import.meta.url),'utf8'),/info.svg/);assert.match(await readFile(new URL('../../public/native-dialogs/LICENSE.txt',import.meta.url),'utf8'),/GNU AFFERO GENERAL PUBLIC LICENSE/);});
