import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{nativeColorPrintLayers,nativeFilamentUsage,nativeCompactWeight,nativeMaterialAmount,nativeCompactCount,nativeMaterialLabel}from'../../shared/native-filament-preview.js';import{nativeVertexColor}from'../../shared/native-preview-adapter.js';
const fixture=JSON.parse(await readFile(new URL('../fixtures/native-filament-reference.json',import.meta.url)));
function data(){const d=structuredClone(fixture.synthetic.input);d.layers=[...new Set(d.vertices.map(v=>v[13]))].map(id=>({id}));return d;}
const near=(a,b,label)=>assert.ok(Math.abs(a-b)<=Math.max(1,Math.abs(b))*1e-12,`${label}: ${a} vs ${b}`);
test('native Filament and Summary colors match original C++ for palette wrapping, travels, wipes and pause/custom layers',()=>{const d=data(),before=JSON.stringify(d),flags=nativeColorPrintLayers(d),parsed={native:{data:d,colorPrintLayers:flags}};assert.deepEqual([...flags],[0,1,1,0]);for(const mode of['color','summary'])for(let i=0;i<d.vertices.length;i++){const expected='#'+fixture.synthetic.expected.colors[mode][i].map(v=>v.toString(16).padStart(2,'0')).join('');assert.equal(nativeVertexColor(parsed,i,mode),expected,`${mode} vertex${i}`);}assert.equal(JSON.stringify(d),before);});
test('native filament category presence, float row totals, double column totals and imported cost match original GUI source',()=>{for(const imperial of[false,true]){const d=data(),actual=nativeFilamentUsage(d,{imperial}),expected=fixture.synthetic.expected[imperial?'imperial':'metric'];assert.deepEqual(actual.rows.map(r=>r.tool),[0,1]);assert.deepEqual(actual.columns.map(c=>c.key),['model','support','flushed','tower']);assert.equal(actual.showTotals,true);for(const c of actual.columns){actual.rows.forEach((row,i)=>{near(row.amounts[c.key].length,expected[c.key][i][0],c.key+' length');near(row.amounts[c.key].grams,expected[c.key][i][1],c.key+' grams');});near(actual.totals[c.key].length,expected.totals[c.key][0],'total length');near(actual.totals[c.key].grams,expected.totals[c.key][1],'total grams');}actual.rows.forEach((row,i)=>{assert.equal(row.total.length,expected.rowTotals[i][0]);assert.equal(row.total.grams,expected.rowTotals[i][1]);});near(actual.cost,fixture.synthetic.expected.cost,'imported cost');assert.equal(actual.filamentChanges,4);assert.equal(actual.toolChanges,2);}});
test('compact native weight formatting matches original g/kg/t and imperial boundaries',()=>{for(const[weight,metric,imperial]of fixture.synthetic.expected.weights){assert.equal(nativeCompactWeight(weight),metric);assert.equal(nativeCompactWeight(weight,true),imperial);}});
test('old metadata and invalid material properties remain unavailable; empty maps do not invent categories or tool identities',()=>{const d=data();delete d.materialStatistics;delete d.materialStatisticsVersion;assert.equal(nativeFilamentUsage(d).available,false);assert.deepEqual(nativeFilamentUsage(d).rows.map(r=>r.tool),[0,1]);const empty=data();for(const key of ['modelVolumes','supportVolumes','towerVolumes','flushedVolumes','totalVolumes'])empty.materialStatistics[key]=[];assert.deepEqual(nativeFilamentUsage(empty).columns,[]);assert.equal(nativeFilamentUsage(empty).showTotals,false);empty.filamentDiameters[0]=0;empty.filamentDensities=[];assert.equal(nativeMaterialAmount(empty,5,0).length,null);assert.equal(nativeMaterialAmount(empty,5,0).grams,null);});

test('additive native material schema bounds maps, identities, counts and provenance while accepting old helpers',async()=>{const{nativePreviewFixture}=await import('../fixtures/native-preview-result.js');const{validateNativePreview}=await import('../../shared/native-preview-data.js');const base=nativePreviewFixture();assert.equal(validateNativePreview(base),base);Object.assign(base,{materialStatisticsVersion:1,materialStatistics:structuredClone(fixture.synthetic.input.materialStatistics),colorPaletteSource:'native-standalone-import'});assert.equal(validateNativePreview(base),base);for(const change of[d=>d.materialStatisticsVersion=2,d=>delete d.materialStatistics.totalVolumes,d=>d.materialStatistics.modelVolumes=[[0,-1]],d=>d.materialStatistics.modelVolumes=[[0,NaN]],d=>d.materialStatistics.modelVolumes=[[0,1],[0,2]],d=>d.materialStatistics.modelVolumes=[[256,1]],d=>d.materialStatistics.modelVolumes=Array(257).fill([0,1]),d=>d.materialStatistics.filamentChanges=-1,d=>d.materialStatistics.toolChanges=4294967296,d=>d.colorPaletteSource='estimated']){const value=structuredClone(base);change(value);assert.throws(()=>validateNativePreview(value),/Invalid native preview/);}});

test('native compact counts truncate suffix tenths and two-line usage retains native unit formatting',()=>{for(const[count,label]of fixture.synthetic.expected.counts)assert.equal(nativeCompactCount(count),label);assert.equal(nativeMaterialLabel({length:1.2345,grams:12.34},false,true),'1.23 m\n12.34g');assert.equal(nativeMaterialLabel({length:1.2345,grams:12.34}),'1.23 m    12.34g');assert.equal(nativeCompactCount(-1),'Unavailable');});
