import test from 'node:test';import assert from 'node:assert/strict';import {BoxGeometry,Matrix4,Vector3} from 'three';
import {createMesh,transformPositions} from '../../shared/geometry.js';import {emptyProject} from '../../shared/project.js';import {prepareNativeArrangement,applyNativeArrangement,validateArrangementResult,normalizeArrangeOptions,ARRANGE_REVISION} from '../../shared/native-arrangement.js';
const box=(id,extra={})=>{const g=new BoxGeometry(20,10,8).toNonIndexed();g.translate(10,5,4);return createMesh({id,name:id,positions:Array.from(g.attributes.position.array),plateId:'plate-1',...extra});};
const scene=()=>({...emptyProject(),objects:[box('one',{position:[50,50,0],rotation:[0,0,25],scale:[2,.5,1],native:{groupId:'assembly',objectSettings:{layer_height:'.15'}},painting:{version:1,color:{0:'1'}}}),box('negative',{position:[53,52,0],native:{groupId:'assembly',partType:'negative_part',objectSettings:{layer_height:'.15'}}}),box('fixed',{position:[100,100,0]})],selectedId:'one',selectedIds:['one']});
const settings={printable_area:['0x0','220x0','220x220','0x220'],printable_height:'250',nozzle_diameter:['.4'],post_process:['never-run'],print_sequence:'by layer'};
function result(request,delta=new Matrix4().makeTranslation(17,-11,0),bedIndex=0){return{format:'orca-native-arrangement',version:1,sourceRevision:ARRANGE_REVISION,objects:request.objects.filter(o=>o.selected).map(o=>({id:o.id,bedIndex,matrix:delta.clone().multiply(new Matrix4().fromArray(o.matrix)).toArray()}))};}
test('request preserves assemblies/part roles and transforms; selected-only keeps other objects fixed',()=>{const project=scene(),request=prepareNativeArrangement(project,settings,{scope:'selection'});assert.equal(request.objects.length,2);assert.deepEqual(request.objects.map(o=>o.selected),[true,false]);assert.equal(request.objects[0].parts[1].type,'negative_part');assert.deepEqual(request.objects[0].parts[0].color,{0:'1'});assert.equal(request.settings.post_process,undefined);for(const group of request.objects)for(const part of group.parts){const source=project.objects.find(o=>o.id===part.id),nativeMatrix=new Matrix4().fromArray(group.matrix).multiply(new Matrix4().fromArray(part.matrix)),actual=part.triangles.flatMap(t=>t.flatMap(i=>new Vector3(...part.vertices[i]).applyMatrix4(nativeMatrix).toArray())),expected=transformPositions(source);for(let i=0;i<actual.length;i++)assert.ok(Math.abs(actual[i]-expected[i])<1e-5);}});
test('rigid native delta rotates whole assembly while preserving geometry, painting, settings and other objects',()=>{const project=scene(),snapshot=structuredClone(project),request=prepareNativeArrangement(project,settings,{scope:'selection'}),delta=new Matrix4().makeTranslation(30,20,0).multiply(new Matrix4().makeRotationZ(Math.PI/2)),changed=applyNativeArrangement(project,request,result(request,delta));assert.deepEqual(project,snapshot);assert.equal(changed.objects[2],project.objects[2]);for(let i=0;i<2;i++){const old=project.objects[i],next=changed.objects[i];assert.equal(next.positions,old.positions);assert.deepEqual(next.painting,old.painting);assert.deepEqual(next.native.objectSettings,old.native.objectSettings);const before=transformPositions(old),after=transformPositions(next);for(let j=0;j<before.length;j+=3){const point=new Vector3(...before.slice(j,j+3)).applyMatrix4(delta);for(let a=0;a<3;a++)assert.ok(Math.abs(point.getComponent(a)-after[j+a])<1e-5);}}});
test('spill placements create independent plates, preserve their native settings and clear moved selection',()=>{const p=scene();p.plates[0].native={metadata:{bed_type:'High Temp Plate'},events:[{type:'pause',z:2}]};const request=prepareNativeArrangement(p,settings,{scope:'selection'}),changed=applyNativeArrangement(p,request,result(request,undefined,1));assert.equal(changed.plates.length,2);assert.deepEqual(changed.plates[1].native,{metadata:{bed_type:'High Temp Plate'}});assert.equal(changed.objects[0].plateId,changed.plates[1].id);assert.equal(changed.objects[1].plateId,changed.plates[1].id);assert.equal(changed.objects[2].plateId,'plate-1');assert.deepEqual(changed.selectedIds,[]);});
test('invalid options, locked/empty selections and malformed native results never mutate project',()=>{for(const value of[{spacing:-1},{spacing:101},{rotation:1},{unknown:true},{scope:'outside'}])assert.throws(()=>normalizeArrangeOptions(value));assert.equal(normalizeArrangeOptions({rotation:true,alignY:true}).alignY,false);const p=scene(),request=prepareNativeArrangement(p,settings,{scope:'selection'});assert.throws(()=>prepareNativeArrangement({...p,plates:[{id:'plate-1',locked:true}]},settings),/locked/);assert.throws(()=>prepareNativeArrangement({...p,selectedIds:[],selectedId:null},settings,{scope:'selection'}),/Select/);for(const change of[r=>r.sourceRevision='wrong',r=>r.objects.push(r.objects[0]),r=>r.objects[0].id='unexpected',r=>r.objects[0].bedIndex=-1,r=>r.objects[0].matrix[15]=0]){const invalid=result(request);change(invalid);assert.throws(()=>validateArrangementResult(invalid,request));}assert.throws(()=>applyNativeArrangement(p,request,result(request,new Matrix4().makeTranslation(0,0,1))),/XY placement/);assert.throws(()=>applyNativeArrangement(p,request,result(request,new Matrix4().makeScale(2,2,2))),/XY placement/);});

test('legacy single selection survives arrangement when selectedIds is empty',()=>{const p=scene();p.selectedIds=[];const request=prepareNativeArrangement(p,settings,{scope:'selection'}),changed=applyNativeArrangement(p,request,result(request));assert.equal(changed.selectedId,'one');assert.deepEqual(changed.selectedIds,['one']);});
