import test from 'node:test';import assert from 'node:assert/strict';import {BoxGeometry,Matrix4,Vector3}from'three';import{unzipSync,strFromU8}from'fflate';
import{createMesh,meshBounds}from'../../shared/geometry.js';import{emptyProject,serializeProject,parseProject}from'../../shared/project.js';import{exportNative3MF,importNative3MF}from'../../shared/native-project.js';import{updateSceneTransform}from'../../shared/scene-object-operations.js';import{updateNativePart}from'../../shared/native-object-settings.js';import{normalizeNativeMeshSource}from'../../shared/native-mesh-source.js';import{instanceDescriptor,instanceGroups,assertInstanceFamilies}from'../../shared/native-instances.js';import{reconcileNativeInstanceEdits,synchronizedInstanceFrame}from'../../shared/native-instance-edits.js';import{meshPointMatrix,worldBrimEars}from'../../shared/brim-ears.js';
const settings={printable_area:['0x0','250x0','250x210','0x210'],printable_height:'220',filament_settings_id:['PLA','PETG'],filament_colour:['#ff0000','#00ff00'],printer_technology:'FFF'};
import {fixture} from '../fixtures/native-instance-project.js';

const edited=(p,objects,options)=>reconcileNativeInstanceEdits(p,{...p,objects},options);
const group=(p,id=0)=>p.objects.filter(o=>o.native.groupId===`group${id}`);
function equivalent(p){assertInstanceFamilies(p.objects);for(const object of p.objects)normalizeNativeMeshSource(object);const restored=importNative3MF(exportNative3MF(p));assert.equal(new Set(restored.objects.map(o=>o.native.instanceFamily)).size,1);assert.equal(restored.objects.length,p.objects.length);assert.equal(JSON.stringify(parseProject(serializeProject(p)).objects),JSON.stringify(p.objects));return restored;}
test('shared object/part settings propagate with one immutable transaction, preserving exact raw mesh and frame',()=>{const p=fixture(),before=JSON.stringify(p),objects=updateNativePart(p.objects,'i0p0',{partSettings:{wall_loops:'7'},objectSettings:{layer_height:'0.12'}}),next=edited(p,objects);assert.equal(JSON.stringify(p),before);for(const part of next.objects){assert.deepEqual(part.native.objectSettings,{layer_height:'0.12'});assert.deepEqual(part.native.partSettings,part.name==='Part 0'?{wall_loops:'7'}:{});assert.deepEqual(part.native.meshSource.vertices,p.objects[0].native.meshSource.vertices);assert.deepEqual(part.native.meshSource.component,p.objects.find(o=>o.id===part.id).native.meshSource.component);}equivalent(next);});
test('part translation uses one shared component frame even with rotated and mirrored peer instances',()=>{for(const mirror of [false,true]){const p=fixture({mirror}),objects=updateSceneTransform(p.objects,'i0p1',{position:[3,4,2]},{scope:'part'}),next=edited(p,objects,{instanceScope:'part'});const source=next.objects.find(o=>o.id==='i0p1'),peer=next.objects.find(o=>o.id==='i1p1');assert.deepEqual(meshBounds(source).center,[57,44,12]);assert.deepEqual(meshBounds(peer).center.map(v=>Math.round(v*1e8)/1e8),[96,mirror?23:57,12]);assert.deepEqual(source.native.meshSource.component,peer.native.meshSource.component);equivalent(next);}});
test('paint, filament, volume role, name and height metadata are shared but visibility and printable flags are instance-local',()=>{const p=fixture(),objects=p.objects.map(o=>o.id==='i0p1'?{...o,name:'Modifier',filamentSlot:2,visible:false,printable:false,painting:{version:1,winding:1,support:{1:'4'}},native:{...o.native,partType:'modifier',layerHeightProfile:[0,.2,10,.2]}}:o),next=edited(p,objects);const peer=next.objects.find(o=>o.id==='i1p1');assert.equal(peer.name,'Modifier');assert.equal(peer.filamentSlot,2);assert.equal(peer.native.partType,'modifier');assert.deepEqual(peer.painting.support,{1:'4'});assert.deepEqual(peer.native.layerHeightProfile,[0,.2,10,.2]);assert.equal(peer.visible,true);assert.equal(peer.printable,undefined);assertInstanceFamilies(next.objects);});
test('world-Z rotation and XY translation remain local; tilt/scale synchronize peers without copying XY or Z rotation',()=>{for(const [patch,propagates]of [[{position:[8,3,0]},false],[{rotation:[0,0,20]},false],[{rotation:[20,0,0]},true],[{scale:[2,1,1]},true]]){const p={...fixture(),selectionScope:'object'},old=instanceDescriptor(group(p,1)).frame,objects=updateSceneTransform(p.objects,'i0p0',patch,{scope:'object'}),expectedSelected=instanceDescriptor(objects.filter(o=>o.native.groupId==='group0')).frame,next=edited(p,objects,{instanceScope:'object'}),actual=instanceDescriptor(group(next,1)).frame,expected=propagates?synchronizedInstanceFrame(instanceDescriptor(group(p,0)).frame,expectedSelected,old):old;actual.elements.forEach((v,i)=>assert.ok(Math.abs(v-expected.elements[i])<1e-8,`${JSON.stringify(patch)} matrix ${i}`));assert.deepEqual(actual.elements.slice(12,15),old.elements.slice(12,15));equivalent(next);}});
test('deleting a part removes that volume from all peers; deleting a whole instance leaves its peers',()=>{const p=fixture(),next=edited(p,p.objects.filter(o=>o.id!=='i0p1'));assert.deepEqual(next.objects.map(o=>o.id),['i0p0','i1p0']);equivalent(next);const deleted=edited(p,p.objects.filter(o=>o.native.groupId!=='group0'));assert.deepEqual(deleted.objects.map(o=>o.id),['i1p0','i1p1']);});
test('adding a part to a linked group creates one corresponding part in every instance',()=>{const p=fixture(),source=p.objects[1],added={...structuredClone(source),id:'new',name:'New part',position:[0,0,5],native:{...source.native,instanceFamily:undefined}},next=edited(p,[...p.objects,added],{instanceScope:'part'});assert.equal(next.objects.length,6);assert.equal(group(next,1).filter(o=>o.name==='New part').length,1);assert.equal(new Set(next.objects.map(o=>o.id)).size,6);equivalent(next);});
test('incompatible concurrent part edits reject atomically; stale geometry carriers are never silently accepted',()=>{const p=fixture(),objects=p.objects.map(o=>o.id==='i0p1'?{...o,name:'A'}:o.id==='i1p1'?{...o,name:'B'}:o);assert.throws(()=>edited(p,objects),/conflicting edits/);const stale=p.objects.map(o=>o.id==='i0p1'?{...o,positions:o.positions.map((v,i)=>i===0?v+1:v)}:o);assert.throws(()=>edited(p,stale),/no longer matches/);});
test('topology replacement without a stale carrier propagates actual geometry, keeps peer placement and export identity',()=>{const p=fixture(),source=p.objects[1],positions=source.positions.map((v,i)=>i%3===2?v+1:v),native={...source.native};delete native.meshSource;const next=edited(p,p.objects.map(o=>o===source?{...o,positions,native}:o),{instanceScope:'part'});assert.equal(meshBounds(next.objects.find(o=>o.id==='i1p1')).center[2],11);equivalent(next);});
test('native no-auto-drop peer synchronizes Z; ordinary selected instance auto-drop leaves peer Z unchanged',()=>{const old=new Matrix4().makeTranslation(20,30,5),current=new Matrix4().makeTranslation(22,33,8),peer=new Matrix4().makeRotationZ(.7).setPosition(80,90,3);assert.equal(synchronizedInstanceFrame(old,current,peer,{rotation:'none',autoDrop:false}).elements[14],8);assert.equal(synchronizedInstanceFrame(old,current,peer,{rotation:'none',autoDrop:true}).elements[14],3);assert.equal(synchronizedInstanceFrame(old,current,peer,{rotation:'none',autoDrop:false,sla:true}).elements[14],3);});
test('unrelated project edits and untouched instance metadata remain strict no-ops',()=>{const p=fixture(),proposal={...p,name:'New'};assert.equal(reconcileNativeInstanceEdits(p,proposal),proposal);const objects=p.objects.map(o=>o.id==='i0p0'?{...o,visible:false}:o),next={...p,objects};assert.equal(reconcileNativeInstanceEdits(p,next),next);});
test('native auto_drop survives both archive and JSON roundtrips and rejects forged nonboolean values',()=>{const p=fixture();for(const object of p.objects)object.native.instanceAutoDrop=object.id.startsWith('i1')?false:true;const restored=equivalent(p);assert.deepEqual(restored.objects.map(o=>o.native.instanceAutoDrop),[true,true,false,false]);const xml=strFromU8(unzipSync(exportNative3MF(p))['3D/3dmodel.model']);assert.match(xml,/auto_drop="0"/);p.objects[0].native.instanceAutoDrop='false';assert.throws(()=>serializeProject(p),/auto-drop/);});
test('brim ears and imported text regeneration frames follow shared edits in model coordinates',async()=>{const {readFile}=await import('node:fs/promises');const imported=importNative3MF(await readFile(new URL('../fixtures/native-text-planar-2.4.2.3mf',import.meta.url))),first=imported.objects;const sourceFrame=instanceDescriptor(first).frame,peerFrame=new Matrix4().makeTranslation(60,20,0).multiply(sourceFrame),delta=peerFrame.clone().multiply(sourceFrame.clone().invert());const peer=first.map((o,i)=>{const copy=structuredClone(o);copy.id=`peer-${i}`;copy.native.groupId='peer';copy.position=copy.position.map((v,j)=>v+delta.elements[12+j]);return copy;});const p={...imported,objects:[...first,...peer],selectionScope:'part'},text=first.find(o=>o.native.textConfiguration),objects=updateSceneTransform(p.objects,text.id,{position:[2,3,1]},{scope:'part'}),next=edited(p,objects);assertInstanceFamilies(next.objects);const result=importNative3MF(exportNative3MF(next));const texts=result.objects.filter(o=>o.native.textConfiguration);assert.equal(texts.length,2);assert.deepEqual(texts[0].native.textConfiguration,texts[1].native.textConfiguration);assert.ok(texts.every(o=>o.native.embossShape));
 const base=fixture();base.objects[0].brimEars=[{position:[40,40,5],radius:2}];base.objects[2].brimEars=[{position:[100,40,5],radius:2}];const changed=base.objects.map(o=>o.id==='i0p0'?{...o,brimEars:[{position:[43,42,5],radius:2}]}:o),out=edited(base,changed);assert.deepEqual(worldBrimEars(out.objects[2]).map(e=>({...e,position:e.position.map(v=>Math.round(v*1e8)/1e8)})),[{position:[98,43,5],radius:2}]);equivalent(out);});
test('native matrix rules match independent unchanged C++ Selection method in all six cases and both auto-drop states',async()=>{const {readFile}=await import('node:fs/promises'),reference=JSON.parse(await readFile(new URL('../fixtures/native-instance-reference.json',import.meta.url)));assert.equal(reference.commit,'8500fcdccaa10b5099ac20d252af3a7c560046f1');assert.equal(reference.cases.length,6);for(const {input,expected}of reference.cases)for(let index=0;index<input.peers.length;index++){const peer=input.peers[index],result=synchronizedInstanceFrame(new Matrix4().fromArray(input.old),new Matrix4().fromArray(input.current),new Matrix4().fromArray(peer.matrix),{rotation:input.rotation||'general',autoDrop:peer.autoDrop,sla:input.sla});result.elements.forEach((v,i)=>assert.ok(Math.abs(v-expected[index][i])<1e-12,`${input.name} / ${index} / ${i}: ${v} != ${expected[index][i]}`));}});
test('nonconflicting edits to different shared volumes merge instead of overwriting one another',()=>{const p=fixture(),objects=p.objects.map(o=>o.id==='i0p0'?{...o,name:'First changed'}:o.id==='i1p1'?{...o,name:'Second changed'}:o),next=edited(p,objects);assert.deepEqual(next.objects.map(o=>o.name),['First changed','Second changed','First changed','Second changed']);assert.deepEqual(next.objects.map(o=>o.id),p.objects.map(o=>o.id));equivalent(next);});
test('native parts normalization does not create false peer conflicts from absent empty override arrays',async()=>{const{normalizeNativeParts}=await import('../../shared/native-object-settings.js'),p=fixture(),objects=normalizeNativeParts(updateNativePart(structuredClone(p.objects),'i0p0',{name:'Changed',partSettings:{wall_loops:'7'}}),2),next=edited(p,objects);assert.equal(next.objects.filter(o=>o.name==='Changed').length,2);assert.equal(next.objects.filter(o=>o.native.partSettings.wall_loops==='7').length,2);equivalent(next);});
test('mirroring synchronizes linked instance handedness without detaching shared paint or indexed geometry',async()=>{const{mirrorNativeGroup}=await import('../../shared/geometry-cut.js'),p={...fixture(),selectionScope:'object'},next=edited(p,mirrorNativeGroup(p.objects,'i0p0','x'),{instanceScope:'object'});assert.ok(instanceDescriptor(group(next,0)).frame.determinant()<0);assert.ok(instanceDescriptor(group(next,1)).frame.determinant()<0);equivalent(next);});
