import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{createHash}from'node:crypto';
import{nativePreviewFixture}from'../fixtures/native-preview-result.js';import{validateNativePreview}from'../../shared/native-preview-data.js';import{adaptNativePreview,nativeVertexColor,nativeVertexAttributes,nativePreviewRange,nativeScalarModes,nativeScalarRangeKey}from'../../shared/native-preview-adapter.js';import{parseGcode}from'../../shared/gcode.js';
const fixture=JSON.parse(await readFile(new URL('../fixtures/native-scalar-reference.json',import.meta.url))),colors=hex=>hex.slice(1).match(/../g).map(v=>parseInt(v,16));
export function scalarFixture(){const data=nativePreviewFixture();data.vertices=structuredClone(fixture.synthetic.vertices);data.vertexCount=data.processorMoveCount=data.vertices.length;data.scalarRangesVersion=1;data.scalarRanges=Object.fromEntries(Object.entries(fixture.synthetic.expected).map(([key,value])=>[key,value.ranges]));return data;}
const parsedFixture=()=>{const data=scalarFixture();return adaptNativePreview(parseGcode(data.vertices.map((v,i)=>`G1 X${i*5} F1200`).join('\n'),{includeSource:true}),data);};
test('scalar reference retains original source provenance and four distinct visibility combinations',async()=>{assert.equal(fixture.commit,'8500fcdccaa10b5099ac20d252af3a7c560046f1');assert.equal(fixture.referenceSha256,createHash('sha256').update(await readFile(new URL('../fixtures/native-scalar-reference.cpp',import.meta.url))).digest('hex'));assert.equal(Object.keys(fixture.synthetic.expected).length,4);assert.equal(Object.keys(nativeScalarModes).length,7);assert.equal(validateNativePreview(scalarFixture()).scalarRangesVersion,1);});
test('all seven scalar colors match original C++ for every native motion/event and Travel/Wipe combination',()=>{
 const parsed=parsedFixture();let compared=0;for(const travels of[false,true])for(const wipes of[false,true]){const options={travels,wipes},expected=fixture.synthetic.expected[nativeScalarRangeKey(options)];for(const mode of Object.keys(nativeScalarModes)){const range=nativePreviewRange(parsed,mode,{options});assert.equal(range.min,expected.ranges[mode].min);assert.equal(range.max,expected.ranges[mode].max);assert.deepEqual(range.values,expected.ranges[mode].values);for(let i=0;i<parsed.native.data.vertices.length;i++){assert.deepEqual(colors(nativeVertexColor(parsed,i,mode,range)),expected.colors[mode][i],`${mode}/${travels}/${wipes}/${i}`);compared++;}}}assert.equal(compared,448);
});
test('scalar ranges honor Travel/Wipe controls but retain normal-role and Custom native range semantics',()=>{
 const parsed=parsedFixture();const hidden=nativePreviewRange(parsed,'speed'),travel=nativePreviewRange(parsed,'speed',{options:{travels:true}}),wipe=nativePreviewRange(parsed,'speed',{options:{wipes:true}}),both=nativePreviewRange(parsed,'speed',{options:{travels:true,wipes:true}});assert.ok(travel.max>hidden.max);assert.ok(wipe.min<hidden.min);assert.equal(both.min,wipe.min);assert.equal(both.max,travel.max);assert.ok(both.total>hidden.total);assert.equal(both.scope,'motion');assert.equal(nativePreviewRange(parsed,'temperature').scope,'extrusion');for(const mode of Object.keys(nativeScalarModes))assert.deepEqual(nativePreviewRange(parsed,mode,{hiddenFeatures:['Custom','Outer wall']}),nativePreviewRange(parsed,mode));
});
test('PA before its first command is gray and absent from the native range; native raw cursor values remain exact',()=>{
 const parsed=parsedFixture(),range=nativePreviewRange(parsed,'pressureAdvance');assert.equal(nativeVertexColor(parsed,0,'pressureAdvance',range),'#b8bdc0');assert.equal(range.min,Math.fround(.012));assert.equal(nativeVertexAttributes(parsed.native.data,0).pressureAdvance,null);assert.equal(nativeVertexAttributes(parsed.native.data,3).speed,5);assert.equal(nativeVertexAttributes(parsed.native.data,3).actualSpeed,4);assert.equal(nativeVertexAttributes(parsed.native.data,3).fanSpeed,50);assert.equal(nativeVertexAttributes(parsed.native.data,3).temperature,200);
});
test('additive capability preserves old helper compatibility and rejects malformed scalar collections',()=>{
 const old=nativePreviewFixture(),parsed=adaptNativePreview(parseGcode('G1 X0\nG1 X10',{includeSource:true}),old);assert.equal(validateNativePreview(old),old);for(const mode of Object.keys(nativeScalarModes)){const range=nativePreviewRange(parsed,mode);assert.equal(range.available,0);assert.equal(range.unavailable,true);}
 const changes=[v=>v.scalarRangesVersion=2,v=>delete v.scalarRanges,v=>delete v.scalarRanges.travelVisibleWipeVisible,v=>v.scalarRanges.travelVisibleWipeVisible.speed.min=NaN,v=>v.scalarRanges.travelVisibleWipeVisible.speed.max=-1,v=>v.scalarRanges.travelVisibleWipeVisible.speed.palette[0][0]=300,v=>v.scalarRanges.travelVisibleWipeVisible.speed.values=[Infinity],v=>v.scalarRanges.travelVisibleWipeVisible.speed.count=500001];for(const change of changes){const v=structuredClone(scalarFixture());change(v);assert.throws(()=>validateNativePreview(v),/Invalid native preview/);}
});
