import test from 'node:test';
import assert from 'node:assert/strict';
import {nativeMultipartDetected,needsNativeMultipartChoice,mergeNativeMultipartGeometry,geometryMultipartDescriptor} from '../../shared/native-multipart-import.js';
import {importNativeGeometry} from '../../shared/native-geometry-import.js';
import {emptyProject} from '../../shared/project.js';
import {meshBounds,sceneBounds} from '../../shared/geometry.js';
import {importNative3MF,exportNative3MF} from '../../shared/native-project.js';
import {multipartFixture} from '../fixtures/multipart-project.js';
import {fixture} from '../fixtures/native-instance-project.js';
const bed={width:250,depth:210,height:220};
const destination=()=>({...multipartFixture(),objects:[],selectedId:null,selectedIds:[]});
test('native multipart predicate respects one ModelObject per family, multiple volumes, first-instance height and epsilon',()=>{const p=multipartFixture();assert.equal(needsNativeMultipartChoice(p),true);p.objects[1].position[2]=0;assert.equal(needsNativeMultipartChoice(p),false);p.objects[1].position[2]=.00005;assert.equal(needsNativeMultipartChoice(p),false);p.objects[1].position[2]=.0002;assert.equal(needsNativeMultipartChoice(p),true);assert.equal(needsNativeMultipartChoice(fixture({parts:1})),false);assert.equal(needsNativeMultipartChoice(fixture()),false);assert.deepEqual(geometryMultipartDescriptor(multipartFixture()).map(o=>o.minZ),[0,20]);});
test('native ordered multipart decision returns at the first differing height, before a later complex object',()=>{const simple=z=>({volumeCount:1,configKeys:1,minZ:z}),complex={volumeCount:2,configKeys:1,minZ:10};assert.equal(nativeMultipartDetected([simple(0),simple(1),complex]),true);assert.equal(nativeMultipartDetected([simple(0),complex,simple(1)]),false);assert.equal(nativeMultipartDetected([simple(0),{...simple(1),configKeys:2}]),false);});
test('Yes preserves stacked native part geometry and painting while No grounds separate objects independently',()=>{const source=multipartFixture();source.objects[1].painting={version:1,color:{4:'4'},supports:{4:'8'}};const before=structuredClone(source),merged=mergeNativeMultipartGeometry(source,{name:'Stack'}),yes=importNativeGeometry(destination(),merged,bed,{centerAllParts:true}),no=importNativeGeometry(destination(),source,bed);assert.equal(new Set(yes.objects.map(o=>o.native.groupId)).size,1);assert.equal(new Set(no.objects.map(o=>o.native.groupId)).size,2);assert.equal(sceneBounds(yes.objects).size[2],40);assert.equal(sceneBounds(no.objects).size[2],20);assert.deepEqual(meshBounds(yes.objects[1]).min,[115,95,20]);assert.deepEqual(yes.objects[1].painting,source.objects[1].painting);assert.deepEqual(source,before);const round=importNative3MF(exportNative3MF(yes));assert.equal(sceneBounds(round.objects).size[2],40);assert.deepEqual(round.objects[1].painting.color,{4:'4'});});
test('merged parts use native volume-over-object material priority and discard former object state',()=>{const source=multipartFixture();for(const o of source.objects){o.native.objectSettings={extruder:'2',wall_loops:'8'};o.native.layerHeightProfile=[0,.2,1,.2,20,.2];o.native.layerConfigRanges=[{minZ:0,maxZ:1,settings:{layer_height:'.1'}}];o.native.cutId={id:'42',checkSum:'1',connectorsCount:'0'};o.brimEars=[{position:[0,0,0],radius:2}];o.printable=false;}source.objects[0].native.partSettings={extruder:'0'};source.objects[1].native.partSettings={};const merged=mergeNativeMultipartGeometry(source);assert.deepEqual(merged.objects.map(o=>o.filamentSlot),[1,2]);for(const o of merged.objects){assert.equal(o.printable,true);assert.deepEqual(o.native.objectSettings,{extruder:'1'});for(const key of ['layerHeightProfile','layerConfigRanges','cutId','instanceFamily','groupTransform'])assert.equal(o.native[key],undefined);assert.equal(o.brimEars,undefined);}});
test('multipart conversion expands linked mirrored instances into independent volume copies in one retained model frame',()=>{const linked=fixture({mirror:true}),other=multipartFixture();other.objects=other.objects.slice(1);const source={...linked,objects:[...linked.objects,...other.objects]},out=mergeNativeMultipartGeometry(source,{name:'Combined'});assert.equal(out.objects.length,5);assert.ok(out.objects.every(o=>!o.native.instanceFamily));assert.deepEqual(out.objects.map(o=>o.name),['Shared','Shared','Shared','Shared','Top']);const placed=importNativeGeometry(destination(),out,bed,{centerAllParts:true}),round=importNative3MF(exportNative3MF(placed));assert.equal(round.objects.length,5);assert.equal(new Set(round.objects.map(o=>o.native.groupId)).size,1);for(const o of round.objects.slice(0,4))assert.deepEqual(o.painting.color,{0:'4'});});

test('multipart decisions and affine/config/name conversion match original compiled native methods',async()=>{const {readFileSync}=await import('node:fs'),{BoxGeometry,Matrix4,Vector3}=await import('three'),{createMesh}=await import('../../shared/geometry.js'),r=JSON.parse(readFileSync(new URL('../fixtures/native-multipart-import-reference.json',import.meta.url)));for(const row of r.predicates)assert.equal(nativeMultipartDetected(row.objects),row.detected,JSON.stringify(row.objects));
 const geometry=new BoxGeometry(10,10,10).toNonIndexed(),vertices=Array.from(geometry.attributes.position.array),triangles=Array.from({length:vertices.length/3},(_,i)=>i);
 for(const row of r.conversions){const source={...emptyProject(),objects:[]};for(const[g,group]of row.groups.entries())for(const[i,instance]of group.instances.entries())for(const[p,volume]of group.volumes.entries()){const build=new Matrix4().fromArray(instance),component=new Matrix4().fromArray(volume.matrix),matrix=build.clone().multiply(component),positions=[];for(let f=0;f<triangles.length;f+=3)for(const n of(matrix.determinant()<0?[0,2,1]:[0,1,2])){const v=triangles[f+n]*3;positions.push(...new Vector3(...vertices.slice(v,v+3)).applyMatrix4(matrix).toArray());}source.objects.push(createMesh({id:`${g}-${i}-${p}`,name:volume.name,plateId:'plate-1',positions,filamentSlot:volume.extruder||group.objectExtruder||1,native:{groupId:`${g}-${i}`,instanceFamily:`family-${g}`,objectName:group.name,objectSettings:group.objectExtruder===null?{}:{extruder:String(group.objectExtruder)},partSettings:volume.extruder===null?{}:{extruder:String(volume.extruder)},meshSource:{version:1,vertices,triangles,component:volume.matrix,build:instance}}}));}
 const out=mergeNativeMultipartGeometry(source,{name:'Stack'});assert.equal(out.objects[0].native.objectName,row.result.name);assert.equal(out.objects.length,row.result.volumes.length);out.objects.forEach((o,i)=>{const expected=row.result.volumes[i];assert.equal(o.name,expected.name);assert.equal(o.native.partSettings.extruder,expected.extruder===null?undefined:String(expected.extruder));o.native.meshSource.component.forEach((v,a)=>assert.ok(Math.abs(v-expected.matrix[a])<1e-10,`${row.name} ${i}:${a}`));});}geometry.dispose();});
test('multipart native reference retains source and generator provenance',async()=>{const{readFileSync}=await import('node:fs'),{createHash}=await import('node:crypto'),r=JSON.parse(readFileSync(new URL('../fixtures/native-multipart-import-reference.json',import.meta.url)));assert.equal(r.commit,'8500fcdccaa10b5099ac20d252af3a7c560046f1');assert.equal(r.predicates.length,49);assert.equal(r.conversions.length,3);for(const[key,path]of [['generatorSha256','../../scripts/reference/build-multipart-import-reference.py'],['referenceSha256','../fixtures/native-multipart-import-reference.cpp']])assert.equal(createHash('sha256').update(readFileSync(new URL(path,import.meta.url))).digest('hex'),r[key]);});
test('multipart warning uses the unmodified installed native asset with pinned attribution',async()=>{const{readFileSync}=await import('node:fs'),{createHash}=await import('node:crypto'),manifest=JSON.parse(readFileSync(new URL('../../public/native-dialogs/manifest.json',import.meta.url)));assert.equal(manifest.baseline,'OrcaSlicer2.4.2');const matches=manifest.assets.filter(asset=>asset.file==='exclamation.svg');assert.equal(matches.length,1);const asset=matches[0];assert.equal(createHash('sha256').update(readFileSync(new URL('../../public/native-dialogs/'+asset.file,import.meta.url))).digest('hex'),asset.sha256);assert.match(readFileSync(new URL('../../public/native-dialogs/NOTICE.md',import.meta.url),'utf8'),/Affero/);});
