import test from 'node:test';import assert from 'node:assert/strict';import{createHash}from'node:crypto';
import{nativePreviewFixture}from'../fixtures/native-preview-result.js';import{validateNativePreview}from'../../shared/native-preview-data.js';import{adaptNativePreview,nativeVertexColor,nativePreviewRange,nativePreviewLegendRows}from'../../shared/native-preview-adapter.js';import{loadNativePreview}from'../../shared/native-preview-client.js';import{parseGcode}from'../../shared/gcode.js';import{selectPreviewSegments,previewCommandWindow}from'../../shared/gcode-preview.js';
const text='G1 X0\nG1 X10\n',base=()=>parseGcode(text,{includeSource:true});
test('native schema rejects non-finite geometry, invalid adjacency, names, colors and unbounded output collections',()=>{
 const original=nativePreviewFixture();assert.equal(validateNativePreview(original),original);
 for(const change of [v=>v.vertices[0][0]=NaN,v=>v.vertices[1][26]=1,v=>v.vertices[1][11]=8,v=>v.modes.push({...v.modes[0],name:'guess'}),v=>v.ranges.normal.customVisible.width.palette[0]=[999,0,0],v=>v.ranges.normal.customVisible.width.values=[NaN],v=>v.ranges.normal.customVisible.layerTime.layerColors=[],v=>v.toolsColors=[[999,0,0]],v=>v.nativeWarnings=[{message:'a'.repeat(16385)}]]){const value=structuredClone(original);change(value);assert.throws(()=>validateNativePreview(value),/Invalid native preview/);}
});
test('native render IDs, raw commands and per-endpoint geometry remain distinct from old parsed indices',()=>{
 const parsed=adaptNativePreview(base(),nativePreviewFixture());assert.equal(parsed.segments.length,1);const move=parsed.segments[0];assert.equal(move.nativeStartVertex,0);assert.equal(move.nativeEndVertex,1);assert.equal(move.line,2);assert.equal(parsed.native.volumeData.segments[0].end.nativeVertexIndex,1);assert.deepEqual(parsed.native.volumeData.segments[0].end.position,[10,0,.1]);assert.deepEqual(parsed.native.volumeData.segments[0].end.hwa,[.2,.4,0,0]);assert.equal(parsed.native.attributes[0].actualFlow,Math.fround(20*.08));const selected=selectPreviewSegments(parsed,{}),window=previewCommandWindow(parsed,selected);assert.equal(window.currentLine,2);assert.equal(window.rows.find(row=>row.selected).text,'G1 X10');assert.equal(nativeVertexColor(parsed,1,'tool'),'#ff0000');const range=nativePreviewRange(parsed,'layerTimeLog');assert.equal(nativeVertexColor(parsed,1,'layerTimeLog',range),'#0b2c7a');assert.deepEqual(nativePreviewLegendRows(range),[{value:1,color:'#0b2c7a'}]);
});
test('native adapter refuses missing, incomplete or out-of-range command mapping and unavailable modes',()=>{
 assert.throws(()=>adaptNativePreview({},nativePreviewFixture()),/Complete source/);assert.throws(()=>adaptNativePreview({...base(),source:{lines:['G1'],complete:false}},nativePreviewFixture()),/Complete source/);assert.throws(()=>adaptNativePreview({...base(),source:{lines:['G1'],complete:true}},nativePreviewFixture()),/outside/);assert.throws(()=>adaptNativePreview(base(),nativePreviewFixture(),{timeMode:'stealth'}),/unavailable/);
});
test('native fetch requires matching full source bytes and provides explicit fallback on unavailable/error/mismatched output',async()=>{
 const value={...nativePreviewFixture(),sourceSha256:createHash('sha256').update(text).digest('hex'),sourceBytes:Buffer.byteLength(text)},routes=[];
 const fetcher=async url=>{routes.push(url);return Response.json(url.endsWith('capabilities')?{available:true}:value);};assert.ok((await loadNativePreview(base(),text,{jobId:'own',fetcher})).native);assert.deepEqual(routes,['/api/jobs/native-preview/capabilities','/api/jobs/own/native-preview']);
 for(const fetcher of [async()=>Response.json({available:false,error:'Missing worker'}),async url=>Response.json(url.endsWith('capabilities')?{available:true}:{...value,sourceSha256:'0'.repeat(64)}),async url=>url.endsWith('capabilities')?Response.json({available:true}):Response.json({error:'Processor failed'},{status:503})]){const result=await loadNativePreview(base(),text,{jobId:'own',fetcher});assert.equal(result.native,undefined);assert.ok(result.nativeUnavailable);}
 const controller=new AbortController();controller.abort();await assert.rejects(loadNativePreview(base(),text,{jobId:'own',signal:controller.signal,fetcher:async()=>{throw new Error('aborted');}}),/aborted/);
});
