import test from'node:test';import assert from'node:assert/strict';
import{normalizeNativePreviewContext}from'../../shared/native-preview-context.js';import{snapshotNativePreviewContext,captureNativePreviewContext}from'../../server/native-preview-context.js';import{nativeEditorTestContext}from'../fixtures/native-editor-context.js';import{createNativePreviewPreferences,nativePreviewPreferencesForData}from'../../shared/native-preview-preferences.js';import{nativePreviewFixture}from'../fixtures/native-preview-result.js';import{validateNativePreview}from'../../shared/native-preview-data.js';import{readFile}from'node:fs/promises';
test('editor context copies and normalizes only bounded native palette/property/event data',()=>{const source=nativeEditorTestContext();source.filamentColors[0]='#c800ff';const result=normalizeNativePreviewContext(source);assert.equal(result.filamentColors[0],'#C800FF');source.filamentDiameters[0]=5;source.customEvents[0].z=8;assert.equal(result.filamentDiameters[0],1.75);assert.equal(result.customEvents[0].z,.2);assert.throws(()=>normalizeNativePreviewContext({...source,script:'M112'}),/Unsupported/);});
test('editor context rejects invalid or mismatched native properties and event assignments',()=>{for(const patch of[{filamentColors:[]},{filamentColors:['javascript:x']},{filamentDiameters:[1.75]},{filamentDiameters:[0,2.85]},{filamentDensities:[NaN,.97]},{filamentCosts:[22,-1]},{timeCost:Infinity},{timeCost:'2'},{customEvents:[{type:1.5,z:.2,extruder:1,color:''}]},{customEvents:[{type:0,z:.2,extruder:3,color:''}]},{customEvents:[{type:1,z:.2,extruder:-1,color:'',gcode:'M112'}]},{customEvents:Array(10001).fill({})}])assert.throws(()=>normalizeNativePreviewContext({...nativeEditorTestContext(),...patch}));});
test('job snapshot retains resolved defaults and strips event commands without guessing missing values',()=>{const settings={filament_colour:['#AaBB00'],filament_diameter:['1.75'],filament_density:['1.24'],filament_cost:['22'],time_cost:'7'},events=[{printZ:1.2,type:'ColorChange',extruder:1,color:'#123ABC',gcode:'M600',extra:'private'}];const snapshot=snapshotNativePreviewContext(settings,{events});assert.equal(snapshot.timeCost,7);assert.deepEqual(snapshot.customEvents,[{type:0,z:1.2,extruder:1,color:'#123ABC'}]);settings.filament_colour[0]='#FFFFFF';assert.equal(snapshot.filamentColors[0],'#AABB00');assert.throws(()=>snapshotNativePreviewContext({...settings,filament_cost:undefined}));assert.throws(()=>snapshotNativePreviewContext({...settings,time_cost:undefined}));});
test('native smart default changes only between single and multi extruder categories',async()=>{const reference=JSON.parse(await readFile(new URL('../fixtures/native-editor-reference.json',import.meta.url))),oracle=reference.cases[0].expected.smart;let preferences=createNativePreviewPreferences();for(const[count,category,mode]of oracle){const data=nativePreviewFixture();data.vertices=Array.from({length:count},(_,i)=>{const vertex=[...data.vertices[0]];vertex[14]=i;return vertex;});preferences=nativePreviewPreferencesForData(preferences,data);assert.equal(preferences.category,category);assert.equal(preferences.mode,['feature','color','width'][mode]);preferences.mode='width';}});
test('native viewer preferences retain visibility and copy mutable arrays across reloads',()=>{const data=nativePreviewFixture(),previous={...createNativePreviewPreferences(),category:1,mode:'width',hiddenFeatures:['Outer wall'],topLayerOnly:false,showCode:true};previous.options.travel=true;const next=nativePreviewPreferencesForData(previous,data);assert.equal(next.mode,'width');assert.equal(next.topLayerOnly,false);assert.equal(next.showCode,true);assert.equal(next.options.travel,true);next.hiddenFeatures.push('Support');next.options.travel=false;assert.deepEqual(previous.hiddenFeatures,['Outer wall']);assert.equal(previous.options.travel,true);});
test('unsupported remembered native capability falls back to feature without fabricating data',()=>{for(const mode of['summary','pressureAdvance','invalid']){const next=nativePreviewPreferencesForData({...createNativePreviewPreferences(),category:1,mode},nativePreviewFixture());assert.equal(next.mode,'feature');}});
test('optional editor statistics and custom overview validate capabilities, bounds and provenance',()=>{const valid=()=>{const data=nativePreviewFixture();data.colorPaletteSource='native-editor-job';data.editorStatisticsVersion=1;data.editorStatistics={source:'native-editor-formula',filamentMm:20,filamentGrams:1,filamentMm3:40,cost:.03,timeCost:2};data.customEventOverviewVersion=1;data.customEventOverview=[{type:1,extruder:-1,z:.2,layer:1,seconds:[0],labels:['0s']}];return data;};assert.doesNotThrow(()=>validateNativePreview(valid()));for(const mutate of[d=>d.editorStatistics.cost=-1,d=>d.colorPaletteSource='native-standalone-import',d=>d.customEventOverview[0].layer=2,d=>d.customEventOverview[0].seconds=[NaN],d=>d.customEventOverview[0].type=6,d=>d.modes[0].summaryTimeLabel='x'.repeat(65)]){const data=valid();mutate(data);assert.throws(()=>validateNativePreview(data));}});

test('bounded preview snapshot failure remains explicit without blocking the slicing pipeline',()=>{const result=captureNativePreviewContext({});assert.equal(result.nativePreviewContext,undefined);assert.match(result.nativePreviewContextUnavailable,/snapshot is unavailable/);});
