import test from 'node:test';import assert from 'node:assert/strict';
import {fixture} from '../fixtures/native-instance-project.js';
import {nativeObjectTree,flattenNativeTree,nativeTreeShowsVolumes,nativeTreeSettingsCategories,nativeTreeCategoryExcluded,nativeTreeInstanceLabel,selectNativeTreeNode,nativeTreeNodeSelected,setNativeTreePrintable,resetNativeTreeSettings,nativeTreeHasVisible,setNativeTreeVisible} from '../../shared/native-object-tree.js';
import {exportNative3MF,importNative3MF} from '../../shared/native-project.js';
import {reconcileNativeInstanceEdits} from '../../shared/native-instance-edits.js';
const nodes=p=>flattenNativeTree(nativeObjectTree(p,{filamentCount:2,globalSettings:{layer_height:'.2'}}));
const node=(p,kind,index=0)=>nodes(p).filter(n=>n.kind===kind)[index];
function configured(){const p=fixture();for(const o of p.objects){o.native.objectSettings={extruder:'2',wall_loops:'4',layer_height:'.2'};o.native.partSettings={extruder:'1',sparse_infill_density:'30%'};o.native.layerConfigRanges=[{minZ:4,maxZ:8,settings:{extruder:'0',layer_height:'.1',wall_loops:'7'}},{minZ:0,maxZ:2,settings:{extruder:'1',layer_height:'.2'}}];o.native.layerHeightProfile=[0,.2,1,.1,10,.2];}return p;}
test('one native object owns shared volumes, sorted Layers then Instances, painted/height flags and assigned plate root',()=>{const p=configured(),before=structuredClone(p),tree=nativeObjectTree(p,{filamentCount:2,globalSettings:{layer_height:'.2'}});assert.equal(tree.length,2);assert.equal(tree[0].label,'Plate 1');assert.equal(tree[1].label,'Outside');assert.equal(tree[0].children.length,1);const root=tree[0].children[0];assert.deepEqual(root.children.map(n=>n.kind),['volume','volume','layers','instances']);assert.equal(root.variableHeight,true);assert.equal(root.colorPaint,true);assert.equal(root.supportPaint,false);assert.equal(root.filament,2);assert.deepEqual(root.children[2].children.map(n=>n.label),['Range 0.00-2.00 (mm)','Range 4.00-8.00 (mm)']);assert.equal(root.children[2].children[0].rangeIndex,1);assert.equal(root.children[2].children[0].categories.length,0);assert.deepEqual(p,before);});
test('a missing native extruder key omits the range row while retaining Layers and untouched metadata',()=>{const p=configured();for(const o of p.objects)o.native.layerConfigRanges=[{minZ:0,maxZ:2,settings:{layer_height:'.1'}}];assert.equal(node(p,'layers').children.length,0);assert.equal(p.objects[0].native.layerConfigRanges.length,1);});
test('cut connector predicate hides processed connectors and exposes dedicated selection even when volumes collapse',()=>{const p=fixture();for(const o of p.objects){o.native.cutId={id:'20',checkSum:'2',connectorsCount:'1'};if(o.id.endsWith('p1'))o.native.cutConnector={type:'plug',radiusTolerance:0,heightTolerance:0};}assert.equal(nativeTreeShowsVolumes(p.objects.slice(0,2)),false);assert.deepEqual(node(p,'object').children.map(n=>n.kind),['connectors','instances']);const selected=selectNativeTreeNode(p,node(p,'connectors'));assert.deepEqual(selected.selectedIds,['i0p1']);assert.equal(selected.selectionScope,'part');p.objects[0].native.partType='modifier_part';assert.equal(nativeTreeShowsVolumes(p.objects.slice(0,2)),true);});
test('native source categories exclude restricted roles, parent-equal layer height and unsupported scope keys',()=>{assert.deepEqual(nativeTreeSettingsCategories({wall_loops:'4'},{kind:'volume',role:'negative_part'}),[]);assert.deepEqual(nativeTreeSettingsCategories({layer_height:'.2'},{kind:'volume'}),[]);assert.deepEqual(nativeTreeSettingsCategories({layer_height:'.2'},{kind:'layer',parentSettings:{layer_height:'.2'}}),[]);assert.ok(nativeTreeSettingsCategories({wall_loops:'4'}).length);assert.deepEqual(nativeTreeSettingsCategories({made_up_option:'1'}),[]);assert.equal(nativeTreeInstanceLabel(0,2),'Instance 1');assert.equal(nativeTreeInstanceLabel(0,2,{renumbered:true}),'[P2]Instance 1');assert.equal(nativeTreeInstanceLabel(0,0,{renumbered:true}),'Instance 1');});
test('object selects current-plate instances; instance chooses one group; part row follows selected instance',()=>{const p=fixture(),root=node(p,'object');let selected=selectNativeTreeNode(p,root);assert.deepEqual(selected.selectedIds,p.objects.map(o=>o.id));assert.equal(nativeTreeNodeSelected(selected,root),true);selected=selectNativeTreeNode(selected,node(p,'instance',1));assert.deepEqual(selected.selectedIds,['i1p0','i1p1']);selected=selectNativeTreeNode(selected,node(p,'volume',0));assert.deepEqual(selected.selectedIds,['i1p0']);assert.equal(selected.selectionScope,'part');assert.equal(nativeTreeNodeSelected(selected,node(p,'volume',0)),true);assert.equal(nativeTreeNodeSelected(selected,root),false);});
test('cross-plate instance selection switches plate explicitly; object selection stays on that plate',()=>{const p=fixture();p.plates.push({id:'plate-2',name:'Second'});for(const o of p.objects.slice(2))o.plateId='plate-2';const tree=nativeObjectTree(p);assert.equal(tree[0].children.length,1);assert.equal(tree[1].children.length,0);let selected=selectNativeTreeNode(p,node(p,'instance',1));assert.equal(selected.activePlateId,'plate-2');assert.deepEqual(selected.selectedIds,['i1p0','i1p1']);selected=selectNativeTreeNode(selected,node(p,'object'));assert.deepEqual(selected.selectedIds,['i1p0','i1p1']);selected=selectNativeTreeNode(selected,tree[0]);assert.equal(selected.activePlateId,'plate-1');assert.equal(selected.selectedId,null);});
test('printability is per instance or all shared instances and survives strict native 3MF roundtrip',()=>{const p=fixture(),before=structuredClone(p);let next=setNativeTreePrintable(p,node(p,'instance',1),false);next=reconcileNativeInstanceEdits(p,next);assert.deepEqual(next.objects.map(o=>o.printable!==false),[true,true,false,false]);assert.equal(node(next,'object').printable,true);assert.deepEqual(p,before);const imported=importNative3MF(exportNative3MF(next));assert.deepEqual(imported.objects.map(o=>o.printable!==false),[true,true,false,false]);next=setNativeTreePrintable(next,node(next,'object'),false);assert.equal(node(next,'object').printable,false);assert.ok(next.objects.every(o=>o.printable===false));});
test('native action reset preserves extruder and object-only part compensation, applies linked parts atomically',()=>{const p=configured();for(const o of p.objects)o.native.partSettings.layer_height='.3';const before=structuredClone(p);let next=resetNativeTreeSettings(p,node(p,'volume',0));assert.deepEqual(next.objects[0].native.partSettings,{extruder:'1',layer_height:'.3'});assert.deepEqual(next.objects[2].native.partSettings,next.objects[0].native.partSettings);assert.equal(next.objects[1],p.objects[1]);next=resetNativeTreeSettings(p,node(p,'object'));assert.ok(next.objects.every(o=>JSON.stringify(o.native.objectSettings)==='{"extruder":"2"}'));assert.deepEqual(p,before);});
test('layer reset retains extruder and restores parent layer_height without modifying other ranges; stale rows reject',()=>{const p=configured(),target=node(p,'layer',1),next=resetNativeTreeSettings(p,target,{globalSettings:{layer_height:'.25'}});for(const [index,o] of next.objects.entries()){assert.deepEqual(o.native.layerConfigRanges[0].settings,{extruder:'0',layer_height:'.2'});assert.equal(o.native.layerConfigRanges[1],p.objects[index].native.layerConfigRanges[1]);}const deleted={...p,objects:[]};assert.throws(()=>setNativeTreePrintable(deleted,node(p,'object'),false),/tree changed/);assert.throws(()=>selectNativeTreeNode(deleted,node(p,'volume')),/tree changed/);});

test('unchanged pinned C++ predicate and SetIdx reference match exhaustive connector/type combinations and renumber labels',async()=>{const {default:reference}=await import('../fixtures/native-object-tree-reference.json',{with:{type:'json'}});assert.equal(reference.provenance.commit,'8500fcdccaa10b5099ac20d252af3a7c560046f1');for(const row of reference.volumes){const parts=row.parts.map(p=>({native:{...(row.cut&&{cutId:{id:'1'}}),...(p.connector&&{cutConnector:{type:'plug'}}),partType:p.model?'normal_part':'modifier_part'}}));assert.equal(nativeTreeShowsVolumes(parts),row.expected,JSON.stringify(row));}for(const row of reference.categories)assert.equal(nativeTreeCategoryExcluded(row.category,row.filaments,row.object),row.excluded,JSON.stringify(row));for(const row of reference.labels)assert.equal(nativeTreeInstanceLabel(row.index,row.plate,{renumbered:true}),row.expected);});

test('role icons, inherited filament values and reset action availability follow native volume roles',()=>{const p=fixture();p.objects=p.objects.slice(0,2);for(const o of p.objects){delete o.filamentSlot;o.native.objectSettings={extruder:'2'};o.native.partSettings={wall_loops:'4'};}p.objects[1].native.partType='modifier_part';let tree=nodes(p);assert.equal(tree.find(n=>n.kind==='volume'&&n.volumeIndex===0).filament,2);assert.equal(tree.find(n=>n.kind==='volume'&&n.volumeIndex===1).filament,'default');p.objects[1].native.partType='negative_part';tree=nodes(p);const negative=tree.find(n=>n.kind==='volume'&&n.volumeIndex===1);assert.equal(negative.filament,null);assert.equal(negative.icon,'menu_add_negative');assert.deepEqual(negative.categories,[]);assert.throws(()=>resetNativeTreeSettings(p,negative),/no editable/);});

test('Hide/Show preserves native printability and other instances, and does not mutate the source',()=>{const p=fixture(),before=structuredClone(p),target=node(p,'instance',1);let next=setNativeTreeVisible(p,target,false);assert.equal(nativeTreeHasVisible(next,target),false);assert.deepEqual(next.objects.map(o=>o.visible!==false),[true,true,false,false]);assert.ok(next.objects.every(o=>o.printable!==false));next=reconcileNativeInstanceEdits(p,next);assert.deepEqual(next.objects.map(o=>o.visible!==false),[true,true,false,false]);assert.deepEqual(p,before);next=setNativeTreeVisible(next,target,true);assert.ok(next.objects.every(o=>o.visible));});
