import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{createHash}from'node:crypto';import * as THREE from'three';
import{nativePreviewFixture}from'../fixtures/native-preview-result.js';import{nativeToolPosition,nativeActualSpeedProfile,nativeEstimatedTimes,nativeToolMarkerVisible,nativeFixed,nativeElapsedLabel}from'../../shared/native-tool-position.js';import{parseNativeHotend,createPreviewToolMarker}from'../../src/preview-tool-marker.js';
const reference=JSON.parse(await readFile(new URL('../fixtures/native-tool-position-reference.json',import.meta.url)));
test('native tool reference retains source identity, enabled speed profile and excluded CoG release switches',async()=>{assert.equal(reference.commit,'8500fcdccaa10b5099ac20d252af3a7c560046f1');assert.equal(createHash('sha256').update(await readFile(new URL('../fixtures/native-tool-position-reference.cpp',import.meta.url))).digest('hex'),reference.referenceSha256);assert.equal(reference.nativeGui.samples.length,127);assert.ok(reference.sourceSha256['src/libslic3r/Technologies.hpp']);assert.ok(reference.sourceSha256['src/libvgcode/include/Types.hpp']);});
test('native tool marker appears only after scrubbing begins, remains on return to full range, and hides without paths',()=>{const full={full:[0,20],visible:[0,20],ticks:[{}]};assert.equal(nativeToolMarkerVisible(false,full),false);assert.equal(nativeToolMarkerVisible(false,{...full,visible:[0,10]}),true);assert.equal(nativeToolMarkerVisible(true,full),true);assert.equal(nativeToolMarkerVisible(true,{...full,ticks:[]}),false);assert.equal(nativeToolMarkerVisible(true,null),false);});
test('tool properties preserve seam geometry but use previous native vertex outside Feature view and never invent PA',()=>{const d=nativePreviewFixture();d.vertices.push([...d.vertices[1]]);d.vertices[2][11]=3;d.vertices[2][0]=11;d.vertices[2][5]=999;d.vertices[2][18]=null;const feature=nativeToolPosition(d,2),width=nativeToolPosition(d,2,{mode:'width'});assert.equal(feature.propertyVertexId,2);assert.equal(feature.detail,'Seam');assert.deepEqual(width.markerPosition,[11,0,.2]);assert.equal(width.propertyVertexId,1);assert.equal(width.speedText,'20');assert.equal(width.detail,'Width: 0.40');assert.equal(feature.rows.find(r=>r[0]==='Pressure Advance')[1],'Unavailable');assert.equal(nativeToolPosition(d,-1),null);assert.equal(nativeToolPosition(d,100),null);});
test('native format, float accumulation and profile boundaries retain exact source behavior',()=>{assert.equal(nativeFixed(2.5,0),'2');assert.equal(nativeFixed(3.5,0),'4');assert.equal(nativeFixed(-2.5,0),'-2');assert.equal(nativeElapsedLabel(3662.8),'1h 1m 2s');assert.equal(nativeElapsedLabel(.5),'0.500000s');const d=nativePreviewFixture();d.vertices[0][16]=16777216;d.vertices[1][16]=1;assert.deepEqual([...nativeEstimatedTimes(d)],[16777216,16777216]);assert.throws(()=>nativeEstimatedTimes(d,'unknown'),/unavailable/);assert.equal(nativeActualSpeedProfile(d,1),null);assert.equal(nativeActualSpeedProfile(d,-1),null);});
test('native default hotend mesh normals and marker matrices match compiled original source',async()=>{const bytes=await readFile(new URL('../../public/native-preview/hotend.stl',import.meta.url));assert.equal(createHash('sha256').update(bytes).digest('hex'),reference.hotend.sha256);const asset=parseNativeHotend(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));assert.equal(asset.triangles,560);for(let i=0;i<560;i++)for(let j=0;j<3;j++)for(let axis=0;axis<3;axis++)assert.ok(Math.abs(asset.normals[i*9+j*3+axis]-reference.hotend.normals[i][axis])<1e-6,`face ${i}/${axis}`);const marker=createPreviewToolMarker(asset),worldToNative=new THREE.Matrix4().makeRotationX(Math.PI/2);for(const sample of reference.hotend.transforms){assert.equal(marker.update(sample.position,true),true);const actual=new THREE.Matrix4().multiplyMatrices(worldToNative,marker.mesh.matrix);for(let i=0;i<16;i++)assert.ok(Math.abs(actual.elements[i]-sample.matrix[i])<1e-9);}assert.equal(marker.update(null,true),false);marker.dispose();});
test('native hotend asset rejects truncation, forged counts and nonfinite coordinates',async()=>{const bytes=await readFile(new URL('../../public/native-preview/hotend.stl',import.meta.url));const buffer=()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength);assert.throws(()=>parseNativeHotend(new ArrayBuffer(12)),/truncated/);let b=buffer();new DataView(b).setUint32(80,100001,true);assert.throws(()=>parseNativeHotend(b),/invalid geometry/);b=buffer();new DataView(b).setFloat32(96,NaN,true);assert.throws(()=>parseNativeHotend(b),/invalid coordinates/);});
