import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
import{nativePreviewRangeState,nativePreviewSelection,nativePreviewCommandWindow,nativePreviewOptions,nativePreviewVertexDimmed,nativePreviewVisibilityTransition,nativePreviewStep}from'../../shared/native-preview-range.js';
import{nativeFeaturePalette}from'../../shared/gcode-preview.js';
const fixture=JSON.parse(readFileSync(new URL('../fixtures/native-preview-range-reference.json',import.meta.url)));
export function expand(test){const c=test.control,vertices=test.vertices.map(row=>{const v=Array(27).fill(0);[v[11],v[13],v[10],v[12],v[26]]=row;return v;});return{data:{vertices,layers:Array.from({length:Math.max(...vertices.map(v=>v[13]))+1},()=>({})),spiralVase:c.spiralVase},settings:{...c,hiddenFeatures:c.hiddenRoles.map(id=>nativeFeaturePalette[id].name),options:Object.fromEntries(c.options.map((value,i)=>[nativePreviewOptions[i].key,value]))}};}
test('native range, retained hidden ticks and enabled geometry match 94 compiled original cases',()=>{fixture.cases.forEach((sample,i)=>{const{data,settings}=expand(sample),actual=transition(data,settings,sample.control);for(const key of Object.keys(sample.expected))assert.deepEqual(actual[key],sample.expected[key],`case ${i} ${key}`);});});
test('stationary events keep their original vertex and source line without inventing a segment',()=>{const sample=fixture.cases[0],{data,settings}=expand(sample),state=nativePreviewRangeState(data,{...settings,visibleRange:[0,8],options:{...settings.options,retractions:true}}),parsed={native:{data},segments:[],source:{lines:Array.from({length:30},(_,i)=>`G1 X${i}; line ${i+1}`),complete:true}};assert.deepEqual(state.eventIds,[5,8]);const window=nativePreviewCommandWindow(parsed,state);assert.equal(window.nativeVertexIndex,8);assert.equal(window.segmentIndex,null);assert.equal(window.event,'Retract');assert.equal(window.currentLine,6);assert.equal(window.rows.find(row=>row.selected).line,6);});
test('top-only playback keeps lower geometry gray until the full native endpoint is reached',()=>{const{data,settings}=expand(fixture.cases[12]),state=nativePreviewRangeState(data,{...settings,visibleRange:[0,24]});assert.equal(state.dimLowerLayers,true);assert.equal(nativePreviewVertexDimmed(data,state,3,2),true);assert.equal(nativePreviewVertexDimmed(data,state,23,2),false);const full=nativePreviewRangeState(data,settings);assert.equal(full.dimLowerLayers,false);});
test('native ID selection is independent of spatial indices and control input is bounded',()=>{const parsed={segments:[{nativeStartVertex:42},{nativeStartVertex:2},{nativeStartVertex:8}]};assert.deepEqual(nativePreviewSelection(parsed,{segmentIds:[2,8]}).indices,[1,2]);const{data,settings}=expand(fixture.cases[0]);for(const changes of[{firstLayer:-1},{lastLayer:20},{visibleRange:[0,NaN]},{options:{seams:'yes'}},{options:{bogus:true}}])assert.throws(()=>nativePreviewRangeState(data,{...settings,...changes}));assert.deepEqual(nativePreviewRangeState({vertices:[],layers:[]}).ticks,[]);});

function transition(data,settings,control){const before=nativePreviewRangeState(data,settings);if(control.toggleOption!==undefined){const key=nativePreviewOptions[control.toggleOption].key;return nativePreviewVisibilityTransition(data,before,{...settings,options:{...settings.options,[key]:!settings.options[key]}},{kind:'option'});}if(control.toggleRole!==undefined){const role=nativeFeaturePalette[control.toggleRole].name;return nativePreviewVisibilityTransition(data,before,{...settings,hiddenFeatures:settings.hiddenFeatures.includes(role)?settings.hiddenFeatures.filter(v=>v!==role):[...settings.hiddenFeatures,role]});}return before;}

test('native shortcut composition counts hidden event ticks and crosses layer ranges with original vertex identities',()=>{const{data}=expand(fixture.cases[0]),settings={};let current={low:0,high:1,active:'high',singleLayer:false,remembered:1,nativeCursor:null};const home=nativePreviewStep(data,current,{action:'home'},settings);assert.equal(home.nativeCursor,11);assert.equal(data.vertices[home.nativeCursor][11],2);const right=nativePreviewStep(data,home,{action:'arrowright',amount:1},settings);assert.equal(right.nativeCursor,12);const maximum=nativePreviewStep(data,right,{action:'arrowright',amount:5},settings);assert.equal(maximum.nativeCursor,null);const nextLayer=nativePreviewStep(data,maximum,{action:'arrowright'},settings);assert.equal(nextLayer.high,2);assert.equal(nextLayer.nativeCursor,22);assert.equal(nextLayer.changed,true);});
