import test from 'node:test';import assert from 'node:assert/strict';
import {BoxGeometry} from 'three';import {emptyProject} from '../../shared/project.js';import {createMesh} from '../../shared/geometry.js';
import {captureProcessClipboard,prepareProcessSettingsPaste,applyProcessSettingsPaste,processClipboardAvailability,captureLayerClipboard,pasteLayerClipboard} from '../../shared/native-settings-clipboard.js';
import {normalizeObjectSettings,normalizeNativeParts} from '../../shared/native-object-settings.js';
function cube(id,group=id){const geo=new BoxGeometry(10,10,10).toNonIndexed(),object=createMesh({id,name:id,plateId:'plate-1',positions:Array.from(geo.attributes.position.array),position:[30,30,5],native:{groupId:group,partType:'normal_part',objectSettings:{wall_loops:'4'},partSettings:{sparse_infill_density:'30%'}}});geo.dispose();return object;}
const scene=()=>({...emptyProject(),objects:[cube('a'),cube('b'),cube('b-part','b')],selectedId:'a',selectedIds:['a']});
const range=(minZ,maxZ,height=.2,extra={})=>({minZ,maxZ,settings:{layer_height:String(height),extruder:'0',...extra}});
test('process Copy captures object then part overrides without global defaults or later source mutation',()=>{const p=scene();p.objects[0].native.partSettings.wall_loops='8';const copied=captureProcessClipboard(p,{scope:'part'});assert.deepEqual(copied.settings,{sparse_infill_density:'30%',wall_loops:'8'});p.objects[0].native.partSettings.wall_loops='9';assert.equal(copied.settings.wall_loops,'8');assert.deepEqual(captureProcessClipboard(p).settings,{wall_loops:'4'});});
test('process clipboard scopes and single-source bounds match context-menu availability',()=>{const p=scene(),clip=captureProcessClipboard(p);assert.match(processClipboardAvailability(p,clip,{scope:'part'}),/objects/);p.selectedIds=['a','b'];assert.throws(()=>captureProcessClipboard(p),/one object/);assert.equal(prepareProcessSettingsPaste(p,clip,{}).targets.length,2);assert.equal(processClipboardAvailability(p,null),'Copy process settings first');});
test('native process Paste updates every destination part atomically and preserves filament, other groups and source snapshot',()=>{const p=scene(),clip=captureProcessClipboard(p);p.selectedId='b';p.selectedIds=['b'];for(const object of p.objects.filter(o=>o.native.groupId==='b'))object.native.objectSettings={extruder:'2',wall_loops:'3'};const prepared=prepareProcessSettingsPaste(p,clip,{}, {filamentCount:2}),before=structuredClone(p);const result=applyProcessSettingsPaste(p,prepared,{settingsClipboardVersion:1,settings:[{wall_loops:'4',extruder:'2'}]});assert.deepEqual(p,before);assert.equal(result.objects[0],p.objects[0]);for(const o of result.objects.slice(1)){assert.equal(o.native.objectSettings.wall_loops,'4');assert.equal(o.native.objectSettings.extruder,'2');assert.equal(o.native.partSettings.sparse_infill_density,'30%');}assert.throws(()=>applyProcessSettingsPaste(p,prepared,{settingsClipboardVersion:1,settings:[{wall_loops:'4',extruder:'1'}]}),/filament/);assert.throws(()=>applyProcessSettingsPaste(p,prepared,{settingsClipboardVersion:1,settings:[]}),/result/);});
test('source-defined compensating object options survive native part storage while part editor validation stays region-only',()=>{assert.throws(()=>normalizeObjectSettings({layer_height:'.2'},1,{part:true}),/Unsupported part/);const p=scene();p.objects[0].native.partSettings={layer_height:'.2',wall_loops:'5'};const result=normalizeNativeParts(p.objects);assert.equal(result[0].native.partSettings.layer_height,'0.2');assert.throws(()=>normalizeNativeParts([{...p.objects[0],native:{...p.objects[0].native,partSettings:{post_process:'echo nope'}}}]),/Unsupported part/);});
test('selected layer copying accumulates and overwrites equal bounds; root copy replaces; draft index survives sorting',()=>{const first=[range(10,15,.1),range(0,4,.2)],a=captureLayerClipboard(first,null,{indices:[0]});assert.equal(a.ranges[0].minZ,10);const b=captureLayerClipboard(first,a,{indices:[1]});assert.deepEqual(b.ranges.map(r=>r.minZ),[0,10]);const c=captureLayerClipboard([range(10,15,.25)],b,{indices:[0]});assert.equal(c.ranges[1].settings.layer_height,'0.25');assert.equal(b.ranges[1].settings.layer_height,'0.1');assert.equal(captureLayerClipboard([range(2,5)],c).ranges.length,1);assert.throws(()=>captureLayerClipboard(first,null,{indices:[2]}),/valid height/);});
test('layer Paste preserves destination equal-bound values and adds overlapping ranges to every grouped part',()=>{const p=scene(),existing=[range(0,5,.1)],clip=captureLayerClipboard([range(0,5,.3),range(4,8,.15,{wall_loops:'6'})]);for(const o of p.objects.slice(1))o.native.layerConfigRanges=structuredClone(existing);const before=structuredClone(p),objects=pasteLayerClipboard(p.objects,'b',clip,1);assert.deepEqual(p,before);assert.equal(objects[0],p.objects[0]);for(const o of objects.slice(1)){assert.equal(o.native.layerConfigRanges.length,2);assert.equal(o.native.layerConfigRanges[0].settings.layer_height,'0.1');assert.equal(o.native.layerConfigRanges[1].settings.wall_loops,'6');}assert.throws(()=>pasteLayerClipboard(p.objects,'b',clip,1,{printer:{min_layer_height:['.2'],max_layer_height:['.3']}}),/between/);assert.throws(()=>pasteLayerClipboard(p.objects,'b',{version:1,kind:'layers',ranges:[]}),/Copy height/);});
