import test from 'node:test';import assert from 'node:assert/strict';import{Matrix4,Vector3,BoxGeometry}from'three';
import{createMesh,meshBounds}from'../../shared/geometry.js';import{emptyProject,serializeProject,parseProject}from'../../shared/project.js';import{exportNative3MF,importNative3MF}from'../../shared/native-project.js';
import{defaultNativeText,nativeTextFrame,nativeTextAnchor,prepareNativeTextCreation,applyNativeTextCreation}from'../../shared/native-text-creation.js';import{nativeEmbossRequest,nativeTextSettingsUnchanged}from'../../shared/native-emboss-regeneration.js';
const box=()=>{const geometry=new BoxGeometry(40,30,20).toNonIndexed();geometry.translate(100,100,10);const body=createMesh({id:'body',positions:Array.from(geometry.attributes.position.array),plateId:'plate-1'});geometry.dispose();return body;};
const result={vertices:[[0,0,-.015],[2,0,-.015],[0,2,-.015],[0,0,.985]],triangles:[[0,2,1],[0,1,3],[0,3,2],[1,2,3]],scale:1e-5,healed:true};
test('native surface frame follows independently expected upright bases including bottom and angled faces',()=>{
 for(const[n,x,y]of[[[0,0,1],[1,0,0],[0,1,0]],[[0,0,-1],[-1,0,0],[0,1,0]],[[1,0,0],[0,1,0],[0,0,1]],[[0,-1,0],[1,0,0],[0,0,1]],[[Math.SQRT1_2,0,Math.SQRT1_2],[0,1,0],[-Math.SQRT1_2,0,Math.SQRT1_2]]]){const frame=nativeTextFrame({anchor:[2,3,4],normal:n}),basis=[new Vector3(),new Vector3(),new Vector3()];frame.extractBasis(...basis);basis.flatMap(v=>v.toArray()).forEach((v,i)=>assert.ok(Math.abs(v-[...x,...y,...n][i])<1e-12));assert.deepEqual(new Vector3().setFromMatrixPosition(frame).toArray(),[2,3,4]);assert.ok(Math.abs(frame.determinant()-1)<1e-12);}
 const rotated=nativeTextFrame({angle:90});assert.ok(new Vector3(1,0,0).applyMatrix4(rotated).distanceTo(new Vector3(0,1,0))<1e-12);assert.throws(()=>nativeTextFrame({normal:[0,0,0]}),/cannot be zero/);assert.throws(()=>nativeTextFrame({angle:181}),/angle/);
});
test('standalone native creation rests on bed and roundtrips native text editing data without a placeholder',()=>{const prepared=prepareNativeTextCreation({textConfiguration:{...defaultNativeText(),text:'A'},bed:{width:200,depth:160,height:100}}),created=applyNativeTextCreation([],prepared,result,{fontName:'Helvetica',fontDescriptor:'Helvetica.ttc'});assert.equal(created.objects.length,1);const bounds=meshBounds(created.text);assert.ok(Math.abs(bounds.min[2])<1e-7);assert.ok(Math.abs(bounds.max[2]-1)<1e-7);assert.deepEqual(bounds.center.slice(0,2),[100,80]);assert.equal(created.text.text,undefined);assert.equal(created.text.native.textConfiguration.fontDescriptorType,'file_name');const project={...emptyProject(),objects:created.objects,selectedId:created.selectedId},saved=parseProject(serializeProject(project)),again=importNative3MF(exportNative3MF(saved,{includeWebProject:false}));assert.equal(again.objects[0].native.textConfiguration.text,'A');assert.ok(again.objects[0].native.meshSource);assert.equal(nativeEmbossRequest(again.objects,again.objects[0].id).request.text,'A');});
test('native engraved or modifier text adopts its object group without mutating the source and supplies only normal sources',()=>{for(const mode of ['engrave','modifier']){const body=box(),before=structuredClone(body),placement=nativeTextAnchor([body],body.id,'Front'),prepared=prepareNativeTextCreation({objects:[body],selectedId:body.id,mode,placement,useSurface:true}),created=applyNativeTextCreation([body],prepared,result);assert.deepEqual(body,before);assert.deepEqual(placement.anchor,[100,85,10]);assert.equal(prepared.request.outside,false);assert.equal(prepared.request.sources.length,1);assert.equal(created.text.native.partType,mode==='engrave'?'negative_part':'modifier_part');assert.equal(created.text.native.groupId,created.objects[0].native.groupId);assert.equal(created.text.plateId,body.plateId);assert.equal(created.text.native.embossShape.useSurface,true);}});
test('native creation rejects detached per-glyph/surface modes and invalid attachment before submitting a worker job',()=>{for(const options of [{useSurface:true},{textConfiguration:{...defaultNativeText(),perGlyph:true}},{mode:'engrave'},{mode:'invented'},{placement:{normal:[0,0,0],anchor:[0,0,0]}}])assert.throws(()=>prepareNativeTextCreation(options));});
test('unchanged native settings preserve semantic zero defaults and do not hide an actual edit or font substitution',()=>{const prepared=prepareNativeTextCreation(),part=applyNativeTextCreation([],prepared,result).text,options={textConfiguration:{...part.native.textConfiguration,charGap:0,lineGap:0,collection:0,boldness:0,skew:0},depth:1,useSurface:false,fontId:'font',initialFontId:'font'};assert.equal(nativeTextSettingsUnchanged(part,options),true);for(const change of [{depth:2},{useSurface:true},{fontId:'different'},{textConfiguration:{...options.textConfiguration,perGlyph:true}},{textConfiguration:{...options.textConfiguration,text:'Edited'}}])assert.equal(nativeTextSettingsUnchanged(part,{...options,...change}),false);});
