import{nativeFixed}from'../../shared/native-format.js';
import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{createHash}from'node:crypto';import{nativeRoleUsageLabels,nativeUsageDistance,nativeSummaryMaterialLabels,readNativeDisplayPreferences,saveNativeDisplayPreferences,NATIVE_UNITS_STORAGE_KEY,NATIVE_UNIT_OPTIONS,nativePreferencesShortcut}from'../../shared/native-display-units.js';
const reference=JSON.parse(await readFile(new URL('../fixtures/native-units-reference.json',import.meta.url)));
for(const c of reference.cases)test(`original Units formatting: ${c.name}`,()=>{for(const imperial of[false,true]){const expected=c.expected[imperial?'imperial':'metric'],labels=nativeRoleUsageLabels(c.input,c.input,{imperial});assert.deepEqual(labels,{time:expected.time,percent:expected.percent,length:expected.length,weight:expected.weight});assert.equal(nativeUsageDistance(c.input.distanceMm,{imperial}),expected.distance);assert.deepEqual(nativeSummaryMaterialLabels(c.input,{imperial}),{length:expected.summaryLength,weight:expected.summaryWeight});}});
test('native role imperial conversion quirk remains isolated from once-converted Summary weight',()=>{const input={seconds:1,totalSeconds:10,filamentMeters:1,filamentMm:1000,filamentGrams:28.34952};assert.equal(nativeRoleUsageLabels(input,input,{imperial:true}).weight,'0.04 oz');assert.equal(nativeSummaryMaterialLabels(input,{imperial:true}).weight,'1.00 oz');});
test('Units preference defaults to native metric, persists exact native string values, and rejects malformed storage',()=>{let raw=null;const storage={getItem(key){assert.equal(key,NATIVE_UNITS_STORAGE_KEY);return raw;},setItem(key,value){assert.equal(key,NATIVE_UNITS_STORAGE_KEY);raw=value;}};assert.deepEqual(readNativeDisplayPreferences(storage),{version:1,use_inches:'0'});assert.deepEqual(saveNativeDisplayPreferences(storage,{version:1,use_inches:'1',unrelated:'discard'}),{version:1,use_inches:'1'});assert.equal(readNativeDisplayPreferences(storage).use_inches,'1');for(const invalid of ['bad','null','{"version":1,"use_inches":true}','{"version":2,"use_inches":"1"}']){raw=invalid;assert.equal(readNativeDisplayPreferences(storage).use_inches,'0');}assert.throws(()=>saveNativeDisplayPreferences(storage,{version:1,use_inches:'yes'}));assert.deepEqual(NATIVE_UNIT_OPTIONS.map(row=>row.label),['Metric (mm, g)','Imperial (in, oz)']);});
test('storage failure is surfaced on save without changing native default read behavior',()=>{const storage={getItem(){throw Error('disabled');},setItem(){throw Error('full');}};assert.equal(readNativeDisplayPreferences(storage).use_inches,'0');assert.throws(()=>saveNativeDisplayPreferences(storage,{version:1,use_inches:'1'}),/full/);});
test('source platform Preferences shortcut respects text input/modal and composition guards',()=>{const mac={key:',',metaKey:true},win={key:'P',ctrlKey:true};assert.equal(nativePreferencesShortcut(mac,{platform:'MacIntel'}),true);assert.equal(nativePreferencesShortcut(win,{platform:'Win32'}),true);assert.equal(nativePreferencesShortcut(win,{platform:'MacIntel'}),false);assert.equal(nativePreferencesShortcut(mac,{platform:'Linux'}),false);for(const guard of[{modal:true},{editing:true}])assert.equal(nativePreferencesShortcut(mac,{platform:'MacIntel',...guard}),false);for(const field of['defaultPrevented','isComposing','altKey','shiftKey','repeat'])assert.equal(nativePreferencesShortcut({...mac,[field]:true},{platform:'MacIntel'}),false);});
test('original formatting reference retains pinned commit and source hash',async()=>{const cpp=await readFile(new URL('../fixtures/native-units-reference.cpp',import.meta.url));assert.equal(createHash('sha256').update(cpp).digest('hex'),reference.referenceSha256);assert.equal(reference.commit,'8500fcdccaa10b5099ac20d252af3a7c560046f1');assert.match(reference.sourceSha256['src/slic3r/GUI/Preferences.cpp'],/^[a-f0-9]{64}$/);});

test('native fixed decimals match printf for exact and false half ties, signed zero, subnormals and large values',()=>{for(const row of reference.fixedCases)assert.equal(nativeFixed(row.value,row.digits),row.expected,`${Object.is(row.value,-0)?'-0':row.value}, ${row.digits}`);});
