import test from 'node:test';import assert from 'node:assert/strict';
import {compatibilityMetadata,listNativeCompatiblePresets,nativeCompatibilitySources} from '../../server/native-compatibility.js';
const metadata=(id,type,config={})=>compatibilityMetadata({id,type,name:id,vendor:'Fixture',config});
function fixture(){const candidates=[{id:'process',type:'process',metadata:metadata('process','process'),summary:{id:'process',name:'process'}},{id:'filament',type:'filament',metadata:metadata('filament','filament'),summary:{id:'filament',name:'filament',type:'PLA'}}];return{compatibilityCandidates:()=>structuredClone(candidates),getPresetSource:(id,type)=>({name:id,chain:[{name:id,type}],metadata:metadata(id,type)}),getPreset:()=>({name:'printer'}),list:()=>({printers:[{id:'printer'}],defaults:{printerId:'printer'},warnings:[],limitations:['Native compatibility expressions are not evaluated.']})};}
const run=async request=>request.operation==='filament-library-exclusions'?{exclusions:{filament:['Excluded']}}:{compatibility:request.candidates.map(item=>({id:item.id,compatible:true,diagnostics:[]}))};
test('compatibility metadata retains explicit lists and conditions while only the explicit leaf alias is sent to native naming',()=>{const value=compatibilityMetadata({id:'id',type:'process',name:'Fine @Printer',vendor:'V',config:{alias:'Inherited alias',compatible_printers:['P'],compatible_printers_condition:'false'},leaf:{}});assert.equal(value.alias,'');assert.deepEqual(value.compatible_printers,['P']);assert.equal(value.compatible_printers_condition,'false');assert.throws(()=>metadata('id','process',{compatible_printers:[3]}),/Invalid/);assert.throws(()=>metadata('id','process',{compatible_printers_condition:'x'.repeat(16385)}),/Invalid/);});
test('listing selects active process for filament evaluation and carries native library exclusions',async()=>{const calls=[],result=await listNativeCompatiblePresets({catalog:fixture(),run:async request=>{calls.push(request);return run(request);}});assert.equal(result.defaults.processId,'process');assert.equal(result.defaults.filamentId,'filament');assert.deepEqual(result.limitations,[]);assert.equal(calls[2].process.name,'process');assert.deepEqual(calls[2].candidates[0].excludedFrom,['Excluded']);const source=await nativeCompatibilitySources(fixture(),run);assert.deepEqual(source.source('filament','filament').metadata.excludedFrom,['Excluded']);});
test('listing does not fall back on helper failure, mismatched result IDs, or cancellation',async()=>{const catalog=fixture();await assert.rejects(listNativeCompatiblePresets({catalog,run:async()=>{throw new Error('unavailable');}}),/unavailable/);await assert.rejects(listNativeCompatiblePresets({catalog,run:async request=>request.operation==='filament-library-exclusions'?run(request):{compatibility:[{id:'wrong',compatible:true,diagnostics:[]}]}}),/does not match/);const controller=new AbortController();controller.abort();await assert.rejects(listNativeCompatiblePresets({catalog,run,signal:controller.signal}),{name:'AbortError'});});
test('an incompatible selected process is explicit and native parser warnings retain original acceptance',async()=>{await assert.rejects(listNativeCompatiblePresets({catalog:fixture(),run,processId:'other'}),/incompatible/);const result=await listNativeCompatiblePresets({catalog:fixture(),run:async request=>request.operation==='filament-library-exclusions'?run(request):{compatibility:request.candidates.map(item=>({id:item.id,compatible:true,diagnostics:['Parse failed']}))}});assert.equal(result.processes.length,1);assert.match(result.warnings[0],/expression error in process; OrcaSlicer treats that expression as compatible/);});
test('all catalog batches share one deadline rather than resetting the timeout per helper',async()=>{
 const calls=[],catalog=fixture();await listNativeCompatiblePresets({catalog,run:async(request,options)=>{calls.push(options.timeoutMs);await new Promise(resolve=>setTimeout(resolve,15));return run(request);}});assert.equal(calls.length,3);assert.ok(calls[0]>calls[1]);assert.ok(calls[1]>calls[2]);
});
