import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{decodeFacet}from'../../shared/facet-codec.js';import{nativePlateExtrudersFromDescriptor,nativePlateExtruderDescriptor,nativePlateExtruders}from'../../shared/native-plate-extruders.js';
const reference=JSON.parse(await readFile(new URL('../fixtures/native-plate-extruders-reference.json',import.meta.url)));
function descriptor(value){const copy=structuredClone(value);for(const object of copy.objects)for(const volume of object.volumes){const states=new Set(),visit=node=>Object.hasOwn(node,'state')?(node.state&&states.add(node.state)):node.children.forEach(visit);for(const code of Object.values(volume.painting))visit(decodeFacet(code).tree);volume.painted=[...states];}return copy;}
for(const fixture of reference.cases)test(`original native all-plate extruder collection: ${fixture.name}`,()=>assert.deepEqual(nativePlateExtrudersFromDescriptor(descriptor(fixture.input)),fixture.expected.extruders));
const global=reference.cases[0].input.global,settings={...global,filament_colour:['#FF0000','#00FF00','#0000FF','#FFFFFF']};
const mesh=(id,plateId,slot,native={})=>({id,plateId,name:id,filamentSlot:slot,native,positions:[0,0,0,10,0,0,0,10,0]});
test('project adapter matches native exported part roles, object-level ranges and explicit filament slots',()=>{const project={activePlateId:'a',plates:[{id:'a',layerEvents:{items:[{type:'ToolChange',extruder:4}]}}],objects:[mesh('normal','a',2,{groupId:'group',objectSettings:{extruder:'1'},partSettings:{extruder:'3'},layerConfigRanges:[{minZ:0,maxZ:1,settings:{extruder:'3'}}]}),mesh('negative','a',4,{groupId:'group',partType:'negative_part',objectSettings:{extruder:'1'}})]};project.objects[0].painting={version:1,color:{0:'4'}};const result=nativePlateExtruderDescriptor(project,settings);assert.equal(result.objects[0].volumes[0].config.extruder,2);assert.deepEqual(nativePlateExtrudersFromDescriptor(result),[1,2,3,4]);});
test('shared families retain original first-instance containment across active-plate requests',()=>{const first=mesh('first','a',2,{groupId:'ga',instanceFamily:'same'}),second=mesh('second','b',2,{groupId:'gb',instanceFamily:'same'}),full={activePlateId:'a',plates:[{id:'a'},{id:'b'}],objects:[first,second]},partB={...full,activePlateId:'b',objects:[second],plates:[{id:'b'}]};assert.deepEqual(nativePlateExtruders(full,settings),[2]);assert.deepEqual(nativePlateExtruders(partB,settings,{fullProject:full}),[]);assert.deepEqual(nativePlateExtruders(partB,settings),[2]);});
test('unresolved or malformed global settings cannot silently produce guessed collection',()=>{const project={activePlateId:'a',plates:[{id:'a'}],objects:[mesh('one','a',1)]};assert.throws(()=>nativePlateExtruders(project,{filament_colour:['#FF0000']}),/resolved support_interface_filament/);assert.throws(()=>nativePlateExtruders(project,{...settings,raft_layers:'bad'}),/raft_layers/);});
