import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {importNativeGeometry} from '../../shared/native-geometry-import.js';
import {geometryProjectContext} from '../../shared/native-project-load.js';
import {emptyProject,validateProject} from '../../shared/project.js';
import {importNative3MF,exportNative3MF} from '../../shared/native-project.js';
import {assertInstanceFamilies} from '../../shared/native-instances.js';
import {fixture} from '../fixtures/native-instance-project.js';
import {createMesh,sceneBounds} from '../../shared/geometry.js';
const bed={width:250,depth:210,height:220};
function current(){return{...emptyProject(),ids:{printerId:'p',processId:'q',filamentId:'f'},overrides:{layer_height:'0.25'},filamentIds:['f'],projectOverrides:{filament_colour:['#123456'],flush_volumes_matrix:['0'],flush_volumes_vector:['141','142']}};}
const cube=()=>importNative3MF(readFileSync(new URL('../fixtures/native-gui-cube-2.4.2.3mf',import.meta.url)));
const apply=(a,b)=>{let id=0;return importNativeGeometry(a,b,bed,{idFactory:()=>String(++id)});};
test('geometry import preserves linked instances, exact meshes, painting and per-layer data while dropping object and part overrides',()=>{
 const source=fixture({mirror:true});for(const o of source.objects){o.native.objectSettings={extruder:'1',wall_loops:'9'};o.native.partSettings={extruder:'1',sparse_infill_density:'70%'};o.native.layerConfigRanges=[{minZ:1,maxZ:3,settings:{layer_height:'0.12'}}];o.native.layerHeightProfile=[0,.2,1,.2,10,.2];}const destination=current(),before=structuredClone({source,destination}),out=apply(destination,source);
 assert.equal(out.objects.length,4);assert.equal(new Set(out.objects.map(o=>o.native.groupId)).size,2);assert.equal(new Set(out.objects.map(o=>o.native.instanceFamily)).size,1);assert.notEqual(out.objects[0].native.instanceFamily,'family');assertInstanceFamilies(out.objects);
 for(let i=0;i<4;i++){const got=out.objects[i],expected=source.objects[i];assert.deepEqual(got.positions,expected.positions);assert.deepEqual(got.native.meshSource,expected.native.meshSource);assert.deepEqual(got.painting,expected.painting);assert.deepEqual(got.native.layerConfigRanges,expected.native.layerConfigRanges);assert.deepEqual(got.native.layerHeightProfile,expected.native.layerHeightProfile);assert.deepEqual(got.native.objectSettings,{extruder:'1'});assert.deepEqual(got.native.partSettings,{extruder:'1'});}
 assert.deepEqual(out.overrides,{layer_height:'0.25'});assert.deepEqual(out.projectOverrides,destination.projectOverrides);assert.equal(out.nativeSettings,undefined);assert.deepEqual({source,destination},before);
});
test('all source plates merge onto the active plate using native global coordinates without importing plate events',()=>{
 const source=cube(),first=source.objects[0];source.plates=[{id:'plate-1',name:'First',native:{origin:[0,0,0]}},{id:'plate-2',name:'Second',native:{origin:[300,-252,0]},layerEvents:{mode:'SingleExtruder',items:[]}}];source.objects=[first,{...structuredClone(first),id:'other',plateId:'plate-2',native:{...structuredClone(first.native),groupId:'second',instanceFamily:undefined}}];const out=apply(current(),source);assert.deepEqual(out.plates,current().plates);assert.ok(out.objects.every(o=>o.plateId==='plate-1'));assert.equal(out.objects[1].position[0]-out.objects[0].position[0],300);assert.equal(out.objects[1].position[1]-out.objects[0].position[1],-252);assert.deepEqual(sceneBounds(out.objects).center.slice(0,2),[125,105]);
});
test('native role order and model-only placement keep outside modifiers from moving the solid off center',()=>{
 const source=cube(),body=source.objects[0],roles=['support_enforcer','modifier_part','support_blocker','negative_part'];source.objects=[...roles.map((role,i)=>({...structuredClone(body),id:'role'+i,position:[500,500,-50],native:{...structuredClone(body.native),partType:role}})),body];const out=apply(current(),source);assert.deepEqual(out.objects.map(o=>o.native.partType),['normal_part','negative_part','modifier_part','support_blocker','support_enforcer']);assert.deepEqual(sceneBounds([out.objects[0]]).center,[125,105,10]);assert.equal(out.objects[1].position[2],-50);
});
test('geometry material and painted requirements grow current slots without adopting imported materials or replacing existing purge values',()=>{
 const source=cube();source.objects[0].filamentSlot=3;source.objects[0].native.partSettings={extruder:'3',wall_loops:'8'};source.objects[0].painting={version:1,color:{0:'0C'}};const out=apply(current(),source);assert.deepEqual(out.filamentIds,['f','f','f']);assert.deepEqual(out.projectOverrides.filament_colour,['#123456','#00C1AE','#F4E2C1']);assert.deepEqual(out.projectOverrides.flush_volumes_vector.slice(0,2),['141','142']);assert.equal(out.projectOverrides.flush_volumes_matrix.length,9);assert.equal(out.objects[0].filamentSlot,3);assert.deepEqual(out.objects[0].native.partSettings,{extruder:'3'});
});
test('painting alone allocates its assigned material while imported extruder zero becomes the native default',()=>{const source=cube();source.objects[0].native.objectSettings={extruder:'0'};source.objects[0].painting={version:1,color:{0:'0C'}};const out=apply(current(),source);assert.equal(out.filamentIds.length,3);assert.deepEqual(out.objects[0].native.objectSettings,{extruder:'1'});});
test('repeated imports allocate independent families and preserve existing geometry and native processed cut metadata',()=>{const source=fixture();for(const o of source.objects)o.native.cutId={id:'42',checkSum:'4',connectorsCount:'0'};const first=importNativeGeometry(current(),source,bed),second=importNativeGeometry(first,source,bed);assert.equal(second.objects.length,8);assert.equal(new Set(second.objects.map(o=>o.id)).size,8);assert.equal(new Set(second.objects.map(o=>o.native.instanceFamily)).size,2);assert.deepEqual(second.objects.slice(0,4),first.objects);assert.ok(second.objects.every(o=>o.native.cutId.id==='42'));assertInstanceFamilies(second.objects);});
test('locked plate, invalid roles, invalid slots, broken families and exhausted identities reject atomically',()=>{const destination=current(),original=structuredClone(destination),source=cube();assert.throws(()=>apply({...destination,plates:[{...destination.plates[0],locked:true}]},source),/locked/);const bad=structuredClone(source);bad.objects[0].native.partType='unknown';assert.throws(()=>apply(destination,bad),/part type/);bad.objects[0].native.partType='negative_part';assert.throws(()=>apply(destination,bad),/normal part/);bad.objects[0].native.partType='normal_part';bad.objects[0].filamentSlot=65;assert.throws(()=>apply(destination,bad),/material slot/);const linked=fixture();linked.objects[2].name='Different';assert.throws(()=>apply(destination,linked),/instance|diverge|differ|share/i);assert.throws(()=>importNativeGeometry(destination,source,bed,{idFactory:()=>1}),/distinct/);assert.deepEqual(destination,original);});
test('geometry-only Open retains material colors, purge tables and native preset context by value',()=>{const source={...current(),nativePresetNames:{printer:'P'},nativeContext:{version:'2.4.2'},nativeUnsupportedSettings:['unknown']},out=geometryProjectContext(source,emptyProject());for(const key of ['projectOverrides','nativePresetNames','nativeContext','nativeUnsupportedSettings']){assert.deepEqual(out[key],source[key]);assert.notEqual(out[key],source[key]);}out.projectOverrides.filament_colour[0]='#FFFFFF';assert.equal(source.projectOverrides.filament_colour[0],'#123456');});
test('geometry export retains actual linked model references and native painting after import',()=>{const source=fixture({mirror:true}),destination={...cube(),objects:[],selectedId:null,selectedIds:[]},out=apply(destination,source),round=importNative3MF(exportNative3MF(out));assert.equal(round.objects.length,4);assert.equal(new Set(round.objects.map(o=>o.native.instanceFamily)).size,1);assertInstanceFamilies(round.objects);for(const o of round.objects)assert.deepEqual(o.painting.color,{0:'4'});validateProject(round);});

test('geometry-only placement matches ten compiled native first-instance auto-drop and double-precision centering cases',async()=>{
 const {BoxGeometry,Matrix4,Vector3}=await import('three'),reference=JSON.parse(readFileSync(new URL('../fixtures/native-geometry-import-reference.json',import.meta.url)));
 for(const row of reference.cases){const source={...emptyProject(),objects:[]};for(const [g,group]of row.groups.entries()){const geo=new BoxGeometry(...group.max.map((v,i)=>v-group.min[i])).toNonIndexed(),center=group.min.map((v,i)=>(v+group.max[i])/2),vertices=Array.from(geo.attributes.position.array).map((v,i)=>v+center[i%3]),triangles=vertices.map((_,i)=>i).slice(0,vertices.length/3);for(const [n,offset]of group.offsets.entries()){const build=new Matrix4().makeTranslation(...offset),positions=[];for(let i=0;i<vertices.length;i+=3)positions.push(...new Vector3(...vertices.slice(i,i+3)).applyMatrix4(build).toArray());source.objects.push(createMesh({id:`${g}-${n}`,name:`Group ${g}`,positions,plateId:'plate-1',native:{groupId:`${g}-${n}`,instanceFamily:`family-${g}`,instanceAutoDrop:group.autoDrop[n],meshSource:{version:1,vertices,triangles,component:new Matrix4().toArray(),build:build.toArray()}}}));}geo.dispose();}
 const out=importNativeGeometry(current(),source,{width:row.center[0]*2,depth:row.center[1]*2,height:220});let at=0;for(const[g,group]of row.groups.entries())for(const[n,offset]of group.offsets.entries()){const object=out.objects[at++];for(let a=0;a<3;a++)assert.ok(Math.abs(object.position[a]+offset[a]-row.placedOffsets[g][n][a])<1e-9,`${row.name} group${g} instance${n} axis${a}`);}}
});
test('geometry placement reference has reproducible original-source and generator provenance',async()=>{const {createHash}=await import('node:crypto'),r=JSON.parse(readFileSync(new URL('../fixtures/native-geometry-import-reference.json',import.meta.url)));assert.equal(r.commit,'8500fcdccaa10b5099ac20d252af3a7c560046f1');assert.equal(r.cases.length,10);for(const[key,path]of [['generatorSha256','../../scripts/reference/build-geometry-import-reference.py'],['referenceSha256','../fixtures/native-geometry-import-reference.cpp']])assert.equal(createHash('sha256').update(readFileSync(new URL(path,import.meta.url))).digest('hex'),r[key]);});

test('geometry-only native text and SVG retain their regeneration frames and embedded vector source through export',async()=>{const {Matrix4,Vector3}=await import('three'),{meshPointMatrix}=await import('../../shared/brim-ears.js');for(const kind of ['text','svg']){const source=importNative3MF(readFileSync(new URL('../fixtures/native-text-planar-2.4.2.3mf',import.meta.url))),part=source.objects.find(o=>o.native.textConfiguration);if(kind==='svg'){delete part.native.textConfiguration;part.native.embossShape.svg={name:'shape.svg',source:'<svg xmlns="http://www.w3.org/2000/svg"><path d="M0 0L10 0L10 10Z"/></svg>'};}const out=apply({...cube(),objects:[],selectedId:null,selectedIds:[]},source),expected=out.objects.find(o=>o.native.embossShape),round=importNative3MF(exportNative3MF(out)),actual=round.objects.find(o=>o.native.embossShape);assert.deepEqual(actual.native.textConfiguration,expected.native.textConfiguration);assert.deepEqual(actual.native.embossShape.svg,expected.native.embossShape.svg);const frame=o=>new Vector3(0,0,0).applyMatrix4(meshPointMatrix(o).multiply(new Matrix4().fromArray(o.native.embossShape.frame))).toArray();frame(actual).forEach((v,i)=>assert.ok(Math.abs(v-frame(expected)[i])<2e-5));}});
test('geometry-only import retains printable flags, brim attachment positions and processed cut identifiers across export',async()=>{const {worldBrimEars}=await import('../../shared/brim-ears.js'),source=cube();source.objects[0].printable=false;source.objects[0].brimEars=[{position:[0,0,0],radius:3}];source.objects[0].native.cutId={id:'18446744073709551615',checkSum:'9',connectorsCount:'0'};const out=apply({...cube(),objects:[],selectedId:null,selectedIds:[]},source),round=importNative3MF(exportNative3MF(out));assert.equal(round.objects[0].printable,false);assert.deepEqual(round.objects[0].native.cutId,source.objects[0].native.cutId);assert.deepEqual(worldBrimEars(round.objects[0]),worldBrimEars(out.objects[0]));});
