import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm,stat} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {createNativeEmbossWorker,normalizeEmbossRequest,validateEmbossResponse,EMBOSS_WORKER_COMMIT} from '../../server/native-emboss-worker.js';
const base={text:'A & B',lineHeight:13,depth:1},identity=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];const mesh={vertices:[[0,0,0],[1,0,0],[0,1,0]],triangles:[[0,1,2]]};
async function fixture(t,options={}){const directory=await mkdtemp(path.join(tmpdir(),'emboss-worker-test-'));t.after(()=>rm(directory,{recursive:true,force:true}));const font=path.join(directory,'trusted.ttf'),script=path.join(directory,'fake.mjs'),ready=path.join(directory,'ready');await writeFile(font,Buffer.alloc(20));await writeFile(script,`import {writeFileSync} from 'node:fs';let input='';for await(const chunk of process.stdin)input+=chunk;const request=JSON.parse(input);if(request.text==='wait'){setInterval(()=>{},1000);process.on('SIGTERM',()=>{});writeFileSync(process.argv[2],'ready');}else if(request.text==='output'){process.stdout.write('x'.repeat(100000));}else if(request.text==='stderr'){process.stderr.write('x'.repeat(100000));setInterval(()=>{},1000);}else if(request.text==='invalid'){console.log('{}');}else if(request.text==='fail'){console.error('fixture failure');process.exitCode=3;}else {console.log(JSON.stringify({nativeVersion:'2.4.2',commit:'${EMBOSS_WORKER_COMMIT}',scale:.00001,healed:true,vertices:[[0,0,0],[1,0,0],[0,1,0]],triangles:[[0,1,2]]}));}`);const ids=[];const worker=createNativeEmbossWorker({binary:process.execPath,workerArgs:[script,ready],resolveFont:async id=>{ids.push(id);return{filename:font};},...options});t.after(()=>worker.close());return{worker,ids,ready};}
const tick=()=>new Promise(resolve=>setTimeout(resolve,20));
test('native request validates typed font settings, matrices, geometry totals and explicit unsupported features',()=>{assert.deepEqual(normalizeEmbossRequest(base),{...base,outside:true,useSurface:false,perGlyph:false,horizontal:'center',vertical:'middle'});assert.deepEqual(normalizeEmbossRequest({...base,useSurface:true,transform:identity,sources:[{...mesh,transform:identity}]}).sources[0].triangles,mesh.triangles);for(const change of [{lineHeight:NaN},{text:'\0'},{depth:0},{file:'/etc/passwd'},{charGap:.5},{boldness:500001},{horizontal:'justify'},{collection:-1},{perGlyph:true},{transform:identity},{outside:'true'}])assert.throws(()=>normalizeEmbossRequest({...base,...change}));for(const source of [{...mesh,transform:[...identity.slice(0,15),0]},{...mesh,triangles:[[0,1,3]],transform:identity},{...mesh,triangles:[[0,1,1]],transform:identity}])assert.throws(()=>normalizeEmbossRequest({...base,useSurface:true,transform:identity,sources:[source]}));});
test('native response requires pinned engine identity and bounded valid indices',()=>{const result={...mesh,nativeVersion:'2.4.2',commit:EMBOSS_WORKER_COMMIT,scale:1e-5,healed:true};assert.deepEqual(validateEmbossResponse(result),result);for(const change of [{nativeVersion:'2.4.3'},{commit:'unknown'},{scale:0},{healed:1},{triangles:[[0,4,1]]},{vertices:[[NaN,0,0]]}])assert.throws(()=>validateEmbossResponse({...result,...change}));});
test('wrapper uses only opaque font ID with trusted resolver and returns parsed mesh',async t=>{const{worker,ids}=await fixture(t);const result=await worker.generate(base,{fontId:'bundled-font'});assert.deepEqual(ids,['bundled-font']);assert.deepEqual(result.triangles,mesh.triangles);assert.deepEqual(worker.state,{active:0,queued:0,closed:false});await assert.rejects(worker.generate({...base,path:'/etc/passwd'},{fontId:'bundled-font'}),/Unsupported/);});
test('worker errors and malformed output cannot become successful geometry',async t=>{const{worker}=await fixture(t);await assert.rejects(worker.generate({...base,text:'fail'},{fontId:'x'}),/fixture failure/);await assert.rejects(worker.generate({...base,text:'invalid'},{fontId:'x'}),/version/);assert.equal(worker.state.active,0);});
test('active cancellation kills uncooperative child, clears queue slot and subsequent job runs',async t=>{const{worker,ready}=await fixture(t,{timeoutMs:5000});const controller=new AbortController();const pending=worker.generate({...base,text:'wait'},{fontId:'x',signal:controller.signal});for(let i=0;i<100;i++){try{await stat(ready);break;}catch{await tick();}}await stat(ready);const start=Date.now();controller.abort();await assert.rejects(pending,{name:'AbortError'});assert.ok(Date.now()-start>=200,'SIGKILL escalation waits for uncooperative child');assert.equal(worker.state.active,0);assert.equal((await worker.generate(base,{fontId:'x'})).triangles.length,1);});
test('queued cancellation never resolves a font or spawns a child, and queue bounds reject overload',async t=>{const{worker,ids}=await fixture(t,{maxQueued:1,timeoutMs:5000});const firstControl=new AbortController(),queuedControl=new AbortController();const first=worker.generate({...base,text:'wait'},{fontId:'first',signal:firstControl.signal});const queued=worker.generate(base,{fontId:'queued',signal:queuedControl.signal});await assert.rejects(worker.generate(base,{fontId:'overflow'}),/queue is full/);queuedControl.abort();await assert.rejects(queued,{name:'AbortError'});assert.deepEqual(ids,['first']);firstControl.abort();await assert.rejects(first,{name:'AbortError'});});
test('wall deadline includes pending font resolution and queued wait, without late spawn',async t=>{let release;const resolver=new Promise(resolve=>release=resolve);const{worker}=await fixture(t,{timeoutMs:50,resolveFont:()=>resolver});const a=worker.generate(base,{fontId:'a'}),b=worker.generate(base,{fontId:'b'});await Promise.all([assert.rejects(a,/deadline/),assert.rejects(b,/deadline/)]);release({filename:'/does-not-exist'});await tick();assert.deepEqual(worker.state,{active:0,queued:0,closed:false});});
test('stdout and stderr overflow stop child and preserve bounded diagnostics',async t=>{const{worker}=await fixture(t,{maxOutputBytes:1000,maxStderrBytes:1000});await assert.rejects(worker.generate({...base,text:'output'},{fontId:'x'}),/output exceeds/);await assert.rejects(worker.generate({...base,text:'stderr'},{fontId:'x'}),/diagnostics exceed/);assert.equal(worker.state.active,0);});
test('closing cancels active and queued work and rejects future requests',async t=>{const{worker}=await fixture(t,{timeoutMs:5000});const a=worker.generate({...base,text:'wait'},{fontId:'a'}),b=worker.generate(base,{fontId:'b'});worker.close();await Promise.all([assert.rejects(a,{name:'AbortError'}),assert.rejects(b,{name:'AbortError'})]);await assert.rejects(worker.generate(base,{fontId:'c'}),/closed/);});
