import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createNativeGcodeWorker} from '../../server/native-gcode-worker.js';
const binary=path.resolve('tests/fixtures/fake-gcode-worker.mjs');
async function setup(t,options={}){const tempRoot=await mkdtemp(path.join(tmpdir(),'orca-gcode-test-')),worker=createNativeGcodeWorker({binary,tempRoot,...options});t.after(async()=>{await worker.shutdown();assert.deepEqual(await readdir(tempRoot),[]);await rm(tempRoot,{recursive:true,force:true});});return worker;}
test('worker validates native identity and output while every successful/failed request cleans its files',async t=>{const worker=await setup(t);const identity=await worker.identity();assert.equal(identity.metadata.version,'2.4.2');assert.equal((await worker.process(Buffer.from('G1 X10'))).vertexCount,2);await assert.rejects(worker.process(Buffer.from('FAIL')),/Fixture processor failure/);await assert.rejects(worker.process(Buffer.from('INVALID')),/non-finite vertex/);});
test('worker enforces input, result and console byte limits',async t=>{const worker=await setup(t,{maxInputBytes:100,maxOutputBytes:1000,timeoutMs:5000});await assert.rejects(worker.process(Buffer.alloc(101)),/input exceeds/);await assert.rejects(worker.process(Buffer.from('LARGE')),/output size limit/);await assert.rejects(worker.process(Buffer.from('NOISY')),/console output/);});
test('worker retains its short deadline for stalled native code independently of byte-limit checks',async t=>{const worker=await setup(t,{timeoutMs:150});await worker.identity();const began=Date.now();await assert.rejects(worker.process(Buffer.from('WAIT')),/timed out/);assert.ok(Date.now()-began<1000,'the 150 ms operation deadline must abort stalled work promptly');});
test('worker cancels active and queued requests, enforces queue capacity and drains on shutdown',async t=>{const worker=await setup(t,{maxActive:1,maxQueued:1});const activeAbort=new AbortController(),queuedAbort=new AbortController();const first=worker.process(Buffer.from('WAIT'),{signal:activeAbort.signal}),firstCheck=assert.rejects(first,/cancelled/);const second=worker.process(Buffer.from('WAIT'),{signal:queuedAbort.signal}),secondCheck=assert.rejects(second,/cancelled/);await assert.rejects(worker.process(Buffer.from('WAIT')),error=>error.status===429);queuedAbort.abort();activeAbort.abort();await Promise.all([firstCheck,secondCheck]);assert.equal((await worker.process(Buffer.from('G1 X10'))).vertexCount,2);const pending=worker.process(Buffer.from('WAIT'));const rejected=assert.rejects(pending,/cancelled|shutting down/);await worker.shutdown();await rejected;await assert.rejects(worker.process(Buffer.from('G1')),/shutting down/);});

test('operation deadlines include queue wait rather than granting every queued job another full execution window',async t=>{const worker=await setup(t,{timeoutMs:300,maxActive:1,maxQueued:4});await worker.identity();const began=Date.now(),requests=Array.from({length:5},()=>assert.rejects(worker.process(Buffer.from('WAIT')),/timed out/));await Promise.all(requests);assert.ok(Date.now()-began<1000,'all queued requests should expire in one deadline, not five sequential windows');});
