import test from'node:test';import assert from'node:assert/strict';
import{prepareMultiPatternFixture,multiPatternRequest}from'../fixtures/pa-pattern-multiplate.js';
import{createCalibrationPlan}from'../../shared/calibration.js';import{paPatternPlanForPlate}from'../../shared/pa-pattern-calibration.js';import{patternLayerEvents}from'../../shared/pa-pattern-gcode.js';import{importNative3MF}from'../../shared/native-project.js';import{meshBounds}from'../../shared/geometry.js';import{createNativeProjectService}from'../../server/native-projects.js';import{assertGeneratedPatternProjectUnchanged,assertGeneratedPatternEdit}from'../../shared/generated-pattern-binding.js';
const fixture=await prepareMultiPatternFixture();
test('PA batch adds plates without splitting source speed/acceleration combinations or overlapping full footprints',()=>{
 const {plan}=fixture;assert.deepEqual(plan.patternPlates.map(p=>p.patternCount),[6,2]);assert.deepEqual(plan.paPatterns.map(p=>[p.speed,p.acceleration]),[80,120,160,200].map(speed=>[speed,1000]).concat([80,120,160,200].map(speed=>[speed,2000])));
 for(const plate of plan.patternPlates){const selected=paPatternPlanForPlate(plan,plate.id);assert.equal(selected.paPatterns.length,plate.patternCount);assert.equal(selected.request,plan.request);const layers=patternLayerEvents(selected).items;assert.equal(layers.length,4);for(const layer of layers)assert.equal((layer.extra.match(/ORCA_WEB_PA_PATTERN_START /g)||[]).length,plate.patternCount);for(const [i,p]of selected.paPatterns.entries()){assert.ok(p.bounds.min[0]>plan.patternBed.min[0]&&p.bounds.max[0]<plan.patternBed.max[0]);assert.ok(p.bounds.min[1]>plan.patternBed.min[1]&&p.bounds.max[1]<plan.patternBed.max[1]);for(const q of selected.paPatterns.slice(0,i))assert.ok(p.bounds.min[0]>=q.bounds.max[0]||p.bounds.max[0]<=q.bounds.min[0]||p.bounds.min[1]>=q.bounds.max[1]||p.bounds.max[1]<=q.bounds.min[1]);}}
 assert.throws(()=>patternLayerEvents(plan),/Select one/);assert.throws(()=>paPatternPlanForPlate(plan,'plate-99'),/existing/);assert.throws(()=>createCalibrationPlan({...multiPatternRequest,end:2},fixture.selection),/does not fit/);
});
test('complete and selected archives retain four commands per plate and local handle positions',()=>{
 const full=importNative3MF(fixture.prepared.nativeProject.bytes);assert.equal(full.plates.length,2);assert.equal(full.objects.length,8);
 for(const plate of fixture.plan.patternPlates){const cached=fixture.prepared.nativeProject.plateProjects[plate.id],selected=importNative3MF(cached.bytes);assert.equal(selected.plates.length,1);assert.equal(selected.objects.length,plate.patternCount);assert.equal(selected.plates[0].layerEvents.items.length,4);assert.equal(cached.summary.plateId,plate.id);const matching=full.objects.filter(object=>object.plateId===plate.id);for(let i=0;i<selected.objects.length;i++)assert.deepEqual(meshBounds(selected.objects[i]),meshBounds(matching[i]));}
 assert.ok(fixture.prepared.plates.every(plate=>!plate.layerEvents));assert.ok(!('plateProjects'in fixture.prepared));
});
test('imported complete multi-plate pattern permits plate selection but rejects edits anywhere in the bound scene',async()=>{
 const service=createNativeProjectService({catalog:fixture.catalog}),base=(await service.importArchive(fixture.prepared.nativeProject.bytes)).project;base.useEmbeddedSettings=true;
 for(const plate of base.plates){const next={...base,activePlateId:plate.id,selectedId:null};assert.equal(assertGeneratedPatternEdit(base,next),true);assert.equal(assertGeneratedPatternProjectUnchanged(next,{plateId:base.plates[0].id}),true);const selected=await service.prepare({project:next,plateId:plate.id,useEmbeddedSettings:true});assert.equal(selected.summary.plateCount,1);assert.equal(importNative3MF(selected.bytes).plates[0].layerEvents.items.length,4);}
 for(const change of[p=>p.objects.at(-1).position[0]++,p=>p.objects[0].plateId='plate-2',p=>p.plates.reverse(),p=>p.plates[1].layerEvents.items[1].extra+='\nG1 X0',p=>p.nativeSettings.outer_wall_speed='999',p=>p.activePlateId='missing']){const next=structuredClone(base);change(next);assert.throws(()=>assertGeneratedPatternEdit(base,next),/regenerate/);await assert.rejects(service.prepare({project:next,plateId:'plate-1',useEmbeddedSettings:true}),/regenerate|active plate/i);}
 assert.throws(()=>assertGeneratedPatternProjectUnchanged(base,{plateId:'missing'}),/regenerate/);
});
