import test from'node:test';import assert from'node:assert/strict';
import{createMesh}from'../../shared/geometry.js';import{previewPaintFill,paintMesh}from'../../shared/facet-paint-tools.js';import{paintMeshContext,nearestPaintLeaf}from'../../shared/facet-graph.js';import{fillBoundarySegments,previewObjectFill}from'../../shared/paint-fill-preview.js';import{fillHoverColor}from'../../src/paint-fill-overlay.js';
const square=()=>createMesh({id:'part-a',positions:[0,0,0,4,0,0,0,4,0,4,0,0,4,4,0,0,4,0],painting:{version:1,supports:{0:'00443'},seam:{1:'4'}},native:{groupId:'group',partType:'normal_part'}});
const center=vertices=>[0,1,2].map(axis=>vertices.reduce((sum,point)=>sum+point[axis],0)/3);
function freeze(value){if(value&&typeof value==='object'){for(const next of Object.values(value))freeze(next);Object.freeze(value);}return value;}
const segments=positions=>Array.from({length:positions.length/6},(_,i)=>[positions.slice(i*6,i*6+3),positions.slice(i*6+3,i*6+6)]);
const perimeter=positions=>segments(positions).reduce((sum,[a,b])=>sum+Math.hypot(...a.map((v,i)=>v-b[i])),0);
const near=(actual,expected)=>assert.ok(Math.abs(actual-expected)<1e-7,`${actual} != ${expected}`);
test('smart-fill hover retains current leaf states while selecting exactly the committed original-facet footprint',()=>{
 const mesh=freeze(square()),snapshot=JSON.stringify(mesh),options={channel:'supports',tool:'fill',triangleIndex:0,point:[.5,.5,0],fillAngle:0},preview=previewPaintFill(mesh,options);assert.deepEqual(preview.map(f=>[f.original,f.state]),[[0,0],[0,0],[0,1],[0,1],[1,0]]);assert.deepEqual(preview[0].vertices,[[0,0,0],[2,0,0],[0,2,0]]);assert.equal(preview[4].original,1);const result=paintMesh(mesh,{...options,state:2});assert.deepEqual(result.mesh.painting.supports,{0:'8',1:'8'});assert.deepEqual(result.mesh.painting.seam,mesh.painting.seam);assert.equal(JSON.stringify(mesh),snapshot);const dry=paintMesh(mesh,{...options,state:2,previewOnly:true});assert.equal(dry.mesh,mesh);assert.equal(dry.report.changedFacets,0);assert.equal(preview.length,dry.facets.length);
});
test('bucket and pointer hover preserve existing state boundaries and agree with committed changes',()=>{
 const mesh=freeze(square()),before=JSON.stringify(mesh);
 for(const tool of['bucket','facet'])for(const point of[[.5,.5,0],[3,.5,0],[1,2,0]]){
  const options={tool,channel:'supports',triangleIndex:0,point,fillAngle:-1},preview=previewPaintFill(mesh,options),changed=paintMesh(mesh,{...options,state:2}).mesh,source=paintMeshContext(mesh,{channel:'supports',leaves:true}),after=paintMeshContext(changed,{channel:'supports',leaves:true});assert.ok(preview.length);assert.ok(preview.every(f=>f.state===preview[0].state));
  for(const leaf of source.facets){const point=center(leaf.vertices),selected=preview.some(f=>f.original===leaf.original&&JSON.stringify(f.vertices)===JSON.stringify(leaf.vertices)),newState=after.facets[nearestPaintLeaf(after.facets,leaf.original,point)].state;assert.equal(newState,selected?2:leaf.state);}
 }
 assert.equal(JSON.stringify(mesh),before);assert.equal(previewPaintFill(mesh,{tool:'facet',channel:'supports',triangleIndex:0,point:[.5,.5,0]}).length,1);assert.throws(()=>previewPaintFill(mesh,{tool:'circle',channel:'supports',triangleIndex:0}),/Only connected/);
});
test('unequal subdivided shared edges have no false contour and partial sharing retains only uncovered intervals',()=>{
 const full=previewPaintFill(square(),{tool:'fill',channel:'supports',triangleIndex:0,fillAngle:0}),boundary=fillBoundarySegments(full);near(perimeter(boundary),16);for(const [a,b]of segments(boundary))assert.ok(a[0]===0&&b[0]===0||a[0]===4&&b[0]===4||a[1]===0&&b[1]===0||a[1]===4&&b[1]===4,'only independent square boundary edges remain');
 // One coarse triangle on the left, one half-edge neighbor on the right.
 // The uncovered diagonal from (2,2) to (0,4) must remain a boundary.
 const facets=[{vertices:[[0,0,0],[4,0,0],[0,4,0]]},{vertices:[[4,0,0],[4,4,0],[2,2,0]]}],partial=segments(fillBoundarySegments(facets));assert.ok(partial.some(([a,b])=>a.every((v,i)=>Math.abs(v-[2,2,0][i])<1e-7)&&b.every((v,i)=>Math.abs(v-[0,4,0][i])<1e-7)));assert.ok(!partial.some(([a,b])=>a[0]+a[1]===4&&b[0]+b[1]===4&&Math.max(a[0],b[0])>2&&Math.min(a[0],b[0])<4));near(perimeter(partial.flat(2)),12+4*Math.SQRT2);
 const transformed=full.map(f=>({...f,vertices:f.vertices.map(([x,y,z])=>[10-2*y,20+3*x,4+z])})),world=fillBoundarySegments(transformed);near(perimeter(world),40);for(const [a,b]of segments(world))assert.ok(a[0]===2&&b[0]===2||a[0]===10&&b[0]===10||a[1]===20&&b[1]===20||a[1]===32&&b[1]===32);assert.ok(world.filter((_,i)=>i%3===2).every(z=>z===4));
});
test('clipping, overhang restriction and angle changes use the same selector constraints without metadata writes',()=>{
 const mesh=square(),options={tool:'fill',channel:'supports',triangleIndex:0,point:[.5,.5,0],fillAngle:0};assert.equal(previewPaintFill(mesh,{...options,overhangAngle:40}).length,0);assert.equal(previewPaintFill(mesh,{...options,clipPlane:{normal:[1,0,0],offset:3}}).length,0);
 const down={...mesh,rotation:[180,0,0]},point=[.5,3.5,0];assert.equal(previewPaintFill(down,{...options,point,overhangAngle:40}).length,5);
 const folded=createMesh({positions:[0,0,0,4,0,0,0,4,0,4,0,0,0,0,0,0,0,4]});assert.equal(previewPaintFill(folded,{...options,fillAngle:30}).length,1);assert.equal(previewPaintFill(folded,{...options,fillAngle:90}).length,2);
});
test('hover targets only the actual visible normal part in the selected native object',()=>{
 const a=square(),b={...square(),id:'part-b',position:[10,0,0]},other={...square(),id:'other',native:{groupId:'other'}},hidden={...square(),id:'hidden',visible:false},negative={...square(),id:'negative',native:{groupId:'group',partType:'negative_part'}},objects=freeze([a,b,other,hidden,negative]),before=JSON.stringify(objects),options={tool:'fill',channel:'supports',fillAngle:0};const preview=previewObjectFill(objects,'part-a',{id:'part-b',triangleIndex:0,point:[10.5,.5,0]},options);assert.equal(preview.objectId,'part-b');assert.ok(preview.facets.flatMap(f=>f.vertices).every(p=>p[0]>=10));for(const id of['other','hidden','negative','missing'])assert.equal(previewObjectFill(objects,'part-a',{id,triangleIndex:0,point:[0,0,0]},options),null);assert.equal(JSON.stringify(objects),before);
});
test('hover brightens each existing state RGB by the source 1.25 clamp and ignores the requested new paint state',()=>{
 for(const [state,channel,expected]of[[0,'supports',[1,1,1]],[1,'supports',[128/255*1.25,1,128/255*1.25]],[2,'supports',[1,128/255*1.25,128/255*1.25]]])fillHoverColor(state,{channel}).forEach((v,i)=>near(v,expected[i]));fillHoverColor(0,{channel:'color',filamentColors:['#204060','#abcdef'],filamentSlot:2}).forEach((v,i)=>near(v,Math.min(1,[171,205,239][i]/255*1.25)));assert.deepEqual(fillHoverColor(1,{channel:'color',filamentColors:['#204060'],state:2}),fillHoverColor(1,{channel:'color',filamentColors:['#204060'],state:0}));
});

test('fill renderer replaces and disposes prior hover geometry without retaining old object highlights',async()=>{const{Scene}=await import('three'),{createFillHoverOverlay}=await import('../../src/paint-fill-overlay.js'),scene=new Scene(),renderer={domElement:{dataset:{}}},overlay=createFillHoverOverlay(scene,renderer),selection=previewObjectFill([square()],'part-a',{id:'part-a',triangleIndex:0,point:[.5,.5,0]},{tool:'fill',channel:'supports',fillAngle:0});overlay.show(selection,{channel:'supports'});const children=[...scene.children[0].children];assert.equal(children.length,2);let disposed=0;for(const child of children){child.geometry.addEventListener('dispose',()=>disposed++);child.material.addEventListener('dispose',()=>disposed++);}overlay.show({...selection,objectId:'part-b'},{channel:'supports'});assert.equal(disposed,4);assert.equal(scene.children[0].children.length,2);assert.equal(JSON.parse(renderer.domElement.dataset.paintFillPreview).objectId,'part-b');overlay.clear();assert.equal(scene.children[0].children.length,0);assert.equal(renderer.domElement.dataset.paintFillPreview,'null');});
