import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {importNative3MF} from '../../shared/native-project.js';import {paintedFacetGeometry} from '../../shared/facet-painting.js';import {paintObjectMembers,paintObjectGroup,changeObjectPaint,paintObjectCursor} from '../../shared/paint-object-group.js';
const source=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url))).objects[0];
function parts(){return['a','b','negative','other','plate','hidden'].map((id,index)=>({...structuredClone(source),id,position:[index*30,0,0],plateId:id==='plate'?'other-plate':source.plateId,visible:id!=='hidden',painting:{version:1,seam:{0:'4'}},native:{...source.native,groupId:id==='other'?'other':'group',partType:id==='negative'?'negative_part':'normal_part'}}));}
test('native object height paint visits every visible normal part while leaving unrelated groups, plates and helpers intact',()=>{
 const objects=parts(),snapshot=structuredClone(objects),result=paintObjectGroup(objects,'a',{id:'b',triangleIndex:0,point:[30,5,8]},{tool:'height',channel:'color',state:2,height:4,filamentCount:2});assert.deepEqual(paintObjectMembers(objects,'a').map(o=>o.id),['a','b']);for(const object of result.objects.slice(0,2)){const facets=paintedFacetGeometry(object,'color');assert.ok(facets.length>10);assert.ok(facets.every(f=>f.vertices.every(p=>p[2]>=7.95&&p[2]<=12.05)));assert.deepEqual(object.painting.seam,{0:'4'});}for(let i=2;i<objects.length;i++)assert.equal(result.objects[i],objects[i]);assert.deepEqual(objects,snapshot);assert.throws(()=>paintObjectGroup(objects,'a',{id:'a',triangleIndex:0,point:[0,0,8]},{tool:'height',channel:'color',state:1,height:8.1}),/0.1 and 8/);
});
test('ordinary brush targets the actual normal-part hit and never joins strokes across different meshes',()=>{
 const objects=parts(),result=paintObjectGroup(objects,'a',{id:'b',triangleIndex:0,point:[35,5,0]},{tool:'triangle',channel:'supports',state:1,previousHit:{id:'a',point:[5,5,0],triangleIndex:0}});assert.equal(result.objects[0],objects[0]);assert.deepEqual(result.objects[1].painting.supports,{0:'4'});assert.deepEqual(result.objects[1].painting.seam,{0:'4'});assert.equal(paintObjectGroup(objects,'a',{id:'other'},{tool:'triangle'}).objects,objects);
 const cleared=changeObjectPaint(result.objects,'a','clear',{channel:'seam'});assert.equal(cleared.objects[0].painting.seam,undefined);assert.equal(cleared.objects[1].painting.seam,undefined);assert.deepEqual(cleared.objects[1].painting.supports,{0:'4'});assert.equal(cleared.objects[3],objects[3]);
});
test('height cursor draws both native object parts at a common world range and preserves scene data',()=>{
 const objects=parts(),before=structuredClone(objects),shape=paintObjectCursor(objects,'a',{id:'b',point:[30,5,8]},{tool:'height',height:4,atPointer:true});assert.deepEqual(shape.range,[8,12]);assert.deepEqual([...new Set(shape.positions.filter((_,i)=>i%3===2))],[8,12]);assert.ok(shape.positions.some((x,i)=>i%3===0&&x<=20));assert.ok(shape.positions.some((x,i)=>i%3===0&&x>=30));assert.ok(shape.positions.filter((_,i)=>i%3===0).every(x=>x<=50));assert.deepEqual(objects,before);
});
