import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';
import{importNative3MF}from'../../shared/native-project.js';import{plateShrinkageContext}from'../../shared/plate-shrinkage.js';import{layerProfileContext}from'../../shared/variable-layers.js';import{generateObjectLayers}from'../../shared/layer-height-texture.js';import{resolveLayerMaterialSettings}from'../../src/layer-material-context.js';
const base=importNative3MF(await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)));
function scene(){const object=structuredClone(base.objects[0]);object.id='solid';object.native={...object.native,groupId:'group',objectSettings:{},partSettings:{}};object.filamentSlot=1;return[object];}
const settings={...base.nativeSettings,layer_height:'.2',initial_layer_print_height:'.2',filament_settings_id:['One','Two','Three'],filament_diameter:['1.75','1.75','1.75'],filament_shrink:['98','97','96'],filament_shrinkage_compensation_z:['98','98','98'],brim_type:'no_brim',enable_support:'0',enable_prime_tower:'0',outer_wall_filament_id:'0',inner_wall_filament_id:'0',sparse_infill_filament_id:'0',internal_solid_filament_id:'0',top_surface_filament_id:'0',bottom_surface_filament_id:'0'};
const context=(objects=scene(),config=settings,options={})=>plateShrinkageContext(objects,objects[0].plateId,config,options);
function part(objects,id,slot,partType='normal_part'){const object=structuredClone(objects[0]);Object.assign(object,{id,filamentSlot:slot});object.native.partType=partType;objects.push(object);return object;}
test('plate scope excludes hidden, nonprintable and other-plate objects; unused slots do not disable compensation',()=>{
 const objects=scene();part(objects,'hidden',2).visible=false;const other=part(objects,'other',2);other.plateId='elsewhere';const no=part(objects,'not-printable',2);no.native.groupId='unprinted';no.printable=false;
 const result=context(objects);assert.deepEqual(result.usedFilamentSlots,[1]);assert.deepEqual(result.shrinkageCompensation,[100/98,100/98,100/98]);const layers=layerProfileContext(objects,objects[0].id,settings);assert.equal(layers.shrinkageCompensationZ,100/98);assert.equal(generateObjectLayers([],layers).length/2,102);
});
test('mixed XY alone or mixed Z disables every axis; equality uses native exact values and get_at first-element fallback',()=>{
 const objects=scene();part(objects,'two',2);assert.deepEqual(context(objects).shrinkageCompensation,[1,1,1]);assert.deepEqual(context(objects,{...settings,filament_shrink:['98','98'],filament_shrinkage_compensation_z:['98','97']}).shrinkageCompensation,[1,1,1]);assert.deepEqual(context(objects,{...settings,filament_shrink:['98'],filament_shrinkage_compensation_z:['98']}).shrinkageCompensation,[100/98,100/98,100/98]);assert.equal(context(objects,{...settings,filament_shrink:['98','98.000000001']}).shrinkageCompensationZ,1);
});
test('subdivided color leaves, modifier base slots and declared height slots participate; negative and support-volume slots do not',()=>{
 const objects=scene();objects[0].painting={version:1,color:{0:'841'}};assert.deepEqual(context(objects).usedFilamentSlots,[1,2]);delete objects[0].painting;part(objects,'negative',2,'negative_part');part(objects,'support',3,'support_enforcer');assert.deepEqual(context(objects).usedFilamentSlots,[1]);const modifier=part(objects,'modifier',2,'modifier_part');modifier.position[0]+=100;assert.deepEqual(context(objects).usedFilamentSlots,[1,2]);objects.pop();objects[0].native.layerConfigRanges=[{minZ:40,maxZ:50,settings:{layer_height:'.2',extruder:'3'}}];assert.deepEqual(context(objects).usedFilamentSlots,[1,3]);
});
test('native feature precedence respects walls/infill gates, modifier intersections and height-range intersections',()=>{
 const objects=scene();objects[0].native.partSettings.outer_wall_filament_id='2';assert.deepEqual(context(objects).usedFilamentSlots,[1,2]);assert.deepEqual(context(objects,{...settings,wall_loops:'0'}).usedFilamentSlots,[1]);delete objects[0].native.partSettings.outer_wall_filament_id;const modifier=part(objects,'modifier',1,'modifier_part');modifier.native.partSettings={outer_wall_filament_id:'2'};modifier.position[0]+=100;assert.deepEqual(context(objects).usedFilamentSlots,[1]);modifier.position[0]-=100;assert.deepEqual(context(objects).usedFilamentSlots,[1,2]);objects.pop();objects[0].native.layerConfigRanges=[{minZ:40,maxZ:50,settings:{layer_height:'.2',outer_wall_filament_id:'2'}}];assert.deepEqual(context(objects).usedFilamentSlots,[1]);objects[0].native.layerConfigRanges[0].minZ=10;assert.deepEqual(context(objects).usedFilamentSlots,[1,2]);
});
test('print-wide brim forces wall region use, raft suppresses brim, and support/raft/enforce include both support slots',()=>{
 const objects=scene();objects[0].native.partSettings.outer_wall_filament_id='2';assert.deepEqual(context(objects,{...settings,wall_loops:'0',brim_type:'auto_brim',brim_width:'0'}).usedFilamentSlots,[1,2]);assert.deepEqual(context(objects,{...settings,wall_loops:'0',brim_type:'auto_brim',raft_layers:'1',support_filament:'1',support_interface_filament:'1'}).usedFilamentSlots,[1]);delete objects[0].native.partSettings.outer_wall_filament_id;
 for(const flag of [{enable_support:'1'},{raft_layers:'1'},{enforce_support_layers:'1'}])assert.deepEqual(context(objects,{...settings,...flag,support_filament:'2',support_interface_filament:'3',support_interface_top_layers:'0'}).usedFilamentSlots,[1,2,3]);assert.deepEqual(context(objects,{...settings,enable_support:'0',support_filament:'2',support_interface_filament:'3'}).usedFilamentSlots,[1]);
});
test('tower uses native pre-dedup gate and selected-plate spiral flag; layer tool events never add shrinkage slots',()=>{
 const objects=scene(),tower={...settings,enable_support:'1',support_filament:'0',support_interface_filament:'0',enable_prime_tower:'1',wipe_tower_filament:'3'};assert.deepEqual(context(objects,tower).usedFilamentSlots,[1,3]);assert.deepEqual(context(objects,tower,{plate:{native:{metadata:{spiral_mode:'true'}}}}).usedFilamentSlots,[1]);assert.deepEqual(context(objects,{...tower,timelapse_type:'1'},{plate:{native:{metadata:{spiral_mode:'true'}}}}).usedFilamentSlots,[1,3]);assert.deepEqual(context(objects,settings,{plate:{layerEvents:{items:[{type:'ToolChange',extruder:2,printZ:2}]}}}).usedFilamentSlots,[1]);
});
test('unresolved materials, invalid percentages and malformed painting fail explicitly',()=>{
 assert.throws(()=>context(scene(),settings,{materialSettingsComplete:false}),/resolved/);assert.throws(()=>context(scene(),{...settings,filament_shrink:['bad']}),/valid/);const objects=scene();objects[0].painting={version:1,color:{0:'FF'}};assert.throws(()=>context(objects),/facet/);objects[0].painting=undefined;objects[0].filamentSlot=4;assert.throws(()=>context(objects),/unresolved/);
});
test('catalog resolver deduplicates requests, restores slot order and ignores displayed first-slot vectors',async()=>{
 const calls=[],project={ids:{printerId:'machine',processId:'process',filamentId:'a'},filamentIds:['a','b','a'],overrides:{}},result=await resolveLayerMaterialSettings(project,{filament_shrink:['101']},{fetchImpl:async url=>{calls.push(url);const b=new URL(url,'http://localhost').searchParams.get('filamentId')==='b';return{ok:true,json:async()=>({filamentSettings:{filament_diameter:['1.75'],filament_shrink:[b?97:98],filament_shrinkage_compensation_z:[98]}})};}});assert.equal(calls.length,2);assert.deepEqual(result.settings.filament_shrink,[98,97,98]);assert.equal(result.filamentCount,3);
 const embedded=await resolveLayerMaterialSettings({useEmbeddedSettings:true,nativeSettings:settings,overrides:{layer_height:.16}},{filament_shrink:['101']},{fetchImpl:()=>{throw new Error('must not fetch');}});assert.deepEqual(embedded.settings.filament_shrink,settings.filament_shrink);assert.equal(embedded.settings.layer_height,'0.16');
});
test('catalog resolution reports failed/missing settings and propagates cancellation',async()=>{
 const project={ids:{printerId:'m',processId:'p',filamentId:'a'},overrides:{}};await assert.rejects(resolveLayerMaterialSettings(project,{}, {fetchImpl:async()=>({ok:false,json:async()=>({error:'Preset missing'})})}),/Preset missing/);await assert.rejects(resolveLayerMaterialSettings(project,{}, {fetchImpl:async()=>({ok:true,json:async()=>({filamentSettings:{}})})}),/missing filament_diameter/);const controller=new AbortController();controller.abort();await assert.rejects(resolveLayerMaterialSettings(project,{}, {signal:controller.signal,fetchImpl:async()=>({ok:true,json:async()=>({filamentSettings:{}})})}),{name:'AbortError'});
});
test('native modifier extents retain Z separation and use ancestor unions for chained candidate regions',()=>{
 const objects=scene(),high=part(objects,'high',1,'modifier_part');high.position[2]+=30;high.native.partSettings={outer_wall_filament_id:'2'};assert.deepEqual(context(objects).usedFilamentSlots,[1]);objects.pop();
 const first=part(objects,'first-modifier',1,'modifier_part');first.position[0]+=10;first.native.partSettings={outer_wall_filament_id:'2'};const second=part(objects,'second-modifier',1,'modifier_part');second.position[0]+=25;second.native.partSettings={outer_wall_filament_id:'3'};assert.deepEqual(context(objects).usedFilamentSlots,[1,2,3]);
});


test('sparse catalog settings resolve structured native percent defaults before region validation',()=>{
 const objects=scene(),minimal={filament_settings_id:['PLA'],filament_diameter:['1.75'],nozzle_diameter:['0.4'],layer_height:'.2',initial_layer_print_height:'.2'};
 const result=context(objects,minimal);assert.deepEqual(result.usedFilamentSlots,[1]);assert.deepEqual(result.shrinkageCompensation,[1,1,1]);
 const layers=layerProfileContext(objects,objects[0].id,minimal);assert.equal(layers.layerHeight,.2);assert.equal(layers.shrinkageCompensationZ,1);
});
