import test from'node:test';import assert from'node:assert/strict';import{createPreviewRenderScheduler}from'../../src/preview-render-scheduler.js';
function clock(){let next=0;const queue=new Map();return{request:fn=>{queue.set(++next,fn);return next;},cancel:id=>queue.delete(id),get size(){return queue.size;},tick(){const pending=[...queue.values()];queue.clear();for(const fn of pending)fn();}};}
test('preview renders invalidated frames once and remains idle until a new change',()=>{const time=clock();let rendered=0;const scheduler=createPreviewRenderScheduler({...time,render:()=>rendered++});scheduler.invalidate();scheduler.invalidate();assert.equal(time.size,1);time.tick();assert.equal(rendered,1);assert.equal(time.size,0);time.tick();assert.equal(rendered,1);scheduler.invalidate();time.tick();assert.equal(rendered,2);scheduler.dispose();});
test('preview drains OrbitControls damping including change events without an endless animation loop',()=>{const time=clock();let rendered=0,remaining=4,scheduler; scheduler=createPreviewRenderScheduler({...time,render:()=>rendered++,update:()=>{if(!remaining--)return false;scheduler.invalidate();return true;}});scheduler.invalidate();for(let i=0;i<5;i++){assert.equal(time.size,1);time.tick();}assert.equal(rendered,5);assert.equal(time.size,0);scheduler.dispose();});
test('disposed previews cancel pending frames and cannot draw into a detached canvas',()=>{const time=clock();let rendered=0;const scheduler=createPreviewRenderScheduler({...time,render:()=>rendered++});scheduler.invalidate();assert.equal(time.size,1);scheduler.dispose();assert.equal(time.size,0);scheduler.invalidate();time.tick();assert.equal(rendered,0);});
function pacedClock(){let id=0,t=0;const frames=new Map(),timers=new Map();return{now:()=>t,request:fn=>{frames.set(++id,fn);return id;},cancel:id=>frames.delete(id),delay:(fn,ms)=>{timers.set(++id,{fn,due:t+ms});return id;},clearDelay:id=>timers.delete(id),get size(){return frames.size+timers.size;},get frames(){return frames.size;},get timers(){return timers.size;},elapse:ms=>{t+=ms;},tick(ms){t=ms;for(const [key,v] of [...timers])if(v.due<=t){timers.delete(key);v.fn();}const due=[...frames.values()];frames.clear();for(const fn of due)fn();}};}
test('a capped viewport coalesces continuous invalidation and leaves no timer while idle',()=>{const time=pacedClock(),draws=[],s=createPreviewRenderScheduler({...time,readFpsCap:()=>10,render:()=>draws.push(time.now())});for(let t=0;t<=500;t+=5){s.invalidate();time.tick(t);}assert.deepEqual(draws,[0,100,200,300,400,500]);assert.equal(time.size,0);time.tick(2000);assert.equal(draws.length,6);s.invalidate();time.tick(2001);assert.equal(draws.at(-1),2001);assert.equal(time.size,0);s.dispose();});
test('changing the cap releases a waiting frame and disposal cancels all scheduled work',()=>{const time=pacedClock();let cap=1,draws=0;const s=createPreviewRenderScheduler({...time,readFpsCap:()=>cap,render:()=>draws++});s.invalidate();time.tick(0);s.invalidate();time.tick(10);assert.equal(time.timers,1);cap=0;s.refresh();assert.equal(time.timers,0);time.tick(11);assert.equal(draws,2);cap=1;s.invalidate();time.tick(12);assert.equal(time.timers,1);s.dispose();assert.equal(time.size,0);time.tick(2000);assert.equal(draws,2);});
test('render duration consumes the native frame budget and a trailing damped frame still draws',()=>{const time=pacedClock(),starts=[];let updates=2;const s=createPreviewRenderScheduler({...time,readFpsCap:()=>10,update:()=>updates-->0,render:()=>{starts.push(time.now());time.elapse(80);}});s.invalidate();time.tick(0);time.tick(85);assert.equal(time.timers,1);time.tick(100);time.tick(185);time.tick(200);assert.deepEqual(starts,[0,100,200]);assert.equal(time.size,0);s.dispose();});
