import test from'node:test';import assert from'node:assert/strict';import{extendPrusaFilaments}from'../../shared/prusa-context.js';
const settings=()=>({printer_settings_id:'Current machine',print_settings_id:'Current process',filament_settings_id:['Red','Blue'],nozzle_diameter:['.4'],filament_shrink:['99','98'],filament_shrinkage_compensation_z:['97','96'],filament_colour:['#FF0000','#0000FF'],filament_colour_type:['1','1'],filament_multi_colour:['#FF0000','#0000FF'],filament_map:['1','1'],flush_multiplier:['1'],flush_volumes_vector:['120','80','90','110'],flush_volumes_matrix:['0','230','170','0'],layer_height:'0.17'});
test('current full embedded vectors remain untouched when native import needs no added slot',()=>{const original=settings();assert.deepEqual(extendPrusaFilaments(original,1),original);assert.notEqual(extendPrusaFilaments(original,1),original);});
test('native material expansion repeats last material, preserves old purge cells, and derives new cells from first load/unload pair',()=>{const original=settings(),result=extendPrusaFilaments(original,3);assert.deepEqual(result.filament_settings_id,['Red','Blue','Blue']);assert.deepEqual(result.filament_shrink,['99','98','98']);assert.deepEqual(result.filament_shrinkage_compensation_z,['97','96','96']);assert.deepEqual(result.filament_colour,['#FF0000','#0000FF','#00C1AE']);assert.deepEqual(result.flush_volumes_vector,['120','80','90','110','120','80']);assert.deepEqual(result.flush_volumes_matrix,['0','230','200','170','0','170','200','230','0']);assert.equal(result.layer_height,'0.17');assert.deepEqual(original,settings());});
test('malformed material contexts fail explicitly',()=>{for(const value of[0,65,NaN,1.5])assert.throws(()=>extendPrusaFilaments(settings(),value));assert.throws(()=>extendPrusaFilaments({...settings(),flush_volumes_matrix:['0','1','2']},3),/[Pp]urg(?:e|ing) matrix/);});

test('missing current display color uses the pinned native project default before adding the native cycle color',()=>{const source={...settings(),filament_settings_id:['First'],filament_colour:undefined,filament_colour_type:undefined,filament_multi_colour:undefined,filament_map:['1'],flush_volumes_matrix:['0'],flush_volumes_vector:['140','140'],filament_shrink:['100%'],filament_shrinkage_compensation_z:['100%']};assert.deepEqual(extendPrusaFilaments(source,2).filament_colour,['#F2754E','#00C1AE']);});

test('imported multi-nozzle material expansion retains every nozzle matrix and multiplier',()=>{const source={...settings(),nozzle_diameter:['.4','.4'],flush_multiplier:['.3','.8'],flush_volumes_matrix:['0','111','222','0','0','333','444','0']};const expanded=extendPrusaFilaments(source,3);assert.deepEqual(expanded.flush_volumes_matrix,['0','111','200','222','0','170','200','230','0','0','333','200','444','0','170','200','230','0']);assert.deepEqual(expanded.flush_multiplier,['.3','.8']);});
