import test from'node:test';import assert from'node:assert/strict';import{normalizePurgeSettings,resizePurgeSettings,physicalNozzleCount,purgeDisplayValue,purgeRawValue}from'../../shared/purge-volumes.js';
const dual=()=>({nozzle_diameter:['.4','.4'],flush_volumes_matrix:['0','111','222','0','0','333','444','0'],flush_volumes_vector:['120','80','90','110'],flush_multiplier:['.3','.8']});
test('native nozzle-major tables and multipliers preserve distinct source values',()=>{const s=dual();assert.equal(physicalNozzleCount(s),2);assert.deepEqual(normalizePurgeSettings(s,2),{flush_volumes_matrix:s.flush_volumes_matrix,flush_volumes_vector:s.flush_volumes_vector,flush_multiplier:s.flush_multiplier});assert.equal(s.flush_volumes_matrix[5],'333');});
test('adding material retains each physical table and fills only new transitions from first load/unload pair',()=>{const s=dual(),n=resizePurgeSettings(s,2,[0,1,null]);assert.deepEqual(n.flush_volumes_matrix,['0','111','200','222','0','170','200','230','0','0','333','200','444','0','170','200','230','0']);assert.deepEqual(n.flush_multiplier,['.3','.8']);assert.deepEqual(n.flush_volumes_vector,['120','80','90','110','120','80']);assert.deepEqual(s,dual());});
test('removing a material preserves nozzle boundaries and all unrelated values',()=>{const n=resizePurgeSettings(dual(),2,[0,1,null]);assert.deepEqual(resizePurgeSettings({...dual(),...n},3,[0,1]),normalizePurgeSettings(dual(),2));});
test('adding a physical nozzle initializes its full table independently and defaults only its multiplier to1',()=>{const n=resizePurgeSettings(dual(),2,[0,1],{oldNozzles:2,nozzles:3});assert.deepEqual(n.flush_volumes_matrix.slice(8),['0','230','170','0']);assert.deepEqual(n.flush_multiplier,['.3','.8','1']);});
test('known native unused four-material defaults normalize, while arbitrary malformed layouts fail',()=>{assert.deepEqual(normalizePurgeSettings({},1,{nozzles:2}).flush_volumes_matrix,['0','0']);assert.deepEqual(normalizePurgeSettings({},1,{nozzles:2}).flush_multiplier,['0.3','1']);for(const matrix of[[],['0','1','2'],['0','3','4','0'],Array(8).fill('oops')])assert.throws(()=>normalizePurgeSettings({...dual(),flush_volumes_matrix:matrix},2));assert.throws(()=>resizePurgeSettings(dual(),2,[0,0]));assert.throws(()=>normalizePurgeSettings(dual(),65));});
test('native displayed-volume and raw-volume rounding preserves multiplier semantics includingzero',()=>{assert.equal(purgeDisplayValue(375,.3),113);assert.equal(purgeRawValue(375,.3),'1250');assert.equal(purgeDisplayValue(280,0),0);assert.equal(purgeRawValue(200,0),'0');assert.equal(purgeDisplayValue(99999,1),20000);assert.throws(()=>purgeRawValue(20001,1));});

import{normalizeNativeProjectValues}from'../../shared/profile-settings.js';
test('typed project settings permit the bounded native64-material dual-nozzle matrix beyond the generic vector limit',()=>{const matrix=Array(2*64*64).fill('0');assert.equal(normalizeNativeProjectValues({flush_volumes_matrix:matrix}).flush_volumes_matrix.length,8192);assert.throws(()=>normalizeNativeProjectValues({flush_volumes_matrix:Array(64**3+1).fill(0)}),/262144/);});
