import test from 'node:test';import assert from 'node:assert/strict';
import {createCalibrationPlan,applyCalibrationOverrides} from '../../shared/calibration.js';
import {retractionLength,applyRetractionSchedule} from '../../shared/retraction-calibration.js';
const selected=()=>({printer:{name:'Fixture',printer_technology:'FFF',gcode_flavor:'marlin2',nozzle_diameter:['.4'],printable_height:'250',max_layer_height:['.3'],retraction_length:['.8'],z_hop:['0'],retract_before_wipe:['70'],retract_restart_extra:['0'],wipe:['1']},process:{},filament:{slow_down_layer_time:['0'],filament_retraction_length:['nil'],filament_z_hop:['nil'],filament_retract_before_wipe:['nil'],filament_retract_restart_extra:['nil'],filament_wipe:['nil']}});
const request={mode:'retraction',start:.2,end:.6,step:.2};
function fixture(){const lines=['; retraction_length = 0.8','; use_firmware_retraction = 0','; gcode_comments = 1','; retract_restart_extra = 0','M83',';LAYER_CHANGE',';Z:0.2','G1 E-.8 F1800 ; retract',';_SET_FAN_SPEED_CHANGING_LAYER','G1 E.8 F1800 ; ; unretract','G1 X10 E1 F1200 ; perimeter','G1 E-.56 F1800 ; retract',';WIPE_START','G1 F1200','G1 X11 E-.12 ; wipe and retract','G1 X12 E-.12 ; wipe and retract',';WIPE_END','G1 X20 F18000','G1 E.8 F1800 ; ; unretract','G1 X30 E2 F1200 ; perimeter',';LAYER_CHANGE',';Z:1.4','G1 E-.8 F1800 ; retract',';_SET_FAN_SPEED_CHANGING_LAYER','G1 E.8 F1800 ; ; unretract','G1 X40 E1 F1200 ; perimeter','G1 E-.56 F1800 ; retract',';WIPE_START','G1 F1200','G1 X41 E-.12 ; wipe and retract','G1 X42 E-.12 ; wipe and retract',';WIPE_END','G1 X50 F18000','G1 E.8 F1800 ; ; unretract','M73 P50 R3','; estimated printing time = 3m','; filament used [g] = 1.25'];const middle=[];for(let i=2;i<=6;i++)middle.push(';LAYER_CHANGE',`;Z:${i*.2}`,';_SET_FAN_SPEED_CHANGING_LAYER');lines.splice(20,0,...middle);const layers=[{start:5,anchor:8,z:.2},...Array.from({length:5},(_,i)=>({start:20+i*3,anchor:22+i*3,z:(i+2)*.2})),{start:35,anchor:38,z:1.4}];return{lines,layers};}
test('retraction uses pinned native tower height, nozzle layer height and writer schedule',()=>{const native=selected(),plan=createCalibrationPlan(request,native),settings=applyCalibrationOverrides(native,plan);assert.ok(Math.abs(plan.height-3.3999)<1e-10);assert.equal(plan.model.resource,'retraction/retraction_tower.drc');assert.equal(plan.overrides.process.wall_loops,'2');assert.equal(Number(plan.overrides.process.layer_height),Math.fround(.2));assert.equal(Number(plan.overrides.process.initial_layer_print_height),Math.fround(.2));assert.equal(plan.overrides.process.seam_position,'aligned');assert.equal(plan.overrides.printer.use_firmware_retraction,'0');assert.equal(retractionLength(plan,.2),.2);assert.equal(retractionLength(plan,1.2),.2);assert.equal(retractionLength(plan,1.4),.4);assert.equal(retractionLength(plan,1.4001),.4);assert.deepEqual(settings.filament.filament_retraction_length,['0.8']);assert.deepEqual(native.printer.retraction_length,['.8']);for(const [nozzle,height]of[['.1','0.05'],['.2','0.1'],['.25','0.2']]){native.printer.nozzle_diameter=[nozzle];assert.equal(Number(createCalibrationPlan(request,native).overrides.process.layer_height),Math.fround(Number(height)));}});
test('relative E changes pre-wipe distribution and balances old retraction across layer anchors',()=>{const plan=createCalibrationPlan(request,selected()),{lines,layers}=fixture(),result=applyRetractionSchedule(lines,layers,plan),text=result.lines.join('\n');assert.match(text,/G1 E-0.14 F1800 ; retract/);assert.match(text,/G1 X11 E-0.03 ; wipe and retract/);assert.match(text,/G1 X41 E-0.06 ; wipe and retract/);assert.match(text,/;Z:1.4\nG1 E-0.2 F1800 ; retract\n;_SET_FAN_SPEED_CHANGING_LAYER\n; Calib_Retraction_tower: Z_HEIGHT: 1.4, length:0.4\nG1 E0.2 F1800/);assert.match(text,/G1 E0.4 F1800 ; ; unretract/);assert.match(text,/G1 X30 E2 F1200 ; perimeter/);assert.doesNotMatch(text,/^M73|^; estimated printing time/m);assert.match(text,/filament used \[g\] = 1.25/);assert.equal(result.summary.cycles,4);assert.equal(result.summary.wipeMoves,4);});
test('zero-length retraction with no hop emits zero E for wipes and matching unretractions',()=>{const plan=createCalibrationPlan({...request,start:0,end:.4},selected()),{lines,layers}=fixture(),text=applyRetractionSchedule(lines,layers,plan).lines.join('\n');assert.match(text,/G1 X11 E0 ; wipe and retract/);assert.match(text,/G1 E0 F1800 ; ; unretract/);assert.match(text,/G1 X41 E-0.03 ; wipe and retract/);});
test('wipe capacity moves excess retraction before the wipe rather than increasing its physical E rate',()=>{const native=selected();native.printer.retract_before_wipe=['0'];const plan=createCalibrationPlan(request,native),{lines,layers}=fixture();const result=applyRetractionSchedule(lines,layers,plan).lines.join('\n');assert.match(result,/G1 X11 E-0.1 ; wipe and retract/);assert.match(result,/G1 E-0.16 F1800 ; retract\n;WIPE_START/);assert.match(result,/G1 X41 E-0.12 ; wipe and retract/);});
test('absolute E coordinates preserve deposition deltas through changed retractions and G92 resets',()=>{const plan=createCalibrationPlan(request,selected()),{lines}=fixture();lines.splice(20,0,'G92 E0');let e=0;const absolute=lines.map(line=>{if(line==='M83')return'M82';if(line==='G92 E0'){e=0;return line;}if(!/^G1\b/.test(line))return line;return line.replace(/\bE([-+.\d]+)/,(_,n)=>`E${Number((e+=Number(n)).toFixed(5))}`)});const layers=[];for(let row=0;row<lines.length;row++){if(lines[row]===';LAYER_CHANGE')layers.push({start:row,z:Number(lines[row+1].slice(3))});if(lines[row]===';_SET_FAN_SPEED_CHANGING_LAYER')layers.at(-1).anchor=row;}const result=applyRetractionSchedule(absolute,layers,plan).lines.join('\n');assert.match(result,/G1 X11 E0.83 ; wipe and retract/);assert.match(result,/G1 X30 E3 F1200 ; perimeter\nG92 E0/);assert.match(result,/G1 X40 E1 F1200 ; perimeter/);assert.match(result,/G1 X41 E0.66 ; wipe and retract/);});
test('unproven native couplings and invalid ranges are rejected explicitly',()=>{for(const change of [{start:-1},{end:21},{step:0},{end:.2},{end:20,step:.01}])assert.throws(()=>createCalibrationPlan({...request,...change},selected()));for(const modify of [s=>s.printer.z_hop=['.4'],s=>s.filament.slow_down_layer_time=['10'],s=>s.process.max_volumetric_extrusion_rate_slope='1',s=>{s.filament.enable_pressure_advance=['1'];s.filament.adaptive_pressure_advance=['1']},s=>s.printer.retract_restart_extra=['.1'],s=>s.process.raft_layers='1',s=>s.process.spiral_mode='1',s=>s.printer.layer_change_gcode='G1 E1']){const native=selected();modify(native);assert.throws(()=>createCalibrationPlan({...request,start:0,end:.4},native));}});
test('missing native guards, unknown body retractions and incomplete wipe data fail closed',()=>{const plan=createCalibrationPlan(request,selected());for(const change of [lines=>lines[0]='; retraction_length = 9',lines=>lines[10]='G1 X10 E-1 ; unknown retract',lines=>lines[16]=';missing',lines=>lines[10]='G10']){const{lines,layers}=fixture();change(lines);assert.throws(()=>applyRetractionSchedule(lines,layers,plan));}});
test('Bambu wipe and custom role tags preserve retraction bookkeeping and leave end macros untouched',()=>{
 const plan=createCalibrationPlan(request,selected()),{lines,layers}=fixture();lines.push(';TYPE:Custom','G1 E-.8 F1800 ; retract');const native=lines.map(line=>line.replace(';LAYER_CHANGE','; CHANGE_LAYER').replace(';Z:','; Z_HEIGHT: ').replace(';WIPE_START','; WIPE_START').replace(';WIPE_END','; WIPE_END').replace(';TYPE:','; FEATURE: '));
 const expected=applyRetractionSchedule(lines,layers,plan),actual=applyRetractionSchedule(native,layers,plan);assert.deepEqual(actual.summary,expected.summary);assert.deepEqual(actual.lines.filter(line=>/^[GM]\d/.test(line)),expected.lines.filter(line=>/^[GM]\d/.test(line)));assert.equal(actual.lines.at(-1),'G1 E-.8 F1800 ; retract');assert.ok(actual.lines.includes('; WIPE_START'));
});
