import test from'node:test';import assert from'node:assert/strict';import{readFile,mkdtemp,mkdir,writeFile,readdir,rm,stat}from'node:fs/promises';import{tmpdir}from'node:os';import path from'node:path';import{unzipSync,strFromU8}from'fflate';import{XMLParser}from'fast-xml-parser';
import{prepareShrinkageWarmup}from'../../server/shrinkage-warmup.js';import{exportNative3MF,importNative3MF}from'../../shared/native-project.js';import{sliceModel}from'../../server/slicer.js';
import{shrinkageCase}from'../fixtures/shrinkage-cases.js';
const version='OrcaSlicer-2.4.2';const fixture=async kind=>(await shrinkageCase(kind)).project;
const parser=new XMLParser({ignoreAttributes:false,parseAttributeValue:false,parseTagValue:false});const arr=value=>Array.isArray(value)?value:[value];
test('second-apply archive reuses exact geometry/settings and places only a second instance on the internal plate',async()=>{
 const project=await fixture('range-same'),bytes=exportNative3MF(project),warm=prepareShrinkageWarmup({project,bytes,engineVersion:version}),a=unzipSync(bytes),b=unzipSync(warm.bytes),original=parser.parse(strFromU8(a['3D/3dmodel.model'])),internal=parser.parse(strFromU8(b['3D/3dmodel.model']));
 assert.deepEqual(internal.model.resources,original.model.resources);assert.deepEqual(arr(internal.model.build.item).slice(0,1),arr(original.model.build.item));assert.equal(arr(internal.model.build.item).length,2);assert.equal(arr(internal.model.build.item)[0]['@_objectid'],arr(internal.model.build.item)[1]['@_objectid']);assert.deepEqual(b['Metadata/layer_config_ranges.xml'],a['Metadata/layer_config_ranges.xml']);assert.equal(b['Metadata/orca-web.json'],undefined);
 assert.deepEqual(warm.summary.usedFilamentSlots,[1,2]);assert.deepEqual(warm.summary.compensation,[100/98,100/98,100/98]);const imported=importNative3MF(warm.bytes);assert.equal(imported.plates.length,2);assert.equal(imported.objects.length,2);assert.deepEqual(imported.objects[0].positions,imported.objects[1].positions);
});
test('warmup activates only for exact installed version and nonunity used-slot compensation',async()=>{
 for(const [kind,active]of [['xy-only',true],['z-only',true],['unused-slot',true],['mixed-xy',false],['paint-same',true],['range-same',true],['brim',true],['support-slot',true]]){const project=await fixture(kind);assert.equal(Boolean(prepareShrinkageWarmup({project,engineVersion:version})),active,kind);assert.equal(prepareShrinkageWarmup({project,engineVersion:'OrcaSlicer-2.4.3'}),null);}
 const project=await fixture('xy-only');project.nativeSettings.filament_shrink=['100'];assert.equal(prepareShrinkageWarmup({project,engineVersion:version}),null);
});
test('painting, brim auxiliaries and layer event/filament sequence metadata survive both initialization instances',async()=>{
 const project=await fixture('brim');project.objects[0].painting={version:1,color:{4:'4'}};project.plates[0].layerEvents={mode:'SingleExtruder',items:[{type:'PausePrint',printZ:1,extruder:1,color:'',extra:'check'}]};const warm=prepareShrinkageWarmup({project,engineVersion:version}),q=importNative3MF(warm.bytes);
 assert.deepEqual(q.objects[0].painting,q.objects[1].painting);assert.deepEqual(q.objects[0].brimEars,q.objects[1].brimEars);assert.deepEqual(q.plates[0].layerEvents,q.plates[1].layerEvents);assert.equal(q.objects[0].native.objectSettings.brim_type,'painted');
});
async function mockBinary(t,body){const root=await mkdtemp(path.join(tmpdir(),'orca-warmup-adapter-'));t.after(()=>rm(root,{recursive:true,force:true}));const binary=path.join(root,'mock-slicer');await writeFile(binary,`#!/bin/sh\n${body}\n`,{mode:0o755});return{root,binary,output:path.join(root,'out','result.gcode')};}
const request={version:1,bytes:new Uint8Array([1,2,3]),expectedOutputNames:['plate_1.gcode','plate_2.gcode'],targetOutputName:'plate_1.gcode',summary:{method:'native-two-apply'}};
test('adapter returns target plate1 only and removes all internal files',async t=>{const args=await mockBinary(t,"printf 'real target' > plate_1.gcode\nprintf 'internal copy' > plate_2.gcode");const result=await sliceModel({...args,input:path.join(args.root,'unused'),preservePosition:true,shrinkageWarmup:request});assert.equal(await readFile(args.output,'utf8'),'real target');assert.deepEqual(await readdir(path.dirname(args.output)),['result.gcode']);assert.deepEqual(result.shrinkageInitialization,request.summary);});
test('adapter rejects missing or extra plate outputs and cleans temporary data without publishing a download',async t=>{for(const body of ["printf target > plate_1.gcode","printf target > plate_1.gcode\nprintf warm > plate_2.gcode\nprintf unexpected > plate_3.gcode"]){const args=await mockBinary(t,body);await assert.rejects(sliceModel({...args,input:'unused',preservePosition:true,shrinkageWarmup:request}),/unexpected plate outputs/);assert.deepEqual(await readdir(path.dirname(args.output)),[]);}});
test('adapter rejects mixing initialized embedded settings with external preset flags',async t=>{const args=await mockBinary(t,'exit 0');await assert.rejects(sliceModel({...args,input:'unused',profilePath:'process.json',preservePosition:true,shrinkageWarmup:request}),/Invalid native shrinkage/);assert.deepEqual(await readdir(path.dirname(args.output)),[]);});
test('cancelling native initialization deletes partial outputs and never publishes plate1',async t=>{
 const root=await mkdtemp(path.join(tmpdir(),'orca-warmup-cancel-'));t.after(()=>rm(root,{recursive:true,force:true}));const binary=path.join(root,'slow-slicer'),output=path.join(root,'out','result.gcode');await writeFile(binary,`#!${process.execPath}\nimport('node:fs').then(fs=>{fs.writeFileSync('plate_1.gcode','partial');fs.writeFileSync('plate_2.gcode','partial');setInterval(()=>{},1000);});\n`,{mode:0o755});
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),100);try{await assert.rejects(sliceModel({binary,input:'unused',output,preservePosition:true,shrinkageWarmup:request,signal:controller.signal,timeoutMs:5000}),/cancelled/);}finally{clearTimeout(timer);}assert.deepEqual(await readdir(path.dirname(output)),[]);
});
