import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{XMLParser,XMLBuilder}from'fast-xml-parser';import{strFromU8,strToU8,zipSync}from'fflate';
import{importNative3MF,exportNative3MF}from'../../shared/native-project.js';import{extractBoundedZip}from'../../shared/import-limits.js';import{addFilamentSlot}from'../../shared/filament-slots.js';import{plateShrinkageContext}from'../../shared/plate-shrinkage.js';import{updateSceneTransform}from'../../shared/scene-object-operations.js';import{updateNativePart}from'../../shared/native-object-settings.js';
const fixture=await readFile(new URL('../fixtures/native-gui-shrink98-2.4.2.3mf',import.meta.url)),parser=new XMLParser({ignoreAttributes:false,parseTagValue:false,parseAttributeValue:false}),builder=new XMLBuilder({ignoreAttributes:false});
function project(){const p=addFilamentSlot({...importNative3MF(fixture),useEmbeddedSettings:true});p.useEmbeddedSettings=true;p.nativeSettings.filament_shrink=['100','98'];p.nativeSettings.filament_shrinkage_compensation_z=['100','98'];return p;}
function staleArchive(){const p=project(),files=extractBoundedZip(exportNative3MF(p)),config=parser.parse(strFromU8(files['Metadata/model_settings.config']));config.config.object.part.metadata.find(v=>v['@_key']==='extruder')['@_value']='2';files['Metadata/model_settings.config']=strToU8(builder.build(config));return zipSync(files);}
test('single-volume native import exposes the material the actual native importer uses',()=>{
 const p=importNative3MF(staleArchive());assert.equal(p.objects[0].native.partSettings.extruder,'2','Source field retained');assert.equal(p.objects[0].native.objectSettings.extruder,'1');assert.equal(p.objects[0].filamentSlot,1,'Native discards a sole volume material override');const context=plateShrinkageContext(p.objects,p.activePlateId,p.nativeSettings);assert.deepEqual(context.usedFilamentSlots,[1]);assert.equal(context.shrinkageCompensationZ,1);
});
for(const edit of['inspector','part-editor'])test(`explicit ${edit} single-volume material survives native export despite stale parent metadata`,()=>{
 const p=project(),source=p.objects[0];p.objects=edit==='inspector'?updateSceneTransform(p.objects,source.id,{filamentSlot:2}):updateNativePart(p.objects,source.id,{filamentSlot:2});assert.equal(p.objects[0].native.objectSettings.extruder,'1','Reproduces existing stale metadata');const q=importNative3MF(exportNative3MF(p));assert.equal(q.objects[0].native.objectSettings.extruder,'2');assert.equal(q.objects[0].filamentSlot,2);assert.equal(plateShrinkageContext(q.objects,q.activePlateId,q.nativeSettings).shrinkageCompensationZ,100/98);
});
test('multi-volume groups retain a distinct parent material and independent part choices',()=>{
 const p=project(),source=p.objects[0];p.objects=[source,{...structuredClone(source),id:'second-part',filamentSlot:2,position:[30,0,0]}];const q=importNative3MF(exportNative3MF(p));assert.deepEqual(q.objects.map(o=>o.filamentSlot),[1,2]);assert.deepEqual(q.objects.map(o=>o.native.objectSettings.extruder),['1','1']);assert.deepEqual(plateShrinkageContext(q.objects,q.activePlateId,q.nativeSettings).usedFilamentSlots,[1,2]);
});
