import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{strFromU8,strToU8,zipSync}from'fflate';
import{normalizeLayerHeightProfile,layerProfileContext,initialLayerHeightProfile,adaptiveLayerHeightProfile,smoothLayerHeightProfile,readLayerHeightProfiles,writeLayerHeightProfiles,updateLayerHeightProfile,LAYER_PROFILE_PATH}from'../../shared/variable-layers.js';import{importNative3MF,exportNative3MF}from'../../shared/native-project.js';import{createMesh}from'../../shared/geometry.js';import{extractBoundedZip}from'../../shared/import-limits.js';import{createNativeProjectService}from'../../server/native-projects.js';import{fixtureCatalog}from'../fixtures/native-project-catalog.js';import{makeNativeAcceptanceProject}from'../fixtures/native-project.js';import{updateNativePart}from'../../shared/native-object-settings.js';
const fixture=await readFile(new URL('../fixtures/orca-2.4.2-cube.3mf',import.meta.url)),base=importNative3MF(fixture),settings={...base.nativeSettings,layer_height:'.2'},context=layerProfileContext(base.objects,base.selectedId,settings),profile=[0,.2,.2,.2,.2,.1,8,.1,12,.25,20,.25];
function pyramid(){const a=[-10,-10,0],b=[10,-10,0],c=[10,10,0],d=[-10,10,0],top=[0,0,20];return createMesh({id:'pyramid',name:'Pyramid',positions:[a,c,b,a,d,c,a,b,top,b,c,top,c,d,top,d,a,top].flat(),plateId:'plate-1'});}
const reference=JSON.parse(await readFile(new URL('../fixtures/variable-layers-native-reference.json',import.meta.url)));
for(const item of reference.cases)test(`adaptive and smoothing match independently compiled native ${item.shape} quality ${item.quality}`,()=>{
 const objects=item.shape==='cube'?base.objects:[pyramid()],ctx=layerProfileContext(objects,objects[0].id,settings),actual=adaptiveLayerHeightProfile(ctx,item.quality);assert.equal(actual.length,item.profile.length);for(let i=0;i<actual.length;i++)assert.ok(Math.abs(actual[i]-item.profile[i])<1e-7,`profile[${i}]: ${actual[i]} vs ${item.profile[i]}`);
 for(const [key,keepMin]of [['smooth',false],['keepMin',true]]){const smoothed=smoothLayerHeightProfile(actual,ctx,{radius:3,keepMin});assert.equal(smoothed.length,item[key].length);for(let i=0;i<smoothed.length;i++)assert.ok(Math.abs(smoothed[i]-item[key][i])<1e-7,`${key}[${i}]`);}
});
test('profile boundary validates scalar pairs, finite heights, order, native first height and current normal-part height',()=>{
 for(const bad of [[0,.2,20,.2],[0,.2,1],[1,.2,10,.2,20,.2],[0,.2,12,.2,10,.2],[0,.2,10,0,20,.2],[0,.2,10,NaN,20,.2],[0,.2,'10',.2,20,.2]])assert.throws(()=>normalizeLayerHeightProfile(bad));assert.throws(()=>normalizeLayerHeightProfile([...profile.slice(0,-2),30,.25],context),/object is 20/);assert.throws(()=>normalizeLayerHeightProfile([0,.16,.2,.2,20,.2],context),/first height/);assert.throws(()=>normalizeLayerHeightProfile([0,.2,.2,.2,10,.5,20,.5],context),/between/);assert.deepEqual(normalizeLayerHeightProfile([],context),[]);
});
test('source layer limits fall back for zero bounds, include default layer height and preserve raft semantics',()=>{
 const ctx=layerProfileContext(base.objects,base.selectedId,{...settings,min_layer_height:['0'],max_layer_height:['0']});assert.equal(ctx.minLayerHeight,.07);assert.ok(Math.abs(ctx.maxLayerHeight-.3)<1e-12);const raft=layerProfileContext(base.objects,base.selectedId,{...settings,raft_layers:'2',initial_layer_print_height:'.3'});assert.equal(raft.firstLayerHeight,.2);assert.equal(raft.firstLayerFixed,false);
 const thin=layerProfileContext(base.objects,base.selectedId,{...settings,layer_height:'.05'});assert.equal(thin.minLayerHeight,.05);assert.throws(()=>adaptiveLayerHeightProfile(context,-1),/quality/);assert.throws(()=>smoothLayerHeightProfile(profile,context,{radius:1.5}),/integer/);
});
test('adaptive source incorporates sorted height ranges and smoothing keep-min never increases a point',()=>{
 const objects=structuredClone(base.objects);objects[0].native.layerConfigRanges=[{minZ:2,maxZ:6,settings:{layer_height:'.1'}}];const ctx=layerProfileContext(objects,objects[0].id,settings),adaptive=adaptiveLayerHeightProfile(ctx,.5);for(let i=0;i<adaptive.length;i+=2)if(adaptive[i]>=2&&adaptive[i]<=6)assert.ok(Math.abs(adaptive[i+1]-.1)<1e-7);const smooth=smoothLayerHeightProfile(profile,context,{radius:3,keepMin:true});for(let i=1;i<smooth.length;i+=2)assert.ok(smooth[i]<=profile[i]+1e-12);assert.deepEqual(smooth.slice(0,4),profile.slice(0,4));
});
test('native profile codec uses model-object indices, preserves decimal values and refuses malformed metadata',()=>{
 const text=writeLayerHeightProfiles([[],profile]);assert.match(text,/^object_id=2\|0\.000000;0\.200000/);assert.deepEqual(readLayerHeightProfiles(text).get(2),profile);assert.equal(writeLayerHeightProfiles([[]]),null);for(const text of ['object_id=0|0;.2;1;.2;2;.2','object_id=1|0;.2;20;.2','object_id=1|0;.2;;.2;20;.2','object_id=1|0;.2;10;.2;20;NaN',`object_id=1|0;.2;10;.2;20;.2\nobject_id=1|0;.2;10;.2;20;.2`])assert.throws(()=>readLayerHeightProfiles(text));
});
test('profiles roundtrip over component groups and selected plates, including joint height-range metadata',()=>{
 let project=makeNativeAcceptanceProject(base);project.nativeSettings={...settings,filament_settings_id:['Red','Blue']};project.objects=updateLayerHeightProfile(project.objects,'base',profile,settings,{filamentCount:2});project.objects=updateLayerHeightProfile(project.objects,'second',profile,settings,{filamentCount:2});const bytes=exportNative3MF(project),data=strFromU8(extractBoundedZip(bytes)[LAYER_PROFILE_PATH]);assert.match(data,/object_id=1\|/);assert.match(data,/object_id=3\|/);const result=importNative3MF(bytes);for(const name of ['Red main','Through hole','Dense corner','Second plate object'])assert.deepEqual(result.objects.find(o=>o.name===name).native.layerHeightProfile,profile);assert.ok(!result.nativeImportWarnings.some(w=>w.includes('layer_heights_profile')));assert.deepEqual(importNative3MF(exportNative3MF({...project,activePlateId:'plate-2'},{allPlates:false})).objects[0].native.layerHeightProfile,profile);
 const moved=updateNativePart(project.objects,'hole',{groupId:'blue'});assert.deepEqual(moved.find(o=>o.id==='hole').native.layerHeightProfile,[]);const split=updateNativePart(project.objects,'modifier',{groupId:'new',partType:'normal_part'});assert.deepEqual(split.find(o=>o.id==='modifier').native.layerHeightProfile,profile);
});
test('server preserves profiles and rejects stale geometry/first-layer changes instead of native silent fallback',async()=>{
 const service=createNativeProjectService({catalog:fixtureCatalog(base)}),project={...structuredClone(base),nativeSettings:settings};project.objects=updateLayerHeightProfile(project.objects,project.selectedId,profile,settings);const prepared=await service.prepare({project,useEmbeddedSettings:true});assert.deepEqual(importNative3MF(prepared.bytes).objects[0].native.layerHeightProfile,profile);
 const scaled=structuredClone(project);scaled.objects[0].scale[2]=2;scaled.objects[0].position[2]+=10;await assert.rejects(service.prepare({project:scaled,useEmbeddedSettings:true}),/Reset or regenerate/);const changed=structuredClone(project);changed.nativeSettings.initial_layer_print_height='.24';await assert.rejects(service.prepare({project:changed,useEmbeddedSettings:true}),/first height/);
 const files=extractBoundedZip(fixture);files[LAYER_PROFILE_PATH]=strToU8(writeLayerHeightProfiles([[],profile]));assert.throws(()=>importNative3MF(zipSync(files)),/missing native object/);
});
