import test from 'node:test';import assert from 'node:assert/strict';
import { createCalibrationPlan, applyCalibrationGcode, applyCalibrationOverrides } from '../../shared/calibration.js';
import { vfaRequestedSpeed, vfaLayerSpeed } from '../../shared/vfa-calibration.js';
const selection=()=>({printer:{name:'Fixture',printer_technology:'FFF',gcode_flavor:'marlin2',nozzle_diameter:['.4'],printable_height:'300'},process:{layer_height:'.2',initial_layer_speed:'20',slow_down_layers:'5',small_perimeter_threshold:'0'},filament:{filament_max_volumetric_speed:['12']}});
const request={mode:'vfa',start:40,end:80,step:20};
test('VFA follows native model, height, spiral settings and preserves selected volumetric limits',()=>{
 const native=selection(),plan=createCalibrationPlan(request,native),applied=applyCalibrationOverrides(native,plan);
 assert.deepEqual(plan.model,{resource:'vfa/vfa.drc',minZ:0,maxZ:15,scale:1});assert.equal(plan.overrides.process.outer_wall_speed,'100');assert.equal(plan.overrides.process.spiral_mode,'1');assert.equal(plan.overrides.process.bottom_shell_layers,'1');assert.deepEqual(applied.filament.filament_max_volumetric_speed,['12']);assert.deepEqual(applied.filament.slow_down_layer_time,['0']);assert.equal(plan.overrides.process.spiral_mode_smooth,undefined);
 assert.deepEqual([.2,4.99,5,10,15].map(z=>vfaRequestedSpeed(plan,z)),[40,40,60,80,100]);
});
test('VFA honors native first layer, gradual slowdown and whole-number speed rounding',()=>{
 const plan=createCalibrationPlan(request,selection());assert.deepEqual([0,1,2,3,4,5].map(i=>vfaLayerSpeed(plan,i,.2+i*.2)),[20,24,28,32,36,40]);
 const slow=createCalibrationPlan({...request,start:15,end:25,step:5},selection());assert.equal(vfaLayerSpeed(slow,1,.4),15,'native ramp never increases a slower requested speed');
 assert.equal(vfaRequestedSpeed(createCalibrationPlan({mode:'vfa',start:40.4,end:42.4,step:1},selection()),5),41);
});
test('VFA rejects invalid ranges, oversized towers and speed-dependent unsupported native settings',()=>{
 for(const change of [{start:10},{end:1001},{step:0},{step:.001},{start:NaN},{end:40},{start:40.1,end:40.3,step:.1}])assert.throws(()=>createCalibrationPlan({...request,...change},selection()));
 for(const change of [{max_volumetric_extrusion_rate_slope:'1'},{raft_layers:'1'},{small_perimeter_threshold:'10'}]){const native=selection();Object.assign(native.process,change);assert.throws(()=>createCalibrationPlan(request,native));}
 const native=selection();native.filament.enable_pressure_advance=['1'];native.filament.adaptive_pressure_advance=['1'];assert.throws(()=>createCalibrationPlan(request,native),/adaptive pressure/);
});
function fixture(relative=true){const pre=relative?'M83':'M82';return `; generated by OrcaSlicer 2.4.2\n; total layer number: 3\n${pre}\n`+[.2,5,10].map((z,i)=>`;LAYER_CHANGE\n;Z:${z}\n;_SET_FAN_SPEED_CHANGING_LAYER\n; printing object VFA id:0 copy 0\n;TYPE:Outer wall\nG92 E0\nG1 F6000\nG1 X10 Y20 E1\nG1 X20 E${relative?'1':'2'}\nG1 X25\nG1 X30 F1200 E${relative?'1':'3'} ; native flow cap\nG1 E${relative?'-.5':'2.5'} F1800\nG1 X40 F9000\n; stop printing object VFA id:0 copy 0\n`).join('')+`; total layers count = 3\n; outer_wall_speed = 100\n; initial_layer_speed = 20\n; slow_down_layers = 5\n; spiral_mode = 1\n; enable_overhang_speed = 0\n; slow_down_layer_time = 0\n; max_volumetric_extrusion_rate_slope = 0\n; small_perimeter_threshold = 0\n; estimated printing time (normal mode) = 3m\nM73 P3 R5\n; filament used [g] = 1.2\n`;}
const movesWithoutFeed=text=>text.split('\n').filter(line=>/^G[0123]\b/.test(line)&&!/^G1 F\d+(?:\.\d+)?$/.test(line)).map(line=>line.split(';')[0].replace(/\sF[-+\d.]+/g,'').trim());
for(const relative of [true,false])test(`VFA changes only outer-wall feedrates with ${relative?'relative':'absolute'} extrusion and preserves modal travel`,()=>{
 const raw=fixture(relative),plan=createCalibrationPlan(request,selection()),result=applyCalibrationGcode(raw,plan);assert.deepEqual(movesWithoutFeed(result.gcode),movesWithoutFeed(raw));
 assert.match(result.gcode,/G1 X10 Y20 E1 F1680/);assert.match(result.gcode,/G1 X30 F1200 E\d ; native flow cap/);assert.match(result.gcode,/G1 X25 F6000/);assert.match(result.gcode,/G1 X40 F9000/);assert.match(result.gcode,/G1 E(?:-.5|2.5) F1800/);assert.doesNotMatch(result.gcode,/M73|estimated printing time/);assert.match(result.gcode,/filament used \[g\] = 1.2/);assert.ok(result.summary.changedMoves>0);assert.ok(result.summary.cappedMoves>0);assert.equal(result.summary.timeEstimate,'unavailable-after-speed-calibration');
});
test('VFA rejects mismatched native baselines, missing object boundaries and unit changes',()=>{
 const plan=createCalibrationPlan(request,selection());for(const raw of [fixture().replace('outer_wall_speed = 100','outer_wall_speed = 80'),fixture().replaceAll('; printing object','; missing object'),fixture().replace('M83','G20\nM83')])assert.throws(()=>applyCalibrationGcode(raw,plan));
});
test('Bambu native role and layer tags retain identical scheduled moves without rewriting the tags',()=>{
 const plan=createCalibrationPlan(request,selection()),raw=fixture(),bambu=raw.replaceAll(';LAYER_CHANGE','; CHANGE_LAYER').replaceAll(';Z:','; Z_HEIGHT: ').replaceAll(';TYPE:','; FEATURE: '),expected=applyCalibrationGcode(raw,plan),actual=applyCalibrationGcode(bambu,plan);
 assert.deepEqual(actual.summary,expected.summary);assert.deepEqual(actual.gcode.split('\n').filter(line=>/^[GM]\d/.test(line)),expected.gcode.split('\n').filter(line=>/^[GM]\d/.test(line)));assert.ok(actual.gcode.includes('; FEATURE: Outer wall'));assert.ok(!actual.gcode.includes(';TYPE:'));
});
